### ISSUE TITLE
[APP SUBMITTED]: index() got an unexpected keyword argument 'cmd'

### ISSUE THREAD

**Issue by MYLE-01** [SickRage/SickRage#1194]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-79-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dd619c630445a56dc79ec670faaf45752aae6cf0
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [dd619c6] Failed doing webui callback: Traceback (most recent call last):
  File "/home/stephan/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument 'cmd'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by MYLE-01** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-79-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dd619c630445a56dc79ec670faaf45752aae6cf0
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [dd619c6] Failed doing webui callback: Traceback (most recent call last):
  File "/home/stephan/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument 'cmd'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
