### ISSUE TITLE
Error after update with web_root configured

### ISSUE THREAD

**Issue by Maximumi** [SickRage/SickRage#1217]
**INFO**
Branch/Commit: SickRage/SickRage@6116245
OS: Debian Jessie Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux
What you did: Open home page after update
What happened: Errors
What you expected: The home page :)

**ERRORS**

Traceback (most recent call last):
  File "/opt/sickrage/lib/tornado/web.py", line 1390, in _execute
    result = self.prepare()
  File "/opt/sickrage/lib/tornado/web.py", line 2103, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found

**DEBUG LOG**
2016-03-23 20:55:19 DEBUG    CHECKVERSION :: Executing git config remote.origin.url https://github.com/SickRage/SickRage.git with your shell in /opt/sickrage
2016-03-23 20:55:19 DEBUG    CHECKVERSION :: git config remote.origin.url https://github.com/SickRage/SickRage.git : returned successful
2016-03-23 20:55:19 DEBUG    CHECKVERSION :: Executing git fetch origin with your shell in /opt/sickrage
2016-03-23 20:55:20 DEBUG    CHECKVERSION :: git fetch origin : returned successful
2016-03-23 20:55:20 DEBUG    CHECKVERSION :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /opt/sickrage
2016-03-23 20:55:20 DEBUG    CHECKVERSION :: git rev-parse --verify --quiet "@{upstream}" : returned successful
2016-03-23 20:55:20 DEBUG    CHECKVERSION :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /opt/sickrage
2016-03-23 20:55:20 DEBUG    CHECKVERSION :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2016-03-23 20:55:20 DEBUG    CHECKVERSION :: cur_commit = 6116245c03c8627b33c5cdad7de100e8b0f93529, newest_commit = 6116245c03c8627b33c5cdad7de100e8b0f93529, num_commits_behind = 0, num_commits_ahead = 0
2016-03-23 20:55:20 DEBUG    CHECKVERSION :: check_for_new_news: Checking GitHub for latest news.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
#1210

**Comment by Mr-Chaos** [comment]
Cancelling a rename doesn't honor the web_root setting...

**Comment by miigotu** [comment]
@Mr-Chaos will be fixed in my next PR, thanks.

**Comment by Mr-Chaos** [comment]
Thank you.

**Comment by Mr-Chaos** [comment]
Sorry but it is still a little broken. The latest code fixed the web_root inclusion issue but introduced an extra trailing double quote on the return URL that results in this error:

Invalid show ID: 000000"

Thanks.

**Comment by miigotu** [comment]
Fixed, it was a missing " actually xD
