### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/opt/sickrage/cache/mako/tmpCD_fVH'

### ISSUE THREAD

**Issue by limerick11** [SickRage/SickRage#1226]
### INFO
Python Version: **2.7.9 (default, Mar  8 2015, 00:52:26) [GCC 4.9.2]**
Operating System: **Linux-4.1.13-v7+-armv7l-with-debian-8.0**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@1abc630b78dbf54b63f5699dc0eeaaf7a6ba4443
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [1abc630] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 698, in index
    t = PageTemplate(rh=self, filename="home.mako")
  File "/opt/sickrage/sickbeard/webserve.py", line 128, in __init__
    self.template = lookup.get_template(filename)
  File "/opt/sickrage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/opt/sickrage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/opt/sickrage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/opt/sickrage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/opt/sickrage/lib/mako/template.py", line 703, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "/usr/lib/python2.7/tempfile.py", line 308, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/opt/sickrage/cache/mako/tmpCD_fVH'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
