### ISSUE TITLE
Exception in thread SHOWQUEUE-ADD

### ISSUE THREAD

**Issue by stramel** [SickRage/SickRage#1229]
### Exception while adding existing shows

The following error seems to happen when trying to add any number of existing shows. The steps below show 1 show being added but it fails with multiple as well. 

**Branch**: Master
**Commit**: 1abc630b78dbf54b63f5699dc0eeaaf7a6ba4443
**Version**: 2016.03.23-1
**Python Version**: 2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]
**OS**: Linux-4.2.0-34-generic-x86_64-with-Ubuntu-14.04-trusty

**What you did**: I attempted to add an existing show to my show list (currently empty).
  1. Shows > Add Shows
  2. Add Existing Shows
  3. Unselect All
  4. Check the first show in the list
  5. Submit

**What happened**: Show appears as loading then disappears

**What you expected**: Show to appear loading and then populate with show information

**Logs**: Couldn't see anything in the logs listed in the app. However, I am running through docker and can attach to the log file. I see the following error every time that I try to add an existing show.

```
Exception in thread SHOWQUEUE-ADD:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/app/sickrage/sickbeard/show_queue.py", line 279, in run
    assert isinstance(self.showDir, unicode)
AssertionError
```

Note: I have not tried adding a new show that does not currently exist.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
