### ISSUE TITLE
DanishBit Intergration Broke

### ISSUE THREAD

**Issue by jacobmmp** [SickRage/SickRage#1235]
This is a new error keeps trowing this error on everything.
```
AAUnicodeDecodeError: 'utf8' codec can't decode byte 0x8f in position 1887: invalid start byte
AA    return codecs.utf_8_decode(input, errors, True)
AA  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
AA    logger.log('Torrent bencoded data: {0}'.format(result.content), logger.DEBUG)
AA  File "/home/**********/.sickrage/sickbeard/clients/generic.py", line 180, in _get_torrent_hash
AA    result = self._get_torrent_hash(result)
AA  File "/home/**********/.sickrage/sickbeard/clients/generic.py", line 217, in sendTORRENT
AATraceback (most recent call last):
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Need the rest of the log.
```
                logger.log('Unable to bdecode torrent', logger.ERROR)
                logger.log('Error is: {0}'.format(error), logger.DEBUG)
                logger.log('Torrent bencoded data: {0}'.format(result.content), logger.DEBUG)
```

**Comment by miigotu** [comment]
Here is the full error:

```
02:27:20 ERROR::SEARCHQUEUE-MANUAL-257655 :: [53f7264] Unable to bdecode torrent
Traceback (most recent call last):
  File "/home/******/Projects/SickRage/sickbeard/clients/generic.py", line 176, in _get_torrent_hash
    torrent_bdecode = bencoder.decode(result.content)
  File "/home/******/Projects/SickRage/lib/bencode/__init__.py", line 228, in decode
    return _decode(becode_string)
  File "/home/******/Projects/SickRage/lib/bencode/__init__.py", line 198, in _decode
    for token in src:  # look for more tokens
  File "/home/******/Projects/SickRage/lib/bencode/__init__.py", line 147, in _tokenizer
    s = m.group(m.lastindex)  # http://stackoverflow.com/questions/22489243/re-in-python-lastindex-attribute
AttributeError: 'NoneType' object has no attribute 'group'
02:27:20 DEBUG::SEARCHQUEUE-MANUAL-257655 :: Error is: 'NoneType' object has no attribute 'group'
02:27:20 ERROR::SEARCHQUEUE-MANUAL-257655 :: [53f7264] uTorrent: Failed Sending Torrent
Traceback (most recent call last):
  File "/home/******/Projects/SickRage/sickbeard/clients/generic.py", line 217, in sendTORRENT
    result = self._get_torrent_hash(result)
  File "/home/******/Projects/SickRage/sickbeard/clients/generic.py", line 180, in _get_torrent_hash
    logger.log('Torrent bencoded data: {0}'.format(result.content), logger.DEBUG)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x97 in position 5553: invalid start byte
02:27:20 DEBUG::SEARCHQUEUE-MANUAL-257655 :: Traceback (most recent call last):
  File "/home/******/Projects/SickRage/sickbeard/search_queue.py", line 184, in run
    self.success = search.snatchEpisode(searchResult[0])
  File "/home/******/Projects/SickRage/sickbeard/search.py", line 141, in snatchEpisode
    dlResult = client.sendTORRENT(result)
  File "/home/******/Projects/SickRage/sickbeard/clients/generic.py", line 248, in sendTORRENT
    logger.log('{0}: Exception raised when sending torrent: {1}. Error {2}'.format(self.name, result, error), logger.DEBUG)
  File "/home/******/Projects/SickRage/sickbeard/classes.py", line 90, in __str__
    my_string += u' {0}\n'.format(ep)
  File "/home/******/Projects/SickRage/sickbeard/tv.py", line 1806, in __str__
    toReturn += "{0!r} - S{1:2!r}E{2:2!r} - {3!r}\n".format(self.show.name, self.season, self.episode, self.name)
ValueError: Invalid conversion specification
```
