### ISSUE TITLE
[APP SUBMITTED]: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

### ISSUE THREAD

**Issue by arathas** [SickRage/SickRage#1245]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@42c95761d5a7acf821a610b0da80335a9c281bce
No Log available with ERRORS:
### ERROR
```
Thread-20 :: [42c9576] Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\logger.py", line 344, in submit_errors
    reports = git.get_organization(gh_org).get_repo(gh_repo).get_issues(state='all')
  File "C:\SickRage\SickRage\lib\github\MainClass.py", line 188, in get_organization
    "/orgs/" + login
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by piluc88** [comment]
### INFO
Python Version: **2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-34-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@75042d8c406bb4356d88b6b67a73c847a56ce3f3
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [75042d8] Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/logger.py", line 350, in submit_errors
    repo = sickbeard.gh.get_organization(sickbeard.GIT_ORG).get_repo(sickbeard.GIT_REPO)
  File "/opt/sickrage/lib/github/MainClass.py", line 188, in get_organization
    "/orgs/" + login
  File "/opt/sickrage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/opt/sickrage/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by deersew** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@8bf53e8d03dc2b5bb946123dbaef2afb8667730c
No Log available with ERRORS:
### ERROR
```
Thread-24 :: [8bf53e8] Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\logger.py", line 349, in submit_errors
    repo = sickbeard.gh.get_organization(sickbeard.GIT_ORG).get_repo(sickbeard.GIT_REPO)
  File "C:\SickRage\SickRage\lib\github\MainClass.py", line 188, in get_organization
    "/orgs/" + login
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by 03397** [comment]
### INFO
Python Version: **2.7.11 (default, Feb 23 2016, 08:27:03) [GCC 4.8.5]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@8bf53e8d03dc2b5bb946123dbaef2afb8667730c
No Log available with ERRORS:
### ERROR
```
Thread-75 :: [8bf53e8] Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/logger.py", line 349, in submit_errors
    repo = sickbeard.gh.get_organization(sickbeard.GIT_ORG).get_repo(sickbeard.GIT_REPO)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/MainClass.py", line 188, in get_organization
    "/orgs/" + login
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by 03397** [comment]
### INFO
Python Version: **2.7.11 (default, Feb 23 2016, 08:27:03) [GCC 4.8.5]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@8bf53e8d03dc2b5bb946123dbaef2afb8667730c
No Log available with ERRORS:
### ERROR
```
Thread-76 :: [8bf53e8] Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/logger.py", line 349, in submit_errors
    repo = sickbeard.gh.get_organization(sickbeard.GIT_ORG).get_repo(sickbeard.GIT_REPO)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/MainClass.py", line 188, in get_organization
    "/orgs/" + login
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by stevles** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@e216414dc835ef5c995154d25a4b3f4b2851f0e9
No Log available with ERRORS:
### ERROR
```
Thread-30 :: [e216414] Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\logger.py", line 356, in submit_errors
    repo = sickbeard.gh.get_organization(sickbeard.GIT_ORG).get_repo(sickbeard.GIT_REPO)
  File "C:\SickRage\SickRage\lib\github\MainClass.py", line 188, in get_organization
    "/orgs/" + login
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Piiixz** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@797ce21e86fa97adbd03190593419807f9bfaa46
No Log available with ERRORS:
### ERROR
```
Thread-21 :: [797ce21] Traceback (most recent call last):
  File "C:\SickRage\sickbeard\logger.py", line 356, in submit_errors
    repo = sickbeard.gh.get_organization(sickbeard.GIT_ORG).get_repo(sickbeard.GIT_REPO)
  File "C:\SickRage\lib\github\MainClass.py", line 188, in get_organization
    "/orgs/" + login
  File "C:\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\lib\github\Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
