### ISSUE TITLE
[APP SUBMITTED]: bad character range

### ISSUE THREAD

**Issue by mrbipbip** [SickRage/SickRage#1249]
### INFO
Python Version: **2.7.9 (default, Mar  8 2015, 00:52:26) [GCC 4.9.2]**
Operating System: **Linux-4.1.19-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1847f03608e96cf80b9999233811ff58021ddb3e
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [1847f03] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2290, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/opt/sickrage/sickbeard/processTV.py", line 154, in func_wrapper
    ret = func(*args, **kargs)
  File "/opt/sickrage/sickbeard/processTV.py", line 295, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/opt/sickrage/sickbeard/processTV.py", line 572, in process_media
    result.result = processor.process()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 1159, in process
    sickbeard.USE_SUBTITLES and ep_obj.show.subtitles)
  File "/opt/sickrage/sickbeard/postProcessor.py", line 405, in _move
    subtitles=subtitles)
  File "/opt/sickrage/sickbeard/postProcessor.py", line 328, in _combined_file_operation
    file_list = file_list + self.list_associated_files(file_path)
  File "/opt/sickrage/sickbeard/postProcessor.py", line 201, in list_associated_files
    checklist = glob.glob(ek(os.path.join, ek(os.path.dirname, globbable_file_path), '*'))
  File "/usr/lib/python2.7/glob.py", line 27, in glob
    return list(iglob(pathname))
  File "/usr/lib/python2.7/glob.py", line 63, in iglob
    for dirname in dirs:
  File "/usr/lib/python2.7/glob.py", line 63, in iglob
    for dirname in dirs:
  File "/usr/lib/python2.7/glob.py", line 64, in iglob
    for name in glob_in_dir(dirname, basename):
  File "/usr/lib/python2.7/glob.py", line 83, in glob1
    return fnmatch.filter(names, pattern)
  File "/usr/lib/python2.7/fnmatch.py", line 54, in filter
    _cache[pat] = re.compile(res)
  File "/usr/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
error: bad character range

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by mrbipbip** [comment]
This is the debug los:
https://gist.github.com/mrbipbip/28a3a22383207b03cb66

hope it's help.

**Comment by zpatten** [comment]
:+1: had this happen as well.

**Comment by zpatten** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-32-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1847f03608e96cf80b9999233811ff58021ddb3e
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [1847f03] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2290, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/opt/sickrage/sickbeard/processTV.py", line 154, in func_wrapper
    ret = func(*args, **kargs)
  File "/opt/sickrage/sickbeard/processTV.py", line 295, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/opt/sickrage/sickbeard/processTV.py", line 572, in process_media
    result.result = processor.process()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 1159, in process
    sickbeard.USE_SUBTITLES and ep_obj.show.subtitles)
  File "/opt/sickrage/sickbeard/postProcessor.py", line 405, in _move
    subtitles=subtitles)
  File "/opt/sickrage/sickbeard/postProcessor.py", line 328, in _combined_file_operation
    file_list = file_list + self.list_associated_files(file_path)
  File "/opt/sickrage/sickbeard/postProcessor.py", line 201, in list_associated_files
    checklist = glob.glob(ek(os.path.join, ek(os.path.dirname, globbable_file_path), '*'))
  File "/usr/lib/python2.7/glob.py", line 27, in glob
    return list(iglob(pathname))
  File "/usr/lib/python2.7/glob.py", line 58, in iglob
    for dirname in dirs:
  File "/usr/lib/python2.7/glob.py", line 59, in iglob
    for name in glob_in_dir(dirname, basename):
  File "/usr/lib/python2.7/glob.py", line 78, in glob1
    return fnmatch.filter(names, pattern)
  File "/usr/lib/python2.7/fnmatch.py", line 54, in filter
    _cache[pat] = re.compile(res)
  File "/usr/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 244, in _compile
    raise error, v # invalid expression
error: bad character range

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by zpatten** [comment]
Debug Log: https://gist.github.com/zpatten/7adbb27382e76a818b94

**Comment by zpatten** [comment]
Also, noticing a fair amount of the `Post processor is already running` messages since the recent update.

```
root@pvr:/var/opt/sickrage/Logs# grep 'Post processor is already running' sickrage.log  | wc -l
16
root@pvr:/var/opt/sickrage/Logs# grep 'Post processor is already running' sickrage.log.1  | wc -l
4
root@pvr:/var/opt/sickrage/Logs# grep 'Post processor is already running' sickrage.log.2  | wc -l
0
root@pvr:/var/opt/sickrage/Logs# grep 'Post processor is already running' sickrage.log.3  | wc -l
0
root@pvr:/var/opt/sickrage/Logs# grep 'Post processor is already running' sickrage.log.4  | wc -l
0
root@pvr:/var/opt/sickrage/Logs# grep 'Post processor is already running' sickrage.log.5  | wc -l
0
```
Nothing changed in my setup/configuration; as mention just started after the recent update.

**Comment by zpatten** [comment]
One last note; my post-processing is triggered via clinton-hall's `nzbToMedia` scripts and does not run automatically via SickRage.

**Comment by gturner30** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1847f03608e96cf80b9999233811ff58021ddb3e
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [1847f03] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 1964, in doRename
    root_ep_obj.rename()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2455, in rename
    self.location, base_name_only=True, subfolders=True)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 195, in list_associated_files
    filelist = recursive_glob(ek(os.path.dirname, globbable_file_path), base_name + '*')
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 166, in recursive_glob
    goodfiles = fnmatch.filter(files, pattern)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/fnmatch.py", line 54, in filter
    _cache[pat] = re.compile(res)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
error: bad character range

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
@zpatten 'Post processor is already running' means exactly that, it is only allowed to be run once at a time, because if it overlaps it creates havoc.

**Comment by duramato** [comment]
@miigotu If someone has auto PP and nzbtomedia, sab will try to execute the script but it will fail and wont execute again

**Comment by miigotu** [comment]
Then they shouldnt have both enabled.

**Comment by duramato** [comment]
You can use auto PP for torrents and nzbtomedia for usenet

**Comment by miigotu** [comment]
That doesnt change the fact that if the PP is running more than once at a time it crashes.

**Comment by duramato** [comment]
Crashes if its PPing the same file, the api PP starts a diferent thread

**Comment by miigotu** [comment]
Fact of the matter is, the singleton decorator was added as a stop-gap until the situation could be fixed better, and this discussion does not belong in this thread at all since it doesnt pertain to the issue.

I have very little help atm and the PP singleton issue is not a priority. Most users use either NZB OR torrents, and if they use nzbtomedia AND both nzb and torrents, they generally use nzbtomedia for both.

Again, this is the wrong place for this discussion.

**Comment by zpatten** [comment]
@miigotu Yes, I know what the PP message means.  I only mentioned it as it started appearing after that update and was trying to be helpful by mentioning it; I was not seeking help or support for the PP issue.

It just seemed suspect that it started showing up in my logs at the same time the reported error started.  So again, was just trying to supply as much information as possible since both those errors starting showing up in my logs at the same time.

Since the original error has stopped so have the PP messages.  Maybe it was coincidence; maybe not; just trying to be thorough.

**Comment by zpatten** [comment]
Not to mention the PP code is in the stack trace which also indicated a possible link to me.

**Comment by mdunham08** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8.1-6.3.9600**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@ad174b0a75eb63c651a46a1499f39215cf51aaa3
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [ad174b0] Exception generated in thread POSTPROCESSER: bad character range
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mdunham08** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8.1-6.3.9600**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@ad174b0a75eb63c651a46a1499f39215cf51aaa3
No Log available with ERRORS:
### ERROR
```
Thread-177 :: [ad174b0] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2290, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "C:\SickRage\sickbeard\processTV.py", line 295, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\sickbeard\processTV.py", line 575, in process_media
    result.result = processor.process()
  File "C:\SickRage\sickbeard\postProcessor.py", line 1159, in process
    sickbeard.USE_SUBTITLES and ep_obj.show.subtitles)
  File "C:\SickRage\sickbeard\postProcessor.py", line 405, in _move
    subtitles=subtitles)
  File "C:\SickRage\sickbeard\postProcessor.py", line 328, in _combined_file_operation
    file_list = file_list + self.list_associated_files(file_path)
  File "C:\SickRage\sickbeard\postProcessor.py", line 201, in list_associated_files
    checklist = glob.glob(ek(os.path.join, ek(os.path.dirname, globbable_file_path), '*'))
  File "C:\Python27\lib\glob.py", line 27, in glob
    return list(iglob(pathname))
  File "C:\Python27\lib\glob.py", line 63, in iglob
    for dirname in dirs:
  File "C:\Python27\lib\glob.py", line 63, in iglob
    for dirname in dirs:
  File "C:\Python27\lib\glob.py", line 64, in iglob
    for name in glob_in_dir(dirname, basename):
  File "C:\Python27\lib\glob.py", line 83, in glob1
    return fnmatch.filter(names, pattern)
  File "C:\Python27\lib\fnmatch.py", line 56, in filter
    _cache[pat] = re_pat = re.compile(res)
  File "C:\Python27\lib\re.py", line 194, in compile
    return _compile(pattern, flags)
  File "C:\Python27\lib\re.py", line 251, in _compile
    raise error, v # invalid expression
error: bad character range

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by jgrip** [comment]
I reverted this part of commit https://github.com/SickRage/SickRage/commit/d5f274fbeb3c35b39b1977c933b7076f12c46894 and it seems to fix it for me:

`
 def fixGlob(path):
-    path = re.sub(r'\[', '[[]', path)
+    path = re.sub(r'\[b', '[[]', path)
     return re.sub(r'(?<!\[)\]', '[]]', path)`

**Comment by miigotu** [comment]
@jgrip ugh good find. That was a bad search/replace with unicode_literals changes -.-

I will hotfix it now.
