### ISSUE TITLE
Unable to add show codec can't encode character u'\u200b'

### ISSUE THREAD

**Issue by Rouzax** [SickRage/SickRage#1266]
Still can't download the episodes as described in https://github.com/SickRage/sickrage-issues/issues/1370

SickRage Info:	Branch: master
Commit: 1847f03608e96cf80b9999233811ff58021ddb3e
Version: 2016.03.23-1
 Python Version:	2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
 SSL Version:	OpenSSL 1.0.2d 9 Jul 2015
 OS:	Windows-2012ServerR2-6.3.9600
 Locale:	nl_NL.cp1252

```
2016-03-28 12:22:43 DEBUG    SEARCHQUEUE-MANUAL-308582 :: Traceback (most recent call last):
2016-03-28 12:22:43 DEBUG    SEARCHQUEUE-MANUAL-308582 :: formatting pattern: %SN - S%0SE%0E - %EN -> ​The Story of Cats - S01E01 - Wild at Heart
2016-03-28 12:22:43 INFO     SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Performing season pack search for ​The Story of Cats
2016-03-28 12:22:43 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Fallback season pack search initiate
2016-03-28 12:22:43 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Data returned from provider does not contain any torrents
2016-03-28 12:22:43 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: With post data: cata=yes&search=%E2%80%8BThe%2BStory%2Bof%2BCats%2BS01E01&c26=1&jxt=8&jxw=b&c24=1&c2=1&c7=1
2016-03-28 12:22:43 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: POST URL: https://classic.torrentday.com/V3/API/API.php [Status: 200]
2016-03-28 12:22:43 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Search string: ​The Story of Cats S01E01
2016-03-28 12:22:43 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Search Mode: Episode
2016-03-28 12:22:43 INFO     SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Performing episode search for ​The Story of Cats
2016-03-28 12:22:43 INFO     SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Performing season pack search for ​The Story of Cats
2016-03-28 12:22:43 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Fallback season pack search initiate
2016-03-28 12:22:43 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Data returned from provider does not contain any torrents
2016-03-28 12:22:42 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: GET URL: https://iptorrents.eu/t?73=&60=&q=%E2%80%8BThe%20Story%20of%20Cats%20S01E01&qf=#torrents;o=seeders [Status: 200]
2016-03-28 12:22:42 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Search string: ​The Story of Cats S01E01
2016-03-28 12:22:42 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Search Mode: Episode
2016-03-28 12:22:42 INFO     SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Performing episode search for ​The Story of Cats
2016-03-28 12:22:42 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [TorrentDay] :: Last update was too soon, using old cache: 2016-03-28 12:19:00. Updated less then 10 minutes ago
2016-03-28 12:22:42 DEBUG    SEARCHQUEUE-MANUAL-308582 :: [IPTorrents] :: Last update was too soon, using old cache: 2016-03-28 12:18:55. Updated less then 10 minutes ago
2016-03-28 12:22:42 INFO     SEARCHQUEUE-MANUAL-308582 :: Beginning manual search for: [​The Story of Cats - S01E01 - Wild at Heart]
2016-03-28 12:22:42 DEBUG    SEARCHQUEUE-MANUAL-308582 :: formatting pattern: %SN - S%0SE%0E - %EN -> ​The Story of Cats - S01E01 - Wild at Heart
AA
AAUnicodeEncodeError: 'charmap' codec can't encode character u'\u200b' in position 0: character maps to 
AA    return codecs.charmap_encode(input,errors,encoding_table)
AA  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
AA    "Couldn't find a download for {0}".format(self.segment.prettyName()))
AA  File "C:\GitHub\SickRage\sickbeard\search_queue.py", line 191, in run
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Some reason it seems part of one of my commits got lost. I will work on this soon.

**Comment by Rouzax** [comment]
No need, with one of the latest commits it started downloading :)
