### ISSUE TITLE
[APP SUBMITTED]: coercing to Unicode: need string or buffer, int found

### ISSUE THREAD

**Issue by didyouexpectthat** [SickRage/SickRage#1269]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-4.2.8-1-pve-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@a908b34e07d0875b1ea415053b9d3225cfea834d

POSTPROCESS failed in what appears to be a lookup of available space on the destination. I have 11 TB free on the destination. Underlying filesystem is ZFS. See this on fresh restart of SickRage, causing the POSTPROCESS to become inactive and no longer function until restart of SR. 

```
2016-03-28 08:59:59 DEBUG    POSTPROCESSER :: 'Traceback (most recent call last):\n  File "/usr/share/sickrage/sickbeard/scheduler.py", line 106, in run\n    self.action.run(self.force)\n  File "/usr/share/sickrage/sickbeard/auto_postprocessor.py", line 56, in run\n    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)\n  File "/usr/share/sickrage/sickbeard/processTV.py", line 154, in func_wrapper\n    ret = func(*args, **kargs)\n  File "/usr/share/sickrage/sickbeard/processTV.py", line 295, in processDir\n    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)\n  File "/usr/share/sickrage/sickbeard/processTV.py", line 572, in process_media\n    result.result = processor.process()\n  File "/usr/share/sickrage/sickbeard/postProcessor.py", line 1040, in process\n    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps):  # pylint: disable=protected-access\n  File "/usr/share/sickrage/sickbeard/helpers.py", line 1617, in verify_freespace\n    diskfree += ek(os.path.getsize, f.location)\nTypeError: coercing to Unicode: need string or buffer, int found\n'
AATypeError: coercing to Unicode: need string or buffer, int found
AA    diskfree += ek(os.path.getsize, f.location)
AA  File "/usr/share/sickrage/sickbeard/helpers.py", line 1617, in verify_freespace
AA    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps):  # pylint: disable=protected-access
AA  File "/usr/share/sickrage/sickbeard/postProcessor.py", line 1040, in process
AA    result.result = processor.process()
AA  File "/usr/share/sickrage/sickbeard/processTV.py", line 572, in process_media
AA    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
AA  File "/usr/share/sickrage/sickbeard/processTV.py", line 295, in processDir
AA    ret = func(*args, **kargs)
AA  File "/usr/share/sickrage/sickbeard/processTV.py", line 154, in func_wrapper
AA    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)
AA  File "/usr/share/sickrage/sickbeard/auto_postprocessor.py", line 56, in run
AA    self.action.run(self.force)
AA  File "/usr/share/sickrage/sickbeard/scheduler.py", line 106, in run
AATraceback (most recent call last):
2016-03-28 08:59:59 ERROR    POSTPROCESSER :: [a908b34] Exception generated in thread POSTPROCESSER: coercing to Unicode: need string or buffer, int found
2016-03-28 08:59:59 DEBUG    POSTPROCESSER :: Trying to determine free space on destination drive
2016-03-28 08:59:59 INFO     POSTPROCESSER :: This download is marked a priority download so I'm going to replace an existing file if I find one
2016-03-28 08:59:59 DEBUG    POSTPROCESSER :: File /children/Hey Arnold!/s01e06.mkv is larger than /completed/sickrage/Hey.Arnold.S01.DVDRip.x264-DEiMOS/proof-hey.arnold.s01e06.dvdrip.x264-deimos.vob
2016-03-28 08:59:59 DEBUG    POSTPROCESSER :: Is ep a priority download: True
2016-03-28 08:59:59 DEBUG    POSTPROCESSER :: This was manually downloaded but it appears to be better quality than what we have so I'm marking it as priority
2016-03-28 08:59:59 DEBUG    POSTPROCESSER :: Quality of the episode we're processing: SD DVD
2016-03-28 08:59:59 DEBUG    POSTPROCESSER :: Hey.Arnold.S01.DVDRip.x264-DEiMOS looks like it has quality SD DVD, using that
2016-03-28 08:59:59 DEBUG    POSTPROCESSER :: Looking up quality for name Hey.Arnold.S01.DVDRip.x264-DEiMOS, got SD DVD
2016-03-28 08:59:59 DEBUG    POSTPROCESSER :: Checking if /children/Hey Arnold!/s01e06-thumb.jpg exists: True
2016-03-28 08:59:59 DEBUG    POSTPROCESSER :: Checking if /children/Hey Arnold!/s01e06.nfo exists: True
```
### ERROR
```
POSTPROCESSER :: [a908b34] Exception generated in thread POSTPROCESSER: coercing to Unicode: need string or buffer, int found
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by thejrose1984** [comment]
### INFO
Python Version: **2.7.11 (default, Mar 20 2016, 02:22:54) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.3-RELEASE-p31-amd64-64bit-ELF**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@66a138d008cb0f6659cf071ca283bc1f46d3b3f1
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [66a138d] Exception generated in thread POSTPROCESSER: coercing to Unicode: need string or buffer, int found
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by dejh0n** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-4.1.21.x86_64.1-x86_64-with-debian-7.11**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@fe325d68023dc34fc30b451a81157e0dfc01b68e
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [fe325d6] Failed doing webui callback: Traceback (most recent call last):
  File "/apps/sickrage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/apps/sickrage/sickbeard/webserve.py", line 2290, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/apps/sickrage/sickbeard/processTV.py", line 154, in func_wrapper
    ret = func(*args, **kargs)
  File "/apps/sickrage/sickbeard/processTV.py", line 247, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/apps/sickrage/sickbeard/processTV.py", line 572, in process_media
    result.result = processor.process()
  File "/apps/sickrage/sickbeard/postProcessor.py", line 1040, in process
    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps):  # pylint: disable=protected-access
  File "/apps/sickrage/sickbeard/helpers.py", line 1617, in verify_freespace
    diskfree += ek(os.path.getsize, f.location)
TypeError: coercing to Unicode: need string or buffer, int found

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by dejh0n** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-4.1.21.x86_64.1-x86_64-with-debian-7.11**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@fe325d68023dc34fc30b451a81157e0dfc01b68e
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [fe325d6] Failed doing webui callback: Traceback (most recent call last):
  File "/apps/sickrage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/apps/sickrage/sickbeard/webserve.py", line 2290, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/apps/sickrage/sickbeard/processTV.py", line 154, in func_wrapper
    ret = func(*args, **kargs)
  File "/apps/sickrage/sickbeard/processTV.py", line 247, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/apps/sickrage/sickbeard/processTV.py", line 572, in process_media
    result.result = processor.process()
  File "/apps/sickrage/sickbeard/postProcessor.py", line 1040, in process
    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps):  # pylint: disable=protected-access
  File "/apps/sickrage/sickbeard/helpers.py", line 1617, in verify_freespace
    diskfree += ek(os.path.getsize, f.location)
TypeError: coercing to Unicode: need string or buffer, int found

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by nakyl** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **develop**
Commit: SickRage/SickRage@528239f274f5d8d754e3cb6a8c8e5d7e114af771
No Log available with ERRORS:
### ERROR
```
Thread-27 :: [528239f] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 601, in sickrage_background
    if sickbeard.SICKRAGE_BACKGROUND_PATH and ek(os.path.isfile, sickbeard.SICKRAGE_BACKGROUND_PATH):
  File "C:\SickRage\SickRage\sickrage\helper\encoding.py", line 38, in ek
    result = function(*args, **kwargs)
  File "C:\SickRage\Python\lib\genericpath.py", line 37, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, int found

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by nakyl** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **develop**
Commit: SickRage/SickRage@528239f274f5d8d754e3cb6a8c8e5d7e114af771
No Log available with ERRORS:
### ERROR
```
Thread-31 :: [528239f] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 601, in sickrage_background
    if sickbeard.SICKRAGE_BACKGROUND_PATH and ek(os.path.isfile, sickbeard.SICKRAGE_BACKGROUND_PATH):
  File "C:\SickRage\SickRage\sickrage\helper\encoding.py", line 38, in ek
    result = function(*args, **kwargs)
  File "C:\SickRage\Python\lib\genericpath.py", line 37, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, int found

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by nakyl** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **develop**
Commit: SickRage/SickRage@528239f274f5d8d754e3cb6a8c8e5d7e114af771
No Log available with ERRORS:
### ERROR
```
Thread-24 :: [528239f] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 601, in sickrage_background
    if sickbeard.SICKRAGE_BACKGROUND_PATH and ek(os.path.isfile, sickbeard.SICKRAGE_BACKGROUND_PATH):
  File "C:\SickRage\SickRage\sickrage\helper\encoding.py", line 38, in ek
    result = function(*args, **kwargs)
  File "C:\SickRage\Python\lib\genericpath.py", line 37, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, int found

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by nakyl** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **develop**
Commit: SickRage/SickRage@528239f274f5d8d754e3cb6a8c8e5d7e114af771
No Log available with ERRORS:
### ERROR
```
Thread-29 :: [528239f] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 601, in sickrage_background
    if sickbeard.SICKRAGE_BACKGROUND_PATH and ek(os.path.isfile, sickbeard.SICKRAGE_BACKGROUND_PATH):
  File "C:\SickRage\SickRage\sickrage\helper\encoding.py", line 38, in ek
    result = function(*args, **kwargs)
  File "C:\SickRage\Python\lib\genericpath.py", line 37, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, int found

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
