### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/opt/sickrage/cache/mako/tmpjoz6SO'

### ISSUE THREAD

**Issue by babblings** [SickRage/SickRage#1276]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@ebcffac5fd575a408778cdc14773616716bac98a
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [ebcffac] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1421, in editShow
    t = PageTemplate(rh=self, filename="editShow.mako")
  File "/opt/sickrage/sickbeard/webserve.py", line 128, in __init__
    self.template = lookup.get_template(filename)
  File "/opt/sickrage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/opt/sickrage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/opt/sickrage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/opt/sickrage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/opt/sickrage/lib/mako/template.py", line 703, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "/usr/lib/python2.7/tempfile.py", line 308, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/opt/sickrage/cache/mako/tmpjoz6SO'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Dont delete cache/mako while SickRage is running.

**Comment by babblings** [comment]
Thanks.

It was just after i had done a pull on master from git and restarted the
app. Seeing the error count rise just after an update nakes ne a bit hinky.

Rob
