### ISSUE TITLE
Error when traktchecker tries to sync

### ISSUE THREAD

**Issue by JulienDatour** [SickRage/SickRage#1287]
Hi,

I cannot sync my trakt watchlist anymore. SR seems to fail when trying to remove show.

Thank you for your help and your awesome job with SickRage

Branch: master
Commit: 78bcf673c8c64b3f1f6a5d4cb16aa5a301cdfa09
OS: Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Ubuntu-14.04-trusty
What you did: enabled trakt notifications
What happened: no more sync
What you expected: SR adds my watchlist shows
Logs:
```
2016-03-29 13:10:54 DEBUG    TRAKTCHECKER :: COLLECTION::REMOVE::FINISH - Look for Episodes to Remove From Trakt Collection
2016-03-29 13:10:54 DEBUG    TRAKTCHECKER :: COLLECTION::REMOVE::START - Look for Episodes to Remove From Trakt Collection
2016-03-29 13:10:54 DEBUG    TRAKTCHECKER :: COLLECTION::ADD::FINISH - Look for Episodes to Add to Trakt Collection
2016-03-29 13:10:54 DEBUG    TRAKTCHECKER :: COLLECTION::ADD::START - Look for Episodes to Add to Trakt Collection
2016-03-29 13:10:53 DEBUG    TRAKTCHECKER :: Getting Show Collection
2016-03-29 13:10:53 DEBUG    TRAKTCHECKER :: Sync SickRage with Trakt Collection
AA
AATypeError: cannot concatenate 'str' and 'NoneType' objects
AA    progress = self.trakt_api.traktRequest("shows/" + show.imdbid + "/progress/watched") or []
AA  File "/opt/********/sickbeard/traktChecker.py", line 362, in removeShowFromSickRage
AA    self.removeShowFromSickRage()
AA  File "/opt/********/sickbeard/traktChecker.py", line 250, in syncWatchlist
AA    self.syncWatchlist()
AA  File "/opt/********/sickbeard/traktChecker.py", line 85, in run
2016-03-29 13:10:53 DEBUG    TRAKTCHECKER :: Traceback (most recent call last):
2016-03-29 13:10:53 DEBUG    TRAKTCHECKER :: SHOW_SICKRAGE::REMOVE::START - Look for Shows to remove from SickRage
2016-03-29 13:10:53 DEBUG    TRAKTCHECKER :: Sync SickRage with Trakt Watchlist
2016-03-29 13:10:53 DEBUG    TRAKTCHECKER :: Starting new thread: TRAKTCHECKER
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Can you try forcing a full update on all shows? You have a show that does not have it's imdb id set and it is choking. If that doesnt fix it I can add in some wizardry

**Comment by JulienDatour** [comment]
Thank you for your reply.

> Can you try forcing a full update on all shows? You have a show that does not have it's imdb id set and it is choking. If that doesnt fix it I can add in some wizardry

I did that but same problem. 

I noticed shows like Ajin(http://www.imdb.com/title/tt5537534/) or Falling skies(http://www.imdb.com/title/tt1462059/) do not have the imdb tag when I go to serie detail. Tried to refresh them one by one but still no success.

**Comment by miigotu** [comment]
Yeah those series dont have their imdb id linked on tvdb. Trying to come up with a solution.

**Comment by JulienDatour** [comment]
Ok thank you ! 
Added IMDB id on TVDB by the way

**Comment by miigotu** [comment]
After the imdb id is on tvdb, forcing a full refresh on the show should make the imdb rating/icon show on the show page and your error with trakt will go away.

**Comment by JulienDatour** [comment]
That worked for one show, not for others. Maybe cache / refresh problem. I will try later.
