### ISSUE TITLE
[APP SUBMITTED]: Command has timed out

### ISSUE THREAD

**Issue by arathas** [SickRage/SickRage#1292]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@ad174b0a75eb63c651a46a1499f39215cf51aaa3
No Log available with ERRORS:
### ERROR
```
Thread-24 :: [ad174b0] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 2196, in fetch_releasegroups
    groups = anime.get_groups()
  File "C:\SickRage\SickRage\lib\adba\aniDBAbstracter.py", line 171, in get_groups
    self.rawData = self.aniDB.groupstatus(aid=self.aid)
  File "C:\SickRage\SickRage\lib\adba\__init__.py", line 581, in groupstatus
    return self.handle(GroupstatusCommand(aid, state), callback)
  File "C:\SickRage\SickRage\lib\adba\__init__.py", line 127, in handle
    raise AniDBCommandTimeoutError("Command has timed out")
AniDBCommandTimeoutError: Command has timed out

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Anidb is slow. It happens.

**Comment by pct00** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [a760263] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 2402, in fetch_releasegroups
    groups = anime.get_groups()
  File "C:\SickRage\SickRage\lib\adba\aniDBAbstracter.py", line 171, in get_groups
    self.rawData = self.aniDB.groupstatus(aid=self.aid)
  File "C:\SickRage\SickRage\lib\adba\__init__.py", line 581, in groupstatus
    return self.handle(GroupstatusCommand(aid, state), callback)
  File "C:\SickRage\SickRage\lib\adba\__init__.py", line 127, in handle
    raise AniDBCommandTimeoutError("Command has timed out")
AniDBCommandTimeoutError: Command has timed out

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
