### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/opt/etc/sickrage/cache/mako/tmp4BTRyM'

### ISSUE THREAD

**Issue by alienx2** [SickRage/SickRage#1293]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 19:23:54) [GCC 4.8.5]**
Operating System: **Linux-2.6.22.19-mips-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@ad174b0a75eb63c651a46a1499f39215cf51aaa3
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [ad174b0] Failed doing webui callback: Traceback (most recent call last):
  File "/tmp/mnt/TOSHIBA/entware/etc/sickrage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/tmp/mnt/TOSHIBA/entware/etc/sickrage/sickbeard/webserve.py", line 1249, in displayShow
    t = PageTemplate(rh=self, filename="displayShow.mako")
  File "/tmp/mnt/TOSHIBA/entware/etc/sickrage/sickbeard/webserve.py", line 128, in __init__
    self.template = lookup.get_template(filename)
  File "/opt/etc/sickrage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/opt/etc/sickrage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/opt/etc/sickrage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/opt/etc/sickrage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/opt/etc/sickrage/lib/mako/template.py", line 703, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "/opt/lib/python2.7/tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/opt/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/opt/etc/sickrage/cache/mako/tmp4BTRyM'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
A restart of Sickrage should solve this.

**Comment by binarylimited** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@1c86cf68e30a5437e668ec6f2387bc390df54d4e
No Log available with ERRORS:
### ERROR
```
Thread-25 :: [1c86cf6] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 3839, in index
    t = PageTemplate(rh=self, filename="config_general.mako")
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 128, in __init__
    self.template = lookup.get_template(filename)
  File "C:\SickRage\SickRage\lib\mako\lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "C:\SickRage\SickRage\lib\mako\lookup.py", line 321, in _load
    **self.template_args)
  File "C:\SickRage\SickRage\lib\mako\template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\SickRage\lib\mako\template.py", line 378, in _compile_from_file
    self.module_writer)
  File "C:\SickRage\SickRage\lib\mako\template.py", line 703, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "C:\SickRage\Python\lib\tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "C:\SickRage\Python\lib\tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
