### ISSUE TITLE
just updated and getting this now: Failed doing webui callback: Traceback (most recent call last):

### ISSUE THREAD

**Issue by autobaud** [SickRage/SickRage#1295]
Branch/Commit: Branch: master, Commit: ad174b0a75eb63c651a46a1499f39215cf51aaa3 Version: 2016.03.28-2
OS: Windows 10 64bit
What you did: added shows
What happened: didn't notice anything happening, just saw the error notification a while later
What you expected: 
Logs:
```
2016-03-30 09:40:53 Thread-19 :: [ad174b0] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 2741, in addShowByID
    show_name = get_showname_from_indexer(1, indexer_id)
  File "C:\SickRage\SickRage\sickbeard\helpers.py", line 1745, in get_showname_from_indexer
    s = t[int(indexer_id)]
  File "C:\SickRage\SickRage\lib\tvdb_api\tvdb_api.py", line 953, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "C:\SickRage\SickRage\lib\tvdb_api\tvdb_api.py", line 848, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "C:\SickRage\SickRage\lib\tvdb_api\tvdb_api.py", line 636, in _getetsrc
    raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/301630/en.xml
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by OmgImAlexis** [comment]
It helps if you actually fill in the issue as it asks.

**Comment by autobaud** [comment]
i'm actually not sure what caused the issue, as i was doing a bunch of things and just then noticed the Error notification from 10 minutes earlier... all i know i was adding shows and checking things in my show lists... sorry i dont have more info, but i thought showing the error messages would help

**Comment by OmgImAlexis** [comment]
I've edited the question to add in areas you deleted.

**Comment by autobaud** [comment]
added as much info as i have to original post

**Comment by miigotu** [comment]
http://thetvdb.com/api/F9C450E78D99172E/series/301630/en.xml is 404, they removed that series from tvdb.
