### ISSUE TITLE
Cannot postprocess manually (nor automatically)

### ISSUE THREAD

**Issue by malevolent** [SickRage/SickRage#1303]
Post-processing doesn't always work, but since some days ago, it never does. On server status I can see 
Post Process 	False 	True 	True 		10m 		2016-03-31 11:09:02 	False
I can restart sickrage or even the computer, but yet the status can be "true" or green, as soon as I click Manual Post-processing, it fails once again.

I must say I am spanish and I have my locale set to en_US-UTF 8, and perhaps something with non-english characters are screwing things up.

Branch/Commit: master/ 9a4b1fd2cf04451e74cd8ed51c6210545a7d7fd3
OS: Arch Linux (ARM)
What you did: Click on Shows --> Manual Post-processing --> Process
What happened: 
Oops
You have reached this page by accident, please check the url.

What you expected:
Process my donwloaded files from my default download location to their own folder and naming them.
Logs:
```
2016-03-31 11:28:58 Thread-14 :: [9a4b1fd] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2290, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/opt/sickrage/sickbeard/processTV.py", line 255, in processDir
    for curDir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]:
  File "/opt/sickrage/sickbeard/processTV.py", line 392, in validateDir
    videoFiles = [x for x in allFiles if helpers.isMediaFile(x)]
  File "/opt/sickrage/sickbeard/helpers.py", line 197, in isMediaFile
    if filename.startswith('._'):
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc2 in position 13: invalid continuation byte
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
You have a file or folder in your post processing dir with a bad character in the name.

**Comment by malevolent** [comment]
I think I had not set my locale and sickrage was writing the spanish tildes as ???. After reading your answer, I've correctly set the locale and now they are showing weird characters like Ã³ or Ã©... so I guess I must rename correctly all files before continue.

Thank you
