### ISSUE TITLE
No subtitles found

### ISSUE THREAD

**Issue by SeeDborg** [SickRage/SickRage#1310]
Branch/Commit: master
OS: OSMC (raspbian)

I just reinstalled Sickrage on my Raspberry Pi, but it does not find any subtitles (french language) for my shows... I'm searching on addic7ed only, and checked several times my username and password.
It was working before.

Is that a known issue and is there a way to solve it ?

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
A username is not required for the subtitle search, it just increases the number of searches you can do. Try to enable other subtitle providers like Opensubtitles etc.
And you can try to disable `Perfect matches` but you might get subs that are out of sync.
Its a little try and error what settings/providers are best for your language/shows.

**Comment by PhunkyBob** [comment]
I have the same issue.
When I force a subtitle search and I look in the log file, I see that it searches for subtitles that are not even in my download folder (it's some episodes that are already downloaded and that already have subtitles).
But it doesn't tries to download subtitles for files that are indeed in my download folder.

**Comment by PhunkyBob** [comment]
For Addic7ed, the debug log says 

> Could not search in addic7ed provider. Discarding for now

**Comment by fernandog** [comment]
@PhunkyBob 

stop SR
edit SickRage/sickbeard/logger.py
uncoment logging.getLogger('subliminal') and align with others
start SR
force subtitle search UI /manage/manageSearches/

it will print a LOT of logs but subliminal logs

**Comment by PhunkyBob** [comment]
@fernandog , file was 
> /volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py

List of my download folder is 

> 11.22.63 E07 1080p HDTV x265-KRAVE.mp4
> Star.Wars.Rebels.S02E19.720p.HDTV.X264-UAV[rarbg]
> The.Americans.S04E01.Glanders.1080p.WEB-DL.6CH.x265.HEVC-PSA.mkv
> the.americans.s04e02.1080p.web.dl.6CH.hevc.x265.rmteam.mkv
> The.Americans.S04E03.Experimental.Prototype.City.of.Tomorrow.1080p.WEB-DL.6CH.x265.HEVC-PSA.mkv

I kept only Addic7ed as subtitles provider and ran a force subtitles search.

Short version: 

2016-04-02 22:33:37 INFO     FINDSUBTITLES :: Finished checking for missed subtitles
**2016-04-02 22:33:34 INFO     FINDSUBTITLES :: Searching for missing subtitles of 11.22.63 S01E06**
**2016-04-02 22:33:32 INFO     FINDSUBTITLES :: Searching for missing subtitles of Marvel's Agents of S.H.I.E.L.D. S03E13**
**2016-04-02 22:33:29 INFO     FINDSUBTITLES :: Searching for missing subtitles of The Flash (2014) S02E16**
2016-04-02 22:33:27 INFO     FINDSUBTITLES :: Searching for missing subtitles of The Americans (2013) S04E02
**2016-04-02 22:33:25 INFO     FINDSUBTITLES :: Searching for missing subtitles of Star Wars Rebels S02E18**
**2016-04-02 22:33:23 INFO     FINDSUBTITLES :: Searching for missing subtitles of Marvel's Agents of S.H.I.E.L.D. S03E14**
**2016-04-02 22:33:20 INFO     FINDSUBTITLES :: Searching for missing subtitles of The Flash (2014) S02E17**
**2016-04-02 22:33:18 INFO     FINDSUBTITLES :: Searching for missing subtitles of Star Wars Rebels S02E20**
2016-04-02 22:33:17 INFO     FINDSUBTITLES :: Searching for missing subtitles of Star Wars Rebels S02E19
2016-04-02 22:33:14 INFO     FINDSUBTITLES :: Searching for missing subtitles of The Americans (2013) S04E03
**2016-04-02 22:33:10 INFO     FINDSUBTITLES :: Searching for missing subtitles of The Big Bang Theory S09E19**
2016-04-02 22:33:10 INFO     FINDSUBTITLES :: Checking for missed subtitles
2016-04-02 22:32:57 INFO     FINDSUBTITLES :: Checking for needed subtitles in Post-Process folder

I've highlighted in **bold** files that are NOT in my download folder (and I already have the subtitles in the final directory).


Long version : http://pastebin.com/kqbvfdJE
(I don't know where to find the whole log, because it only displays the 500 last lines)

I think 2 important lines are:

>     2016-04-02 22:33:08 DEBUG    FINDSUBTITLES :: Could not search in addic7ed provider. Discarding for now

I don't know why it's discarded.

> AA2016-04-02 22:33:20 INFO     Scanning video 'The Flash (2014) - 2x17 - Flash Back (1080p HDTV x264).mkv' in '/volume1/video/TV Shows/The Flash (2014)/The Flash (2014) (S2)'
> 2016-04-02 22:33:20 DEBUG    FINDSUBTITLES :: Checking subtitle candidates for The Flash (2014) S02E17 (The Flash (2014) - 2x17 - Flash Back (1080p HDTV x264).mkv)
> 2016-04-02 22:33:20 DEBUG    FINDSUBTITLES :: Setter sets location to /volume1/video/TV Shows/The Flash (2014)/The Flash (2014) (S2)/The Flash (2014) - 2x17 - Flash Back (1080p HDTV x264).mkv
> 2016-04-02 22:33:20 INFO     FINDSUBTITLES :: Searching for missing subtitles of The Flash (2014) S02E17

Whereas this is a file which already have a subtitle.
When I look at the log, it seems that the force subtitle search try to find better subtitles, even if there is already subtitles for an episode? 
(I see a "scanning video", "compute hash", ...)
Could you explain me what is done?

**Comment by fernandog** [comment]
@PhunkyBob need logs before "2016-04-02 22:33:08 DEBUG    FINDSUBTITLES :: Could not search in addic7ed provider. Discarding for now"

when provider is discarded, all next searchs on that provider are discared. Need to find the reason of the "first" discarded

**Comment by PhunkyBob** [comment]
Yes, I've found the log and updated my post with a new pastebin.

And we can see:

`2016-04-02 22:33:01 INFO     Initializing provider addic7ed
2016-04-02 22:33:01 INFO     Logging in
2016-04-02 22:33:01 INFO     Logging in
2016-04-02 22:33:01 ERROR    Unexpected error in provider 'addic7ed'
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 68, in __getitem__
    provider.initialize()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/providers/addic7ed.py", line 103, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: *************
2016-04-02 22:33:01 ERROR    Unexpected error in provider 'addic7ed'
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 68, in __getitem__
    provider.initialize()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/providers/addic7ed.py", line 103, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: *************
2016-04-02 22:33:01 INFO     Discarding provider addic7ed`

**Comment by fernandog** [comment]
@PhunkyBob  AuthenticationError, user/pass must be wrong. or they changed something in the website. need to open issue in https://github.com/Diaoul/subliminal/issues/new as the subtitle module is from someone else

about the search:
go to subtitle managment: /manage/subtitleMissed/

it only continue to search if your wanted subtitle is not downloaded. 
and some other settings in subtitle settings

**Comment by PhunkyBob** [comment]
For the record: https://github.com/Diaoul/subliminal/issues/616


>  go to subtitle managment: /manage/subtitleMissed/

It's empty.

> it only continue to search if your wanted subtitle is not downloaded. 

For the lines I highlighted, subtitles were already downloaded.
There is something I don't understand...

**Comment by fernandog** [comment]
@PhunkyBob what are your wanted languages? it will stop only when all wanted subs are downloaded.

in  /manage/subtitleMissed/, selecting "all" and clicking "Manage" you get no results?

send a full print of your subtitle settings except user/pass tab
and one print of one of those shows that is searching for subs

**Comment by PhunkyBob** [comment]
> what are your wanted languages?
English, for all my shows.

In the combobox, I only have "English".
When I click on "(english) manage", I have the same episodes as the one in the log file in bold.

My configuration: 
http://i.imgur.com/pZu29NO.png
http://i.imgur.com/KAvytjA.png
http://i.imgur.com/D920n7U.png

And one of the srt that is already downloaded is: http://pastebin.com/GBUVpiUq
withe the same name as the filename.

**Comment by fernandog** [comment]
Can you send a full print of a show that is showing as missing subs?

After print, click rescan file button.

**Comment by PhunkyBob** [comment]
http://i.imgur.com/JQ1m1bR.png

After a "rescan files", I don't see the show in the "subtitlesMissed".

I thought that the workflow was:
- Download a wanted episode in "download".
- Don't move it, because there is no subtitles.
- Search and download a subtitle and match the files names.
- Move the video and srt file to "TV Shows".

How is it possible that a subtitle is missing for an episode in the "TV Shows" folder, while a video has to have a subtitle to be moved in this folder?

**Comment by miigotu** [comment]
Disable "Postpone if no Subs"/"Subtitles in PP"

It doesnt work well, and it CANT work well no matter how much effort is wasted on it.

**Comment by PhunkyBob** [comment]
OK, thank you.

**Comment by fernandog** [comment]
@PhunkyBob do you keep your SR running 24/7 ? because every night at 3am all shows are refreshed.

and when show is PP, its moves the file and recognizes it. 
Does it happens to ALL eps or only those one?

**Comment by PhunkyBob** [comment]
Yes, SR is running 24/7.

>  Does it happens to ALL eps or only those one?

Only those ones (about 8 over 1000 episodes).

> if you manually add subs

I don't, I wait for subs to be downloaded in the download folder.
I never have episode without subtitles in my "TV Shows" folder.

Even with the 3 AM post-process, it shouldn't move episodes without srt.


It's not a blocking problem, because the files are OK and I already have the subtitles. It's just some log pollution.

The real problem is the one mentioned in the first topic: the authentication failing with Addic7ed.
I'm waiting the answer from "subliminal".

**Comment by fernandog** [comment]
Glad you like the feature. A lot of users like it

"Even with the 3 AM post-process, it shouldn't move episodes without srt."

You didnt understand.
At 3am all shows are supposed to be refreshed and you wouldnt have that issue. But show how they didnt get refreshed. So its not a subtitle issue

**Comment by SeeDborg** [comment]
subliminal answered there is no problem. I still have the same issue than @PhunkyBob

**Comment by SeeDborg** [comment]
Bought a Synology NAS, still have the same issue.

Maybe it's real !

**Comment by PhunkyBob** [comment]
Still "_Could not search in addic7ed provider. Discarding for now_"...

**Comment by SeeDborg** [comment]
Same here.
