### ISSUE TITLE
[APP SUBMITTED]: -1

### ISSUE THREAD

**Issue by Iclario** [SickRage/SickRage#1328]
### INFO

Python Version: **2.7.9 (default, Mar  8 2015, 00:52:26) [GCC 4.9.2]**
Operating System: **Linux-4.1.19-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8833592acd2587ecb40b3a13290b1846cc47c2b5
No Log available with ERRORS:
### ERROR

```
TORNADO :: [8833592] API :: error -1
```

---

_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by mabogdan1981** [comment]
### INFO
Python Version: **2.7.11 (default, Mar 27 2016, 22:06:47) [GCC 5.3.0]**
Operating System: **Linux-3.19.8-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@4e8b9eeb3157adb5fcdee67ef68610c0bb65abf4
No Log available with ERRORS:
### ERROR
```
TORNADO :: [4e8b9ee] API :: error -1
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by widend** [comment]
### INFO
Python Version: **2.7.3 (default, Jun 21 2016, 18:38:19) [GCC 4.7.2]**
Operating System: **Linux-3.16.0-0.bpo.4-amd64-x86_64-with-debian-7.11**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@4e8b9eeb3157adb5fcdee67ef68610c0bb65abf4
No Log available with ERRORS:
### ERROR
```
TORNADO :: [4e8b9ee] API :: error -1
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sealtael** [comment]
### INFO
Python Version: **2.7.10 (default, Jan  6 2016, 14:39:32) [GCC 4.6.4]**
Operating System: **Linux-3.10.70-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5443e1bec1404035218c5fc58c8ddedb97dbb88a
No Log available with ERRORS:
### ERROR
```
TORNADO :: [5443e1b] API :: error -1
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sealtael** [comment]
### INFO
Python Version: **2.7.10 (default, Jan  6 2016, 14:39:32) [GCC 4.6.4]**
Operating System: **Linux-3.10.70-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5443e1bec1404035218c5fc58c8ddedb97dbb88a
No Log available with ERRORS:
### ERROR
```
TORNADO :: [5443e1b] API :: error -1
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sealtael** [comment]
### INFO
Python Version: **2.7.10 (default, Jan  6 2016, 14:39:32) [GCC 4.6.4]**
Operating System: **Linux-3.10.70-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5443e1bec1404035218c5fc58c8ddedb97dbb88a
No Log available with ERRORS:
### ERROR
```
TORNADO :: [5443e1b] API :: error -1
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sealtael** [comment]
### INFO
Python Version: **2.7.10 (default, Jan  6 2016, 14:39:32) [GCC 4.6.4]**
Operating System: **Linux-3.10.70-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@a1bf3b30a9a0d6319c09fb0cf48d2d468dbf4e61
No Log available with ERRORS:
### ERROR
```
TORNADO :: [a1bf3b3] API :: error -1
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sealtael** [comment]
### INFO
Python Version: **2.7.10 (default, Jan  6 2016, 14:39:32) [GCC 4.6.4]**
Operating System: **Linux-3.10.70-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@a1bf3b30a9a0d6319c09fb0cf48d2d468dbf4e61
No Log available with ERRORS:
### ERROR
```
TORNADO :: [a1bf3b3] API :: error -1
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sealtael** [comment]
### INFO
Python Version: **2.7.10 (default, Jan  6 2016, 14:39:32) [GCC 4.6.4]**
Operating System: **Linux-3.10.70-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@a1bf3b30a9a0d6319c09fb0cf48d2d468dbf4e61
No Log available with ERRORS:
### ERROR
```
TORNADO :: [a1bf3b3] API :: error -1
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sealtael** [comment]
### INFO
Python Version: **2.7.10 (default, Jan  6 2016, 14:39:32) [GCC 4.6.4]**
Operating System: **Linux-3.10.70-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@a1bf3b30a9a0d6319c09fb0cf48d2d468dbf4e61
No Log available with ERRORS:
### ERROR
```
TORNADO :: [a1bf3b3] API :: error -1
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sealtael** [comment]
### INFO
Python Version: **2.7.10 (default, Jan  6 2016, 14:39:32) [GCC 4.6.4]**
Operating System: **Linux-3.10.70-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@8d1b96f507b88b3098387c5004b88db4f54a0b41
No Log available with ERRORS:
### ERROR
```
TORNADO :: [8d1b96f] API :: error -1
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sealtael** [comment]
### INFO
Python Version: **2.7.10 (default, Jan  6 2016, 14:39:32) [GCC 4.6.4]**
Operating System: **Linux-3.10.70-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@93acf7815e8af09077609816af8aea34c3bb0539
No Log available with ERRORS:
### ERROR
```
TORNADO :: [93acf78] API :: error -1
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
Add logs or it didnt happen.

**Comment by MGaetan89** [comment]
Here is the log associated to this error:
```
2017-02-11 15:18:14 ERROR TORNADO :: [7e6e057] API :: error -1
AA KeyError: -1
AA episode_status_counts_total[status] += 1
AA File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webapi.py", line 2633, in run
AA cur_out_dict = to_call.run() # call function and get response
AA File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webapi.py", line 194, in call_dispatcher
AA out_dict = _call_dispatcher(args, kwargs)
AA File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webapi.py", line 122, in get
AA Traceback (most recent call last):
```

And here is the faulty line: `episode_status_counts_total[status] += 1`.
I guess that an episode status changed in SickRage but the corresponding episodes kept the old status.

**Comment by MGaetan89** [comment]
It's working fine now. Thanks @miigotu

**Comment by Zetsuo** [comment]
### INFO
Python Version: **3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]**
Operating System: **Linux-5.4.51-v7+-armv7l-with-debian-10.4**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@20d84f5288ec3e532b6dd46cdbe4b833fbef00fd
Link to Log: https://gist.github.com/b00bdd4815699820627680c196483388
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
@Zetsuo I see where that error occurred. I was taking part of the day off but I'll see if I can fix that tonight

**Comment by Zetsuo** [comment]
### INFO
Python Version: **3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]**
Operating System: **Linux-5.4.51-v7+-armv7l-with-debian-10.4**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@79a5a4a7cddf021bfd4a458eef256818ff39288d
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
