### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by identd113** [SickRage/SickRage#1337]
### INFO
Python Version: **2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]**
Operating System: **Darwin-15.4.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1c86cf68e30a5437e668ec6f2387bc390df54d4e
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [1c86cf6] Exception generated in thread FINDPROPERS: 'NoneType' object has no attribute 'split'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by identd113** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]**
Operating System: **Darwin-15.4.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1c86cf68e30a5437e668ec6f2387bc390df54d4e
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NZBGeek] :: [1c86cf6] Error while searching NZBGeek, skipping: 'NoneType' object has no attribute 'split'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by identd113** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]**
Operating System: **Darwin-15.4.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1c86cf68e30a5437e668ec6f2387bc390df54d4e
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [ALThub] :: [1c86cf6] Error while searching ALThub, skipping: 'NoneType' object has no attribute 'split'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by identd113** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]**
Operating System: **Darwin-15.4.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1c86cf68e30a5437e668ec6f2387bc390df54d4e
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [nzbfinder.ws] :: [1c86cf6] Error while searching nzbfinder.ws, skipping: 'NoneType' object has no attribute 'split'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
Without logs of the error happening, cant help.

**Comment by identd113** [comment]
AA
AAAttributeError: 'NoneType' object has no attribute 'split'
AA    ignore_words = set(ignore_words).difference(x.strip() for x in show.rls_require_words.split(','))
AA  File "/Applications/SickRage/sickbeard/show_name_helpers.py", line 90, in filterBadReleases
AA    if not show_name_helpers.filterBadReleases(curResult["name"], show=showObj):
AA  File "/Applications/SickRage/sickbeard/tvcache.py", line 322, in findNeededEpisodes
AA    return self.cache.findNeededEpisodes(episodes)
AA  File "/Applications/SickRage/sickrage/providers/GenericProvider.py", line 360, in search_rss
AA    curFoundResults = curProvider.search_rss(episodes)
AA  File "/Applications/SickRage/sickbeard/search.py", line 409, in searchForNeededEpisodes
2016-04-04 08:58:39 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [nzbfinder.ws] :: Traceback (most recent call last):
AAAttributeError: 'NoneType' object has no attribute 'split'
AA    ignore_words = set(ignore_words).difference(x.strip() for x in show.rls_require_words.split(','))
AA  File "/Applications/SickRage/sickbeard/show_name_helpers.py", line 90, in filterBadReleases
AA    if not show_name_helpers.filterBadReleases(curResult["name"], show=showObj):
AA  File "/Applications/SickRage/sickbeard/tvcache.py", line 322, in findNeededEpisodes
AA    return self.cache.findNeededEpisodes(episodes)
AA  File "/Applications/SickRage/sickrage/providers/GenericProvider.py", line 360, in search_rss
AA    curFoundResults = curProvider.search_rss(episodes)
AA  File "/Applications/SickRage/sickbeard/search.py", line 409, in searchForNeededEpisodes
AATraceback (most recent call last):
2016-04-04 08:58:39 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [nzbfinder.ws] :: [1c86cf6] Error while searching nzbfinder.ws, skipping: 'NoneType' object has no attribute 'split'

**Comment by miigotu** [comment]
Thanks for playing =P

**Comment by identd113** [comment]
This resolved the current issue.
Thank you for your time.

**Comment by Hujiin** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 12:07:24) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5443e1bec1404035218c5fc58c8ddedb97dbb88a
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [5443e1b] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 4973, in saveNotifications
    sickbeard.KODI_HOST = config.clean_hosts(kodi_host)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/config.py", line 466, in clean_hosts
    for cur_host in [host.strip() for host in hosts.split(",") if host.strip()]:
AttributeError: 'NoneType' object has no attribute 'split'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by jimcrilly** [comment]
### INFO
Python Version: **2.7.14+ (default, Feb  6 2018, 19:12:18) [GCC 7.3.0]**
Operating System: **Linux-4.14.0-2-amd64-x86_64-with-debian-buster-sid**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@7ddf7f5c9814688275aa437aa6834f948f2d3fa7
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [7ddf7f5] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/opt/SickRage/sickbeard/webserve.py", line 3817, in removeHistory
    for logItem in toRemove.split('|'):
AttributeError: 'NoneType' object has no attribute 'split'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by whiteazn** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19043-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@a8e5d00f02e5d27719409bb9d7d733042b294b82
Link to Log: https://gist.github.com/e851ae6af05ab0fc016973c0ca0ad272
### ERROR
```
Unable to add show due to an error with theTVDB: 'NoneType' object has no attribute 'split'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by whiteazn** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19043-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@a8e5d00f02e5d27719409bb9d7d733042b294b82
Link to Log: https://gist.github.com/4c2c0c453732911086fce98185c5d97d
### ERROR
```
Error trying to add show: 'NoneType' object has no attribute 'split'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
