### ISSUE TITLE
Unable to download torrents from provider IPTorrents

### ISSUE THREAD

**Issue by mrfacu87** [SickRage/SickRage#1342]
Python Version: 2.7 (r27:82525, Jul 4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)]
Operating System: Windows-post2008Server-6.2.9200
Locale: cp1252
Branch: master
Commit: SickRage/SickRage@1c86cf6

More information:
The issue appears to be related to IPTorrents. This is the only search provider I like to use. As a test, I enabled a few other search providers (KAT and Torrentz) and they work just fine. I'm not sure what could've changed, but I have not been able to download anything using IPTorrents for the past week.

```
11:36:37 INFO::SEARCHQUEUE-MANUAL-304196 :: Beginning manual search for: [The Path - S01E02 - 002 - The Era of The Ladder]
11:36:37 INFO::SEARCHQUEUE-MANUAL-304196 :: [IPTorrents] :: Performing episode search for The Path
11:36:38 INFO::SEARCHQUEUE-MANUAL-304196 :: [IPTorrents] :: Quality of The.Path.S01E02.WEBRip.XviD.FUM is SDTV
11:36:38 INFO::SEARCHQUEUE-MANUAL-304196 :: [IPTorrents] :: Quality of The.Path.S01E02.WEBRip.x264.FUM is SDTV
11:36:38 INFO::SEARCHQUEUE-MANUAL-304196 :: [IPTorrents] :: Preferring The.Path.S01E02.WEBRip.x264.FUM (x264 over xvid)
11:36:38 INFO::SEARCHQUEUE-MANUAL-304196 :: Downloading The.Path.S01E02.WEBRip.x264.FUM from IPTorrents
11:36:38 ERROR::SEARCHQUEUE-MANUAL-304196 :: [1c86cf6] Request failed: 'charmap' codec can't decode byte 0x8d in position 670: character maps to 
Traceback (most recent call last):
File "C:\SickRage-master\sickbeard\helpers.py", line 1449, in handle_requests_exception
raise requests_exception
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 670: character maps to 
11:36:38 WARNING::SEARCHQUEUE-MANUAL-304196 :: uTorrent: Unable to send Torrent
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by bergonzzi** [comment]
### INFO
Python Version: **2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@6e3ebea4d634d3e5894ae9b85eabffe4284be0ca
No Log available with ERRORS:
### ERROR
```
Thread-22 :: [6e3ebea] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 644, in get_messages
    return json.dumps(messages)
  File "C:\Python27\Lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 120: invalid start byte

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mrfacu87** [comment]
### INFO
Python Version: **2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-post2008Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@6e3ebea4d634d3e5894ae9b85eabffe4284be0ca
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-273181 :: [6e3ebea] Request failed: 'charmap' codec can't decode byte 0x81 in position 2524: character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mrfacu87** [comment]
### INFO
Python Version: **2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-post2008Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@8e2b26857c85a4bada2b6cc068279c081c7c8311
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-73762 :: [8e2b268] Request failed: 'charmap' codec can't decode byte 0x81 in position 1916: character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MrLinford** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.10586**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@e718ba29b4fd92099d2c2c665ae9c7845a633c23
No Log available with ERRORS:
### ERROR
```
Thread-22 :: [e718ba2] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 647, in get_messages
    return json.dumps(messages)
  File "C:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x85 in position 82: invalid start byte

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mrfacu87** [comment]
### INFO
Python Version: **2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-post2008Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@31b5be571b3cc4d7e11dc543ea5b3c071bf55b41
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-304196 :: [31b5be5] Request failed: 'charmap' codec can't decode byte 0x8d in position 670: character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mrfacu87** [comment]
### INFO
Python Version: **2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-post2008Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@31b5be571b3cc4d7e11dc543ea5b3c071bf55b41
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-293322 :: [31b5be5] Request failed: 'charmap' codec can't decode byte 0x81 in position 2507: character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mrfacu87** [comment]
### INFO
Python Version: **2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-post2008Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@31b5be571b3cc4d7e11dc543ea5b3c071bf55b41
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-304196 :: [31b5be5] Request failed: 'charmap' codec can't decode byte 0x8d in position 670: character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mrfacu87** [comment]
### INFO
Python Version: **2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-post2008Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5709abdbe82611c8c941ddc0cda9784e8ef65bcd
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-304196 :: [5709abd] Request failed: 'charmap' codec can't decode byte 0x8d in position 670: character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mrfacu87** [comment]
### INFO
Python Version: **2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-post2008Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@b80c18dbb712a91c38d3617576a2aff67ed17bb0
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-273181 :: [b80c18d] Request failed: 'charmap' codec can't decode byte 0x90 in position 2116: character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mrfacu87** [comment]
### INFO
Python Version: **2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-post2008Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@b80c18dbb712a91c38d3617576a2aff67ed17bb0
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-293322 :: [b80c18d] Request failed: 'charmap' codec can't decode byte 0x81 in position 2507: character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mrfacu87** [comment]
### INFO
Python Version: **2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-post2008Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@b80c18dbb712a91c38d3617576a2aff67ed17bb0
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-254243 :: [b80c18d] Request failed: 'charmap' codec can't decode byte 0x8d in position 1553: character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mrfacu87** [comment]
### INFO
Python Version: **2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-post2008Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@b80c18dbb712a91c38d3617576a2aff67ed17bb0
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-304196 :: [b80c18d] Request failed: 'charmap' codec can't decode byte 0x8d in position 670: character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
Still an issue?

**Comment by mrfacu87** [comment]
Yes, I updated and tried again last night and the issue was still present.

**Comment by mrfacu87** [comment]
Updated again this morning. Same issue:

11:39:09 INFO::SEARCHQUEUE-MANUAL-257655 :: Beginning manual search for: [Arrow - S04E19 - 088 - Canary Cry]
11:39:09 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Last update was too soon, using old cache: 2016-04-28 11:38:24. Updated less then 10 minutes ago
11:39:09 INFO::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Performing episode search for Arrow
11:39:09 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: GET URL: https://iptorrents.eu/torrents/ [Status: 200]
11:39:09 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: POST URL: https://iptorrents.eu/torrents/ [Status: 302]
11:39:09 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: With post data: username=********&login=submit&password=********
11:39:09 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: GET URL: https://iptorrents.eu/torrents/ [Status: 200]
11:39:09 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Search Mode: Episode
11:39:09 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Search string: Arrow S04E19
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: GET URL: https://iptorrents.eu/t?73=&60=&q=Arrow%20S04E19&qf=#torrents;o=seeders [Status: 200]
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Found result: Arrow S04E19 Canary Cry 1080p WEB-DL DD5 1 H264-DRACULA with 74 seeders and 5 leechers
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Found result: Arrow S04E19 HDTV XviD FUM with 353 seeders and 7 leechers
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Found result: Arrow S04E19 480p x264-mSD with 225 seeders and 24 leechers
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Found result: Arrow S04E19 XviD-AFG with 659 seeders and 31 leechers
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Found result: Arrow S04E19 1080p HDTV X264-DIMENSION with 348 seeders and 4 leechers
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Found result: Arrow S04E19 720p HDTV X264-DIMENSION with 2348 seeders and 54 leechers
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Found result: Arrow S04E19 HDTV x264-LOL with 544 seeders and 16 leechers
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Parsed Arrow.S04E19.Canary.Cry.1080p.WEB-DL.DD5.1.H264-DRACULA into Arrow - S04E19 [GROUP: DRACULA] [ABD: False] [ANIME: False] [whichReg: ['standard']]
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Any,Best = [ SDTV, SD DVD ] [ None ] Found = [ 1080p WEB-DL ]
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Don't want this quality, ignoring found result for Arrow S04E19 with quality 1080p WEB-DL
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Ignoring result Arrow.S04E19.Canary.Cry.1080p.WEB-DL.DD5.1.H264-DRACULA.
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Parsed Arrow.S04E19.1080p.HDTV.X264-DIMENSION into Arrow - S04E19 [GROUP: DIMENSION] [ABD: False] [ANIME: False] [whichReg: ['standard']]
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Any,Best = [ SDTV, SD DVD ] [ None ] Found = [ 1080p HDTV ]
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Don't want this quality, ignoring found result for Arrow S04E19 with quality 1080p HDTV
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Ignoring result Arrow.S04E19.1080p.HDTV.X264-DIMENSION.
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Parsed Arrow.S04E19.720p.HDTV.X264-DIMENSION into Arrow - S04E19 [GROUP: DIMENSION] [ABD: False] [ANIME: False] [whichReg: ['standard']]
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Any,Best = [ SDTV, SD DVD ] [ None ] Found = [ 720p HDTV ]
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Don't want this quality, ignoring found result for Arrow S04E19 with quality 720p HDTV
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Ignoring result Arrow.S04E19.720p.HDTV.X264-DIMENSION.
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Parsed Arrow.S04E19.HDTV.x264-LOL into Arrow - S04E19 [GROUP: LOL] [ABD: False] [ANIME: False] [whichReg: ['standard']]
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Any,Best = [ SDTV, SD DVD ] [ None ] Found = [ SDTV ]
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Existing episode status is 'Wanted', getting found result for Arrow S04E19 with quality SDTV
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Found result Arrow.S04E19.HDTV.x264-LOL at https://iptorrents.eu/download.php/1814607/Arrow.S04E19.HDTV.x264-LOL.torrent
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Single episode result.
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Parsed Arrow.S04E19.HDTV.XviD.FUM into Arrow - S04E19 [ABD: False] [ANIME: False] [whichReg: ['standard']]
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Any,Best = [ SDTV, SD DVD ] [ None ] Found = [ SDTV ]
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Existing episode status is 'Wanted', getting found result for Arrow S04E19 with quality SDTV
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Found result Arrow.S04E19.HDTV.XviD.FUM at https://iptorrents.eu/download.php/1814659/Arrow.S04E19.HDTV.XviD-FUM.torrent
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Single episode result.
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Parsed Arrow.S04E19.480p.x264-mSD into Arrow - S04E19 [GROUP: mSD] [ABD: False] [ANIME: False] [whichReg: ['standard']]
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Any,Best = [ SDTV, SD DVD ] [ None ] Found = [ SDTV ]
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Existing episode status is 'Wanted', getting found result for Arrow S04E19 with quality SDTV
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Found result Arrow.S04E19.480p.x264-mSD at https://iptorrents.eu/download.php/1814645/Arrow.S04E19.480p.x264-mSD.torrent
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Single episode result.
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Parsed Arrow.S04E19.XviD-AFG into Arrow - S04E19 [GROUP: AFG] [ABD: False] [ANIME: False] [whichReg: ['standard']]
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Any,Best = [ SDTV, SD DVD ] [ None ] Found = [ Unknown ]
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Don't want this quality, ignoring found result for Arrow S04E19 with quality Unknown
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Ignoring result Arrow.S04E19.XviD-AFG.
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: The highest quality of any match is SDTV
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Picking the best result out of [u'Arrow.S04E19.HDTV.x264-LOL', u'Arrow.S04E19.HDTV.XviD.FUM', u'Arrow.S04E19.480p.x264-mSD']
11:39:10 INFO::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Quality of Arrow.S04E19.HDTV.x264-LOL is SDTV
11:39:10 INFO::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Quality of Arrow.S04E19.HDTV.XviD.FUM is SDTV
11:39:10 INFO::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Quality of Arrow.S04E19.480p.x264-mSD is SDTV
11:39:10 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Picked Arrow.S04E19.HDTV.x264-LOL as the best
11:39:11 DEBUG::SEARCHQUEUE-MANUAL-257655 :: [IPTorrents] :: Checking if we should keep searching after we've found Arrow.S04E19.HDTV.x264-LOL
11:39:11 INFO::SEARCHQUEUE-MANUAL-257655 :: Downloading Arrow.S04E19.HDTV.x264-LOL from IPTorrents
11:39:11 DEBUG::SEARCHQUEUE-MANUAL-257655 :: GET URL: https://iptorrents.eu/download.php/1814607/Arrow.S04E19.HDTV.x264-LOL.torrent [Status: 200]
11:39:11 DEBUG::SEARCHQUEUE-MANUAL-257655 :: Calling uTorrent Client
11:39:11 DEBUG::SEARCHQUEUE-MANUAL-257655 :: Result Hash is e6aa361ddd92a5573ae57a5dbbff3670e350426c
11:39:11 DEBUG::SEARCHQUEUE-MANUAL-257655 :: uTorrent: Requested a POST connection to url http://localhost:8082/gui/?token=tOHRXv9wSifYQ0at0Od91cNv6oWkOS-vSEqgyw4y87SJlmjxfT_oMJ8uIlcAAAAA&action=add-file
11:39:11 ERROR::SEARCHQUEUE-MANUAL-257655 :: [2f6204d] Request failed: 'charmap' codec can't decode byte 0x90 in position 1577: character maps to <undefined>
Traceback (most recent call last):
  File "C:\SickRage-master\sickbeard\helpers.py", line 1443, in handle_requests_exception
    raise requests_exception
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1577: character maps to <undefined>
11:39:11 DEBUG::SEARCHQUEUE-MANUAL-257655 :: Traceback (most recent call last):
  File "C:\SickRage-master\sickbeard\helpers.py", line 1443, in handle_requests_exception
    raise requests_exception
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1577: character maps to <undefined>

11:39:11 WARNING::SEARCHQUEUE-MANUAL-257655 :: uTorrent: Unable to send Torrent
11:39:35 INFO::Thread-13 :: Checking for updates using SOURCE
11:39:36 DEBUG::Thread-13 :: cur_commit = 2f6204d2500bdfa328fe572e0f1ab88058fe25d3, newest_commit = 2f6204d2500bdfa328fe572e0f1ab88058fe25d3, num_commits_behind = 0
11:39:43 INFO::Thread-13 :: Commented on existing issue #1204 successfully!

**Comment by wimpyrbx** [comment]
got an issue here as well with IPtorrents.
when i view the page mentioned:
https://iptorrents.eu/t?73=&60=&q=The%20Middle%20S07E14&qf=#torrents;o=seeders
i see all the releases. it just does not return anything.

2016-04-28 23:04:37 INFO     SEARCHQUEUE-MANUAL-95021 :: Unable to find a download for: [The Middle - S07E14 - Film, Friends and Fruit Pies]
2016-04-28 23:04:37 DEBUG    SEARCHQUEUE-MANUAL-95021 :: formatting pattern: %SN - S%0SE%0E - %EN -> The Middle - S07E14 - Film, Friends and Fruit Pies
2016-04-28 23:04:37 DEBUG    SEARCHQUEUE-MANUAL-95021 :: formatting pattern: %SN - S%0SE%0E - %EN -> The Middle - S07E14 - Film, Friends and Fruit Pies
2016-04-28 23:04:37 DEBUG    SEARCHQUEUE-MANUAL-95021 :: [IPTorrents] :: Data returned from provider does not contain any torrents
2016-04-28 23:04:37 DEBUG    SEARCHQUEUE-MANUAL-95021 :: [IPTorrents] :: GET URL: https://iptorrents.eu/t?73=&60=&q=The%20Middle%20S07E14&qf=#torrents;o=seeders [Status: 200]
2016-04-28 23:04:36 DEBUG    SEARCHQUEUE-MANUAL-95021 :: [IPTorrents] :: Search string: The Middle S07E14
2016-04-28 23:04:36 DEBUG    SEARCHQUEUE-MANUAL-95021 :: [IPTorrents] :: Search Mode: Episode
2016-04-28 23:04:36 INFO     SEARCHQUEUE-MANUAL-95021 :: [IPTorrents] :: Performing episode search for The Middle
2016-04-28 23:04:36 DEBUG    SEARCHQUEUE-MANUAL-95021 :: [IPTorrents] :: Last update was too soon, using old cache: 2016-04-28 23:01:31. Updated less then 10 minutes ago
2016-04-28 23:04:36 INFO     SEARCHQUEUE-MANUAL-95021 :: Beginning manual search for: [The Middle - S07E14 - Film, Friends and Fruit Pies]

the link displays for example
The Middle S07E14 Film Friends and Fruit Pies 720p WEB-DL DD5 1 H 264-NTb
The Middle S07E14 Film Friends and Fruit Pies 1080p WEB-DL DD5 1 H 264-NTb
The Middle S07E14 1080p HDTV X264-DIMENSION
etc..

**Comment by miigotu** [comment]
@wimpyrbx your issue is totally unrelated, and I would assume it is an outdated openssl or python.

@mrfacu87 I just tested IPT with both black hold and utorrent connection using en_US.ISO8859-1 (very close to charmap in windows) and I have no errors.

**Comment by mrfacu87** [comment]
@miigotu Thanks for looking into this. How do I change the connection settings in utorrent to use en_US.ISO8859-1 instead of charmap?

**Comment by miigotu** [comment]
Its not the connection settings, and you don't want that encoding. I just used that encoding to most closely match yours.
