### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/309435/en.xml

### ISSUE THREAD

**Issue by snapperhead** [SickRage/SickRage#1349]
### INFO
Python Version: **2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]**
Operating System: **Darwin-15.4.0-x86_64-i386-64bit**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@6e3ebea4d634d3e5894ae9b85eabffe4284be0ca
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [6e3ebea] Failed doing webui callback: Traceback (most recent call last):
  File "/Applications/SickRage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/Applications/SickRage/sickbeard/webserve.py", line 2753, in addShowByID
    show_name = get_showname_from_indexer(1, indexer_id)
  File "/Applications/SickRage/sickbeard/helpers.py", line 1733, in get_showname_from_indexer
    s = t[int(indexer_id)]
  File "/Applications/SickRage/lib/tvdb_api/tvdb_api.py", line 953, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/Applications/SickRage/lib/tvdb_api/tvdb_api.py", line 848, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "/Applications/SickRage/lib/tvdb_api/tvdb_api.py", line 636, in _getetsrc
    raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/309435/en.xml

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
TVDB deleted that series (probably a dupe). Remove it and re-add it.
