### ISSUE TITLE
[APP SUBMITTED]: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}

### ISSUE THREAD

**Issue by KanedNUnable** [SickRage/SickRage#1372]
### INFO
Python Version: **2.7.3 (default, May 24 2013, 23:21:13) [GCC 4.5.4]**
Operating System: **Linux-3.14.2-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6e3ebea4d634d3e5894ae9b85eabffe4284be0ca
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [6e3ebea] Traceback (most recent call last):
  File "/share/1000/sickrage/sickbeard/logger.py", line 377, in submit_errors
    issue = git.get_organization(gh_org).get_repo(gh_repo).create_issue(title_error, message)
  File "/direct-usb/sickrage/lib/github/Repository.py", line 885, in create_issue
    input=post_parameters
  File "/direct-usb/sickrage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/direct-usb/sickrage/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by twinden** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 14:08:17) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@31b5be571b3cc4d7e11dc543ea5b3c071bf55b41
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [31b5be5] Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 377, in submit_errors
    issue = git.get_organization(gh_org).get_repo(gh_repo).create_issue(title_error, message)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Repository.py", line 885, in create_issue
    input=post_parameters
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Obrien2** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@b790df702cf1ef84ee64b591f40ce6fae86976dc
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [b790df7] Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 384, in submit_errors
    issue = repo.create_issue(title_error, message)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Repository.py", line 885, in create_issue
    input=post_parameters
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by gvtters** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@946f6be31a26c661a5e0903c5d66e4ce348ce19d
No Log available with ERRORS:
### ERROR
```
Thread-20 :: [946f6be] Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\logger.py", line 384, in submit_errors
    issue = repo.create_issue(title_error, message)
  File "C:\SickRage\SickRage\lib\github\Repository.py", line 885, in create_issue
    input=post_parameters
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by gvtters** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@946f6be31a26c661a5e0903c5d66e4ce348ce19d
No Log available with ERRORS:
### ERROR
```
Thread-23 :: [946f6be] Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\logger.py", line 384, in submit_errors
    issue = repo.create_issue(title_error, message)
  File "C:\SickRage\SickRage\lib\github\Repository.py", line 885, in create_issue
    input=post_parameters
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mrtim00** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@946f6be31a26c661a5e0903c5d66e4ce348ce19d
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [946f6be] Traceback (most recent call last):
  File "C:\SickRage\sickbeard\logger.py", line 384, in submit_errors
    issue = repo.create_issue(title_error, message)
  File "C:\SickRage\lib\github\Repository.py", line 885, in create_issue
    input=post_parameters
  File "C:\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\lib\github\Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by omarelmarajie** [comment]
### INFO
Python Version: **2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-34-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4e8b9eeb3157adb5fcdee67ef68610c0bb65abf4
No Log available with ERRORS:
### ERROR
```
Thread-21 :: [4e8b9ee] Traceback (most recent call last):
  File "/home/omar/.sickrage/sickbeard/logger.py", line 373, in submit_errors
    if report.create_comment(message):
  File "/home/omar/.sickrage/lib/github/Issue.py", line 247, in create_comment
    input=post_parameters
  File "/home/omar/.sickrage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/home/omar/.sickrage/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by geekitup** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@027a950fe0ac81a6d3a139f5ad68cfbaa8c85e9f
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [027a950] Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 373, in submit_errors
    if report.create_comment(message):
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Issue.py", line 247, in create_comment
    input=post_parameters
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by zyphermonkey** [comment]
### INFO
Python Version: **2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]**
Operating System: **Linux-4.4.19-unRAID-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@21c9621a36dabe345fc4879200c3fba39b84c8ce
No Log available with ERRORS:
### ERROR
```
Thread-26 :: [21c9621] Traceback (most recent call last):
  File "/app/sickrage/sickbeard/logger.py", line 384, in submit_errors
    issue = repo.create_issue(title_error, message)
  File "/app/sickrage/lib/github/Repository.py", line 885, in create_issue
    input=post_parameters
  File "/app/sickrage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/app/sickrage/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by benjired** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@d15b7003f8663b76d01fcbf0566389b2f31e0564
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [d15b700] Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 374, in submit_errors
    if report.create_comment(message):
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Issue.py", line 247, in create_comment
    input=post_parameters
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://help.github.com/articles/adding-an-email-address-to-your-github-account', u'message': u'At least one email address must be verified to do that.'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
