### ISSUE TITLE
[APP SUBMITTED]: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by KanedNUnable** [SickRage/SickRage#1373]
### INFO
Python Version: **2.7.3 (default, May 24 2013, 23:21:13) [GCC 4.5.4]**
Operating System: **Linux-3.14.2-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6e3ebea4d634d3e5894ae9b85eabffe4284be0ca
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [6e3ebea] Failed doing webui callback: Traceback (most recent call last):
  File "/share/1000/sickrage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/share/1000/sickrage/sickbeard/webserve.py", line 2302, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/share/1000/sickrage/sickbeard/processTV.py", line 247, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/share/1000/sickrage/sickbeard/processTV.py", line 575, in process_media
    result.result = processor.process()
  File "/share/1000/sickrage/sickbeard/postProcessor.py", line 1029, in process
    if int(ep_obj.season) > int(max_season[0][0]):
TypeError: int() argument must be a string or a number, not 'NoneType'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
fixed in develop

**Comment by Ramsdenj** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@bf18edd1aab8585977d3ffdbb5adcfd7e9b5fff5
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [bf18edd] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 289, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2301, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 295, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 575, in process_media
    result.result = processor.process()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 1107, in process
    proper_path = ep_obj.proper_path()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2361, in proper_path
    result = self.formatted_filename(anime_type=anime_type)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2416, in formatted_filename
    return sanitize_filename(self._format_pattern(name_groups[-1], multi, anime_type))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2204, in _format_pattern
    replace_map = self._replace_map()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2146, in _replace_map
    '%0E': '{0:02d}'.format(int(self.episode)),
TypeError: int() argument must be a string or a number, not 'NoneType'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Ramsdenj** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@bf18edd1aab8585977d3ffdbb5adcfd7e9b5fff5
No Log available with ERRORS:
### ERROR
```
Thread-20 :: [bf18edd] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 289, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2301, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 295, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 575, in process_media
    result.result = processor.process()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 1107, in process
    proper_path = ep_obj.proper_path()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2361, in proper_path
    result = self.formatted_filename(anime_type=anime_type)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2416, in formatted_filename
    return sanitize_filename(self._format_pattern(name_groups[-1], multi, anime_type))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2204, in _format_pattern
    replace_map = self._replace_map()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2146, in _replace_map
    '%0E': '{0:02d}'.format(int(self.episode)),
TypeError: int() argument must be a string or a number, not 'NoneType'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Ramsdenj** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@bf18edd1aab8585977d3ffdbb5adcfd7e9b5fff5
No Log available with ERRORS:
### ERROR
```
Thread-19 :: [bf18edd] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 289, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2301, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 295, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 575, in process_media
    result.result = processor.process()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 1107, in process
    proper_path = ep_obj.proper_path()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2361, in proper_path
    result = self.formatted_filename(anime_type=anime_type)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2416, in formatted_filename
    return sanitize_filename(self._format_pattern(name_groups[-1], multi, anime_type))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2204, in _format_pattern
    replace_map = self._replace_map()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2146, in _replace_map
    '%0E': '{0:02d}'.format(int(self.episode)),
TypeError: int() argument must be a string or a number, not 'NoneType'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by alienx2** [comment]
### INFO
Python Version: **2.7.11 (default, Mar 28 2016, 07:54:27) [GCC 5.3.0]**
Operating System: **Linux-2.6.36.4brcmarm-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@50e350eeb9ae6e0d8f26cff569e5ad85c991a863
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [50e350e] Failed doing webui callback: Traceback (most recent call last):
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/webserve.py", line 2290, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/processTV.py", line 290, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/processTV.py", line 560, in process_media
    result.result = processor.process()
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/postProcessor.py", line 1131, in process
    proper_path = ep_obj.proper_path()
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/tv.py", line 2356, in proper_path
    result = self.formatted_filename(anime_type=anime_type)
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/tv.py", line 2411, in formatted_filename
    return sanitize_filename(self._format_pattern(name_groups[-1], multi, anime_type))
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/tv.py", line 2199, in _format_pattern
    replace_map = self._replace_map()
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/tv.py", line 2141, in _replace_map
    '%0E': '{0:02d}'.format(int(self.episode)),
TypeError: int() argument must be a string or a number, not 'NoneType'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by alienx2** [comment]
### INFO
Python Version: **2.7.11 (default, Mar 28 2016, 07:54:27) [GCC 5.3.0]**
Operating System: **Linux-2.6.36.4brcmarm-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@50e350eeb9ae6e0d8f26cff569e5ad85c991a863
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [50e350e] Exception generated in thread POSTPROCESSER: int() argument must be a string or a number, not 'NoneType'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by xios01** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.3**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8564c29aa3b2d95bf41e03eed7e5a6938f1a6b3a
No Log available with ERRORS:
### ERROR
```
Thread-35 :: [8564c29] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/SickRage/sickbeard/webserve.py", line 4262, in savePostProcessing
    sickbeard.NAMING_ANIME = int(naming_anime)
TypeError: int() argument must be a string or a number, not 'NoneType'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by xios01** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.3**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8564c29aa3b2d95bf41e03eed7e5a6938f1a6b3a
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [8564c29] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/SickRage/sickbeard/webserve.py", line 4262, in savePostProcessing
    sickbeard.NAMING_ANIME = int(naming_anime)
TypeError: int() argument must be a string or a number, not 'NoneType'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ThePieMan** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@d15b7003f8663b76d01fcbf0566389b2f31e0564
No Log available with ERRORS:
### ERROR
```
Thread-127 :: [d15b700] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 4287, in savePostProcessing
    sickbeard.NAMING_ANIME = int(naming_anime)
TypeError: int() argument must be a string or a number, not 'NoneType'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ThePieMan** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@826b084110bdef33f9a519686286a5d6f02e1bcc
No Log available with ERRORS:
### ERROR
```
Thread-48 :: [826b084] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 284, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 4355, in savePostProcessing
    sickbeard.NAMING_ANIME = int(naming_anime)
TypeError: int() argument must be a string or a number, not 'NoneType'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sharkykh** [comment]
@ThePieMan This will be fixed soon.

In the meantime you can edit `config.ini`, look for the line `naming_anime=` and change it to `naming_anime=3`. This will fix the issue locally.
