### ISSUE TITLE
[APP SUBMITTED]: Thread-14 :: [98927da] Missing time zone for network: ITV 1

### ISSUE THREAD

**Issue by ipec** [SickRage/SickRage#1382]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@98927da437d1bcac38ef7aac72d819e6f0e91c2a
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [98927da] Missing time zone for network: ITV 1
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Added https://github.com/SickRage/sickrage.github.io/pull/132

**Comment by tjludico** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 11:15:51) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@8e2b26857c85a4bada2b6cc068279c081c7c8311
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [8e2b268] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 2302, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/processTV.py", line 247, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/processTV.py", line 575, in process_media
    result.result = processor.process()
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/postProcessor.py", line 947, in process
    (show, season, episodes, quality, version) = self._find_info()
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/postProcessor.py", line 642, in _find_info
    cur_show, cur_season, cur_episodes, cur_quality, cur_version = cur_attempt()
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/postProcessor.py", line 626, in <lambda>
    lambda: self._analyze_name(self.file_name),
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/postProcessor.py", line 557, in _analyze_name
    parse_result = NameParser(True, tryIndexers=True).parse(name)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/name_parser/parser.py", line 423, in parse
    file_name_result = self._parse_string(base_file_name)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/name_parser/parser.py", line 140, in _parse_string
    result.episode_numbers = range(ep_num, self._convert_number(match.group('extra_ep_num')) + 1)
MemoryError

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
