### ISSUE TITLE
Update w/big error

### ISSUE THREAD

**Issue by ncfitzge** [SickRage/SickRage#1385]
Branch/Commit: Master / 7f5b71e4ab83a6f6d2e65f5fb12e63bc74e5979a
OS: 	Linux-3.12.6-x86_64-with-glibc2.2.5
What you did: Installed update
What happened: Would not automatically reload
What you expected: Restart

Logs:
```
2016-04-08 16:16:48 INFO     SHOWQUEUE-REFRESH :: 295837: Updating NFOs for show with new indexer info
2016-04-08 16:16:45 INFO     SHOWQUEUE-REFRESH :: Performing refresh on Shadowhunters
2016-04-08 16:16:41 INFO     SHOWQUEUE-FORCE-UPDATE :: This episode Shadowhunters - S02E01 has no name on theTVDB. Setting to an empty string
2016-04-08 16:16:41 INFO     SHOWQUEUE-FORCE-UPDATE :: This episode Shadowhunters - S02E01 has no name on theTVDB. Setting to an empty string
2016-04-08 16:14:15 INFO     TORNADO :: Starting SickRage on https://0.0.0.0:7073/
2016-04-08 16:14:15 INFO     MAIN :: Starting SickRage [master] using '/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/config.ini'
2016-04-08 16:14:15 INFO     MAIN :: Writing PID: 28035 to /tmp/SickBeard-TVRage.pid
2016-04-08 16:14:12 INFO     EVENT-QUEUE :: Restarting SickRage with ['/opt/bin/python2.7', u'/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/SickBeard.py', '--daemon', '--datadir', '/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config', '--pidfile', '/tmp/SickBeard-TVRage.pid', '--nolaunch']
2016-04-08 16:14:12 INFO     EVENT-QUEUE :: Shutting down Tornado
2016-04-08 16:14:12 INFO     EVENT-QUEUE :: Saving config file to disk
2016-04-08 16:14:11 INFO     EVENT-QUEUE :: Saving all shows to the database
2016-04-08 16:14:11 INFO     EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2016-04-08 16:14:11 INFO     EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2016-04-08 16:14:11 INFO     EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2016-04-08 16:14:11 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2016-04-08 16:14:11 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSER thread to exit
2016-04-08 16:14:11 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE-DAILY-SEARCH thread to exit
2016-04-08 16:14:11 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE-REFRESH thread to exit
2016-04-08 16:14:11 INFO     EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2016-04-08 16:14:11 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2016-04-08 16:14:10 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
AATypeError: 'Undefined' object is not callable
AA    __M_writer(unicode(_('Show List')))
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/cache/mako/layouts/main.mako.py", line 206, in render_body
AA    callable_(context, *args, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/runtime.py", line 890, in _exec_template
AA    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/runtime.py", line 864, in _render_context
AA    **_kwargs_for_callable(callable_, data))
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/runtime.py", line 829, in _render
AA    as_unicode=True)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 454, in render_unicode
AA    return get_lookup().get_template('500.mako').render_unicode(*args, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 177, in render
AA    return self.finish(t.render(title='404', header='Oops'))
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 200, in write_error
AA    self.write_error(status_code, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tornado/web.py", line 976, in send_error
AATraceback (most recent call last):
AA2016-04-08 16:14:10 ERROR    Uncaught exception in write_error
AATypeError: 'Undefined' object is not callable
AA    __M_writer(unicode(_('Show List')))
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/cache/mako/layouts/main.mako.py", line 206, in render_body
AA    callable_(context, *args, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/runtime.py", line 890, in _exec_template
AA    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/runtime.py", line 864, in _render_context
AA    **_kwargs_for_callable(callable_, data))
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/runtime.py", line 829, in _render
AA    as_unicode=True)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 454, in render_unicode
AA    return get_lookup().get_template('500.mako').render_unicode(*args, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 177, in render
AA    controller="home", action="restart")
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 1202, in update
AA    result = function(**kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 285, in async_call
AATraceback (most recent call last):
AATypeError: 'Undefined' object is not callable
AA    __M_writer(unicode(_('Show List')))
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/cache/mako/layouts/main.mako.py", line 206, in render_body
AA    callable_(context, *args, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/runtime.py", line 890, in _exec_template
AA    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/runtime.py", line 864, in _render_context
AA    **_kwargs_for_callable(callable_, data))
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/runtime.py", line 829, in _render
AA    as_unicode=True)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 454, in render_unicode
AA    return get_lookup().get_template('500.mako').render_unicode(*args, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 177, in render
AA    controller="home", action="restart")
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 1202, in update
AA    result = function(**kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 285, in async_call
2016-04-08 16:14:10 ERROR    Thread-17 :: [7f5b71e] Failed doing webui callback: Traceback (most recent call last):
2016-04-08 16:14:10 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2016-04-08 16:14:10 INFO     EVENT-QUEUE :: Aborting all threads
2016-04-08 16:14:09 INFO     Thread-17 :: Config backup successful, updating...
2016-04-08 16:14:07 INFO     Thread-17 :: Config backup in progress...
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [ ] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Just restart, its a one time issue because the gettext strings are not loaded in your previous version. SR is fully translatable now, so I think the effort of you having to restart it one time manually isnt too much to ask.
