### ISSUE TITLE
SSL Error on 40 

### ISSUE THREAD

**Issue by ncfitzge** [SickRage/SickRage#1386]
I get this error every couple of weeks. Last week I received the error with an unknown IP address. 

Branch/Commit: Master / 7f5b71e4ab83a6f6d2e65f5fb12e63bc74e5979a / 
OS: Linux-3.12.6-x86_64-with-glibc2.2.5
What you did: Nothing
What happened: Nothing
What you expected: SSL to work (version OpenSSL 1.0.2f 28 Jan 2016)
Logs:
```
AASSLError: [SSL: HTTP_REQUEST] unknown error (_ssl.c:590)
AA  File "", line 3, in raise_exc_info
AA    raise_exc_info(self._exc_info)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tornado/concurrent.py", line 215, in result
AA    value = future.result()
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tornado/gen.py", line 870, in run
AA    quiet_exceptions=iostream.StreamClosedError)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tornado/http1connection.py", line 168, in _read_message
AA    yielded = self.gen.throw(*exc_info)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tornado/gen.py", line 876, in run
AA    raise_exc_info(self._exc_info)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tornado/concurrent.py", line 215, in result
AA    value = future.result()
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tornado/gen.py", line 870, in run
AA    ret = yield conn.read_response(request_delegate)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tornado/http1connection.py", line 693, in _server_request_loop
AATraceback (most recent call last):
AA2016-04-06 08:47:22 ERROR    Uncaught exception
AA2016-04-06 08:47:22 WARNING  SSL Error on 40 ('192.168.1.198', 51515): [SSL: HTTP_REQUEST] unknown error (_ssl.c:590)
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
https://github.com/SickRage/qnap-sickrage

**Comment by neoatomic** [comment]
http://forum.qnap.com/viewtopic.php?f=223&t=118366#p525730

**Comment by kevincw01** [comment]
this error isn't related to qnap.  I have this problem on windows and linux builds.  It happens when http client tries to connect to https configured sickrage.  https://github.com/SickRage/SickRage/pull/2553
