### ISSUE TITLE
[APP SUBMITTED]: u'kodi_hosts'

### ISSUE THREAD

**Issue by eroulland** [SickRage/SickRage#1438]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.6-3-osmc-armv7l-with-debian-8.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@21a0cb5d40d156d539338309c4fc46b38d52598c
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [21a0cb5] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1715, in updateKODI
    ui.notifications.message(_("Library update command sent to KODI host(s)): {kodi_hosts}").format(kodi_host=host))
KeyError: u'kodi_hosts'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by eroulland** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.6-3-osmc-armv7l-with-debian-8.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@21a0cb5d40d156d539338309c4fc46b38d52598c
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [21a0cb5] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1715, in updateKODI
    ui.notifications.message(_("Library update command sent to KODI host(s)): {kodi_hosts}").format(kodi_host=host))
KeyError: u'kodi_hosts'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by eroulland** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.6-3-osmc-armv7l-with-debian-8.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@21a0cb5d40d156d539338309c4fc46b38d52598c
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [21a0cb5] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1715, in updateKODI
    ui.notifications.message(_("Library update command sent to KODI host(s)): {kodi_hosts}").format(kodi_host=host))
KeyError: u'kodi_hosts'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by eroulland** [comment]
Hello

since this morning update, i have errors when i manually update kodi from menu.

I can reproduce it everytime.

Regards.
