### ISSUE TITLE
Won't start after update, localisation error?

### ISSUE THREAD

**Issue by jonand** [SickRage/SickRage#1442]
Branch/Commit: master
OS: OSX, running linuxserver/sickrage docker image
What you did: Updated SickRage
What happened: SickRage won't start
What you expected: I saw something in the release notes about localisation. The below error is probably related to this?
Logs:
```
IOError: [Errno 2] No translation file found for domain: 'messages'
Traceback (most recent call last):
  File "/app/sickrage/SickBeard.py", line 564, in <module>
    SickRage().start()
  File "/app/sickrage/SickBeard.py", line 313, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/app/sickrage/sickbeard/__init__.py", line 799, in initialize
    gettext.translation('messages', 'locale', languages=[GUI_LANG], codeset='UTF-8').install(unicode=1)
  File "/usr/lib/python2.7/gettext.py", line 487, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by jonand** [comment]
Setting the following environment variables in the SickRage Docker container fixed the problem:
~~~
LC_ALL=en_US.UTF-8  
LANG=en_US.UTF-8  
LANGUAGE=en_US.UTF-8  
~~~

The container already had this env variable, which apparently wasn't enough:
~~~
PYTHONIOENCODING=UTF-8
~~~
