### ISSUE TITLE
[APP SUBMITTED]: global name 'PROG_DIR' is not defined

### ISSUE THREAD

**Issue by chatainsim** [SickRage/SickRage#1443]
### INFO
Python Version: **2.7.3 (default, Jun 22 2015, 19:33:41) [GCC 4.6.3]**
Operating System: **Linux-3.13.0-83-generic-x86_64-with-Ubuntu-12.04-precise**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@752afdb7a46bab91190ea0798ce6f58fe11a6597
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [752afdb] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 3857, in saveGeneral
    gettext.translation('messages', os.path.join(PROG_DIR, 'locale'), languages=[gui_language], codeset='UTF-8').install(unicode=1)
NameError: global name 'PROG_DIR' is not defined

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by chatainsim** [comment]
### INFO
Python Version: **2.7.3 (default, Jun 22 2015, 19:33:41) [GCC 4.6.3]**
Operating System: **Linux-3.13.0-83-generic-x86_64-with-Ubuntu-12.04-precise**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@752afdb7a46bab91190ea0798ce6f58fe11a6597
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [752afdb] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 3857, in saveGeneral
    gettext.translation('messages', os.path.join(PROG_DIR, 'locale'), languages=[gui_language], codeset='UTF-8').install(unicode=1)
NameError: global name 'PROG_DIR' is not defined

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
Its fixed, was in a rush fixing a no-start situation with synology. SLAP ME.

**Comment by chatainsim** [comment]
woah that was fast ! Thanks !
