### ISSUE TITLE
Save function don't work.

### ISSUE THREAD

**Issue by xmenxmen** [SickRage/SickRage#1444]
Branch: master
Commit: 752afdb7a46bab91190ea0798ce6f58fe11a6597
Version: 2016.04.11-1

Synology DSM 6.0

After latest update the save function don't work in the ui.

2016-04-11 22:09:58 Thread-16 :: [752afdb] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 3860, in saveGeneral
    gettext.install('messages', os.path.join(PROG_DIR, 'locale'), unicode=1, codeset='UTF-8')
NameError: global name 'PROG_DIR' is not defined

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by xmenxmen** [comment]
Sorry i see now there where 9 more updates and now the save function is working again.
Sorry.
