### ISSUE TITLE
SR dumps translation error when trying to start

### ISSUE THREAD

**Issue by forkless** [SickRage/SickRage#1448]
Branch/Commit: master/394072f7cd865dcd0472e503fb903206b36d25f7
OS: Linux (QNAP on Python 2.7.11)
What you did: Starting SR
What you expected:  SR to start up 
What happened: Python error is being dumped
Logs:
```
Traceback (most recent call last):
  File "SickBeard.py", line 564, in <module>
    SickRage().start()
  File "SickBeard.py", line 313, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickbeard/__init__.py", line 799, in initialize
    gettext.translation('messages', 'locale', languages=[GUI_LANG], codeset='UTF-8').install(unicode=1)
  File "/opt/lib/python2.7/gettext.py", line 472, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
IOError: [Errno 2] No translation file found for domain: 'messages'

```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by forkless** [comment]
Problem resolved, git client did not properly pull down the latest revision.
