### ISSUE TITLE
Sickrage refuses to connect

### ISSUE THREAD

**Issue by Mondyboy** [SickRage/SickRage#1453]
I'm now getting this error when I open Sickrage:

> This site can’t be reached
> 
> localhost refused to connect.
> ERR_CONNECTION_REFUSED

I have auto-update on and I note there was an update earlier today.  Could it have broken SickRage.

I use the SickRage installer so I'm not sure how to revert back to an older version / update.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by iernie** [comment]
Yes, seems the last update broke it. I think I will have to stop using auto-update, it breaks SR too often.

```
Starting SickRage
Traceback (most recent call last):
  File "SickBeard.py", line 564, in <module>
    SickRage().start()
  File "SickBeard.py", line 313, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/apps/sickrage/app/sickbeard/__init__.py", line 799, in initialize
    gettext.translation('messages', 'locale', languages=[GUI_LANG], codeset='UTF-8').install(unicode=1)
  File "/usr/lib/python2.7/gettext.py", line 469, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
IOError: [Errno 2] No translation file found for domain: 'messages'
```

**Comment by iernie** [comment]
Editing `app/sickbeard/__init__.py` and commenting out lines 798-800 lets you start SR for long enough to run the update again that fixes the problem.

**Comment by ItsRaYnor** [comment]
Yep, commenting out lines 798-800 and updating did the trick.
For synology users: the location is /volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py

**Comment by neoatomic** [comment]
A simple update or Git Pull will solve this. 

@iernie Thanks for the quick workaround. That would also work.
