### ISSUE TITLE
AATypeError: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by Ramsdenj** [SickRage/SickRage#1542]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@bf18edd1aab8585977d3ffdbb5adcfd7e9b5fff5

```
AATypeError: int() argument must be a string or a number, not 'NoneType'
```
```
AATypeError: int() argument must be a string or a number, not 'NoneType'
AA    '%0E': '{0:02d}'.format(int(self.episode)),
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2146, in _replace_map
AA    replace_map = self._replace_map()
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2204, in _format_pattern
AA    return sanitize_filename(self._format_pattern(name_groups[-1], multi, anime_type))
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2416, in formatted_filename
AA    result = self.formatted_filename(anime_type=anime_type)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2361, in proper_path
AA    proper_path = ep_obj.proper_path()
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 1107, in process
AA    result.result = processor.process()
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 575, in process_media
AA    process_media(path, [video], nzbName, process_method, force, is_priority, result)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 247, in processDir
AA    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2301, in processEpisode
AA    result = function(**kwargs)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 289, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/concurrent/futures/thread.py", line 61, in run
AA    exec('raise exc_type, exc_value, traceback', {}, locals_)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/concurrent/futures/_compat.py", line 107, in reraise
AA    reraise(self._exception, self._traceback)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/concurrent/futures/_base.py", line 359, in __get_result
AA    return self.__get_result()
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/concurrent/futures/_base.py", line 400, in result
AA    value = future.result()
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tornado/gen.py", line 870, in run
AA    results = yield self.async_call(method)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 273, in get
AA    yielded = self.gen.throw(*exc_info)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tornado/gen.py", line 876, in run
AA    raise_exc_info(self._exc_info)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tornado/concurrent.py", line 215, in result
AA    value = future.result()
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tornado/gen.py", line 870, in run
AA    result = yield result
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tornado/web.py", line 1415, in _execute
AATraceback (most recent call last):
AAHTTPServerRequest(protocol='http', host='192.168.0.5:8081', method='POST', uri='/home/postprocess/processEpisode', version='HTTP/1.1', remote_ip='192.168.0.2', headers={'Origin': 'http://192.168.0.5:8081', 'Content-Length': '119', 'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.0.5:8081', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Dnt': '1', 'Connection': 'keep-alive', 'Referer': 'http://192.168.0.5:8081/home/postprocess/', 'Cache-Control': 'max-age=0', 'Cookie': 'sickrage_user="2|1:0|10:1460584120|13:sickrage_user|44:ZjIyYzA0YzE2Zjc0Y2Q1Y2U3ZTNhYWVlMmVmNzIyZmY=|7d27cb1158856523249e648371da9a939a2021d9e5a79598652239ac2512811c"', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded'})
AA2016-04-17 15:13:56 ERROR    Uncaught exception POST /home/postprocess/processEpisode (192.168.0.2)
AATypeError: int() argument must be a string or a number, not 'NoneType'
AA    '%0E': '{0:02d}'.format(int(self.episode)),
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2146, in _replace_map
AA    replace_map = self._replace_map()
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2204, in _format_pattern
AA    return sanitize_filename(self._format_pattern(name_groups[-1], multi, anime_type))
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2416, in formatted_filename
AA    result = self.formatted_filename(anime_type=anime_type)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2361, in proper_path
AA    proper_path = ep_obj.proper_path()
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 1107, in process
AA    result.result = processor.process()
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 575, in process_media
AA    process_media(path, [video], nzbName, process_method, force, is_priority, result)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 247, in processDir
AA    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2301, in processEpisode
AA    result = function(**kwargs)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 289, in async_call
AATraceback (most recent call last):
AATypeError: int() argument must be a string or a number, not 'NoneType'
AA    '%0E': '{0:02d}'.format(int(self.episode)),
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2146, in _replace_map
AA    replace_map = self._replace_map()
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2204, in _format_pattern
AA    return sanitize_filename(self._format_pattern(name_groups[-1], multi, anime_type))
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2416, in formatted_filename
AA    result = self.formatted_filename(anime_type=anime_type)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2361, in proper_path
AA    proper_path = ep_obj.proper_path()
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 1107, in process
AA    result.result = processor.process()
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 575, in process_media
AA    process_media(path, [video], nzbName, process_method, force, is_priority, result)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 247, in processDir
AA    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2301, in processEpisode
AA    result = function(**kwargs)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 289, in async_call
2016-04-17 15:13:56 ERROR    Thread-15 :: [bf18edd] Failed doing webui callback: Traceback (most recent call last):
2016-04-17 15:13:56 INFO     Thread-15 :: Processing /media/Downloads/Complete/Fate Stay Night - Unlimited Blade Works/[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 00 [1080p].mkv (None)
2016-04-17 15:13:56 INFO     Thread-15 :: PostProcessing Path: /media/Downloads/Complete/Fate Stay Night - Unlimited Blade Works
2016-04-17 15:13:01 ERROR    Thread-18 :: [bf18edd] Failed doing webui callback: Traceback (most recent call last):
2016-04-17 15:13:01 INFO     Thread-18 :: Processing /media/Downloads/Complete/Fate Stay Night - Unlimited Blade Works/[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 00 [1080p].mkv (None)
2016-04-17 15:13:01 INFO     Thread-18 :: PostProcessing Path: /media/Downloads/Complete/Fate Stay Night - Unlimited Blade Works
2016-04-17 15:12:36 ERROR    Thread-13 :: [bf18edd] Failed doing webui callback: Traceback (most recent call last):
2016-04-17 15:12:36 INFO     Thread-13 :: Processing /media/Downloads/Complete/Fate Stay Night - Unlimited Blade Works/[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 00 [1080p].mkv (None)
2016-04-17 15:12:35 INFO     Thread-13 :: PostProcessing Path: /media/Downloads/Complete/Fate Stay Night - Unlimited Blade Works
2016-04-17 15:12:23 ERROR    Thread-20 :: [bf18edd] Failed doing webui callback: Traceback (most recent call last):
2016-04-17 15:12:23 INFO     Thread-20 :: Processing /media/Downloads/Complete/Fate Stay Night - Unlimited Blade Works/[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 00 [1080p].mkv (None)
2016-04-17 15:12:22 INFO     Thread-20 :: Processing succeeded for /media/Downloads/Complete/Fresh.Off.the.Boat.S02E04.The.Fall.Ball.1080p.WEB-DL.DD5.1.H.264-NTb.mkv
2016-04-17 15:12:19 INFO     Thread-20 :: This download is marked a priority download so I'm going to replace an existing file if I find one
2016-04-17 15:12:19 INFO     Thread-20 :: Processing /media/Downloads/Complete/Fresh.Off.the.Boat.S02E04.The.Fall.Ball.1080p.WEB-DL.DD5.1.H.264-NTb.mkv (None)
2016-04-17 15:12:19 INFO     Thread-20 :: PostProcessing Path: /media/Downloads/Complete
2016-04-17 15:11:54 INFO     Thread-16 :: Your issue ticket #1543 was submitted successfully!
2016-04-17 15:10:21 ERROR    POSTPROCESSER :: [bf18edd] Exception generated in thread POSTPROCESSER: int() argument must be a string or a number, not 'NoneType'
2016-04-17 15:10:21 INFO     POSTPROCESSER :: Processing /media/Downloads/Complete/[HorribleSubs] Fate Stay Night - Unlimited Blade Works (00-25) [1080p] (Batch)/[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 00 [1080p].mkv (None)
2016-04-17 15:10:20 INFO     POSTPROCESSER :: PostProcessing Path: /media/Downloads/Complete
2016-04-17 15:07:56 ERROR    Thread-14 :: [bf18edd] Failed doing webui callback: Traceback (most recent call last):
2016-04-17 15:07:56 INFO     Thread-14 :: Processing /media/Downloads/Complete/[HorribleSubs] Fate Stay Night - Unlimited Blade Works (00-25) [1080p] (Batch)/[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 00 [1080p].mkv (None)
2016-04-17 15:07:56 INFO     Thread-14 :: PostProcessing Path: /media/Downloads/Complete
2016-04-17 15:07:38 ERROR    Thread-14 :: [bf18edd] Failed doing webui callback: Traceback (most recent call last):
2016-04-17 15:07:38 INFO     Thread-14 :: Processing /media/Downloads/Complete/[HorribleSubs] Fate Stay Night - Unlimited Blade Works (00-25) [1080p] (Batch)/[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 00 [1080p].mkv (None)
2016-04-17 15:07:37 INFO     Thread-14 :: PostProcessing Path: /media/Downloads/Complete
2016-04-17 15:06:56 ERROR    Thread-20 :: [bf18edd] Failed doing webui callback: Traceback (most recent call last):
2016-04-17 15:06:56 INFO     Thread-20 :: Processing /media/Downloads/Complete/[HorribleSubs] Fate Stay Night - Unlimited Blade Works (00-25) [1080p] (Batch)/[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 00 [1080p].mkv (None)
2016-04-17 15:06:56 INFO     Thread-20 :: PostProcessing Path: /media/Downloads/Complete
2016-04-17 15:06:48 ERROR    Thread-19 :: [bf18edd] Failed doing webui callback: Traceback (most recent call last):
2016-04-17 15:06:48 INFO     Thread-19 :: Processing /media/Downloads/Complete/[HorribleSubs] Fate Stay Night - Unlimited Blade Works (00-25) [1080p] (Batch)/[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 00 [1080p].mkv (None)
2016-04-17 15:06:47 INFO     Thread-19 :: Processing succeeded for /media/Downloads/Complete/Fresh Off The Boat S02E01 Family Business Trip Web-DL 5.1 1080p x265 HEVC-ByteShare[UTR].mkv
2016-04-17 15:06:44 INFO     Thread-19 :: This download is marked a priority download so I'm going to replace an existing file if I find one
2016-04-17 15:06:44 INFO     Thread-19 :: Processing /media/Downloads/Complete/Fresh Off The Boat S02E01 Family Business Trip Web-DL 5.1 1080p x265 HEVC-ByteShare[UTR].mkv (None)
2016-04-17 15:06:44 INFO     Thread-19 :: PostProcessing Path: /media/Downloads/Complete
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
