### ISSUE TITLE
[APP SUBMITTED]: 512

### ISSUE THREAD

**Issue by wpmccormick** [SickRage/SickRage#1600]
### INFO
Python Version: **2.7.11 (default, Jan 29 2016, 03:45:04) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@d9d9ead0938a8e736a35aa45e1f37147dd0cdf49
No Log available with ERRORS:
### ERROR
```
TORNADO :: [d9d9ead] API :: error 512
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Without debug logs and more info, we cant do much...

I suspect you where using a third party app that hasn't been updated for some time and uses the Sickrage API not correctly.

**Comment by raistlin2912** [comment]
### INFO
Python Version: **2.7.11+ (default, Apr 17 2016, 14:00:29) [GCC 5.3.1 20160413]**
Operating System: **Linux-4.4.0-22-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ffcea549ea699fb27937324c8f33bd91da264ce4
No Log available with ERRORS:
### ERROR
```
TORNADO :: [ffcea54] API :: error 512
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by zaggash** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@946f6be31a26c661a5e0903c5d66e4ce348ce19d
No Log available with ERRORS:
### ERROR
```
TORNADO :: [946f6be] API :: error 512
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by blosters** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 12:07:24) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@946f6be31a26c661a5e0903c5d66e4ce348ce19d
No Log available with ERRORS:
### ERROR
```
TORNADO :: [946f6be] API :: error 512
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by zaggash** [comment]
More information about the error posted from me earlier

2016-06-05 21:50:13 DEBUG TORNADO :: API :: all args: '()' 2016-06-05 21:50:13 DEBUG TORNADO :: API :: 172.18.0.2 - gave correct API KEY. ACCESS GRANTED AAKeyError: 512 AA any_qualities.append(quality_map[quality]) AA File "/app/sickrage/sickbeard/webapi.py", line 544, in _map_quality AA any_qualities, best_qualities = _map_quality(show_obj.quality) AA File "/app/sickrage/sickbeard/webapi.py", line 1898, in run AA cur_out_dict = func(cur_args, cur_kwargs).run() # call function and get response AA File "/app/sickrage/sickbeard/webapi.py", line 204, in call_dispatcher AA out_dict = _call_dispatcher(args, kwargs) AA File "/app/sickrage/sickbeard/webapi.py", line 136, in get AATraceback (most recent call last): 2016-06-05 21:50:13 ERROR TORNADO :: [946f6be] API :: error 512 2016-06-05 21:50:13 DEBUG TORNADO :: API :: show: cur_kwargs {'indexerid': '243011'} 2016-06-05 21:50:13 DEBUG TORNADO :: API :: all kwargs: '{'indexerid': '243011', 'cmd': 'show'}' 2016-06-05 21:50:13 DEBUG TORNADO :: API :: all args: '()' 2016-06-05 21:50:13 DEBUG TORNADO :: API :: 172.18.0.2 - gave correct API KEY. ACCESS GRANTED

**Comment by quatrecentquatrenews** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@34d0987400b3d50f550f55472d417c4e5b263f55
No Log available with ERRORS:
### ERROR
```
TORNADO :: [34d0987] API :: error 512
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by emphaticsunshine** [comment]
### INFO
Python Version: **2.7.11 (default, Feb 17 2016, 07:58:43) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@75042d8c406bb4356d88b6b67a73c847a56ce3f3
No Log available with ERRORS:
### ERROR
```
TORNADO :: [75042d8] API :: error 512
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by bwguy** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 13:51:44) [GCC 4.8.5]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@027a950fe0ac81a6d3a139f5ad68cfbaa8c85e9f
No Log available with ERRORS:
### ERROR
```
TORNADO :: [027a950] API :: error 512
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by megabitus98** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.21-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@027a950fe0ac81a6d3a139f5ad68cfbaa8c85e9f
No Log available with ERRORS:
### ERROR
```
TORNADO :: [027a950] API :: error 512
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by bwguy** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 13:51:44) [GCC 4.8.5]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@d7e460ee1fee1be796e5195ee3b104afc1d2c0c7
No Log available with ERRORS:
### ERROR
```
TORNADO :: [d7e460e] API :: error 512
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by bwguy** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 13:51:44) [GCC 4.8.5]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.0**
Locale: None
Branch: ****
Commit: SickRage/SickRage@8d1b96f507b88b3098387c5004b88db4f54a0b41
No Log available with ERRORS:
### ERROR
```
TORNADO :: [8d1b96f] API :: error 512
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
