### ISSUE TITLE
[APP SUBMITTED]: Thread-15 :: [d9d9ead] Missing time zone for network: Style TV

### ISSUE THREAD

**Issue by Vodka2014** [SickRage/SickRage#1604]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@d9d9ead0938a8e736a35aa45e1f37147dd0cdf49
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [d9d9ead] Missing time zone for network: Style TV
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by tjludico** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.6-3-osmc-armv7l-with-debian-8.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@d9d9ead0938a8e736a35aa45e1f37147dd0cdf49
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [d9d9ead] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 289, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2301, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "/opt/sickrage/sickbeard/processTV.py", line 247, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/opt/sickrage/sickbeard/processTV.py", line 575, in process_media
    result.result = processor.process()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 947, in process
    (show, season, episodes, quality, version) = self._find_info()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 642, in _find_info
    cur_show, cur_season, cur_episodes, cur_quality, cur_version = cur_attempt()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 626, in <lambda>
    lambda: self._analyze_name(self.file_name),
  File "/opt/sickrage/sickbeard/postProcessor.py", line 557, in _analyze_name
    parse_result = NameParser(True, tryIndexers=True).parse(name)
  File "/opt/sickrage/sickbeard/name_parser/parser.py", line 423, in parse
    file_name_result = self._parse_string(base_file_name)
  File "/opt/sickrage/sickbeard/name_parser/parser.py", line 140, in _parse_string
    result.episode_numbers = range(ep_num, self._convert_number(match.group('extra_ep_num')) + 1)
MemoryError

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
