### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: u'/config/cache/mako/home.mako.py'

### ISSUE THREAD

**Issue by gshlomi** [SickRage/SickRage#1651]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-4.1.18-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@e9bdd33444c3aaff22418c67b40682f5ae898caa
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [e9bdd33] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 289, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 719, in index
    return t.render(title=_("Home"), header=_("Show List"), topmenu="home", showlists=showlists, show_stat=stats[0], max_download_count=stats[1], controller="home", action="index")
  File "/app/sickrage/sickbeard/webserve.py", line 179, in render
    kwargs['backtrace'] = RichTraceback()
  File "/app/sickrage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/app/sickrage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/app/sickrage/lib/mako/template.py", line 632, in code
    return util.read_python_file(self.module_filename)
  File "/app/sickrage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/config/cache/mako/home.mako.py'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by gshlomi** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-4.1.18-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@e9bdd33444c3aaff22418c67b40682f5ae898caa
No Log available with ERRORS:
### ERROR
```
Thread-18 :: [e9bdd33] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 289, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 719, in index
    return t.render(title=_("Home"), header=_("Show List"), topmenu="home", showlists=showlists, show_stat=stats[0], max_download_count=stats[1], controller="home", action="index")
  File "/app/sickrage/sickbeard/webserve.py", line 179, in render
    kwargs['backtrace'] = RichTraceback()
  File "/app/sickrage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/app/sickrage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/app/sickrage/lib/mako/template.py", line 632, in code
    return util.read_python_file(self.module_filename)
  File "/app/sickrage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/config/cache/mako/home.mako.py'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by gshlomi** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-4.1.18-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@e9bdd33444c3aaff22418c67b40682f5ae898caa
No Log available with ERRORS:
### ERROR
```
Thread-17 :: [e9bdd33] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 289, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 719, in index
    return t.render(title=_("Home"), header=_("Show List"), topmenu="home", showlists=showlists, show_stat=stats[0], max_download_count=stats[1], controller="home", action="index")
  File "/app/sickrage/sickbeard/webserve.py", line 179, in render
    kwargs['backtrace'] = RichTraceback()
  File "/app/sickrage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/app/sickrage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/app/sickrage/lib/mako/template.py", line 632, in code
    return util.read_python_file(self.module_filename)
  File "/app/sickrage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/config/cache/mako/home.mako.py'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
1. Dont delete the cache/mako folder while SR is running.
2. Make sure the cache folder is writable.

**Comment by speedracer76** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-4.1.18-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@61b8a1965bcee524b557a667fa11ffdece31ba72
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [61b8a19] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 700, in index
    return t.render(title=_("Home"), header=_("Show List"), topmenu="home", showlists=showlists, show_stat=stats[0], max_download_count=stats[1], controller="home", action="index")
  File "/app/sickrage/sickbeard/webserve.py", line 160, in render
    kwargs['backtrace'] = RichTraceback()
  File "/app/sickrage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/app/sickrage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/app/sickrage/lib/mako/template.py", line 632, in code
    return util.read_python_file(self.module_filename)
  File "/app/sickrage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/config/cache/mako/home.mako.py'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
1. Dont delete the cache/mako folder while SR is running.
2. Make sure the cache folder is writable.
