### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: u'/opt/sickrage/cache/mako/home.mako.py'

### ISSUE THREAD

**Issue by Orion83** [SickRage/SickRage#1660]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-54-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2f6204d2500bdfa328fe572e0f1ab88058fe25d3
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [2f6204d] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 289, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 719, in index
    return t.render(title=_("Home"), header=_("Show List"), topmenu="home", showlists=showlists, show_stat=stats[0], max_download_count=stats[1], controller="home", action="index")
  File "/opt/sickrage/sickbeard/webserve.py", line 179, in render
    kwargs['backtrace'] = RichTraceback()
  File "/opt/sickrage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/opt/sickrage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/opt/sickrage/lib/mako/template.py", line 632, in code
    return util.read_python_file(self.module_filename)
  File "/opt/sickrage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/opt/sickrage/cache/mako/home.mako.py'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duramato** [comment]
Dont clear your mako cache with SR running.

**Comment by icetail** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-59-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@b790df702cf1ef84ee64b591f40ce6fae86976dc
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [b790df7] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 700, in index
    return t.render(title=_("Home"), header=_("Show List"), topmenu="home", showlists=showlists, show_stat=stats[0], max_download_count=stats[1], controller="home", action="index")
  File "/opt/sickrage/sickbeard/webserve.py", line 160, in render
    kwargs['backtrace'] = RichTraceback()
  File "/opt/sickrage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/opt/sickrage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/opt/sickrage/lib/mako/template.py", line 632, in code
    return util.read_python_file(self.module_filename)
  File "/opt/sickrage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/opt/sickrage/cache/mako/home.mako.py'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by prophead67** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-60-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@a70d27a14ed62fd54939d5a8e5210e33a76afd97
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [a70d27a] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 700, in index
    return t.render(title=_("Home"), header=_("Show List"), topmenu="home", showlists=showlists, show_stat=stats[0], max_download_count=stats[1], controller="home", action="index")
  File "/opt/sickrage/sickbeard/webserve.py", line 160, in render
    kwargs['backtrace'] = RichTraceback()
  File "/opt/sickrage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/opt/sickrage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/opt/sickrage/lib/mako/template.py", line 632, in code
    return util.read_python_file(self.module_filename)
  File "/opt/sickrage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/opt/sickrage/cache/mako/home.mako.py'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by prophead67** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-60-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@a70d27a14ed62fd54939d5a8e5210e33a76afd97
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [a70d27a] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 700, in index
    return t.render(title=_("Home"), header=_("Show List"), topmenu="home", showlists=showlists, show_stat=stats[0], max_download_count=stats[1], controller="home", action="index")
  File "/opt/sickrage/sickbeard/webserve.py", line 160, in render
    kwargs['backtrace'] = RichTraceback()
  File "/opt/sickrage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/opt/sickrage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/opt/sickrage/lib/mako/template.py", line 632, in code
    return util.read_python_file(self.module_filename)
  File "/opt/sickrage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/opt/sickrage/cache/mako/home.mako.py'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
