### ISSUE TITLE
[APP SUBMITTED]: UNIQUE constraint failed: xem_refresh.indexer_id

### ISSUE THREAD

**Issue by alienx2** [SickRage/SickRage#1720]
### INFO
Python Version: **2.7.11 (default, Mar 28 2016, 07:54:27) [GCC 5.3.0]**
Operating System: **Linux-2.6.36.4brcmarm-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@10f768a5492d04b34f1b14ec4e9dcb7eb697c91c
No Log available with ERRORS:
### ERROR
```
Thread-173 :: [10f768a] Fatal error executing query: UNIQUE constraint failed: xem_refresh.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by alienx2** [comment]
### INFO
Python Version: **2.7.11 (default, Mar 28 2016, 07:54:27) [GCC 5.3.0]**
Operating System: **Linux-2.6.36.4brcmarm-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@10f768a5492d04b34f1b14ec4e9dcb7eb697c91c
No Log available with ERRORS:
### ERROR
```
Thread-173 :: [10f768a] Failed doing webui callback: Traceback (most recent call last):
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/webserve.py", line 289, in async_call
    result = function(**kwargs)
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/webserve.py", line 1387, in displayShow
    xem_numbering=get_xem_numbering_for_show(indexerid, indexer),
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/scene_numbering.py", line 383, in get_xem_numbering_for_show
    xem_refresh(indexer_id, indexer)
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/scene_numbering.py", line 491, in xem_refresh
    {'indexer_id': indexer_id}
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/db.py", line 331, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
IntegrityError: UNIQUE constraint failed: xem_refresh.indexer_id

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by alienx2** [comment]
### INFO
Python Version: **2.7.11 (default, Mar 28 2016, 07:54:27) [GCC 5.3.0]**
Operating System: **Linux-2.6.36.4brcmarm-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@10f768a5492d04b34f1b14ec4e9dcb7eb697c91c
No Log available with ERRORS:
### ERROR
```
Thread-174 :: [10f768a] Fatal error executing query: UNIQUE constraint failed: xem_refresh.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by alienx2** [comment]
### INFO
Python Version: **2.7.11 (default, Mar 28 2016, 07:54:27) [GCC 5.3.0]**
Operating System: **Linux-2.6.36.4brcmarm-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@10f768a5492d04b34f1b14ec4e9dcb7eb697c91c
No Log available with ERRORS:
### ERROR
```
Thread-174 :: [10f768a] Failed doing webui callback: Traceback (most recent call last):
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/webserve.py", line 289, in async_call
    result = function(**kwargs)
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/webserve.py", line 1387, in displayShow
    xem_numbering=get_xem_numbering_for_show(indexerid, indexer),
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/scene_numbering.py", line 383, in get_xem_numbering_for_show
    xem_refresh(indexer_id, indexer)
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/scene_numbering.py", line 491, in xem_refresh
    {'indexer_id': indexer_id}
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/db.py", line 331, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
IntegrityError: UNIQUE constraint failed: xem_refresh.indexer_id

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by alienx2** [comment]
### INFO
Python Version: **2.7.11 (default, Mar 28 2016, 07:54:27) [GCC 5.3.0]**
Operating System: **Linux-2.6.36.4brcmarm-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@10f768a5492d04b34f1b14ec4e9dcb7eb697c91c
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [10f768a] Fatal error executing query: UNIQUE constraint failed: xem_refresh.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by alienx2** [comment]
### INFO
Python Version: **2.7.11 (default, Mar 28 2016, 07:54:27) [GCC 5.3.0]**
Operating System: **Linux-2.6.36.4brcmarm-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@10f768a5492d04b34f1b14ec4e9dcb7eb697c91c
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [10f768a] Exception generated in thread DAILYSEARCHER: UNIQUE constraint failed: xem_refresh.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
Stop SR and delete cache.db. Looks like you are trying to migrate some existing db from another fork?

**Comment by miigotu** [comment]
Actually, that is in sickbeard.db, you will need to recreate your db somehow. This is due to a broken db. Maybe you copied it with SR was running?

**Comment by alienx2** [comment]
no i didnt do copy from other fork or other device.. it was working ongoing long time until last night that happen..

**Comment by miigotu** [comment]
check the disk, it might be failing, or the db got corrupted from an unexpected reboot

**Comment by alienx2** [comment]
disk went to read file system only.. SR database are safe. i think its something wrong with disk.

**Comment by alienx2** [comment]
i found out disk corrupt I/O read error. =(

**Comment by mrkuolematon** [comment]
I'm running in the same issue... What did you do to solve it?

**Comment by mrkuolematon** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.10+-armv7l-with-debian-8.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@89676eb74a3fc9f765f17db291c9134df2537e38
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [89676eb] Fatal error executing query: UNIQUE constraint failed: xem_refresh.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mrkuolematon** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.10+-armv7l-with-debian-8.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@89676eb74a3fc9f765f17db291c9134df2537e38
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [89676eb] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1368, in displayShow
    xem_numbering=get_xem_numbering_for_show(indexerid, indexer),
  File "/opt/sickrage/sickbeard/scene_numbering.py", line 383, in get_xem_numbering_for_show
    xem_refresh(indexer_id, indexer)
  File "/opt/sickrage/sickbeard/scene_numbering.py", line 491, in xem_refresh
    {'indexer_id': indexer_id}
  File "/opt/sickrage/sickbeard/db.py", line 331, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/opt/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
IntegrityError: UNIQUE constraint failed: xem_refresh.indexer_id

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mrkuolematon** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.10+-armv7l-with-debian-8.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@89676eb74a3fc9f765f17db291c9134df2537e38
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [89676eb] Fatal error executing query: UNIQUE constraint failed: xem_refresh.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mrkuolematon** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.10+-armv7l-with-debian-8.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@89676eb74a3fc9f765f17db291c9134df2537e38
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [89676eb] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1368, in displayShow
    xem_numbering=get_xem_numbering_for_show(indexerid, indexer),
  File "/opt/sickrage/sickbeard/scene_numbering.py", line 383, in get_xem_numbering_for_show
    xem_refresh(indexer_id, indexer)
  File "/opt/sickrage/sickbeard/scene_numbering.py", line 491, in xem_refresh
    {'indexer_id': indexer_id}
  File "/opt/sickrage/sickbeard/db.py", line 331, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/opt/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
IntegrityError: UNIQUE constraint failed: xem_refresh.indexer_id

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by pcmerc** [comment]
### INFO
Python Version: **3.7.9 (default, Sep  6 2020, 17:42:42) [GCC 6.3.0 20170516]**
Operating System: **Linux-4.9.0-11-amd64-x86_64-with-debian-9.13**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@34112a6279de83bb8671246dbf1b1f942d10915b
No Log available with ERRORS:
### ERROR
```
Fatal error executing query with db.action in database /opt/SickChill/sickchill.db: UNIQUE constraint failed: xem_refresh.indexer_id
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by pcmerc** [comment]
### INFO
Python Version: **3.7.9 (default, Sep  6 2020, 17:42:42) [GCC 6.3.0 20170516]**
Operating System: **Linux-4.9.0-11-amd64-x86_64-with-debian-9.13**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@34112a6279de83bb8671246dbf1b1f942d10915b
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
