### ISSUE TITLE
Error when mass update: pausing all shows

### ISSUE THREAD

**Issue by syrys** [SickRage/SickRage#1722]
I have the need to pause all the shows (doing a server migration). So, i got 2 errors attempting to do so. 

First of all, when i click mass update, check all shows, and click edit, i get an alart saying i have too many characters. "you've selected too many shows, please remove some and try again. [2200/2083 characters]".

Secondly, when i unchecked enough to get past the first error, then select pause to Yes and click submit (so editing all selected shows and setting paused to true) i get the following: http://pastebin.com/8ZjFNUzh
On my SR error log, i see the following:
````
2016-05-09 18:00:56 Thread-24 :: [10f768a] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 289, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 3450, in massEditSubmit
    directCall=True)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 1569, in editShow
    location = location.decode('UTF-8')
  File "C:\SickRage\Python\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x96 in position 36: invalid start byte
````
After the above said error, when i view my pass update page, half the shows have updated with paused set to yes, but half isnt.

Branch: master
Commit: 10f768a5492d04b34f1b14ec4e9dcb7eb697c91c
Version: 2016.04.28-1
Python Version:	2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
OS:	Windows 10

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by syrys** [comment]
The show the error is throwing at is called: "Pokémon Chronicles". 

I managed to pause bunch at a time, and managed to pause everything but this show. im assuming it has something to do with the funny character in the name.

**Comment by neoatomic** [comment]
Indeed, its the `é` that is causing the issue.
Windows isn't very forgiving when it comes to special characters.

At this point not much can be done...

**Comment by syrys** [comment]
@neoatomic Well, what can i do? Can i even delete it? When you pull the show info from the show database, cant you just convert it to a more friendlier character? like "e"?

**Comment by duramato** [comment]
`e` isn't `é`, same reason you can't convert a Greek `alpha` to an `a`

**Comment by syrys** [comment]
@duramato i understand the difference between `e` and `é`. Personally, i dont care what `é` gets translated/mapped into (was just trying to suggest a solution). What alternative do we have, "dont add shows with funny characters", and "if you did add shows with funny characters, you are screwed"?

Seriously though, ignore my suggestions if it sounds stupid (my bad), was just trying to be helpful. Instead of trying to be helpful, let me ask you the question i should have asked: **what should i do?**

**Comment by duramato** [comment]
The issue is with Windows locale, unlike a pure utf-8 that knows what maps to what window's locale,  from my understanding  lacks  some, like ASCII only has very little characters

**Comment by neoatomic** [comment]
@syrys If it was that easy, that it was already fixed. :)

Its a Python2/Windows locale issue, and only Python3 capability will be able to solve that. 
And there is the fact that external API's also dont always support special characters. and so i can go on and on...

So if you are running SR on Windows, than this is one of the issues you can come across...
(If you where running on Linux all would be fine.)
