### ISSUE TITLE
Sickrage wont start after last autoupdate

### ISSUE THREAD

**Issue by marka65** [SickRage/SickRage#1731]
**Branch/Commit:** master / 619a1a43b16853f533f932d72cd58b139877b150
**OS:** QNAP TS-853 Pro
**What you did:** Nothing - noticed that the SickRage web page was unavailable
**What happened:** Tried restarting SickRage and still no web page.
**What you expected:** Application to start up and be usable. Logged in to console via putty and ran startup manually to see what was being output to the console.

**Logs:**
[admin@QNAPIV SickBeard-TVRage]$ sh sickbeard-tvrage.sh start
x86_64
SickBeard-TVRage prestartup checks...
 Checking for git...  Found!
Looking for /usr/bin/python2.7
Looking for /usr/local/bin/python2.7
Looking for /opt/bin/python2.7
Looking for /Apps/opt/bin/python2.7
Looking for /opt/QPython2/bin/python2.7
Found Python Version 2.7.5 at /usr/local/bin/python2.7
Updating SickBeard-TVRage
git: /opt/lib/libcrypto.so.0.9.8: no version information available (required by git)
HEAD is now at 619a1a4 Fixes #1715
git: /opt/lib/libcrypto.so.0.9.8: no version information available (required by git)
git: /opt/lib/libcrypto.so.0.9.8: no version information available (required by git)
git: /opt/lib/libcrypto.so.0.9.8: no version information available (required by git)
git: /opt/lib/libcrypto.so.0.9.8: no version information available (required by git)
git: /opt/lib/libcrypto.so.0.9.8: no version information available (required by git)
git: /opt/lib/libcrypto.so.0.9.8: no version information available (required by git)
git: /opt/lib/libcrypto.so.0.9.8: no version information available (required by git)
git: /opt/lib/libcrypto.so.0.9.8: no version information available (required by git)
git: /opt/lib/libcrypto.so.0.9.8: no version information available (required by git)
git: /opt/lib/libcrypto.so.0.9.8: no version information available (required by git)
git: /opt/lib/libcrypto.so.0.9.8: no version information available (required by git)
git-remote-https: /opt/lib/libcrypto.so.0.9.8: no version information available (required by git-remote-https)
git-remote-https: /opt/lib/libcrypto.so.0.9.8: no version information available (required by /Apps/git/lib/libcurl.so.4)
git-remote-https: /opt/lib/libssl.so.0.9.8: no version information available (required by /Apps/git/lib/libcurl.so.4)
git: /opt/lib/libcrypto.so.0.9.8: no version information available (required by git)
git: /opt/lib/libcrypto.so.0.9.8: no version information available (required by git)
git: /opt/lib/libcrypto.so.0.9.8: no version information available (required by git)
git: /opt/lib/libcrypto.so.0.9.8: no version information available (required by git)
git-merge: /opt/lib/libcrypto.so.0.9.8: no version information available (required by git-merge)
Already up-to-date.
Starting SickBeard-TVRage
Traceback (most recent call last):
  File "SickBeard.py", line 94, in <module>
    import sickbeard
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/__init__.py", line 39, in <module>
    from sickbeard.indexers import indexer_api
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/indexers/__init__.py", line 21, in <module>
    from . import indexer_api
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/indexers/indexer_api.py", line 26, in <module>
    from indexer_config import initConfig
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/indexers/indexer_config.py", line 3, in <module>
    from tvdb_api.tvdb_api import Tvdb
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tvdb_api/tvdb_api.py", line 24, in <module>
    import requests
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/compat.py", line 39, in <module>
    import cookielib
ImportError: No module named cookielib

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
This is not a SR problem, it is your environment.

First, libssl is missing. Second, your python is outdated and wont work with site that now use newer ssl encryption (almost all of them that use https)

Third, cookielib is part of the python standard library. https://hg.python.org/cpython/file/2.7/Lib/cookielib.py

**Comment by marka65** [comment]
Thanks for the response and information.

It has been working fine until this morning. Will try and upgrade these components you say are out of date.

**Comment by miigotu** [comment]
Really I think something is very messed up with the OS on your nas, you will have a really hard time getting it working again. I must reiterate again, SR is not at fault for this and its nothing I can fix in SR.

You will likely have to reinstall git and python, but I would most certainly check the drive/system partition because something is either failing or you had done something by mistake.

**Comment by marka65** [comment]
Well QNAP system could be, but don't know enough about QNAP/Linux to tell you if there is a big problem. Everything else seems to be working fine - sabnzbd, couchpotato, and Kodi. 

This morning there was an update to perl in the Apps Center. But that shouldn't of changed anything with git, python and Sickbeard. I'm wondering if that package may of changed any paths/links for git and python.

I did install a newer version of python (v2.7.9) and SickBeard is now up and running, but still have the older version (maybe corrupt version) of libcrypto.so.0.9.8, and so showing message of:

"You're using the /Apps/bin/git: /opt/lib/libcrypto.so.0.9.8: no version information available (required by /Apps/bin/git) master branch. Please use 'master' unless specifically asked"

Now just working out how to update libcrypto.so.0.9.8.

**Comment by marka65** [comment]
Found that QNAP system had libcrypto.so.1.0.0 in a couple of different packages. Update /opt/lib/ path and fixed symbolic link to point to the new copied file. Rebooted QNAP and its all working fine now. Found an update on github and update without any issues.

Thanks for your help...
