### ISSUE TITLE
[APP SUBMITTED]: [Error 2] The system cannot find the file specified: u'C:\\NAS_drive\\Videos\\Serier\\American Dad!'

### ISSUE THREAD

**Issue by Tiwas** [SickRage/SickRage#1734]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@c0b3435730360d17850e8cad8e1e96f864b88821
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [c0b3435] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 2291, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "C:\SickRage.io\SickRage\sickbeard\processTV.py", line 243, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "C:\SickRage.io\SickRage\sickbeard\processTV.py", line 560, in process_media
    result.result = processor.process()
  File "C:\SickRage.io\SickRage\sickbeard\postProcessor.py", line 1027, in process
    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
  File "C:\SickRage.io\SickRage\sickbeard\helpers.py", line 1578, in verify_freespace
    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev:  # pylint: disable=no-member
  File "C:\SickRage.io\SickRage\sickrage\helper\encoding.py", line 38, in ek
    result = function(*args, **kwargs)
WindowsError: [Error 2] The system cannot find the file specified: u'C:\\NAS_drive\\Videos\\Serier\\American Dad!'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
