### ISSUE TITLE
Exception generated in thread POSTPROCESSER: error 2 : No such file or directory

### ISSUE THREAD

**Issue by askinallquestions** [SickRage/SickRage#1756]
Sickrage worked fine up until a few days ago, where it is no longer creating folders in the location where it should move the shows to. I download the shows and place them in /mnt/samba/torrents/shows (which is where SR should find them sitting. Once they are there, SR should then move them to /mnt/samba/shows//. Normally, the folder would not exist, and SR would create it. I noticed about a week ago, that SR does not create those folders and move the file. If the folder exists, then the show gets moved like it should.

Branch: master
Commit: 61b8a1965bcee524b557a667fa11ffdece31ba72
Version: 2016.05.09-2
Database Version: 43.1

OS: Ubuntu 14.04
What you did: Updated to newest version
What happened: SR stopped creating folders at destination when postprocessing shows
What you expected: SR to create folders that did not exist in the destination location (more detail below)

Logs:

'''2016-05-11 15:53:12 DEBUG    POSTPROCESSER :: Starting new thread: POSTPROCESSER
2016-05-11 15:53:12 DEBUG    POSTPROCESSER :: Processing folder /mnt/samba/torrents/shows
2016-05-11 15:53:12 INFO     POSTPROCESSER :: PostProcessing Path: /mnt/samba/torrents/shows
2016-05-11 15:53:12 DEBUG    POSTPROCESSER :: PostProcessing Dirs: []
2016-05-11 15:53:12 DEBUG    POSTPROCESSER :: PostProcessing Files: ["Show S01E01.mkv", '.hidden']
2016-05-11 15:53:12 DEBUG    POSTPROCESSER :: PostProcessing VideoFiles: ["Show S01E01.mkv"]
2016-05-11 15:53:12 DEBUG    POSTPROCESSER :: PostProcessing RarContent: []
2016-05-11 15:53:12 DEBUG    POSTPROCESSER :: PostProcessing VideoInRar: []
2016-05-11 15:53:12 INFO     POSTPROCESSER :: Processing /mnt/samba/torrents/shows/Show S01E01.mkv (None)
2016-05-11 15:53:12 DEBUG    POSTPROCESSER :: Analyzing name Show S01E01.mkv
2016-05-11 15:53:12 DEBUG    POSTPROCESSER :: Parsed Show S01E01.mkv into Show - S01E01 [GROUP: [Zeus]] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2016-05-11 15:53:12 DEBUG    POSTPROCESSER :: Retrieving episode object for 1x01
2016-05-11 15:53:12 DEBUG    POSTPROCESSER :: Setter sets location to /mnt/samba/shows/Show_Name/Show S01E01.mkv
2016-05-11 15:53:12 DEBUG    POSTPROCESSER :: Snatch history had a quality in it, using that: 1080p HDTV
2016-05-11 15:53:12 DEBUG    POSTPROCESSER :: Quality of the episode we're processing: 1080p HDTV
2016-05-11 15:53:12 DEBUG    POSTPROCESSER :: SR snatched this episode and it is not processed before
2016-05-11 15:53:12 DEBUG    POSTPROCESSER :: Is ep a priority download: True
2016-05-11 15:53:12 DEBUG    POSTPROCESSER :: File /mnt/samba/shows/Show_Name/Show S01E01.mkv doesn't exist so there's no worries about replacing it
2016-05-11 15:53:12 INFO     POSTPROCESSER :: This download is marked a priority download so I'm going to replace an existing file if I find one
2016-05-11 15:53:12 DEBUG    POSTPROCESSER :: Trying to determine free space on destination drive
2016-05-11 15:53:12 ERROR    POSTPROCESSER :: [61b8a19] Exception generated in thread POSTPROCESSER: error 2 : No such file or directory
Traceback (most recent call last):
  File "/home/user/.sickrage/sickbeard/scheduler.py", line 106, in run
    self.action.run(self.force)
  File "/home/user/.sickrage/sickbeard/auto_postprocessor.py", line 56, in run
    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)
  File "/home/user/.sickrage/sickbeard/processTV.py", line 243, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/home/user/.sickrage/sickbeard/processTV.py", line 560, in process_media
    result.result = processor.process()
  File "/home/user/.sickrage/sickbeard/postProcessor.py", line 1027, in process
    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
  File "/home/user/.sickrage/sickbeard/helpers.py", line 1578, in verify_freespace
    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev:  # pylint: disable=no-member
  File "/home/user/.sickrage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 2] No such file or directory: "/mnt/samba/shows/Show_Name"
2016-05-11 15:53:12 DEBUG    POSTPROCESSER :: 'Traceback (most recent call last):\n  File "/home/user/.sickrage/sickbeard/scheduler.py", line 106, in run\n    self.action.run(self.force)\n  File "/home/user/.sickrage/sickbeard/auto_postprocessor.py", line 56, in run\n    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)\n  File "/home/user/.sickrage/sickbeard/processTV.py", line 243, in processDir\n    process_media(path, [video], nzbName, process_method, force, is_priority, result)\n  File "/home/user/.sickrage/sickbeard/processTV.py", line 560, in process_media\n    result.result = processor.process()\n  File "/home/user/.sickrage/sickbeard/postProcessor.py", line 1027, in process\n    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access\n  File "/home/user/.sickrage/sickbeard/helpers.py", line 1578, in verify_freespace\n    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev:  # pylint: disable=no-member\n  File "/home/user/.sickrage/sickrage/helper/encoding.py", line 40, in ek\n    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)\nOSError: [Errno 2] No such file or directory: "/mnt/samba/shows/Show_Name"\n''''

Thank you very much for your assistance!

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [ ] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
#1753
