### ISSUE TITLE
Postprocessing fails on permission issue, files are deleted

### ISSUE THREAD

**Issue by InsomniacSoftware** [SickRage/SickRage#1762]
Branch: master
Commit: f970b5fd5e222469059e71c9b0d6a18348d2770e
Version: 2016.05.12-1
OS: OSX 10.11.4
What you did: processed a tv episode
What happened: the file failed to move due to read-only permissions. the file was deleted.
What you expected: If SR can't move a file, it should throw an error but leave the file alone.  The log does not mention deleting the file but it just vanishes from the drive!  Unfortunately I didn't notice for days and lost a lot of downloads :(

Logs:
Here is the SR log when the postprocessing fails.

```
2016-05-12 15:23:17 DEBUG    Thread-14 :: Processing folder /Plex/3a-Incoming_TV_Show
2016-05-12 15:23:17 INFO     Thread-14 :: PostProcessing Path: /Plex/3a-Incoming_TV_Show
2016-05-12 15:23:17 DEBUG    Thread-14 :: PostProcessing Dirs: []
2016-05-12 15:23:17 DEBUG    Thread-14 :: PostProcessing Files: ['.DS_Store', 'DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT.mkv']
2016-05-12 15:23:17 DEBUG    Thread-14 :: PostProcessing VideoFiles: ['DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT.mkv']
2016-05-12 15:23:17 DEBUG    Thread-14 :: PostProcessing RarContent: []
2016-05-12 15:23:17 DEBUG    Thread-14 :: PostProcessing VideoInRar: []
2016-05-12 15:23:17 INFO     Thread-14 :: Processing /Plex/3a-Incoming_TV_Show/DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT.mkv (None)
2016-05-12 15:23:17 DEBUG    Thread-14 :: Analyzing name DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT.mkv
2016-05-12 15:23:17 DEBUG    Thread-14 :: Using cached parse result for: DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT
2016-05-12 15:23:17 DEBUG    Thread-14 :: Retrieving episode object for 1x11
2016-05-12 15:23:17 DEBUG    Thread-14 :: Snatch history had a quality in it, using that: 1080p WEB-DL
2016-05-12 15:23:17 DEBUG    Thread-14 :: Quality of the episode we're processing: 1080p WEB-DL
2016-05-12 15:23:17 DEBUG    Thread-14 :: Is ep a priority download: False
2016-05-12 15:23:17 DEBUG    Thread-14 :: There is no existing file so there's no worries about replacing it
2016-05-12 15:23:17 DEBUG    Thread-14 :: Trying to determine free space on destination drive
2016-05-12 15:23:17 INFO     Thread-14 :: Process method is 'move' and src and destination are on the same device, skipping freepace check
2016-05-12 15:23:17 DEBUG    Thread-14 :: Found release name DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT
2016-05-12 15:23:17 DEBUG    Thread-14 :: Folder name (3a-Incoming_TV_Show) appears to be a valid release name. Using it.
2016-05-12 15:23:17 DEBUG    Thread-14 :: Using cached parse result for: DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT
2016-05-12 15:23:17 DEBUG    Thread-14 :: Found codec for 'DC's Legends of Tomorrow: The Magnificent Eight'.
2016-05-12 15:23:17 DEBUG    Thread-14 :: formatting pattern: %SN S%0SE%0E %EN [%SQN] -> DC's Legends of Tomorrow S01E11 The Magnificent Eight [1080p WEB-DL h264]
2016-05-12 15:23:17 DEBUG    Thread-14 :: Destination folder for this episode: /Plex/Media/TV/DC's Legends of Tomorrow
2016-05-12 15:23:17 DEBUG    Thread-14 :: Checking if the path /Plex/Media/TV/DC's Legends of Tomorrow already exists
2016-05-12 15:23:18 DEBUG    Thread-14 :: Moving file from /Plex/3a-Incoming_TV_Show/DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT.mkv to /Plex/Media/TV/DC's Legends of Tomorrow/DC's Legends of Tomorrow S01E11 The Magnificent Eight [1080p WEB-DL h264].mkv
2016-05-12 15:23:18 ERROR    Thread-14 :: [f970b5f] [Errno 13] Permission denied: "/Plex/Media/TV/DC's Legends of Tomorrow/DC's Legends of Tomorrow S01E11 The Magnificent Eight [1080p WEB-DL h264].mkv"
Traceback (most recent call last):
  File "/usr/local/opt/SickRage/sickbeard/helpers.py", line 363, in copyFile
    ek(shutil.copyfile, srcFile, destFile)
  File "/usr/local/opt/SickRage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/usr/local/opt/SickRage/lib/shutil_custom/__init__.py", line 42, in copyfile_custom
    fout = os.open(dst, WRITE_FLAGS)
OSError: [Errno 13] Permission denied: "/Plex/Media/TV/DC's Legends of Tomorrow/DC's Legends of Tomorrow S01E11 The Magnificent Eight [1080p WEB-DL h264].mkv"
2016-05-12 15:23:19 ERROR    Thread-14 :: [f970b5f] Unable to move file /Plex/3a-Incoming_TV_Show/DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT.mkv to /Plex/Media/TV/DC's Legends of Tomorrow/DC's Legends of Tomorrow S01E11 The Magnificent Eight [1080p WEB-DL h264].mkv: error 2 : No such file or directory
Traceback (most recent call last):
  File "/usr/local/opt/SickRage/sickbeard/postProcessor.py", line 376, in _int_move
    helpers.chmodAsParent(new_file_path)
  File "/usr/local/opt/SickRage/sickbeard/helpers.py", line 621, in chmodAsParent
    childPathStat = ek(os.stat, childPath.encode(sickbeard.SYS_ENCODING))
  File "/usr/local/opt/SickRage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 2] No such file or directory: "/Plex/Media/TV/DC's Legends of Tomorrow/DC's Legends of Tomorrow S01E11 The Magnificent Eight [1080p WEB-DL h264].mkv"
2016-05-12 15:23:19 WARNING  Thread-14 :: Processing failed for /Plex/3a-Incoming_TV_Show/DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT.mkv: Unable to move the files to their new home
2016-05-12 15:23:19 WARNING  Thread-14 :: Problem(s) during processing, failed the following files/folders:
2016-05-12 15:23:19 WARNING  Thread-14 :: [/Plex/3a-Incoming_TV_Show/DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT.mkv : Processing failed: Unable to move the files to their new home]
```

Here is the directory listing of the destination directory.
```
2016-05-12 15:17MDT(21:17) /Plex/Media/TV/DC's Legends of Tomorrow
@Majikthise$ ls -al
drwsrwxr-x  1 root  wheel         466 May  7 16:14 ./
drwsrwxr-x  1 root  wheel        2778 May  6 19:26 ../
```

I adjusted the permissions to make the directory writable, copied the episode file into the "Incoming" dir, then kicked off the postprocessing again.  This time it was successful.

```
2016-05-12 15:27:06 DEBUG    Thread-15 :: Processing folder /Plex/3a-Incoming_TV_Show
2016-05-12 15:27:06 INFO     Thread-15 :: PostProcessing Path: /Plex/3a-Incoming_TV_Show
2016-05-12 15:27:06 DEBUG    Thread-15 :: PostProcessing Dirs: []
2016-05-12 15:27:06 DEBUG    Thread-15 :: PostProcessing Files: ['.DS_Store', 'DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT.mkv']
2016-05-12 15:27:06 DEBUG    Thread-15 :: PostProcessing VideoFiles: ['DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT.mkv']
2016-05-12 15:27:06 DEBUG    Thread-15 :: PostProcessing RarContent: []
2016-05-12 15:27:06 DEBUG    Thread-15 :: PostProcessing VideoInRar: []
2016-05-12 15:27:06 INFO     Thread-15 :: Processing /Plex/3a-Incoming_TV_Show/DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT.mkv (None)
2016-05-12 15:27:06 DEBUG    Thread-15 :: Analyzing name DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT.mkv
2016-05-12 15:27:06 DEBUG    Thread-15 :: Using cached parse result for: DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT
2016-05-12 15:27:06 DEBUG    Thread-15 :: Retrieving episode object for 1x11
2016-05-12 15:27:06 DEBUG    Thread-15 :: Snatch history had a quality in it, using that: 1080p WEB-DL
2016-05-12 15:27:06 DEBUG    Thread-15 :: Quality of the episode we're processing: 1080p WEB-DL
2016-05-12 15:27:06 DEBUG    Thread-15 :: Is ep a priority download: False
2016-05-12 15:27:06 DEBUG    Thread-15 :: There is no existing file so there's no worries about replacing it
2016-05-12 15:27:06 DEBUG    Thread-15 :: Trying to determine free space on destination drive
2016-05-12 15:27:07 INFO     Thread-15 :: Process method is 'move' and src and destination are on the same device, skipping freepace check
2016-05-12 15:27:07 DEBUG    Thread-15 :: Found release name DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT
2016-05-12 15:27:07 DEBUG    Thread-15 :: Folder name (3a-Incoming_TV_Show) appears to be a valid release name. Using it.
2016-05-12 15:27:07 DEBUG    Thread-15 :: Using cached parse result for: DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT
2016-05-12 15:27:07 DEBUG    Thread-15 :: Found codec for 'DC's Legends of Tomorrow: The Magnificent Eight'.
2016-05-12 15:27:07 DEBUG    Thread-15 :: formatting pattern: %SN S%0SE%0E %EN [%SQN] -> DC's Legends of Tomorrow S01E11 The Magnificent Eight [1080p WEB-DL h264]
2016-05-12 15:27:07 DEBUG    Thread-15 :: Destination folder for this episode: /Plex/Media/TV/DC's Legends of Tomorrow
2016-05-12 15:27:07 DEBUG    Thread-15 :: Checking if the path /Plex/Media/TV/DC's Legends of Tomorrow already exists
2016-05-12 15:27:08 DEBUG    Thread-15 :: Moving file from /Plex/3a-Incoming_TV_Show/DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT.mkv to /Plex/Media/TV/DC's Legends of Tomorrow/DC's Legends of Tomorrow S01E11 The Magnificent Eight [1080p WEB-DL h264].mkv
2016-05-12 15:27:08 DEBUG    Thread-15 :: Setter sets location to /Plex/Media/TV/DC's Legends of Tomorrow/DC's Legends of Tomorrow S01E11 The Magnificent Eight [1080p WEB-DL h264].mkv
2016-05-12 15:27:08 DEBUG    Thread-15 :: Transaction with 2 queries executed
2016-05-12 15:27:08 DEBUG    Thread-15 :: 295760: About to modify date of '/Plex/Media/TV/DC's Legends of Tomorrow/DC's Legends of Tomorrow S01E11 The Magnificent Eight [1080p WEB-DL h264].mkv' to show air date Apr 14,2016 (18:00)
2016-05-12 15:27:08 INFO     Thread-15 :: 295760: Changed modify date of 'DC's Legends of Tomorrow S01E11 The Magnificent Eight [1080p WEB-DL h264].mkv' to show air date Apr 14,2016 (18:00)
2016-05-12 15:27:08 DEBUG    Thread-15 :: Parsed /Plex/Media/TV/DC's Legends of Tomorrow/DC's Legends of Tomorrow S01E11 The Magnificent Eight [1080p WEB-DL h264] into DC's Legends of Tomorrow - S01E11 [ABD: False] [ANIME: False] [whichReg: ['standard']]
2016-05-12 15:27:08 DEBUG    Thread-15 :: Using cached parse result for: DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT
2016-05-12 15:27:08 DEBUG    Thread-15 :: Found codec for 'DC's Legends of Tomorrow: The Magnificent Eight'.
2016-05-12 15:27:08 DEBUG    Thread-15 :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> DC's Legends of Tomorrow - 1x11 - The Magnificent Eight - 1080p WEB-DL
2016-05-12 15:27:08 DEBUG    Thread-15 :: Notification for NMJ scan update not enabled, skipping this notification
2016-05-12 15:27:08 INFO     Thread-15 :: Processing succeeded for /Plex/3a-Incoming_TV_Show/DCs.Legends.of.Tomorrow.S01E11.The.Magnificent.Eight.1080p.WEB-DL.DD5.1.H.264-LoT.mkv
2016-05-12 15:27:08 INFO     Thread-15 :: Successfully processed

2016-05-12 15:26MDT(21:26) /Plex/Media/TV/DC's Legends of Tomorrow
@Majikthise$ ls -al
drwsrwxrwx  1 root  wheel         500 May 12 15:27 ./
drwsrwxr-x  1 root  wheel        2778 May  6 19:26 ../
-rw-rw-rw-@ 1 root  wheel  1705439165 Apr 14 18:00 DC's Legends of Tomorrow S01E11 The Magnificent Eight [1080p WEB-DL h264].mkv
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by InsomniacSoftware** [comment]
Also the tv episode is shown in the show's list as properly Downloaded.  If SR fails to post process the episode file and put it in the destination directory, it should consider it as Downloaded (successful).  Perhaps the status should be failed or error?

**Comment by paintballkev812** [comment]
Wanted to report that I experience this issue as well. I noticed missing downloads and could not figure out how they disappeared. These files were also read-only. This explains the mystery.

**Comment by InsomniacSoftware** [comment]
@miigotu May I ask why this won't be fixed?  It is causing data loss!

I just updated to the latest commit (ffcea549ea699fb27937324c8f33bd91da264ce4) and it happened again.  There were 2 files ready for post processing.  The first was successful but the second failed.  Both going to similar destinations, just slightly different subdirectories.

Here are the permissions on the destination directories.  Fully writable by me.
```
$ cd /Plex/Media/TV
$ ls -ald . Arrow* *Flash*
drwsrwxr-x  1 jeff  staff  2778 May  6 19:26 ./
drwxrwxr-x  1 jeff  staff   466 May 16 17:02 Arrow/
drwxrwxr-x  1 jeff  staff  1078 May 18 14:09 The Flash (2014)/
```

The python process is running as me
```
USER    PID  %CPU %MEM  STARTED      TIME COMMAND
jeff  60519   0.1  0.9   3:29PM   1:24.41 /usr/bin/python /usr/local/opt/SickRage/SickBeard.py --quiet --nolaunch --datadir=/usr/local/etc/SickRage
```

Here is the log when it failed.
```
2016-05-23 15:54:15 DEBUG    POSTPROCESSER :: Starting new thread: POSTPROCESSER
2016-05-23 15:54:15 DEBUG    POSTPROCESSER :: Processing folder /Plex/3a-Incoming_TV_Show
2016-05-23 15:54:15 INFO     POSTPROCESSER :: PostProcessing Path: /Plex/3a-Incoming_TV_Show
2016-05-23 15:54:15 DEBUG    POSTPROCESSER :: PostProcessing Dirs: []
2016-05-23 15:54:15 DEBUG    POSTPROCESSER :: PostProcessing Files: ['.DS_Store', 'The.Flash.2014.S02E22.1080p.HDTV.X264-DIMENSION.mkv', 'Arrow.S04E22.1080p.WEB-DL.DD5.1.H264-RARBG.mkv']
2016-05-23 15:54:15 DEBUG    POSTPROCESSER :: PostProcessing VideoFiles: ['The.Flash.2014.S02E22.1080p.HDTV.X264-DIMENSION.mkv', 'Arrow.S04E22.1080p.WEB-DL.DD5.1.H264-RARBG.mkv']
2016-05-23 15:54:15 DEBUG    POSTPROCESSER :: PostProcessing RarContent: []
2016-05-23 15:54:15 DEBUG    POSTPROCESSER :: PostProcessing VideoInRar: []
2016-05-23 15:54:15 INFO     POSTPROCESSER :: Processing /Plex/3a-Incoming_TV_Show/The.Flash.2014.S02E22.1080p.HDTV.X264-DIMENSION.mkv (None)
2016-05-23 15:54:15 DEBUG    POSTPROCESSER :: Analyzing name The.Flash.2014.S02E22.1080p.HDTV.X264-DIMENSION.mkv
2016-05-23 15:54:16 DEBUG    POSTPROCESSER :: Parsed The.Flash.2014.S02E22.1080p.HDTV.X264-DIMENSION into The Flash 2014 - S02E22 [GROUP: DIMENSION] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2016-05-23 15:54:16 DEBUG    POSTPROCESSER :: Retrieving episode object for 2x22
2016-05-23 15:54:16 DEBUG    POSTPROCESSER :: Snatch history had a quality in it, using that: 1080p HDTV
2016-05-23 15:54:16 DEBUG    POSTPROCESSER :: Quality of the episode we're processing: 1080p HDTV
2016-05-23 15:54:16 DEBUG    POSTPROCESSER :: SR snatched this episode and it is not processed before
2016-05-23 15:54:16 DEBUG    POSTPROCESSER :: Is ep a priority download: True
2016-05-23 15:54:16 DEBUG    POSTPROCESSER :: There is no existing file so there's no worries about replacing it
2016-05-23 15:54:16 INFO     POSTPROCESSER :: This download is marked a priority download so I'm going to replace an existing file if I find one
2016-05-23 15:54:16 DEBUG    POSTPROCESSER :: Trying to determine free space on destination drive
2016-05-23 15:54:16 INFO     POSTPROCESSER :: Process method is 'move' and src and destination are on the same device, skipping freepace check
2016-05-23 15:54:16 DEBUG    POSTPROCESSER :: Found release name The.Flash.2014.S02E22.1080p.HDTV.X264-DIMENSION
2016-05-23 15:54:16 DEBUG    POSTPROCESSER :: Folder name (3a-Incoming_TV_Show) appears to be a valid release name. Using it.
2016-05-23 15:54:16 DEBUG    POSTPROCESSER :: Using cached parse result for: The.Flash.2014.S02E22.1080p.HDTV.X264-DIMENSION
2016-05-23 15:54:16 DEBUG    POSTPROCESSER :: Found codec for 'The Flash: Invincible'.
2016-05-23 15:54:16 DEBUG    POSTPROCESSER :: formatting pattern: %SN S%0SE%0E %EN [%SQN] -> The Flash S02E22 Invincible [1080p HDTV x264]
2016-05-23 15:54:16 DEBUG    POSTPROCESSER :: Destination folder for this episode: /Plex/Media/TV/The Flash (2014)
2016-05-23 15:54:16 DEBUG    POSTPROCESSER :: Checking if the path /Plex/Media/TV/The Flash (2014) already exists
2016-05-23 15:54:17 DEBUG    POSTPROCESSER :: Moving file from /Plex/3a-Incoming_TV_Show/The.Flash.2014.S02E22.1080p.HDTV.X264-DIMENSION.mkv to /Plex/Media/TV/The Flash (2014)/The Flash S02E22 Invincible [1080p HDTV x264].mkv
2016-05-23 15:55:42 DEBUG    POSTPROCESSER :: Failed to set permission for /Plex/Media/TV/The Flash (2014)/The Flash S02E22 Invincible [1080p HDTV x264].mkv to 664, parent directory has 775
2016-05-23 15:55:42 DEBUG    POSTPROCESSER :: Setter sets location to /Plex/Media/TV/The Flash (2014)/The Flash S02E22 Invincible [1080p HDTV x264].mkv
2016-05-23 15:55:42 DEBUG    POSTPROCESSER :: Transaction with 2 queries executed
2016-05-23 15:55:42 DEBUG    POSTPROCESSER :: 279121: About to modify date of '/Plex/Media/TV/The Flash (2014)/The Flash S02E22 Invincible [1080p HDTV x264].mkv' to show air date May 17,2016 (18:00)
2016-05-23 15:55:42 INFO     POSTPROCESSER :: 279121: Changed modify date of 'The Flash S02E22 Invincible [1080p HDTV x264].mkv' to show air date May 17,2016 (18:00)
2016-05-23 15:55:42 DEBUG    POSTPROCESSER :: Parsed /Plex/Media/TV/The Flash (2014)/The Flash S02E22 Invincible [1080p HDTV x264] into The Flash - S02E22 [ABD: False] [ANIME: False] [whichReg: ['standard']]
2016-05-23 15:55:42 DEBUG    POSTPROCESSER :: Using cached parse result for: The.Flash.2014.S02E22.1080p.HDTV.X264-DIMENSION
2016-05-23 15:55:42 DEBUG    POSTPROCESSER :: Found codec for 'The Flash: Invincible'.
2016-05-23 15:55:42 DEBUG    POSTPROCESSER :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> The Flash - 2x22 - Invincible - 1080p HDTV
2016-05-23 15:55:42 DEBUG    POSTPROCESSER :: Notification for NMJ scan update not enabled, skipping this notification
2016-05-23 15:55:42 INFO     POSTPROCESSER :: Processing succeeded for /Plex/3a-Incoming_TV_Show/The.Flash.2014.S02E22.1080p.HDTV.X264-DIMENSION.mkv
2016-05-23 15:55:42 INFO     POSTPROCESSER :: Processing /Plex/3a-Incoming_TV_Show/Arrow.S04E22.1080p.WEB-DL.DD5.1.H264-RARBG.mkv (None)
2016-05-23 15:55:42 DEBUG    POSTPROCESSER :: Analyzing name Arrow.S04E22.1080p.WEB-DL.DD5.1.H264-RARBG.mkv
2016-05-23 15:55:43 DEBUG    POSTPROCESSER :: Parsed Arrow.S04E22.1080p.WEB-DL.DD5.1.H264-RARBG into Arrow - S04E22 [GROUP: RARBG] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2016-05-23 15:55:43 DEBUG    POSTPROCESSER :: Retrieving episode object for 4x22
2016-05-23 15:55:43 DEBUG    POSTPROCESSER :: Snatch history had a quality in it, using that: 1080p WEB-DL
2016-05-23 15:55:43 DEBUG    POSTPROCESSER :: Quality of the episode we're processing: 1080p WEB-DL
2016-05-23 15:55:43 DEBUG    POSTPROCESSER :: SR snatched this episode and it is not processed before
2016-05-23 15:55:43 DEBUG    POSTPROCESSER :: Is ep a priority download: True
2016-05-23 15:55:43 DEBUG    POSTPROCESSER :: There is no existing file so there's no worries about replacing it
2016-05-23 15:55:43 INFO     POSTPROCESSER :: This download is marked a priority download so I'm going to replace an existing file if I find one
2016-05-23 15:55:43 DEBUG    POSTPROCESSER :: Trying to determine free space on destination drive
2016-05-23 15:55:43 INFO     POSTPROCESSER :: Process method is 'move' and src and destination are on the same device, skipping freepace check
2016-05-23 15:55:43 DEBUG    POSTPROCESSER :: Found release name Arrow.S04E22.1080p.WEB-DL.DD5.1.H264-RARBG
2016-05-23 15:55:43 DEBUG    POSTPROCESSER :: Folder name (3a-Incoming_TV_Show) appears to be a valid release name. Using it.
2016-05-23 15:55:43 DEBUG    POSTPROCESSER :: Using cached parse result for: Arrow.S04E22.1080p.WEB-DL.DD5.1.H264-RARBG
2016-05-23 15:55:43 DEBUG    POSTPROCESSER :: Found codec for 'Arrow: Lost in the Flood'.
2016-05-23 15:55:43 DEBUG    POSTPROCESSER :: formatting pattern: %SN S%0SE%0E %EN [%SQN] -> Arrow S04E22 Lost in the Flood [1080p WEB-DL h264]
2016-05-23 15:55:43 DEBUG    POSTPROCESSER :: Destination folder for this episode: /Plex/Media/TV/Arrow
2016-05-23 15:55:43 DEBUG    POSTPROCESSER :: Checking if the path /Plex/Media/TV/Arrow already exists
2016-05-23 15:55:44 DEBUG    POSTPROCESSER :: Moving file from /Plex/3a-Incoming_TV_Show/Arrow.S04E22.1080p.WEB-DL.DD5.1.H264-RARBG.mkv to /Plex/Media/TV/Arrow/Arrow S04E22 Lost in the Flood [1080p WEB-DL h264].mkv
2016-05-23 15:55:44 ERROR    POSTPROCESSER :: [ffcea54] [Errno 13] Permission denied: '/Plex/Media/TV/Arrow/Arrow S04E22 Lost in the Flood [1080p WEB-DL h264].mkv'
Traceback (most recent call last):
  File "/usr/local/opt/SickRage/sickbeard/helpers.py", line 363, in copyFile
    ek(shutil.copyfile, srcFile, destFile)
  File "/usr/local/opt/SickRage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/usr/local/opt/SickRage/lib/shutil_custom/__init__.py", line 42, in copyfile_custom
    fout = os.open(dst, WRITE_FLAGS)
OSError: [Errno 13] Permission denied: '/Plex/Media/TV/Arrow/Arrow S04E22 Lost in the Flood [1080p WEB-DL h264].mkv'
2016-05-23 15:55:44 ERROR    POSTPROCESSER :: [ffcea54] Unable to move file /Plex/3a-Incoming_TV_Show/Arrow.S04E22.1080p.WEB-DL.DD5.1.H264-RARBG.mkv to /Plex/Media/TV/Arrow/Arrow S04E22 Lost in the Flood [1080p WEB-DL h264].mkv: error 2 : No such file or directory
Traceback (most recent call last):
  File "/usr/local/opt/SickRage/sickbeard/postProcessor.py", line 376, in _int_move
    helpers.chmodAsParent(new_file_path)
  File "/usr/local/opt/SickRage/sickbeard/helpers.py", line 621, in chmodAsParent
    childPathStat = ek(os.stat, childPath.encode(sickbeard.SYS_ENCODING))
  File "/usr/local/opt/SickRage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 2] No such file or directory: '/Plex/Media/TV/Arrow/Arrow S04E22 Lost in the Flood [1080p WEB-DL h264].mkv'
2016-05-23 15:55:44 WARNING  POSTPROCESSER :: Processing failed for /Plex/3a-Incoming_TV_Show/Arrow.S04E22.1080p.WEB-DL.DD5.1.H264-RARBG.mkv: Unable to move the files to their new home
2016-05-23 15:55:44 WARNING  POSTPROCESSER :: Problem(s) during processing, failed the following files/folders:
2016-05-23 15:55:44 WARNING  POSTPROCESSER :: [/Plex/3a-Incoming_TV_Show/Arrow.S04E22.1080p.WEB-DL.DD5.1.H264-RARBG.mkv : Processing failed: Unable to move the files to their new home]
```

**Comment by miigotu** [comment]
Look at the permissions of the source files... SR doesn't manage permissions of existing files.

**Comment by InsomniacSoftware** [comment]
All source files (in the /Plex/3a-Incoming_TV_Show/ directory) are always set to read/write by all.
`-rw-rw-rw- 1 jeff  staff`

I will keep digging to see if there is a problem with copying files on my server but the bug with SR remains;  If it fails during post processing, it should not mark the episode as successfully downloaded.
