### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/mnt/media/Anime/Gangsta'

### ISSUE THREAD

**Issue by cbrherms** [SickRage/SickRage#1769]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@f970b5fd5e222469059e71c9b0d6a18348d2770e
No Log available with ERRORS:
### ERROR
```
Thread-18 :: [f970b5f] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2291, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 290, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 560, in process_media
    result.result = processor.process()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 1027, in process
    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/helpers.py", line 1578, in verify_freespace
    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev:  # pylint: disable=no-member
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 2] No such file or directory: '/mnt/media/Anime/Gangsta'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by cbrherms** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@f970b5fd5e222469059e71c9b0d6a18348d2770e
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [f970b5f] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2291, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 290, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 560, in process_media
    result.result = processor.process()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 1027, in process
    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/helpers.py", line 1578, in verify_freespace
    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev:  # pylint: disable=no-member
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 2] No such file or directory: '/mnt/media/Anime/Gangsta'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by cbrherms** [comment]
If "Force already Post Processed Dir/Files:" is checked and destination folder doesn't exist then error thrown up and files not processed.
User error regarding checking that option but would be preferable to have the option ignored in post processing if folder doesn't exist

**Comment by cbrherms** [comment]
SickRage not creating folder, though has permission for mounted share

**Comment by cbrherms** [comment]
#1753 

Duplicate of that issue it seems

**Comment by AbhieSpeaks** [comment]
### INFO
Python Version: **2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-post2008Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@b790df702cf1ef84ee64b591f40ce6fae86976dc
No Log available with ERRORS:
### ERROR
```
Thread-28 :: [b790df7] Failed doing webui callback: Traceback (most recent call last):
  File "G:\Github\SickRage\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "G:\Github\SickRage\sickbeard\webserve.py", line 1256, in displayShow
    t = PageTemplate(rh=self, filename="displayShow.mako")
  File "G:\Github\SickRage\sickbeard\webserve.py", line 112, in __init__
    self.template = lookup.get_template(filename)
  File "G:\Github\SickRage\lib\mako\lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "G:\Github\SickRage\lib\mako\lookup.py", line 321, in _load
    **self.template_args)
  File "G:\Github\SickRage\lib\mako\template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "G:\Github\SickRage\lib\mako\template.py", line 378, in _compile_from_file
    self.module_writer)
  File "G:\Github\SickRage\lib\mako\template.py", line 703, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "C:\Python27\lib\tempfile.py", line 300, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "C:\Python27\lib\tempfile.py", line 235, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
