### ISSUE TITLE
[APP SUBMITTED]: invalid syntax (schedule.mako.py, line 275)

### ISSUE THREAD

**Issue by blkpanther5** [SickRage/SickRage#1771]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@f970b5fd5e222469059e71c9b0d6a18348d2770e
No Log available with ERRORS:
### ERROR
```
Thread-18 :: [f970b5f] Failed doing webui callback: Traceback (most recent call last):
  File "C:\Program Files (x86)\SickRage\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\Program Files (x86)\SickRage\sickbeard\webserve.py", line 513, in schedule
    t = PageTemplate(rh=self, filename='schedule.mako')
  File "C:\Program Files (x86)\SickRage\sickbeard\webserve.py", line 112, in __init__
    self.template = lookup.get_template(filename)
  File "C:\Program Files (x86)\SickRage\lib\mako\lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "C:\Program Files (x86)\SickRage\lib\mako\lookup.py", line 321, in _load
    **self.template_args)
  File "C:\Program Files (x86)\SickRage\lib\mako\template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\Program Files (x86)\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\Program Files (x86)\SickRage\lib\mako\compat.py", line 89, in load_module
    return imp.load_source(module_id, path, fp)
  File "s:\management\sickrage\cache\mako\schedule.mako.py", line 275
    __M_writer(uu'</a>\r\n')
                          ^
SyntaxError: invalid syntax

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
