### ISSUE TITLE
[APP SUBMITTED]: unexpected indent (schedule.mako.py, line 155)

### ISSUE THREAD

**Issue by blkpanther5** [SickRage/SickRage#1772]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@f970b5fd5e222469059e71c9b0d6a18348d2770e
No Log available with ERRORS:
### ERROR
```
Thread-20 :: [f970b5f] Failed doing webui callback: Traceback (most recent call last):
  File "C:\Program Files (x86)\SickRage\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\Program Files (x86)\SickRage\sickbeard\webserve.py", line 513, in schedule
    t = PageTemplate(rh=self, filename='schedule.mako')
  File "C:\Program Files (x86)\SickRage\sickbeard\webserve.py", line 112, in __init__
    self.template = lookup.get_template(filename)
  File "C:\Program Files (x86)\SickRage\lib\mako\lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "C:\Program Files (x86)\SickRage\lib\mako\lookup.py", line 321, in _load
    **self.template_args)
  File "C:\Program Files (x86)\SickRage\lib\mako\template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\Program Files (x86)\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\Program Files (x86)\SickRage\lib\mako\compat.py", line 89, in load_module
    return imp.load_source(module_id, path, fp)
  File "s:\management\sickrage\cache\mako\schedule.mako.py", line 155
    __M_writer(unicode(_('Show')))
    ^
IndentationError: unexpected indent

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
You are probbebly getting errors because you have installed Sickrage in the C:\Program Files (x86) folder. Windows is picky running programs there because of permissions/rights. 

Try to install sickrage with the installer. :
https://github.com/SickRage/SickRageInstaller/releases/latest

**Comment by netvyper** [comment]
ERROR logs
 2017-05-16 14:01:43 Thread-29 :: [c568139] Failed doing webui callback: Traceback (most recent call last):
File "C:\SickRage\SickRage\sickbeard\webserve.py", line 287, in async_call
result = function(**kwargs)
File "C:\SickRage\SickRage\sickbeard\webserve.py", line 5332, in viewlog
t = PageTemplate(rh=self, filename="viewlogs.mako")
File "C:\SickRage\SickRage\sickbeard\webserve.py", line 125, in __init__
self.template = lookup.get_template(filename)
File "C:\SickRage\SickRage\lib\mako\lookup.py", line 258, in get_template
return self._load(srcfile, uri)
File "C:\SickRage\SickRage\lib\mako\lookup.py", line 323, in _load
**self.template_args)
File "C:\SickRage\SickRage\lib\mako\template.py", line 338, in __init__
module = self._compile_from_file(path, filename)
File "C:\SickRage\SickRage\lib\mako\template.py", line 396, in _compile_from_file
module = compat.load_module(self.module_id, path)
File "C:\SickRage\SickRage\lib\mako\compat.py", line 90, in load_module
return imp.load_source(module_id, path, fp)
File "C:\SickRage\Data\cache\mako\viewlogs.mako.py", line 99

^
IndentationError: unexpected unindent

2017-05-16 14:01:43 Thread-27 :: [c568139] Failed doing webui callback: Traceback (most recent call last):
File "C:\SickRage\SickRage\sickbeard\webserve.py", line 287, in async_call
result = function(**kwargs)
File "C:\SickRage\SickRage\sickbeard\webserve.py", line 5332, in viewlog
t = PageTemplate(rh=self, filename="viewlogs.mako")
File "C:\SickRage\SickRage\sickbeard\webserve.py", line 125, in __init__
self.template = lookup.get_template(filename)
File "C:\SickRage\SickRage\lib\mako\lookup.py", line 258, in get_template
return self._load(srcfile, uri)
File "C:\SickRage\SickRage\lib\mako\lookup.py", line 323, in _load
**self.template_args)
File "C:\SickRage\SickRage\lib\mako\template.py", line 338, in __init__
module = self._compile_from_file(path, filename)
File "C:\SickRage\SickRage\lib\mako\template.py", line 396, in _compile_from_file
module = compat.load_module(self.module_id, path)
File "C:\SickRage\SickRage\lib\mako\compat.py", line 90, in load_module
return imp.load_source(module_id, path, fp)
ImportError: Loaded module viewlogs_mako not found in sys.modules


I've just run into the same issue - definitely not program files (x86) related

**Comment by sharkykh** [comment]
@netvyper  Try deleting the mako cache folder:
Shutdown SickRage, go to `C:\SickRage\Data\cache\`, delete the `mako` folder.
Restart SR.

**Comment by netvyper** [comment]
@sharkykh Have done so, now getting a 404... Looks like the mako folder has been recreated ok; full log attached.

[sickrage.log.txt](https://github.com/SickRage/SickRage/files/1004492/sickrage.log.txt)

**Comment by sharkykh** [comment]
@netvyper Did you stop SickRage then start it again **(both) using the links in the Start menu**?
I'm asking because I'm not seeing that in the logs.

**Comment by netvyper** [comment]
@sharkykh I stopped & started the windows service the first time. Did it with the shortcuts after your first edit, and once again after your most recent post.

Still seeing the same behaviour. (mako folder is deleted when the service is stopped, not sure if this is expected?)

[sickrage.log.txt](https://github.com/SickRage/SickRage/files/1004599/sickrage.log.txt)

**Comment by sharkykh** [comment]
@netvyper Since it seems to be consistent with the `viewlogs` file, I'd suggest you stop SickRage again, and delete/move all of the logs from `C:\SickRage\Data\Logs`.
Keep the folder, just empty it. Then run SickRage again.

I think I've encountered that before, and I think that's how I fixed it.

**Comment by netvyper** [comment]
@sharkykh I'm afraid not. New log attached below.

[sickrage.log.txt](https://github.com/SickRage/SickRage/files/1004729/sickrage.log.txt)

**Comment by sharkykh** [comment]
@netvyper Very weird.
Please stop SickRage and run this from Start > Run (or WinKey+R):
`C:\SickRage\Python\python.exe C:\SickRage\SickRage\SickBeard.py --force-update`
(^ This will make sure SickRage is up to date)
After that, delete the mako cache folder like before,
and start SickRage again.

**Comment by netvyper** [comment]
@sharkykh Still the same symptoms.

I cleared the logs, and followed the process you described - the log for the first start after is attached. The log file gets rather large rather quickly.

[sickrage.log.txt](https://github.com/SickRage/SickRage/files/1004920/sickrage.log.txt)

I appreciate your assistance thus far.

**Comment by sharkykh** [comment]
It seems like the mako template is not compiled correctly.
Maybe it has something to do with the domain you're using...
You're behind a reverse proxy, correct?
Can you try with a local address / localhost?

**Comment by netvyper** [comment]
I was using the localhost address from the box itself.

curious, and somewhat irritating one; I did a reboot for windows updates, and it seems to have come back correctly... I hate it when it does that.

**Comment by sharkykh** [comment]
@netvyper That's from before. I think.
Because it was before you started SickRage again.
```
2017-05-16 16:13:30 INFO MAIN :: Starting SickRage [master] using 'C:\SickRage\Data\config.ini'
```

You can just clear the logs again (like before) so you'll get a fresh start now that it doesn't error anymore.

Anything's possible with Windows... :rofl:
