### ISSUE TITLE
[APP SUBMITTED]: [Error 2] The system cannot find the file specified: u'C:\\NAS_drive\\Videos\\Serier\\Quantico'

### ISSUE THREAD

**Issue by Tiwas** [SickRage/SickRage#1787]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@b790df702cf1ef84ee64b591f40ce6fae86976dc
No Log available with ERRORS:
### ERROR
```
Thread-20 :: [b790df7] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 2291, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "C:\SickRage.io\SickRage\sickbeard\processTV.py", line 243, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "C:\SickRage.io\SickRage\sickbeard\processTV.py", line 560, in process_media
    result.result = processor.process()
  File "C:\SickRage.io\SickRage\sickbeard\postProcessor.py", line 1027, in process
    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
  File "C:\SickRage.io\SickRage\sickbeard\helpers.py", line 1578, in verify_freespace
    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev:  # pylint: disable=no-member
  File "C:\SickRage.io\SickRage\sickrage\helper\encoding.py", line 38, in ek
    result = function(*args, **kwargs)
WindowsError: [Error 2] The system cannot find the file specified: u'C:\\NAS_drive\\Videos\\Serier\\Quantico'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Tiwas** [comment]
Ok, I know this has been "auto reported" before, but it was closed before I got to add details.

This happens, as it seems, randomly if the show folder's not present. It doesn't seem to be affected by special characters as it happens to even "Archer". If the main show folder is created it will create other folders by itself.

How to make the error appear:
1. Delete the show folder
2. Run the post processor to add the show to its' folder

Need any more info?

**Comment by neoatomic** [comment]
Under the Post-processing settings is an option to create missing folders. Make sure that is enabled.

**Comment by Tiwas** [comment]
@neoatomic It is. One of the first things I checked. Also, this doesn't happen to all shows - which is weird in itself.

**Comment by Tiwas** [comment]
This is the error I receive when doing a manual post processing


> Error
> 
> [Error 2] The system cannot find the file specified: u'C:\\NAS_drive\\Videos\\Serier\\American Dad!'
> Traceback
> 
> Traceback (most recent call last):
> File "C:\SickRage.io\SickRage\lib\tornado\web.py", line 1415, in _execute result = yield result
> File "C:\SickRage.io\SickRage\lib\tornado\gen.py", line 870, in run value = future.result()
> File "C:\SickRage.io\SickRage\lib\tornado\concurrent.py", line 215, in result raise_exc_info(self._exc_info)
> File "C:\SickRage.io\SickRage\lib\tornado\gen.py", line 876, in run yielded = self.gen.throw(*exc_info)
> File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 254, in get results = yield self.async_call(method)
> File "C:\SickRage.io\SickRage\lib\tornado\gen.py", line 870, in run value = future.result()
> File "C:\SickRage.io\SickRage\lib\concurrent\futures\_base.py", line 400, in result return self.__get_result()
> File "C:\SickRage.io\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result reraise(self._exception, self._traceback)
> File "C:\SickRage.io\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_)
> File "C:\SickRage.io\SickRage\lib\concurrent\futures\thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs)
> File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 270, in async_call result = function(**kwargs)
> File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 2291, in processEpisode is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
> File "C:\SickRage.io\SickRage\sickbeard\processTV.py", line 243, in processDir process_media(path, [video], nzbName, process_method, force, is_priority, result)
> File "C:\SickRage.io\SickRage\sickbeard\processTV.py", line 560, in process_media result.result = processor.process()
> File "C:\SickRage.io\SickRage\sickbeard\postProcessor.py", line 1027, in process if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method): # pylint: disable=protected-access
> File "C:\SickRage.io\SickRage\sickbeard\helpers.py", line 1578, in verify_freespace if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev: # pylint: disable=no-member
> File "C:\SickRage.io\SickRage\sickrage\helper\encoding.py", line 38, in ek result = function(*args, **kwargs)
> WindowsError: [Error 2] The system cannot find the file specified: u'C:\\NAS_drive\\Videos\\Serier\\American Dad!'
> Request Info
> 
> body: proc_dir=C%3A%5C%5BDownloads%5D%5C%5BSAB%5D%5CComplete%5CTV&process_method=move&force=on&is_priority=on&delete_on=on
> files: {}
> protocol: http
> connection:
> body_arguments: {'is_priority': ['on'], 'proc_dir': ['C:\\[Downloads]\\[SAB]\\Complete\\TV'], 'force': ['on'], 'delete_on': ['on'], 'process_method': ['move']}
> uri: /home/postprocess/processEpisode
> query_arguments: {}
> _start_time: 1463514198.96
> headers: {'Content-Length': '116', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0', 'Host': '192.168.1.101:8085', 'Referer': 'http://192.168.1.101:8085/home/postprocess/', 'Cookie': 'plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=charts; late_view2=list; wanted_view2=list; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; imdb_top_dvd_rentals_view=thumb; sickrage_user="2|1:0|10:1462479948|13:sickrage_user|44:YzZiZjM5NjRiMjk4YmRlNTEyOTc1OGUwMGQyZDViZDM=|423e2d99ef09ea70b3fd2981878eff183c8d8987746c48952f6f29d4ccf4fbe4"', 'Content-Type': 'application/x-www-form-urlencoded'}
> host: 192.168.1.101:8085
> version: HTTP/1.1
> arguments: {'is_priority': 'on', 'force': 'on', 'proc_dir': 'C:\\[Downloads]\\[SAB]\\Complete\\TV', 'delete_on': 'on', 'process_method': 'move'}
> _finish_time: None
> query:
> path: /home/postprocess/processEpisode
> _cookies: Set-Cookie: blu_ray_com_new_releases_view=thumb Set-Cookie: imdb_box_office_view=thumb Set-Cookie: imdb_top_dvd_rentals_view=thumb Set-Cookie: late_view=list Set-Cookie: late_view2=list Set-Cookie: plushContainerWidth=100%25 Set-Cookie: plushMultiOps=1 Set-Cookie: plushNoTopMenu=0 Set-Cookie: sickrage_user="2|1:0|10:1462479948|13:sickrage_user|44:YzZiZjM5NjRiMjk4YmRlNTEyOTc1OGUwMGQyZDViZDM=|423e2d99ef09ea70b3fd2981878eff183c8d8987746c48952f6f29d4ccf4fbe4" Set-Cookie: snatched_view=list Set-Cookie: snatched_view2=list Set-Cookie: soon_view=thumb Set-Cookie: soon_view2=thumbs Set-Cookie: suggest_view=thumb Set-Cookie: suggestions_charts_menu_selected=charts Set-Cookie: wanted_view2=list
> method: POST
> remote_ip: 192.168.1.13

**Comment by neoatomic** [comment]
@Tiwas You say it doesn't happen to all shows. Could you check for me if it are shows that have any special characters in there folder/show name.? 
I see this error is for `American Dad!` and as you are on Windows then special characters like an `!` can be an issue.

**Comment by Tiwas** [comment]
@neoatomic Nope. It happens to "Quantico" (in the main post) and even "Archer".

**Comment by Tiwas** [comment]
> Error
> 
> [Error 2] The system cannot find the file specified: u'C:\\NAS_drive\\Videos\\Serier\\Fresh Off the Boat'
> Traceback
> 
> Traceback (most recent call last):
> File "C:\SickRage.io\SickRage\lib\tornado\web.py", line 1415, in _execute result = yield result
> File "C:\SickRage.io\SickRage\lib\tornado\gen.py", line 870, in run value = future.result()
> File "C:\SickRage.io\SickRage\lib\tornado\concurrent.py", line 215, in result raise_exc_info(self._exc_info)
> File "C:\SickRage.io\SickRage\lib\tornado\gen.py", line 876, in run yielded = self.gen.throw(*exc_info)
> File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 254, in get results = yield self.async_call(method)
> File "C:\SickRage.io\SickRage\lib\tornado\gen.py", line 870, in run value = future.result()
> File "C:\SickRage.io\SickRage\lib\concurrent\futures\_base.py", line 400, in result return self.__get_result()
> File "C:\SickRage.io\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result reraise(self._exception, self._traceback)
> File "C:\SickRage.io\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_)
> File "C:\SickRage.io\SickRage\lib\concurrent\futures\thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs)
> File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 270, in async_call result = function(**kwargs)
> File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 2291, in processEpisode is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
> File "C:\SickRage.io\SickRage\sickbeard\processTV.py", line 243, in processDir process_media(path, [video], nzbName, process_method, force, is_priority, result)
> File "C:\SickRage.io\SickRage\sickbeard\processTV.py", line 560, in process_media result.result = processor.process()
> File "C:\SickRage.io\SickRage\sickbeard\postProcessor.py", line 1027, in process if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method): # pylint: disable=protected-access
> File "C:\SickRage.io\SickRage\sickbeard\helpers.py", line 1578, in verify_freespace if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev: # pylint: disable=no-member
> File "C:\SickRage.io\SickRage\sickrage\helper\encoding.py", line 38, in ek result = function(*args, **kwargs)
> WindowsError: [Error 2] The system cannot find the file specified: u'C:\\NAS_drive\\Videos\\Serier\\Fresh Off the Boat'
> Request Info
> 
> body: proc_dir=C%3A%5C%5BDownloads%5D%5C%5BSAB%5D%5CComplete%5CTV&process_method=move&is_priority=on&delete_on=on&failed=on
> files: {}
> protocol: http
> connection:
> body_arguments: {'is_priority': ['on'], 'failed': ['on'], 'proc_dir': ['C:\\[Downloads]\\[SAB]\\Complete\\TV'], 'delete_on': ['on'], 'process_method': ['move']}
> uri: /home/postprocess/processEpisode
> query_arguments: {}
> _start_time: 1463556569.52
> headers: {'Content-Length': '117', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0', 'Host': '192.168.1.101:8085', 'Referer': 'http://192.168.1.101:8085/home/postprocess/', 'Cookie': 'plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=charts; late_view2=list; wanted_view2=list; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; imdb_top_dvd_rentals_view=thumb; sickrage_user="2|1:0|10:1462479948|13:sickrage_user|44:YzZiZjM5NjRiMjk4YmRlNTEyOTc1OGUwMGQyZDViZDM=|423e2d99ef09ea70b3fd2981878eff183c8d8987746c48952f6f29d4ccf4fbe4"', 'Content-Type': 'application/x-www-form-urlencoded'}
> host: 192.168.1.101:8085
> version: HTTP/1.1
> arguments: {'is_priority': 'on', 'failed': 'on', 'proc_dir': 'C:\\[Downloads]\\[SAB]\\Complete\\TV', 'delete_on': 'on', 'process_method': 'move'}
> _finish_time: None
> query:
> path: /home/postprocess/processEpisode
> _cookies: Set-Cookie: blu_ray_com_new_releases_view=thumb Set-Cookie: imdb_box_office_view=thumb Set-Cookie: imdb_top_dvd_rentals_view=thumb Set-Cookie: late_view=list Set-Cookie: late_view2=list Set-Cookie: plushContainerWidth=100%25 Set-Cookie: plushMultiOps=1 Set-Cookie: plushNoTopMenu=0 Set-Cookie: sickrage_user="2|1:0|10:1462479948|13:sickrage_user|44:YzZiZjM5NjRiMjk4YmRlNTEyOTc1OGUwMGQyZDViZDM=|423e2d99ef09ea70b3fd2981878eff183c8d8987746c48952f6f29d4ccf4fbe4" Set-Cookie: snatched_view=list Set-Cookie: snatched_view2=list Set-Cookie: soon_view=thumb Set-Cookie: soon_view2=thumbs Set-Cookie: suggest_view=thumb Set-Cookie: suggestions_charts_menu_selected=charts Set-Cookie: wanted_view2=list
> method: POST
> remote_ip: 192.168.1.13

**Comment by Tiwas** [comment]
Error

[Error 2] The system cannot find the file specified: u'C:\\NAS_drive\\Videos\\Serier\\Ink Master'
Traceback

Traceback (most recent call last):
File "C:\SickRage.io\SickRage\lib\tornado\web.py", line 1415, in _execute result = yield result
File "C:\SickRage.io\SickRage\lib\tornado\gen.py", line 870, in run value = future.result()
File "C:\SickRage.io\SickRage\lib\tornado\concurrent.py", line 215, in result raise_exc_info(self._exc_info)
File "C:\SickRage.io\SickRage\lib\tornado\gen.py", line 876, in run yielded = self.gen.throw(*exc_info)
File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 254, in get results = yield self.async_call(method)
File "C:\SickRage.io\SickRage\lib\tornado\gen.py", line 870, in run value = future.result()
File "C:\SickRage.io\SickRage\lib\concurrent\futures\_base.py", line 400, in result return self.__get_result()
File "C:\SickRage.io\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result reraise(self._exception, self._traceback)
File "C:\SickRage.io\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_)
File "C:\SickRage.io\SickRage\lib\concurrent\futures\thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs)
File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 270, in async_call result = function(**kwargs)
File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 2291, in processEpisode is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
File "C:\SickRage.io\SickRage\sickbeard\processTV.py", line 243, in processDir process_media(path, [video], nzbName, process_method, force, is_priority, result)
File "C:\SickRage.io\SickRage\sickbeard\processTV.py", line 560, in process_media result.result = processor.process()
File "C:\SickRage.io\SickRage\sickbeard\postProcessor.py", line 1027, in process if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method): # pylint: disable=protected-access
File "C:\SickRage.io\SickRage\sickbeard\helpers.py", line 1578, in verify_freespace if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev: # pylint: disable=no-member
File "C:\SickRage.io\SickRage\sickrage\helper\encoding.py", line 38, in ek result = function(*args, **kwargs)
WindowsError: [Error 2] The system cannot find the file specified: u'C:\\NAS_drive\\Videos\\Serier\\Ink Master'
Request Info

body: proc_dir=C%3A%5C%5BDownloads%5D%5C%5BSAB%5D%5CComplete%5CTV&process_method=move&is_priority=on&delete_on=on&failed=on
files: {}
protocol: http
connection:
body_arguments: {'is_priority': ['on'], 'failed': ['on'], 'proc_dir': ['C:\\[Downloads]\\[SAB]\\Complete\\TV'], 'delete_on': ['on'], 'process_method': ['move']}
uri: /home/postprocess/processEpisode
query_arguments: {}
_start_time: 1463556658.36
headers: {'Content-Length': '117', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0', 'Host': '192.168.1.101:8085', 'Referer': 'http://192.168.1.101:8085/home/postprocess/', 'Cache-Control': 'max-age=0', 'Cookie': 'plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=charts; late_view2=list; wanted_view2=list; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; imdb_top_dvd_rentals_view=thumb; sickrage_user="2|1:0|10:1462479948|13:sickrage_user|44:YzZiZjM5NjRiMjk4YmRlNTEyOTc1OGUwMGQyZDViZDM=|423e2d99ef09ea70b3fd2981878eff183c8d8987746c48952f6f29d4ccf4fbe4"', 'Content-Type': 'application/x-www-form-urlencoded'}
host: 192.168.1.101:8085
version: HTTP/1.1
arguments: {'is_priority': 'on', 'failed': 'on', 'proc_dir': 'C:\\[Downloads]\\[SAB]\\Complete\\TV', 'delete_on': 'on', 'process_method': 'move'}
_finish_time: None
query:
path: /home/postprocess/processEpisode
_cookies: Set-Cookie: blu_ray_com_new_releases_view=thumb Set-Cookie: imdb_box_office_view=thumb Set-Cookie: imdb_top_dvd_rentals_view=thumb Set-Cookie: late_view=list Set-Cookie: late_view2=list Set-Cookie: plushContainerWidth=100%25 Set-Cookie: plushMultiOps=1 Set-Cookie: plushNoTopMenu=0 Set-Cookie: sickrage_user="2|1:0|10:1462479948|13:sickrage_user|44:YzZiZjM5NjRiMjk4YmRlNTEyOTc1OGUwMGQyZDViZDM=|423e2d99ef09ea70b3fd2981878eff183c8d8987746c48952f6f29d4ccf4fbe4" Set-Cookie: snatched_view=list Set-Cookie: snatched_view2=list Set-Cookie: soon_view=thumb Set-Cookie: soon_view2=thumbs Set-Cookie: suggest_view=thumb Set-Cookie: suggestions_charts_menu_selected=charts Set-Cookie: wanted_view2=list
method: POST
remote_ip: 192.168.1.13

**Comment by Tiwas** [comment]
Error

[Error 2] The system cannot find the file specified: u"C:\\NAS_drive\\Videos\\Serier\\Marvel's Agents of S.H.I.E.L.D"
Traceback

Traceback (most recent call last):
File "C:\SickRage.io\SickRage\lib\tornado\web.py", line 1415, in _execute result = yield result
File "C:\SickRage.io\SickRage\lib\tornado\gen.py", line 870, in run value = future.result()
File "C:\SickRage.io\SickRage\lib\tornado\concurrent.py", line 215, in result raise_exc_info(self._exc_info)
File "C:\SickRage.io\SickRage\lib\tornado\gen.py", line 876, in run yielded = self.gen.throw(*exc_info)
File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 254, in get results = yield self.async_call(method)
File "C:\SickRage.io\SickRage\lib\tornado\gen.py", line 870, in run value = future.result()
File "C:\SickRage.io\SickRage\lib\concurrent\futures\_base.py", line 400, in result return self.__get_result()
File "C:\SickRage.io\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result reraise(self._exception, self._traceback)
File "C:\SickRage.io\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_)
File "C:\SickRage.io\SickRage\lib\concurrent\futures\thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs)
File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 270, in async_call result = function(**kwargs)
File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 2291, in processEpisode is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
File "C:\SickRage.io\SickRage\sickbeard\processTV.py", line 243, in processDir process_media(path, [video], nzbName, process_method, force, is_priority, result)
File "C:\SickRage.io\SickRage\sickbeard\processTV.py", line 560, in process_media result.result = processor.process()
File "C:\SickRage.io\SickRage\sickbeard\postProcessor.py", line 1027, in process if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method): # pylint: disable=protected-access
File "C:\SickRage.io\SickRage\sickbeard\helpers.py", line 1578, in verify_freespace if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev: # pylint: disable=no-member
File "C:\SickRage.io\SickRage\sickrage\helper\encoding.py", line 38, in ek result = function(*args, **kwargs)
WindowsError: [Error 2] The system cannot find the file specified: u"C:\\NAS_drive\\Videos\\Serier\\Marvel's Agents of S.H.I.E.L.D"
Request Info

body: proc_dir=C%3A%5C%5BDownloads%5D%5C%5BSAB%5D%5CComplete%5CTV&process_method=move&is_priority=on&delete_on=on&failed=on
files: {}
protocol: http
connection:
body_arguments: {'is_priority': ['on'], 'failed': ['on'], 'proc_dir': ['C:\\[Downloads]\\[SAB]\\Complete\\TV'], 'delete_on': ['on'], 'process_method': ['move']}
uri: /home/postprocess/processEpisode
query_arguments: {}
_start_time: 1463556723.24
headers: {'Content-Length': '117', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0', 'Host': '192.168.1.101:8085', 'Referer': 'http://192.168.1.101:8085/home/postprocess/', 'Cache-Control': 'max-age=0', 'Cookie': 'plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=charts; late_view2=list; wanted_view2=list; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; imdb_top_dvd_rentals_view=thumb; sickrage_user="2|1:0|10:1462479948|13:sickrage_user|44:YzZiZjM5NjRiMjk4YmRlNTEyOTc1OGUwMGQyZDViZDM=|423e2d99ef09ea70b3fd2981878eff183c8d8987746c48952f6f29d4ccf4fbe4"', 'Content-Type': 'application/x-www-form-urlencoded'}
host: 192.168.1.101:8085
version: HTTP/1.1
arguments: {'is_priority': 'on', 'failed': 'on', 'proc_dir': 'C:\\[Downloads]\\[SAB]\\Complete\\TV', 'delete_on': 'on', 'process_method': 'move'}
_finish_time: None
query:
path: /home/postprocess/processEpisode
_cookies: Set-Cookie: blu_ray_com_new_releases_view=thumb Set-Cookie: imdb_box_office_view=thumb Set-Cookie: imdb_top_dvd_rentals_view=thumb Set-Cookie: late_view=list Set-Cookie: late_view2=list Set-Cookie: plushContainerWidth=100%25 Set-Cookie: plushMultiOps=1 Set-Cookie: plushNoTopMenu=0 Set-Cookie: sickrage_user="2|1:0|10:1462479948|13:sickrage_user|44:YzZiZjM5NjRiMjk4YmRlNTEyOTc1OGUwMGQyZDViZDM=|423e2d99ef09ea70b3fd2981878eff183c8d8987746c48952f6f29d4ccf4fbe4" Set-Cookie: snatched_view=list Set-Cookie: snatched_view2=list Set-Cookie: soon_view=thumb Set-Cookie: soon_view2=thumbs Set-Cookie: suggest_view=thumb Set-Cookie: suggestions_charts_menu_selected=charts Set-Cookie: wanted_view2=list
method: POST
remote_ip: 192.168.1.13

**Comment by Tiwas** [comment]
Error

[Error 2] The system cannot find the file specified: u'C:\\NAS_drive\\Videos\\Serier\\The Flash (2014)'
Traceback

Traceback (most recent call last):
File "C:\SickRage.io\SickRage\lib\tornado\web.py", line 1415, in _execute result = yield result
File "C:\SickRage.io\SickRage\lib\tornado\gen.py", line 870, in run value = future.result()
File "C:\SickRage.io\SickRage\lib\tornado\concurrent.py", line 215, in result raise_exc_info(self._exc_info)
File "C:\SickRage.io\SickRage\lib\tornado\gen.py", line 876, in run yielded = self.gen.throw(*exc_info)
File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 254, in get results = yield self.async_call(method)
File "C:\SickRage.io\SickRage\lib\tornado\gen.py", line 870, in run value = future.result()
File "C:\SickRage.io\SickRage\lib\concurrent\futures\_base.py", line 400, in result return self.__get_result()
File "C:\SickRage.io\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result reraise(self._exception, self._traceback)
File "C:\SickRage.io\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_)
File "C:\SickRage.io\SickRage\lib\concurrent\futures\thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs)
File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 270, in async_call result = function(**kwargs)
File "C:\SickRage.io\SickRage\sickbeard\webserve.py", line 2291, in processEpisode is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
File "C:\SickRage.io\SickRage\sickbeard\processTV.py", line 243, in processDir process_media(path, [video], nzbName, process_method, force, is_priority, result)
File "C:\SickRage.io\SickRage\sickbeard\processTV.py", line 560, in process_media result.result = processor.process()
File "C:\SickRage.io\SickRage\sickbeard\postProcessor.py", line 1027, in process if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method): # pylint: disable=protected-access
File "C:\SickRage.io\SickRage\sickbeard\helpers.py", line 1578, in verify_freespace if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev: # pylint: disable=no-member
File "C:\SickRage.io\SickRage\sickrage\helper\encoding.py", line 38, in ek result = function(*args, **kwargs)
WindowsError: [Error 2] The system cannot find the file specified: u'C:\\NAS_drive\\Videos\\Serier\\The Flash (2014)'
Request Info

body: proc_dir=C%3A%5C%5BDownloads%5D%5C%5BSAB%5D%5CComplete%5CTV&process_method=move&is_priority=on&delete_on=on&failed=on
files: {}
protocol: http
connection:
body_arguments: {'is_priority': ['on'], 'failed': ['on'], 'proc_dir': ['C:\\[Downloads]\\[SAB]\\Complete\\TV'], 'delete_on': ['on'], 'process_method': ['move']}
uri: /home/postprocess/processEpisode
query_arguments: {}
_start_time: 1463556804.71
headers: {'Content-Length': '117', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0', 'Host': '192.168.1.101:8085', 'Referer': 'http://192.168.1.101:8085/home/postprocess/', 'Cache-Control': 'max-age=0', 'Cookie': 'plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=charts; late_view2=list; wanted_view2=list; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; imdb_top_dvd_rentals_view=thumb; sickrage_user="2|1:0|10:1462479948|13:sickrage_user|44:YzZiZjM5NjRiMjk4YmRlNTEyOTc1OGUwMGQyZDViZDM=|423e2d99ef09ea70b3fd2981878eff183c8d8987746c48952f6f29d4ccf4fbe4"', 'Content-Type': 'application/x-www-form-urlencoded'}
host: 192.168.1.101:8085
version: HTTP/1.1
arguments: {'is_priority': 'on', 'failed': 'on', 'proc_dir': 'C:\\[Downloads]\\[SAB]\\Complete\\TV', 'delete_on': 'on', 'process_method': 'move'}
_finish_time: None
query:
path: /home/postprocess/processEpisode
_cookies: Set-Cookie: blu_ray_com_new_releases_view=thumb Set-Cookie: imdb_box_office_view=thumb Set-Cookie: imdb_top_dvd_rentals_view=thumb Set-Cookie: late_view=list Set-Cookie: late_view2=list Set-Cookie: plushContainerWidth=100%25 Set-Cookie: plushMultiOps=1 Set-Cookie: plushNoTopMenu=0 Set-Cookie: sickrage_user="2|1:0|10:1462479948|13:sickrage_user|44:YzZiZjM5NjRiMjk4YmRlNTEyOTc1OGUwMGQyZDViZDM=|423e2d99ef09ea70b3fd2981878eff183c8d8987746c48952f6f29d4ccf4fbe4" Set-Cookie: snatched_view=list Set-Cookie: snatched_view2=list Set-Cookie: soon_view=thumb Set-Cookie: soon_view2=thumbs Set-Cookie: suggest_view=thumb Set-Cookie: suggestions_charts_menu_selected=charts Set-Cookie: wanted_view2=list
method: POST
remote_ip: 192.168.1.13
