### ISSUE TITLE
Post-Processing Fails When Show Directory is Missing

### ISSUE THREAD

**Issue by PowerPanda** [SickRage/SickRage#1790]
Branch/Commit: master
Commit: b790df702cf1ef84ee64b591f40ce6fae86976dc
Version: 2016.05.12-1
Database Version: 43.1
Python Version: 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
OS: Windows 10 (Windows-8-6.2.9200)
What you did:  Post-Processed an episode where the show directory did not exist.
What happened:  "SickBeard: Failed to post-process - Server returned status 500!"
What you expected:  Expected SR to create the show directory and post-process the file.
Logs:
SABnzbd Script Log: http://pastebin.com/J1xRH2Ww
SR Manual Post-Processing Error: http://pastebin.com/1fezFPNL

PASTE LOGS HERE
ERROR LOG:
```
2016-05-16 23:37:30 Thread-23 :: [b790df7] Failed doing webui callback: Traceback (most recent call last):
  File "C:\Program Files (x86)\SickRage\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\Program Files (x86)\SickRage\sickbeard\webserve.py", line 2291, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "C:\Program Files (x86)\SickRage\sickbeard\processTV.py", line 290, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "C:\Program Files (x86)\SickRage\sickbeard\processTV.py", line 560, in process_media
    result.result = processor.process()
  File "C:\Program Files (x86)\SickRage\sickbeard\postProcessor.py", line 1027, in process
    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
  File "C:\Program Files (x86)\SickRage\sickbeard\helpers.py", line 1578, in verify_freespace
    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev:  # pylint: disable=no-member
  File "C:\Program Files (x86)\SickRage\sickrage\helper\encoding.py", line 38, in ek
    result = function(*args, **kwargs)
WindowsError: [Error 2] The system cannot find the file specified: u'V:\\Game of Thrones'
```
--------------------------------------------------------------------------------------------------------------------------------------------
Previous Versions of SR had no issues with post-processing files that didn't have the show directory.  Both flags below are set to 1:
create_missing_show_dirs = 1
add_shows_wo_dir = 1
I have used SickRage ever since the split with Sickragetv and have never had these issues.  I always delete my show directories when I finish watching the episodes of a given show.  This issue started happening to my system on May 11, 2016.

Please advise and thank you for your assistance.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by PowerPanda** [comment]
Debug logs:
2016-05-16 23:37:30 Thread-23 :: [b790df7] Failed doing webui callback: Traceback (most recent call last):
File "C:\Program Files (x86)\SickRage\sickbeard\webserve.py", line 270, in async_call
result = function(*kwargs)
File "C:\Program Files (x86)\SickRage\sickbeard\webserve.py", line 2291, in processEpisode
is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
File "C:\Program Files (x86)\SickRage\sickbeard\processTV.py", line 290, in processDir
process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
File "C:\Program Files (x86)\SickRage\sickbeard\processTV.py", line 560, in process_media
result.result = processor.process()
File "C:\Program Files (x86)\SickRage\sickbeard\postProcessor.py", line 1027, in process
if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method): # pylint: disable=protected-access
File "C:\Program Files (x86)\SickRage\sickbeard\helpers.py", line 1578, in verify_freespace
if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev: # pylint: disable=no-member
File "C:\Program Files (x86)\SickRage\sickrage\helper\encoding.py", line 38, in ek
result = function(args, **kwargs)

**Comment by PowerPanda** [comment]
Error log:
2016-05-17 17:32:55 Thread-16 :: [b790df7] Failed doing webui callback: Traceback (most recent call last):
  File "C:\Program Files (x86)\SickRage\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\Program Files (x86)\SickRage\sickbeard\webserve.py", line 2291, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "C:\Program Files (x86)\SickRage\sickbeard\processTV.py", line 290, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "C:\Program Files (x86)\SickRage\sickbeard\processTV.py", line 560, in process_media
    result.result = processor.process()
  File "C:\Program Files (x86)\SickRage\sickbeard\postProcessor.py", line 1027, in process
    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
  File "C:\Program Files (x86)\SickRage\sickbeard\helpers.py", line 1578, in verify_freespace
    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev:  # pylint: disable=no-member
  File "C:\Program Files (x86)\SickRage\sickrage\helper\encoding.py", line 38, in ek
    result = function(*args, **kwargs)
WindowsError: [Error 2] The system cannot find the file specified: u'V:\\Game of Thrones'

**Comment by neoatomic** [comment]
Under the Post-processing settings is an option to create missing folders. Make sure that is enabled.

**Comment by PowerPanda** [comment]
Hi neoatomic, that option is checked and the related flag in the config.ini is set to 1.   This issue seems to have been introduced in a build around May 11.

**Comment by neoatomic** [comment]
@PowerPanda Are you having this issue with only 1 or more shows.?
I'm particularly interested in there naming of the folder/show.

**Comment by PowerPanda** [comment]
It's happening to all shows that don't already have the show directory.

**Comment by cbrherms** [comment]
Appears to be across the board with all users. 
I myself had the same problem after changing servers and reimporting show list via config restore.
Had to manually create all folders on new media store.

**Comment by PowerPanda** [comment]
@cbrherms  I've noticed alot of other users with the same "The system cannot find the file specified:..." error message as well.  What might be causing confusion is that there are several different titles of these open issues.

**Comment by Tulosi** [comment]
+1 - Exact same issue. I was many hundreds of commits behind, so decided to update - now i'm stuck with the same issue stated above.

Automatic post-processing will fail if the directory does not exist - despite the "Create missing show directories" being checked under post-processing settings. 

It generated the following error:
[b790df7] Exception generated in thread POSTPROCESSER: error 2 : No such file or directory

Which then leads to the "Server Status" Scheduler for "Post Process" having it's "Alive" status, set to "False" until a server restart is performed.

**Comment by neoatomic** [comment]
Just to verify, where any of you using postpone processing till subs where available.?

**Comment by Tulosi** [comment]
Not to the best of my knowledge - but I also do not even see that option under "Post Processing"...

**Comment by neoatomic** [comment]
Yes, it was removed. :) 
Maybe something related to that is coursing the issue. But its something that @miigotu will have to check. But we need as much info as possible to narrow the issue.

**Comment by miigotu** [comment]
Fixed in https://github.com/SickRage/SickRage/commit/0b7e0995077c598bdabd84af201180ad7323c92e
