### ISSUE TITLE
Unable to remove show

### ISSUE THREAD

**Issue by Scensis** [SickRage/SickRage#1794]
Branch/Commit: Master / b790df702cf1ef84ee64b591f40ce6fae86976dc
Phyton: 2.7.9 (default, Mar 1 2015, 12:57:24) [GCC 4.9.2]
OS: Linux-3.16.7-ckt20-feral-x86_64-with-debian-8.4
What you did: Tried to remove a show from the home page
What happened: It didn't go away. So i tried to remove it from Mass Update (see log)
What you expected: To have the show removed.
Logs:
```
2016-05-17 00:00:48 ERROR    Thread-34 :: [b790df7] Failed doing webui callback: Traceback (most recent call last):
AACantRemoveShowException: Kaze no Stigma is already queued to be removed
AA    raise CantRemoveShowException('{0} is already queued to be removed'.format(show.name))
AA  File "/media/sdy1/*******/.sickrage/sickbeard/show_queue.py", line 160, in removeShow
AA    sickbeard.showQueueScheduler.action.removeShow(show_obj)
AA  File "/media/sdy1/*******/.sickrage/sickbeard/webserve.py", line 3476, in massUpdate
AA    result = function(**kwargs)
AA  File "/media/sdy1/*******/.sickrage/sickbeard/webserve.py", line 270, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "/media/sdy1/*******/.sickrage/lib/concurrent/futures/thread.py", line 61, in run
AA    exec('raise exc_type, exc_value, traceback', {}, locals_)
AA  File "/media/sdy1/*******/.sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise
AA    reraise(self._exception, self._traceback)
AA  File "/media/sdy1/*******/.sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result
AA    return self.__get_result()
AA  File "/media/sdy1/*******/.sickrage/lib/concurrent/futures/_base.py", line 400, in result
AA    value = future.result()
AA  File "/media/sdy1/*******/.sickrage/lib/tornado/gen.py", line 870, in run
AA    results = yield self.async_call(method)
AA  File "/media/sdy1/*******/.sickrage/sickbeard/webserve.py", line 254, in get
AA    yielded = self.gen.throw(*exc_info)
AA  File "/media/sdy1/*******/.sickrage/lib/tornado/gen.py", line 876, in run
AA    raise_exc_info(self._exc_info)
AA  File "/media/sdy1/*******/.sickrage/lib/tornado/concurrent.py", line 215, in result
AA    value = future.result()
AA  File "/media/sdy1/*******/.sickrage/lib/tornado/gen.py", line 870, in run
AA    result = yield result
AA  File "/media/sdy1/*******/.sickrage/lib/tornado/web.py", line 1415, in _execute
AATraceback (most recent call last):
AAHTTPServerRequest(protocol='http', host='cacus.feralhosting.com', method='POST', uri='/*******/sickrage/manage/massUpdate', version='HTTP/1.0', remote_ip='10.0.10.94', headers={'Content-Length': '79', 'Accept-Language': 'en-US,en;q=0.8,nb;q=0.6', 'X-Host': 'cacus.feralhosting.com', 'Connection': 'close', 'X-Requested-With': 'XMLHttpRequest', 'X-Real-Ip': '10.0.0.1', 'Accept-Encoding': 'gzip, deflate', 'Origin': 'http://cacus.feralhosting.com', 'X-Nginx-Proxy': 'true', 'X-Forwarded-For': '::ffff:89.8.50.18, 10.0.0.1', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36', 'Host': 'cacus.feralhosting.com', 'X-Forwarded-Proto': 'http', 'Cookie': 'sickrage_user="2|1:0|10:1462905307|13:sickrage_user|44:YzI3Zjk0ZTZmNWRlZDMwOGQxOWY0MGNlNzQ4ZDczZmE=|d584b8be387eddb020115a86cad4d6f07808f3661318214b952a7eeb3085f1ac"', 'Referer': 'http://cacus.feralhosting.com/*******/sickrage/manage/', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
AA2016-05-17 00:00:47 ERROR    Uncaught exception POST /*******/sickrage/manage/massUpdate (10.0.10.94)
AACantRemoveShowException: Kaze no Stigma is already queued to be removed
AA    raise CantRemoveShowException('{0} is already queued to be removed'.format(show.name))
AA  File "/media/sdy1/*******/.sickrage/sickbeard/show_queue.py", line 160, in removeShow
AA    sickbeard.showQueueScheduler.action.removeShow(show_obj)
AA  File "/media/sdy1/*******/.sickrage/sickbeard/webserve.py", line 3476, in massUpdate
AA    result = function(**kwargs)
AA  File "/media/sdy1/*******/.sickrage/sickbeard/webserve.py", line 270, in async_call
AATraceback (most recent call last):
AACantRemoveShowException: Kaze no Stigma is already queued to be removed
AA    raise CantRemoveShowException('{0} is already queued to be removed'.format(show.name))
AA  File "/media/sdy1/*******/.sickrage/sickbeard/show_queue.py", line 160, in removeShow
AA    sickbeard.showQueueScheduler.action.removeShow(show_obj)
AA  File "/media/sdy1/*******/.sickrage/sickbeard/webserve.py", line 3476, in massUpdate
AA    result = function(**kwargs)
AA  File "/media/sdy1/*******/.sickrage/sickbeard/webserve.py", line 270, in async_call
2016-05-17 00:00:47 ERROR    Thread-30 :: [b790df7] Failed doing webui callback: Traceback (most recent call last):
2016-05-16 23:58:36 ERROR    Thread-25 :: [b790df7] Failed doing webui callback: Traceback (most recent call last):
AACantRemoveShowException: Kaze no Stigma is already queued to be removed
AA    raise CantRemoveShowException('{0} is already queued to be removed'.format(show.name))
AA  File "/media/sdy1/*******/.sickrage/sickbeard/show_queue.py", line 160, in removeShow
AA    sickbeard.showQueueScheduler.action.removeShow(show_obj)
AA  File "/media/sdy1/*******/.sickrage/sickbeard/webserve.py", line 3476, in massUpdate
AA    result = function(**kwargs)
AA  File "/media/sdy1/*******/.sickrage/sickbeard/webserve.py", line 270, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "/media/sdy1/*******/.sickrage/lib/concurrent/futures/thread.py", line 61, in run
AA    exec('raise exc_type, exc_value, traceback', {}, locals_)
AA  File "/media/sdy1/*******/.sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise
AA    reraise(self._exception, self._traceback)
AA  File "/media/sdy1/*******/.sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result
AA    return self.__get_result()
AA  File "/media/sdy1/*******/.sickrage/lib/concurrent/futures/_base.py", line 400, in result
AA    value = future.result()
AA  File "/media/sdy1/*******/.sickrage/lib/tornado/gen.py", line 870, in run
AA    results = yield self.async_call(method)
AA  File "/media/sdy1/*******/.sickrage/sickbeard/webserve.py", line 254, in get
AA    yielded = self.gen.throw(*exc_info)
AA  File "/media/sdy1/*******/.sickrage/lib/tornado/gen.py", line 876, in run
AA    raise_exc_info(self._exc_info)
AA  File "/media/sdy1/*******/.sickrage/lib/tornado/concurrent.py", line 215, in result
AA    value = future.result()
AA  File "/media/sdy1/*******/.sickrage/lib/tornado/gen.py", line 870, in run
AA    result = yield result
AA  File "/media/sdy1/*******/.sickrage/lib/tornado/web.py", line 1415, in _execute
AATraceback (most recent call last):
AAHTTPServerRequest(protocol='http', host='cacus.feralhosting.com', method='POST', uri='/*******/sickrage/manage/massUpdate', version='HTTP/1.0', remote_ip='10.0.10.94', headers={'Content-Length': '79', 'Accept-Language': 'en-US,en;q=0.8,nb;q=0.6', 'X-Host': 'cacus.feralhosting.com', 'Connection': 'close', 'X-Requested-With': 'XMLHttpRequest', 'X-Real-Ip': '10.0.0.1', 'Accept-Encoding': 'gzip, deflate', 'Origin': 'http://cacus.feralhosting.com', 'X-Nginx-Proxy': 'true', 'X-Forwarded-For': '::ffff:89.8.50.18, 10.0.0.1', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36', 'Host': 'cacus.feralhosting.com', 'X-Forwarded-Proto': 'http', 'Cookie': 'sickrage_user="2|1:0|10:1462905307|13:sickrage_user|44:YzI3Zjk0ZTZmNWRlZDMwOGQxOWY0MGNlNzQ4ZDczZmE=|d584b8be387eddb020115a86cad4d6f07808f3661318214b952a7eeb3085f1ac"', 'Referer': 'http://cacus.feralhosting.com/*******/sickrage/manage/', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
AA2016-05-16 23:58:33 ERROR    Uncaught exception POST /*******/sickrage/manage/massUpdate (10.0.10.94)
AACantRemoveShowException: Kaze no Stigma is already queued to be removed
AA    raise CantRemoveShowException('{0} is already queued to be removed'.format(show.name))
AA  File "/media/sdy1/*******/.sickrage/sickbeard/show_queue.py", line 160, in removeShow
AA    sickbeard.showQueueScheduler.action.removeShow(show_obj)
AA  File "/media/sdy1/*******/.sickrage/sickbeard/webserve.py", line 3476, in massUpdate
AA    result = function(**kwargs)
AA  File "/media/sdy1/*******/.sickrage/sickbeard/webserve.py", line 270, in async_call
AATraceback (most recent call last):
AACantRemoveShowException: Kaze no Stigma is already queued to be removed
AA    raise CantRemoveShowException('{0} is already queued to be removed'.format(show.name))
AA  File "/media/sdy1/*******/.sickrage/sickbeard/show_queue.py", line 160, in removeShow
AA    sickbeard.showQueueScheduler.action.removeShow(show_obj)
AA  File "/media/sdy1/*******/.sickrage/sickbeard/webserve.py", line 3476, in massUpdate
AA    result = function(**kwargs)
AA  File "/media/sdy1/*******/.sickrage/sickbeard/webserve.py", line 270, in async_call
```

Also, after this problem occurred, new show that i add wont show up on the front page. Like it's not correctly added.

I've tried to restarting SR with no result.

Full log: https://gist.github.com/Scensis/95ee0d31d7772a78b2e7b03c84791f67

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Lots of strange stuff in your log. But i think this is the underlying course. : 
`OSError(13, 'Permission denied'`

So check if there is something set wrong with the user/permissions/rights.
https://github.com/SickRage/SickRage/wiki/Installation-&-Configuration-Guides
Otherwise do a fresh/clean install.

Also keep the post-processing folder as clean as possible. And if you want to seed your torrents, than use hardlink/symlink instead of copy/move.
