### ISSUE TITLE
[APP SUBMITTED]: Parsing failed with several errors.
First error at line 844.

### ISSUE THREAD

**Issue by lastb0isct** [SickRage/SickRage#1795]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.4.8-1-pve-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@b790df702cf1ef84ee64b591f40ce6fae86976dc
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [b790df7] Failed doing webui callback: Traceback (most recent call last):
  File "/root/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/root/sickrage/sickbeard/webserve.py", line 3956, in saveGeneral
    sickbeard.save_config()
  File "/root/sickrage/sickbeard/__init__.py", line 1658, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8')
  File "/root/sickrage/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/root/sickrage/lib/configobj.py", line 1302, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 844.

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by lastb0isct** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.4.8-1-pve-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@b790df702cf1ef84ee64b591f40ce6fae86976dc
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [b790df7] Failed doing webui callback: Traceback (most recent call last):
  File "/root/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/root/sickrage/sickbeard/webserve.py", line 3956, in saveGeneral
    sickbeard.save_config()
  File "/root/sickrage/sickbeard/__init__.py", line 1658, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8')
  File "/root/sickrage/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/root/sickrage/lib/configobj.py", line 1302, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 844.

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by lastb0isct** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.4.8-1-pve-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@b790df702cf1ef84ee64b591f40ce6fae86976dc
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [b790df7] Failed doing webui callback: Traceback (most recent call last):
  File "/root/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/root/sickrage/sickbeard/webserve.py", line 4846, in saveProviders
    sickbeard.save_config()
  File "/root/sickrage/sickbeard/__init__.py", line 1658, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8')
  File "/root/sickrage/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/root/sickrage/lib/configobj.py", line 1302, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 844.

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by neoatomic** [comment]
Need more info/log lines.
What where you doing.? Saving settings.? and did they contain special characters.?

**Comment by sm-k** [comment]
is this reproducible? line 844 in configobj.py is a single comment character

**Comment by lastb0isct** [comment]
i was just attempting to view the schedule.  It was stuck.  I will try and find more logs

**Comment by lastb0isct** [comment]
What logs would you like?  It looks as though this is now happening when i boot up.  I'm unable to start sickrage anymore.  This is the error i'm receiving:

![sickrage](https://cloud.githubusercontent.com/assets/19312164/15342560/22c8d48c-1c4b-11e6-9a26-9c9bdda68249.PNG)

**Comment by duramato** [comment]
Check your config file, most likely corrupt ,  probably at line 844

**Comment by lastb0isct** [comment]
line 844 is a tag, NMA, for notify my android.  Any other ideas?  I can try and just copy an old .ini in from an old backup.

**Comment by duramato** [comment]
Try an old backup

**Comment by lastb0isct** [comment]
That solved it.  I'm scheduling regular backups of this VM anyways.  Thanks for the help!
