### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/mnt/internal/tv/Robot Chicken'

### ISSUE THREAD

**Issue by frdfsnlght** [SickRage/SickRage#1800]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.15.0-031500-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@b790df702cf1ef84ee64b591f40ce6fae86976dc
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [b790df7] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2291, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "/opt/sickrage/sickbeard/processTV.py", line 290, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/opt/sickrage/sickbeard/processTV.py", line 560, in process_media
    result.result = processor.process()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 1027, in process
    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
  File "/opt/sickrage/sickbeard/helpers.py", line 1578, in verify_freespace
    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev:  # pylint: disable=no-member
  File "/opt/sickrage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 2] No such file or directory: '/mnt/internal/tv/Robot Chicken'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
