### ISSUE TITLE
Thread-642 :: [b790df7] Failed doing webui callback: Traceback (most recent call last)

### ISSUE THREAD

**Issue by NeoMod** [SickRage/SickRage#1816]
**INFO**

**Branch/Commit:** master / b790df702cf1ef84ee64b591f40ce6fae86976dc 

**OS:**  Linux-3.4.110-sun7i-armv7l-with-debian-8.4

**Phyton:** 2.7.9 (default, Mar 1 2015, 13:48:22) [GCC 4.9.2] 

**What you did:** While accessing SickRage Interface I noticed the "red circle" near Settings Menu and I went to check for the error. There were two identical errors, as descirbed below. Clearing Error and Reporting Error are not working.

**What happened:** Apparently SickRage is still working correctly (shows are downloading, notifications are sent, subtitles are beeing downloaded too) but when I tried to submit the error the automated procedure failed and generated a similar error. While trying to use the command "Clear Errors" instead the page went "blank" with a few errors: they are included in the Full Log link below. 

**Logs:**

```
2016-05-19 21:28:16 Thread-641 :: [b790df7] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 5356, in viewlog
    with io.open(logger.log_file, 'r', encoding='utf-8') as f:
IOError: [Errno 5] Input/output error: '/media/NAS/sickrage.log'
```

**Full Log:** This is what appears on screen when trying to execute the command "Clear Erros". The file "sickrage.log" mentioned previously is empty. 

https://gist.github.com/NeoMod/9bf8c7ad2eb2feaf212ded609f60e9b6

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
check your drive for io errors, looks like the drive is dying. Otherwise check for permissions issues. This isnt a bug

**Comment by NeoMod** [comment]
**Problem Solved**
Apparently the problem was due to the corruption of the LOG FILE which in turn resulted empty.
Deleting the active LOG FILE and all previous versions solved the problem.

Thank you @miigotu for your help, I discoverd the problem a few minutes later your hint. :+1:

**Comment by miigotu** [comment]
Glad its fixed
