### ISSUE TITLE
[APP SUBMITTED]: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by MaDTaZ** [SickRage/SickRage#1828]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@b790df702cf1ef84ee64b591f40ce6fae86976dc
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [b790df7] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 4372, in index
    t = PageTemplate(rh=self, filename="config_providers.mako")
  File "/opt/sickrage/sickbeard/webserve.py", line 112, in __init__
    self.template = lookup.get_template(filename)
  File "/opt/sickrage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/opt/sickrage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/opt/sickrage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/opt/sickrage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/opt/sickrage/lib/mako/template.py", line 705, in _compile_module_file
    os.write(dest, source)
OSError: [Errno 28] No space left on device

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
