### ISSUE TITLE
Error After Lastest Update (2)

### ISSUE THREAD

**Issue by Vodka2014** [SickRage/SickRage#1831]
@miigotu 

https://github.com/SickRage/SickRage/issues/1817#issuecomment-220742736
```
Branch: https://github.com/SickRage/SickRage/tree/master
Commit: https://github.com/SickRage/SickRage/commit/c4fc189279b71802a417195e60dac66f1b85e338
Version: https://github.com/SickRage/SickRage/releases/tag/2016.05.20-1
Database Version: 43.1
```
```
2016-05-21 14:11:12 DEBUG TORNADO :: Failed doing webui request "": Traceback (most recent call last): AA AAAttributeError: 'Home' object has no attribute '[object HTMLInputElement]/home/getManualSearchStatus' AA method = getattr(self, _route) AA File "/volume5/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 252, in get 2016-05-21 14:10:42 DEBUG TORNADO :: Failed doing webui request "": Traceback (most recent call last): AA AAAttributeError: 'Home' object has no attribute '[object HTMLInputElement]/home/getManualSearchStatus' AA method = getattr(self, _route) AA File "/volume5/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 252, in get
```
Yes this is from the Repo that you are looking after i can send you logs and show you if you do not believe me.

And after the new update the errors are still there. Like i trying to tell @neoatomic before he was so rude and did not bother to respond to the other message i posted.

I am testing out other Repos on my Dev setup for sport so i do not know why he is so picky when i ask for help on there forms.

Since this is an issue with your master i am asking for help here. To see what is wrong if you want an screenshot to prove it i can show you.

I think it is disgusting that @neoatomic does not want to even hear people out and wants to control everything. 

Thanks

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
`I think it is disgusting that * does not want to even hear people out and wants to control everything.`

I think it is disgusting you think we owe you something.

**Comment by p0psicles** [comment]
@Vodka2014 https://guides.github.com/activities/forking/
Good luck!

**Comment by miigotu** [comment]
lol @p0psicles ill be using that link from now on, awesome.
