### ISSUE TITLE
[APP SUBMITTED]: [Error 3] The system cannot find the path specified: u'Z:\\TV Shows'

### ISSUE THREAD

**Issue by Eamourinho** [SickRage/SickRage#1852]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@a70d27a14ed62fd54939d5a8e5210e33a76afd97
No Log available with ERRORS:
### ERROR
```
Thread-27 :: [a70d27a] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2291, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "C:\SickRage\sickbeard\processTV.py", line 243, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\sickbeard\processTV.py", line 560, in process_media
    result.result = processor.process()
  File "C:\SickRage\sickbeard\postProcessor.py", line 1027, in process
    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
  File "C:\SickRage\sickbeard\helpers.py", line 1578, in verify_freespace
    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest if ek(os.path.exists, dest) else ek(os.path.dirname, dest)).st_dev:  # pylint: disable=no-member
  File "C:\SickRage\sickrage\helper\encoding.py", line 38, in ek
    result = function(*args, **kwargs)
WindowsError: [Error 3] The system cannot find the path specified: u'Z:\\TV Shows'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Eamourinho** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@a70d27a14ed62fd54939d5a8e5210e33a76afd97
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [a70d27a] Exception generated in thread POSTPROCESSER: error 3 : The system cannot find the path specified
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by neoatomic** [comment]
The `Z:\\TV Shows` path cant be found. Check your settings and permissions etc.
