### ISSUE TITLE
SickRage ReadyNAS 104 not launching

### ISSUE THREAD

**Issue by gxander85** [SickRage/SickRage#1887]
Hi All, I am new here & I have been googling most of today to try find a solution.

SickRage is refusing to run on my ReadyNAS 104.
Today I have uninstalled, reinstalled, rebooted the NAS, Uninstalled & cleaned up folders via SSH.

But nothing I try will get it to load. Port Forwarding is set correct too.

Hope someone can help!

Thank's in advance

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Did you try the below package.?
https://github.com/SickRage/readynas-sickrage/releases

In the past we had more users that struggled with ReadyNAS devices. But none of us are using a ReadyNAS ourselves, so we cant help you much there...
You could try to locate the sickrage.log, maybe there will be some pointers to what go's wrong.

Hopefully @Mhynlo has some time and is willing to help you install the package properly.

**Comment by gxander85** [comment]
Hi, I'd be happy to try a "proper" install. If someone has the time to walk me through it, I'd appreciate it. 
Everything seemed to be working fine last week, then it just stopped. Perhaps it was the NAS firmware update that broke it?

Thanks again!

**Comment by Mhynlo** [comment]
I have seen a few people on the netgear forum with similar issues on different apps. Are you getting any specific error messages when started?
Are you able to run the following command to see the current state of sickrage:
`systemctl status fvapp-sickrage.service`

That should give me an idea what it is getting stuck on.

I found on a different app that it some how removed some of the important files. (Not clear on the details of why...) Installing the app through the download(the app)/upload(through the admin interface) option has been able to help some people on the netgear forum.

I should have time to look into the issue this coming week. (I have not reproduced the issue yet, so it may take some time.)

**Comment by gxander85** [comment]
@Mhynlo Forgive my ignorance. Would that be via an SSH terminal screen? I'm quite a novice when it comes to this stuff on my NAS. I have been so used to just installing the app and it running. I transitioned from SickBeard to SickRage. Mainly because it suited my requirements better. The app is "on" but refuses to launch.

If I execute that command in SSH, it should give me what you need right?

I'll have a go at that tonight after work :)

**Comment by miigotu** [comment]
@gxander85 did you check other ports? 8081 is SickRages default, but the package specifies another

**Comment by gxander85** [comment]
@miigotu I'm positive it's 8081 as that is what I am redirected to when I click "launch" on the ReadyNAS.

**Comment by miigotu** [comment]
If the port was changed ready-made would still open tge page with 8081 and you would see nothing, it would look like its broken. Same would happen with toggling HTTPS .

Check the port in the config.ini

**Comment by gxander85** [comment]
@miigotu this is from the config.xml file (could not find .ini)?

`<Application resource-id="sickrage">
  <Name>SickRage</Name>
  <Author>Mhynlo</Author>
  <Version>2016.03.28-2</Version>
  <RequireReboot>0</RequireReboot>
  <ConfigURL/>
  <LaunchURL>http://localhost:8081/</LaunchURL>
  <ReservePort>8081</ReservePort>
  <InfoURL>https://sickrage.github.io/</InfoURL>
  <DebianPackage>sickrage</DebianPackage>
  <ServiceName>fvapp-sickrage.service</ServiceName>
  <Description lang="en-us">Automatic Video Library Manager for TV Shows.</Description>
</Application>
`

**Comment by miigotu** [comment]
config.xml is the file used by the readynas-ui, not the file used by SR.

**Comment by gxander85** [comment]
@Mhynlo here is the result from the command you gave me

`fvapp-sickrage.service - Service for sickrage app
          Loaded: loaded (/lib/systemd/system/fvapp-sickrage.service; enabled)
          Active: active (running) since Tue, 31 May 2016 06:43:55 +1000; 16h ago
         Process: 1640 ExecStart=/usr/bin/python /apps/sickrage/SickBeard.py -q --daemon --nolaunch --datadir=/apps/s                                                                      ickrage/app-config --config=/apps/sickrage/app-config/config.ini --pidfile=/var/run/sickrage.pid (code=exited, status                                                                      =0/SUCCESS)
        Main PID: 2035 (python)
          CGroup: name=systemd:/system/fvapp-sickrage.service
                  └ 2035 /usr/bin/python /apps/sickrage/SickBeard.py -q --daemon --nolaunch --datadir=/apps/sick...
`

**Comment by gxander85** [comment]
Okay, so this is really REALLY strange. It is just working again...
I performed another NAS reboot this morning prior to work & now it runs....

In saying that, is there anything I should/can do to improve its stability? THANKS!

**Comment by gxander85** [comment]
@miigotu for future reference, where is the config.ini file?
Thank you all for your assistance so far, I am slowly learning :)

**Comment by Mhynlo** [comment]
@gxander85 the ini file is located here:
`/apps/sickrage/app-config/config.ini`
The systemctl output; is that from when the unit was working? (It looks like it is working based on that output.)

The configuration should be fairly default and there was no conflict from other readynas apps.

**Comment by gxander85** [comment]
@Mhynlo yeah, that is from when it was working. I ran it, posted it, then realised it was back up again... /sigh/

**Comment by gxander85** [comment]
@Mhynlo update, now I cannot access it again.
Checked the config file "web_port = 8081"
Ran that code again & got this. Could too many TV shows make it fail?

fvapp-sickrage.service - Service for sickrage app
          Loaded: loaded (/lib/systemd/system/fvapp-sickrage.service; enabled)
          Active: activating (start) since Wed, 01 Jun 2016 18:23:38 +1000; 3s ago
        Main PID: 5199 (code=killed, signal=KILL); Control: 15992 (python)
          CGroup: name=systemd:/system/fvapp-sickrage.service
                  └ 15992 /usr/bin/python /apps/sickrage/SickBeard.py -q --daemon --nolaunch --datadir=/apps/sickrage/app-config --config=/apps/sickrage/app-config/config.ini --pidfile=/var/run/sickrage.pid

**Comment by gxander85** [comment]
Here is a snip of the log file from where it failed at about Midday to when I rebooted it just before

`2016-06-01 18:57:43 INFO     DAILYSEARCHER :: New episode Person of Interest - S05E10 - The Day the World Went Away airs today, setting to default episode status for this show: Wanted
2016-06-01 18:57:41 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2016-06-01 18:52:41 INFO     POSTPROCESSER :: Successfully processed
2016-06-01 18:52:41 INFO     POSTPROCESSER :: PostProcessing Path: /JARVIS/Downloads/TV
2016-06-01 18:47:44 INFO     CHECKVERSION :: Checking for updates using SOURCE
2016-06-01 18:47:44 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2016-06-01 18:47:44 INFO     MAIN :: Starting SickRage [master] using '/apps/sickrage/app-config/config.ini'
2016-06-01 18:47:43 INFO     MAIN :: 78912: Unable to find IMDb show info in the database
2016-06-01 18:47:43 INFO     MAIN :: 81328: Unable to find IMDb show info in the database
2016-06-01 18:47:40 INFO     MAIN :: Writing PID: 2888 to /var/run/sickrage.pid
2016-06-01 18:46:59 INFO     EVENT-QUEUE :: Shutting down Tornado
2016-06-01 18:46:58 INFO     EVENT-QUEUE :: Saving config file to disk
2016-06-01 18:46:57 INFO     EVENT-QUEUE :: Saving all shows to the database
2016-06-01 18:46:57 INFO     EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2016-06-01 18:46:57 INFO     EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2016-06-01 18:46:57 INFO     EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2016-06-01 18:46:57 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2016-06-01 18:46:57 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSER thread to exit
2016-06-01 18:46:57 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE thread to exit
2016-06-01 18:46:57 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE thread to exit
2016-06-01 18:46:57 INFO     EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2016-06-01 18:46:57 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2016-06-01 18:46:57 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2016-06-01 18:46:57 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2016-06-01 18:46:57 INFO     EVENT-QUEUE :: Aborting all threads
2016-06-01 18:46:56 INFO     MAIN :: Signal 15 caught, saving and exiting...
AANone
2016-06-01 18:46:37 ERROR    Thread-13 :: [ffcea54] Missing time zone for network: www.purepwnage.com
2016-06-01 18:45:28 INFO     CHECKVERSION :: Checking for updates using SOURCE
2016-06-01 18:45:28 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2016-06-01 18:45:27 INFO     MAIN :: Starting SickRage [master] using '/apps/sickrage/app-config/config.ini'
2016-06-01 18:45:27 INFO     MAIN :: 78912: Unable to find IMDb show info in the database
2016-06-01 18:45:26 INFO     MAIN :: 81328: Unable to find IMDb show info in the database
2016-06-01 18:45:25 INFO     MAIN :: Writing PID: 2012 to /var/run/sickrage.pid
2016-06-01 12:06:25 INFO     SHOWQUEUE-ADD :: theTVDB: {'useZip': True, 'apikey': 'F9C450E78D99172E', 'cache': u'/apps/sickrage/app-config/cache/indexers/theTVDB', 'language': 'en'}
2016-06-01 12:06:25 INFO     SHOWQUEUE-ADD :: Starting to add show by ShowDir: /JARVIS/TV/The Simpsons
2016-06-01 12:05:59 INFO     SHOWQUEUE-ADD :: Done cache check
2016-06-01 12:05:31 INFO     SHOWQUEUE-ADD :: 289096: Updating NFOs for show with new indexer info
2016-06-01 12:05:30 INFO     SHOWQUEUE-ADD :: Launching backlog for this show since its episodes are WANTED
2016-06-01 12:01:32 INFO     DAILYSEARCHER :: No new released episodes found ...
2016-06-01 12:01:27 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2016-06-01 11:37:29 INFO     SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
2016-06-01 11:37:14 INFO     SHOWQUEUE-ADD :: 289096: Unable to find the show in the database
2016-06-01 11:35:55 INFO     SHOWQUEUE-ADD :: theTVDB: {'useZip': True, 'apikey': 'F9C450E78D99172E', 'cache': u'/apps/sickrage/app-config/cache/indexers/theTVDB', 'language': 'en'}
2016-06-01 11:35:55 INFO     SHOWQUEUE-ADD :: Starting to add show by ShowDir: /JARVIS/TV/The Shannara Chronicles
2016-06-01 11:24:36 INFO     SHOWQUEUE-ADD :: Done cache check
2016-06-01 11:22:58 INFO     SHOWQUEUE-ADD :: 74608: Updating NFOs for show with new indexer info
2016-06-01 11:22:35 INFO     SHOWQUEUE-ADD :: Launching backlog for this show since its episodes are WANTED
2016-06-01 11:21:26 INFO     DAILYSEARCHER :: No new released episodes found ...
2016-06-01 11:21:26 INFO     DAILYSEARCHER :: Searching for new released episodes ...`

**Comment by gxander85** [comment]
Furthermore, I found this when I checked the log again. Perhaps there is an error in the post-processor?

AATypeError: coercing to Unicode: need string or buffer, long found
AA    diskfree += ek(os.path.getsize, f.location)
AA  File "/apps/sickrage/sickbeard/helpers.py", line 1617, in verify_freespace
AA    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps):  # pylint: disable=protected-access
AA  File "/apps/sickrage/sickbeard/postProcessor.py", line 1040, in process
AA    result.result = processor.process()
AA  File "/apps/sickrage/sickbeard/processTV.py", line 572, in process_media
AA    process_media(path, [video], nzbName, process_method, force, is_priority, result)
AA  File "/apps/sickrage/sickbeard/processTV.py", line 247, in processDir
AA    ret = func(*args, **kargs)
AA  File "/apps/sickrage/sickbeard/processTV.py", line 154, in func_wrapper
AA    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)
AA  File "/apps/sickrage/sickbeard/auto_postprocessor.py", line 56, in run
AA    self.action.run(self.force)
AA  File "/apps/sickrage/sickbeard/scheduler.py", line 106, in run
AATraceback (most recent call last):
2016-06-01 21:02:13 ERROR    POSTPROCESSER :: [ffcea54] Exception generated in thread POSTPROCESSER: coercing to Unicode: need string or buffer, long found

**Comment by miigotu** [comment]
get it started and update it.

**Comment by gxander85** [comment]
@miigotu i have just succesfully got it started and updated. My post processor is working again. Before the updated, the server status page stated that I only had 400mb of free space. I actually have over 400gb. It is almost like the GB was being recognized as MB.

Long story short, it seems to be working fine again. I have gone through all my settings start to finish. Got them all set, ran a backup so everything is saved.

I think my NAS FW updated broke everything. I will keep this in mind for next time...

Thank you all again for your help. I think it is okay now :)

**Comment by gxander85** [comment]
Hi All, I am re-opening this as I just rebuilt my NAS & switching to XRAID for 4x4TB drives.
I initially had SickRage working from the initial restore to factory, but since then it has stopped again. Below is the code from checking the status of the app. I have uninstalled, reinstalled, rebooted, all the different things I tried previously. I even tried an older verison, & current version via direct upload of the .deb file. Still, no luck. Any assistance (again) is greatly appreciated.

`Last login: Wed Jun 22 13:26:55 2016 from brix
root@JARVIS:~# systemctl status fvapp-sickrage.service
fvapp-sickrage.service - Service for sickrage app
          Loaded: loaded (/lib/systemd/system/fvapp-sickrage.service; disabled)
          Active: activating (start) since Wed, 22 Jun 2016 13:27:44 +1000; 44s ago
         Control: 8131 (python)
          CGroup: name=systemd:/system/fvapp-sickrage.service
                  + 8131 /usr/bin/python /apps/sickrage/SickBeard.py -q --daemon --nolaunch --datadir=/apps/sickrage/app-config --config=/apps/sickrage/app...`

**Comment by Mhynlo** [comment]
After the factory default the drives normally sync. Did the drives finish syncing?
(The sync can be very cpu intense on those 104s and apps may misbehave during that sync.)

**Comment by gxander85** [comment]
Hi @Mhynlo, the resync completed late last night. Nothing is running on it but AntiVirus, SickRage, Transmission & moving more data back onto it. Come to think of it, I only just recently added AntiVirus, could that be causing issues? Transmission is still working fine.

**Comment by miigotu** [comment]
check the port in /apps/sickrage/app-config/config.ini

**Comment by gxander85** [comment]
@miigotu port is 8081. One of the first things I checked. All port forwarding is set correctly on my router too.

**Comment by gxander85** [comment]
Commenting on this again as it's not working. Well, it was running on the NAS but could not log into the GUI to check/edit etc. I've been trawling the web and found this post. Hope someone can help, thanks,
