### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/mnt/synology_video/torrents/complete/The.Night.Manager.S01E05.BRRip.x264-FUM[ettv]/The.Night.Manager.S01E05.BRRip.x264-FUM[ettv].mp4'

### ISSUE THREAD

**Issue by MickHussey** [SickRage/SickRage#1916]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-4.1.19+-armv6l-with-debian-7.10**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@946f6be31a26c661a5e0903c5d66e4ce348ce19d
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [946f6be] Failed doing webui callback: Traceback (most recent call last):
  File "/home/pi/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/home/pi/SickRage/sickbeard/webserve.py", line 2291, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "/home/pi/SickRage/sickbeard/processTV.py", line 290, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/home/pi/SickRage/sickbeard/processTV.py", line 560, in process_media
    result.result = processor.process()
  File "/home/pi/SickRage/sickbeard/postProcessor.py", line 982, in process
    existing_file_status = self._checkForExistingFile(ep_obj.location)
  File "/home/pi/SickRage/sickbeard/postProcessor.py", line 135, in _checkForExistingFile
    if ek(os.path.getsize, existing_file) > ek(os.path.getsize, self.file_path):
  File "/home/pi/SickRage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/mnt/synology_video/torrents/complete/The.Night.Manager.S01E05.BRRip.x264-FUM[ettv]/The.Night.Manager.S01E05.BRRip.x264-FUM[ettv].mp4'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
