### ISSUE TITLE
Test Connection Broken 

### ISSUE THREAD

**Issue by swetoast** [SickRage/SickRage#1920]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Asustor (2.6.1 R5H1)
What you did: Entered data for transmission settings pushed test connection
What happened: Error message
What you expected: N/A
Logs:
``
2016-06-06 12:36:22 Thread-13 :: [946f6be] Failed doing webui callback: Traceback (most recent call last): File "/volume1/.@plugins/AppCentral/entware-ng/opt/bin/SickRage/sickbeard/webserve.py", line 270, in async_call result = function(**kwargs) File "/volume1/.@plugins/AppCentral/entware-ng/opt/bin/SickRage/sickbeard/webserve.py", line 800, in testTorrent result_, accesMsg = client(host, username, password).testAuthentication() File "/volume1/.@plugins/AppCentral/entware-ng/opt/bin/SickRage/sickbeard/clients/generic.py", line 274, in testAuthentication helpers.handle_requests_exception(error) File "/volume1/.@plugins/AppCentral/entware-ng/opt/bin/SickRage/sickbeard/helpers.py", line 1453, in handle_requests_exception if error.response.status_code == 404 and \ AttributeError: 'NoneType' object has no attribute 'status_code'  2016-06-06 12:36:21 Thread-14 :: [946f6be] Failed doing webui callback: Traceback (most recent call last): File "/volume1/.@plugins/AppCentral/entware-ng/opt/bin/SickRage/sickbeard/webserve.py", line 270, in async_call result = function(**kwargs) File "/volume1/.@plugins/AppCentral/entware-ng/opt/bin/SickRage/sickbeard/webserve.py", line 800, in testTorrent result_, accesMsg = client(host, username, password).testAuthentication() File "/volume1/.@plugins/AppCentral/entware-ng/opt/bin/SickRage/sickbeard/clients/generic.py", line 274, in testAuthentication helpers.handle_requests_exception(error) File "/volume1/.@plugins/AppCentral/entware-ng/opt/bin/SickRage/sickbeard/helpers.py", line 1453, in handle_requests_exception if error.response.status_code == 404 and \ AttributeError: 'NoneType' object has no attribute 'status_code'
``

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
I dont have transmission setup, so cant test it here. But the errors shows a 404 error, so site/transmission is not found.
Is it just the test button that doesn't work, or also the sending of torrents to transmission.?

Also are you using http/https.? And did it work before/till when.?

**Comment by swetoast** [comment]
Using http for transmission and HTTS  for sickrage

and yes im 100% certain that the adress is right cause i can access it thru chrome if i use the internal lan ip.

**Comment by swetoast** [comment]
k i did one thing i flushed iptables with 

iptables -F

then added my password

Success: Connected and Authenticated

still there was no rules prohibiting sickrage from checking itself in iptables

**Comment by sebiiiii** [comment]
Thanks swetoast, same issue and a flush worked.
