### ISSUE TITLE
API Error in clients when show is 4k/UHD

### ISSUE THREAD

**Issue by shapetheLOLa** [SickRage/SickRage#1923]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master / 946f6be31a26c661a5e0903c5d66e4ce348ce19d
OS: Ubuntu
What you did: Load a TV Show within nzb360 or nzbmanager on Android
What happened: It wont load any info and sometimes the client crashes
What you expected: It should load the information :)

This just happens on shows where a UHD/4k quality is set. So it could be a custom quality where 4k/uhd is included or just 4k. 720p and 1080p Shows qualities arent affected by this.

In the log the first 2 shows I open are 720p or 1080p. The third one is a custom quality with also 4k.

Logs:

```
2016-06-06 19:30:12 DEBUG    TORNADO :: API :: 10.0.1.21 - gave correct API KEY. ACCESS GRANTED
2016-06-06 19:30:12 DEBUG    TORNADO :: API :: all args: '()'
2016-06-06 19:30:12 DEBUG    TORNADO :: API :: all kwargs: '{'sort': 'date', 'cmd': 'future'}'
2016-06-06 19:30:12 DEBUG    TORNADO :: API :: future: cur_kwargs {'sort': 'date'}
2016-06-06 19:30:15 DEBUG    TORNADO :: API :: 10.0.1.21 - gave correct API KEY. ACCESS GRANTED
2016-06-06 19:30:15 DEBUG    TORNADO :: API :: all args: '()'
2016-06-06 19:30:15 DEBUG    TORNADO :: API :: all kwargs: '{'cmd': 'show', 'tvdbid': '272644'}'
2016-06-06 19:30:15 DEBUG    TORNADO :: API :: show: cur_kwargs {'tvdbid': '272644'}
2016-06-06 19:30:15 DEBUG    TORNADO :: Found indexer mapping in cache for show: 12 Monkeys
2016-06-06 19:30:15 DEBUG    TORNADO :: API :: 10.0.1.21 - gave correct API KEY. ACCESS GRANTED
2016-06-06 19:30:15 DEBUG    TORNADO :: API :: all args: '()'
2016-06-06 19:30:15 DEBUG    TORNADO :: API :: all kwargs: '{'cmd': 'show.seasons', 'tvdbid': '272644'}'
2016-06-06 19:30:15 DEBUG    TORNADO :: API :: show.seasons: cur_kwargs {'tvdbid': '272644'}
2016-06-06 19:30:17 DEBUG    TORNADO :: API :: 10.0.1.21 - gave correct API KEY. ACCESS GRANTED
2016-06-06 19:30:17 DEBUG    TORNADO :: API :: all args: '()'
2016-06-06 19:30:17 DEBUG    TORNADO :: API :: all kwargs: '{'sort': 'date', 'cmd': 'future'}'
2016-06-06 19:30:17 DEBUG    TORNADO :: API :: future: cur_kwargs {'sort': 'date'}
2016-06-06 19:30:18 DEBUG    TORNADO :: API :: 10.0.1.21 - gave correct API KEY. ACCESS GRANTED
2016-06-06 19:30:18 DEBUG    TORNADO :: API :: all args: '()'
2016-06-06 19:30:18 DEBUG    TORNADO :: API :: all kwargs: '{'cmd': 'show', 'tvdbid': '248741'}'
2016-06-06 19:30:18 DEBUG    TORNADO :: API :: show: cur_kwargs {'tvdbid': '248741'}
2016-06-06 19:30:18 ERROR    TORNADO :: [946f6be] API :: error 512
Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webapi.py", line 136, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/opt/sickrage/sickbeard/webapi.py", line 204, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "/opt/sickrage/sickbeard/webapi.py", line 1898, in run
    any_qualities, best_qualities = _map_quality(show_obj.quality)
  File "/opt/sickrage/sickbeard/webapi.py", line 544, in _map_quality
    any_qualities.append(quality_map[quality])
KeyError: 512
2016-06-06 19:30:18 DEBUG    TORNADO :: API :: 10.0.1.21 - gave correct API KEY. ACCESS GRANTED
2016-06-06 19:30:18 DEBUG    TORNADO :: API :: all args: '()'
2016-06-06 19:30:18 DEBUG    TORNADO :: API :: all kwargs: '{'cmd': 'show.seasons', 'tvdbid': '248741'}'
2016-06-06 19:30:18 DEBUG    TORNADO :: API :: show.seasons: cur_kwargs {'tvdbid': '248741'}
```

Regards,
Jan

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
