### ISSUE TITLE
[APP SUBMITTED]: timed out

### ISSUE THREAD

**Issue by WGSLLC** [SickRage/SickRage#1935]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@946f6be31a26c661a5e0903c5d66e4ce348ce19d
No Log available with ERRORS:
### ERROR
```
Thread-167 :: [946f6be] Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\logger.py", line 366, in submit_errors
    for report in reports:
  File "C:\SickRage\SickRage\lib\github\PaginatedList.py", line 48, in __iter__
    newElements = self._grow()
  File "C:\SickRage\SickRage\lib\github\PaginatedList.py", line 60, in _grow
    newElements = self._fetchNextPage()
  File "C:\SickRage\SickRage\lib\github\PaginatedList.py", line 161, in _fetchNextPage
    headers=self.__headers
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 275, in __requestRaw
    requestHeaders
  File "C:\SickRage\Python\lib\httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "C:\SickRage\Python\lib\httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "C:\SickRage\Python\lib\httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "C:\SickRage\Python\lib\httplib.py", line 893, in _send_output
    self.send(msg)
  File "C:\SickRage\Python\lib\httplib.py", line 855, in send
    self.connect()
  File "C:\SickRage\Python\lib\httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "C:\SickRage\Python\lib\httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "C:\SickRage\Python\lib\socket.py", line 575, in create_connection
    raise err
timeout: timed out

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by gvtters** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@946f6be31a26c661a5e0903c5d66e4ce348ce19d
No Log available with ERRORS:
### ERROR
```
Thread-20 :: [946f6be] Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\logger.py", line 366, in submit_errors
    for report in reports:
  File "C:\SickRage\SickRage\lib\github\PaginatedList.py", line 48, in __iter__
    newElements = self._grow()
  File "C:\SickRage\SickRage\lib\github\PaginatedList.py", line 60, in _grow
    newElements = self._fetchNextPage()
  File "C:\SickRage\SickRage\lib\github\PaginatedList.py", line 161, in _fetchNextPage
    headers=self.__headers
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 275, in __requestRaw
    requestHeaders
  File "C:\SickRage\Python\lib\httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "C:\SickRage\Python\lib\httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "C:\SickRage\Python\lib\httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "C:\SickRage\Python\lib\httplib.py", line 893, in _send_output
    self.send(msg)
  File "C:\SickRage\Python\lib\httplib.py", line 855, in send
    self.connect()
  File "C:\SickRage\Python\lib\httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "C:\SickRage\Python\lib\httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "C:\SickRage\Python\lib\socket.py", line 575, in create_connection
    raise err
timeout: timed out

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Grantp1962** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@21c9621a36dabe345fc4879200c3fba39b84c8ce
No Log available with ERRORS:
### ERROR
```
Thread-19 :: [21c9621] Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/logger.py", line 366, in submit_errors
    for report in reports:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/PaginatedList.py", line 48, in __iter__
    newElements = self._grow()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/PaginatedList.py", line 60, in _grow
    newElements = self._fetchNextPage()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/PaginatedList.py", line 161, in _fetchNextPage
    headers=self.__headers
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 275, in __requestRaw
    requestHeaders
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 1204, in connect
    HTTPConnection.connect(self)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/socket.py", line 571, in create_connection
    raise err
timeout: timed out

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by digitalgp** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@d15b7003f8663b76d01fcbf0566389b2f31e0564
No Log available with ERRORS:
### ERROR
```
Thread-23 :: [d15b700] Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\logger.py", line 367, in submit_errors
    for report in reports:
  File "C:\SickRage\SickRage\lib\github\PaginatedList.py", line 48, in __iter__
    newElements = self._grow()
  File "C:\SickRage\SickRage\lib\github\PaginatedList.py", line 60, in _grow
    newElements = self._fetchNextPage()
  File "C:\SickRage\SickRage\lib\github\PaginatedList.py", line 161, in _fetchNextPage
    headers=self.__headers
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 275, in __requestRaw
    requestHeaders
  File "C:\SickRage\Python\lib\httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "C:\SickRage\Python\lib\httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "C:\SickRage\Python\lib\httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "C:\SickRage\Python\lib\httplib.py", line 893, in _send_output
    self.send(msg)
  File "C:\SickRage\Python\lib\httplib.py", line 855, in send
    self.connect()
  File "C:\SickRage\Python\lib\httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "C:\SickRage\Python\lib\httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "C:\SickRage\Python\lib\socket.py", line 575, in create_connection
    raise err
timeout: timed out

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mitch71h** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@b3da866cadff70973fabdbb3ffbe8ad0dd208c49
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [b3da866] Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\logger.py", line 369, in submit_errors
    repo = sickbeard.gh.get_organization(sickbeard.GIT_ORG).get_repo(sickbeard.GIT_REPO)
  File "C:\SickChill\SickChill\lib\github\MainClass.py", line 198, in get_organization
    "/orgs/" + login
  File "C:\SickChill\SickChill\lib\github\Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickChill\SickChill\lib\github\Requester.py", line 215, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\SickChill\SickChill\lib\github\Requester.py", line 268, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\SickChill\SickChill\lib\github\Requester.py", line 293, in __requestRaw
    requestHeaders
  File "C:\SickChill\Python\lib\httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "C:\SickChill\Python\lib\httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "C:\SickChill\Python\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "C:\SickChill\Python\lib\httplib.py", line 882, in _send_output
    self.send(msg)
  File "C:\SickChill\Python\lib\httplib.py", line 844, in send
    self.connect()
  File "C:\SickChill\Python\lib\httplib.py", line 1255, in connect
    HTTPConnection.connect(self)
  File "C:\SickChill\Python\lib\httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "C:\SickChill\Python\lib\socket.py", line 575, in create_connection
    raise err
timeout: timed out

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
