### ISSUE TITLE
[SpeedCD] Exception while searching Speedcd. Error: AttributeError("'NoneType' object has no attribute 'find'",)

### ISSUE THREAD

**Issue by hobojoe720** [SickRage/SickRage#1952]
Branch/Commit: master
OS: Synology
What you did: Added Speed.CD as a torrent provider
What happened: An error was generated
What you expected: A torrent to be downloaded
I have added Speed.CD as TorrentDay no longer works.
Logs:
```
2016-06-12 11:48:29 INFO     SEARCHQUEUE-MANUAL-76808 :: Unable to find a download for: [Whose Line Is It Anyway - S12E03 - Karla Souza]
2016-06-12 11:48:29 DEBUG    SEARCHQUEUE-MANUAL-76808 :: formatting pattern: %SN - S%0SE%0E - %EN -> Whose Line Is It Anyway - S12E03 - Karla Souza
2016-06-12 11:48:29 DEBUG    SEARCHQUEUE-MANUAL-76808 :: formatting pattern: %SN - S%0SE%0E - %EN -> Whose Line Is It Anyway - S12E03 - Karla Souza
AA
AAAttributeError: 'NoneType' object has no attribute 'find'
AA    torrent_table = html.find('div', class_='boxContent').find('table')
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/speedcd.py", line 133, in search
AA    items_list += self.search(search_string, ep_obj=episode)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickrage/providers/GenericProvider.py", line 145, in find_search_results
AA    searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 489, in searchProviders
2016-06-12 11:48:29 DEBUG    SEARCHQUEUE-MANUAL-76808 :: [Speedcd] :: Traceback (most recent call last):
AAAttributeError: 'NoneType' object has no attribute 'find'
AA    torrent_table = html.find('div', class_='boxContent').find('table')
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/speedcd.py", line 133, in search
AA    items_list += self.search(search_string, ep_obj=episode)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickrage/providers/GenericProvider.py", line 145, in find_search_results
AA    searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 489, in searchProviders
AATraceback (most recent call last):
2016-06-12 11:48:29 ERROR    SEARCHQUEUE-MANUAL-76808 :: [Speedcd] :: [946f6be] Exception while searching Speedcd. Error: AttributeError("'NoneType' object has no attribute 'find'",)
2016-06-12 11:48:29 DEBUG    SEARCHQUEUE-MANUAL-76808 :: [Speedcd] :: GET URL: https://speed.cd/login.php [Status: 200]
2016-06-12 11:48:29 DEBUG    SEARCHQUEUE-MANUAL-76808 :: [Speedcd] :: GET URL: https://speed.cd/browse.php?c55=1&c52=1&search=Whose+Line+is+it+Anyway+US+S12E03&c41=1&c50=1&c2=1&c30=1&c49=1 [Status: 302]
2016-06-12 11:48:29 DEBUG    SEARCHQUEUE-MANUAL-76808 :: [Speedcd] :: Search string: Whose Line is it Anyway US S12E03
2016-06-12 11:48:29 DEBUG    SEARCHQUEUE-MANUAL-76808 :: [Speedcd] :: Search Mode: Episode
2016-06-12 11:48:29 INFO     SEARCHQUEUE-MANUAL-76808 :: [Speedcd] :: Performing episode search for Whose Line Is It Anyway?```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by hobojoe720** [comment]
I have checked and there is a fix that was added to develop, but this was for a different issue. This issue still persists.

**Comment by boboduhobo** [comment]
I did some investigation hoping it was an easy fix, what I found is that it seems to be javascript related. I have to go out of town so I'm putting what I found so far here. The issue happens in the [with BS4Parser(data, 'html5lib') block](https://github.com/SickRage/SickRage/blob/master/sickbeard/providers/speedcd.py#L132)

First, I did some checking of types when running a speed.cd backlog search. To see what part was the NonType, I added the following lines before the erroring line 133:
```
# This checks the BS4Parser(html, data) call in the with-block
testtype = type(html)
print "html (BS4Parser)",testtype

# This checks the find in that same line, which is used to find the table of torrents
testtype = type(html.find('div', class_='boxContent'))
print "html.find('div', class_='boxContent')",testtype

# This was to verify that there is no boxContent, 
# it is printing all the divs from the html and their attributes
for testtag in html.find_all('div'):
    print testtag.attrs
```
The relevant Log from that is here:
```
08:20:04 INFO::SEARCHQUEUE-BACKLOG-275120 :: Beginning backlog search for: [Bordertown (2016)]
html (BS4Parser) <class 'bs4.BeautifulSoup'>
html.find('div', class_='boxContent') <type 'NoneType'>
{u'id': u'maincontain'}
{u'class': [u'shade'], u'id': u'logintab'}
{u'id': u'logo'}
{u'class': [u'loginWarp']}
{u'data-theme': u'dark', u'data-callback': u'verify', u'class': [u'g-recaptcha'], u'data-sitekey': u'6LdEuCETAAAAAPX9BY9Wi-QBhCoP2wv7R6taDnLK'}
{u'id': u'foot'}
{u'style': u'vertical-align: middle; padding-left:20px;', u'class': [u'mil']}
{u'id': u'mil', u'class': [u'mil']}
08:20:06 INFO::SEARCHQUEUE-BACKLOG-275120 :: [Speedcd] :: Performing episode search for Bordertown (2016)
html (BS4Parser) <class 'bs4.BeautifulSoup'>
html.find('div', class_='boxContent') <type 'NoneType'>
{u'id': u'maincontain'}
{u'class': [u'shade'], u'id': u'logintab'}
{u'id': u'logo'}
{u'class': [u'loginWarp']}
{u'data-theme': u'dark', u'data-callback': u'verify', u'class': [u'g-recaptcha'], u'data-sitekey': u'6LdEuCETAAAAAPX9BY9Wi-QBhCoP2wv7R6taDnLK'}
{u'id': u'foot'}
{u'style': u'vertical-align: middle; padding-left:20px;', u'class': [u'mil']}
{u'id': u'mil', u'class': [u'mil']}
08:20:06 ERROR::SEARCHQUEUE-BACKLOG-275120 :: [Speedcd] :: Exception while searching Speedcd. Error: AttributeError("'NoneType' object has no attribute 'find'",)
```
This led me back to the actual data the html is parsing. I wanted to take a look at what it gets back from speed.cd so I added the following before the with-block which contains the error (so at line 131 insterted this):
```
testf = open("dataexcerpt.txt", "w")
testf.write( str(data) )
testf.close()
```
That gives me the HTML it is getting from speed.cd. And in that HTML, there is no search results from the browse.php call, which is why it can't find the div with class "boxContent" which is there if you were to replicate the browse.php call in your browser. I think the issue is speed.cd uses javascript to pull in the torrent table.
```
dataexcerpt.txt
-------------------
<!doctype html>

<html xml:lang="en" lang="en">

	<head>

        <meta http-equiv='Content-Type' content='text/html; charset=utf-8' />

		<meta name="apple-mobile-web-app-capable" content="yes">

		<meta name="apple-mobile-web-app-status-bar-style" content="black">

		<meta name="viewport" content="initial-scale=1.0,user-scalable=no;">

		<link rel="apple-touch-icon" sizes="152x152" href="/V3/img/iFavicon.png">

        <link rel="shortcut icon" href="/favicon.ico">

        <link rel="stylesheet" href="/rsrc/css/com/etc/login.css?" type="text/css">

        <title>SPEED.CD :: You're home now!</title>

    </head>

    <body>

		<noscript>

            <div class="notification error png_bg">

                <div>

                    Javascript is disabled or is not supported by your browser. Please <a href="http://browsehappy.com/" title="Upgrade to a better browser">upgrade</a> your browser or <a href="http://www.google.com/support/bin/answer.py?answer=23852" title="Enable Javascript in your browser">enable</a> Javascript to navigate the interface properly.

                </div>

            </div>

		</noscript><img src="/V3/img/.gif" id="bg" style="background:no-repeat 50%/cover #F2A41E;" />    			<div id='maincontain'>

			<div id='logintab' class='shade'>

				<div id="logo">

					<img src="/V3/img/speed.png?" style="width:48px">

					<img src="/V3/img/speedlogo.png" style="width:118px">

				</div>

				<form method="post" action="takelogin.php" id="loginform">

				<div class="loginWarp">

					<table class="sign">

					   <tr>

							<td align="left"><label for="nick">Username:</label></td>

							<td align="left"><label for="pass">Password:</label><a href="/checkpoint/" style="color:#CCC;margin-left:20px;">Forgot Password?</a></td>

						</tr>

						<tr>

							<td align="left"><input type="text" id="nick" class="uiInput" size="40" name="username" placeholder="Username"></td>

							<td align="left"><input type="password" id="pass" class="uiInput" size="40" name="password" placeholder="Password"></td>

							<td align="left"><div class="g-recaptcha" data-callback=verify data-theme=dark data-sitekey="6LdEuCETAAAAAPX9BY9Wi-QBhCoP2wv7R6taDnLK"></div></td>							</td>

						</tr>

					</table>

				</div>

				</form>

			</div>

        </div>

		<div id='foot'>

			<div class='mil' style="vertical-align: middle; padding-left:20px;">

				<a id="ltab" class="button" href="#" onClick="$.vpbox._();$(this).hide();$('#stab,#logintab,#rtab').show();return false;"><span>Login</span></a>

				<a id="stab" class="button" href="/signup.php" onClick="$.vpbox(sUp.p);$('#stab,#logintab').hide();$('#ltab,#rtab').show();return false;"><span style='color:#F00;font-weight:bold;text-decoration:blink;'>Sign Up</span></a>

				<a id="rtab" class="button" href="/checkpoint"><span>Forgot Password?</span></a>

			</div>

			<div class='mil' id='mil'><a class="button" href="#" onClick="decrypted.g();"><span>Help</span></a></div>

		</div>

	

		<script type="text/javascript" src='/rsrc/js/core/jq.js'></script>

		<script type='text/javascript' src='/rsrc/js/core/engine.js'></script>

		<script type="text/javascript" src='/rsrc/js/extensions/VPbox.js'></script>

		<script type="text/javascript" src='https://www.google.com/recaptcha/api.js?hl=en'></script>

		<script type='text/javascript'>

			var sUp = {

				"p":"<p style='background-color:#F00;color:#FFF;font-weight:bold;text-decoration:blink;margin:0;text-align:center;'><nobr>You will not get a second chance! So think before you Submit.<\/nobr><\/p><div class='shade'>\r\n\t<form method='post' id='jxlin=3&' action='#' onsubmit=\"Engine.API(this.id+$(this).serialize());$('#emailgo').hide();$('.boogie').show();return false;\">\r\n\t\t<table cellpadding='0' border='0' align='center' class='sign'>\r\n\t\t   <tr>\r\n\t\t\t\t<td align='left'><label for='useremail'>Email address:<\/label><\/td>\r\n\t\t\t<\/tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td align='left'><input type='text' name='email' id='useremail' class='uiInput'><\/td>\r\n\t\t\t<\/tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td align='left'><label for='cuz'>Why should we let you in:<\/label><\/td>\r\n\t\t\t<\/tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td align='left'><textarea class='uiInput' id='cuz' style='min-height: 150px; max-width: 290px; min-width: 290px;font-size:12px; width: 290px; height: 150px;color:#666;' onfocus='$(this).hide().next().show().focus();'>Tips:\r\n\r\nWhy do you want to join Speed.cd?\r\nAre you member at other torrent site?\r\nDo you have any ratio proof?\r\n\r\nNOTE: Any application less than 2 lines will be deleted without consideration!<\/textarea><textarea name='reason' class='uiInput' id='cuz' style='display:none;font-size:12px;min-height: 150px; max-width: 290px; min-width: 290px; width: 290px; height: 150px;'><\/textarea><\/td>\r\n\t\t\t<\/tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td align='left'><label for='useremail'>Enter the numbers you see:<\/label><\/td>\r\n\t\t\t<\/tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td align='left'><img class='reload' src='VPsec.php?i=3'><a href='javascript:reload();' title='Request a new picture'><img src='\/pic\/refresh_btn.png' class='reicon'><\/a><\/td>\r\n\t\t\t<\/tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td align='left'><input type='text' id='code' autocomplete='off' name='VPsec' class='uiInput' \/> <\/td>\r\n\t\t\t<\/tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td align='right'><label class='uiButton uiButtoncolor' id='emailgo'><button class='button' type='submit'>Do it!<\/button><\/label><img width='30' border='0' class='boogie' style='display:none;' src='\/pic\/extention\/v3\/boogie.gif'><\/td>\r\n\t\t\t<\/tr>\r\n\t\t<\/table>\r\n\t<\/form>\r\n<\/div>",

				"d":"<p style='background-color:#F00;color:#FFF;font-weight:bold;text-decoration:blink;margin:0;text-align:center;'><nobr>After you completed the donation proccess you will recieve an email by system.<br \/>\r\nso please provide a valid email address. or you won't reiceve the account activation link.<\/nobr><\/p>\r\n<div class='shade'>\r\n\t<form method='post' id='don' action='#'>\r\n\t\t<table cellpadding='0' border='0' align='center' class='sign' style='width:300px;'>\r\n\t\t\t<tr>\r\n\t\t\t\t<td align='left'><label for='useremail'>Email address:<\/label><\/td>\r\n\t\t\t<\/tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td align='left'><input type='text' id='useremail' class='uiInput' size='40' name='donateemail'><\/td>\r\n\t\t\t<\/tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td align='right'><label id='donatego' class='uiButton uiButtoncolor'><button class='button' type='button' id='jxlin=2&' onclick='don(this);'>Do it!<\/button><\/label><img src='\/pic\/extention\/v3\/boogie.gif' border='0' style='display:none;' class='boogie' width='30' \/><\/td>\r\n\t\t\t<\/tr>\r\n\t\t<\/table>\r\n\t<\/form>\r\n<\/div>",

				"e":"<p style='background-color:#F00;color:#FFF;font-weight:bold;text-decoration:blink;margin:0;text-align:center;'><nobr>You will not get a second chance! So think before you Submit.<\/nobr><\/p><div class='shade'>\r\n\t<form method='post' id='jxlin=3&' action='#' onsubmit=\"Engine.API(this.id+$(this).serialize());$('#emailgo').hide();$('.boogie').show();return false;\">\r\n\t\t<table cellpadding='0' border='0' align='center' class='sign'>\r\n\t\t   <tr>\r\n\t\t\t\t<td align='left'><label for='useremail'>Email address:<\/label><\/td>\r\n\t\t\t<\/tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td align='left'><input type='text' name='email' id='useremail' class='uiInput'><\/td>\r\n\t\t\t<\/tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td align='left'><label for='cuz'>Why should we let you in:<\/label><\/td>\r\n\t\t\t<\/tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td align='left'><textarea class='uiInput' id='cuz' style='min-height: 150px; max-width: 290px; min-width: 290px;font-size:12px; width: 290px; height: 150px;color:#666;' onfocus='$(this).hide().next().show().focus();'>Tips:\r\n\r\nWhy do you want to join Speed.cd?\r\nAre you member at other torrent site?\r\nDo you have any ratio proof?\r\n\r\nNOTE: Any application less than 2 lines will be deleted without consideration!<\/textarea><textarea name='reason' class='uiInput' id='cuz' style='display:none;font-size:12px;min-height: 150px; max-width: 290px; min-width: 290px; width: 290px; height: 150px;'><\/textarea><\/td>\r\n\t\t\t<\/tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td align='left'><label for='useremail'>Enter the numbers you see:<\/label><\/td>\r\n\t\t\t<\/tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td align='left'><img class='reload' src='VPsec.php?i=3'><a href='javascript:reload();' title='Request a new picture'><img src='\/pic\/refresh_btn.png' class='reicon'><\/a><\/td>\r\n\t\t\t<\/tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td align='left'><input type='text' id='code' autocomplete='off' name='VPsec' class='uiInput' \/> <\/td>\r\n\t\t\t<\/tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td align='right'><label class='uiButton uiButtoncolor' id='emailgo'><button class='button' type='submit'>Do it!<\/button><\/label><img width='30' border='0' class='boogie' style='display:none;' src='\/pic\/extention\/v3\/boogie.gif'><\/td>\r\n\t\t\t<\/tr>\r\n\t\t<\/table>\r\n\t<\/form>\r\n<\/div>"			},

			verify=function(){

				$('#loginform')[0].submit();

			}

			$(document).ready(function(){

				$('#bg').css({"background-image":'url(//lookpic.com/O/i2/218/tKyQtUEH.jpeg)'});

			});		</script>

		<script type='text/javascript' src='/js/temp/logi.js'></script>

	</body>

</html>
```

**Comment by boboduhobo** [comment]
From what I could tell, SickRage providers currently do not support javascript rendering on the pages scraped. Seems like this is most commonly done with [Selenium](http://www.seleniumhq.org/) and [PhantomJS](http://phantomjs.org/). [Here](http://techstonia.com/scraping-with-phantomjs-and-python.html) is an example of a how-to I found while searching. There are a lot of other "guides" on the subject, but the handful I saw all used selenium and phantomJS.

I don't see a code quality guide anywhere, on what is allowed to be added to the repository. But adding these two tools would make it possible to scrape sites that use javascript (and checks that the browser is running javascript) more effectively (or at all, in this case). Fixing the speed.cd provider is something I'll happily do though, as long as it's possible with the tools available to SickRage.

**Comment by p0psicles** [comment]
IMO selenium is way to heavy to solve an issue like this. If the data is parsed post DOM load. It's still retrieved using a REST/json call. Then we should look into that rest call, and use that. Data still needs to come from somewhere.

**Comment by boboduhobo** [comment]
That's true that the data must be coming from somewhere. I did a bit of searching on speed.cd forums and found a post from their site dev relating to sickrage and other automated means of scraping speed.cd:

> our API was being used without our permission. We upgraded our search engine and browse code to improve search speed and it changed our front end code completely and broke the plugin.

You can grab an RSS feed from speed.cd customized for your account and for a specific set of categories (under RSS). This is going to be my solution to this problem, seen that their dev purposely broke the way speed.cd used to be scraped.

**Comment by hobojoe720** [comment]
RSS is the work around I went with as well. But it is a work around. If the issue cannot be fixed, then Speed.CD as a provider should be removed maybe?

**Comment by neoatomic** [comment]
Indeed, hope when @miigotu has time he can do a quick check. If its possible to fix or that we simply remove Speed.cd and advice users to use the RSS feed.

**Comment by zorvalth** [comment]
I got two instances of sickrage one older (lastly updated a couple months ago) and speed.cd is working there.. The brand new install - sickrage is broken. I updated the old one and it broke speed.cd . Isnt it possible to revert?

**Comment by iLlama** [comment]
Also having this issue with Speed.cd

It was working fine until I installed the latest version today and now I get the same error as above. Has their been any progress?

**Comment by iLlama** [comment]
After latest update, I am no longer getting the errors when searching like before but it is not finding any episodes for shows I verified are there.

**Comment by miigotu** [comment]
https://github.com/SickRage/SickRage/issues/1971#issuecomment-226681693

**Comment by iLlama** [comment]
Not resolved for me at least. I am logged into Speed, went to the site in the comment above, logged in fine, still not finding anything.

**Comment by miigotu** [comment]
then it isnt there? I didnt test if maybe they changed their site again, but they do that often to intentionally break SR parsing.
