### ISSUE TITLE
Error downloading subs

### ISSUE THREAD

**Issue by spot88** [SickRage/SickRage#1962]
Branch/Commit: Master
OS: Ubuntu Server 16.04 LTS
What you did: Added show
What happened: Show got added, get's error when trying to download subs.
What you expected: Subs to get downloaded without errors.
Logs:
```
2016-06-14 10:00:12 FINDSUBTITLES :: Traceback (most recent call last): File "/opt/sickrage/sickbeard/subtitles.py", line 251, in download_subtitles single=not sickbeard.SUBTITLES_MULTI) File "/opt/sickrage/lib/subliminal/core.py", line 693, in save_subtitles with io.open(subtitle_path, 'wb') as f: IOError: [Errno 13] Permission denied: '/media/share-3TB/Chicago P.D/Season 02/Chicago P.D - S02E02 - Get My Cigarettes - 720p HDTV.en.srt'

drwxrwxrwx 4 media media 4096 Jun 14 06:35 Chicago P.D
drwxrwxrwx 2 media media 4096 Jun 14 06:35 Season 01
drwxrwxrwx 2 media media 4096 Jun 14 09:35 Season 02
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by spot88** [comment]
Appends almost regularly to new shows i'm adding: 

2016-06-14 16:35:48 POSTPROCESSER :: Traceback (most recent call last): File "/opt/sickrage/sickbeard/subtitles.py", line 251, in download_subtitles single=not sickbeard.SUBTITLES_MULTI) File "/opt/sickrage/lib/subliminal/core.py", line 693, in save_subtitles with io.open(subtitle_path, 'wb') as f: IOError: [Errno 13] Permission denied: '/media/share-3TB/The Blacklist/Season 02/The Blacklist - S02E11 - Ruslan Denisov - 720p HDTV.en.srt'

**Comment by neoatomic** [comment]
The error is pretty clear. `[Errno 13] Permission denied:` Is sickrage also running as media:media.?
And you say adding a "new show". So no files where present.? aka added an existing show.?

**Comment by spot88** [comment]
@neoatomic Sickrage is running as media.
http://pastebin.com/NCCTQAGw

**Comment by miigotu** [comment]
Fix the permissions of /media/share-3TB/The Blacklist/Season 02

**Comment by meyersbs** [comment]
I just ran into the same issue. SickRage was running under the group `sickrage`, so I ran the following to resolve the issue:

``` bash
    # Add the user 'meyersbs' to the group 'sickrage'
    sudo usermod -a -G sickrage meyersbs # add 'meyersbs' to 'sickrage'
    # Give read and write permissions to the the user and group for '/path/to/media/'.
    # Do this recursively.
    sudo chmod -R ug+rw /path/to/media/
    # Make the user 'meyersbs' the owner of '/path/to/media/' and set the group to
    # 'sickrage'. Do this recursively.
    sudo chown -R meyersbs:sickrage /path/to/media/
```
