### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by oconnellkj** [SickRage/SickRage#1968]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@acf14ec6aec29e10e954efc7bef4dcfe371039f8
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-ADD :: [acf14ec] Error searching dir for episodes: 'NoneType' object has no attribute 'replace'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duramato** [comment]
Will need debug logs to do anything

**Comment by rootwyrm** [comment]
### INFO
Python Version: **2.7.11 (default, Jun 22 2016, 07:25:36) [GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)]**
Operating System: **FreeBSD-10.3-RELEASE-p4-i386-32bit-ELF**
Locale: None
Branch: **develop**
Commit: SickRage/SickRage@bb48594a1ec3ca3024385c2e32dd2c47cdb2ba76
No Log available with ERRORS:
### ERROR
```
AUTO :: [bb48594] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/local/sickrage/sickbeard/webserve.py", line 269, in async_call
    result = function(**kwargs)
  File "/usr/local/sickrage/sickbeard/webserve.py", line 2354, in processEpisode
    t = PageTemplate(rh=self, filename="addShows.mako")
AttributeError: 'NoneType' object has no attribute 'replace'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rootwyrm** [comment]
This is occurring during attempts to run post-processing without queue. Post-processing is also currently completely broken. The exact same issue occurs on master. No additional logs are produced.

**Comment by GBANSE** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@43e87014bcd7515e3cb2e50a185361861aed6800
No Log available with ERRORS:
### ERROR
```
MANUAL :: [43e8701] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2355, in processEpisode
    result = result.replace("\n", "<br>\n")
AttributeError: 'NoneType' object has no attribute 'replace'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SLIMaxPower** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-STABLE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b3dad8eec3e238b1cadc809acf8e0e26deb9eb3
No Log available with ERRORS:
### ERROR
```
MANUAL :: [4b3dad8] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 286, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2433, in processEpisode
    result = result.replace("\n", "<br>\n")
AttributeError: 'NoneType' object has no attribute 'replace'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sharkykh** [comment]
@SLIMaxPower Can you provide debug logs of the post-processing task you performed?
I'm trying to reproduce the issue in order to fix it.

**Comment by SLIMaxPower** [comment]
where do i find the appropriate log file

**Comment by sharkykh** [comment]
In your data dir there's a folder named Logs, in it there are .log files.

**Comment by Garion1122** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
MANUAL :: [10a0c30] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 2442, in processEpisode
    result = result.replace("\n", "<br>\n")
AttributeError: 'NoneType' object has no attribute 'replace'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by PipingR** [comment]
### INFO
Python Version: **2.7.3 (default, Oct 26 2016, 21:01:49) [GCC 4.6.3]**
Operating System: **Linux-3.13.0-67-generic-x86_64-with-Ubuntu-12.04-precise**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
MANUAL :: [10a0c30] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/tretflix/appdata/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/opt/tretflix/appdata/sickrage/sickbeard/webserve.py", line 2442, in processEpisode
    result = result.replace("\n", "<br>\n")
AttributeError: 'NoneType' object has no attribute 'replace'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by dvillaruz** [comment]
### INFO
Python Version: **2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.22-ti-r48-armv7l-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
Link to Log: https://gist.github.com/6d625d94ee323dba8c47f86bc33499c8
### ERROR
```
MANUAL :: [5a9a634] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2498, in processEpisode
    result = result.replace("\n", "<br>\n")
AttributeError: 'NoneType' object has no attribute 'replace'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by skjnldsv** [comment]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]**
Operating System: **Linux-4.17.0-0.bpo.3-amd64-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@30efa255db37af28f62f6c21a86a92e755ea1ff9
Link to Log: https://gist.github.com/c91443520f601a76b18e6eed45aa4aa7
### ERROR
```
MANUAL :: [30efa25] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 2497, in processEpisode
    result = result.replace("\n", "<br>\n")
AttributeError: 'NoneType' object has no attribute 'replace'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by skjnldsv** [comment]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]**
Operating System: **Linux-4.17.0-0.bpo.3-amd64-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@30efa255db37af28f62f6c21a86a92e755ea1ff9
Link to Log: https://gist.github.com/5a2903f545c9e29d083f908103d4eb1c
### ERROR
```
MANUAL :: [30efa25] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 2497, in processEpisode
    result = result.replace("\n", "<br>\n")
AttributeError: 'NoneType' object has no attribute 'replace'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by skjnldsv** [comment]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]**
Operating System: **Linux-4.17.0-0.bpo.3-amd64-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@97cd7bb2ee4cf5ef77eb8d0482655668f66576db
Link to Log: https://gist.github.com/c47210700d61d40854b2c5ff2389904e
### ERROR
```
MANUAL :: [97cd7bb] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 2497, in processEpisode
    result = result.replace("\n", "<br>\n")
AttributeError: 'NoneType' object has no attribute 'replace'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by skjnldsv** [comment]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]**
Operating System: **Linux-4.18.0-0.bpo.1-amd64-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@61e699ea0a706d453437cc5650fdc201e3188d65
Link to Log: https://gist.github.com/a0cdb4ef878190a94035022e599a4a71
### ERROR
```
MANUAL :: [61e699e] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 2499, in processEpisode
    result = result.replace("\n", "<br>\n")
AttributeError: 'NoneType' object has no attribute 'replace'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by skjnldsv** [comment]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]**
Operating System: **Linux-4.18.0-0.bpo.1-amd64-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@c0e676570fbffe964c57e8e089b8cab7b4b2f668
Link to Log: https://gist.github.com/c6f1834fdde3ca607424d75ad379b449
### ERROR
```
MANUAL :: [c0e6765] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 2499, in processEpisode
    result = result.replace("\n", "<br>\n")
AttributeError: 'NoneType' object has no attribute 'replace'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by purrloftruth** [comment]
### INFO
Python Version: **2.7.15 (default, Nov 26 2018, 01:46:47) [GCC 7.3.0]**
Operating System: **Linux-4.14.60-gentoo-whatbox-x86_64-Intel-R-_Xeon-R-_CPU_E5-2697_v4_@_2.30GHz-with-gentoo-2.6**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@abc6aab554715e57cf1668627a1f57f5b1ed4588
Link to Log: https://gist.github.com/12895a219b154343d4db0ec8a5fcb237
### ERROR
```
MANUAL :: [abc6aab] Failed doing webui callback: Traceback (most recent call last):
  File "/mnt/mpathk/biiaru/sickchill/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/mnt/mpathk/biiaru/sickchill/sickbeard/webserve.py", line 2490, in processEpisode
    result = result.replace("\n", "<br>\n")
AttributeError: 'NoneType' object has no attribute 'replace'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by purrloftruth** [comment]
I can provide some additional information as to what's going on here, at least as far as my particular issue goes.

It's attempting to process a file with an episode number of "00" in the filename. The filename of this particular file, for example, is "[RH] Nichijou - 00 [4261C944].mkv". Renaming this file so it doesn't have the 00 allows the postprocessing process to continue, but whether or not I'll actually be able to get it to attach to the correct slot (Episode 0 is listed as a "Special" for this particular show) is unknown yet.

> ### INFO
> Python Version: **2.7.15 (default, Nov 26 2018, 01:46:47) [GCC 7.3.0]**
> Operating System: **Linux-4.14.60-gentoo-whatbox-x86_64-Intel-R-_Xeon-R-_CPU_E5-2697_v4_@_2.30GHz-with-gentoo-2.6**
> Locale: UTF-8
> Branch: **master**
> Commit: [abc6aab](https://github.com/SickChill/SickChill/commit/abc6aab554715e57cf1668627a1f57f5b1ed4588)
> Link to Log: https://gist.github.com/12895a219b154343d4db0ec8a5fcb237
>
