### ISSUE TITLE
Error: No item with that key on startup

### ISSUE THREAD

**Issue by lokenx** [SickRage/SickRage#1969]
# Info

Branch/Commit: Master acf14ec
OS: Ubuntu 14.04
Python: 2.7.11
What you did: Update to latest commit
What happened: All shows disappeared 
What you expected: Shows not to disappear
Logs: The below is merely a single show, this occurred for every single show
Workaround: Rolled back to 946f6be31a26c661a5e0903c5d66e4ce348ce19d and things are back to normal. Updating again caused same issue

```
AA File "/opt/sickrage/sickbeard/tv.py", line 125, in __init__
AA cur_show = TVShow(sql_show[b'indexer'], sql_show[b'indexer_id'])
AA File "/opt/sickrage/SickBeard.py", line 481, in load_shows_from_db
AATraceback (most recent call last): 2016-06-14 19:58:40 ERROR MAIN :: [acf14ec] There was an error creating the show in /mnt/TV/True Detective: Error No item with that key
AAIndexError: No item with that key AA self.subtitles_sr_metadata = int(sql_results[0][b"sub_use_sr_metadata"] or 0)
AA File "/opt/sickrage/sickbeard/tv.py", line 817, in loadFromDB
AA self.loadFromDB()
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Thanks for the report.
Seems to be related to this PR. https://github.com/SickRage/SickRage/pull/1924
However cant explain it at this time, checked my own install and its working fine here.

Are you using any subtitle settings in Sickrage.? And do you have metadata files (tvshow.nfo) in the shows folders.?

**Comment by lokenx** [comment]
No subtitles settings enabled or ever have, and nope! Not sure where to check metadata settings but none of my folders have that in them..

**Comment by duramato** [comment]
If you are OK with,  can you share your main DB ` sickbeard.db `
You can send me via email if you want

**Comment by lokenx** [comment]
No worries just heading into the office, I'll send link or something on Gitter direct chat?

**Comment by duramato** [comment]
Sure can do

**Comment by duramato** [comment]
And also will need complete debug logs if you have, to try narrow it

**Comment by duramato** [comment]
Did you used your db from some other fork or something?
Yours is at version 44.1 while ours is at 43.1 and when you did the last SR update, what should had happen you would get the db upgraded to 43.2 and added a new table. But as you are ahead of the db version that didn't happen, i would think

**Comment by lokenx** [comment]
My DB would have been from the original version before the move to the current fork. Can I for update the DB or will a new update do it?

**Comment by dogeatdog** [comment]
I had the same thing today after updating to acf14ec6aec29e10e954efc7bef4dcfe371039f8 

I got a message that a new version was available, so I clicked the update link in my Sickrage main page. It updated.. and then all my shows were gone. 

The logs revealed the following :
2016-06-15 10:26:45 MAIN :: [acf14ec] There was an error creating the show in /media/data8/series/House of Cards (2013): Error No item with that key 2016-06-15 10:26:45 MAIN :: [acf14ec] There was an error creating the show in /media/data8/series/Banshee: Error No item with that key 2016-06-15 10:26:45 MAIN :: [acf14ec] There was an error creating the show in /media/data8/series/The Big Bang Theory: Error No item with that key ... and the list goes on for every single show I have.

I started to thing this had to have something to do with a database update since trying to Checkout Branch via the Advanced Settings results in a 'Can't switch branch as this will result in a database downgrade.' message.

Since I figured it had to do something with the database and I didn't feel like waiting for another solution, I stopped Sickrage, deleted sickbeard.db, started Sickrage again and added my (existing) shows again. Took me a while, but it was the best solution I could think of at that time. All is smooth again now. If you want I can attach my old and new sickbeard.db ?

**Comment by lokenx** [comment]
Hmm I just used Git directly to rollback my version, not sure if that could've messed stuff up?

**Comment by duramato** [comment]
Should be fixed, try updating to the latest master version, and let me know how it goes

**Comment by lokenx** [comment]
Seems to be good now! I get an error on startup but seems unrelated

```
2016-06-15 14:08:50 Thread-13 :: [34d0987] Failed doing webui callback: Traceback (most recent call last): File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call result = function(**kwargs) File "/opt/sickrage/sickbeard/webserve.py", line 700, in index return t.render(title=_("Home"), header=_("Show List"), topmenu="home", showlists=showlists, show_stat=stats[0], max_download_count=stats[1], controller="home", action="index") File "/opt/sickrage/sickbeard/webserve.py", line 160, in render kwargs['backtrace'] = RichTraceback() File "/opt/sickrage/lib/mako/exceptions.py", line 93, in __init__ self.records = self._init(traceback) File "/opt/sickrage/lib/mako/exceptions.py", line 165, in _init module_source = info.code File "/opt/sickrage/lib/mako/template.py", line 632, in code return util.read_python_file(self.module_filename) File "/opt/sickrage/lib/mako/util.py", line 374, in read_python_file fp = open(path, "rb") IOError: [Errno 2] No such file or directory: u'/opt/sickrage/cache/mako/home.mako.py'
```

**Comment by duramato** [comment]
Did you try restarting SR? `IOError: [Errno 2] No such file or directory: u'/opt/sickrage/cache/mako/home.mako.py'`  mako cache is cleaned on each startup afaik

**Comment by lokenx** [comment]
Seems fine now!
