### ISSUE TITLE
fresh install won't start up

### ISSUE THREAD

**Issue by gtippitt** [SickRage/SickRage#1972]
Please excuse me if I am posting this in the wrong place.  I installed SickRage a week ago on my Ubuntu 16.04 server.  It ran fine until a had it update itself and restarted my server.  I then started getting an error like the one below.  Since I didn't have much done with it yet, I deleted the old install. I have since tried several times to install it again on two different machines, but I continue to get the error below.  Since it fails to start, I have no logs.

If anyone can guide me toward what I'm doing wrong, I would deeply appreciate the assistance.

To install SickRage I did the following:
```
sudo apt-get install python-pip python-dev libssl-dev git unrar -y
sudo pip install pyopenssl
sudo git clone https://github.com/SickRage/SickRage.git   /opt/sickrage
sudo chown sickrage:sickrage -R /opt/sickrage
sudo --user=sickrage python /opt/sickrage/SickBeard.py -d
```

Greg

my errors
**Traceback (most recent call last):
  File "sickrage/SickBeard.py", line 94, in <module>
    import sickbeard
  File "/opt/sickrage/sickbeard/__init__.py", line 44, in <module>
    from sickbeard.config import CheckSection, check_setting_int, check_setting_str, \
  File "/opt/sickrage/sickbeard/config.py", line 29, in <module>
    from sickbeard import naming
  File "/opt/sickrage/sickbeard/naming.py", line 27, in <module>
    from sickbeard import tv
  File "/opt/sickrage/sickbeard/tv.py", line 36, in <module>
    from send2trash import send2trash
  File "/opt/sickrage/lib/send2trash/__init__.py", line 16, in <module>
    from .plat_gio import send2trash
  File "/opt/sickrage/lib/send2trash/plat_gio.py", line 7, in <module>
    from gi.repository import GObject, Gio
  File "/usr/lib/python2.7/dist-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
EOFError: EOF read where object expected**

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
The version of python you have installed seems broken.

**Comment by gtippitt** [comment]
Please excuse me.  I think this was a mistake on my part.  When I erased
and installed again, I think that I may have forgotten to delete the
/etc/default/sickrage or some other file.  After searching for and deleting
all "sick*" files and folders, the next install work fine.  Thank you for
your work on a great applications.
Greg
