### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/313059/en.xml

### ISSUE THREAD

**Issue by r5464y75** [SickRage/SickRage#1980]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.4.6-grsec-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@34d0987400b3d50f550f55472d417c4e5b263f55
No Log available with ERRORS:
### ERROR
```
Thread-30 :: [34d0987] Failed doing webui callback: Traceback (most recent call last):
  File "/home/disk19/ceelo/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/home/disk19/ceelo/sickrage/sickbeard/webserve.py", line 2738, in addShowByID
    show_name = get_showname_from_indexer(1, indexer_id)
  File "/home/disk19/ceelo/sickrage/sickbeard/helpers.py", line 1735, in get_showname_from_indexer
    s = t[int(indexer_id)]
  File "/home/disk19/ceelo/sickrage/lib/tvdb_api/tvdb_api.py", line 953, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/home/disk19/ceelo/sickrage/lib/tvdb_api/tvdb_api.py", line 848, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "/home/disk19/ceelo/sickrage/lib/tvdb_api/tvdb_api.py", line 636, in _getetsrc
    raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/313059/en.xml

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
