### ISSUE TITLE
ImportError: No module named sickrage.helper.common

### ISSUE THREAD

**Issue by frankicia** [SickRage/SickRage#1983]
I am in the latest branch. 

I copy the runscript for ubuntu to /etc/init.d and try to start:

    $ sudo service sickrage start
    Starting SickRage  
    Traceback (most recent call last):  
      File "SickBeard.py", line 94, in <module>  
        import sickbeard  
      File "/home/sickrage/sickbeard/__init__.py", line 39, in <module>
        from sickbeard.indexers import indexer_api
      File "/home/sickrage/sickbeard/indexers/__init__.py", line 21, in <module>
        from . import indexer_api
      File "/home/sickrage/sickbeard/indexers/indexer_api.py", line 23, in <module>
        from sickrage.helper.common import try_int
    ImportError: No module named sickrage.helper.common

My /etc/default/Sickrage (from it takes some inputs for the runscript):

    $ cat /etc/default/sickrage
    SR_USER=sickrage-daemon
    SR_HOME=/home/sickrage/
    SR_DATA=/home/sickrage/
    SR_OPTS=-config=/home/config.ini
    SR_PIDFILE=/home/sickrage/sickrage.pid

But if I execute from ~/sickrage/ the SickBear.py then it works like a charm

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by frankicia** [comment]
Ok, I figured out what happened.
The user I have to execute sickrage (sickrage-daemon) had no permissions to read from the folder ~/sickrage/sickrage/helpers/

Gave it permissions and fixed it
