### ISSUE TITLE
TV Shows added from IMDB Popular generate errors on "Show Details" and "Mass Update" screens

### ISSUE THREAD

**Issue by ErickXavier** [SickRage/SickRage#1985]
Branch: **master**
Commit: @34d0987400b3d50f550f55472d417c4e5b263f55
Version: **2016.06.14-1**
Database Version: **44.0**
Python Version: **2.7.6 (default, Aug 8 2014, 11:00:32) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
SSL Version: **OpenSSL 0.9.8za 5 Jun 2014**
OS: **Darwin-14.0.0-x86_64-i386-64bit (Mac OSX 10.10)**
Locale: **pt_BR.UTF-8**
What you did: Added 3 new TV Shows from "IMDB Populars" (Billions, Blindspot and Cleverman)
What happened: On the tv shows list, when I click in any of these 3 shows, the log bellow is shown in a White Screen, with no "SickRage" design applied. Attention, this only happens with shows I tried to add from "IMDB Popular"
What you expected: Well, to see the details of each show I clicked.
Logs:
```
Error

[Errno 2] No such file or directory: u'/Applications/Sickrage/cache/mako/layouts/main.mako.py'

Traceback

Traceback (most recent call last): 
File "/Applications/Sickrage/lib/tornado/web.py", line 1415, in _execute result = yield result 
File "/Applications/Sickrage/lib/tornado/gen.py", line 870, in run value = future.result() 
File "/Applications/Sickrage/lib/tornado/concurrent.py", line 215, in result raise_exc_info(self._exc_info) 
File "/Applications/Sickrage/lib/tornado/gen.py", line 876, in run yielded = self.gen.throw(*exc_info) 
File "/Applications/SickRage/sickbeard/webserve.py", line 254, in get results = yield self.async_call(method) 
File "/Applications/Sickrage/lib/tornado/gen.py", line 870, in run value = future.result() 
File "/Applications/Sickrage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/Applications/Sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/Applications/Sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/Applications/Sickrage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/Applications/SickRage/sickbeard/webserve.py", line 270, in async_call result = function(**kwargs) 
File "/Applications/SickRage/sickbeard/webserve.py", line 1373, in displayShow action="displayShow" 
File "/Applications/SickRage/sickbeard/webserve.py", line 160, in render kwargs['backtrace'] = RichTraceback() 
File "/Applications/Sickrage/lib/mako/exceptions.py", line 93, in __init__ self.records = self._init(traceback) 
File "/Applications/Sickrage/lib/mako/exceptions.py", line 165, in _init module_source = info.code 
File "/Applications/Sickrage/lib/mako/template.py", line 632, in code return util.read_python_file(self.module_filename) 
File "/Applications/Sickrage/lib/mako/util.py", line 374, in read_python_file fp = open(path, "rb") 
IOError: [Errno 2] No such file or directory: u'/Applications/Sickrage/cache/mako/layouts/main.mako.py' 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /home/displayShow?show=279536
query_arguments: {'show': ['279536']}
_start_time: 1466391451.63
headers: {'Accept-Language': 'pt-BR,pt;q=0.8,en;q=0.6,es;q=0.4', 'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36', 'Host': 'localhost:8081', 'Referer': 'http://localhost:8081/home/', 'Cookie': 'imdb_top_dvd_rentals_view=thumb; __utma=111872281.1831493686.1463011501.1463011501.1463011501.1; __utmc=111872281; __utmz=111872281.1463011501.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); user="2|1:0|10:1464094558|4:user|44:MWJkOGRmYzBlZTI1NGU5MTg5NDJkOTU1MDdjYTU5N2Q=|82b79fbd6d22615fc676f38cfbe5da1c9f3b65feff5b2f849e4dbf711b9f6d9d"; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; wanted_view=list; blu_ray_com_new_releases_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_box_office_view=thumb; imdb_top_250_movies_view=thumb; advanced_toggle_checked=0; manage_view=thumb; PHPSESSID=c7d07685f7f9dbc9cecae0ad0e33c671', 'Upgrade-Insecure-Requests': '1'}
host: localhost:8081
version: HTTP/1.1
arguments: {'show': '279536'}
_finish_time: None
query: show=279536
path: /home/displayShow
method: GET
remote_ip: 127.0.0.1

View Log(Errors)
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by ErickXavier** [comment]
New information, when I click on "Manage > Mass Update" similar screen appears:

```
Error

[Errno 2] No such file or directory: u'/Applications/Sickrage/cache/mako/layouts/main.mako.py'

Traceback

Traceback (most recent call last): 
File "/Applications/Sickrage/lib/tornado/web.py", line 1415, in _execute result = yield result 
File "/Applications/Sickrage/lib/tornado/gen.py", line 870, in run value = future.result() 
File "/Applications/Sickrage/lib/tornado/concurrent.py", line 215, in result raise_exc_info(self._exc_info) 
File "/Applications/Sickrage/lib/tornado/gen.py", line 876, in run yielded = self.gen.throw(*exc_info) 
File "/Applications/SickRage/sickbeard/webserve.py", line 254, in get results = yield self.async_call(method) 
File "/Applications/Sickrage/lib/tornado/gen.py", line 870, in run value = future.result() 
File "/Applications/Sickrage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/Applications/Sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/Applications/Sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/Applications/Sickrage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/Applications/SickRage/sickbeard/webserve.py", line 270, in async_call result = function(**kwargs) 
File "/Applications/SickRage/sickbeard/webserve.py", line 2958, in index return t.render(title=_('Mass Update'), header=_('Mass Update'), topmenu='manage', controller="manage", action="index") 
File "/Applications/SickRage/sickbeard/webserve.py", line 160, in render kwargs['backtrace'] = RichTraceback() 
File "/Applications/Sickrage/lib/mako/exceptions.py", line 93, in __init__ self.records = self._init(traceback) 
File "/Applications/Sickrage/lib/mako/exceptions.py", line 165, in _init module_source = info.code 
File "/Applications/Sickrage/lib/mako/template.py", line 632, in code return util.read_python_file(self.module_filename) 
File "/Applications/Sickrage/lib/mako/util.py", line 374, in read_python_file fp = open(path, "rb") 
IOError: [Errno 2] No such file or directory: u'/Applications/Sickrage/cache/mako/layouts/main.mako.py' 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /manage/
query_arguments: {}
_start_time: 1466392273.69
headers: {'Accept-Language': 'pt-BR,pt;q=0.8,en;q=0.6,es;q=0.4', 'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36', 'Host': 'localhost:8081', 'Referer': 'http://localhost:8081/home/', 'Cookie': 'imdb_top_dvd_rentals_view=thumb; __utma=111872281.1831493686.1463011501.1463011501.1463011501.1; __utmc=111872281; __utmz=111872281.1463011501.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); user="2|1:0|10:1464094558|4:user|44:MWJkOGRmYzBlZTI1NGU5MTg5NDJkOTU1MDdjYTU5N2Q=|82b79fbd6d22615fc676f38cfbe5da1c9f3b65feff5b2f849e4dbf711b9f6d9d"; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; wanted_view=list; blu_ray_com_new_releases_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_box_office_view=thumb; imdb_top_250_movies_view=thumb; advanced_toggle_checked=0; manage_view=thumb; PHPSESSID=c7d07685f7f9dbc9cecae0ad0e33c671', 'Upgrade-Insecure-Requests': '1'}
host: localhost:8081
version: HTTP/1.1
arguments: {}
_finish_time: None
query: 
path: /manage/
method: GET
remote_ip: 127.0.0.1

View Log(Errors)
```

**Comment by ErickXavier** [comment]
### New information

When I restarted SickRage, the error was gone. The shows details pages appears normally and the Mass Update screens just works.

**Comment by neoatomic** [comment]
Should be a 1 time error, and a restart should fix it.
Mostly this happens when you run two instances of Sickrage at the same time.
