### ISSUE TITLE
[APP SUBMITTED]: Parse error in value at line 844.

### ISSUE THREAD

**Issue by Djripper66** [SickRage/SickRage#1992]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@34d0987400b3d50f550f55472d417c4e5b263f55
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [34d0987] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 4849, in saveProviders
    sickbeard.save_config()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 1658, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8')
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/configobj.py", line 1302, in _load
    raise error
ParseError: Parse error in value at line 844.

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Its probbebly a special character that is causing this. But i'm unable to tell without debug logs...
