### ISSUE TITLE
Does not install

### ISSUE THREAD

**Issue by dilruwan7** [SickRage/SickRage#2010]
**Branch/Commit:** master 34d0987
**OS:** Mac OSX 10.11.5 (15F34)
**What you did:** I tried to install sickrage, 
**What happened:** The install did not fully complete with the error code 

> Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/d6/78tc0r7s4f76f91nv9zm1jkm0000gn/T/pip-build-ZzAaYc/hachoir-metadata

I had a look around on Google/Stackoverflow and I have updated the latest version of pip and setuptools but the error still occurs. 

**What you expected:** For sickrage to install
**Logs:**

pip install -U sickrage
Collecting sickrage
  Using cached sickrage-8.0.0-py2.py3-none-any.whl
Collecting rtorrent-python==0.2.9 (from sickrage)
  Using cached rtorrent-python-0.2.9.tar.gz
Collecting yarg==0.1.9 (from sickrage)
  Downloading yarg-0.1.9-py2.py3-none-any.whl
Collecting stevedore==1.12.0 (from sickrage)
  Using cached stevedore-1.12.0-py2.py3-none-any.whl
Collecting Mako==1.0.4 (from sickrage)
  Using cached Mako-1.0.4.tar.gz
Collecting hachoir-parser==1.3.4 (from sickrage)
  Using cached hachoir-parser-1.3.4.tar.gz
Collecting configobj==5.0.6 (from sickrage)
  Using cached configobj-5.0.6.tar.gz
Collecting sqlite-cache==0.0.3 (from sickrage)
  Using cached sqlite_cache-0.0.3.tar.gz
Collecting requests[security]==2.10.0 (from sickrage)
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 687kB/s 
Collecting Tempita==0.5.2 (from sickrage)
  Using cached Tempita-0.5.2.tar.gz
Collecting funcsigs==1.0.2 (from sickrage)
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Collecting jsonrpclib==0.1.7 (from sickrage)
  Using cached jsonrpclib-0.1.7.tar.gz
Collecting gntp==1.0.3 (from sickrage)
  Using cached gntp-1.0.3-py2-none-any.whl
Collecting pyOpenSSL==16.0.0 (from sickrage)
  Downloading pyOpenSSL-16.0.0-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 1.0MB/s 
Collecting imdbpie==4.0.2 (from sickrage)
  Using cached imdbpie-4.0.2-py2.py3-none-any.whl
Collecting oauth2==1.9.0.post1 (from sickrage)
  Using cached oauth2-1.9.0.post1-py2.py3-none-any.whl
Collecting hachoir-metadata==1.3.3 (from sickrage)
  Using cached hachoir-metadata-1.3.3.tar.gz
    Complete output from command python setup.py egg_info:
    Warning: unable to recompile dialog.ui to dialog_ui.py using pyuic4
    (use command "-c egg_info --egg-base pip-egg-info --disable-qt" to disable this warning)
    
    running egg_info
    creating pip-egg-info/hachoir_metadata.egg-info
    writing pip-egg-info/hachoir_metadata.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/hachoir_metadata.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/hachoir_metadata.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/hachoir_metadata.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/hachoir_metadata.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/hachoir_metadata.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/d6/78tc0r7s4f76f91nv9zm1jkm0000gn/T/pip-build-ZzAaYc/hachoir-metadata/setup.py", line 102, in <module>
        main()
      File "/private/var/folders/d6/78tc0r7s4f76f91nv9zm1jkm0000gn/T/pip-build-ZzAaYc/hachoir-metadata/setup.py", line 64, in main
        exitcode = call(command)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
        return Popen(*popenargs, **kwargs).wait()
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
        child_exception = pickle.loads(data)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1388, in loads
        return Unpickler(file).load()
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 864, in load
        dispatch[key](self)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 972, in load_string
        raise ValueError, "insecure string pickle"
    ValueError: insecure string pickle
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/d6/78tc0r7s4f76f91nv9zm1jkm0000gn/T/pip-build-ZzAaYc/hachoir-metadata/

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
You are installing the wrong sickrage. (thats the old Repo, that's broken/not working.)
Give the below guide a try. :) 

http://www.htpcguides.com/install-sickrage-mac-osx-usenet-torrent-tv/

**Comment by dilruwan7** [comment]
@neoatomic - Thank you! Worked like a charm 👍
