### ISSUE TITLE
Can't start init.d process

### ISSUE THREAD

**Issue by Moerin** [SickRage/SickRage#2012]
branch : master
OS: raspbian

Hi, I tried to create a service process for SiCKRAGE.

Launch the application by command line (python SiCKRAGE.py) is working but when I copy the debian script for init.d I found the following error
```
Jun 26 18:55:22 groseille.pi sickrage[12063]: ..::[ SiCKRAGE ]::..
Jun 26 18:55:22 groseille.pi sickrage[12063]: ..::[ SiCKRAGE ]::..
Jun 26 18:55:22 groseille.pi sickrage[12063]: Daemonized successfully, pid 12093
Jun 26 18:55:22 groseille.pi sickrage[12063]: Traceback (most recent call last):
Jun 26 18:55:22 groseille.pi sickrage[12063]: File "/home/pi/SiCKRAGE/sickrage/__init__.py", line 273, in main
Jun 26 18:55:22 groseille.pi sickrage[12063]: daemonize(PIDFILE)
Jun 26 18:55:22 groseille.pi sickrage[12063]: File "/home/pi/SiCKRAGE/sickrage/__init__.py", line 142, in daemonize
Jun 26 18:55:22 groseille.pi sickrage[12063]: os.dup2(so.fileno(), sys.stdout.fileno())
Jun 26 18:55:22 groseille.pi sickrage[12063]: AttributeError: 'UnicodeStdout' object has no attribute 'fileno'
```
I've used this scripts init.debian as default and here my /etc/default/sickrage:
SR_USER=pi
SR_HOME=/home/pi/SiCKRAGE
SR_DATA=/home/pi/.sickrage

Any ideas?

Cheers.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by kooimens** [comment]
Same here

**Comment by p0psicles** [comment]
Can you post the exact commit your on?

**Comment by Moerin** [comment]
Sure I'm this commit : eee6b67028f45a9d87763c65966e6897acb105cb

**Comment by p0psicles** [comment]
That's not a sickrage commit.  Think your on a different fork.

**Comment by kooimens** [comment]
Can you explain why you wouldn't recommend that one?

**Comment by duramato** [comment]
It not working at all, is one big selling point. Also we do not provide any support for it.
