### ISSUE TITLE
SQL syntax error when checking for duplicates when converting TVRage shows to TheTVDB

### ISSUE THREAD

**Issue by dgholz** [SickRage/SickRage#2028]
Branch/Commit: develop
OS: debian jessie
What you did: started sickrage with my old config, previously on SiCKRAGETV 68cd0fa18e3ae75a368728aeaaae7913caf13db4
What happened: sickrage failed to start
What you expected: sickrage to start
Logs:
```
01:04:54 WARNING::MAIN :: Found 1 shows with TVRage ID's, attempting automatic conversion...
01:04:54 INFO::MAIN :: Processing The House of Eliott at /sickrage/tv/The House of Eliott
01:04:54 INFO::MAIN :: Checking if there is already a show with id:%i in the show list
01:04:54 ERROR::MAIN :: [d131b57] DB error: near "FROM": syntax error
Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/sickrage/sickbeard/db.py", line 106, in _execute
    sql_results = self.connection.cursor().execute(query)
OperationalError: near "FROM": syntax error
Traceback (most recent call last):
  File "/opt/sickrage/SickBeard.py", line 566, in <module>
    SickRage().start()
  File "/opt/sickrage/SickBeard.py", line 315, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/opt/sickrage/sickbeard/__init__.py", line 1435, in initialize
    db.sanityCheckDatabase(main_db_con, mainDB.MainSanityCheck)
  File "/opt/sickrage/sickbeard/db.py", line 401, in sanityCheckDatabase
    sanity_check(connection).check()
  File "/opt/sickrage/sickbeard/databases/mainDB.py", line 52, in check
    self.convert_tvrage_to_tvdb()
  File "/opt/sickrage/sickbeard/databases/mainDB.py", line 106, in convert_tvrage_to_tvdb
    duplicate = self.connection.select("SELECT show_name, indexer_id, location, FROM tv_shows WHERE indexer_id = {0:d} AND indexer = {1:d}".format(mapping[0]['mindexer_id'], INDEXER_TVDB))
  File "/opt/sickrage/sickbeard/db.py", line 287, in select
    sql_results = self.action(query, args, fetchall=True)
  File "/opt/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/sickrage/sickbeard/db.py", line 106, in _execute
    sql_results = self.connection.cursor().execute(query)
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Thanks for the PR, i see its merged. :)
