### ISSUE TITLE
[APP SUBMITTED]: 'getpwuid(): uid not found: 1001'

### ISSUE THREAD

**Issue by Skewled** [SickRage/SickRage#2030]
### INFO
Python Version: **2.7.11+ (default, Apr 17 2016, 14:00:29) [GCC 5.3.1 20160413]**
Operating System: **Linux-4.4.0-28-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@34d0987400b3d50f550f55472d417c4e5b263f55
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [34d0987] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 3751, in index
    sr_user = pwd.getpwuid(os.getuid()).pw_name
KeyError: 'getpwuid(): uid not found: 1001'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Skewled** [comment]
Pretty sure this has to do with changing the uid of the user running sickrage as a service.
