### ISSUE TITLE
qBittorrent label setting for version 3.3.5 no longer working.

### ISSUE THREAD

**Issue by EraYaN** [SickRage/SickRage#2041]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master 
OS: Windows Server 2012 R2
What you did: Snatched torrent
What happened: Torrent got added without label
What you expected: Torrent added with label
Logs: ( For qBittorrent test)
```
2016-07-06 20:56:51 Thread-19 :: [34d0987] Failed doing webui callback: Traceback (most recent call last):
  File "C:\Program Files (x86)\SickRage\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\Program Files (x86)\SickRage\sickbeard\webserve.py", line 800, in testTorrent
    result_, accesMsg = client(host, username, password).testAuthentication()
  File "C:\Program Files (x86)\SickRage\sickbeard\clients\generic.py", line 274, in testAuthentication
    helpers.handle_requests_exception(error)
  File "C:\Program Files (x86)\SickRage\sickbeard\helpers.py", line 1453, in handle_requests_exception
    if error.response.status_code == 404 and \
AttributeError: 'NoneType' object has no attribute 'status_code'

```
(For actual issue)
```
2016-07-06 21:17:49 WARNING  SEARCHQUEUE-BACKLOG-261802 :: qbittorrent: Unable to send Torrent
2016-07-06 21:17:49 INFO     SEARCHQUEUE-BACKLOG-261802 :: Request failed: 403 Client Error: Forbidden for url: http://localhost:8080/command/download
2016-07-06 21:17:49 DEBUG    SEARCHQUEUE-BACKLOG-261802 :: qbittorrent: Requested a POST connection to url http://localhost:8080/command/download and data: {'urls': u'magnet:?xt=urn:btih:b90639c6910351909e3edc6c68107b019eb68e21&dn=Devious.Maids.S02E11.You...
2016-07-06 21:17:49 DEBUG    SEARCHQUEUE-BACKLOG-261802 :: Calling qbittorrent Client
2016-07-06 21:17:49 INFO     SEARCHQUEUE-BACKLOG-261802 :: Downloading Devious.Maids.S02E11.You.Cant.Take.It.With.You.1080p.WEB-DL.DD5. from ThePirateBay
```

Cause: label system overhaul and API version bump. Should implement (GUI) warning on test, that unsupported version is used. Now the test just hangs. I have checked the user/password (besides the bypass auth for localhost is selected in qBittorrent).

Also `qbittorrent: Unable to send Torrent` is seen as a warning while the not being able to set a label is an error. That is a little weird. Seems backwards.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
