### ISSUE TITLE
Mass update returns error

### ISSUE THREAD

**Issue by danielmason30** [SickRage/SickRage#2075]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@9e75d592bf4e4cd463087aa428f994530ed67971
No Log available with ERRORS:
### ERROR
```
Error

'utf8' codec can't decode byte 0xe9 in position 23: invalid continuation byte

Traceback

Traceback (most recent call last): 
File "C:\SickRage\lib\tornado\web.py", line 1415, in _execute result = yield result 
File "C:\SickRage\lib\tornado\gen.py", line 870, in run value = future.result() 
File "C:\SickRage\lib\tornado\concurrent.py", line 215, in result raise_exc_info(self._exc_info) 
File "C:\SickRage\lib\tornado\gen.py", line 876, in run yielded = self.gen.throw(*exc_info) 
File "C:\SickRage\sickbeard\webserve.py", line 254, in get results = yield self.async_call(method) 
File "C:\SickRage\lib\tornado\gen.py", line 870, in run value = future.result() 
File "C:\SickRage\lib\concurrent\futures\_base.py", line 400, in result return self.__get_result() 
File "C:\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "C:\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "C:\SickRage\lib\concurrent\futures\thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "C:\SickRage\sickbeard\webserve.py", line 270, in async_call result = function(**kwargs) 
File "C:\SickRage\sickbeard\webserve.py", line 3434, in massEditSubmit directCall=True) 
File "C:\SickRage\sickbeard\webserve.py", line 1552, in editShow location = location.decode('UTF-8') 
File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode return codecs.utf_8_decode(input, errors, True) 
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 23: invalid continuation byte 

Request Info

body: toEdit=272644%7C286362%7C149101%7C204161%7C281613%7C289108%7C73141%7C309053%7C253478%7C281614%7C304262%7C303586%7C311819%7C281537%7C257655%7C296295%7C281714%7C303069%7C294206%7C273181%7C279536%7C262407%7C281511%7C295647%7C287314%7C281181%7C282254%7C75682%7C277928%7C309052%7C81189%7C266398%7C311945%7C303300%7C289771%7C276916%7C113701%7C265369%7C261745%7C308846%7C295780%7C284210%7C94571%7C295767%7C311878%7C296654%7C267970%7C262558%7C292174%7C295760%7C309992%7C311876%7C280847%7C294801%7C306859%7C299845%7C78804%7C295697%7C295557%7C79836%7C255316%7C295779%7C281617%7C254834%7C123581%7C287299%7C75978%7C269613%7C290853%7C305722%7C306249%7C309959%7C311958%7C264190%7C121361%7C268009%7C274431%7C81561%7C306391%7C309990%7C284643%7C305687%7C280537%7C247897%7C262980%7C281620%7C292124%7C304962%7C76605%7C311915%7C289079%7C281470%7C306347%7C311944%7C281534%7C278518%7C311790%7C260092%7C305378%7C295685%7C159591%7C311902%7C281623%7C309212%7C257248%7C311833%7C283346%7C311946%7C308986%7C263365%7C281662%7C284190%7C304219%7C84489%7C167751%7C82817%7C299033%7C262569%7C76316%7C289590%7C273402%7C282670%7C278125%7C312423%7C294133%7C311957%7C255005%7C311877%7C298085%7C303236%7C270915%7C311835%7C267951%7C76703%7C312585%7C286943%7C300472%7C75340%7C311947%7C295515%7C306719%7C259866%7C311954%7C307368%7C75734%7C295683%7C298368%7C120541%7C281630%7C293302%7C294417%7C310903%7C268156%7C281711%7C295837%7C176941%7C311834%7C284265%7C76355%7C277165%7C305194%7C269578%7C263921%7C311817%7C299614%7C75897%7C311875%7C291273%7C304214%7C283468%7C292745%7C305288%7C247808%7C295759%7C300714%7C80165%7C268592%7C310911%7C261690%7C75795%7C299972%7C80379%7C81068%7C266189%7C295696%7C93991%7C302973%7C305666%7C308129%7C311816%7C280619%7C279121%7C300886%7C297346%7C311711%7C184871%7C311948%7C260355%7C79216%7C298566%7C281622%7C269533%7C269689%7C281709%7C308509%7C299139%7C295829%7C259007%7C282401%7C272391%7C269159%7C310516%7C78107%7C73244%7C304196%7C310263%7C300658%7C289096%7C71663%7C276564%7C202571%7C274065%7C257313%7C153021%7C74626%7C77398%7C311714%7C303884%7C311713%7C311949%7C293753%7C250436%7C281593%7C295720%7C300929%7C301057%7C300280%7C307899%7C276838%7C269750%7C296762%7C310457%7C310555%7C305582%7C281776%7C283318&orig_root_dir_0=M%3A%5C_temporary_shows&new_root_dir_0=M%3A%5C_temporary_shows&orig_root_dir_1=M%3A%5CTV+Shows&new_root_dir_1=M%3A%5CTV+Shows&quality_preset=keep&flatten_folders=enable&paused=disable&default_ep_status=3&scene=keep&anime=disable&sports=disable&air_by_date=disable&subtitles=disable
files: {}
protocol: http
connection: 
body_arguments: {'paused': ['disable'], 'flatten_folders': ['enable'], 'new_root_dir_0': ['M:\\_temporary_shows'], 'new_root_dir_1': ['M:\\TV Shows'], 'orig_root_dir_0': ['M:\\_temporary_shows'], 'orig_root_dir_1': ['M:\\TV Shows'], 'scene': ['keep'], 'sports': ['disable'], 'air_by_date': ['disable'], 'default_ep_status': ['3'], 'quality_preset': ['keep'], 'toEdit': ['272644|286362|149101|204161|281613|289108|73141|309053|253478|281614|304262|303586|311819|281537|257655|296295|281714|303069|294206|273181|279536|262407|281511|295647|287314|281181|282254|75682|277928|309052|81189|266398|311945|303300|289771|276916|113701|265369|261745|308846|295780|284210|94571|295767|311878|296654|267970|262558|292174|295760|309992|311876|280847|294801|306859|299845|78804|295697|295557|79836|255316|295779|281617|254834|123581|287299|75978|269613|290853|305722|306249|309959|311958|264190|121361|268009|274431|81561|306391|309990|284643|305687|280537|247897|262980|281620|292124|304962|76605|311915|289079|281470|306347|311944|281534|278518|311790|260092|305378|295685|159591|311902|281623|309212|257248|311833|283346|311946|308986|263365|281662|284190|304219|84489|167751|82817|299033|262569|76316|289590|273402|282670|278125|312423|294133|311957|255005|311877|298085|303236|270915|311835|267951|76703|312585|286943|300472|75340|311947|295515|306719|259866|311954|307368|75734|295683|298368|120541|281630|293302|294417|310903|268156|281711|295837|176941|311834|284265|76355|277165|305194|269578|263921|311817|299614|75897|311875|291273|304214|283468|292745|305288|247808|295759|300714|80165|268592|310911|261690|75795|299972|80379|81068|266189|295696|93991|302973|305666|308129|311816|280619|279121|300886|297346|311711|184871|311948|260355|79216|298566|281622|269533|269689|281709|308509|299139|295829|259007|282401|272391|269159|310516|78107|73244|304196|310263|300658|289096|71663|276564|202571|274065|257313|153021|74626|77398|311714|303884|311713|311949|293753|250436|281593|295720|300929|301057|300280|307899|276838|269750|296762|310457|310555|305582|281776|283318'], 'subtitles': ['disable'], 'anime': ['disable']}
uri: /manage/massEditSubmit
query_arguments: {}
_start_time: 1468448514.58
headers: {'Origin': 'http://localhost:8081', 'Content-Length': '2488', 'Accept-Language': 'en-GB,en-US;q=0.8,en;q=0.6', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Host': 'localhost:8081', 'Referer': 'http://localhost:8081/manage/massEdit?toEdit=272644|286362|149101|204161|281613|289108|73141|309053|253478|281614|304262|303586|311819|281537|257655|296295|281714|303069|294206|273181|279536|262407|281511|295647|287314|281181|282254|75682|277928|309052|81189|266398|311945|303300|289771|276916|113701|265369|261745|308846|295780|284210|94571|295767|311878|296654|267970|262558|292174|295760|309992|311876|280847|294801|306859|299845|78804|295697|295557|79836|255316|295779|281617|254834|123581|287299|75978|269613|290853|305722|306249|309959|311958|264190|121361|268009|274431|81561|306391|309990|284643|305687|280537|247897|262980|281620|292124|304962|76605|311915|289079|281470|306347|311944|281534|278518|311790|260092|305378|295685|159591|311902|281623|309212|257248|311833|283346|311946|308986|263365|281662|284190|304219|84489|167751|82817|299033|262569|76316|289590|273402|282670|278125|312423|294133|311957|255005|311877|298085|303236|270915|311835|267951|76703|312585|286943|300472|75340|311947|295515|306719|259866|311954|307368|75734|295683|298368|120541|281630|293302|294417|310903|268156|281711|295837|176941|311834|284265|76355|277165|305194|269578|263921|311817|299614|75897|311875|291273|304214|283468|292745|305288|247808|295759|300714|80165|268592|310911|261690|75795|299972|80379|81068|266189|295696|93991|302973|305666|308129|311816|280619|279121|300886|297346|311711|184871|311948|260355|79216|298566|281622|269533|269689|281709|308509|299139|295829|259007|282401|272391|269159|310516|78107|73244|304196|310263|300658|289096|71663|276564|202571|274065|257313|153021|74626|77398|311714|303884|311713|311949|293753|250436|281593|295720|300929|301057|300280|307899|276838|269750|296762|310457|310555|305582|281776|283318', 'Cache-Control': 'max-age=0', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded'}
host: localhost:8081
version: HTTP/1.1
arguments: {'air_by_date': 'disable', 'new_root_dir_0': 'M:\\_temporary_shows', 'new_root_dir_1': 'M:\\TV Shows', 'orig_root_dir_0': 'M:\\_temporary_shows', 'orig_root_dir_1': 'M:\\TV Shows', 'default_ep_status': '3', 'scene': 'keep', 'sports': 'disable', 'paused': 'disable', 'flatten_folders': 'enable', 'quality_preset': 'keep', 'toEdit': '272644|286362|149101|204161|281613|289108|73141|309053|253478|281614|304262|303586|311819|281537|257655|296295|281714|303069|294206|273181|279536|262407|281511|295647|287314|281181|282254|75682|277928|309052|81189|266398|311945|303300|289771|276916|113701|265369|261745|308846|295780|284210|94571|295767|311878|296654|267970|262558|292174|295760|309992|311876|280847|294801|306859|299845|78804|295697|295557|79836|255316|295779|281617|254834|123581|287299|75978|269613|290853|305722|306249|309959|311958|264190|121361|268009|274431|81561|306391|309990|284643|305687|280537|247897|262980|281620|292124|304962|76605|311915|289079|281470|306347|311944|281534|278518|311790|260092|305378|295685|159591|311902|281623|309212|257248|311833|283346|311946|308986|263365|281662|284190|304219|84489|167751|82817|299033|262569|76316|289590|273402|282670|278125|312423|294133|311957|255005|311877|298085|303236|270915|311835|267951|76703|312585|286943|300472|75340|311947|295515|306719|259866|311954|307368|75734|295683|298368|120541|281630|293302|294417|310903|268156|281711|295837|176941|311834|284265|76355|277165|305194|269578|263921|311817|299614|75897|311875|291273|304214|283468|292745|305288|247808|295759|300714|80165|268592|310911|261690|75795|299972|80379|81068|266189|295696|93991|302973|305666|308129|311816|280619|279121|300886|297346|311711|184871|311948|260355|79216|298566|281622|269533|269689|281709|308509|299139|295829|259007|282401|272391|269159|310516|78107|73244|304196|310263|300658|289096|71663|276564|202571|274065|257313|153021|74626|77398|311714|303884|311713|311949|293753|250436|281593|295720|300929|301057|300280|307899|276838|269750|296762|310457|310555|305582|281776|283318', 'subtitles': 'disable', 'anime': 'disable'}
_finish_time: None
query: 
path: /manage/massEditSubmit
method: POST
remote_ip: ::1
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Probably a special character coursing the error. However i cant see from what name/show. Also see if you can lower the number of shows that you mass update at a time.

**Comment by mattpulpfree** [comment]
Having a similar issue. this is the error I keep getting when trying to mass edit, with all shows or just 5 selected.

Traceback (most recent call last):
  File "C:\SickRage\lib\tornado\web.py", line 1390, in _execute
    result = self.prepare()
  File "C:\SickRage\lib\tornado\web.py", line 2103, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found

**Comment by neoatomic** [comment]
Again, its a special character that is probbebly to blame. Check your shows and folders for that, and change/rename it. 
Windows and special characters is just a bad combination. Only way to get around that is moving to a Linux based OS that supports UTF-8. :(
