### ISSUE TITLE
[APP SUBMITTED]: Parsing failed with several errors.
First error at line 983.

### ISSUE THREAD

**Issue by 00mpy** [SickRage/SickRage#2077]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@9e75d592bf4e4cd463087aa428f994530ed67971
No Log available with ERRORS:
### ERROR
```
Thread-18 :: [9e75d59] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 3661, in index
    sickbeard.save_config()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/__init__.py", line 1661, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8')
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/configobj.py", line 1302, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 983.

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by 00mpy** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@9e75d592bf4e4cd463087aa428f994530ed67971
No Log available with ERRORS:
### ERROR
```
Thread-20 :: [9e75d59] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 3661, in index
    sickbeard.save_config()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/__init__.py", line 1661, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8')
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/configobj.py", line 1302, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 983.

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by 00mpy** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@9e75d592bf4e4cd463087aa428f994530ed67971
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [9e75d59] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 3661, in index
    sickbeard.save_config()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/__init__.py", line 1661, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8')
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/configobj.py", line 1302, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 983.

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by 00mpy** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@9e75d592bf4e4cd463087aa428f994530ed67971
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [9e75d59] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 3661, in index
    sickbeard.save_config()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/__init__.py", line 1661, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8')
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/configobj.py", line 1302, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 983.

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by p0psicles** [comment]
I would recommend to create a backup of your configuration file,  and the delete config.ini. A new one will be generated. Then you can look at the differences.

**Comment by miigotu** [comment]
Open config.ini and look at line 983.... Your config.ini has become corrupted, you might be able to just fix the errors in it, or you might have to regenerate it and re-add all the settings. SR did not cause this, it was likely a forced shutdown or power loss or crash while the config was being written.
