### ISSUE TITLE
Error in subtitle management

### ISSUE THREAD

**Issue by royteeuwen** [SickRage/SickRage#2094]
Following error gets thrown on my QNAP when post-processing with subtitles enabled:
````
2016-07-16 23:50:24 FINDSUBTITLES :: [8e42283] Traceback (most recent call last): File "/share/CACHEDEV1_DATA/.qpkg/sickrage/sickbeard/subtitles.py", line 244, in download_subtitles (subtitle.provider_name, subtitle.id, score, user_score), logger.DEBUG) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language) File "/share/CACHEDEV1_DATA/.qpkg/sickrage/lib/subliminal/subtitle.py", line 162, in __repr__ return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language)
````
SickRage Info:
Branch: master
Commit: 8e42283
Version: 2016.07.10-1
Database Version: 44.0
Python Version: 2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]
SSL Version: OpenSSL 0.9.8e 23 Feb 2007
OS: Linux-3.19.8+-x86_64-with-glibc2.4

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Its already reported. : https://github.com/SickRage/SickRage/issues/1864
