### ISSUE TITLE
Subtitle recursion issue

### ISSUE THREAD

**Issue by Xebozone** [SickRage/SickRage#2096]
Just thought I would leave this here...

Branch/Commit: Master (latest commit as at time of reporting)
OS: Ubuntu 14
Logs:
```
2016-07-17 06:43:50 FINDSUBTITLES :: [8e42283] Traceback (most recent call last):
  File "/home/myth/sickRage/sickbeard/subtitles.py", line 244, in download_subtitles
    (subtitle.provider_name, subtitle.id, score, user_score), logger.DEBUG)
  File "/home/myth/sickRage/lib/subliminal/subtitle.py", line 162, in __repr__
    return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language)
  File "/home/myth/sickRage/lib/subliminal/subtitle.py", line 162, in __repr__
    return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language)
............................................. (this continues for a while)
    return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language)
  File "/home/myth/sickRage/lib/subliminal/subtitle.py", line 162, in __repr__
    return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language)
  File "/home/myth/sickRage/lib/subliminal/subtitle.py", line 162, in __repr__
    return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language)
  File "/home/myth/sickRage/lib/subliminal/subtitle.py", line 162, in __repr__
    return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language)
  File "/home/myth/sickRage/lib/subliminal/subtitle.py", line 162, in __repr__
    return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language)
  File "/home/myth/sickRage/lib/subliminal/subtitle.py", line 162, in __repr__
    return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language)
  File "/home/myth/sickRage/lib/subliminal/subtitle.py", line 162, in __repr__
    return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language)
  File "/home/myth/sickRage/lib/subliminal/subtitle.py", line 162, in __repr__
    return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language)
  File "/home/myth/sickRage/lib/subliminal/subtitle.py", line 162, in __repr__
    return '<%s %r [%s]>' % (self.__class__.__name__, self.id, self.language)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Its already reported. : https://github.com/SickRage/SickRage/issues/1864
