### ISSUE TITLE
Error on processing XEM scene exception

### ISSUE THREAD

**Issue by poppop92** [SickRage/SickRage#2103]
Branch/Commit: 018a6b0f81158ddd669934464f92a5e2e285cd47
OS: Linux
What you did: Triggered an episode search
What happened: Episode switched to snatched state but nothing arrives to downloader.
Everything was working correctly before updating to the HEAD of master
What you expected: A new download shall be triggered.
Logs:
```
16-07-20 19:41:09 INFO     SEARCHQUEUE-MANUAL-300472 :: Beginning manual search for: [XXX]
2016-07-20 19:41:09 INFO     SEARCHQUEUE-MANUAL-300472 :: Checking for XEM scene exception updates for theTVDB
2016-07-20 19:41:09 DEBUG    SEARCHQUEUE-MANUAL-300472 :: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/search_queue.py", line 179, in run
    searchResult = search.searchProviders(self.show, [self.segment], True, self.downCurQuality)
  File "/opt/sickrage/sickbeard/search.py", line 453, in searchProviders
    sickbeard.name_cache.buildNameCache(show)
  File "/opt/sickrage/sickbeard/name_cache.py", line 83, in buildNameCache
    sickbeard.scene_exceptions.retrieve_exceptions()
  File "/opt/sickrage/sickbeard/scene_exceptions.py", line 223, in retrieve_exceptions
    _xem_exceptions_fetcher()
  File "/opt/sickrage/sickbeard/scene_exceptions.py", line 317, in _xem_exceptions_fetcher
    for indexerid, names in parsedJSON['data'].iteritems():
AttributeError: 'list' object has no attribute 'iteritems'

```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duramato** [comment]
Did you try checking xem's site? It seems to be having issues or on maintnance.
