### ISSUE TITLE
Search provider is not not called

### ISSUE THREAD

**Issue by DonJX** [SickRage/SickRage#2108]
Branch/Commit: Branch: master; Commit: 018a6b0f81158ddd669934464f92a5e2e285cd47
OS: Linux-3.12.6-x86_64-with-glibc2.2.5 / QNAP
What you did: Trigger a search manually
What happened: The search provider is not being called. It appears as if no provider can be found although some are setup.
What you expected: Querying the search provider API
Logs:

>  21:54:58 DEBUG    SEARCHQUEUE-MANUAL-153021 :: formatting pattern: %SN - S%0SE%0E - %EN -> The Walking Dead - S06E15 - East
2016-07-20 21:54:58 INFO     SEARCHQUEUE-MANUAL-153021 :: Beginning manual search for: [The Walking Dead - S06E15 - East]
2016-07-20 21:54:58 INFO     SEARCHQUEUE-MANUAL-153021 :: Checking for XEM scene exception updates for theTVDB
2016-07-20 21:54:58 DEBUG    SEARCHQUEUE-MANUAL-153021 :: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/search_queue.py", line 179, in run
    searchResult = search.searchProviders(self.show, [self.segment], True, self.downCurQuality)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/search.py", line 453, in searchProviders
    sickbeard.name_cache.buildNameCache(show)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/name_cache.py", line 83, in buildNameCache
    sickbeard.scene_exceptions.retrieve_exceptions()
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/scene_exceptions.py", line 223, in retrieve_exceptions
    _xem_exceptions_fetcher()
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/scene_exceptions.py", line 317, in _xem_exceptions_fetcher
    for indexerid, names in parsedJSON['data'].iteritems():
AttributeError: 'list' object has no attribute 'iteritems'

![2016-07-20 21_59_17-sickrage - config - providers](https://cloud.githubusercontent.com/assets/1153528/17002854/435d3420-4ec5-11e6-8fc7-475dd462d6c6.png)

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duramato** [comment]
https://github.com/SickRage/SickRage/issues/2103
