### ISSUE TITLE
[APP SUBMITTED]: index() got an unexpected keyword argument '<methodCall> <methodName>system.listMethods</methodName> <params></params> </methodCall>'

### ISSUE THREAD

**Issue by NilsNojje** [SickRage/SickRage#2142]
### INFO
Python Version: **2.7.11+ (default, Apr 17 2016, 14:00:29) [GCC 5.3.1 20160413]**
Operating System: **Linux-4.4.0-24-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@570cd207fe00798fb2182b0a90af16c1d936ea83
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [570cd20] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument '<methodCall> <methodName>system.listMethods</methodName> <params></params> </methodCall>'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Sadly the log is missing. Where/how did this error happen.?

**Comment by fookhk** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  8 2015, 00:52:26) [GCC 4.9.2]**
Operating System: **Linux-4.4.20-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4d69a8e09fe808751fa5fef9a0c3e3b8c1af99b1
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [4d69a8e] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument '<methodCall> <methodName>system.listMethods</methodName> <params></params> </methodCall>'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by jimcrilly** [comment]
### INFO
Python Version: **2.7.14+ (default, Feb  6 2018, 19:12:18) [GCC 7.3.0]**
Operating System: **Linux-4.14.0-2-amd64-x86_64-with-debian-buster-sid**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@7ddf7f5c9814688275aa437aa6834f948f2d3fa7
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_5 :: [7ddf7f5] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument '<methodCall> <methodName>system.listMethods</methodName> <params></params> </methodCall>'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by jimcrilly** [comment]
### INFO
Python Version: **2.7.14+ (default, Feb  6 2018, 19:12:18) [GCC 7.3.0]**
Operating System: **Linux-4.14.0-2-amd64-x86_64-with-debian-buster-sid**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@7ddf7f5c9814688275aa437aa6834f948f2d3fa7
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [7ddf7f5] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument '<methodCall> <methodName>system.listMethods</methodName> <params></params> </methodCall>'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by jimcrilly** [comment]
### INFO
Python Version: **2.7.14+ (default, Feb  6 2018, 19:12:18) [GCC 7.3.0]**
Operating System: **Linux-4.14.0-2-amd64-x86_64-with-debian-buster-sid**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@7ddf7f5c9814688275aa437aa6834f948f2d3fa7
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_4 :: [7ddf7f5] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument '<methodCall> <methodName>system.listMethods</methodName> <params></params> </methodCall>'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
