### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by jiska78** [SickRage/SickRage#2148]
2016-07-27 14:26:47 Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "/apps/sickrage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/apps/sickrage/sickbeard/webserve.py", line 2290, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/apps/sickrage/sickbeard/processTV.py", line 154, in func_wrapper
    ret = func(*args, **kargs)
  File "/apps/sickrage/sickbeard/processTV.py", line 247, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/apps/sickrage/sickbeard/processTV.py", line 572, in process_media
    result.result = processor.process()
  File "/apps/sickrage/sickbeard/postProcessor.py", line 1040, in process
    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps):  # pylint: disable=protected-access
  File "/apps/sickrage/sickbeard/helpers.py", line 1617, in verify_freespace
    diskfree += ek(os.path.getsize, f.location)
TypeError: coercing to Unicode: need string or buffer, int found

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Cant say much without more info logs, but looks like its an special character that is causing this.
