### ISSUE TITLE
issue with SSL

### ISSUE THREAD

**Issue by FernandoMiguel** [SickRage/SickRage#2152]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master: 570cd207fe00798fb2182b0a90af16c1d936ea83
OS: Ubuntu 14.04
What you did: added Lets Encrypt SSL
from the config.ini
https_key = /home/USER/.getssl/DOMAIN/DOMAIN.key
https_cert = /home/USER/.getssl/DOMAIN/chain.crt

What happened:
when accessing the site with chrome, page fails to load and logs show this
2016-07-28 01:19:41 INFO     TORNADO :: Starting SickRage on https://0.0.0.0:12430/
2016-07-28 01:20:01 WARNING  SSL Error on 13 ('IP', 61558): [Errno 1] _ssl.c:510: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
2016-07-28 01:20:01 ERROR    Uncaught exception
Traceback (most recent call last):
  File "/home/hd1/**************/apps/sickrage/lib/tornado/http1connection.py", line 693, in _server_request_loop
    ret = yield conn.read_response(request_delegate)
  File "/home/hd1/**************/apps/sickrage/lib/tornado/gen.py", line 870, in run
    value = future.result()
  File "/home/hd1/**************/apps/sickrage/lib/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/home/hd1/**************/apps/sickrage/lib/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/hd1/**************/apps/sickrage/lib/tornado/http1connection.py", line 168, in _read_message
    quiet_exceptions=iostream.StreamClosedError)
  File "/home/hd1/**************/apps/sickrage/lib/tornado/gen.py", line 870, in run
    value = future.result()
  File "/home/hd1/**************/apps/sickrage/lib/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SSLError: [Errno 1] _ssl.c:510: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
2016-07-28 01:20:01 WARNING  SSL Error on 13 ('IP', 61559): [Errno 1] _ssl.c:510: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
2016-07-28 01:20:01 ERROR    Uncaught exception
Traceback (most recent call last):
  File "/home/hd1/**************/apps/sickrage/lib/tornado/http1connection.py", line 693, in _server_request_loop
    ret = yield conn.read_response(request_delegate)
  File "/home/hd1/**************/apps/sickrage/lib/tornado/gen.py", line 870, in run
    value = future.result()
  File "/home/hd1/**************/apps/sickrage/lib/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/home/hd1/**************/apps/sickrage/lib/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/hd1/**************/apps/sickrage/lib/tornado/http1connection.py", line 168, in _read_message
    quiet_exceptions=iostream.StreamClosedError)
  File "/home/hd1/**************/apps/sickrage/lib/tornado/gen.py", line 870, in run
    value = future.result()
  File "/home/hd1/**************/apps/sickrage/lib/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SSLError: [Errno 1] _ssl.c:510: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [ ] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duramato** [comment]
Update your python version to > 2.7.10 and/or update your OpenSSL (or any of the forks)
