### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: u'/opt/sickrage/cache/mako/schedule.mako.py'

### ISSUE THREAD

**Issue by Dracozny** [SickRage/SickRage#2174]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@4e8b9eeb3157adb5fcdee67ef68610c0bb65abf4
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [4e8b9ee] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 484, in schedule
    controller="schedule", action="index")
  File "/opt/sickrage/sickbeard/webserve.py", line 160, in render
    kwargs['backtrace'] = RichTraceback()
  File "/opt/sickrage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/opt/sickrage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/opt/sickrage/lib/mako/template.py", line 632, in code
    return util.read_python_file(self.module_filename)
  File "/opt/sickrage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/opt/sickrage/cache/mako/schedule.mako.py'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Dracozny** [comment]
This happened after restarting the server. The Mako directory does not
exist in cache.

**Comment by Dracozny** [comment]
I looked at the log file after sending this report and discovered that
using restart caused a second instance of the server to attempt to start. I
clicked shutdown which shut down the first and that allowed the second to
start without error.

2016-08-03 21:32:16 INFO TORNADO :: Could not start webserver on port
8081, already in use! 2016-08-03 21:32:16 INFO TORNADO :: Starting
SickRage on http://0.0.0.0:8081/ 2016-08-03 21:32:16 INFO MAIN ::
Starting SickRage [master] using '/opt/sickrage/config.ini' 2016-08-03
21:32:16 INFO TORNADO :: Could not start webserver on port 8081,
already in use! 2016-08-03 21:32:16 INFO TORNADO :: Starting SickRage
on http://0.0.0.0:8081/ 2016-08-03 21:32:16 INFO MAIN :: Starting
SickRage [master] using '/opt/sickrage/config.ini' 2016-08-03 21:32:15
INFO TORNADO :: Could not start webserver on port 8081, already in
use! 2016-08-03 21:32:15 INFO TORNADO :: Starting SickRage on
http://0.0.0.0:8081/

the question becomes why did a second instance start?

**Comment by neoatomic** [comment]
This happens when you have 2 instances of sickrage running.
The cache gets removed on a restart, so than this error happens.

However why a second instance did start i cant tell. Might want to check your setup/installation.
There are also some setup guides in the wiki if you need them.
