### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by bwguy** [SickRage/SickRage#2202]
### INFO

Python Version: **2.7.11 (default, Jan  9 2016, 13:51:44) [GCC 4.8.5]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@4e8b9eeb3157adb5fcdee67ef68610c0bb65abf4
No Log available with ERRORS:
### ERROR

```
Thread-30 :: [4e8b9ee] Unable to get error title : 'NoneType' object has no attribute 'group'
```

---

_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by bwguy** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 13:51:44) [GCC 4.8.5]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@4e8b9eeb3157adb5fcdee67ef68610c0bb65abf4
No Log available with ERRORS:
### ERROR
```
Thread-29 :: [4e8b9ee] Unable to get error title : 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by bwguy** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 13:51:44) [GCC 4.8.5]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@4e8b9eeb3157adb5fcdee67ef68610c0bb65abf4
No Log available with ERRORS:
### ERROR
```
Thread-29 :: [4e8b9ee] Unable to get error title : 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by RicardoJ** [comment]
Related to #2141.

**Comment by bwguy** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 13:51:44) [GCC 4.8.5]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@4e8b9eeb3157adb5fcdee67ef68610c0bb65abf4
No Log available with ERRORS:
### ERROR
```
Thread-18 :: [4e8b9ee] Unable to get error title : 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mike19715** [comment]
### INFO
Python Version: **2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by johnvick** [comment]
### INFO
Python Version: **2.7.9 (default, Aug 13 2016, 17:56:53) [GCC 4.9.2]**
Operating System: **Linux-3.10.103+-armv7l-with-debian-8.6**
Locale: ISO8859-1
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by desmonio** [comment]
### INFO
Python Version: **2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]**
Operating System: **Darwin-13.4.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by desmonio** [comment]
### INFO
Python Version: **2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]**
Operating System: **Darwin-13.4.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-300835 :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ncl2fth** [comment]
### INFO
Python Version: **2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-38-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-250487 :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ncl2fth** [comment]
### INFO
Python Version: **2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-38-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ncl2fth** [comment]
### INFO
Python Version: **2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-38-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ncl2fth** [comment]
### INFO
Python Version: **2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-38-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [BitSnoop] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by pr0fetul** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.23-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by pramoino** [comment]
### INFO
Python Version: **2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-38-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-152831 :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ChromevoidGit** [comment]
### INFO
Python Version: **2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-298474 :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ChromevoidGit** [comment]
### INFO
Python Version: **2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Thanatosgratus** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.4.0-24-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Thanatosgratus** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.4.0-24-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-72762 :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Thanatosgratus** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.4.0-24-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-250071 :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Thanatosgratus** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.4.0-24-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-308045 :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Thanatosgratus** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.4.0-24-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-283468 :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by zapru** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 11:15:51) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-247808 :: [BitSnoop] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by trancen** [comment]
### INFO
Python Version: **2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]**
Operating System: **Linux-2.6.32-042stab108.8-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-307341 :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by trancen** [comment]
### INFO
Python Version: **2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]**
Operating System: **Linux-2.6.32-042stab108.8-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-295557 :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tenderjackson** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tenderjackson** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by krash1220** [comment]
### INFO
Python Version: **2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-38-generic-x86_64-with-LinuxMint-18-sarah**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by elvenpath** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 11:15:51) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by elvenpath** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 11:15:51) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-269533 :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by elvenpath** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 11:15:51) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295829 :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by elvenpath** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 11:15:51) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-289590 :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by elvenpath** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 11:15:51) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295515 :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by elvenpath** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 11:15:51) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-272644 :: [TorrentProject] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by elvenpath** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 11:15:51) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-272644 :: [BitSnoop] :: [dc765c9] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by studio-es-lee** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  5 2016, 18:57:05) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@fc59f23c105551f513fc78757f9636a8a5d08b15
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [fc59f23] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by studio-es-lee** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  5 2016, 18:57:05) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@fc59f23c105551f513fc78757f9636a8a5d08b15
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [TorrentProject] :: [fc59f23] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ezar** [comment]
### INFO
Python Version: **2.7.12+ (default, Sep  1 2016, 20:27:38) [GCC 6.1.1 20160802]**
Operating System: **Linux-4.4.23-v7+-armv7l-with-debian-stretch-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@fc59f23c105551f513fc78757f9636a8a5d08b15
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [fc59f23] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Spyd05** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.13-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@fc59f23c105551f513fc78757f9636a8a5d08b15
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-153021 :: [TorrentProject] :: [fc59f23] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Spyd05** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.13-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@fc59f23c105551f513fc78757f9636a8a5d08b15
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-268592 :: [TorrentProject] :: [fc59f23] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Thanatosgratus** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.4.0-24-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@fc59f23c105551f513fc78757f9636a8a5d08b15
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [fc59f23] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by krash1220** [comment]
### INFO
Python Version: **2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-38-generic-x86_64-with-LinuxMint-18-sarah**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6a023791556047f7ce04cd6b5185d41ed212bd84
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [6a02379] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by trancen** [comment]
### INFO
Python Version: **2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]**
Operating System: **Linux-2.6.32-042stab108.8-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@6a023791556047f7ce04cd6b5185d41ed212bd84
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-141181 :: [TorrentProject] :: [6a02379] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by trancen** [comment]
### INFO
Python Version: **2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]**
Operating System: **Linux-2.6.32-042stab108.8-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@6a023791556047f7ce04cd6b5185d41ed212bd84
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-273761 :: [TorrentProject] :: [6a02379] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by trancen** [comment]
### INFO
Python Version: **2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]**
Operating System: **Linux-2.6.32-042stab108.8-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@6a023791556047f7ce04cd6b5185d41ed212bd84
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-307341 :: [TorrentProject] :: [6a02379] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by trancen** [comment]
### INFO
Python Version: **2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]**
Operating System: **Linux-2.6.32-042stab108.8-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@6a023791556047f7ce04cd6b5185d41ed212bd84
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-295557 :: [TorrentProject] :: [6a02379] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by trancen** [comment]
### INFO
Python Version: **2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]**
Operating System: **Linux-2.6.32-042stab108.8-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@6a023791556047f7ce04cd6b5185d41ed212bd84
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-283215 :: [TorrentProject] :: [6a02379] Request failed: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MGaetan89** [comment]
I'm still facing this issue with the latest version of SickRage:
> SickRage Info:
> -  Branch: [master](https://github.com/SickRage/SickRage/tree/master)
> - Commit: https://github.com/SickRage/SickRage/commit/7e6e0575542c3f3e5476663532b1357f3ae1e902
> - Version: [v2017.02.2-1](https://github.com/SickRage/SickRage/releases/tag/v2017.02.2-1)
>
> Database Version: 44.0
> Python Version: 2.7.13 (default, Dec 18 2016, 23:11:11) [GCC 4.6.4]
> SSL Version: OpenSSL 1.0.2j 26 Sep 2016
> OS: Linux-3.2.40-armv7l-with-glibc2.4
> Locale: None.None

Here is the associated exception:
```
2017-02-11 15:13:56 INFO SEARCHQUEUE-MANUAL-258171 :: [ExtraTorrent] :: Performing episode search for Continuum
AA 
AA AttributeError: 'NoneType' object has no attribute 'group'
AA raise requests_exception
AA File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/helpers.py", line 1433, in handle_requests_exception
AA AttributeError: 'NoneType' object has no attribute 'group'
AA raise requests_exception
AA File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/helpers.py", line 1433, in handle_requests_exception
AA Traceback (most recent call last):
```

**Comment by sharkykh** [comment]
Fixed in https://github.com/SickRage/SickRage/commit/fbb90794c2564b7bebfd2c0d9f691510d42748cc
