### ISSUE TITLE
[APP SUBMITTED]: need more than 1 value to unpack

### ISSUE THREAD

**Issue by Kiggerbare** [SickRage/SickRage#2203]
### INFO
Python Version: **2.7.10 (default, Sep 13 2015, 09:57:10) [GCC 4.7.2]**
Operating System: **Linux-3.10.101.2-x86_64-with-glibc2.3**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4e8b9eeb3157adb5fcdee67ef68610c0bb65abf4
No Log available with ERRORS:
### ERROR
```
SHOWUPDATER :: [4e8b9ee] Exception generated in thread SHOWUPDATER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by bwguy** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 13:51:44) [GCC 4.8.5]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@4e8b9eeb3157adb5fcdee67ef68610c0bb65abf4
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [4e8b9ee] Failed Unrar archive 54df86b27521156.rar: Invalid Rar Archive
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by jupiler** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 21 2016, 17:01:39) [GCC 4.9.3]**
Operating System: **Linux-4.4.6-gentoo-CYBERIA-x86_64-AMD_Phenom-tm-_II_X6_1055T_Processor-with-gentoo-2.2**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@d15b7003f8663b76d01fcbf0566389b2f31e0564
No Log available with ERRORS:
### ERROR
```
SHOWUPDATER :: [d15b700] Exception generated in thread SHOWUPDATER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mattail** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b3dad8eec3e238b1cadc809acf8e0e26deb9eb3
No Log available with ERRORS:
### ERROR
```
SHOWUPDATER :: [4b3dad8] Exception generated in thread SHOWUPDATER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tcatut** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
No Log available with ERRORS:
### ERROR
```
SHOWUPDATER :: [5bc5c3a] Exception generated in thread SHOWUPDATER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tcatut** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
No Log available with ERRORS:
### ERROR
```
SHOWUPDATER :: [5bc5c3a] Exception generated in thread SHOWUPDATER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tcatut** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
No Log available with ERRORS:
### ERROR
```
SHOWUPDATER :: [5bc5c3a] Exception generated in thread SHOWUPDATER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tcatut** [comment]
This issue causes the "Show Update" thread to stop working, and seems to be happening around the same time every night.  Restarting SickRage will resolve the issue for a while, but then it happens again after a day or two.

Here's the traceback, since I didn't see it here.

2018-02-12 03:37:00 ERROR    SHOWUPDATER :: [f30a844] Exception generated in thread SHOWUPDATER: need more than 1 value to unpack
Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/scheduler.py", line 109, in run
    self.action.run(self.force)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/showUpdater.py", line 62, in run
    network_timezones.update_network_dict()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/network_timezones.py", line 58, in update_network_dict
    (key, val) = line.strip().rsplit(':', 1)
ValueError: need more than 1 value to unpack

**Comment by tcatut** [comment]
I may have found a work around for this issue on my end.  However, maybe additional information might be beneficial to you for development?

After looking at the code I realized that its just not downloading "http://sickrage.github.io/sb_network_timezones/network_timezones.txt" properly.  Turns out, pfBlockerNG, specifically DNSBL, is blocking your github.io site under my current firewall settings.  I added an exception for the github.io domain and now I'm able to access the file on my network.  I will have to wait and see, but I'm willing to bet this fixes the SickRage issue.

**Comment by dwightturner36** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.1-STABLE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@fa36303a1f48e9862729b0f1a74f83de81bc2522
Link to Log: https://gist.github.com/56373382c687f738aafb271f0c2cd4c2
### ERROR
```
SHOWUPDATER :: [fa36303] Exception generated in thread SHOWUPDATER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Snowaks** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@c0e676570fbffe964c57e8e089b8cab7b4b2f668
No Log available with ERRORS:
### ERROR
```
SHOWUPDATER :: [c0e6765] Exception generated in thread SHOWUPDATER: need more than 1 value to unpack
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
