### ISSUE TITLE
Empty show gives "list index out of range"

### ISSUE THREAD

**Issue by Arcanemagus** [SickRage/SickRage#2204]
### What you did:

I attempted to load a show information for a show ([Class (2016)](http://www.imdb.com/title/tt5079788/)) with no seasons/episodes currently listed.

### What happened:

The page showed the diagnostic information below, with an entry put in the logs.

Note that it looks like @rishitank is experiencing something similar in https://github.com/SickRage/SickRage/issues/1621#issuecomment-239246662, but as that issue is related to the HDSpace provider it's not the same problem.

Note that Sickrage shows no episodes, while IMDb shows 8, I'm not sure what thetvdb shows, as this show is rather hard to search for specifically.

### What you expected:

No error, and the show information to show.

### Logs

Web page error:

```
Error

list index out of range

Traceback

Traceback (most recent call last): 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tornado/web.py", line 1415, in _execute result = yield result 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tornado/gen.py", line 870, in run value = future.result() 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tornado/concurrent.py", line 215, in result raise_exc_info(self._exc_info) 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tornado/gen.py", line 876, in run yielded = self.gen.throw(*exc_info) 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 254, in get results = yield self.async_call(method) 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tornado/gen.py", line 870, in run value = future.result() 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 270, in async_call result = function(**kwargs) 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 1267, in displayShow if int(seasonResults[-1]["season"]) == 0: 
IndexError: list index out of range 

Request Info

body: 
files: {}
protocol: https
connection: 
body_arguments: {}
uri: /home/displayShow?show=309893
query_arguments: {'show': ['309893']}
_start_time: 1470950549.24
headers: {'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2824.0 Safari/537.36', 'Host': 'sickrage.domain.tld:8081', 'Referer': 'https://sickrage.domain.tld:8081/home/', 'Cookie': '_ga=GA1.2.659509415.1417064505; sickrage_user="2|1:0|10:1485601742|13:sickrage_user|44:MjVlYjgyZjdkNmRmMjRjNWI5YjdmYzM1MzY0ZjJhNTQ=|4f39996f866b60090cbf4b231feb082b3a6711a66ac159cbdca066d7d5c6a743"', 'Upgrade-Insecure-Requests': '1'}
host: sickrage.domain.tld:8081
version: HTTP/1.1
arguments: {'show': '309893'}
_finish_time: None
query: show=309893
path: /home/displayShow
_cookies: Set-Cookie: _ga=GA1.2.659509415.1417064505 Set-Cookie: sickrage_user="2|1:0|10:1485601742|13:sickrage_user|44:MjVlYjgyZjdkNmRmMjRjNWI5YjdmYzM1MzY0ZjJhNTQ=|4f39996f866b60090cbf4b231feb082b3a6711a66ac159cbdca066d7d5c6a743"
method: GET
remote_ip: 203.0.113.1
```

SickRage log:

```
2016-08-11 14:21:55 Thread-16 :: [4e8b9ee] Failed doing webui callback: Traceback (most recent call last):
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 270, in async_call
result = function(**kwargs)
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 1267, in displayShow
if int(seasonResults[-1]["season"]) == 0:
IndexError: list index out of range
```

### System Information

Branch: master
Commit: 4e8b9eeb3157adb5fcdee67ef68610c0bb65abf4
Version: 2016.07.31-1
Database Version: 44.0
OS: FreeBSD-10.3-RELEASE-amd64-64bit-ELF
Python Version: 2.7.9 (default, Sep 9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]
SSL Version: OpenSSL 1.0.2d 9 Jul 2015
Locale: en_US.UTF-8

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Arcanemagus** [comment]
Looks like @zither911 is also hitting this bug, and the auto-submit is sticking it on the other issue.

**Comment by Arcanemagus** [comment]
@SickRage/owners @SickRage/moderators it looks like several more people are hitting this and getting sent over to that dead thread because the error title is the same.

Is there any further information you need?

**Comment by Arcanemagus** [comment]
List of users hitting this bug and getting lumped into #1621 by the auto-submit:

* @rishitank [here](https://github.com/SickRage/SickRage/issues/1621#issuecomment-239246662)
* @zither911 [here](https://github.com/SickRage/SickRage/issues/1621#issuecomment-239453615) + 1
* @ghost [here](https://github.com/SickRage/SickRage/issues/1621#issuecomment-239453615) + 2
* @alyzze [here](https://github.com/SickRage/SickRage/issues/1621#issuecomment-239653566) + 5
* @vlsoft [here](https://github.com/SickRage/SickRage/issues/1621#issuecomment-239666610) + 1
* @the-buzz-man [here](https://github.com/SickRage/SickRage/issues/1621#issuecomment-239706544)
* @NicolasDWolfwood [here](https://github.com/SickRage/SickRage/issues/1621#issuecomment-240362725)
* @dirkr07 [here](https://github.com/SickRage/SickRage/issues/1621#issuecomment-240543881)
* @quindarious-gooch [here](https://github.com/SickRage/SickRage/issues/1621#issuecomment-241235975) + 1
* @Yellow1144 [here](https://github.com/SickRage/SickRage/issues/1621#issuecomment-241445560) + 1
* @HitmanThe47 [here](https://github.com/SickRage/SickRage/issues/1621#issuecomment-242142782)

**Comment by miigotu** [comment]
They are submitted in 1621 because thats where it belongs.
