### ISSUE TITLE
[APP SUBMITTED]: [Errno 5] Input/output error: '/c/.sickrage/config/cache/images/277928.banner.jpg'

### ISSUE THREAD

**Issue by devenashani** [SickRage/SickRage#2208]
### INFO
Python Version: **2.7.10 (default, Mar  8 2016, 02:40:45) [GCC 4.4.5]**
Operating System: **Linux-2.6.31.8.nv+v2-armv5tel-with-debian-6.0.3**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4e8b9eeb3157adb5fcdee67ef68610c0bb65abf4
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [4e8b9ee] Unable to write image to /c/.sickrage/config/cache/images/277928.banner.jpg - are you sure the show folder is writable? error 5 : Input/output error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by bwguy** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 13:51:44) [GCC 4.8.5]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@4e8b9eeb3157adb5fcdee67ef68610c0bb65abf4
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [4e8b9ee] Failed Unrar archive 54df86b27521156.rar: Invalid Rar Archive
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by johnvick** [comment]
### INFO
Python Version: **2.7.9 (default, Aug 13 2016, 17:56:53) [GCC 4.9.2]**
Operating System: **Linux-3.10.103+-armv7l-with-debian-8.6**
Locale: ISO8859-1
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
Thread-17 :: [dc765c9] [Errno 5] Input/output error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by johnvick** [comment]
### INFO
Python Version: **2.7.9 (default, Aug 13 2016, 17:56:53) [GCC 4.9.2]**
Operating System: **Linux-3.10.103+-armv7l-with-debian-8.6**
Locale: ISO8859-1
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [dc765c9] [Errno 5] Input/output error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by wah0808** [comment]
### INFO
Python Version: **2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.13.0-37-generic-x86_64-with-LinuxMint-18.3-sylvia**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@c0e676570fbffe964c57e8e089b8cab7b4b2f668
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [c0e6765] Failed doing webui callback: Traceback (most recent call last):
  File "/home/alan/SickChill/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/home/alan/SickChill/sickbeard/webserve.py", line 4764, in saveProviders
    print (ratio)
IOError: [Errno 5] Input/output error

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-88-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@61ac4b20de6f8d96ebf9e6e6a1faf6f83e43a73f
Link to Log: https://gist.github.com/cc4a0a69b61bce64639776496b7487ff
### ERROR
```
WEBSERVER-CONFIGPROVIDERS :: [61ac4b2] Failed doing webui callback: Traceback (most recent call last):
  File "/home/kevin/.sickrage/sickchill/views/index.py", line 213, in async_call
    result = function(**kwargs)
  File "/home/kevin/.sickrage/sickchill/views/config/providers.py", line 273, in saveProviders
    print (ratio)
IOError: [Errno 5] Input/output error

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
