### ISSUE TITLE
Error when checking for software updates

### ISSUE THREAD

**Issue by jjlawren** [SickRage/SickRage#2222]
*Branch/Commit*: master/4e8b9eeb3157adb5fcdee67ef68610c0bb65abf4
*OS*: SmartOS (Solaris-ish)
*What you did*: Tools dropdown --> Check for updates
*What happened*: Python exception thrown

Note: If I shut down SickBeard and restart manually, the update checks begin to work again. However, after a day or two this problem always reappears.

Logs:
```
Error

argument of type 'NoneType' is not iterable

Traceback

Traceback (most recent call last): 
File "/home/user/SickRage/lib/tornado/web.py", line 1415, in _execute result = yield result 
File "/home/user/SickRage/lib/tornado/gen.py", line 870, in run value = future.result() 
File "/home/user/SickRage/lib/tornado/concurrent.py", line 215, in result raise_exc_info(self._exc_info) 
File "/home/user/SickRage/lib/tornado/gen.py", line 876, in run yielded = self.gen.throw(*exc_info) 
File "/home/user/SickRage/sickbeard/webserve.py", line 254, in get results = yield self.async_call(method) 
File "/home/user/SickRage/lib/tornado/gen.py", line 870, in run value = future.result() 
File "/home/user/SickRage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/home/user/SickRage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/home/user/SickRage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/home/user/SickRage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/home/user/SickRage/sickbeard/webserve.py", line 270, in async_call result = function(**kwargs) 
File "/home/user/SickRage/sickbeard/webserve.py", line 1142, in updateCheck sickbeard.versionCheckScheduler.action.check_for_new_version(force=True) 
File "/home/user/SickRage/sickbeard/versionChecker.py", line 269, in check_for_new_version if not self.updater.need_update(): 
File "/home/user/SickRage/sickbeard/versionChecker.py", line 586, in need_update if self.branch != self._find_installed_branch(): 
File "/home/user/SickRage/sickbeard/versionChecker.py", line 499, in _find_installed_branch branch_info, errors_, exit_status = self._run_git(self._git_path, 'symbolic-ref -q HEAD') # @UnusedVariable
File "/home/user/SickRage/sickbeard/versionChecker.py", line 460, in _run_git if 'stash' in output: 
TypeError: argument of type 'NoneType' is not iterable 
 ```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
You could try to shutdown sickrage, and remove the cache folder (except images) and restart.
If not, than do a fresh install. There are also some guides in the Wiki that might help setting it up.
