### ISSUE TITLE
int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by alienx2** [SickRage/SickRage#2236]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master / 50e350eeb9ae6e0d8f26cff569e5ad85c991a863
OS: Linux-2.6.36.4brcmarm-armv7l-with-glibc2.4
What you did: Manual Post-Processing
What happened: It went error page with debug.
What you expected: It need move all finished download to library.
Logs:
```
2016-08-21 13:58:05 Thread-13 :: [50e350e] Traceback (most recent call last): File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/logger.py", line 366, in submit_errors for report in reports: File "/opt/etc/sickrage/lib/github/PaginatedList.py", line 48, in __iter__ newElements = self._grow() File "/opt/etc/sickrage/lib/github/PaginatedList.py", line 60, in _grow newElements = self._fetchNextPage() File "/opt/etc/sickrage/lib/github/PaginatedList.py", line 161, in _fetchNextPage headers=self.__headers File "/opt/etc/sickrage/lib/github/Requester.py", line 171, in requestJsonAndCheck return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx)) File "/opt/etc/sickrage/lib/github/Requester.py", line 212, in requestJson return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode) File "/opt/etc/sickrage/lib/github/Requester.py", line 251, in __requestEncode status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input) File "/opt/etc/sickrage/lib/github/Requester.py", line 275, in __requestRaw requestHeaders File "/opt/lib/python2.7/httplib.py", line 1057, in request self._send_request(method, url, body, headers) File "/opt/lib/python2.7/httplib.py", line 1097, in _send_request self.endheaders(body) File "/opt/lib/python2.7/httplib.py", line 1053, in endheaders self._send_output(message_body) File "/opt/lib/python2.7/httplib.py", line 897, in _send_output self.send(msg) File "/opt/lib/python2.7/httplib.py", line 859, in send self.connect() File "/opt/lib/python2.7/httplib.py", line 1270, in connect HTTPConnection.connect(self) File "/opt/lib/python2.7/httplib.py", line 836, in connect self.timeout, self.source_address) File "/opt/lib/python2.7/socket.py", line 557, in create_connection for res in getaddrinfo(host, port, 0, SOCK_STREAM): gaierror: [Errno -3] Temporary failure in name resolution  2016-08-21 13:56:07 Thread-13 :: [50e350e] Failed doing webui callback: Traceback (most recent call last): File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/webserve.py", line 270, in async_call result = function(**kwargs) File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/webserve.py", line 2290, in processEpisode is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/processTV.py", line 290, in processDir process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result) File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/processTV.py", line 560, in process_media result.result = processor.process() File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/postProcessor.py", line 1131, in process proper_path = ep_obj.proper_path() File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/tv.py", line 2356, in proper_path result = self.formatted_filename(anime_type=anime_type) File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/tv.py", line 2411, in formatted_filename return sanitize_filename(self._format_pattern(name_groups[-1], multi, anime_type)) File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/tv.py", line 2199, in _format_pattern replace_map = self._replace_map() File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/tv.py", line 2141, in _replace_map '%0E': '{0:02d}'.format(int(self.episode)), TypeError: int() argument must be a string or a number, not 'NoneType'  2016-08-21 13:36:32 POSTPROCESSER :: [50e350e] Exception generated in thread POSTPROCESSER: int() argument must be a string or a number, not 'NoneType'
```
```
Error

int() argument must be a string or a number, not 'NoneType'

Traceback

Traceback (most recent call last): 
File "/opt/etc/sickrage/lib/tornado/web.py", line 1415, in _execute result = yield result 
File "/opt/etc/sickrage/lib/tornado/gen.py", line 870, in run value = future.result() 
File "/opt/etc/sickrage/lib/tornado/concurrent.py", line 215, in result raise_exc_info(self._exc_info) 
File "/opt/etc/sickrage/lib/tornado/gen.py", line 876, in run yielded = self.gen.throw(*exc_info) 
File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/webserve.py", line 254, in get results = yield self.async_call(method) 
File "/opt/etc/sickrage/lib/tornado/gen.py", line 870, in run value = future.result() 
File "/opt/etc/sickrage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/opt/etc/sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/opt/etc/sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/opt/etc/sickrage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/webserve.py", line 270, in async_call result = function(**kwargs) 
File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/webserve.py", line 2290, in processEpisode is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type 
File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/processTV.py", line 290, in processDir process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result) 
File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/processTV.py", line 560, in process_media result.result = processor.process() 
File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/postProcessor.py", line 1131, in process proper_path = ep_obj.proper_path() 
File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/tv.py", line 2356, in proper_path result = self.formatted_filename(anime_type=anime_type) 
File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/tv.py", line 2411, in formatted_filename return sanitize_filename(self._format_pattern(name_groups[-1], multi, anime_type)) 
File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/tv.py", line 2199, in _format_pattern replace_map = self._replace_map() 
File "/tmp/mnt/TOSHIBA/entware-ng.arm/etc/sickrage/sickbeard/tv.py", line 2141, in _replace_map '%0E': '{0:02d}'.format(int(self.episode)), 
TypeError: int() argument must be a string or a number, not 'NoneType' 

Request Info

body: proc_dir=%2Fmnt%2FSADownload%2FDownload%2FTorrent%2FComplete&process_method=move&force=on&is_priority=on
files: {}
protocol: http
connection: 
body_arguments: {'is_priority': ['on'], 'proc_dir': ['/mnt/SADownload/Download/Torrent/Complete'], 'force': ['on'], 'process_method': ['move']}
uri: /home/postprocess/processEpisode
query_arguments: {}
_start_time: 1471759487.35
headers: {'Origin': 'http://192.168.2.1:8081', 'Content-Length': '104', 'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7.2 (KHTML, like Gecko) FluidApp Version/2156 Safari/601.2.7.2', 'Host': '192.168.2.1:8081', 'Cookie': 'advanced_toggle_checked=1; beaker.session.id=ee7cac8df4d4281f468d637e6040c75c; blu_ray_com_new_releases_view=thumb; dm_enable=no; dm_install=no; hwaddr=74:D0:2B:87:E1:F0; imdb_box_office_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_top_250_movies_view=thumb; late_view=list; manage_view=thumb; snatched_view=list; soon_view=thumb; suggest_view=thumb; traffic_warning_0=2016.6:1; wanted_view=list', 'Referer': 'http://192.168.2.1:8081/home/postprocess/', 'Content-Type': 'application/x-www-form-urlencoded'}
host: 192.168.2.1:8081
version: HTTP/1.1
arguments: {'is_priority': 'on', 'force': 'on', 'proc_dir': '/mnt/SADownload/Download/Torrent/Complete', 'process_method': 'move'}
_finish_time: None
query: 
path: /home/postprocess/processEpisode
method: POST
remote_ip: 192.168.2.102
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by alienx2** [comment]
now back to working after updated.

**Comment by alienx2** [comment]
It happen again when manual post-processing...

**Comment by neoatomic** [comment]
Are you renaming folders/files when manually post processing.? Or symlink/hard-linking.?
Also are you sure the mount is setup correctly.?

**Comment by miigotu** [comment]
The file it was processing doesnt have an episode number in the name.

**Comment by Pakoach** [comment]
Hello,

I think I got the same issue when auto post processing an anime episode which was named episode 00 (while actually it should be 01). So I guess it falls in the category @miigotu was referring to: a file without episode number.
In my case the issue is not that it cannot post process the episode automatically (it is a corner case so it's fine if I have to take care about it manually). The issue is more that the auto post processing crashes and thus the other episodes are not post processed. I think detecting the issue and throwing an error would be a better solution.

Here is the log:

```
AA TypeError: int() argument must be a string or a number, not 'NoneType'
AA '%0E': '{0:02d}'.format(int(self.e**sode)),
AA File "/home/sickrage/sickbeard/tv.py", line 2140, in _replace_map
AA replace_map = self._replace_map()
AA File "/home/sickrage/sickbeard/tv.py", line 2198, in _format_pattern
AA return sanitize_filename(self._format_pattern(name_groups[-1], multi, anime_type))
AA File "/home/sickrage/sickbeard/tv.py", line 2410, in formatted_filename
AA result = self.formatted_filename(anime_type=anime_type)
AA File "/home/sickrage/sickbeard/tv.py", line 2355, in proper_path
AA proper_path = ep_obj.proper_path()
AA File "/home/sickrage/sickbeard/postProcessor.py", line 1129, in process
AA result.result = processor.process()
AA File "/home/sickrage/sickbeard/processTV.py", line 500, in process_media
AA process_media(current_directory, video_files, release_name, process_method, force, is_priority, result)
AA File "/home/sickrage/sickbeard/processTV.py", line 198, in process_dir
AA mode=self.mode
AA File "/home/sickrage/sickbeard/post_processing_queue.py", line 225, in run
2017-12-03 10:46:45 INFO POSTPROCESSOR-AUTO :: Processing /volume1/Download Station/BT/Snatch/Fate Stay Night - Unlimited Blade Works/[Anonimu-Fansubu] Fate Stay Night - Unlimited Blade Works - 00 [1080p] [V2].mp4 (None)
2017-12-03 10:46:39 INFO POSTPROCESSOR-AUTO :: Processing /volume1/Download Station/BT/Snatch
```

SickRage Info:
Branch: master
Commit: d8c2613583ce8b321a5adc9ff70c52e830f224a8
Version: v2017.06.05-1
Database Version: 44.0


It is the first time I post an issue so please let me know if you need anything more or if I need to open a new issue. I thought this was related but maybe you prefer a new one.

If it can help I can try to solve the issue and propose you a fix?
