### ISSUE TITLE
[APP SUBMITTED]: Parsing failed with several errors.
First error at line 992.

### ISSUE THREAD

**Issue by yongbi85** [SickRage/SickRage#2268]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@75042d8c406bb4356d88b6b67a73c847a56ce3f3
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [75042d8] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 3658, in index
    sickbeard.save_config()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 1661, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8')
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/configobj.py", line 1302, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 992.

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by yongbi85** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@75042d8c406bb4356d88b6b67a73c847a56ce3f3
No Log available with ERRORS:
### ERROR
```
EVENT-QUEUE :: [75042d8] Exception generated in thread EVENT-QUEUE: Parsing failed with several errors.
First error at line 992.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by yongbi85** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@75042d8c406bb4356d88b6b67a73c847a56ce3f3
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [75042d8] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 3658, in index
    sickbeard.save_config()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 1661, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8')
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/configobj.py", line 1302, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 992.

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by yongbi85** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@75042d8c406bb4356d88b6b67a73c847a56ce3f3
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [75042d8] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 3658, in index
    sickbeard.save_config()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 1661, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8')
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/configobj.py", line 1302, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 992.

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by yongbi85** [comment]
Sorry it was lagging badly on the page, didn't mean to spamm the bug, anyway for information it prevents me from opening the history page since the latest update

**Comment by neoatomic** [comment]
Do you recall with what action this problem started.?  And do you have any shows that contain special characters in there name.?

**Comment by yongbi85** [comment]
Well sickrage isn't starting anymore on my synology, i tryed downloading it again and restoring db ad config.ini, but it seems the config.ini prevents it from starting. Do you where can i find a log on synology that would state why a pakcage fails to start ?

**Comment by yongbi85** [comment]
You can close this thread, i restored the db but remade all the config manually and it's working fine again, no idea what happened but the current commit isn't at fault
