### ISSUE TITLE
TNTVillage Provider

### ISSUE THREAD

**Issue by usulbz** [SickRage/SickRage#2272]
Hi everybody. This is what happens using TNTVillage Provider.

### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Windows 10
What you did: I put as "wanted" some episodes
What happened: nothing, just the error below
What you expected: to have the episodes queued correctly
Logs:
```
016-08-30 15:25:56 SEARCHQUEUE-BACKLOG-70865 :: [TNTVillage] :: [75042d8] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\providers\tntvillage.py", line 376, in search
    if self._is_season_pack(title):
  File "C:\SickRage\SickRage\sickbeard\providers\tntvillage.py", line 263, in _is_season_pack
    parse_result = NameParser(tryIndexers=True).parse(name)
  File "C:\SickRage\SickRage\sickbeard\name_parser\parser.py", line 461, in parse
    name, file_name_result or dir_name_result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\x92' in position 23: character maps to 
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
https://github.com/SickRage/SickRage/wiki/FAQ's-and-Fixes#what-are-unicode-errors
