### ISSUE TITLE
Post Processing error

### ISSUE THREAD

**Issue by piluc88** [SickRage/SickRage#2286]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Ubuntu 16.04
What you did: Manual Post Processing
What happened: Can not post processing 
What you expected: 
Logs:
```
2016-09-02 14:38:46 Thread-14 :: [4219585] Failed doing webui callback: Traceback (most recent call last): File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call result = function(**kwargs) File "/opt/sickrage/sickbeard/webserve.py", line 2298, in processEpisode is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type File "/opt/sickrage/sickbeard/processTV.py", line 251, in processDir for curDir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]: File "/opt/sickrage/sickbeard/processTV.py", line 387, in validateDir videoFiles = [x for x in allFiles if helpers.isMediaFile(x)] File "/opt/sickrage/sickbeard/helpers.py", line 192, in isMediaFile if filename.startswith('._'): File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode return codecs.utf_8_decode(input, errors, True) UnicodeDecodeError: 'utf8' codec can't decode byte 0xc9 in position 0: invalid continuation byte
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by piluc88** [comment]
Error

'utf8' codec can't decode byte 0xc9 in position 0: invalid continuation byte

Traceback

Traceback (most recent call last): 
File "/opt/sickrage/lib/tornado/web.py", line 1415, in _execute result = yield result 
File "/opt/sickrage/lib/tornado/gen.py", line 870, in run value = future.result() 
File "/opt/sickrage/lib/tornado/concurrent.py", line 215, in result raise_exc_info(self._exc_info) 
File "/opt/sickrage/lib/tornado/gen.py", line 876, in run yielded = self.gen.throw(*exc_info) 
File "/opt/sickrage/sickbeard/webserve.py", line 254, in get results = yield self.async_call(method) 
File "/opt/sickrage/lib/tornado/gen.py", line 870, in run value = future.result() 
File "/opt/sickrage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/opt/sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/opt/sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/opt/sickrage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call result = function(**kwargs) 
File "/opt/sickrage/sickbeard/webserve.py", line 2298, in processEpisode is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type 
File "/opt/sickrage/sickbeard/processTV.py", line 251, in processDir for curDir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]: 
File "/opt/sickrage/sickbeard/processTV.py", line 387, in validateDir videoFiles = [x for x in allFiles if helpers.isMediaFile(x)] 
File "/opt/sickrage/sickbeard/helpers.py", line 192, in isMediaFile if filename.startswith('._'): 
File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode return codecs.utf_8_decode(input, errors, True) 
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc9 in position 0: invalid continuation byte 

Request Info

body: proc_dir=%2Fhome%2Fsb%2Fdata%2Ftorrents&process_method=copy
files: {}
protocol: https
connection: 
body_arguments: {'proc_dir': ['/home/sb/data/torrents'], 'process_method': ['copy']}
uri: /home/postprocess/processEpisode
query_arguments: {}
_start_time: 1472841807.39
headers: {'Origin': 'https://sb01.hebergement-qc.com:8081', 'Content-Length': '59', 'Accept-Language': 'en-US,en;q=0.8,fr-CA;q=0.6,fr;q=0.4', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Host': 'sb01.hebergement-qc.com:8081', 'Referer': 'https://sb01.hebergement-qc.com:8081/home/postprocess/', 'Cache-Control': 'max-age=0', 'Cookie': 'user="2|1:0|10:1471963351|4:user|44:YTY1NzAyOGU2M2I5NGNlYmE2NjYxM2JlZWMwODE0OTI=|ca98ae9223d8ac63dca3411686f3c6c31370b658b4edbdf213868e6b821a6e1a"; ACEGI_SECURITY_HASHED_REMEMBER_ME_COOKIE=YWRtaW46MTUwMzk1NjU4NDc2NDo1MWRhODY3YTY2MmI5YjgyZDk4MDAwYTBlZjViOWYzYw==; player-61646d696e=1; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; wanted_view=thumb; _ga=GA1.2.569604646.1470667259; PHPSESSID=61mkj48ktgr8e7gju748f1oo10', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded'}
host: sb01.hebergement-qc.com:8081
version: HTTP/1.1
arguments: {'proc_dir': '/home/sb/data/torrents', 'process_method': 'copy'}
_finish_time: None
query: 
path: /home/postprocess/processEpisode
method: POST
remote_ip: 69.67.13.10

**Comment by neoatomic** [comment]
Check your locale. it needs to be utf-8.

https://github.com/SickRage/SickRage/wiki/FAQ's-and-Fixes#what-are-unicode-errors

**Comment by piluc88** [comment]
i set utf-8 and same error

**Comment by jordan8037310** [comment]
Related: https://github.com/SickRage/SickRage/issues/1303
