### ISSUE TITLE
[APP SUBMITTED]: 'module' object has no attribute 'SLACK_NOTIFY_SUBTITLEDOWNLOAD'

### ISSUE THREAD

**Issue by mughoj** [SickRage/SickRage#2287]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4219585709dc1d9ed23ec7ea773a51e92c97b7b5
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [4219585] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2298, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "/opt/sickrage/sickbeard/processTV.py", line 290, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/opt/sickrage/sickbeard/processTV.py", line 560, in process_media
    result.result = processor.process()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 1194, in process
    cur_ep.download_subtitles(force=True)
  File "/opt/sickrage/sickbeard/tv.py", line 1428, in download_subtitles
    notifiers.notify_subtitle_download(self.prettyName(), subtitle_list)
  File "/opt/sickrage/sickbeard/notifiers/__init__.py", line 89, in notify_subtitle_download
    n.notify_subtitle_download(ep_name, lang)
  File "/opt/sickrage/sickbeard/notifiers/slack.py", line 39, in notify_subtitle_download
    if sickbeard.SLACK_NOTIFY_SUBTITLEDOWNLOAD:
AttributeError: 'module' object has no attribute 'SLACK_NOTIFY_SUBTITLEDOWNLOAD'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by mathewcalvin** [comment]
Seconded.
Commit: 4218585
OS: Win 10 x64
Branch: Origin/Master
Problem on postprocessing, crashes automated post processing service as well
Symptoms: returns "Oops 404 error" page
Troubleshooting: Git hard reset and pull.

Gist below with debug logs
<script src="https://gist.github.com/mathewcalvin/6fb42ba0d2f596c978177003739e846f.js"></script>

**Comment by mathewcalvin** [comment]
@mughoj 
As noted in the logs, this seems to be some sort of subtitle related error.  I disabled "search subtitles" in options and post processing works again.

**Comment by klamouri** [comment]
### INFO
Python Version: **2.7.12 (default, Jun 29 2016, 14:05:02) [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]**
Operating System: **Darwin-15.6.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4219585709dc1d9ed23ec7ea773a51e92c97b7b5
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [4219585] Exception generated in thread POSTPROCESSER: 'module' object has no attribute 'SLACK_NOTIFY_SUBTITLEDOWNLOAD'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by djkemai** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@4219585709dc1d9ed23ec7ea773a51e92c97b7b5
No Log available with ERRORS:
### ERROR
```
Thread-24 :: [4219585] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 2298, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "C:\SickRage\SickRage\sickbeard\processTV.py", line 243, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\SickRage\sickbeard\processTV.py", line 560, in process_media
    result.result = processor.process()
  File "C:\SickRage\SickRage\sickbeard\postProcessor.py", line 1194, in process
    cur_ep.download_subtitles(force=True)
  File "C:\SickRage\SickRage\sickbeard\tv.py", line 1428, in download_subtitles
    notifiers.notify_subtitle_download(self.prettyName(), subtitle_list)
  File "C:\SickRage\SickRage\sickbeard\notifiers\__init__.py", line 89, in notify_subtitle_download
    n.notify_subtitle_download(ep_name, lang)
  File "C:\SickRage\SickRage\sickbeard\notifiers\slack.py", line 39, in notify_subtitle_download
    if sickbeard.SLACK_NOTIFY_SUBTITLEDOWNLOAD:
AttributeError: 'module' object has no attribute 'SLACK_NOTIFY_SUBTITLEDOWNLOAD'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by maverock** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1254
Branch: **master**
Commit: SickRage/SickRage@4219585709dc1d9ed23ec7ea773a51e92c97b7b5
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [4219585] Exception generated in thread POSTPROCESSER: 'module' object has no attribute 'SLACK_NOTIFY_SUBTITLEDOWNLOAD'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by djkemai** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@4219585709dc1d9ed23ec7ea773a51e92c97b7b5
No Log available with ERRORS:
### ERROR
```
Thread-25 :: [4219585] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 2298, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "C:\SickRage\SickRage\sickbeard\processTV.py", line 290, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\SickRage\sickbeard\processTV.py", line 560, in process_media
    result.result = processor.process()
  File "C:\SickRage\SickRage\sickbeard\postProcessor.py", line 1194, in process
    cur_ep.download_subtitles(force=True)
  File "C:\SickRage\SickRage\sickbeard\tv.py", line 1428, in download_subtitles
    notifiers.notify_subtitle_download(self.prettyName(), subtitle_list)
  File "C:\SickRage\SickRage\sickbeard\notifiers\__init__.py", line 89, in notify_subtitle_download
    n.notify_subtitle_download(ep_name, lang)
  File "C:\SickRage\SickRage\sickbeard\notifiers\slack.py", line 39, in notify_subtitle_download
    if sickbeard.SLACK_NOTIFY_SUBTITLEDOWNLOAD:
AttributeError: 'module' object has no attribute 'SLACK_NOTIFY_SUBTITLEDOWNLOAD'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by djkemai** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@4219585709dc1d9ed23ec7ea773a51e92c97b7b5
No Log available with ERRORS:
### ERROR
```
Thread-23 :: [4219585] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 2298, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "C:\SickRage\SickRage\sickbeard\processTV.py", line 290, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\SickRage\sickbeard\processTV.py", line 560, in process_media
    result.result = processor.process()
  File "C:\SickRage\SickRage\sickbeard\postProcessor.py", line 1194, in process
    cur_ep.download_subtitles(force=True)
  File "C:\SickRage\SickRage\sickbeard\tv.py", line 1428, in download_subtitles
    notifiers.notify_subtitle_download(self.prettyName(), subtitle_list)
  File "C:\SickRage\SickRage\sickbeard\notifiers\__init__.py", line 89, in notify_subtitle_download
    n.notify_subtitle_download(ep_name, lang)
  File "C:\SickRage\SickRage\sickbeard\notifiers\slack.py", line 39, in notify_subtitle_download
    if sickbeard.SLACK_NOTIFY_SUBTITLEDOWNLOAD:
AttributeError: 'module' object has no attribute 'SLACK_NOTIFY_SUBTITLEDOWNLOAD'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by djkemai** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@4219585709dc1d9ed23ec7ea773a51e92c97b7b5
No Log available with ERRORS:
### ERROR
```
Thread-24 :: [4219585] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 2298, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "C:\SickRage\SickRage\sickbeard\processTV.py", line 290, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\SickRage\sickbeard\processTV.py", line 560, in process_media
    result.result = processor.process()
  File "C:\SickRage\SickRage\sickbeard\postProcessor.py", line 1194, in process
    cur_ep.download_subtitles(force=True)
  File "C:\SickRage\SickRage\sickbeard\tv.py", line 1428, in download_subtitles
    notifiers.notify_subtitle_download(self.prettyName(), subtitle_list)
  File "C:\SickRage\SickRage\sickbeard\notifiers\__init__.py", line 89, in notify_subtitle_download
    n.notify_subtitle_download(ep_name, lang)
  File "C:\SickRage\SickRage\sickbeard\notifiers\slack.py", line 39, in notify_subtitle_download
    if sickbeard.SLACK_NOTIFY_SUBTITLEDOWNLOAD:
AttributeError: 'module' object has no attribute 'SLACK_NOTIFY_SUBTITLEDOWNLOAD'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by spiddeer** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 11:41:39) [GCC 4.6.4]**
Operating System: **Linux-3.10.77-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4219585709dc1d9ed23ec7ea773a51e92c97b7b5
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [4219585] Exception generated in thread POSTPROCESSER: 'module' object has no attribute 'SLACK_NOTIFY_SUBTITLEDOWNLOAD'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
