### ISSUE TITLE
[APP SUBMITTED]: 401 {u'documentation_url': u'https://developer.github.com/v3/auth#working-with-two-factor-authentication', u'message': u'Must specify two-factor authentication OTP code.'}

### ISSUE THREAD

**Issue by spiddeer** [SickRage/SickRage#2289]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 11:41:39) [GCC 4.6.4]**
Operating System: **Linux-3.10.77-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4219585709dc1d9ed23ec7ea773a51e92c97b7b5
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [4219585] Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 350, in submit_errors
    repo = sickbeard.gh.get_organization(sickbeard.GIT_ORG).get_repo(sickbeard.GIT_REPO)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/MainClass.py", line 188, in get_organization
    "/orgs/" + login
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
TwoFactorException: 401 {u'documentation_url': u'https://developer.github.com/v3/auth#working-with-two-factor-authentication', u'message': u'Must specify two-factor authentication OTP code.'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by stramel** [comment]
@spiddeer Did you figure out how to get around this? I am running into the same issue.

**Comment by sharkykh** [comment]
This is Github's "Two-Factor Authentication", and it's not currently supported by SickRage.
In the meantime you can remove your Github login information from Config -> General -> Advanced
If you're not using this function

**Comment by stramel** [comment]
Would love to see support for 2FA! Especially since it would make sending in issues easier.

**Comment by sharkykh** [comment]
I'm attempting to do so now.
However... the part where the user having to enter a code doesn't really fit in anywhere yet..
