### ISSUE TITLE
API error htpc manager

### ISSUE THREAD

**Issue by gl3nni3** [SickRage/SickRage#2313]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:master
OS:Unraid docker
What you did: Tried to connect htpc manager to sickrage
What happened: after debugging sickrage it turns out it got an error from sickrage saying : {"data": {"args": [], "error_msg": "error 512", "kwargs": {"indexerid": "267440"}}, "message": "SickRage encountered an internal error! Please report to the Devs", "result": "fatal"}
What you expected: all the episoded in the return
Logs:
AKeyError: 512 AA any_qualities.append(quality_map[quality]) AA File "/app/sickrage/sickbeard/webapi.py", line 544, in _map_quality AA any_qualities, best_qualities = _map_quality(show_obj.quality) AA File "/app/sickrage/sickbeard/webapi.py", line 1898, in run AA cur_out_dict = func(cur_args, cur_kwargs).run() # call function and get response AA File "/app/sickrage/sickbeard/webapi.py", line 204, in call_dispatcher AA out_dict = _call_dispatcher(args, kwargs) AA File "/app/sickrage/sickbeard/webapi.py", line 136, in get AATraceback (most recent call last): 2016-09-08 11:22:24 ERROR TORNADO :: [8564c29] API :: error 512 2016-09-08 11:22:24 DEBUG TORNADO :: API :: show: cur_kwargs {'indexerid': '267440'} 2016-09-08 11:22:24 DEBUG TORNADO :: API :: all kwargs: '{'indexerid': '267440', 'cmd': 'show'}' 2016-09-08 11:22:24 DEBUG TORNADO :: API :: all args: '()' 2016-09-08 11:22:24 DEBUG TORNADO :: API :: 172.17.42.1 - gave correct API KEY. ACCESS GRANTED AA AAAttributeError: 'WebRoot' object has no attribute 'api/********************************' AA method = getattr(self, _route) AA File "/app/sickrage/sickbeard/webserve.py", line 252, in get 2016-09-08 11:22:18 DEBUG TORNADO :: Failed doing webui request "": Traceback (most recent call last): AA AAAttributeError: 'WebRoot' object has no attribute 'api/********************************' AA method = getattr(self, _route) AA File "/app/sickrage/sickbeard/webserve.py", line 252, in get

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [ ] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Error 512 generally indicates a network connection issue.  Maybe htpc cant access the sickrage correctly.?
Might be the docker setup or proxy etc.?

You also could try to remove this show from your list and see if it than loads. : 

https://thetvdb.com/?tab=series&id=267440
