### ISSUE TITLE
Post-processing throws error - UnicodeEncodeError: 'charmap' codec can't encode character u'\u262e' in position 0

### ISSUE THREAD

**Issue by Concept211** [SickRage/SickRage#2314]
Branch/Commit: Latest/Master
OS: Windows 7 SP1
What you did: Ran automated and/or manual post-processing
What happened: Throws the UnicodeEncodeError and won't move any files.
What you expected: To move the files ;)
Logs:
```
2016-09-08 06:05:59 Thread-69 :: [8564c29] Failed doing webui callback: Traceback (most recent call last): 
File "C:\SickRage\SickRage\sickbeard\webserve.py", line 270, in async_call result = function(**kwargs) 
File "C:\SickRage\SickRage\sickbeard\webserve.py", line 2298, in processEpisode is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type 
File "C:\SickRage\SickRage\sickbeard\processTV.py", line 251, in processDir for curDir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]: 
File "C:\SickRage\SickRage\sickbeard\processTV.py", line 400, in validateDir NameParser().parse(proc_dir, cache_result=False) 
File "C:\SickRage\SickRage\sickbeard\name_parser\parser.py", line 461, in parse name, file_name_result or dir_name_result)) 
File "C:\SickRage\Python\lib\encodings\cp1252.py", line 12, in encode return codecs.charmap_encode(input,errors,encoding_table) 
UnicodeEncodeError: 'charmap' codec can't encode character u'\u262e' in position 0: character maps to 
```

It seems this happens when post-processing files that are inside of a sub-directory. If I pull the file out to the root processing directory it works fine. I've tested with multiple subdirectories and they all fail. None of them have any strange characters or anything. This used to work perfectly fine for years and now all of a sudden it's failing. Please help!

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sm-k** [comment]
\u262e is the unicode for ☮ 

so you have a folder/file with that in the name. it seems like the unicode in this chokes constantly

**Comment by Concept211** [comment]
That's the strange thing because I don't have any directories like that in the scan folder. I have all hidden directories turned on and there's nothing. I just don't understand where SR is reading that from? Any ideas for next steps?

thanks!

**Comment by neoatomic** [comment]
Its definitely an UnicodeEncodeError , so it has a character somewhere that is giving problems with Windows cp1252.

Maybe there is a scene exception added that has a special character.? Its a little hard to tell for me. :)
And removing/re-adding the show might be worth trying.
