### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by ammelec** [SickRage/SickRage#2327]
### INFO
Python Version: **2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-36-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4d69a8e09fe808751fa5fef9a0c3e3b8c1af99b1
No Log available with ERRORS:
### ERROR
```
Thread-897 :: [4d69a8e] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1610, in deleteShow
    show_name=show.name,
AttributeError: 'NoneType' object has no attribute 'name'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by danmcg13** [comment]
### INFO
Python Version: **2.7.3 (default, Jun 21 2016, 18:38:19) [GCC 4.7.2]**
Operating System: **Linux-3.16.0-0.bpo.4-amd64-x86_64-with-debian-7.11**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@1faad224a89a4c0ee588627fe65065e2f0d0ffc2
No Log available with ERRORS:
### ERROR
```
Thread-30 :: [1faad22] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 1730, in deleteShow
    show_name=show.name,
AttributeError: 'NoneType' object has no attribute 'name'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by phishin4dmb** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.102-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@558cd35a9c7dee197cced35a0db9361de1c41ca3
No Log available with ERRORS:
### ERROR
```
Thread-42 :: [558cd35] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 1732, in deleteShow
    show_name=show.name,
AttributeError: 'NoneType' object has no attribute 'name'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rishitank** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 26 2015, 22:15:29) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@c56813972dbd79b774fab271b990881af464aa7a
No Log available with ERRORS:
### ERROR
```
MANUAL :: [c568139] Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 1740, in deleteShow
    show_name=show.name,
AttributeError: 'NoneType' object has no attribute 'name'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by PapaFatHead** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
Thread-17 :: [10a0c30] Failed doing webui callback: Traceback (most recent call last):
  File "/home/seeduser/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/home/seeduser/sickrage/sickbeard/webserve.py", line 1740, in deleteShow
    show_name=show.name,
AttributeError: 'NoneType' object has no attribute 'name'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by potestus** [comment]
### INFO
Python Version: **2.7.15 (default, Mar 21 2019, 20:32:32) [GCC 7.4.0]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@2404f197697602a2bbfa8e6b39207229a94d37bb
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [2404f19] Failed doing webui callback: Traceback (most recent call last):
  File "/share/HDA_DATA/.qpkg/SickChill/SickChill/sickchill/views/index.py", line 180, in async_call
    result = function(**kwargs)
  File "/share/HDA_DATA/.qpkg/SickChill/SickChill/sickchill/views/home.py", line 1194, in deleteShow
    show_name=show.name,
AttributeError: 'NoneType' object has no attribute 'name'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by potestus** [comment]
### INFO
Python Version: **2.7.15 (default, Mar 21 2019, 20:32:32) [GCC 7.4.0]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@1f124b31b16303a511c86717f11dd28b9cbf7b46
No Log available with ERRORS:
### ERROR
```
WEBSERVER-HOME :: [1f124b3] Failed doing webui callback: Traceback (most recent call last):
  File "/share/HDA_DATA/.qpkg/SickChill/SickChill/sickchill/views/index.py", line 178, in async_call
    result = function(**kwargs)
  File "/share/HDA_DATA/.qpkg/SickChill/SickChill/sickchill/views/home.py", line 1193, in deleteShow
    show_name=show.name,
AttributeError: 'NoneType' object has no attribute 'name'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
