### ISSUE TITLE
ImportError: No module named apscheduler.schedulers.tornado

### ISSUE THREAD

**Issue by ouija** [SickRage/SickRage#2348]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 3e79a8f
OS:  Linux QNAP-NAS 3.12.6 x86_64
What you did: Installed SickRage QPKG (for QNAP NAS) via: https://forum.qnap.com/viewtopic.php?f=223&t=118366
What happened: SickRage fails to start
What you expected: Wanted SickRage to start
Logs:
```
SickBeard-TVRage prestartup checks...
 Checking for git...  Found!
Updating SickBeard-TVRage
HEAD is now at 3e79a8f new: Version 8.1.9
Already up-to-date.
Starting SickBeard-TVRage
Traceback (most recent call last):
  File "/share/5000C50065270017_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sic              krage/__init__.py", line 208, in main
    from sickrage import core
  File "/share/5000C50065270017_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sic              krage/core/__init__.py", line 32, in <module>
    from apscheduler.schedulers.tornado import TornadoScheduler
ImportError: No module named apscheduler.schedulers.tornado
Failed to import required libs, please run 'pip install -r /share/5000C500652700              17_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/requirements.txt' from console

```

Yes I've installed the requirements via PIP and also tried updating both apscheduler and tornado. as well as pip itself and everything else, but the error still occurs.

I searched the installation and logs directory for an actual log file, but none exist :(
I realize that this is a NAS unit and not a typical linux setup/environment, but any help is appreciated.

Thank you.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by ouija** [comment]
Update:  Managed to get SickRage installed on my QNAP NAS using the installer package from http://sickrage.ca/ instead.

Consider this issue resolved.

**Comment by ouija** [comment]
Quick update #2: The QNAP package at sickrage.ca is outdated and is not working; However, I found a better (updated) QPKG file at: https://www.forum-nas.fr/viewtopic.php?f=21&t=1359&sid=18e8d4829d4ef9d30d345f0299439ce2

This is working well and resolved my issues (although I had to install the x86 version, even though uname -m reported my system running x86_64) but at least it's working! :)
