### ISSUE TITLE
[APP SUBMITTED]: invalid syntax (home.mako.py, line 95)

### ISSUE THREAD

**Issue by cheesehd** [SickRage/SickRage#2349]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@b6041e99bdacb809005fb7c9ff691216de15f7d3
No Log available with ERRORS:
### ERROR
```
Thread-17 :: [b6041e9] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 654, in index
    t = PageTemplate(rh=self, filename="home.mako")
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 112, in __init__
    self.template = lookup.get_template(filename)
  File "C:\SickRage\SickRage\lib\mako\lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "C:\SickRage\SickRage\lib\mako\lookup.py", line 321, in _load
    **self.template_args)
  File "C:\SickRage\SickRage\lib\mako\template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\SickRage\lib\mako\compat.py", line 89, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\SickRage\Data\cache\mako\home.mako.py", line 95
    retur render_content(context)
                       ^
SyntaxError: invalid syntax

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Stop SR and delete `C:\SickRage\Data\cache\mako`

**Comment by prantzos** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [5a9a634] Failed doing webui callback: Traceback (most recent call last):
  File "C:\My\OneDrive\Programs\SickRage\sickbeard\webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "C:\My\OneDrive\Programs\SickRage\sickbeard\webserve.py", line 716, in index
    t = PageTemplate(rh=self, filename="home.mako")
  File "C:\My\OneDrive\Programs\SickRage\sickbeard\webserve.py", line 115, in __init__
    self.template = lookup.get_template(filename)
  File "C:\My\OneDrive\Programs\SickRage\lib\mako\lookup.py", line 258, in get_template
    return self._load(srcfile, uri)
  File "C:\My\OneDrive\Programs\SickRage\lib\mako\lookup.py", line 323, in _load
    **self.template_args)
  File "C:\My\OneDrive\Programs\SickRage\lib\mako\template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\My\OneDrive\Programs\SickRage\lib\mako\template.py", line 396, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\My\OneDrive\Programs\SickRage\lib\mako\compat.py", line 90, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\My\OneDrive\Programs\SickRage\cache\mako\home.mako.py", line 95
    
    ^
SyntaxError: invalid syntax

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DravenSA** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@020e76222c851074fe22b76ada95d31697091a91
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [020e762] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickChill\SickChill\sickbeard\webserve.py", line 717, in index
    t = PageTemplate(rh=self, filename="home.mako")
  File "C:\SickChill\SickChill\sickbeard\webserve.py", line 114, in __init__
    self.template = lookup.get_template(filename)
  File "C:\SickChill\SickChill\lib\mako\lookup.py", line 258, in get_template
    return self._load(srcfile, uri)
  File "C:\SickChill\SickChill\lib\mako\lookup.py", line 323, in _load
    **self.template_args)
  File "C:\SickChill\SickChill\lib\mako\template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickChill\SickChill\lib\mako\template.py", line 396, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickChill\SickChill\lib\mako\compat.py", line 90, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\SickChill\Data\cache\mako\home.mako.py", line 95
    
    ^
SyntaxError: invalid syntax

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ronrosenfeld** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@1f124b31b16303a511c86717f11dd28b9cbf7b46
Link to Log: https://gist.github.com/1958eb67a689fcccca61b869fa6f9b90
### ERROR
```
WEBSERVER-HOME :: [1f124b3] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickchill\views\index.py", line 178, in async_call
    result = function(**kwargs)
  File "C:\SickChill\SickChill\sickchill\views\home.py", line 98, in index
    t = PageTemplate(rh=self, filename="home.mako")
  File "C:\SickChill\SickChill\sickchill\views\common.py", line 64, in __init__
    self.template = lookup.get_template(filename)
  File "C:\SickChill\SickChill\lib\mako\lookup.py", line 260, in get_template
    return self._load(srcfile, uri)
  File "C:\SickChill\SickChill\lib\mako\lookup.py", line 327, in _load
    **self.template_args
  File "C:\SickChill\SickChill\lib\mako\template.py", line 347, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickChill\SickChill\lib\mako\template.py", line 415, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickChill\SickChill\lib\mako\compat.py", line 103, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\SickChill\SickChill\gui\slick\cache\mako\home.mako.py", line 95
    
    ^
SyntaxError: invalid syntax

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by DravenSA** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@cec77d3551a9593a1da98b887104458c13189e92
Link to Log: https://gist.github.com/8dd559ea5366be32a11b2fc13732e320
### ERROR
```
WEBSERVER-HOME :: [cec77d3] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickchill\views\index.py", line 215, in async_call
    result = function(**kwargs)
  File "C:\SickChill\SickChill\sickchill\views\home.py", line 98, in index
    t = PageTemplate(rh=self, filename="home.mako")
  File "C:\SickChill\SickChill\sickchill\views\common.py", line 64, in __init__
    self.template = lookup.get_template(filename)
  File "C:\SickChill\SickChill\lib\mako\lookup.py", line 260, in get_template
    return self._load(srcfile, uri)
  File "C:\SickChill\SickChill\lib\mako\lookup.py", line 327, in _load
    **self.template_args
  File "C:\SickChill\SickChill\lib\mako\template.py", line 347, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickChill\SickChill\lib\mako\template.py", line 415, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickChill\SickChill\lib\mako\compat.py", line 103, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\SickChill\SickChill\gui\slick\cache\mako\home.mako.py", line 95
    
    ^
SyntaxError: invalid syntax

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by doublegalz** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@0018d0847e9e2371501e63727b756218096d665b
Link to Log: https://gist.github.com/55da0066ba6d22f6573194c5173d3ec3
### ERROR
```
WEBSERVER-HOME :: [0018d08] Failed doing webui callback: Traceback (most recent call last):
  File "D:\SickChill\SickChill\SickChill\sickchill\views\index.py", line 216, in async_call
    result = function(**kwargs)
  File "D:\SickChill\SickChill\SickChill\sickchill\views\home.py", line 98, in index
    t = PageTemplate(rh=self, filename="home.mako")
  File "D:\SickChill\SickChill\SickChill\sickchill\views\common.py", line 64, in __init__
    self.template = lookup.get_template(filename)
  File "D:\SickChill\SickChill\SickChill\lib\mako\lookup.py", line 260, in get_template
    return self._load(srcfile, uri)
  File "D:\SickChill\SickChill\SickChill\lib\mako\lookup.py", line 327, in _load
    **self.template_args
  File "D:\SickChill\SickChill\SickChill\lib\mako\template.py", line 348, in __init__
    module = self._compile_from_file(path, filename)
  File "D:\SickChill\SickChill\SickChill\lib\mako\template.py", line 416, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "D:\SickChill\SickChill\SickChill\lib\mako\compat.py", line 114, in load_module
    return imp.load_source(module_id, path, fp)
  File "D:\SickChill\SickChill\SickChill\gui\slick\cache\mako\home.mako.py", line 95
    
    ^
SyntaxError: invalid syntax

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
