### ISSUE TITLE
Referenced 'curShowName' before assignment

### ISSUE THREAD

**Issue by tblyler** [SickRage/SickRage#2356]
Branch/Commit: master/c5433660132461e7ffc5fe1501f43c81fac9c345
OS: Debian Linux Jessie amd64
What you did: Ran sickrage idley
What happened: A Python exception and daemon crash.
What you expected: None of the above.
Logs:
```
python2.7[438]: Exception in thread SHOWQUEUE-FORCE-UPDATE:
python2.7[438]: Traceback (most recent call last):
python2.7[438]: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
python2.7[438]: self.run()
python2.7[438]: File "/home/downer/sickrage/sickbeard/show_queue.py", line 642, in run
python2.7[438]: DBEpList = self.show.loadEpisodesFromDB()
python2.7[438]: File "/home/downer/sickrage/sickbeard/tv.py", line 534, in loadEpisodesFromDB
python2.7[438]: (show=curShowName, id=curShowid), logger.DEBUG)
python2.7[438]: UnboundLocalError: local variable 'curShowName' referenced before assignment
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
