### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: u'/sickbeard/cache/mako/errorlogs.mako.py'

### ISSUE THREAD

**Issue by gbrowerjr** [SickRage/SickRage#2368]
### INFO
Python Version: **2.7.9 (default, Mar  8 2015, 00:52:26) [GCC 4.9.2]**
Operating System: **Linux-4.1.18-v7+-armv7l-with-debian-8.0**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@027a950fe0ac81a6d3a139f5ad68cfbaa8c85e9f
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [027a950] Failed doing webui callback: Traceback (most recent call last):
  File "/sickbeard/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/sickbeard/sickbeard/webserve.py", line 5275, in index
    logLevel=level, controller="errorlogs", action="index")
  File "/sickbeard/sickbeard/webserve.py", line 160, in render
    kwargs['backtrace'] = RichTraceback()
  File "/sickbeard/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/sickbeard/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/sickbeard/lib/mako/template.py", line 632, in code
    return util.read_python_file(self.module_filename)
  File "/sickbeard/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/sickbeard/cache/mako/errorlogs.mako.py'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
