### ISSUE TITLE
Problem with anime naming convention

### ISSUE THREAD

**Issue by tabouzeid** [SickRage/SickRage#2371]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Synology DSM
What you did: tried to set the naming convention for anime to %SN - %E - %EN with 'Only Absolute Number' selected at the bottom
What happened: didn't save, it thinks it's invalid
What you expected: new naming convention to be saved
Logs:

```
AAIndexError: unknown group name: u'pre_sep' 
AA raise IndexError(msg) 
AA File "/usr/local/sickbeard-custom/env/lib/python2.7/sre_parse.py", line 781, in parse_template 
AA p = sre_parse.parse_template(repl, pattern) 
AA File "/usr/local/sickbeard-custom/env/lib/python2.7/re.py", line 271, in _compile_repl 
AA template = _compile_repl(template, pattern) 
AA File "/usr/local/sickbeard-custom/env/lib/python2.7/re.py", line 286, in _subx 
AA return _compile(pattern, flags).sub(repl, string, count) 
AA File "/usr/local/sickbeard-custom/env/lib/python2.7/re.py", line 155, in sub 
AA cur_name_group_result = re.sub('(?i)(?x)' + regex_used, regex_replacement, cur_name_group) 
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 2341, in _format_pattern 
AA return sanitize_filename(self._format_pattern(name_groups[-1], multi, anime_type)) 
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 2415, in formatted_filename 
AA new_name = ep.formatted_filename(pattern, multi, anime_type) + '.ext' 
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/naming.py", line 210, in validate_name 
AA valid = validate_name(pattern, None, anime_type) 
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/naming.py", line 156, in check_valid_naming 
AA is_valid = naming.check_valid_naming(pattern, multi, anime_type) 
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 4343, in isNamingValid 
AA if self.isNamingValid(naming_anime_pattern, naming_anime_multi_ep, anime_type=naming_anime) != "invalid": 
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 4270, in savePostProcessing 
AA result = function(**kwargs) 
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 270, in async_call 
AA result = self.fn(*self.args, **self.kwargs) 
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/thread.py", line 61, in run 
AA exec('raise exc_type, exc_value, traceback', {}, locals_) 
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_compat.py", line 107, in reraise 
AA reraise(self._exception, self._traceback) 
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_base.py", line 359, in __get_result 
AA return self.__get_result() 
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_base.py", line 400, in result 
AA value = future.result()
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/gen.py", line 870, in run 
AA results = yield self.async_call(method) 
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 254, in get 
AA yielded = self.gen.throw(*exc_info) 
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/gen.py", line 876, in run 
AA raise_exc_info(self._exc_info) 
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/concurrent.py", line 215, in result 
AA value = future.result() 
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/gen.py", line 870, in run 
AA result = yield result 
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/web.py", line 1415, in _execute 
AATraceback (most recent call last):
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by hergonoway** [comment]
+1 naming convention bug on any modification. Whatever you modify, or even, whatever you choose in pre-build naming convention. I think there's a deep bug in the validation script :(

**Comment by tabouzeid** [comment]
Any traction on this from the Sickrage team?

**Comment by neoatomic** [comment]
There is a overhaul planned for the naming convention, but that wont happen on a short timeline.
The Nzbtomedia scripts support also renaming, so maybe that's a temp solution.
https://github.com/SickRage/SickRage/wiki/NZBtoMedia

**Comment by belak** [comment]
I seem to run into this when trying to add the absolute number as well.

So, with anime_type=1 and anime_type=2 it errors even with a naming scheme that's valid with anime_type=3

**Comment by hergonoway** [comment]
Had the same issue, one time the absolute numbering worked ( don't know how don't know why), never touched the configuration again just in case.

**Comment by h3llrais3r** [comment]
@miigotu any idea why the page of the 'episode naming' page is as slow as hell?
It keeps formatting patterns... but I have no clue where it's coming from...

**Comment by miigotu** [comment]
It isnt slow here, I dont know.  But the pattern is tested with js every time you change the patterns

**Comment by h3llrais3r** [comment]
Strange, it really takes a few seconds until the preview is shown...

**Comment by sharkykh** [comment]
@h3llrais3r @miigotu 
I recorded some timings:

![image](https://cloud.githubusercontent.com/assets/10238474/23483974/b442978e-fedd-11e6-900b-481b6888f025.png)

**Comment by h3llrais3r** [comment]
@sharkykh can you do the same with debug enabled AND when debugging from your ide?
Try to modify the anime pattern as explained above.

**Comment by h3llrais3r** [comment]
![image](https://cloud.githubusercontent.com/assets/1945295/23484200/4ae93f10-fed6-11e6-99ce-9a578382f439.png)

This is just be removing a part from the anime pattern... 😢

**Comment by sharkykh** [comment]
Debug was enabled when I recorded.
Running from IDE/Debugging platform is much much slower because of the extra debugging of the IDE.
But why does it go up to a minute?!

**Comment by h3llrais3r** [comment]
I have no idea, but if you enable the debug logging, it really logs a lot... but this shouldn't take up to a minute...

**Comment by sharkykh** [comment]
I don't know what you use, but I used PyCharm now, debugged SickRage and ..
![image](https://cloud.githubusercontent.com/assets/10238474/23484528/02246f66-fee0-11e6-9442-d7b4647a0c80.png)

Anyway, does this bug/issue still exist?
Even with all the changes over the last... I don't know, month?

**Comment by h3llrais3r** [comment]
Yes it does, otherwise I wouldn't have labeled it as a bug. 😄 
But I think I have clue, but still need to test more, which isn't easy if it takes that long...
I think it's related to the fact that the season folder is not longer in the rename pattern, while season folders are used for the shows...

**Comment by h3llrais3r** [comment]
Ok, my clue seems to be right...
The following pattern is not a valid pattern and throws an error: `%SN - %E - %EN`
Instead the following pattern should be used to get a similar result: `%SN - %Sx%0E - %EN`
Perhaps we can show something in the gui that the pattern is not valid?

**Comment by sharkykh** [comment]
It's supposed to do ajax POST to isNamingValid on every change in any of the input boxes
and display a qtip that says it's not a valid pattern...
See https://github.com/SickRage/SickRage/blob/develop/gui/slick/js/core.js#L1256-L1256

**Comment by h3llrais3r** [comment]
Thanks for the hint, will check it out tomorrow. Time for sleep now. 😴
