### ISSUE TITLE
Exception while searching in SceneTime.

### ISSUE THREAD

**Issue by Dracozny** [SickRage/SickRage#2407]
Branch: master
Commit: 2d9a6c1f4a837fa4030fb53a884117dfcdf6a2bb
Version: 2016.09.28-1
Database Version: 44.0
OS: Linux-4.4.0-38-generic-x86_64-with-LinuxMint-18-sarah
What you did: Scheduled or forced search
What happened: Error: Exception while searching propers in SceneTime, skipping: 'NoneType' object has no attribute 'next_element'
What you expected: Scenetime search results and snagged.
Logs:
```
2016-09-29 16:33:08 INFO POSTPROCESSER :: Successfully processed 2016-09-29 16:33:05 INFO POSTPROCESSER :: PostProcessing Path: /media/Completed/TVShows 2016-09-29 16:28:34 INFO FINDPROPERS :: Completed the search for new propers, next check in approx. 1h, 29m 2016-09-29 16:28:28 INFO FINDPROPERS :: [ExtraTorrent] :: Searching for any new PROPER releases from ExtraTorrent AA AAAttributeError: 'NoneType' object has no attribute 'next_element' AA current = current.next_element AA File "/opt/sickrage/lib/bs4/element.py", line 1277, in descendants AA result = (element for element in generator AA File "/opt/sickrage/lib/bs4/element.py", line 526, in  AA super(ResultSet, self).__init__(result) AA File "/opt/sickrage/lib/bs4/element.py", line 1724, in __init__ AA return ResultSet(strainer, result) AA File "/opt/sickrage/lib/bs4/element.py", line 529, in _find_all AA return self._find_all(name, attrs, text, limit, generator, **kwargs) AA File "/opt/sickrage/lib/bs4/element.py", line 1259, in find_all AA return self.find_all(*args, **kwargs) AA File "/opt/sickrage/lib/bs4/element.py", line 988, in __call__ AA labels = [label.get_text(strip=True) for label in torrent_rows[0]('td')] AA File "/opt/sickrage/sickbeard/providers/scenetime.py", line 106, in search AA for item in self.search(search_strings[0]): AA File "/opt/sickrage/sickrage/providers/torrent/TorrentProvider.py", line 66, in find_propers AA curPropers = curProvider.find_propers(search_date) AA File "/opt/sickrage/sickbeard/properFinder.py", line 88, in _getProperList 2016-09-29 16:28:28 ERROR FINDPROPERS :: [SceneTime] :: [2d9a6c1] Exception while searching propers in SceneTime, skipping: 'NoneType' object has no attribute 'next_element' 2016-09-29 16:28:27 INFO FINDPROPERS :: [SceneTime] :: Searching for any new PROPER releases from SceneTime 2016-09-29 16:28:27 INFO FINDPROPERS :: Beginning the search for new propers 2016-09-29 16:28:26 INFO Thread-17 :: Find propers search forced 2016-09-29 16:28:05 INFO CHECKVERSION :: Checking for updates using GIT 2016-09-29 16:28:05 INFO TORNADO :: Starting SickRage on http://0.0.0.0:8081/ 2016-09-29 16:28:05 INFO MAIN :: Starting SickRage [master] using '/opt/sickrage/config.ini' 2016-09-29 16:28:01 INFO EVENT-QUEUE :: Restarting SickRage with ['/usr/bin/python2.7', u'/opt/sickrage/SickBeard.py', '-q', '--daemon', '--nolaunch', '--datadir=/opt/sickrage']
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by thibmaek** [comment]
Yep same here!

**Comment by kyneticx** [comment]
am having the same issue - here are some debug logs..  i am on the latest commit of the master branch... this is running on a windows server 2012 R2 machine and i have noticed that the shows in my daily queue have not been downloading as they normally would automatically for about roughly a month now. i get this error when i goto do a manual search by clicking on the spyglass icon in the schedule next to the episode i want to download. i know there are results as when i go to do a search through the site itself i most definitely get results..
without actually having checked i presume the same error is occuring when the daily queue search is being executed - let me know if you'd like copies of the full log files after theyve been running with debug mode on for a while... 
just a few things ive noted already without digging too much deeper yet - the post url is returning a redirect status code (302) so im not sure that the post url is returning the correctly formatted output youre expecting which is possibly the root cause of your issue.. - im no expert and i havent really dug any further than this just thought id chuck my two cents in for what it might be worth.. let me know if you need any further info or the complete log files  ive posted two searches i performed in an inline log file below for you to peruse.. i have also included the personally generated scenetime rss url that they provide you with (omitted my passkey and i am searching all of their tv feeds)
perhaps a quick fix here might be to use the users self generated rss link with an option in the scenetime settings to add their own personalised url so that you are getting an xml output to parse through rather than the html table output you seem to get when using the browse_api.php link.. again this is my non expert opinion - i havent really done a lot of coding using python but id be interested in having a go at figuring out this issue if its not just something you can quickly fix :) 

[my personalised rss link with passkey omitted](https://www.scenetime.com/get_rss.php?user=kynetic&cat=9,63,100,43,77,83,2&passkey=)
```
2016-10-03 22:02:26 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [SceneTime] :: Search Mode: RSS
2016-10-03 22:02:28 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [SceneTime] :: POST URL: https://www.scenetime.com/browse_API.php [Status: 302]
2016-10-03 22:02:28 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [SceneTime] :: With post data: c79=1&cata=yes&search=&c83=1&c42=1&c63=1&c77=1&c9=1&sec=jax&c2=1&c100=1
2016-10-03 22:02:28 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [SceneTime] :: GET URL: https://www.scenetime.com/login.php [Status: 200]
2016-10-03 22:02:28 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [SceneTime] :: Error while searching SceneTime, skipping: AttributeError("'NoneType' object has no attribute 'next_element'",)
2016-10-03 22:02:28 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [SceneTime] :: Transaction with 245 queries executed
2016-10-03 22:02:28 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2016-10-03 22:04:00 DEBUG    SEARCHQUEUE-MANUAL-75897 :: formatting pattern: %SN - S%0SE%0E - %EN -> South Park - S20E03 - The Damned
2016-10-03 22:04:00 INFO     SEARCHQUEUE-MANUAL-75897 :: Beginning manual search for: [South Park - S20E03 - The Damned]
2016-10-03 22:04:00 DEBUG    SEARCHQUEUE-MANUAL-75897 :: [SceneTime] :: Search Mode: RSS
2016-10-03 22:04:01 DEBUG    SEARCHQUEUE-MANUAL-75897 :: [SceneTime] :: POST URL: https://www.scenetime.com/browse_API.php [Status: 302]
2016-10-03 22:04:01 DEBUG    SEARCHQUEUE-MANUAL-75897 :: [SceneTime] :: With post data: c79=1&cata=yes&search=&c83=1&c42=1&c63=1&c77=1&c9=1&sec=jax&c2=1&c100=1
2016-10-03 22:04:02 DEBUG    SEARCHQUEUE-MANUAL-75897 :: [SceneTime] :: GET URL: https://www.scenetime.com/login.php [Status: 200]
2016-10-03 22:04:02 DEBUG    SEARCHQUEUE-MANUAL-75897 :: [SceneTime] :: Error while searching SceneTime, skipping: AttributeError("'NoneType' object has no attribute 'next_element'",)
2016-10-03 22:04:02 INFO     SEARCHQUEUE-MANUAL-75897 :: [SceneTime] :: Performing episode search for South Park
2016-10-03 22:04:02 DEBUG    SEARCHQUEUE-MANUAL-75897 :: [SceneTime] :: Search Mode: Episode
2016-10-03 22:04:02 DEBUG    SEARCHQUEUE-MANUAL-75897 :: [SceneTime] :: Search string: South Park S20E03
2016-10-03 22:04:03 DEBUG    SEARCHQUEUE-MANUAL-75897 :: [SceneTime] :: POST URL: https://www.scenetime.com/browse_API.php [Status: 302]
2016-10-03 22:04:03 DEBUG    SEARCHQUEUE-MANUAL-75897 :: [SceneTime] :: With post data: c79=1&cata=yes&search=South+Park+S20E03&c83=1&c42=1&c63=1&c77=1&c9=1&sec=jax&c2=1&c100=1
2016-10-03 22:04:04 DEBUG    SEARCHQUEUE-MANUAL-75897 :: [SceneTime] :: GET URL: https://www.scenetime.com/login.php [Status: 200]
2016-10-03 22:04:04 ERROR    SEARCHQUEUE-MANUAL-75897 :: [SceneTime] :: [d7e460e] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'next_element'",)
Traceback (most recent call last):
  File "c:\sickrage\sickbeard\search.py", line 489, in searchProviders
    searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
  File "c:\sickrage\sickrage\providers\GenericProvider.py", line 152, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "c:\sickrage\sickbeard\providers\scenetime.py", line 106, in search
    labels = [label.get_text(strip=True) for label in torrent_rows[0]('td')]
  File "c:\sickrage\lib\bs4\element.py", line 988, in __call__
    return self.find_all(*args, **kwargs)
  File "c:\sickrage\lib\bs4\element.py", line 1259, in find_all
    return self._find_all(name, attrs, text, limit, generator, **kwargs)
  File "c:\sickrage\lib\bs4\element.py", line 529, in _find_all
    return ResultSet(strainer, result)
  File "c:\sickrage\lib\bs4\element.py", line 1724, in __init__
    super(ResultSet, self).__init__(result)
  File "c:\sickrage\lib\bs4\element.py", line 526, in <genexpr>
    result = (element for element in generator
  File "c:\sickrage\lib\bs4\element.py", line 1277, in descendants
    current = current.next_element
AttributeError: 'NoneType' object has no attribute 'next_element'
2016-10-03 22:04:04 DEBUG    SEARCHQUEUE-MANUAL-75897 :: [SceneTime] :: Traceback (most recent call last):
  File "c:\sickrage\sickbeard\search.py", line 489, in searchProviders
    searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
  File "c:\sickrage\sickrage\providers\GenericProvider.py", line 152, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "c:\sickrage\sickbeard\providers\scenetime.py", line 106, in search
    labels = [label.get_text(strip=True) for label in torrent_rows[0]('td')]
  File "c:\sickrage\lib\bs4\element.py", line 988, in __call__
    return self.find_all(*args, **kwargs)
  File "c:\sickrage\lib\bs4\element.py", line 1259, in find_all
    return self._find_all(name, attrs, text, limit, generator, **kwargs)
  File "c:\sickrage\lib\bs4\element.py", line 529, in _find_all
    return ResultSet(strainer, result)
  File "c:\sickrage\lib\bs4\element.py", line 1724, in __init__
    super(ResultSet, self).__init__(result)
  File "c:\sickrage\lib\bs4\element.py", line 526, in <genexpr>
    result = (element for element in generator
  File "c:\sickrage\lib\bs4\element.py", line 1277, in descendants
    current = current.next_element
AttributeError: 'NoneType' object has no attribute 'next_element'

2016-10-03 22:04:04 WARNING  SEARCHQUEUE-MANUAL-75897 :: [SceneTime] :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.
2016-10-03 22:04:04 DEBUG    SEARCHQUEUE-MANUAL-75897 :: formatting pattern: %SN - S%0SE%0E - %EN -> South Park - S20E03 - The Damned
2016-10-03 22:04:04 DEBUG    SEARCHQUEUE-MANUAL-75897 :: formatting pattern: %SN - S%0SE%0E - %EN -> South Park - S20E03 - The Damned
2016-10-03 22:04:04 INFO     SEARCHQUEUE-MANUAL-75897 :: Unable to find a download for: [South Park - S20E03 - The Damned]
2016-10-03 22:04:20 DEBUG    SEARCHQUEUE-MANUAL-281620 :: formatting pattern: %SN - S%0SE%0E - %EN -> How to Get Away with Murder - S03E02 - There Are Worse Things Than Murder
2016-10-03 22:04:20 INFO     SEARCHQUEUE-MANUAL-281620 :: Beginning manual search for: [How to Get Away with Murder - S03E02 - There Are Worse Things Than Murder]
2016-10-03 22:04:20 DEBUG    SEARCHQUEUE-MANUAL-281620 :: [SceneTime] :: Search Mode: RSS
2016-10-03 22:04:21 DEBUG    SEARCHQUEUE-MANUAL-281620 :: [SceneTime] :: POST URL: https://www.scenetime.com/browse_API.php [Status: 302]
2016-10-03 22:04:21 DEBUG    SEARCHQUEUE-MANUAL-281620 :: [SceneTime] :: With post data: c79=1&cata=yes&search=&c83=1&c42=1&c63=1&c77=1&c9=1&sec=jax&c2=1&c100=1
2016-10-03 22:04:21 DEBUG    SEARCHQUEUE-MANUAL-281620 :: [SceneTime] :: GET URL: https://www.scenetime.com/login.php [Status: 200]
2016-10-03 22:04:21 DEBUG    SEARCHQUEUE-MANUAL-281620 :: [SceneTime] :: Error while searching SceneTime, skipping: AttributeError("'NoneType' object has no attribute 'next_element'",)
2016-10-03 22:04:21 INFO     SEARCHQUEUE-MANUAL-281620 :: [SceneTime] :: Performing episode search for How to Get Away with Murder
2016-10-03 22:04:22 DEBUG    SEARCHQUEUE-MANUAL-281620 :: [SceneTime] :: Search Mode: Episode
2016-10-03 22:04:22 DEBUG    SEARCHQUEUE-MANUAL-281620 :: [SceneTime] :: Search string: How to Get Away with Murder S03E02
2016-10-03 22:04:22 DEBUG    SEARCHQUEUE-MANUAL-281620 :: [SceneTime] :: POST URL: https://www.scenetime.com/browse_API.php [Status: 302]
2016-10-03 22:04:22 DEBUG    SEARCHQUEUE-MANUAL-281620 :: [SceneTime] :: With post data: c79=1&cata=yes&search=How+to+Get+Away+with+Murder+S03E02&c83=1&c42=1&c63=1&c77=1&c9=1&sec=jax&c2=1&c100=1
2016-10-03 22:04:23 DEBUG    SEARCHQUEUE-MANUAL-281620 :: [SceneTime] :: GET URL: https://www.scenetime.com/login.php [Status: 200]
2016-10-03 22:04:23 ERROR    SEARCHQUEUE-MANUAL-281620 :: [SceneTime] :: [d7e460e] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'next_element'",)
Traceback (most recent call last):
  File "c:\sickrage\sickbeard\search.py", line 489, in searchProviders
    searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
  File "c:\sickrage\sickrage\providers\GenericProvider.py", line 152, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "c:\sickrage\sickbeard\providers\scenetime.py", line 106, in search
    labels = [label.get_text(strip=True) for label in torrent_rows[0]('td')]
  File "c:\sickrage\lib\bs4\element.py", line 988, in __call__
    return self.find_all(*args, **kwargs)
  File "c:\sickrage\lib\bs4\element.py", line 1259, in find_all
    return self._find_all(name, attrs, text, limit, generator, **kwargs)
  File "c:\sickrage\lib\bs4\element.py", line 529, in _find_all
    return ResultSet(strainer, result)
  File "c:\sickrage\lib\bs4\element.py", line 1724, in __init__
    super(ResultSet, self).__init__(result)
  File "c:\sickrage\lib\bs4\element.py", line 526, in <genexpr>
    result = (element for element in generator
  File "c:\sickrage\lib\bs4\element.py", line 1277, in descendants
    current = current.next_element
AttributeError: 'NoneType' object has no attribute 'next_element'
2016-10-03 22:04:23 DEBUG    SEARCHQUEUE-MANUAL-281620 :: [SceneTime] :: Traceback (most recent call last):
  File "c:\sickrage\sickbeard\search.py", line 489, in searchProviders
    searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
  File "c:\sickrage\sickrage\providers\GenericProvider.py", line 152, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "c:\sickrage\sickbeard\providers\scenetime.py", line 106, in search
    labels = [label.get_text(strip=True) for label in torrent_rows[0]('td')]
  File "c:\sickrage\lib\bs4\element.py", line 988, in __call__
    return self.find_all(*args, **kwargs)
  File "c:\sickrage\lib\bs4\element.py", line 1259, in find_all
    return self._find_all(name, attrs, text, limit, generator, **kwargs)
  File "c:\sickrage\lib\bs4\element.py", line 529, in _find_all
    return ResultSet(strainer, result)
  File "c:\sickrage\lib\bs4\element.py", line 1724, in __init__
    super(ResultSet, self).__init__(result)
  File "c:\sickrage\lib\bs4\element.py", line 526, in <genexpr>
    result = (element for element in generator
  File "c:\sickrage\lib\bs4\element.py", line 1277, in descendants
    current = current.next_element
AttributeError: 'NoneType' object has no attribute 'next_element'

2016-10-03 22:04:23 WARNING  SEARCHQUEUE-MANUAL-281620 :: [SceneTime] :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.
2016-10-03 22:04:23 DEBUG    SEARCHQUEUE-MANUAL-281620 :: formatting pattern: %SN - S%0SE%0E - %EN -> How to Get Away with Murder - S03E02 - There Are Worse Things Than Murder
2016-10-03 22:04:23 DEBUG    SEARCHQUEUE-MANUAL-281620 :: formatting pattern: %SN - S%0SE%0E - %EN -> How to Get Away with Murder - S03E02 - There Are Worse Things Than Murder
2016-10-03 22:04:23 INFO     SEARCHQUEUE-MANUAL-281620 :: Unable to find a download for: [How to Get Away with Murder - S03E02 - There Are Worse Things Than Murder]
```

**Comment by zhimsel** [comment]
+1 Having the same issue on Archlinux

**Comment by zhimsel** [comment]
Confirmed that switching back to the tag `2016.09.10-1` fixes the issue, so it must have been introduced since then.

**Comment by AubreyKloppers** [comment]
I am also getting this in my logs and it has been happening for at least a month...

AA AAAttributeError: 'NoneType' object has no attribute 'next_element' AA current = current.next_element AA File "/opt/sickbeard/lib/bs4/element.py", line 1277, in descendants AA result = (element for element in generator AA File "/opt/sickbeard/lib/bs4/element.py", line 526, in  AA super(ResultSet, self).__init__(result) AA File "/opt/sickbeard/lib/bs4/element.py", line 1724, in __init__ AA return ResultSet(strainer, result) AA File "/opt/sickbeard/lib/bs4/element.py", line 529, in _find_all AA return self._find_all(name, attrs, text, limit, generator, **kwargs) AA File "/opt/sickbeard/lib/bs4/element.py", line 1259, in find_all AA return self.find_all(*args, **kwargs) AA File "/opt/sickbeard/lib/bs4/element.py", line 988, in __call__ AA labels = [label.get_text(strip=True) for label in torrent_rows[0]('td')] AA File "/opt/sickbeard/sickbeard/providers/scenetime.py", line 106, in search AA items_list += self.search(search_string, ep_obj=episode) AA File "/opt/sickbeard/sickrage/providers/GenericProvider.py", line 152, in find_search_results AA searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality) AA File "/opt/sickbeard/sickbeard/search.py", line 489, in searchProviders 2016-10-04 08:31:31 ERROR SEARCHQUEUE-BACKLOG-295829 :: [SceneTime] :: [d7e460e] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'next_element'",)

**Comment by AubreyKloppers** [comment]
I also get in my logs:
2016-10-04 08:43:43 SEARCHQUEUE-BACKLOG-287247 :: [SceneTime] :: [d7e460e] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'next_element'",) 2016-10-04 08:42:02 SEARCHQUEUE-BACKLOG-300658 :: [SceneTime] :: [d7e460e] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'next_element'",) 2016-10-04 08:41:35 SEARCHQUEUE-BACKLOG-75805 :: [SceneTime] :: [d7e460e] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'next_element'",)

**Comment by kyneticx** [comment]
yeahh.. so i think ive cracked it.. theyve added a captcha to their login page - which breaks the initial login to the site so when it goes to run the search its getting the login.php as a result rather than the expected result of the list of torrents..  im going to talk to the site admins and see if theres something that can be arranged in order to fix this particular issue.. will get back to you guys with what they tell me :)

**Comment by Dracozny** [comment]
But if it's a captcha then why does the tag from last month work?

**Comment by kyneticx** [comment]
yeah.. i couldnt get that commit to work.. :/ ended up with the exact same error... and just to be sure i was using the write commit i grabbed the entire commit as a zip and set it up from scratch... so not exactly sure whats changed there...  ill dig deeper but the captcha makes sense as thats definitely a recent adition

**Comment by miigotu** [comment]
Its the captcha. Someone was supposed to be contacting them about their api login page not working.

**Comment by Dracozny** [comment]
One of the admins is aware of it as it is affecting couch potato users as
well. They haven't given an eta on a solution.

**Comment by bjornhamra** [comment]
Maybe we should look into enabling cookie based authentication with scenetime similar to for example TorrentDay. I might submit a PR for it if I get around to it anytime soon.

**Comment by thibmaek** [comment]
Even though after updating and reading the changelog from pr #2335 : (`providers/scenetime: Fix broken search after site changes (#2335)`) I can confirm it still doesn't work and still produces the error:

`2016-10-19 10:41:23 SEARCHQUEUE-MANUAL-248682 :: [SceneTime] :: [57c3a7a] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'next_element'",)`

**Comment by miigotu** [comment]
Read the issue before you comment useless information please. https://github.com/SickRage/SickRage/issues/2407#issuecomment-252543812

**Comment by thibmaek** [comment]
@miigotu aha, I thought #2335 fixed it with cookie auth but seems that pr is solely for searching their DB.

**Comment by miigotu** [comment]
Just pushed a commit to enable adding cookies in scenetime settings. Hope it works =P

**Comment by thibmaek** [comment]
This might be a slightly off topic question but do I set the cookie as JSON in the input field?
`{uid: val, pass: val}` or something else?

**Comment by miigotu** [comment]
```uid=xxxxx;pass=yyyyy```

**Comment by bjornhamra** [comment]
Yes, my previous PR solved a different problem, this was before ST introduced recaptcha.

@miigotu's latest commit works for me, cheers 👍

**Comment by Dracozny** [comment]
Please forgive my ignorance, but this fix went over my head. I pulled the values from the site cookie via chrome developer but they are not 5 characters in length and I get a failed to log in warning.

**Comment by bjornhamra** [comment]
@Dracozny Sounds like you're doing it just about right, amount of chars will vary. Just extract the uid and pass fields, the other ones are irrelevant. Also; the cookie you pull from chrome will have a space between the key/value pairs, ie `uid=xxxx; pass=xxxx` - make sure to remove that space when adding the cookie in the settings.

**Comment by Dracozny** [comment]
I didn't see a space they are tabbed fields that I cannot copy directly, so now I think I am looking in the wrong place.

**Comment by bjornhamra** [comment]
Perhaps even easier; just use Javascript console: `document.cookie.replace(/ /g,"")` and copy the result.

**Comment by miigotu** [comment]
open chrome dev tools, click the console tab, type:
```javascript
document.cookie.replace(/ /g,"").match(/uid=\w*;pass=[\w]*/)[0]
```

**Comment by Dracozny** [comment]
that produced the same values which were easier to copy and paste. I don't see an error or warning so I will assume it's working. Thanks miigotu.

**Comment by thibmaek** [comment]
I got the warning in the Sickrage logs too but seems it fixed itself like in your case @Dracozny .
