### ISSUE TITLE
Post proccessing halted

### ISSUE THREAD

**Issue by titomontes** [SickRage/SickRage#2429]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master/d7e460ee1fee1be796e5195ee3b104afc1d2c0c7
OS: Win10 64b
What you did: Manual post proccessing
What happened: Postprocessing halted, no post proccessing working at all (auto/manual)
What you expected: 
Logs:
```
Error

'charmap' codec can't decode byte 0x81 in position 3: character maps to

Traceback

Traceback (most recent call last): 
File "C:\Program Files\SickRage\lib\tornado\web.py", line 1415, in _execute result = yield result 
File "C:\Program Files\SickRage\lib\tornado\gen.py", line 870, in run value = future.result() 
File "C:\Program Files\SickRage\lib\tornado\concurrent.py", line 215, in result raise_exc_info(self._exc_info) 
File "C:\Program Files\SickRage\lib\tornado\gen.py", line 876, in run yielded = self.gen.throw(*exc_info) 
File "C:\Program Files\SickRage\sickbeard\webserve.py", line 254, in get results = yield self.async_call(method) 
File "C:\Program Files\SickRage\lib\tornado\gen.py", line 870, in run value = future.result() 
File "C:\Program Files\SickRage\lib\concurrent\futures\_base.py", line 400, in result return self.__get_result() 
File "C:\Program Files\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "C:\Program Files\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "C:\Program Files\SickRage\lib\concurrent\futures\thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "C:\Program Files\SickRage\sickbeard\webserve.py", line 270, in async_call result = function(**kwargs) 
File "C:\Program Files\SickRage\sickbeard\webserve.py", line 2298, in processEpisode is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type 
File "C:\Program Files\SickRage\sickbeard\processTV.py", line 251, in processDir for curDir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]: 
File "C:\Program Files\SickRage\sickbeard\processTV.py", line 393, in validateDir NameParser().parse(video, cache_result=False) 
File "C:\Program Files\SickRage\sickbeard\name_parser\parser.py", line 461, in parse name, file_name_result or dir_name_result)) 
File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode return codecs.charmap_decode(input,errors,decoding_table) 
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3: character maps to 

Request Info

body: proc_dir=D%3A%5CDownloads&process_method=move&delete_on=on
files: {}
protocol: http
connection: 
body_arguments: {'proc_dir': ['D:\\Downloads'], 'delete_on': ['on'], 'process_method': ['move']}
uri: /home/postprocess/processEpisode
query_arguments: {}
_start_time: 1475538103.02
headers: {'Origin': 'http://************************', 'Content-Length': '58', 'Accept-Language': 'es,en-US;q=0.8,en;q=0.6', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Dnt': '1', 'Host': '************************:8081', 'Referer': 'http://************************/home/postprocess/', 'Cache-Control': 'max-age=0', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded'}
host: ************************:8081
version: HTTP/1.1
arguments: {'proc_dir': 'D:\\Downloads', 'delete_on': 'on', 'process_method': 'move'}
_finish_time: None
query: 
path: /home/postprocess/processEpisode
method: POST
remote_ip: **.**.**.***
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
You are most certainly not on commit d7e460ee1fee1be796e5195ee3b104afc1d2c0c7
That code you posted is from SickRageTV, not this fork.

**Comment by OmgImAlexis** [comment]
@titomontes @miigotu I've replaced some of the strings in that since it shows his domain and he doesn't have a password set.

@titomontes I'd highly suggest you add a password since anyone with your domain can currently access your Sickrage install.
