### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by desmonio** [SickRage/SickRage#2444]
### INFO
Python Version: **2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]**
Operating System: **Darwin-13.4.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by desmonio** [comment]
### INFO
Python Version: **2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]**
Operating System: **Darwin-13.4.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-300835 :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by desmonio** [comment]
if selected rarbg
error again torrentproject

**Comment by desmonio** [comment]
you can not use Cpasbien or torrentproject

**Comment by desmonio** [comment]
loop stays looking and no download

**Comment by desmonio** [comment]
sorry for my English translator

**Comment by desmonio** [comment]
2016-10-08 10:57:18 WARNING SEARCHQUEUE-MANUAL-311713 :: Failed to download any results 2016-10-08 10:57:18 INFO SEARCHQUEUE-MANUAL-311713 :: Request failed: 404 Client Error: Not Found for url: http://thetorrent.org/torrent/BEE1B671DD2E60DC64D5AD768A7ECD3E61BDB1B7.torrent 2016-10-08 10:57:17 INFO SEARCHQUEUE-MANUAL-311713 :: Downloading a result from ThePirateBay at http://thetorrent.org/torrent/BEE1B671DD2E60DC64D5AD768A7ECD3E61BDB1B7.torrent 2016-10-08 10:57:17 WARNING SEARCHQUEUE-MANUAL-311713 :: Could not download http://torrentproject.se/torrent/BEE1B671DD2E60DC64D5AD768A7ECD3E61BDB1B7.torrent 2016-10-08 10:57:11 INFO SEARCHQUEUE-MANUAL-311713 :: Downloading a result from ThePirateBay at http://torrentproject.se/torrent/BEE1B671DD2E60DC64D5AD768A7ECD3E61BDB1B7.torrent 2016-10-08 10:57:11 INFO SEARCHQUEUE-MANUAL-311713 :: Request failed: 404 Client Error: Not Found for url: http://btdig.com/torrent/BEE1B671DD2E60DC64D5AD768A7ECD3E61BDB1B7.torrent

**Comment by desmonio** [comment]
hello, if I have the same problem.
when torrenten providers of piratebay or rargb are marked.
report same all the time, you can not download torrentproject.se.
this blocks other torrent searches and no discharge occurs.
when you remove pirate and rargb and some other works again.
I have not checked one by one but the error give it with several.
sorry for my English by google translator.

**Comment by nicknd** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-254203 :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by nicknd** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-276536 :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ChromevoidGit** [comment]
### INFO
Python Version: **2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Thanatosgratus** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.4.0-24-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Thanatosgratus** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.4.0-24-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-253982 :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Thanatosgratus** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.4.0-24-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-72762 :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Thanatosgratus** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.4.0-24-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-250071 :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Thanatosgratus** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.4.0-24-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-308045 :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Thanatosgratus** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.4.0-24-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-283468 :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by trancen** [comment]
### INFO
Python Version: **2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]**
Operating System: **Linux-2.6.32-042stab108.8-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-307341 :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by trancen** [comment]
### INFO
Python Version: **2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]**
Operating System: **Linux-2.6.32-042stab108.8-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-295557 :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by elvenpath** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 11:15:51) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by elvenpath** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 11:15:51) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-269533 :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by elvenpath** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 11:15:51) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295829 :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by elvenpath** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 11:15:51) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-289590 :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by elvenpath** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 11:15:51) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295515 :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by elvenpath** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 11:15:51) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dc765c90bc3337ce0d3ed73ffe7424d176a9858d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-272644 :: [Cpasbien] :: [dc765c9] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by studio-es-lee** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  5 2016, 18:57:05) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@fc59f23c105551f513fc78757f9636a8a5d08b15
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [Cpasbien] :: [fc59f23] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by studio-es-lee** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  5 2016, 18:57:05) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@fc59f23c105551f513fc78757f9636a8a5d08b15
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Cpasbien] :: [fc59f23] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ezar** [comment]
+1 same error.

**Comment by Thanatosgratus** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.4.0-24-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@fc59f23c105551f513fc78757f9636a8a5d08b15
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-76177 :: [Cpasbien] :: [fc59f23] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Thanatosgratus** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.4.0-24-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@fc59f23c105551f513fc78757f9636a8a5d08b15
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Cpasbien] :: [fc59f23] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by krash1220** [comment]
### INFO
Python Version: **2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-38-generic-x86_64-with-LinuxMint-18-sarah**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6a023791556047f7ce04cd6b5185d41ed212bd84
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Cpasbien] :: [6a02379] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by trancen** [comment]
### INFO
Python Version: **2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]**
Operating System: **Linux-2.6.32-042stab108.8-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@6a023791556047f7ce04cd6b5185d41ed212bd84
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-141181 :: [Cpasbien] :: [6a02379] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by trancen** [comment]
### INFO
Python Version: **2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]**
Operating System: **Linux-2.6.32-042stab108.8-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@6a023791556047f7ce04cd6b5185d41ed212bd84
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-273761 :: [Cpasbien] :: [6a02379] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by trancen** [comment]
### INFO
Python Version: **2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]**
Operating System: **Linux-2.6.32-042stab108.8-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@6a023791556047f7ce04cd6b5185d41ed212bd84
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-307341 :: [Cpasbien] :: [6a02379] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by trancen** [comment]
### INFO
Python Version: **2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]**
Operating System: **Linux-2.6.32-042stab108.8-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@6a023791556047f7ce04cd6b5185d41ed212bd84
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-295557 :: [Cpasbien] :: [6a02379] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by trancen** [comment]
### INFO
Python Version: **2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]**
Operating System: **Linux-2.6.32-042stab108.8-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@6a023791556047f7ce04cd6b5185d41ed212bd84
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-283215 :: [Cpasbien] :: [6a02379] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
and none of you provide logs...

**Comment by HorusPi** [comment]
$ tail -40 sickrage.log
2016-10-09 18:47:54 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [TorrentProject] :: Search string: Sucesor designado S01E01
2016-10-09 18:47:54 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [TorrentProject] :: GET URL: https://torrentproject.se/?filter=2101&s=Sucesor+designado+S01E01&showmagnets=on&num=50&out=json [Status: 503]
2016-10-09 18:47:59 ERROR    SEARCHQUEUE-MANUAL-311876 :: [TorrentProject] :: [6a02379] Request failed: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/helpers.py", line 1443, in handle_requests_exception
    raise requests_exception
AttributeError: 'NoneType' object has no attribute 'group'
2016-10-09 18:47:59 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [TorrentProject] :: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/helpers.py", line 1443, in handle_requests_exception
    raise requests_exception
AttributeError: 'NoneType' object has no attribute 'group'

2016-10-09 18:47:59 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [TorrentProject] :: Data returned from provider does not contain any torrents
2016-10-09 18:47:59 INFO     SEARCHQUEUE-MANUAL-311876 :: [LimeTorrents] :: Performing episode search for Sucesor designado
2016-10-09 18:47:59 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [LimeTorrents] :: Search Mode: Episode
2016-10-09 18:47:59 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [LimeTorrents] :: Search string: Sucesor designado S01E01
2016-10-09 18:47:59 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [LimeTorrents] :: GET URL: https://www.limetorrents.cc/searchrss/20/Sucesor%20designado%20S01E01 [Status: 301]
2016-10-09 18:47:59 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [LimeTorrents] :: GET URL: http://www.limetorrents.cc/searchrss/20/Sucesor%20designado%20S01E01/ [Status: 301]
2016-10-09 18:48:00 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [LimeTorrents] :: GET URL: https://www.limetorrents.cc/searchrss/20/Sucesor%20designado%20S01E01/ [Status: 200]
2016-10-09 18:48:00 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [LimeTorrents] :: No data returned from provider
2016-10-09 18:48:00 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [NyaaTorrents] :: Sucesor designado is not an anime, skipping
2016-10-09 18:48:00 INFO     SEARCHQUEUE-MANUAL-311876 :: [ExtraTorrent] :: Performing episode search for Sucesor designado
2016-10-09 18:48:00 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [ExtraTorrent] :: Search Mode: Episode
2016-10-09 18:48:00 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [ExtraTorrent] :: Search string: Sucesor designado S01E01
2016-10-09 18:48:00 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [ExtraTorrent] :: GET URL: http://extratorrent.cc/rss.xml?search=Sucesor+designado+S01E01&type=search&cid=8 [Status: 200]
2016-10-09 18:48:00 INFO     SEARCHQUEUE-MANUAL-311876 :: [ThePirateBay] :: Performing episode search for Sucesor designado
2016-10-09 18:48:00 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [ThePirateBay] :: Search Mode: Episode
2016-10-09 18:48:00 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [ThePirateBay] :: Search string: Sucesor designado S01E01
2016-10-09 18:48:00 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [ThePirateBay] :: GET URL: https://thepiratebay.se/s/?q=Sucesor+designado+S01E01&orderby=7&category=200&type=search&page=0 [Status: 301]
2016-10-09 18:48:01 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [ThePirateBay] :: GET URL: https://thepiratebay.org/s/?q=Sucesor+designado+S01E01&orderby=7&category=200&type=search&page=0 [Status: 302]
2016-10-09 18:48:04 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [ThePirateBay] :: GET URL: https://thepiratebay.org/search/Sucesor%20designado%20S01E01/0/7/200 [Status: 200]
2016-10-09 18:48:04 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [ThePirateBay] :: Data returned from provider does not contain any torrents
2016-10-09 18:48:04 INFO     SEARCHQUEUE-MANUAL-311876 :: [Rarbg] :: Performing episode search for Sucesor designado
2016-10-09 18:48:04 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [Rarbg] :: Search Mode: Episode
2016-10-09 18:48:04 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [Rarbg] :: Search string: Sucesor designado S01E01
2016-10-09 18:48:06 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [Rarbg] :: GET URL: http://torrentapi.org/pubapi_v2.php?sort=seeders&min_leechers=0&min_seeders=1&search_tvdb=311876&app_id=sickrage2&search_string=Sucesor+designado+S01E01&ranked=1&category=tv&format=json_extended&token=lyc0zfuogj&limit=100&mode=search [Status: 200]
2016-10-09 18:48:06 DEBUG    SEARCHQUEUE-MANUAL-311876 :: [TokyoToshokan] :: Sucesor designado is not an anime, skipping
2016-10-09 18:48:06 DEBUG    SEARCHQUEUE-MANUAL-311876 :: formatting pattern: %SN - S%0SE%0E - %EN -> Sucesor designado - S01E01 - Piloto
2016-10-09 18:48:07 DEBUG    SEARCHQUEUE-MANUAL-311876 :: formatting pattern: %SN - S%0SE%0E - %EN -> Sucesor designado - S01E01 - Piloto
2016-10-09 18:48:07 INFO     SEARCHQUEUE-MANUAL-311876 :: Unable to find a download for: [Sucesor designado - S01E01 - Piloto]
$

**Comment by trancen** [comment]
2016-10-09 22:17:54 DEBUG SEARCHQUEUE-MANUAL-295557 :: [BTDigg] :: Requested a json response but response was not json, check the url: https://api.btdigg.org/api/private-341ada3245790954/s02 2016-10-09 22:17:54 DEBUG SEARCHQUEUE-MANUAL-295557 :: [BTDigg] :: GET URL: https://api.btdigg.org/cgi-sys/suspendedpage.cgi?q=x264&p=0&order=2 [Status: 200] 2016-10-09 22:17:54 DEBUG SEARCHQUEUE-MANUAL-295557 :: [BTDigg] :: GET URL: https://api.btdigg.org/api/private-341ada3245790954/s02?q=x264&p=0&order=2 [Status: 302] 2016-10-09 22:17:42 DEBUG SEARCHQUEUE-MANUAL-295557 :: [BTDigg] :: Search Mode: RSS 2016-10-09 22:17:42 DEBUG SEARCHQUEUE-MANUAL-295557 :: [TorrentProject] :: Data returned from provider does not contain any torrents AA AAAttributeError: 'NoneType' object has no attribute 'group' AA raise requests_exception AA File "/var/www/sickrage/sickbeard/helpers.py", line 1443, in handle_requests_exception 2016-10-09 22:17:42 DEBUG SEARCHQUEUE-MANUAL-295557 :: [TorrentProject] :: Traceback (most recent call last): AAAttributeError: 'NoneType' object has no attribute 'group' AA raise requests_exception AA File "/var/www/sickrage/sickbeard/helpers.py", line 1443, in handle_requests_exception AATraceback (most recent call last): 2016-10-09 22:17:42 ERROR SEARCHQUEUE-MANUAL-295557 :: [TorrentProject] :: [6a02379] Request failed: 'NoneType' object has no attribute 'group' 2016-10-09 22:17:37 DEBUG SEARCHQUEUE-MANUAL-295557 :: [TorrentProject] :: GET URL: https://torrentproject.se/?filter=2101&s=0day&showmagnets=on&num=50&out=json [Status: 503] 2016-10-09 22:17:37 DEBUG SEARCHQUEUE-MANUAL-295557 :: [TorrentProject] :: Search Mode: RSS 2016-10-09 22:17:37 DEBUG SEARCHQUEUE-MANUAL-295557 :: [HorribleSubs] :: Unable to match Mahou.Shoujo.Ikusei.Keikaku.-.02.[1080p] to a show in your database. Parser result: Mahou Shoujo Ikusei Keikaku - [ABS: [2]] [ANIME VER: 1] [ABD: False] [ANIME: True] [whichReg: ['anime_standard']] 2016-10-09 22:17:37 DEBUG SEARCHQUEUE-MANUAL-295557 :: [HorribleSubs] :: Unable to match Mahou.Shoujo.Ikusei.Keikaku.-.02.[720p] to a show in your database. Parser result: Mahou Shoujo Ikusei Keikaku - [ABS: [2]] [ANIME VER: 1] [ABD: False] [ANIME: True] [whichReg: ['anime_standard']] 2016-10-09 22:17:37 DEBUG SEARCHQUEUE-MANUAL-295557 :: [HorribleSubs] :: Unable to match Mahou.Shoujo.Ikusei.Keikaku.-.02.[480p] to a show in your database. Parser result: Mahou Shoujo Ikusei Keikaku - [ABS: [2]] [ANIME VER: 1] [ABD: False] [ANIME: True] [whichReg: ['anime_standard']]

**Comment by trancen** [comment]
I'm still getting this error. And have updated to the latest version

**Comment by ThePieMan** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@d15b7003f8663b76d01fcbf0566389b2f31e0564
No Log available with ERRORS:
### ERROR
```
SHOWUPDATER :: [d15b700] Request failed: 'NoneType' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
