### ISSUE TITLE
Unable to start SickRage on Raspberry Pi

### ISSUE THREAD

**Issue by hopgoodpaul** [SickRage/SickRage#2452]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master / fc59f23c105551f513fc78757f9636a8a5d08b15
OS: Raspbian Jessie with Pixel
What you did: tried to start sickrage
What happened: received an error
What you expected: it to start
Logs:
```
$ python /home/pi/.sickrage/SickBeard.py --nolaunch --datadir=/home/pi/.sickrage
Traceback (most recent call last):
  File "/home/pi/.sickrage/SickBeard.py", line 92, in <module>
    import sickbeard
  File "/home/pi/.sickrage/sickbeard/__init__.py", line 40, in <module>
    from sickbeard.databases import mainDB, cache_db, failed_db
  File "/home/pi/.sickrage/sickbeard/databases/mainDB.py", line 34, in <module>
    from sickbeard import subtitles
  File "/home/pi/.sickrage/sickbeard/subtitles.py", line 33, in <module>
    import subliminal
  File "/home/pi/.sickrage/lib/subliminal/__init__.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/home/pi/.sickrage/lib/subliminal/core.py", line 17, in <module>
    from .extensions import provider_manager, refiner_manager
  File "/home/pi/.sickrage/lib/subliminal/extensions.py", line 98, in <module>
    'tvsubtitles = subliminal.providers.tvsubtitles:TVsubtitlesProvider'
  File "/home/pi/.sickrage/lib/subliminal/extensions.py", line 30, in __init__
    super(RegistrableExtensionManager, self).__init__(namespace, **kwargs)
  File "/home/pi/.sickrage/lib/stevedore/extension.py", line 93, in __init__
    verify_requirements)
  File "/home/pi/.sickrage/lib/stevedore/extension.py", line 156, in _load_plugins
    for ep in self._find_entry_points(self.namespace):
  File "/home/pi/.sickrage/lib/subliminal/extensions.py", line 34, in _find_entry_points
    eps = list(super(RegistrableExtensionManager, self)._find_entry_points(namespace))
  File "/home/pi/.sickrage/lib/stevedore/extension.py", line 149, in _find_entry_points
    eps = list(pkg_resources.iter_entry_points(namespace))
  File "/home/pi/.sickrage/lib/pkg_resources.py", line 480, in iter_entry_points
    entries = dist.get_entry_map(group)
  File "/home/pi/.sickrage/lib/pkg_resources.py", line 2233, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "/home/pi/.sickrage/lib/pkg_resources.py", line 2038, in parse_map
    for group, lines in data:
  File "/home/pi/.sickrage/lib/pkg_resources.py", line 2572, in split_sections
    raise ValueError("Invalid section heading", line)
ValueError: ('Invalid section heading', '[consO,e_raRipts]\x087(ee|A}\xa0wh%al.tOnl:-!Hf')
```

I'm pretty sure something is corrupt somewhere but I can't find where or know how to fix it. I've tried re-cloning the repo entirely and even re-installed the OS which made sickrage work once but then broke after a short time.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Looks like you have a corrupted install or other install on your system. the heading is `[console_scripts]`

**Comment by neoatomic** [comment]
Indeed this doesn't look good : 
`[consO,e_raRipts]\x087(ee|A}\xa0wh%al.tOnl:-!Hf')`

There are some guides in the wiki that might help you with the setup. : 
https://github.com/SickRage/SickRage/wiki/Installation-&-Configuration-Guides

Also make sure the locale is `utf-8`.
