### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by fookhk** [SickRage/SickRage#2466]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.23-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@21c9621a36dabe345fc4879200c3fba39b84c8ce
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [21c9621] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 387, in showPoster
    if which[0:6] == 'banner':
TypeError: 'NoneType' object has no attribute '__getitem__'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by fookhk** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.23-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@21c9621a36dabe345fc4879200c3fba39b84c8ce
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [21c9621] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 387, in showPoster
    if which[0:6] == 'banner':
TypeError: 'NoneType' object has no attribute '__getitem__'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fookhk** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.23-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@21c9621a36dabe345fc4879200c3fba39b84c8ce
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [21c9621] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 387, in showPoster
    if which[0:6] == 'banner':
TypeError: 'NoneType' object has no attribute '__getitem__'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fookhk** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.23-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@21c9621a36dabe345fc4879200c3fba39b84c8ce
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [21c9621] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 387, in showPoster
    if which[0:6] == 'banner':
TypeError: 'NoneType' object has no attribute '__getitem__'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fookhk** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.23-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@21c9621a36dabe345fc4879200c3fba39b84c8ce
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [21c9621] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 387, in showPoster
    if which[0:6] == 'banner':
TypeError: 'NoneType' object has no attribute '__getitem__'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fookhk** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.23-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@21c9621a36dabe345fc4879200c3fba39b84c8ce
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [21c9621] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 387, in showPoster
    if which[0:6] == 'banner':
TypeError: 'NoneType' object has no attribute '__getitem__'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fookhk** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.23-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@21c9621a36dabe345fc4879200c3fba39b84c8ce
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [21c9621] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 387, in showPoster
    if which[0:6] == 'banner':
TypeError: 'NoneType' object has no attribute '__getitem__'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fookhk** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.23-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@21c9621a36dabe345fc4879200c3fba39b84c8ce
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [21c9621] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 387, in showPoster
    if which[0:6] == 'banner':
TypeError: 'NoneType' object has no attribute '__getitem__'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Xandoyi** [comment]
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@412686d3365091bada426d77f789ebd34350ed96
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-320558 :: [YggTorrent] :: [412686d] Failed parsing provider YggTorrent.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Xandoyi** [comment]
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@412686d3365091bada426d77f789ebd34350ed96
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-300472 :: [YggTorrent] :: [412686d] Failed parsing provider YggTorrent.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Xandoyi** [comment]
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@412686d3365091bada426d77f789ebd34350ed96
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-270633 :: [YggTorrent] :: [412686d] Failed parsing provider YggTorrent.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Xandoyi** [comment]
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@412686d3365091bada426d77f789ebd34350ed96
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-78804 :: [YggTorrent] :: [412686d] Failed parsing provider YggTorrent.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Xandoyi** [comment]
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@412686d3365091bada426d77f789ebd34350ed96
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-263365 :: [YggTorrent] :: [412686d] Failed parsing provider YggTorrent.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Xandoyi** [comment]
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@412686d3365091bada426d77f789ebd34350ed96
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-274431 :: [YggTorrent] :: [412686d] Failed parsing provider YggTorrent.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Xandoyi** [comment]
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@412686d3365091bada426d77f789ebd34350ed96
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-274431 :: [YggTorrent] :: [412686d] Failed parsing provider YggTorrent.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fabzeh** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:28:10) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-270915 :: [SceneTime] :: [4b69468] Exception while searching SceneTime. Error: TypeError("'NoneType' object has no attribute '__getitem__'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fabzeh** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:28:10) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-333829 :: [SceneTime] :: [4b69468] Exception while searching SceneTime. Error: TypeError("'NoneType' object has no attribute '__getitem__'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fabzeh** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:28:10) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-190351 :: [SceneTime] :: [4b69468] Exception while searching SceneTime. Error: TypeError("'NoneType' object has no attribute '__getitem__'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fabzeh** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:28:10) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-146711 :: [SceneTime] :: [4b69468] Exception while searching SceneTime. Error: TypeError("'NoneType' object has no attribute '__getitem__'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fabzeh** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:28:10) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-321148 :: [SceneTime] :: [4b69468] Exception while searching SceneTime. Error: TypeError("'NoneType' object has no attribute '__getitem__'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fabzeh** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:28:10) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-81189 :: [SceneTime] :: [4b69468] Exception while searching SceneTime. Error: TypeError("'NoneType' object has no attribute '__getitem__'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fabzeh** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:28:10) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-318408 :: [SceneTime] :: [4b69468] Exception while searching SceneTime. Error: TypeError("'NoneType' object has no attribute '__getitem__'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fabzeh** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:28:10) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-285532 :: [SceneTime] :: [4b69468] Exception while searching SceneTime. Error: TypeError("'NoneType' object has no attribute '__getitem__'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fabzeh** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:28:10) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-264817 :: [SceneTime] :: [4b69468] Exception while searching SceneTime. Error: TypeError("'NoneType' object has no attribute '__getitem__'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fabzeh** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:28:10) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-293692 :: [SceneTime] :: [4b69468] Exception while searching SceneTime. Error: TypeError("'NoneType' object has no attribute '__getitem__'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fabzeh** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:28:10) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-159591 :: [SceneTime] :: [4b69468] Exception while searching SceneTime. Error: TypeError("'NoneType' object has no attribute '__getitem__'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fabzeh** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:28:10) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-287314 :: [SceneTime] :: [4b69468] Exception while searching SceneTime. Error: TypeError("'NoneType' object has no attribute '__getitem__'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fabzeh** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:28:10) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [SceneTime] :: [4b69468] Exception while searching propers in SceneTime, skipping: 'NoneType' object has no attribute '__getitem__'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [a760263] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 388, in showPoster
    if which[0:6] == 'banner':
TypeError: 'NoneType' object has no attribute '__getitem__'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
