### ISSUE TITLE
[APP SUBMITTED]: index() got an unexpected keyword argument ''

### ISSUE THREAD

**Issue by fookhk** [SickRage/SickRage#2468]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.23-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@21c9621a36dabe345fc4879200c3fba39b84c8ce
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [21c9621] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument ''

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by fookhk** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.46-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [7e6e057] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument ''

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fookhk** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.46-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [7e6e057] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument ''

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
