### ISSUE TITLE
[APP SUBMITTED]: no such column: scene_season

### ISSUE THREAD

**Issue by zyphermonkey** [SickRage/SickRage#2476]
### INFO
Python Version: **2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]**
Operating System: **Linux-4.4.19-unRAID-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@21c9621a36dabe345fc4879200c3fba39b84c8ce
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [21c9621] DB error: no such column: scene_season
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by zyphermonkey** [comment]
### INFO
Python Version: **2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]**
Operating System: **Linux-4.4.19-unRAID-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@21c9621a36dabe345fc4879200c3fba39b84c8ce
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [21c9621] Exception generated in thread POSTPROCESSER: no such column: scene_season
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by zyphermonkey** [comment]
### INFO
Python Version: **2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]**
Operating System: **Linux-4.4.19-unRAID-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@21c9621a36dabe345fc4879200c3fba39b84c8ce
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [21c9621] DB error: no such column: scene_season
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by zyphermonkey** [comment]
### INFO
Python Version: **2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]**
Operating System: **Linux-4.4.19-unRAID-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@21c9621a36dabe345fc4879200c3fba39b84c8ce
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [21c9621] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 1374, in displayShow
    xem_numbering=get_xem_numbering_for_show(indexerid, indexer),
  File "/app/sickrage/sickbeard/scene_numbering.py", line 388, in get_xem_numbering_for_show
    [indexer, indexer_id])
  File "/app/sickrage/sickbeard/db.py", line 287, in select
    sql_results = self.action(query, args, fetchall=True)
  File "/app/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/app/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: no such column: scene_season

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by zyphermonkey** [comment]
Every show in my show list show 0/0.
If I try and drill into a show I get an error page including the following:
`POSTPROCESSER :: [21c9621] DB error: no such column: scene_season`

I've already restarted the docker to no help. I also removed the docker and image and did a full reinstall from template (just to keep my settings). 

If I had to guess I'd say there were some changes introduced to webserve.py in the last release that caused this.

Let me know if I can provide any other info.

**Comment by zyphermonkey** [comment]
2016-10-16 22:06:45 ERROR Thread-14 :: [21c9621] Failed doing webui callback: Traceback (most recent call last): AAOperationalError: no such column: scene_season AA sql_results = self.connection.cursor().execute(query, args) AA File "/app/sickrage/sickbeard/db.py", line 108, in _execute AA sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone) AA File "/app/sickrage/sickbeard/db.py", line 257, in action AATraceback (most recent call last): 
2016-10-16 22:06:45 ERROR Thread-14 :: [21c9621] DB error: no such column: scene_season 
2016-10-16 22:06:45 DEBUG Thread-14 :: Looking up XEM scene mapping for show 300774 on theTVDB 
2016-10-16 22:05:21 DEBUG Thread-22 :: check_for_new_news: Checking GitHub for latest news. 
2016-10-16 22:05:21 INFO Thread-22 :: No update needed 
2016-10-16 22:05:21 DEBUG Thread-22 :: cur_commit = 21c9621a36dabe345fc4879200c3fba39b84c8ce, newest_commit = 21c9621a36dabe345fc4879200c3fba39b84c8ce, num_commits_behind = 0, num_commits_ahead = 0 
2016-10-16 22:05:21 DEBUG Thread-22 :: git rev-list --left-right "@{upstream}"...HEAD : returned successful 
2016-10-16 22:05:21 DEBUG Thread-22 :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /app/sickrage 
2016-10-16 22:05:21 DEBUG Thread-22 :: git rev-parse --verify --quiet "@{upstream}" : returned successful 
2016-10-16 22:05:21 DEBUG Thread-22 :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /app/sickrage 
2016-10-16 22:05:21 DEBUG Thread-22 :: git fetch origin : returned successful 
2016-10-16 22:05:21 DEBUG Thread-22 :: Executing git fetch origin with your shell in /app/sickrage 
2016-10-16 22:05:21 DEBUG Thread-22 :: git config remote.origin.pushurl https://github.com/zyphermonkey/SickRage.git : returned successful 
2016-10-16 22:05:21 DEBUG Thread-22 :: Executing git config remote.origin.pushurl https://github.com/zyphermonkey/SickRage.git with your shell in /app/sickrage 
2016-10-16 22:05:21 DEBUG Thread-22 :: git config remote.origin.url https://github.com/SickRage/SickRage.git : returned successful 
2016-10-16 22:05:21 DEBUG Thread-22 :: Executing git config remote.origin.url https://github.com/SickRage/SickRage.git with your shell in /app/sickrage 
2016-10-16 22:05:21 DEBUG Thread-22 :: git rev-parse HEAD : returned successful 
2016-10-16 22:05:21 DEBUG Thread-22 :: Executing git rev-parse HEAD with your shell in /app/sickrage 
2016-10-16 22:05:21 DEBUG Thread-22 :: git symbolic-ref -q HEAD : returned successful 
2016-10-16 22:05:21 DEBUG Thread-22 :: Executing git symbolic-ref -q HEAD with your shell in /app/sickrage

**Comment by OmgImAlexis** [comment]
Which docker container are you using?

**Comment by zyphermonkey** [comment]
![image](https://cloud.githubusercontent.com/assets/22804652/19423481/b518974e-93ee-11e6-8d5b-184012c8b158.png)

I just noticed that there is an update available that wasn't there when I created this issue. Should I update before we do anything else?

**Comment by zyphermonkey** [comment]
I updated and still have the same issue. There is a minor unraid update. Going to do that to see if it helps.

Is there anyway to repair the database?

**Comment by OmgImAlexis** [comment]
You'll have to wait for @miigotu to look at this as I'm not too sure. If you're okay with it I'd say backup your appdata directory, delete the whole container and appdata directory and reinstall it. Then just use the add existing show section to re-add your shows. That way you've got a clean DB. If that doesn't fix it then you can stop the container and just copy the backup appdata directory back and look into another way of fixing this.

**Comment by zyphermonkey** [comment]
I thought about doing that, but I'd rather not lose my show settings. I have a lot of shows and some are set to HD and others SD. I'd like to avoid resetting that at all costs.

**Comment by zyphermonkey** [comment]
I just gave up.
Turned of the docker
renamed the database
Turned on the docker
And added existing shows

Having to do all my HD/SD settings along with manually setting certain shows to paused and other random show stuff, but at least I'm auto downloading my shows again.

I still have the nonfunctional Database if any of the Devs want to look at it or want me to go back to it for testing.

**Comment by wyrickre** [comment]
This just hit me, too.  Exact same error.  Nothing works.
In an attempt to resolve the issue, I tried upgrading from linuxserver/sickrage to sickchill/sickchill since it was a thing I needed to do anyway....  It didn't help.  Same issue persists.  I have a *LOT* of shows.  Having to start over is going to suck.

**Comment by miigotu** [comment]
you don't have to start from scratch. Stop the SC service and delete cache.db, then start the service again.

**Comment by wyrickre** [comment]
Actually, it was more messed up than that.  I dug in and it appears that every schema update in mainDB.py to the tv_episodes table in sickbeard.db had failed.  It did, however, increment my db version all the way to 44.  Other schema updates to other tables appear to have succeeded just fine....  I have no idea how I got into this state.

I manually upgraded the tv_episodes table with the half dozen missing columns and was able to get the server working again.  It did lose all state of everything on disk, but I just re-scanned all files and did a full update on everything and now everything seems to be functioning again.

**Comment by miigotu** [comment]
@wyrickre that's crazy, lol. I don't see how that could happen unless it is something echelon is doing with his version and you came from his with that DB recently. Glad you got it sorted out though, but if it happens again we can try to track it down.
