### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by darkdragondraco** [SickRage/SickRage#2478]
### INFO

Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@21c9621a36dabe345fc4879200c3fba39b84c8ce
No Log available with ERRORS:
### ERROR

```
Thread-212 :: [21c9621] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 3965, in saveGeneral
    if not config.change_LOG_DIR(log_dir, web_log):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/config.py", line 112, in change_LOG_DIR
    abs_log_dir = ek(os.path.normpath, ek(os.path.join, sickbeard.DATA_DIR, log_dir))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'

```

---

_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Hujiin** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 12:07:24) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5443e1bec1404035218c5fc58c8ddedb97dbb88a
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [5443e1b] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 4233, in savePostProcessing
    if not config.change_TV_DOWNLOAD_DIR(tv_download_dir):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/config.py", line 182, in change_TV_DOWNLOAD_DIR
    if ek(os.path.normpath, sickbeard.TV_DOWNLOAD_DIR) != ek(os.path.normpath, tv_download_dir):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/usr/local/sickbeard-custom/env/lib/python2.7/posixpath.py", line 335, in normpath
    initial_slashes = path.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Tyrell66** [comment]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]**
Operating System: **Linux-3.10.102-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@abc6aab554715e57cf1668627a1f57f5b1ed4588
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [abc6aab] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 4107, in saveGeneral
    if not config.change_log_dir(log_dir, web_log):
  File "/app/sickrage/sickbeard/config.py", line 246, in change_log_dir
    abs_log_dir = ek(os.path.normpath, ek(os.path.join, sickbeard.DATA_DIR, log_dir))
  File "/app/sickrage/sickchill/helper/encoding.py", line 44, in ek
    result = function(*[ss(x) if isinstance(x, six.string_types) else x for x in args], **kwargs)
  File "/usr/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
