### ISSUE TITLE
LookupError: unknown encoding: ascii

### ISSUE THREAD

**Issue by BillVeusees** [SickRage/SickRage#2480]
Hi,

Sickrage does not start anymore, I get a weird error 
`LookupError: unknown encoding: ascii`

Branch/Commit: Latest Master and Develop

OS: Raspbian Wheezy

What you did: 
started sickrage as usual, observed crash, pull, reset and hard reset from both master and develop branches, and even fresh cloned the repo

What happened: crash 
LookupError: unknown encoding: ascii

What you expected:
No crash

Logs:
```
alex@fourmi ~/Medias/.apps $ git clone https://github.com/SickRage/SickRage.git sickrage2
Cloning into 'sickrage2'...
remote: Counting objects: 65400, done.
remote: Compressing objects: 100% (166/166), done.
remote: Total 65400 (delta 56), reused 0 (delta 0), pack-reused 65233
Receiving objects: 100% (65400/65400), 63.74 MiB | 2.21 MiB/s, done.
Resolving deltas: 100% (42092/42092), done.
Checking out files: 100% (3307/3307), done.

alex@fourmi ~/Medias/.apps $ python /home/alex/Medias/.apps/sickrage2/SickBeard.py -q --daemon
Traceback (most recent call last):
  File "/home/alex/Medias/.apps/sickrage2/SickBeard.py", line 92, in <module>
    import sickbeard
  File "/home/alex/Medias/.apps/sickrage2/sickbeard/__init__.py", line 38, in <module>
    from sickbeard.indexers import indexer_api
  File "/home/alex/Medias/.apps/sickrage2/sickbeard/indexers/__init__.py", line 21, in <module>
    from . import indexer_api
  File "/home/alex/Medias/.apps/sickrage2/sickbeard/indexers/indexer_api.py", line 26, in <module>
    from indexer_config import initConfig
  File "/home/alex/Medias/.apps/sickrage2/sickbeard/indexers/indexer_config.py", line 3, in <module>
    from tvdb_api.tvdb_api import Tvdb
  File "/home/alex/Medias/.apps/sickrage2/lib/tvdb_api/tvdb_api.py", line 24, in <module>
    import requests
  File "/home/alex/Medias/.apps/sickrage2/lib/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/home/alex/Medias/.apps/sickrage2/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 49, in <module>
    from ndg.httpsclient.ssl_peer_verification import SUBJ_ALT_NAME_SUPPORT
  File "/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/ssl_peer_verification.py", line 14, in <module>
    from ndg.httpsclient.subj_alt_name import SubjectAltName
  File "/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/subj_alt_name.py", line 15, in <module>
    from pyasn1.type import univ, constraint, char, namedtype, tag
  File "/home/alex/Medias/.apps/sickrage2/lib/pyasn1/type/univ.py", line 423, in <module>
    class Null(OctetString):
  File "/home/alex/Medias/.apps/sickrage2/lib/pyasn1/type/univ.py", line 424, in Null
    defaultValue = ''.encode()  # This is tightly constrained
LookupError: unknown encoding: ascii

```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Not sickrage related, your python install is broken. Try `python -V` and make sure it is version 2.7.x, otherwise start sickrage with `python2.7 /home/alex/Medias/.apps/sickrage2/SickBeard.py -q --daemon`

**Comment by BillVeusees** [comment]
alex@fourmi /etc/apt $ python -V
Python 2.7.3
alex@fourmi /etc/apt $ python2.7 /home/alex/Medias/.apps/sickrage2/SickBeard.py -q --daemon
Traceback (most recent call last):
  File "/home/alex/Medias/.apps/sickrage2/SickBeard.py", line 92, in <module>
    import sickbeard
  File "/home/alex/Medias/.apps/sickrage2/sickbeard/__init__.py", line 38, in <module>
    from sickbeard.indexers import indexer_api
  File "/home/alex/Medias/.apps/sickrage2/sickbeard/indexers/__init__.py", line 21, in <module>
    from . import indexer_api
  File "/home/alex/Medias/.apps/sickrage2/sickbeard/indexers/indexer_api.py", line 26, in <module>
    from indexer_config import initConfig
  File "/home/alex/Medias/.apps/sickrage2/sickbeard/indexers/indexer_config.py", line 3, in <module>
    from tvdb_api.tvdb_api import Tvdb
  File "/home/alex/Medias/.apps/sickrage2/lib/tvdb_api/tvdb_api.py", line 24, in <module>
    import requests
  File "/home/alex/Medias/.apps/sickrage2/lib/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/home/alex/Medias/.apps/sickrage2/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 49, in <module>
    from ndg.httpsclient.ssl_peer_verification import SUBJ_ALT_NAME_SUPPORT
  File "/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/ssl_peer_verification.py", line 14, in <module>
    from ndg.httpsclient.subj_alt_name import SubjectAltName
  File "/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/subj_alt_name.py", line 15, in <module>
    from pyasn1.type import univ, constraint, char, namedtype, tag
  File "/home/alex/Medias/.apps/sickrage2/lib/pyasn1/type/univ.py", line 423, in <module>
    class Null(OctetString):
  File "/home/alex/Medias/.apps/sickrage2/lib/pyasn1/type/univ.py", line 424, in Null
    defaultValue = ''.encode()  # This is tightly constrained
LookupError: unknown encoding: ascii

**Comment by miigotu** [comment]
YOUR PYTHON INSTALL IS BROKEN. AND YOU NEED 2.7.9-2.7.12.

**Comment by BillVeusees** [comment]
OK !! let's not loose our cool here :-/

I started by adressing 2 of your 3 points, (i.e. python version and command line) and I was reinstalling python, not knowing that you would be on a one minute response basis (which is rather cool so thanks for that).

After reinstalling /ugrading python, it works again.

As I have other python based services that still work normally, I think it is rather version related, but who knows,

Thanks for the tips

**Comment by miigotu** [comment]
Your other python based services simply dont require the standard built in ascii codeset for encoding. ascii is included with all versions of python. It was just a broken python install
