### ISSUE TITLE
Insecure string pickle, sickrage fails to launch

### ISSUE THREAD

**Issue by kvanhoorn** [SickRage/SickRage#2517]
Hi,

This is probably not the fault of SickRage itself, but it only occurs in your program.
Can you maybe tell me what's going wrong?

I have tried to use other python versions, other pickle version, don't import subtitles or sublimal, but the error keeps showing up.

Branch/Commit: Master/HEAD
OS: OSX
What you did: reboot sickbeard after pull
What happened: won't boot
What you expected: boot
Logs:

Traceback (most recent call last):
  File "SickBeard.py", line 91, in <module>
    import sickbeard
  File "/Users/kevin/Applications/SickRage/sickbeard/**init**.py", line 42, in <module>
    from sickbeard.config import CheckSection, check_setting_int, check_setting_str, \
  File "/Users/kevin/Applications/SickRage/sickbeard/config.py", line 27, in <module>
    from sickbeard import db, helpers, logger, naming
  File "/Users/kevin/Applications/SickRage/sickbeard/naming.py", line 27, in <module>
    from sickbeard import common, logger, tv
  File "/Users/kevin/Applications/SickRage/sickbeard/tv.py", line 48, in <module>
    from sickbeard import subtitles
  File "/Users/kevin/Applications/SickRage/sickbeard/subtitles.py", line 29, in <module>
    import subliminal
  File "/Users/kevin/Applications/SickRage/lib/subliminal/**init**.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/Users/kevin/Applications/SickRage/lib/subliminal/core.py", line 14, in <module>
    from rarfile import NotRarFile, RarCannotExec, RarFile
  File "/Users/kevin/Applications/SickRage/lib/rarfile/**init**.py", line 1972, in <module>
    custom_check([UNRAR_TOOL], True)
  File "/Users/kevin/Applications/SickRage/lib/rarfile/**init**.py", line 1920, in custom_check
    p = custom_popen(cmd)
  File "/Users/kevin/Applications/SickRage/lib/rarfile/**init**.py", line 1910, in custom_popen
    creationflags = creationflags)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 972, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by kvanhoorn** [comment]
I have detected the problem:

in the file lib/rarfile/__init__.py line 1910 it tries to import unrar, but Subprocess returns a ValueError instead of an OSError, which results in pickle to crash. This is probably an OSX issue only, I will try to install unrar to get rid of this error.
