### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: ''

### ISSUE THREAD

**Issue by megabitus98** [SickRage/SickRage#2521]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.21-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8bf53e8d03dc2b5bb946123dbaef2afb8667730c
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [8bf53e8] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2322, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "/opt/sickrage/sickbeard/processTV.py", line 231, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/opt/sickrage/sickbeard/processTV.py", line 551, in process_media
    result.result = processor.process()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 1042, in process
    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
  File "/opt/sickrage/sickbeard/helpers.py", line 1577, in verify_freespace
    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest if ek(os.path.exists, dest) else ek(os.path.dirname, dest)).st_dev:  # pylint: disable=no-member
  File "/opt/sickrage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 2] No such file or directory: ''

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by megabitus98** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.21-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8bf53e8d03dc2b5bb946123dbaef2afb8667730c
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [8bf53e8] Exception generated in thread POSTPROCESSER: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by megabitus98** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.21-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8bf53e8d03dc2b5bb946123dbaef2afb8667730c
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [8bf53e8] Exception generated in thread POSTPROCESSER: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by megabitus98** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.21-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8bf53e8d03dc2b5bb946123dbaef2afb8667730c
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [8bf53e8] Exception generated in thread POSTPROCESSER: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by demitrix** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  5 2016, 18:57:05) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@338c416542700141a6902ba17e9c13aaad7e6924
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [338c416] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2345, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 231, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 551, in process_media
    result.result = processor.process()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/postProcessor.py", line 1043, in process
    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1577, in verify_freespace
    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest if ek(os.path.exists, dest) else ek(os.path.dirname, dest)).st_dev:  # pylint: disable=no-member
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 2] No such file or directory: ''

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by demitrix** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  5 2016, 18:57:05) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@338c416542700141a6902ba17e9c13aaad7e6924
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [338c416] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2345, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 231, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 551, in process_media
    result.result = processor.process()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/postProcessor.py", line 1043, in process
    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1577, in verify_freespace
    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest if ek(os.path.exists, dest) else ek(os.path.dirname, dest)).st_dev:  # pylint: disable=no-member
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 2] No such file or directory: ''

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by demitrix** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  5 2016, 18:57:05) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@338c416542700141a6902ba17e9c13aaad7e6924
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [338c416] Exception generated in thread POSTPROCESSER: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
