### ISSUE TITLE
sqlite3.OperationalError: disk I/O error

### ISSUE THREAD

**Issue by mathieumd** [SickRage/SickRage#2522]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: develop 1749b20
OS: Ubuntu 14.04.4 LTS / Python 2.7.6
What you did: Nothing particular.
What happened: Sickrage wont start anymore.
What you expected: A restart from the last working uncorrupted database state.

When I try to start my SickRage installation, I get this error:
```
/etc/init.d/sickrage start
Traceback (most recent call last):
  File "SickBeard.py", line 562, in <module>
    SickRage().start()
  File "SickBeard.py", line 311, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/mnt/nas/sickrage/SickRage/sickbeard/__init__.py", line 1435, in initialize
    db.upgradeDatabase(main_db_con, mainDB.InitialSchema)
  File "/mnt/nas/sickrage/SickRage/sickbeard/db.py", line 424, in upgradeDatabase
    _processUpgrade(connection, schema)
  File "/mnt/nas/sickrage/SickRage/sickbeard/db.py", line 449, in _processUpgrade
    if not instance.test():
  File "/mnt/nas/sickrage/SickRage/sickbeard/databases/mainDB.py", line 307, in test
    return self.hasTable("db_version")
  File "/mnt/nas/sickrage/SickRage/sickbeard/db.py", line 471, in hasTable
    return len(self.connection.select("SELECT 1 FROM sqlite_master WHERE name = ?;", (tableName, ))) > 0
  File "/mnt/nas/sickrage/SickRage/sickbeard/db.py", line 287, in select
    sql_results = self.action(query, args, fetchall=True)
  File "/mnt/nas/sickrage/SickRage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/mnt/nas/sickrage/SickRage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
sqlite3.OperationalError: disk I/O error
```

It was working up until the day before. I had a network failure the previous night which may have cause a disconnect of the NAS hosting SickRage installation, which may have corrupt the database.

Now I'm trying to restore my SR installation. I tried to remove all *.db files, but still SickRage won't start, complaining about the same "disk I/O error". If I cannot do otherwise, I am OK to start with a fresh install and reconfigure everything manually, but removing all .db files does not seems to be enough. What should I do?

PS: I opened an account on the forum (https://www.sickrage.ca/forums/), but I did not received the confirmation email, therefore I cannot post there.

Thanks.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by mathieumd** [comment]
My bad, it was my NFS server which needed to be rebooted. Now Sickrage starts without problem.
