### ISSUE TITLE
UnicodeDecodeError exception in lib\tornado\web.py with GET /ui/get_messages byte 0x92 in position 43

### ISSUE THREAD

**Issue by LeeThompson** [SickRage/SickRage#2534]
Branch/Commit: master
OS: Windows 7 (x64)
What you did: Searched for shows
What happened: Error in log
What you expected: No error in log
Note; The search seems to be working ok, but this error just started appearing recently.    It seems like a Sickrage UI webserver error.    It seems to be related to a specific show perhaps.

One of the usenet indexers I use is private so I've redacted it's URL and name.

It's listed as `[Newznab Idx]` and `redactedurl.xxxx.net`

Logs:

```
2016-10-24 00:38:09 INFO     SEARCHQUEUE-MANUAL-78783 :: Unable to find a download for: [The Mysterious Cities of Gold - S03E01 - ]
2016-10-24 00:38:09 DEBUG    SEARCHQUEUE-MANUAL-78783 :: formatting pattern: %SN - S%0SE%0E - %EN -> The Mysterious Cities of Gold - S03E01 - 
2016-10-24 00:38:09 DEBUG    SEARCHQUEUE-MANUAL-78783 :: formatting pattern: %SN - S%0SE%0E - %EN -> The Mysterious Cities of Gold - S03E01 - 
2016-10-24 00:38:09 INFO     SEARCHQUEUE-MANUAL-78783 :: [NZBGeek] :: Performing season pack search for The Mysterious Cities of Gold
2016-10-24 00:38:09 DEBUG    SEARCHQUEUE-MANUAL-78783 :: [NZBGeek] :: Fallback season pack search initiate
2016-10-24 00:38:09 DEBUG    SEARCHQUEUE-MANUAL-78783 :: [NZBGeek] :: GET URL: https://api.nzbgeek.info/api?apikey=**********&tvdbid=78783&season=3&maxage=1825&cat=5030%2C5040&limit=100&t=tvsearch&offset=0&ep=1 [Status: 200]
2016-10-24 00:38:05 DEBUG    SEARCHQUEUE-MANUAL-78783 :: [NZBGeek] :: Search string: The Mysterious Cities of Gold S03E01
2016-10-24 00:38:05 DEBUG    SEARCHQUEUE-MANUAL-78783 :: [NZBGeek] :: Search Mode: Episode
2016-10-24 00:38:04 INFO     SEARCHQUEUE-MANUAL-78783 :: [NZBGeek] :: Performing episode search for The Mysterious Cities of Gold
2016-10-24 00:38:04 INFO     SEARCHQUEUE-MANUAL-78783 :: [Newznab Idx] :: Performing season pack search for The Mysterious Cities of Gold
2016-10-24 00:38:04 DEBUG    SEARCHQUEUE-MANUAL-78783 :: [Newznab Idx] :: Fallback season pack search initiate
2016-10-24 00:38:04 DEBUG    SEARCHQUEUE-MANUAL-78783 :: [Newznab Idx] :: GET URL: http://redactedurl.xxxx.net/api?apikey=**********&tvdbid=78783&season=3&maxage=1825&cat=5070%2C5080%2C5040%2C5030&limit=100&t=tvsearch&offset=0&ep=1 [Status: 200]
AAUnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 43: invalid start byte
AA    return _iterencode(o, 0)
AA  File "C:\python\lib\json\encoder.py", line 270, in iterencode
AA    chunks = self.iterencode(o, _one_shot=True)
AA  File "C:\python\lib\json\encoder.py", line 207, in encode
AA    return _default_encoder.encode(obj)
AA  File "C:\python\lib\json\__init__.py", line 243, in dumps
AA    return json.dumps(messages)
AA  File "C:\Program Files (x86)\Sickrage\current\sickbeard\webserve.py", line 597, in get_messages
AA    result = function(**kwargs)
AA  File "C:\Program Files (x86)\Sickrage\current\sickbeard\webserve.py", line 270, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "C:\Program Files (x86)\Sickrage\current\lib\concurrent\futures\thread.py", line 61, in run
AA    exec('raise exc_type, exc_value, traceback', {}, locals_)
AA  File "C:\Program Files (x86)\Sickrage\current\lib\concurrent\futures\_compat.py", line 107, in reraise
AA    reraise(self._exception, self._traceback)
AA  File "C:\Program Files (x86)\Sickrage\current\lib\concurrent\futures\_base.py", line 359, in __get_result
AA    return self.__get_result()
AA  File "C:\Program Files (x86)\Sickrage\current\lib\concurrent\futures\_base.py", line 400, in result
AA    value = future.result()
AA  File "C:\Program Files (x86)\Sickrage\current\lib\tornado\gen.py", line 870, in run
AA    results = yield self.async_call(method)
AA  File "C:\Program Files (x86)\Sickrage\current\sickbeard\webserve.py", line 254, in get
AA    yielded = self.gen.throw(*exc_info)
AA  File "C:\Program Files (x86)\Sickrage\current\lib\tornado\gen.py", line 876, in run
AA    raise_exc_info(self._exc_info)
AA  File "C:\Program Files (x86)\Sickrage\current\lib\tornado\concurrent.py", line 215, in result
AA    value = future.result()
AA  File "C:\Program Files (x86)\Sickrage\current\lib\tornado\gen.py", line 870, in run
AA    result = yield result
AA  File "C:\Program Files (x86)\Sickrage\current\lib\tornado\web.py", line 1415, in _execute
AATraceback (most recent call last):
AAHTTPServerRequest(protocol='http', host='localhost:8001', method='GET', uri='/ui/get_messages', version='HTTP/1.1', remote_ip='192.168.0.27', headers={'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8001', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://localhost:8001/schedule/'})
AA2016-10-24 00:38:04 ERROR    Uncaught exception GET /ui/get_messages (192.168.0.27)
AAUnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 43: invalid start byte
AA    return _iterencode(o, 0)
AA  File "C:\python\lib\json\encoder.py", line 270, in iterencode
AA    chunks = self.iterencode(o, _one_shot=True)
AA  File "C:\python\lib\json\encoder.py", line 207, in encode
AA    return _default_encoder.encode(obj)
AA  File "C:\python\lib\json\__init__.py", line 243, in dumps
AA    return json.dumps(messages)
AA  File "C:\Program Files (x86)\Sickrage\current\sickbeard\webserve.py", line 597, in get_messages
AA    result = function(**kwargs)
AA  File "C:\Program Files (x86)\Sickrage\current\sickbeard\webserve.py", line 270, in async_call
AATraceback (most recent call last):
AAUnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 43: invalid start byte
AA    return _iterencode(o, 0)
AA  File "C:\python\lib\json\encoder.py", line 270, in iterencode
AA    chunks = self.iterencode(o, _one_shot=True)
AA  File "C:\python\lib\json\encoder.py", line 207, in encode
AA    return _default_encoder.encode(obj)
AA  File "C:\python\lib\json\__init__.py", line 243, in dumps
AA    return json.dumps(messages)
AA  File "C:\Program Files (x86)\Sickrage\current\sickbeard\webserve.py", line 597, in get_messages
AA    result = function(**kwargs)
AA  File "C:\Program Files (x86)\Sickrage\current\sickbeard\webserve.py", line 270, in async_call
2016-10-24 00:38:04 ERROR    Thread-17 :: [8bf53e8] Failed doing webui callback: Traceback (most recent call last):
2016-10-24 00:38:02 DEBUG    SEARCHQUEUE-MANUAL-78783 :: [Newznab Idx] :: Search string: The Mysterious Cities of Gold S03E01
2016-10-24 00:38:02 DEBUG    SEARCHQUEUE-MANUAL-78783 :: [Newznab Idx] :: Search Mode: Episode
2016-10-24 00:38:02 INFO     SEARCHQUEUE-MANUAL-78783 :: [Newznab Idx] :: Performing episode search for The Mysterious Cities of Gold
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
This error is related to a special character. (on position 43)
Does the api key contain a special character.? if so generate a new one without it.

**Comment by LeeThompson** [comment]
The API does not have a special character.

**Comment by neoatomic** [comment]
Judging from the log NZBGeek works fine, so it seems to be specific to your private nzb server setup.
It could be the naming of a show, but than i would expect the same error with NZBGeek.

So it still searches/snatches episodes from your private nzb server.?
Might want to check if the category's are correctly selected, and existing on your private nzb server.

**Comment by LeeThompson** [comment]
Well this odd since the last Sickrage update (a few days back I think?) the error has not returned.
