### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/media/Downloads/Seriale Finished/Orphan Black S01e05-06/Orphan.Black.S01E06.La.Variazione.Allo.Stato.Domestico.ITA.ENG.720p.BluRay.x264.mkv'

### ISSUE THREAD

**Issue by megabitus98** [SickRage/SickRage#2536]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.21-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8bf53e8d03dc2b5bb946123dbaef2afb8667730c
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [8bf53e8] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2322, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "/opt/sickrage/sickbeard/processTV.py", line 278, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/opt/sickrage/sickbeard/processTV.py", line 551, in process_media
    result.result = processor.process()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 997, in process
    existing_file_status = self._checkForExistingFile(ep_obj.location)
  File "/opt/sickrage/sickbeard/postProcessor.py", line 126, in _checkForExistingFile
    if ek(os.path.getsize, existing_file) > ek(os.path.getsize, self.file_path):
  File "/opt/sickrage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/media/Downloads/Seriale Finished/Orphan Black S01e05-06/Orphan.Black.S01E06.La.Variazione.Allo.Stato.Domestico.ITA.ENG.720p.BluRay.x264.mkv'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
