### ISSUE TITLE
[APP SUBMITTED]: 'home_mako'

### ISSUE THREAD

**Issue by camouille** [SickRage/SickRage#2557]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 12:32:54) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@68db29ad555585cb96e655d470221a3898140ef4
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [68db29a] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 654, in index
    t = PageTemplate(rh=self, filename="home.mako")
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 112, in __init__
    self.template = lookup.get_template(filename)
  File "/usr/local/sickrage/var/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/usr/local/sickrage/var/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 380, in _compile_from_file
    del sys.modules[self.module_id]
KeyError: 'home_mako'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
dont delete the cache with SR running.
