### ISSUE TITLE
SickRage failed to start since last update

### ISSUE THREAD

**Issue by chatainsim** [SickRage/SickRage#2579]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master /
OS: Ubuntu 14.04 - Kernel 4.4.0-12
What you did: Nothing, SickRage update himself
What happened: Didn't restart
What you expected:
Logs:
```
Starting SickRage
Traceback (most recent call last):
  File "SickBeard.py", line 94, in <module>
    from sickbeard.webserveInit import SRWebServer
  File "/opt/sickrage/sickbeard/webserveInit.py", line 5, in <module>
    from tornado.httpserver import HTTPServer
  File "/opt/sickrage/lib/tornado/httpserver.py", line 34, in <module>
    from tornado.http1connection import HTTP1ServerConnection, HTTP1ConnectionParameters
  File "/opt/sickrage/lib/tornado/http1connection.py", line 28, in <module>
    from tornado import gen
  File "/opt/sickrage/lib/tornado/gen.py", line 1243, in <module>
    import tornado.platform.asyncio
  File "/opt/sickrage/lib/tornado/platform/asyncio.py", line 33, in <module>
    import asyncio # type: ignore
  File "/usr/local/lib/python2.7/dist-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/usr/local/lib/python2.7/dist-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Could it be that the update was run with a different user. aka permission issue.?
See if you can run the manual git commands, and see if that solves it.

https://github.com/SickRage/SickRage/wiki/FAQ's-and-Fixes#update-problems-try-this

**Comment by chatainsim** [comment]
It's the same:
```
simon@ubuntu-server:/opt/sickrage$ git remote set-url origin https://github.com/SickRage/SickRage.git
simon@ubuntu-server:/opt/sickrage$ git fetch origin
simon@ubuntu-server:/opt/sickrage$ git checkout master
Déjà sur 'master'
Votre branche est à jour avec 'origin/master'.
simon@ubuntu-server:/opt/sickrage$ git branch -u origin/master
La branche master est paramétrée pour suivre la branche distante master depuis origin.
simon@ubuntu-server:/opt/sickrage$ git reset --hard origin/master
HEAD est maintenant à d66f885 Update tornado to 4.4.2, add dependancies (#2561) (#2562)
simon@ubuntu-server:/opt/sickrage$ git pull
Already up-to-date.
simon@ubuntu-server:/opt/sickrage$ sudo /etc/init.d/sickbeard start
[sudo] password for simon:
/etc/default/sickbeard not found using default settings.
Starting SickRage
Traceback (most recent call last):
  File "SickBeard.py", line 94, in <module>
    from sickbeard.webserveInit import SRWebServer
  File "/opt/sickrage/sickbeard/webserveInit.py", line 5, in <module>
    from tornado.httpserver import HTTPServer
  File "/opt/sickrage/lib/tornado/httpserver.py", line 34, in <module>
    from tornado.http1connection import HTTP1ServerConnection, HTTP1ConnectionParameters
  File "/opt/sickrage/lib/tornado/http1connection.py", line 28, in <module>
    from tornado import gen
  File "/opt/sickrage/lib/tornado/gen.py", line 1243, in <module>
    import tornado.platform.asyncio
  File "/opt/sickrage/lib/tornado/platform/asyncio.py", line 33, in <module>
    import asyncio # type: ignore
  File "/usr/local/lib/python2.7/dist-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/usr/local/lib/python2.7/dist-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax
```

**Comment by neoatomic** [comment]
Strange, if it was broken i would expect a flood of issues on the issue tracker...
You could rollback a few versions, and see if an older version works.?

`git checkout v2016.10.20-1`

**Comment by chatainsim** [comment]
Thanks, it's working now.
But how can I solve this so I can update Sickrage again ?

**Comment by neoatomic** [comment]
We first need to know the exact issue. :)
So in short v2016.10.20-1 does work, but v2016.10.28-1 isn't.?

Its probably something @miigotu has to look into, but i'm wondering if the startup script is at fault here.

**Comment by chatainsim** [comment]
Ok, I've updated the init script.
Change right for /var/run/sickrage/
Add SR_USER in file /etc/default/sickrage.
Starting with v2016.10.20-1 work, I'll try to update Sickrage and start again.

**Comment by miigotu** [comment]
python version?

**Comment by chatainsim** [comment]
```
$ python --version
Python 2.7.6
```
But I have also Python 2.6.5 and Python 3.4.3 installed. Maybe I need to switch to another version ?

**Comment by miigotu** [comment]
you need 2.7.9-2.7.12

**Comment by miigotu** [comment]
If that doesnt work you have a broken package in your python install, the error that shows up has nothing to do with SR tbh.

**Comment by chatainsim** [comment]
Thanks,
How can I find the broken package ? I will try this before trying to upgrade python version.
So if I understand correctly, last update of SR need a higher version of python ?

**Comment by chatainsim** [comment]
Ok, I've compiled python 2.7.9 and add the path in /etc/default/sickrage.
Now it's working fine:
```
 SickRage Info:
Branch: master
Commit: dad54ac43de897812087a671eef1e4aa3c6ea02d
Version: v2016.10.28-1
Database Version: 44.0
Version de Python: 2.7.9 (default, Nov 2 2016, 21:20:42) [GCC 4.8.4]
```

**Comment by miigotu** [comment]
SSL doesnt work properly in versions less than 2.7.9, so a lot of dependancies dont work with a lesser version. Idk how you got asyncio in python2.7 without trollius but it is what it is.
