### ISSUE TITLE
Logging has stopped

### ISSUE THREAD

**Issue by bobbysteel** [SickRage/SickRage#2586]
This is weird. I had a disk full moment on the 30th and had to free up space a day later when I noticed. Now logging has entirely stopped. I pulled the latest version from git, rebooted and restarted everything but logs aren't restarting and the only active logging is a strange DEBUG error, which doesn't correspond to anything I'm even downloading now. 
```
2016-11-03 18:45:18 DEBUG MAIN :: The name Show.Name.S02E03.Ep Name.720p HDTV.ext parsed into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: ['standard']]
2016-11-03 18:45:18 DEBUG MAIN :: Parsed Show.Name.S02E03.Ep Name.720p HDTV.ext into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: ['standard']]
2016-11-03 18:45:18 DEBUG MAIN :: Trying to parse Show.Name.S02E03.Ep Name.720p HDTV.ext
2016-11-03 18:45:18 DEBUG MAIN :: formatting pattern: Season.%0S -> Season.02
2016-11-03 18:45:18 DEBUG MAIN :: Found codec for 'Show Name: Ep Name'.
2016-11-03 18:45:18 DEBUG MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: ['standard']]
```
This just repeats. Despite having DEBUG enabled, no log entries for just restarting the server, etc, which I'd expect.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [ ] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by pkoutsias** [comment]
I'm also having this issue.

Seems related to https://github.com/SickRage/SickRage/issues/2079

**Comment by bobbysteel** [comment]
Hm, I'm not sure if they're related. I can't find any actual Python errors in the system.log or such that would show why logger has just full on stopped.

**Comment by pkoutsias** [comment]
I'm having the exact same logs as you are, and when I start SickRage from terminal, I get the error messages from the other issue. They could be related in my opinion

**Comment by bobbysteel** [comment]
Interesting. The only thing that changed in that period for me was adding FOT as a torrent provider, so perhaps it's a bug around a certain kind of torrent provider?

**Comment by bobbysteel** [comment]
Anyone else having this issue? Still happening here. Nothing major but a bit annoying to not be able to view logs.

**Comment by bobbysteel** [comment]
Still happening. Really hard to troubleshoot since the logs themselves are the problem. Only my debug log changes and it's a loop of this 
    `
2016-12-19 09:32:18 DEBUG MAIN :: The name Show.Name.S02E03.Ep Name.720p HDTV.ext parsed into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: ['standard']]
2016-12-19 09:32:18 DEBUG MAIN :: Parsed Show.Name.S02E03.Ep Name.720p HDTV.ext into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: ['standard']]
2016-12-19 09:32:18 DEBUG MAIN :: Trying to parse Show.Name.S02E03.Ep Name.720p HDTV.ext
2016-12-19 09:32:18 DEBUG MAIN :: formatting pattern: Season.%0S -> Season.02
2016-12-19 09:32:18 DEBUG MAIN :: Found codec for 'Show Name: Ep Name'.
    `

**Comment by bobbysteel** [comment]
Fwiw, running manually I'm getting the following error 
    `
Logged from file logger.py, line 240
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 726, in format
    return fmt.format(record)
  File "/Users/robk/SickRage/sickbeard/logger.py", line 88, in format
    censored = {item for _, item in censored_items.iteritems() if item}
  File "/Users/robk/SickRage/sickbeard/logger.py", line 88, in <setcomp>
    censored = {item for _, item in censored_items.iteritems() if item}
TypeError: unhashable type: 'Section'
Logged from file logger.py, line 240
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 853, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 726, in format
    return fmt.format(record)
  File "/Users/robk/SickRage/sickbeard/logger.py", line 88, in format
    censored = {item for _, item in censored_items.iteritems() if item}
  File "/Users/robk/SickRage/sickbeard/logger.py", line 88, in <setcomp>
    censored = {item for _, item in censored_items.iteritems() if item}
TypeError: unhashable type: 'Section'
    `

**Comment by bobbysteel** [comment]
PR submitted to fix https://github.com/SickRage/SickRage/pull/2802

**Comment by Ic3Nine** [comment]
FWIW, i uninstalled, and started fresh.  Manually re-did my settings and imported all shows again.  Logs are working again.  Backing up, uninstall, re-install, restore did not solve the issue.

**Comment by Peglah** [comment]
@Ic3Nine I did the same thing and got the logs back. And not even a week later the logs stopped again after an restart of SR.

**Comment by bobbysteel** [comment]
Did you delete all the cookies from the ini? You have to shut down SR THEN
DELETE THE COOKIES SECTION then restart. If you do it while running it
undoes your delete. View the ini to see if cookies present.

**Comment by Peglah** [comment]
I'm sorry, I don't understand. Not the cookies in the browser, right? Where can I find ini?
> Did you delete all the cookies from the ini? You have to shut down SR THEN
DELETE THE COOKIES SECTION then restart. If you do it while running it
undoes your delete. View the ini to see if cookies present.

**Comment by bobbysteel** [comment]
In the sickbeard.ini in the main sick rage folder. Shutdown then edit it.
There should be a section called freshon_cookies or similar. Delete the
next line or two until the next section Beginning w brackets. Then restart
sickrage.

**Comment by Peglah** [comment]
Wow. Thank you! Using SR as a Docker container so the file was /config/config.ini and the line was [[freshontv_cookies]]. But it looks like my log just woke up.

> In the sickbeard.ini in the main sick rage folder. Shutdown then edit it.
There should be a section called freshon_cookies or similar. Delete the
next line or two until the next section Beginning w brackets. Then restart
sickrage.

**Comment by Telecart** [comment]
Same issue, log doesn't log, getting this in the terminal:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Applications/SickRage/sickbeard/logger.py", line 88, in format
    censored = {item for _, item in censored_items.iteritems() if item}
  File "/Applications/SickRage/sickbeard/logger.py", line 88, in <setcomp>
    censored = {item for _, item in censored_items.iteritems() if item}
TypeError: unhashable type: 'Section'
Logged from file logger.py, line 242

**Comment by bobbysteel** [comment]
Shutdown, delete the 3 freshon cookies lines in the ini file then restart.
