### ISSUE TITLE
[APP SUBMITTED]: ('The read operation timed out',)

### ISSUE THREAD

**Issue by squareflapjack** [SickRage/SickRage#2607]
this was submitted in error.  I was trying to submit a previous error about nonetype group and there was a hiccup.

sorry for the extra work

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by blurb2m** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@d15b7003f8663b76d01fcbf0566389b2f31e0564
No Log available with ERRORS:
### ERROR
```
Thread-29 :: [d15b700] Traceback (most recent call last):
  File "C:\SickRage\sickbeard\logger.py", line 367, in submit_errors
    for report in reports:
  File "C:\SickRage\lib\github\PaginatedList.py", line 48, in __iter__
    newElements = self._grow()
  File "C:\SickRage\lib\github\PaginatedList.py", line 60, in _grow
    newElements = self._fetchNextPage()
  File "C:\SickRage\lib\github\PaginatedList.py", line 161, in _fetchNextPage
    headers=self.__headers
  File "C:\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\lib\github\Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\SickRage\lib\github\Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\SickRage\lib\github\Requester.py", line 281, in __requestRaw
    output = response.read()
  File "C:\Python27\lib\httplib.py", line 596, in read
    s = self._safe_read(self.length)
  File "C:\Python27\lib\httplib.py", line 703, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "C:\Python27\lib\socket.py", line 384, in read
    data = self._sock.recv(left)
  File "C:\Python27\lib\ssl.py", line 734, in recv
    return self.read(buflen)
  File "C:\Python27\lib\ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
SSLError: ('The read operation timed out',)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:14:38) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [7e6e057] Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 372, in submit_errors
    for report in reports:
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/PaginatedList.py", line 48, in __iter__
    newElements = self._grow()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/PaginatedList.py", line 60, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/PaginatedList.py", line 161, in _fetchNextPage
    headers=self.__headers
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 277, in __requestRaw
    response = cnx.getresponse()
  File "/usr/local/python/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/local/python/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/python/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/python/lib/python2.7/ssl.py", line 766, in recv
    return self.read(buflen)
  File "/usr/local/python/lib/python2.7/ssl.py", line 653, in read
    v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by russtyisme** [comment]
### INFO
Python Version: **2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@d95ec824201c32be3e22dd3e64c8c3a7e3fe2c63
No Log available with ERRORS:
### ERROR
```
Thread-36 :: [d95ec82] Traceback (most recent call last):
  File "C:\SickRage\sickbeard\logger.py", line 372, in submit_errors
    for report in reports:
  File "C:\SickRage\lib\github\PaginatedList.py", line 48, in __iter__
    newElements = self._grow()
  File "C:\SickRage\lib\github\PaginatedList.py", line 60, in _grow
    newElements = self._fetchNextPage()
  File "C:\SickRage\lib\github\PaginatedList.py", line 161, in _fetchNextPage
    headers=self.__headers
  File "C:\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\lib\github\Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\SickRage\lib\github\Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\SickRage\lib\github\Requester.py", line 281, in __requestRaw
    output = response.read()
  File "C:\Python27\lib\httplib.py", line 596, in read
    s = self._safe_read(self.length)
  File "C:\Python27\lib\httplib.py", line 703, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "C:\Python27\lib\socket.py", line 384, in read
    data = self._sock.recv(left)
  File "C:\Python27\lib\ssl.py", line 756, in recv
    return self.read(buflen)
  File "C:\Python27\lib\ssl.py", line 643, in read
    v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by therealcorwin** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.102-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@de056c2380cb140bf8430a1ac4569899b3b44a52
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [de056c2] Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 385, in submit_errors
    for report in reports:
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/PaginatedList.py", line 48, in __iter__
    newElements = self._grow()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/PaginatedList.py", line 60, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/PaginatedList.py", line 161, in _fetchNextPage
    headers=self.__headers
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 277, in __requestRaw
    response = cnx.getresponse()
  File "/usr/local/python/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/local/python/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/python/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/python/lib/python2.7/ssl.py", line 766, in recv
    return self.read(buflen)
  File "/usr/local/python/lib/python2.7/ssl.py", line 653, in read
    v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by janusn** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1d34bcb48c1e03d568a8fdc08f60df8fa7f2d5d4
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [1d34bcb] Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/logger.py", line 369, in submit_errors
    repo = sickbeard.gh.get_organization(sickbeard.GIT_ORG).get_repo(sickbeard.GIT_REPO)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Organization.py", line 548, in get_repo
    "/repos/" + self.login + "/" + name
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 215, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 268, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 295, in __requestRaw
    response = cnx.getresponse()
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/ssl.py", line 714, in recv
    return self.read(buflen)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/ssl.py", line 608, in read
    v = self._sslobj.read(len or 1024)
SSLError: ('The read operation timed out',)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by scoobydoo1959** [comment]
### INFO
Python Version: **2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [a760263] Traceback (most recent call last):
  File "C:\Media_Apps\SickRage\sickbeard\logger.py", line 385, in submit_errors
    for report in reports:
  File "C:\Media_Apps\SickRage\lib\github\PaginatedList.py", line 49, in __iter__
    newElements = self._grow()
  File "C:\Media_Apps\SickRage\lib\github\PaginatedList.py", line 61, in _grow
    newElements = self._fetchNextPage()
  File "C:\Media_Apps\SickRage\lib\github\PaginatedList.py", line 163, in _fetchNextPage
    headers=self.__headers
  File "C:\Media_Apps\SickRage\lib\github\Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\Media_Apps\SickRage\lib\github\Requester.py", line 215, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\Media_Apps\SickRage\lib\github\Requester.py", line 268, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\Media_Apps\SickRage\lib\github\Requester.py", line 299, in __requestRaw
    output = response.read()
  File "C:\Python27\lib\httplib.py", line 581, in read
    s = self._safe_read(self.length)
  File "C:\Python27\lib\httplib.py", line 688, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "C:\Python27\lib\socket.py", line 384, in read
    data = self._sock.recv(left)
  File "C:\Python27\lib\ssl.py", line 766, in recv
    return self.read(buflen)
  File "C:\Python27\lib\ssl.py", line 653, in read
    v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by prantzos** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [a760263] Traceback (most recent call last):
  File "C:\My\OneDrive\Programs\SickRage\sickbeard\logger.py", line 385, in submit_errors
    for report in reports:
  File "C:\My\OneDrive\Programs\SickRage\lib\github\PaginatedList.py", line 49, in __iter__
    newElements = self._grow()
  File "C:\My\OneDrive\Programs\SickRage\lib\github\PaginatedList.py", line 61, in _grow
    newElements = self._fetchNextPage()
  File "C:\My\OneDrive\Programs\SickRage\lib\github\PaginatedList.py", line 163, in _fetchNextPage
    headers=self.__headers
  File "C:\My\OneDrive\Programs\SickRage\lib\github\Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\My\OneDrive\Programs\SickRage\lib\github\Requester.py", line 215, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\My\OneDrive\Programs\SickRage\lib\github\Requester.py", line 268, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\My\OneDrive\Programs\SickRage\lib\github\Requester.py", line 295, in __requestRaw
    response = cnx.getresponse()
  File "C:\My\OneDrive\Programs\Python27\lib\httplib.py", line 1121, in getresponse
    response.begin()
  File "C:\My\OneDrive\Programs\Python27\lib\httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "C:\My\OneDrive\Programs\Python27\lib\httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "C:\My\OneDrive\Programs\Python27\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "C:\My\OneDrive\Programs\Python27\lib\ssl.py", line 766, in recv
    return self.read(buflen)
  File "C:\My\OneDrive\Programs\Python27\lib\ssl.py", line 653, in read
    v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rkorn86** [comment]
### INFO
Python Version: **2.7.18 (default, May  3 2020, 20:31:45) [GCC 9.2.0]**
Operating System: **Linux-5.10.14-arch1-1-x86_64-with**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f638d1bca3b3db45b9d5c7da021b07c8c2030ca2
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [f638d1b] Traceback (most recent call last):
  File "/sickchill/sickbeard/logger.py", line 392, in submit_errors
    if report.create_comment(message):
  File "/sickchill/lib/github/Issue.py", line 276, in create_comment
    input=post_parameters
  File "/sickchill/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/sickchill/lib/github/Requester.py", line 215, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/sickchill/lib/github/Requester.py", line 268, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/sickchill/lib/github/Requester.py", line 295, in __requestRaw
    response = cnx.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1161, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 448, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 404, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 754, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 641, in read
    v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
