### ISSUE TITLE
After debian update unable to start sickrage (Cryptography_HAS_SSL_ST)

### ISSUE THREAD

**Issue by janvgils** [SickRage/SickRage#2622]
### Before submitting your issue:

Branch/Commit: Master
OS: Debian testing
What you did: debian apt update && apt-upgrade
What happened: sick beard no longer able to start
What you expected: Is there a possible solution or fix
Logs:
```
/etc/init.d/sickrage start
Starting SickRage
Traceback (most recent call last):
  File "SickBeard.py", line 91, in <module>
    import sickbeard
  File "/opt/sickrage/sickbeard/__init__.py", line 37, in <module>
    from sickbeard.indexers import indexer_api
  File "/opt/sickrage/sickbeard/indexers/__init__.py", line 21, in <module>
    from . import indexer_api
  File "/opt/sickrage/sickbeard/indexers/indexer_api.py", line 26, in <module>
    from indexer_config import initConfig
  File "/opt/sickrage/sickbeard/indexers/indexer_config.py", line 3, in <module>
    from tvdb_api.tvdb_api import Tvdb
  File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 24, in <module>
    import requests
  File "/opt/sickrage/lib/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/opt/sickrage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 112, in <module>
    if _lib.Cryptography_HAS_SSL_ST:
AttributeError: 'module' object has no attribute 'Cryptography_HAS_SSL_ST'

package update dpkg.log:

2016-11-15 13:48:37 upgrade python-openssl:all 16.1.0-1 16.2.0-1
2016-11-15 13:48:37 status half-configured python-openssl:all 16.1.0-1
2016-11-15 13:48:37 status unpacked python-openssl:all 16.1.0-1
2016-11-15 13:48:37 status half-installed python-openssl:all 16.1.0-1
2016-11-15 13:48:37 status half-installed python-openssl:all 16.1.0-1
2016-11-15 13:48:37 status unpacked python-openssl:all 16.2.0-1
2016-11-15 13:48:37 status unpacked python-openssl:all 16.2.0-1
2016-11-15 13:48:41 configure python-openssl:all 16.2.0-1 <none>
2016-11-15 13:48:41 status unpacked python-openssl:all 16.2.0-1
2016-11-15 13:48:41 status half-configured python-openssl:all 16.2.0-1
2016-11-15 13:48:41 status installed python-openssl:all 16.2.0-1

It seem python-openssl went from 16.1.0 to 16.2.0-1

```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duduke** [comment]
I can also confirm this.

**Comment by duduke** [comment]
deleting SSL.pyc from SICKRAGEFOLDER/lib/OpenSSL seems to resolve the issue.

**Comment by janvgils** [comment]
Thanks for your reply and possible workaround.
In my case this isn't working because I don't have the file avialable in the directory you mention.

Also in the latest git clone there is no ssl.pyc present.

The only version I could find was in /usr/lib/python2.7/ssl.py and ssl.pyc.
renamed the ssl.pyc to something else but this didn't solve the issue.
So also renamed ssl.py to something else but then I get a the following error:

/etc/init.d/sickrage start
Starting SickRage
Traceback (most recent call last):
  File "SickBeard.py", line 71, in <module>
    import ssl

I do think we are on the right track

**Comment by janvgils** [comment]
After having a better look if the file SSL.pyc was available in another location, I found the following.

/usr/lib/python2.7/dist-packages/OpenSSL 

I renamed the whole directory and now sickrage starts again.

So this seems to be solved.

**Comment by miigotu** [comment]
I would be using pip to install python packages rather than the debian package manager, its just best practice. Also, you can try `pip install cryptography idna`. I might need to update the included libs in SR, specifically `requests`.

**Comment by 7h3ju57** [comment]
Can confirm uninstalling python-openssl and running pip install cryptography idna has resolved the issue for me.
