### ISSUE TITLE
Error while adding new show that’s not released yet

### ISSUE THREAD

**Issue by hboetes** [SickRage/SickRage#2627]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Debian Stretch, up to date
What you did: Shows →Add new show → Star trek:discovery (correctly found in the list) → Add show
What happened: I got the error below.
What you expected: A decent reply, preferably adding the show correctly, even though nothing is known about it yet.
Logs:
```
2016-11-17 20:35:46 SHOWQUEUE-ADD :: [5443e1b] Unable to look up the show in /home/sickrage/Star Trek Discovery on theTVDB using ID 319131, not using the NFO. Delete .nfo and try adding manually again.: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/319131/en.xml
2016-11-17 20:33:52 Thread-14 :: [5443e1b] Failed doing webui callback: Traceback (most recent call last):
File "/home/sickrage/SickRage/sickbeard/webserve.py", line 270, in async_call
result = function(**kwargs)
File "/home/sickrage/SickRage/sickbeard/webserve.py", line 2767, in addShowByID
show_name = get_showname_from_indexer(1, indexer_id)
File "/home/sickrage/SickRage/sickbeard/helpers.py", line 1734, in get_showname_from_indexer
s = t[int(indexer_id)]
File "/home/sickrage/SickRage/lib/tvdb_api/tvdb_api.py", line 953, in __getitem__
self._getShowData(key, self.config['language'], True)
File "/home/sickrage/SickRage/lib/tvdb_api/tvdb_api.py", line 848, in _getShowData
self.config['url_seriesInfo'] % (sid, getShowInLanguage)
File "/home/sickrage/SickRage/lib/tvdb_api/tvdb_api.py", line 636, in _getetsrc
raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/315442/en.xml
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by OmgImAlexis** [comment]
Try again thetvdb was down quite a bit in the last 24 hours.

**Comment by theailer** [comment]
Now the show does not even show up when searching for it.

**Comment by hboetes** [comment]
What @theailer said, this is more like a work around. A more satisfying solution would be to:

1. Display a notice like: This show isn’t available yet, please try again later.
2. Add the show in stub mode with a notice: This show isn’t running yet, so we don’t know any details about it, but we’ll keep looking for it.

Just my 2ct
