### ISSUE TITLE
[APP SUBMITTED]: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by AubreyKloppers** [SickRage/SickRage#2639]
### INFO
Python Version: **2.7.3 (default, Jun 21 2016, 18:38:19) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.11**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@a1bf3b30a9a0d6319c09fb0cf48d2d468dbf4e61
No Log available with ERRORS:
### ERROR
```
Thread-542 :: [a1bf3b3] Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/logger.py", line 367, in submit_errors
    for report in reports:
  File "/opt/sickbeard/lib/github/PaginatedList.py", line 48, in __iter__
    newElements = self._grow()
  File "/opt/sickbeard/lib/github/PaginatedList.py", line 60, in _grow
    newElements = self._fetchNextPage()
  File "/opt/sickbeard/lib/github/PaginatedList.py", line 161, in _fetchNextPage
    headers=self.__headers
  File "/opt/sickbeard/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/opt/sickbeard/lib/github/Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/opt/sickbeard/lib/github/Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/opt/sickbeard/lib/github/Requester.py", line 275, in __requestRaw
    requestHeaders
  File "/usr/lib/python2.7/httplib.py", line 1000, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1034, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 996, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 847, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 809, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1199, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by SteveBeauchemin** [comment]
### INFO
Python Version: **2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]**
Operating System: **Linux-4.12.3-1.el7.elrepo.x86_64-x86_64-with-centos-7.3.1611-Core**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@91809083cb82732908357e184acd477138277ef5
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [9180908] Traceback (most recent call last):
  File "/usr/local/SickRage/sickbeard/logger.py", line 385, in submit_errors
    for report in reports:
  File "/usr/local/SickRage/lib/github/PaginatedList.py", line 48, in __iter__
    newElements = self._grow()
  File "/usr/local/SickRage/lib/github/PaginatedList.py", line 60, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/SickRage/lib/github/PaginatedList.py", line 161, in _fetchNextPage
    headers=self.__headers
  File "/usr/local/SickRage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/local/SickRage/lib/github/Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/SickRage/lib/github/Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/local/SickRage/lib/github/Requester.py", line 275, in __requestRaw
    requestHeaders
  File "/usr/lib64/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1227, in connect
    HTTPConnection.connect(self)
  File "/usr/lib64/python2.7/httplib.py", line 807, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
