### ISSUE TITLE
OLD settings present after backup restore on fresh system setup and updated configuration

### ISSUE THREAD

**Issue by metatronikos** [SickRage/SickRage#2642]
Dear Sirs,

A help request for anyone ready to help.
Please follow the structured schema.

thanks to everyone in advance

meta

**Branch/Commit:**
Branch: master
Commit: a1bf3b30a9a0d6319c09fb0cf48d2d468dbf4e61
Version: v2016.10.28-1
Database Version: 44.0

**OS:**
OSMC VERSION_ID="2016.10-2"

**What you did:** 

After new system setup . Restored the sickrage settings from backup file.
After some new finished media file downloads on new system setup, which were ready to automatic post proccesing started to get error.
See "What happened"

**What happened:**
2016-11-24 16:50:43 ERROR    POSTPROCESSER :: [a1bf3b3] Exception generated in thread POSTPROCESSER: error 2 : No such file or directory

**What happened next:**
Forked around with manual postprocessing, and did find out, that in more detailed  log i get the old destination path from previous system enviroment. (restored the sickrage settings from backup),
and it was /mnt/hdd1g/tv_shows'
FYI: the new actual postprocess path is '/mnt/HDD3TB/torrents/complete'

**Logs:**
AAOSError: [Errno 2] No such file or directory: '/mnt/hdd1g/tv_shows'
AA    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
AA  File "/opt/sickrage/sickrage/helper/encoding.py", line 40, in ek
AA    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest if ek(os.path.exists, dest) else ek(os.path.dirname, dest)).st_dev:  # pylint: disable=no-member
AA  File "/opt/sickrage/sickbeard/helpers.py", line 1577, in verify_freespace
AA    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
AA  File "/opt/sickrage/sickbeard/postProcessor.py", line 1043, in process
AA    result.result = processor.process()
AA  File "/opt/sickrage/sickbeard/processTV.py", line 551, in process_media
AA    process_media(path, [video], nzbName, process_method, force, is_priority, result)
AA  File "/opt/sickrage/sickbeard/processTV.py", line 231, in processDir
AA    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
AA  File "/opt/sickrage/sickbeard/webserve.py", line 2322, in processEpisode
AA    result = function(**kwargs)
AA  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "/opt/sickrage/lib/concurrent/futures/thread.py", line 61, in run
AA    exec('raise exc_type, exc_value, traceback', {}, locals_)
AA  File "/opt/sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise
AA    reraise(self._exception, self._traceback)
AA  File "/opt/sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result
AA    return self.__get_result()
AA  File "/opt/sickrage/lib/concurrent/futures/_base.py", line 400, in result
AA    value = future.result()
AA  File "/opt/sickrage/lib/tornado/gen.py", line 1015, in run
AA    results = yield self.async_call(method)
AA  File "/opt/sickrage/sickbeard/webserve.py", line 254, in get
AA    yielded = self.gen.throw(*exc_info)
AA  File "/opt/sickrage/lib/tornado/gen.py", line 1021, in run
AA    raise_exc_info(self._exc_info)
AA  File "/opt/sickrage/lib/tornado/concurrent.py", line 237, in result
AA    value = future.result()
AA  File "/opt/sickrage/lib/tornado/gen.py", line 1015, in run
AA    result = yield result
AA  File "/opt/sickrage/lib/tornado/web.py", line 1469, in _execute
AATraceback (most recent call last):
AAHTTPServerRequest(protocol='http', host='192.168.100.20:8081', method='POST', uri='/home/postprocess/processEpisode', version='HTTP/1.1', remote_ip='192.168.100.10', headers={'Content-Length': '94', 'Accept-Language': 'sk,cs;q=0.8,en-US;q=0.5,en;q=0.3', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.100.20:8081', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0', 'Connection': 'keep-alive', 'Referer': 'http://192.168.100.20:8081/home/postprocess/', 'Cookie': '_ga=GA1.1.1879114779.1464497191; filter=all; sort_method=percent_completed; sort_direction=ascending; user="2|1:0|10:1478111053|4:user|44:NDYxNDMwODkyNTg2NGRlMWI4YmZhMjNlMDE1ZTE1YTg=|2c43c071b351ca88637658b3d7d71ec551c6df6635ef86e59a21482ec391b9ba"; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_box_office_view=thumb; imdb_top_dvd_rentals_view=thumb; imdb_top_250_movies_view=thumb; advanced_toggle_checked=1; wanted_view=list; manage_view=list; sickrage_user="2|1:0|10:1479930124|13:sickrage_user|44:NmMxMmRiOTYwNDIxMGIxYWQ5YWU5NDY0MDQ0ZDEzYjI=|8ec822594e5775772f8bfa4b1aa9c40c04755d414b7fea4e3a41c0ef23ab1d5d"', 'Content-Type': 'application/x-www-form-urlencoded'})
AA2016-11-24 18:05:58 ERROR    Uncaught exception POST /home/postprocess/processEpisode (192.168.100.10)
AAOSError: [Errno 2] No such file or directory: '/mnt/hdd1g/tv_shows'
AA    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
AA  File "/opt/sickrage/sickrage/helper/encoding.py", line 40, in ek
AA    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest if ek(os.path.exists, dest) else ek(os.path.dirname, dest)).st_dev:  # pylint: disable=no-member
AA  File "/opt/sickrage/sickbeard/helpers.py", line 1577, in verify_freespace
AA    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
AA  File "/opt/sickrage/sickbeard/postProcessor.py", line 1043, in process
AA    result.result = processor.process()
AA  File "/opt/sickrage/sickbeard/processTV.py", line 551, in process_media
AA    process_media(path, [video], nzbName, process_method, force, is_priority, result)
AA  File "/opt/sickrage/sickbeard/processTV.py", line 231, in processDir
AA    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
AA  File "/opt/sickrage/sickbeard/webserve.py", line 2322, in processEpisode
AA    result = function(**kwargs)
AA  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
AATraceback (most recent call last):
AAOSError: [Errno 2] No such file or directory: '/mnt/hdd1g/tv_shows'
AA    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
AA  File "/opt/sickrage/sickrage/helper/encoding.py", line 40, in ek
AA    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest if ek(os.path.exists, dest) else ek(os.path.dirname, dest)).st_dev:  # pylint: disable=no-member
AA  File "/opt/sickrage/sickbeard/helpers.py", line 1577, in verify_freespace
AA    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
AA  File "/opt/sickrage/sickbeard/postProcessor.py", line 1043, in process
AA    result.result = processor.process()
AA  File "/opt/sickrage/sickbeard/processTV.py", line 551, in process_media
AA    process_media(path, [video], nzbName, process_method, force, is_priority, result)
AA  File "/opt/sickrage/sickbeard/processTV.py", line 231, in processDir
AA    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
AA  File "/opt/sickrage/sickbeard/webserve.py", line 2322, in processEpisode
AA    result = function(**kwargs)
AA  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
2016-11-24 18:05:58 ERROR    Thread-14 :: [a1bf3b3] Failed doing webui callback: Traceback (most recent call last):
2016-11-24 18:05:58 INFO     Thread-14 :: This download is marked a priority download so I'm going to replace an existing file if I find one
2016-11-24 18:05:58 INFO     Thread-14 :: Processing /mnt/HDD3TB/torrents/complete/Fear.the.Walking.Dead.S02E09.720p.HDTV.x265.ShAaNiG.mkv (None)
2016-11-24 18:05:57 INFO     Thread-14 :: PostProcessing Path: /mnt/HDD3TB/torrents/complete
2016-11-24 17:55:43 INFO     FINDSUBTITLES :: Finished checking for missed ********s
2016-11-24 17:55:43 INFO     FINDSUBTITLES :: Checking for missed ********s
2016-11-24 17:37:04 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2016-11-24 17:36:38 INFO     SEARCHQUEUE-DAILY-SEARCH :: [BTDigg] :: Request failed: 525 Server Error: Origin SSL Handshake Error for url: https://api.btdigg.org/api/private-341ada3245790954/s02?q=720.HDTV.x264&p=0&order=2
2016-11-24 17:36:38 INFO     SEARCHQUEUE-DAILY-SEARCH :: [BTDigg] :: Request failed: 525 Server Error: Origin SSL Handshake Error for url: https://api.btdigg.org/api/private-341ada3245790954/s02?q=x264.HDTV&p=0&order=2
2016-11-24 17:36:38 INFO     SEARCHQUEUE-DAILY-SEARCH :: [BTDigg] :: Request failed: 525 Server Error: Origin SSL Handshake Error for url: https://api.btdigg.org/api/private-341ada3245790954/s02?q=x264&p=0&order=2
2016-11-24 17:35:47 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2016-11-24 17:35:43 INFO     DAILYSEARCHER :: No new released episodes found ...
2016-11-24 17:35:43 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2016-11-24 16:57:25 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2016-11-24 16:56:53 INFO     SEARCHQUEUE-DAILY-SEARCH :: [BTDigg] :: Request failed: 525 Server Error: Origin SSL Handshake Error for url: https://api.btdigg.org/api/private-341ada3245790954/s02?q=720.HDTV.x264&p=0&order=2
2016-11-24 16:56:53 INFO     SEARCHQUEUE-DAILY-SEARCH :: [BTDigg] :: Request failed: 525 Server Error: Origin SSL Handshake Error for url: https://api.btdigg.org/api/private-341ada3245790954/s02?q=x264.HDTV&p=0&order=2
2016-11-24 16:56:53 INFO     SEARCHQUEUE-DAILY-SEARCH :: [BTDigg] :: Request failed: 525 Server Error: Origin SSL Handshake Error for url: https://api.btdigg.org/api/private-341ada3245790954/s02?q=x264&p=0&order=2
2016-11-24 16:55:47 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2016-11-24 16:55:43 INFO     FINDSUBTITLES :: Finished checking for missed ********s
2016-11-24 16:55:42 INFO     DAILYSEARCHER :: No new released episodes found ...
2016-11-24 16:55:42 INFO     FINDSUBTITLES :: Checking for missed ********s
2016-11-24 16:55:42 INFO     DAILYSEARCHER :: Searching for new released episodes ...
AAOSError: [Errno 2] No such file or directory: '/mnt/hdd1g/tv_shows'
AA    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
AA  File "/opt/sickrage/sickrage/helper/encoding.py", line 40, in ek
AA    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest if ek(os.path.exists, dest) else ek(os.path.dirname, dest)).st_dev:  # pylint: disable=no-member
AA  File "/opt/sickrage/sickbeard/helpers.py", line 1577, in verify_freespace
AA    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
AA  File "/opt/sickrage/sickbeard/postProcessor.py", line 1043, in process
AA    result.result = processor.process()
AA  File "/opt/sickrage/sickbeard/processTV.py", line 551, in process_media
AA    process_media(path, [video], nzbName, process_method, force, is_priority, result)
AA  File "/opt/sickrage/sickbeard/processTV.py", line 231, in processDir
AA    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)
AA  File "/opt/sickrage/sickbeard/auto_postprocessor.py", line 55, in run
AA    self.action.run(self.force)
AA  File "/opt/sickrage/sickbeard/scheduler.py", line 107, in run
AATraceback (most recent call last):

**What do you expect:**
Help to get postprocessing working again.

```
**git remote show origin:**
Fetch URL: https://github.com/SickRage/SickRage.git


```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by metatronikos** [comment]
Im apologizing for postin such banal issue.
I found the problem. It was just in front of me and could not see it.
The problem was generated by (nonexistent) path in tv show settings, which came from backup file.

thanks

you can close this.
