### ISSUE TITLE
Error when doing mass update

### ISSUE THREAD

**Issue by ManOrMonster** [SickRage/SickRage#2690]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master 2016.09.18-1
OS: Windows 10
What you did: Mass update to point to new drive
What happened: Changed many (most?) of the shows to the new drive but some didn't change. Received error below.
What you expected: Change all of the shows to the new drive without giving an error.
Logs:
```
Error

'utf8' codec can't decode byte 0x92 in position 17: invalid start byte

Traceback

Traceback (most recent call last): 
File "C:\SickRage\lib\tornado\web.py", line 1469, in _execute result = yield result 
File "C:\SickRage\lib\tornado\gen.py", line 1015, in run value = future.result() 
File "C:\SickRage\lib\tornado\concurrent.py", line 237, in result raise_exc_info(self._exc_info) 
File "C:\SickRage\lib\tornado\gen.py", line 1021, in run yielded = self.gen.throw(*exc_info) 
File "C:\SickRage\sickbeard\webserve.py", line 254, in get results = yield self.async_call(method) 
File "C:\SickRage\lib\tornado\gen.py", line 1015, in run value = future.result() 
File "C:\SickRage\lib\concurrent\futures\_base.py", line 400, in result return self.__get_result() 
File "C:\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "C:\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "C:\SickRage\lib\concurrent\futures\thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "C:\SickRage\sickbeard\webserve.py", line 270, in async_call result = function(**kwargs) 
File "C:\SickRage\sickbeard\webserve.py", line 3464, in massEditSubmit directCall=True) 
File "C:\SickRage\sickbeard\webserve.py", line 1558, in editShow location = location.decode('UTF-8') 
File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode return codecs.utf_8_decode(input, errors, True) 
UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 17: invalid start byte 

Request Info

body: toEdit=301824%7C283115%7C269613%7C274897%7C97731%7C299400%7C285378%7C292124%7C276148%7C264991%7C284210%7C259765%7C303069%7C124051%7C298085%7C300472%7C75817%7C292157%7C289590%7C176941%7C281534%7C279977%7C182061%7C83462%7C255325%7C264190%7C286943%7C275557%7C303236%7C296762%7C82283%7C281181%7C276564%7C305666%7C76107%7C75897%7C228751%7C77398%7C265074%7C280582%7C311817%7C273021%7C262407%7C79182%7C308772%7C262414%7C309876%7C280619%7C295721%7C266398%7C264222%7C265579%7C265609%7C211751%7C279121%7C295779%7C305326%7C253463%7C248261%7C71663%7C261277%7C277531%7C82230%7C253573%7C280847%7C161511%7C269650%7C78901%7C193131%7C279201%7C258744%7C104641%7C317998%7C259972%7C269689%7C269750%7C279893%7C270550%7C275274%7C267002%7C306313%7C79563%7C303884%7C187071%7C265766%7C284219%7C152831%7C270633%7C277165%7C121361%7C296295%7C260750%7C82467%7C153021%7C308771%7C273181%7C281776%7C283317%7C270701%7C258310%7C295697%7C271708%7C293302%7C289079%7C283346%7C304433%7C272391%7C259184%7C269586%7C139941%7C304214%7C283345%7C76177%7C281622%7C290853%7C295751%7C277954%7C250487%7C268591%7C289096%7C295760%7C282403%7C256520%7C272135%7C282994%7C308204%7C314473%7C248482%7C275104%7C276312%7C163751%7C268386%7C75805%7C79905%7C312505%7C251457%7C140681&orig_root_dir_0=T%3A%5CTV&new_root_dir_0=T%3A%5CTV&orig_root_dir_1=V%3A%5CTV&new_root_dir_1=T%3A%5CTV&quality_preset=500&anyQualities=4&anyQualities=16&anyQualities=32&anyQualities=64&anyQualities=128&anyQualities=256&flatten_folders=disable&paused=disable&default_ep_status=keep&scene=keep&anime=disable&sports=disable&air_by_date=disable&subtitles=disable
files: {}
protocol: http
connection: 
body_arguments: {'paused': ['disable'], 'flatten_folders': ['disable'], 'new_root_dir_0': ['T:\\TV'], 'new_root_dir_1': ['T:\\TV'], 'orig_root_dir_0': ['T:\\TV'], 'orig_root_dir_1': ['V:\\TV'], 'scene': ['keep'], 'sports': ['disable'], 'air_by_date': ['disable'], 'default_ep_status': ['keep'], 'quality_preset': ['500'], 'anyQualities': ['4', '16', '32', '64', '128', '256'], 'toEdit': ['301824|283115|269613|274897|97731|299400|285378|292124|276148|264991|284210|259765|303069|124051|298085|300472|75817|292157|289590|176941|281534|279977|182061|83462|255325|264190|286943|275557|303236|296762|82283|281181|276564|305666|76107|75897|228751|77398|265074|280582|311817|273021|262407|79182|308772|262414|309876|280619|295721|266398|264222|265579|265609|211751|279121|295779|305326|253463|248261|71663|261277|277531|82230|253573|280847|161511|269650|78901|193131|279201|258744|104641|317998|259972|269689|269750|279893|270550|275274|267002|306313|79563|303884|187071|265766|284219|152831|270633|277165|121361|296295|260750|82467|153021|308771|273181|281776|283317|270701|258310|295697|271708|293302|289079|283346|304433|272391|259184|269586|139941|304214|283345|76177|281622|290853|295751|277954|250487|268591|289096|295760|282403|256520|272135|282994|308204|314473|248482|275104|276312|163751|268386|75805|79905|312505|251457|140681'], 'subtitles': ['disable'], 'anime': ['disable']}
uri: /manage/massEditSubmit
query_arguments: {}
_start_time: 1481592408.27
headers: Origin: http://localhost:8081 Content-Length: 1579 Accept-Language: en-US,en;q=0.8 Accept-Encoding: gzip, deflate, br Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8 Upgrade-Insecure-Requests: 1 Host: localhost:8081 Referer: http://localhost:8081/manage/massEdit Cache-Control: max-age=0 Cookie: manage_view=thumb; plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; advanced_toggle_checked=1; wanted_view=list; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; imdb_movies_in_theaters_view=thumb; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; imdb_top_dvd_rentals_view=thumb User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36 Content-Type: application/x-www-form-urlencoded 
host: localhost:8081
version: HTTP/1.1
arguments: {'air_by_date': 'disable', 'new_root_dir_0': 'T:\\TV', 'new_root_dir_1': 'T:\\TV', 'orig_root_dir_0': 'T:\\TV', 'orig_root_dir_1': 'V:\\TV', 'default_ep_status': 'keep', 'scene': 'keep', 'sports': 'disable', 'paused': 'disable', 'flatten_folders': 'disable', 'quality_preset': '500', 'anyQualities': ['4', '16', '32', '64', '128', '256'], 'toEdit': '301824|283115|269613|274897|97731|299400|285378|292124|276148|264991|284210|259765|303069|124051|298085|300472|75817|292157|289590|176941|281534|279977|182061|83462|255325|264190|286943|275557|303236|296762|82283|281181|276564|305666|76107|75897|228751|77398|265074|280582|311817|273021|262407|79182|308772|262414|309876|280619|295721|266398|264222|265579|265609|211751|279121|295779|305326|253463|248261|71663|261277|277531|82230|253573|280847|161511|269650|78901|193131|279201|258744|104641|317998|259972|269689|269750|279893|270550|275274|267002|306313|79563|303884|187071|265766|284219|152831|270633|277165|121361|296295|260750|82467|153021|308771|273181|281776|283317|270701|258310|295697|271708|293302|289079|283346|304433|272391|259184|269586|139941|304214|283345|76177|281622|290853|295751|277954|250487|268591|289096|295760|282403|256520|272135|282994|308204|314473|248482|275104|276312|163751|268386|75805|79905|312505|251457|140681', 'subtitles': 'disable', 'anime': 'disable'}
_finish_time: None
query: 
path: /manage/massEditSubmit
method: POST
remote_ip: 127.0.0.1
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Best case would be to remove latin-1 chars from the folder names, but alas I have pushed a fix to develop that should fix this.

**Comment by ManOrMonster** [comment]
I'm getting the following error when I check for update:

2016-12-30 10:53:08 CHECKVERSION :: [17e9b81] We can't proceed with the update. Unable to check remote DB version. Error: AssertionError('Commit hash wrong length: 4 hash: None',)
