### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: u'/home/user/.apps/sickrage/cache/mako/layouts/main.mako.py'

### ISSUE THREAD

**Issue by HitmanThe47** [SickRage/SickRage#2697]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.8.4-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@a1bf3b30a9a0d6319c09fb0cf48d2d468dbf4e61
No Log available with ERRORS:
### ERROR
```
Thread-21 :: [a1bf3b3] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2988, in index
    return t.render(title=_('Mass Update'), header=_('Mass Update'), topmenu='manage', controller="manage", action="index")
  File "/opt/sickrage/sickbeard/webserve.py", line 160, in render
    kwargs['backtrace'] = RichTraceback()
  File "/opt/sickrage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/opt/sickrage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/opt/sickrage/lib/mako/template.py", line 632, in code
    return util.read_python_file(self.module_filename)
  File "/opt/sickrage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/home/user/.apps/sickrage/cache/mako/layouts/main.mako.py'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.8.4-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@a1bf3b30a9a0d6319c09fb0cf48d2d468dbf4e61
No Log available with ERRORS:
### ERROR
```
Thread-20 :: [a1bf3b3] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2988, in index
    return t.render(title=_('Mass Update'), header=_('Mass Update'), topmenu='manage', controller="manage", action="index")
  File "/opt/sickrage/sickbeard/webserve.py", line 160, in render
    kwargs['backtrace'] = RichTraceback()
  File "/opt/sickrage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/opt/sickrage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/opt/sickrage/lib/mako/template.py", line 632, in code
    return util.read_python_file(self.module_filename)
  File "/opt/sickrage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/home/user/.apps/sickrage/cache/mako/layouts/main.mako.py'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.8.4-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@a1bf3b30a9a0d6319c09fb0cf48d2d468dbf4e61
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [a1bf3b3] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1379, in displayShow
    action="displayShow"
  File "/opt/sickrage/sickbeard/webserve.py", line 160, in render
    kwargs['backtrace'] = RichTraceback()
  File "/opt/sickrage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/opt/sickrage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/opt/sickrage/lib/mako/template.py", line 632, in code
    return util.read_python_file(self.module_filename)
  File "/opt/sickrage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/home/user/.apps/sickrage/cache/mako/layouts/main.mako.py'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
restart SR ...
