### ISSUE TITLE
[APP SUBMITTED]: ('_ssl.c:574: The handshake operation timed out',)

### ISSUE THREAD

**Issue by POgli** [SickRage/SickRage#2701]
### INFO
Python Version: **2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@a1bf3b30a9a0d6319c09fb0cf48d2d468dbf4e61
No Log available with ERRORS:
### ERROR
```
Thread-25 :: [a1bf3b3] Traceback (most recent call last):
  File "C:\SickRage\sickbeard\logger.py", line 367, in submit_errors
    for report in reports:
  File "C:\SickRage\lib\github\PaginatedList.py", line 48, in __iter__
    newElements = self._grow()
  File "C:\SickRage\lib\github\PaginatedList.py", line 60, in _grow
    newElements = self._fetchNextPage()
  File "C:\SickRage\lib\github\PaginatedList.py", line 161, in _fetchNextPage
    headers=self.__headers
  File "C:\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\lib\github\Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\SickRage\lib\github\Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\SickRage\lib\github\Requester.py", line 275, in __requestRaw
    requestHeaders
  File "C:\Program Files (x86)\Python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "C:\Program Files (x86)\Python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "C:\Program Files (x86)\Python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Program Files (x86)\Python27\lib\httplib.py", line 897, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Python27\lib\httplib.py", line 859, in send
    self.connect()
  File "C:\Program Files (x86)\Python27\lib\httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "C:\Program Files (x86)\Python27\lib\ssl.py", line 353, in wrap_socket
    _context=self)
  File "C:\Program Files (x86)\Python27\lib\ssl.py", line 601, in __init__
    self.do_handshake()
  File "C:\Program Files (x86)\Python27\lib\ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
SSLError: ('_ssl.c:574: The handshake operation timed out',)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by ahummaida** [comment]
### INFO
Python Version: **2.7.11 (default, Jan  9 2016, 16:55:40) [GCC 4.8.5]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@9783c5f4de5d600d249705ce230cca53a9169f65
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [9783c5f] Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/logger.py", line 385, in submit_errors
    for report in reports:
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/PaginatedList.py", line 49, in __iter__
    newElements = self._grow()
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/PaginatedList.py", line 61, in _grow
    newElements = self._fetchNextPage()
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/PaginatedList.py", line 163, in _fetchNextPage
    headers=self.__headers
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/Requester.py", line 215, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/Requester.py", line 268, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/github/Requester.py", line 293, in __requestRaw
    requestHeaders
  File "/opt/lib/python2.7/httplib.py", line 1057, in request
  File "/opt/lib/python2.7/httplib.py", line 1097, in _send_request
  File "/opt/lib/python2.7/httplib.py", line 1053, in endheaders
  File "/opt/lib/python2.7/httplib.py", line 897, in _send_output
  File "/opt/lib/python2.7/httplib.py", line 859, in send
  File "/opt/lib/python2.7/httplib.py", line 1278, in connect
  File "/opt/lib/python2.7/ssl.py", line 352, in wrap_socket
  File "/opt/lib/python2.7/ssl.py", line 579, in __init__
  File "/opt/lib/python2.7/ssl.py", line 808, in do_handshake
SSLError: ('_ssl.c:574: The handshake operation timed out',)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
