### ISSUE TITLE
SQL Error and Missing time zone for network: .... Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by udochrist** [SickRage/SickRage#2786]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@4761a49a93e532ddf59b8aed8cdba69eee519d33
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [4761a49] Missing time zone for network: ITV1. Check valid network is set in indexer (theTVDB) before filing issue.
```

I have tons of these (around 100).
Interestingly enough the first error i get is
``` 
2016-12-20 18:58:50 MAIN :: [4761a49] DB error: too many SQL variables
``` 

Full Log for the SQL error (from view log -> DEBUG)
```
2016-12-20 18:58:51 DEBUG CHECKVERSION :: "/usr/local/git/bin/git" fetch origin : returned successful
AAOperationalError: too many SQL variables
AA sql_results = self.connection.cursor().execute(query, args)
AA File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/db.py", line 108, in _execute
AA sql_results.append(self._execute(qu[0], qu[1], fetchall=fetchall))
AA File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/db.py", line 204, in mass_action
AATraceback (most recent call last):
2016-12-20 18:58:50 ERROR MAIN :: [4761a49] DB error: too many SQL variables
2016-12-20 18:58:50 DEBUG CHECKVERSION :: Executing "/usr/local/git/bin/git" fetch origin with your shell in /usr/local/sickrage/var/SickRage
```

---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by udochrist** [comment]
All logs i can find about the SQL error attached to the initial post.

**Comment by miigotu** [comment]
Stop SR, delete cache.db, start SR.

**Comment by udochrist** [comment]
THX: This seems to do the trick. Up since 2 min and no errors in the log.

**Comment by miigotu** [comment]
https://github.com/SickRage/SickRage/issues/2786#issuecomment-268315648
