### ISSUE TITLE
Cannot login remotely after turning on "Notify on login"

### ISSUE THREAD

**Issue by Xx-Ness-xX** [SickRage/SickRage#2795]
### INFO

Branch/Commit: **master/4761a49a93e532ddf59b8aed8cdba69eee519d33**
OS: **Windows-10-10.0.14393**
What you did: **Turn on Notify on login**
What happened: **Cannot login remotely anymore**
What you expected: **Login remotely**
Logs:
```
AAAttributeError: 'Notifier' object has no attribute 'notify_login'
AA n.notify_login(ipaddress)
AA File "C:\SickRage\sickbeard\notifiers\__init__.py", line 108, in notify_login
AA notifiers.notify_login(self.request.remote_ip)
AA File "C:\SickRage\sickbeard\webserve.py", line 300, in post
AA result = method(*self.path_args, **self.path_kwargs)
AA File "C:\SickRage\lib\tornado\web.py", line 1467, in _execute
AATraceback (most recent call last):
AAHTTPServerRequest(protocol='http', host='********.duckdns.org:8081', method='POST', uri='/login/?next=%2Ferrorlogs%2F', version='HTTP/1.1', remote_ip='50.205.46.74', headers={'Origin': 'http://********.duckdns.org:8081', 'Content-Length': '45', 'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': '********.duckdns.org:8081', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Dnt': '1', 'Connection': 'keep-alive', 'Referer': 'http://********.duckdns.org:8081/login/?next=%2Ferrorlogs%2F', 'Cache-Control': 'max-age=0', 'Cookie': 'advanced_toggle_checked=0; wanted_view=thumb; SID=yBUAACZtAACwcgAAGE8AAP0CAABmGwAA; user="2|1:0|10:1482159859|4:user|44:MDRiNDhhY2IwNzMxNGY3ZjllMWNhNGU2YTgxOWU2ZTQ=|82ab037363912394f259a5e47872c2530398f1c8c20bbd517ce6ce718047347a"; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; imdb_movies_in_theaters_view=thumb; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; imdb_top_dvd_rentals_view=thumb; imdb_top_250_movies_view=thumb', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded'})
AA2016-12-20 13:51:29 ERROR Uncaught exception POST /login/?next=%2Ferrorlogs%2F (50.205.46.74)
```

It just started happening recently, I would say in the last 2 weeks.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
