### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318852/en.xml

### ISSUE THREAD

**Issue by nakyl** [SickRage/SickRage#2799]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@8d1b96f507b88b3098387c5004b88db4f54a0b41
No Log available with ERRORS:
### ERROR
```
Thread-18 :: [8d1b96f] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 2792, in addShowByID
    show_name = get_showname_from_indexer(1, indexer_id)
  File "C:\SickRage\SickRage\sickbeard\helpers.py", line 1734, in get_showname_from_indexer
    s = t[int(indexer_id)]
  File "C:\SickRage\SickRage\lib\tvdb_api\tvdb_api.py", line 953, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "C:\SickRage\SickRage\lib\tvdb_api\tvdb_api.py", line 848, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "C:\SickRage\SickRage\lib\tvdb_api\tvdb_api.py", line 636, in _getetsrc
    raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318852/en.xml

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by HPMSGEN8** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@2ac702b26cb528cbacd3cb35a4392a9f373a1df0
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [2ac702b] Failed doing webui callback: Traceback (most recent call last):
  File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2793, in addShowByID
    show_name = get_showname_from_indexer(1, indexer_id)
  File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1729, in get_showname_from_indexer
    s = t[int(indexer_id)]
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 946, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 841, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 629, in _getetsrc
    raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318852/en.xml

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by EliteNevil** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@43e87014bcd7515e3cb2e50a185361861aed6800
No Log available with ERRORS:
### ERROR
```
Thread-275 :: [43e8701] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2796, in addShowByID
    show_name = get_showname_from_indexer(1, indexer_id)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/helpers.py", line 1729, in get_showname_from_indexer
    s = t[int(indexer_id)]
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdb_api/tvdb_api.py", line 946, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdb_api/tvdb_api.py", line 841, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdb_api/tvdb_api.py", line 629, in _getetsrc
    raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318852/en.xml

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by EliteNevil** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@43e87014bcd7515e3cb2e50a185361861aed6800
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [43e8701] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2796, in addShowByID
    show_name = get_showname_from_indexer(1, indexer_id)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/helpers.py", line 1729, in get_showname_from_indexer
    s = t[int(indexer_id)]
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdb_api/tvdb_api.py", line 946, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdb_api/tvdb_api.py", line 841, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdb_api/tvdb_api.py", line 629, in _getetsrc
    raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318852/en.xml

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Lowmach1ne** [comment]
### INFO
Python Version: **2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]**
Operating System: **Linux-4.4.35-2-pve-x86_64-with-centos-7.3.1611-Core**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-18 :: [7e6e057] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/share/sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/usr/share/sickrage/sickbeard/webserve.py", line 2821, in addShowByID
    show_name = get_showname_from_indexer(1, indexer_id)
  File "/usr/share/sickrage/sickbeard/helpers.py", line 1729, in get_showname_from_indexer
    s = t[int(indexer_id)]
  File "/usr/share/sickrage/lib/tvdb_api/tvdb_api.py", line 946, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/usr/share/sickrage/lib/tvdb_api/tvdb_api.py", line 841, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "/usr/share/sickrage/lib/tvdb_api/tvdb_api.py", line 629, in _getetsrc
    raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318852/en.xml

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by consenti** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@59ce8253f9f43c2297ea4e558373d46c6e2b185b
No Log available with ERRORS:
### ERROR
```
Thread-17 :: [59ce825] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2830, in addShowByID
    show_name = get_showname_from_indexer(1, indexer_id)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1730, in get_showname_from_indexer
    s = t[int(indexer_id)]
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 946, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 841, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 629, in _getetsrc
    raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318852/en.xml

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by consenti** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@59ce8253f9f43c2297ea4e558373d46c6e2b185b
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [59ce825] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2830, in addShowByID
    show_name = get_showname_from_indexer(1, indexer_id)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1730, in get_showname_from_indexer
    s = t[int(indexer_id)]
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 946, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 841, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 629, in _getetsrc
    raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318852/en.xml

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by consenti** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@59ce8253f9f43c2297ea4e558373d46c6e2b185b
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [59ce825] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2830, in addShowByID
    show_name = get_showname_from_indexer(1, indexer_id)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1730, in get_showname_from_indexer
    s = t[int(indexer_id)]
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 946, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 841, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 629, in _getetsrc
    raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318852/en.xml

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
