### ISSUE TITLE
[APP SUBMITTED]: User is banned

### ISSUE THREAD

**Issue by djkemai** [SickRage/SickRage#2803]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@8d1b96f507b88b3098387c5004b88db4f54a0b41
No Log available with ERRORS:
### ERROR
```
Thread-27 :: [8d1b96f] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 1465, in editShow
    if helpers.set_up_anidb_connection() and not anidb_failed:
  File "C:\SickRage\SickRage\sickbeard\helpers.py", line 1155, in set_up_anidb_connection
    return sickbeard.ADBA_CONNECTION.authed()
  File "C:\SickRage\SickRage\lib\adba\__init__.py", line 139, in authed
    self._reAuthenticate()
  File "C:\SickRage\SickRage\lib\adba\__init__.py", line 147, in _reAuthenticate
    resp = self.auth(self._username, self._password)
  File "C:\SickRage\SickRage\lib\adba\__init__.py", line 207, in auth
    return self.handle(AuthCommand(username, password, 3, self.clientname, self.clientver, nat, 1, 'utf8', mtu), callback)
  File "C:\SickRage\SickRage\lib\adba\__init__.py", line 125, in handle
    raise AniDBBannedError("User is banned")
AniDBBannedError: User is banned

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
