### ISSUE TITLE
T411, nothing happen

### ISSUE THREAD

**Issue by sooruz** [SickRage/SickRage#2823]
Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
Branch: master
Commit: 338c416
Version: v2016.12.30-1

OS: Windows

What you did: Can not have torrent files from t411. I reinstalled a new version of Sickrage, with only t411 and a series, could not find the files ..
What happened:
What you expected:
a solution :(
Logs:
2017-01-01 16:41:46 INFO SEARCHQUEUE-MANUAL-260449 :: [T411] :: Performing episode search for Vikings
2017-01-01 16:41:46 INFO SEARCHQUEUE-MANUAL-260449 :: Beginning manual search for: [Vikings - S04E15 - All His Angels]

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [ ] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by jery19** [comment]
I have simiar issue, and it seems to be linked to the t411 provider request.
Pretty sure the error lies here : "AATypeError: string indices must be integers"

Here is the debug log :

2017-01-01 18:12:59 INFO SEARCHQUEUE-MANUAL-312505 :: Unable to find a download for: [Dirk Gently's Holistic Detective Agency - S01E01 - Horizons]
2017-01-01 18:12:59 DEBUG SEARCHQUEUE-MANUAL-312505 :: formatting pattern: %SN - S%0SE%0E - %EN -> Dirk Gently's Holistic Detective Agency - S01E01 - Horizons
2017-01-01 18:12:59 DEBUG SEARCHQUEUE-MANUAL-312505 :: formatting pattern: %SN - S%0SE%0E - %EN -> Dirk Gently's Holistic Detective Agency - S01E01 - Horizons
2017-01-01 18:12:59 INFO SEARCHQUEUE-MANUAL-312505 :: [T411] :: Performing season pack search for Dirk Gently's Holistic Detective Agency
2017-01-01 18:12:59 DEBUG SEARCHQUEUE-MANUAL-312505 :: [T411] :: Fallback season pack search initiate
2017-01-01 18:12:59 DEBUG SEARCHQUEUE-MANUAL-312505 :: [T411] :: Data returned from provider does not contain any torrents
2017-01-01 18:12:59 DEBUG SEARCHQUEUE-MANUAL-312505 :: [T411] :: GET URL: https://api.t411.li/torrents/search/Dirk%20Gently's%20Holistic%20Detective%20Agency%20S01E01*?cid=639&limit=100 [Status: 200]
2017-01-01 18:12:58 DEBUG SEARCHQUEUE-MANUAL-312505 :: [T411] :: Data returned from provider does not contain any torrents
2017-01-01 18:12:58 DEBUG SEARCHQUEUE-MANUAL-312505 :: [T411] :: GET URL: https://api.t411.li/torrents/search/Dirk%20Gently's%20Holistic%20Detective%20Agency%20S01E01*?cid=455&limit=100 [Status: 200]
2017-01-01 18:12:58 DEBUG SEARCHQUEUE-MANUAL-312505 :: [T411] :: Data returned from provider does not contain any torrents
2017-01-01 18:12:58 DEBUG SEARCHQUEUE-MANUAL-312505 :: [T411] :: GET URL: https://api.t411.li/torrents/search/Dirk%20Gently's%20Holistic%20Detective%20Agency%20S01E01*?cid=637&limit=100 [Status: 200]
2017-01-01 18:12:57 DEBUG SEARCHQUEUE-MANUAL-312505 :: [T411] :: Data returned from provider does not contain any torrents
2017-01-01 18:12:57 DEBUG SEARCHQUEUE-MANUAL-312505 :: [T411] :: GET URL: https://api.t411.li/torrents/search/Dirk%20Gently's%20Holistic%20Detective%20Agency%20S01E01*?cid=433&limit=100 [Status: 200]
2017-01-01 18:12:57 DEBUG SEARCHQUEUE-MANUAL-312505 :: [T411] :: Search string: Dirk Gently's Holistic Detective Agency S01E01
2017-01-01 18:12:57 DEBUG SEARCHQUEUE-MANUAL-312505 :: [T411] :: Search Mode: Episode
2017-01-01 18:12:56 INFO SEARCHQUEUE-MANUAL-312505 :: [T411] :: Performing episode search for Dirk Gently's Holistic Detective Agency
AA
AATypeError: string indices must be integers
AA title = torrent['name']
AA File "/opt/sickrage/sickbeard/providers/t411.py", line 118, in search
2017-01-01 18:12:56 DEBUG SEARCHQUEUE-MANUAL-312505 :: [T411] :: Failed parsing provider. Traceback: Traceback (most recent call last):
2017-01-01 18:12:56 DEBUG SEARCHQUEUE-MANUAL-312505 :: [T411] :: Invalid torrent data, skipping result: error
AA
AATypeError: string indices must be integers
AA title = torrent['name']
AA File "/opt/sickrage/sickbeard/providers/t411.py", line 118, in search
2017-01-01 18:12:56 DEBUG SEARCHQUEUE-MANUAL-312505 :: [T411] :: Failed parsing provider. Traceback: Traceback (most recent call last):
2017-01-01 18:12:56 DEBUG SEARCHQUEUE-MANUAL-312505 :: [T411] :: Invalid torrent data, skipping result: code
2017-01-01 18:12:56 DEBUG SEARCHQUEUE-MANUAL-312505 :: [T411] :: GET URL: https://api.t411.li/torrents/top/today [Status: 200]
2017-01-01 18:12:45 DEBUG SEARCHQUEUE-MANUAL-312505 :: [T411] :: Search Mode: RSS
2017-01-01 18:12:45 INFO SEARCHQUEUE-MANUAL-312505 :: Beginning manual search for: [Dirk Gently's Holistic Detective Agency - S01E01 - Horizons]
2017-01-01 18:12:45 DEBUG SEARCHQUEUE-MANUAL-312505 :: formatting pattern: %SN - S%0SE%0E - %EN -> Dirk Gently's Holistic Detective Agency - S01E01 - Horizons
2017-01-01 18:12:15 DEBUG Thread-17 :: git ls-remote --heads origin : returned successful
2017-01-01 18:12:13 DEBUG Thread-17 :: Executing git ls-remote --heads origin with your shell in /opt/sickrage
2017-01-01 18:12:13 DEBUG Thread-17 :: git symbolic-ref -q HEAD : returned successful
2017-01-01 18:12:13 DEBUG Thread-17 :: Executing git symbolic-ref -q HEAD with your shell in /opt/sickrage
2017-01-01 18:12:13 DEBUG Thread-17 :: git config remote.origin.url https://github.com/SickRage/SickRage.git : returned successful
2017-01-01 18:12:12 DEBUG Thread-17 :: Executing git config remote.origin.url https://github.com/SickRage/SickRage.git with your shell in /opt/sickrage

**Comment by sooruz** [comment]
Awkward, everything be alright now.

**Comment by miigotu** [comment]
Their api is not working properly:
![image](https://cloud.githubusercontent.com/assets/390379/21583665/0eb808a6-d040-11e6-8bb1-291546a73a80.png)

**Comment by miigotu** [comment]
Their api os not working:
![image](https://cloud.githubusercontent.com/assets/390379/21583670/36d47130-d040-11e6-8f3e-3c60dc5cbc60.png)

**Comment by izanagi1995** [comment]
API back! @miigotu auth route is a POST request

**Comment by miigotu** [comment]
Anyways, its working now. Their api was not working.

**Comment by miigotu** [comment]
dupe #2821
