### ISSUE TITLE
Error Connecting to TorrentDay

### ISSUE THREAD

**Issue by bmccully** [SickRage/SickRage#2834]
Hey Guys

For the last couple of weeks SickRage hasn't been able to find any episodes. Please see below logs. I have double checked that I have got the correct uid and pass. still no go, could anyone point me in the right direction?

Branch/Commit: Master - 423e15fc270c49ec94fc5a11df3d212dbb3e83f4
OS: Open Media Vault
What you did: No Changes, I double checked that I have the correct uid and pass.
What happened: For the last couple of weeks episodes haven't been downloading.
What you expected: Episodes to download.
Logs:
```
2017-01-04 19:27:57 INFO SEARCHQUEUE-MANUAL-75682 :: Unable to find a download for: [Bones - S12E01 - The Hope in the Horror]
2017-01-04 19:27:57 WARNING SEARCHQUEUE-MANUAL-75682 :: [TorrentDay] :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.
AAAttributeError: 'NoneType' object has no attribute 'status_code'
AA if response.status_code not in [200]:
AA File "/opt/sickbeard/sickbeard/providers/torrentday.py", line 82, in login
AA if not self.login():
AA File "/opt/sickbeard/sickbeard/providers/torrentday.py", line 98, in search
AA items_list += self.search(search_string, ep_obj=episode)
AA File "/opt/sickbeard/sickrage/providers/GenericProvider.py", line 152, in find_search_results
AA searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
AA File "/opt/sickbeard/sickbeard/search.py", line 479, in searchProviders
AATraceback (most recent call last):
2017-01-04 19:27:57 ERROR SEARCHQUEUE-MANUAL-75682 :: [TorrentDay] :: [423e15f] Exception while searching TorrentDay. Error: AttributeError("'NoneType' object has no attribute 'status_code'",)
2017-01-04 19:27:57 INFO SEARCHQUEUE-MANUAL-75682 :: [TorrentDay] :: Request failed: 403 Client Error: Forbidden for url: https://classic.torrentday.com/t
2017-01-04 19:27:57 INFO SEARCHQUEUE-MANUAL-75682 :: [TorrentDay] :: Performing episode search for Bones
2017-01-04 19:27:57 INFO SEARCHQUEUE-MANUAL-75682 :: Beginning manual search for: [Bones - S12E01 - The Hope in the Horror]
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
TorrentDay works fine here, your cookies must be set wrong

**Comment by skar42** [comment]
Actually this may be due to the fact that some locations block torrent URL's like this one. I have to change mine from https://classic.torrentday.com to https://torrentday.it

The file I have to amend when I do any updates to Sickrage from git hub is: SickRage/sickbeard/providers/torrentday.py

The line in question is around line 50. Restart Sickrage when you're done.
