### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by meukr** [SickRage/SickRage#2917]
Hello,
After an update of my system (Debian Testing/Stretch) followed by an update of Sickrage, at the restart I can't access to the web page.

Certificates seems too weaks.

Even trying disabling https, ssl_verify and deleting certificates to get them regenerated.

Here is the logs:

```
2017-01-16 12:55:51 DEBUG    CHECKVERSION :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2017-01-16 12:55:51 DEBUG    CHECKVERSION :: cur_commit = 87e5ce80cda49518d2ece8a9075d73ca53ec8405, newest_commit = 87e5ce80cda49518d2ece8a9075d73ca53ec8405, num_commits_behind = 0, num_commits_ahead = 0
2017-01-16 12:55:51 DEBUG    CHECKVERSION :: check_for_new_news: Checking GitHub for latest news.
2017-01-16 12:56:56 ERROR    Exception in callback (<socket._socketobject object at 0x7f4527dfd520>, <function null_wrapper at 0x7f4527dd3140>)
Traceback (most recent call last):
  File "/opt/sickrage/lib/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/opt/sickrage/lib/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/sickrage/lib/tornado/netutil.py", line 272, in accept_handler
    callback(connection, address)
  File "/opt/sickrage/lib/tornado/tcpserver.py", line 244, in _handle_connection
    do_handshake_on_connect=False)
  File "/opt/sickrage/lib/tornado/netutil.py", line 513, in ssl_wrap_socket
    context = ssl_options_to_context(ssl_options)
  File "/opt/sickrage/lib/tornado/netutil.py", line 490, in ssl_options_to_context
    context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
SSLError: [SSL: CA_MD_TOO_WEAK] ca md too weak (_ssl.c:2699)

```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
No clue what version of SR you are using, but I am running ubuntu 17.04 (zesty) dev with https enabled and no issues.

**Comment by meukr** [comment]
I use the last version of SR base on the git master, It appears in the begin of the logs. Maybe the update of SR went bad, I'll try a fresh install.
The exception appears when I tried to access SR in http or https.

**Comment by miigotu** [comment]
Can you stop SR, delete the keys it generated, edit sickbeard/helpers.py and change the `1024` to `4096` on these two lines (Lines 825, 830 at this time)?
`cakey = createKeyPair(TYPE_RSA, 1024)`
`pkey = createKeyPair(TYPE_RSA, 1024)`

**Comment by meukr** [comment]
Not working better, even with a fresh git clone. TYPE_DSA not working either.
The issue could be related to the Debian...

**Comment by miigotu** [comment]
Ill test with debian in a vm later

**Comment by miigotu** [comment]
BTW, you did restart SR after disabling https before you tried right? Also, if you disabled http by editting the config file you had SR stopped when you made the change?

**Comment by meukr** [comment]
It's working with https disabled

**Comment by miigotu** [comment]
How did you install pyopenssl?  Maybe you need to pip install -U on those packages if you installed with pip

**Comment by meukr** [comment]
My pyopenssl is installed by the apt package manager : from dpkg -l : 

ii  python-openssl                        16.2.0-1                          all          Python 2 wrapper around the OpenSSL library

**Comment by miigotu** [comment]
You can generate the keys manually and it works (ill look into fixing this in the source)
```
cd sickragedir
openssl req -new -x509 -days 3650 -nodes -out server.crt -keyout server.key
```

**Comment by meukr** [comment]
works fine, thanks !

**Comment by WebSpider** [comment]
Please don't forget to close the issue if you feel it is solved :)
