### ISSUE TITLE
[APP SUBMITTED]: Parsing failed with several errors.
First error at line 1004.

### ISSUE THREAD

**Issue by xmenxmen** [SickRage/SickRage#2950]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4186c3b2880f1f36133aba2fc6767606260d554c
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [4186c3b] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 269, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 4012, in saveGeneral
    sickbeard.save_config()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 1705, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8')
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/configobj.py", line 1302, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 1004.

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by xmenxmen** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4186c3b2880f1f36133aba2fc6767606260d554c
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [4186c3b] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 269, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 4012, in saveGeneral
    sickbeard.save_config()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 1705, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8')
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/configobj.py", line 1302, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 1004.

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by xmenxmen** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4186c3b2880f1f36133aba2fc6767606260d554c
No Log available with ERRORS:
### ERROR
```
Thread-17 :: [4186c3b] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 269, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 3713, in index
    sickbeard.save_config()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 1705, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8')
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/configobj.py", line 1302, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 1004.

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
Check your config.ini, at line 1004 there is an error in it.

**Comment by xmenxmen** [comment]
Here you have the  line 1004,i dont know what to look after.

[NZBFINDER_WS]
1001nzbfinder_ws = 0
1002 nzbfinder_ws_search_mode = eponly
10031nzbfinder_ws_search_fallback = 0
1004 nzbfinder_ws_enable_daily = 1
1005 nzbfinder_ws_enable_backlog = 1

**Comment by miigotu** [comment]
look above and below that for a strange line (probably no = on the line).  Not sure if the line numbers count blank lines

**Comment by miigotu** [comment]
If you cant find the problem, you could either rename config.ini and let it generate another one (and have to reset all of your settings), or send me the ini and I can try to find the bad line for you. GL

**Comment by xmenxmen** [comment]
I gave up, and made a new install.
And use the backup file to restore.
Now every thing is working again.
Thanks for your answer.
