### ISSUE TITLE
{BUG OR NOT] There is a newer version available (you're 10126 commits behind) — Update Now

### ISSUE THREAD

**Issue by HPMSGEN8** [SickRage/SickRage#2977]
Hi All

I just got this notification "There is a newer version available (you're 10126 commits behind)— Update Now"

Is this an bug or correct ? 

Branch: master
Commit: a3ce318f2c3b207da474db4c8e3cf62bb9032e0e
Version: v2017.01.19-1
Database Version: 44.0

OS: Synology
What you did: Nothing
What happened: Update Available 
What you expected: Small Update Not So Massive 
Logs:
```
https://github.com/SickRage/SickRage/compare/a3ce318f2c3b207da474db4c8e3cf62bb9032e0e...797ce21e86fa97adbd03190593419807f9bfaa46
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Just update it. Likely your config.ini has a commit hash that is no longer in the repo due to rebasing.

**Comment by HPMSGEN8** [comment]
I have just done so ad now i am getting this

`AA AttributeError: 'module' object has no attribute 'SICKRAGE_BACKGROUND'
AA __M_writer(unicode(sickbeard.SICKRAGE_BACKGROUND))
AA File "/usr/local/sickbeard-custom/var/cache/mako/layouts/main.mako.py", line 117, in render_body
AA callable_(context, *args, **kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 890, in _exec_template
AA _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 864, in _render_context
AA **_kwargs_for_callable(callable_, data))
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 829, in _render
AA as_unicode=True)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 454, in render_unicode
AA kwargs['header'] = _('Mako Error')
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 160, in render
AA if url[:3] != 'api':
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 183, in write_error
AA self.write_error(status_code, **kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/web.py", line 994, in send_error
AA Traceback (most recent call last):
AA 2017-01-26 09:29:04 ERROR Uncaught exception in write_error
AA AttributeError: 'module' object has no attribute 'SICKRAGE_BACKGROUND'
AA __M_writer(unicode(sickbeard.SICKRAGE_BACKGROUND))
AA File "/usr/local/sickbeard-custom/var/cache/mako/layouts/main.mako.py", line 117, in render_body
AA callable_(context, *args, **kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 890, in _exec_template
AA _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 864, in _render_context
AA **_kwargs_for_callable(callable_, data))
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 829, in _render
AA as_unicode=True)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 454, in render_unicode
AA kwargs['header'] = _('Mako Error')
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 160, in render
AA if url[:3] != 'api':
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 183, in write_error
AA self.write_error(status_code, **kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/web.py", line 994, in send_error
AA Traceback (most recent call last):
AA 2017-01-26 09:29:04 ERROR Uncaught exception in write_error
AA 
AA AttributeError: 'module' object has no attribute 'SICKRAGE_BACKGROUND'
AA __M_writer(unicode(sickbeard.SICKRAGE_BACKGROUND))
AA File "/usr/local/sickbeard-custom/var/cache/mako/layouts/main.mako.py", line 117, in render_body
AA callable_(context, *args, **kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 890, in _exec_template
AA _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 864, in _render_context
AA **_kwargs_for_callable(callable_, data))
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 829, in _render
AA as_unicode=True)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 454, in render_unicode
AA kwargs['header'] = _('Mako Error')
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 160, in render
AA log_filter=log_filter, log_search=log_search,
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 5298, in viewlog
AA kwargs[arg] = value[0]
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 269, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/thread.py", line 61, in run
AA exec('raise exc_type, exc_value, traceback', {}, locals_)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_compat.py", line 107, in reraise
AA reraise(self._exception, self._traceback)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_base.py", line 359, in __get_result
AA return self.__get_result()
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_base.py", line 400, in result
AA value = future.result()
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/gen.py", line 1015, in run
AA method = getattr(self, _route)
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 253, in get
AA 
AA AttributeError: 'module' object has no attribute 'SICKRAGE_BACKGROUND'
AA __M_writer(unicode(sickbeard.SICKRAGE_BACKGROUND))
AA File "/usr/local/sickbeard-custom/var/cache/mako/layouts/main.mako.py", line 117, in render_body
AA callable_(context, *args, **kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 890, in _exec_template
AA _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 864, in _render_context
AA **_kwargs_for_callable(callable_, data))
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 829, in _render
AA as_unicode=True)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 454, in render_unicode
AA kwargs['header'] = _('Mako Error')
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 160, in render
AA if backup is True:
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1216, in update
AA kwargs[arg] = value[0]
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 269, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/thread.py", line 61, in run
AA exec('raise exc_type, exc_value, traceback', {}, locals_)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_compat.py", line 107, in reraise
AA reraise(self._exception, self._traceback)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_base.py", line 359, in __get_result
AA return self.__get_result()
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_base.py", line 400, in result
AA value = future.result()
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/gen.py", line 1015, in run
AA method = getattr(self, _route)
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 253, in get
AA AttributeError: 'module' object has no attribute 'SICKRAGE_BACKGROUND'
AA __M_writer(unicode(sickbeard.SICKRAGE_BACKGROUND))
AA File "/usr/local/sickbeard-custom/var/cache/mako/layouts/main.mako.py", line 117, in render_body
AA callable_(context, *args, **kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 890, in _exec_template
AA _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 864, in _render_context
AA **_kwargs_for_callable(callable_, data))
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 829, in _render
AA as_unicode=True)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 454, in render_unicode
AA kwargs['header'] = _('Mako Error')
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 160, in render
AA log_filter=log_filter, log_search=log_search,
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 5298, in viewlog
AA kwargs[arg] = value[0]
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 269, in async_call
AA Traceback (most recent call last):
AA AttributeError: 'module' object has no attribute 'SICKRAGE_BACKGROUND'
AA __M_writer(unicode(sickbeard.SICKRAGE_BACKGROUND))
AA File "/usr/local/sickbeard-custom/var/cache/mako/layouts/main.mako.py", line 117, in render_body
AA callable_(context, *args, **kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 890, in _exec_template
AA _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 864, in _render_context
AA **_kwargs_for_callable(callable_, data))
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 829, in _render
AA as_unicode=True)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 454, in render_unicode
AA kwargs['header'] = _('Mako Error')
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 160, in render
AA log_filter=log_filter, log_search=log_search,
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 5298, in viewlog
AA kwargs[arg] = value[0]
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 269, in async_call
2017-01-26 09:29:04 ERROR AUTO :: [25cdaec] Failed doing webui callback: Traceback (most recent call last):
AA AttributeError: 'module' object has no attribute 'SICKRAGE_BACKGROUND'
AA __M_writer(unicode(sickbeard.SICKRAGE_BACKGROUND))
AA File "/usr/local/sickbeard-custom/var/cache/mako/layouts/main.mako.py", line 117, in render_body
AA callable_(context, *args, **kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 890, in _exec_template
AA _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 864, in _render_context
AA **_kwargs_for_callable(callable_, data))
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 829, in _render
AA as_unicode=True)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 454, in render_unicode
AA kwargs['header'] = _('Mako Error')
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 160, in render
AA if backup is True:
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1216, in update
AA kwargs[arg] = value[0]
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 269, in async_call
AA Traceback (most recent call last):
AA AttributeError: 'module' object has no attribute 'SICKRAGE_BACKGROUND'
AA __M_writer(unicode(sickbeard.SICKRAGE_BACKGROUND))
AA File "/usr/local/sickbeard-custom/var/cache/mako/layouts/main.mako.py", line 117, in render_body
AA callable_(context, *args, **kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 890, in _exec_template
AA _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 864, in _render_context
AA **_kwargs_for_callable(callable_, data))
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 829, in _render
AA as_unicode=True)
AA File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 454, in render_unicode
AA kwargs['header'] = _('Mako Error')
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 160, in render
AA if backup is True:
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1216, in update
AA kwargs[arg] = value[0]
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 269, in async_call`

**Comment by miigotu** [comment]
restart it?

**Comment by HPMSGEN8** [comment]
I just saw this in the logs but it restarted and updated and so far stable.  If this is nothing to worry about then all good.

Thanks :)
