### ISSUE TITLE
Fatal error executing query: string or blob too big

### ISSUE THREAD

**Issue by dd6905** [SickRage/SickRage#2986]
I was using SickBeard and then moved to SickRage perfectly fine for a while, and yesturday it just stopped and all the pages show this kind of error. I think I might have too many shows? I have about 120 TV shows I'm watching, and another 30 TV shows that are ended that are still in there. I didn't add any shows recently. I obfuscated the username.

Error

string or blob too big

Traceback

Traceback (most recent call last): 
File "C:\Users\XXXXX\Desktop\SickRage\SickRage\lib\tornado\web.py", line 1469, in _execute result = yield result 
File "C:\Users\XXXXX\Desktop\SickRage\SickRage\lib\tornado\gen.py", line 1015, in run value = future.result() 
File "C:\Users\XXXXX\Desktop\SickRage\SickRage\lib\tornado\concurrent.py", line 237, in result raise_exc_info(self._exc_info) 
File "C:\Users\XXXXX\Desktop\SickRage\SickRage\lib\tornado\gen.py", line 1021, in run yielded = self.gen.throw(*exc_info) 
File "C:\Users\XXXXX\Desktop\SickRage\SickRage\sickbeard\webserve.py", line 253, in get results = yield self.async_call(method) 
File "C:\Users\XXXXX\Desktop\SickRage\SickRage\lib\tornado\gen.py", line 1015, in run value = future.result() 
File "C:\Users\XXXXX\Desktop\SickRage\SickRage\lib\concurrent\futures\_base.py", line 400, in result return self.__get_result() 
File "C:\Users\XXXXX\Desktop\SickRage\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "C:\Users\XXXXX\Desktop\SickRage\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "C:\Users\XXXXX\Desktop\SickRage\SickRage\lib\concurrent\futures\thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "C:\Users\XXXXX\Desktop\SickRage\SickRage\sickbeard\webserve.py", line 269, in async_call result = function(**kwargs) 
File "C:\Users\XXXXX\Desktop\SickRage\SickRage\sickbeard\webserve.py", line 1371, in displayShow show_obj.exceptions = sickbeard.scene_exceptions.get_scene_exceptions(show_obj.indexerid) 
File "C:\Users\XXXXX\Desktop\SickRage\SickRage\sickbeard\scene_exceptions.py", line 83, in get_scene_exceptions [indexer_id, season]) 
File "C:\Users\XXXXX\Desktop\SickRage\SickRage\sickbeard\db.py", line 287, in select sql_results = self.action(query, args, fetchall=True) 
File "C:\Users\XXXXX\Desktop\SickRage\SickRage\sickbeard\db.py", line 257, in action sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone) 
File "C:\Users\XXXXX\Desktop\SickRage\SickRage\sickbeard\db.py", line 108, in _execute sql_results = self.connection.cursor().execute(query, args) 
DataError: string or blob too big 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /home/displayShow?show=281630
query_arguments: {'show': ['281630']}
_start_time: 1485397892.62
headers: Accept-Language: en-US,en;q=0.8 Accept-Encoding: gzip, deflate, sdch, br Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8 User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36 Host: localhost:8082 Referer: http://localhost:8082/home/ Cookie: __utma=111872281.884184373.1476000744.1476000744.1476000744.1; __utmz=111872281.1476000744.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; imdb_top_dvd_rentals_view=thumb; advanced_toggle_checked=0; wanted_view=thumb; manage_view=thumb Upgrade-Insecure-Requests: 1 
host: localhost:8082
version: HTTP/1.1
arguments: {'show': '281630'}
_finish_time: None
query: show=281630
path: /home/displayShow
method: GET
remote_ip: 127.0.0.1

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Trust me you dont have too many shows haha, some users have thousands.  I believe your db became corrupted, maybe the disk it is on is failing?  Try backing up the sickbeard.db while SR is stopped, THEN delete cache.db and start it up. If that doesnt fix it stop it again and delete sickbeard.db (you have it backed up elsewhere because I told you to up there ^) and start it up. Then add existing shows if that fixes it.

**Comment by dd6905** [comment]
Thousands of shows?!?!?! Crazy people!... well, at least now I have
something to aspire to. haha. I did a backup, and tried shutting down the
SickRage, but it stayed at the "SickRage is shutting down..." for over 20
minutes and doesn't seem to shut down as I can use SR if I open another
tab. Resistance was futile. Is there some manual procedures to shut down
like killing some processes in Task Manager? There was about 28G of free
space SSD so I'm ruling that out for now. A few weeks back I was running
out of memory and for some strange reason my Virtual Memory set disabled,
so I re-enabled it, but SR was working fine during and after then. The
SickRage.db was about 12.5MB. and there was a sickbeard.db.v42. I wasn't
sure if I should eventually erase this file as well. Please advise on next
steps.

**Comment by miigotu** [comment]
If you are on windows and installed with the installer, go to services and find SickRage and stop it.  the other db backups are nbd, you can leave them.  Btw I wouldnt recommend the SR db being on an SSD because of constant rw, maybe the SSD developed a bad block where the db is.

**Comment by dd6905** [comment]
Okay, I was able to stop SR, remove the cache.db, and I checked with a
couple shows and seems to get past that problem. But I am concerned about
the statement about the SSD. I think many laptops come with SSD these days,
and to swap to a rotational drive and loose performance for one application
is asking a bit much. My laptop as well as many others only support 1 HD so
I can't fit a 2nd one to accommodate. There should be some big warning
somewhere multiple times

1) Bug: Can't shutdown using the normal shutdown procedure.
2)

**Comment by miigotu** [comment]
The SSD recommendation I made was not a warning, just a side note. SR is meant to be run on an always-on device, which generally excludes laptops.  However you can run it on anything you like.  The not stopping with normal procedure is not really a bug, just a side effect of running it as a service, since the service manager just automatically restarts it when you shut it down.

**Comment by dd6905** [comment]
thanks for your help.
