### ISSUE TITLE
[APP SUBMITTED]: [Error 87] The parameter is incorrect

### ISSUE THREAD

**Issue by TATUMTOT** [SickRage/SickRage#2991]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012ServerR2-6.3.9600**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@25cdaec9d009b311d33ed4468ae2735f785e377a
No Log available with ERRORS:
### ERROR
```
Thread-17 :: [25cdaec] Failed doing webui callback: Traceback (most recent call last):
  File "E:\SickRage\sickbeard\webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "E:\SickRage\sickbeard\webserve.py", line 4272, in savePostProcessing
    if self.isRarSupported() != 'not supported':
  File "E:\SickRage\sickbeard\webserve.py", line 4419, in isRarSupported
    check = rarfile._check_unrar_tool()
  File "E:\SickRage\lib\rarfile\__init__.py", line 2931, in _check_unrar_tool
    custom_check([ORIG_UNRAR_TOOL], True)
  File "E:\SickRage\lib\rarfile\__init__.py", line 2823, in custom_check
    p = custom_popen(cmd)
  File "E:\SickRage\lib\rarfile\__init__.py", line 2813, in custom_popen
    creationflags=creationflags)
  File "E:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "E:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 87] The parameter is incorrect

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by TATUMTOT** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012ServerR2-6.3.9600**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@25cdaec9d009b311d33ed4468ae2735f785e377a
No Log available with ERRORS:
### ERROR
```
Thread-38 :: [25cdaec] Failed doing webui callback: Traceback (most recent call last):
  File "E:\SickRage\sickbeard\webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "E:\SickRage\sickbeard\webserve.py", line 4419, in isRarSupported
    check = rarfile._check_unrar_tool()
  File "E:\SickRage\lib\rarfile\__init__.py", line 2931, in _check_unrar_tool
    custom_check([ORIG_UNRAR_TOOL], True)
  File "E:\SickRage\lib\rarfile\__init__.py", line 2823, in custom_check
    p = custom_popen(cmd)
  File "E:\SickRage\lib\rarfile\__init__.py", line 2813, in custom_popen
    creationflags=creationflags)
  File "E:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "E:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 87] The parameter is incorrect

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
First, make sure you have winrar installed (it IS require now). Then, please try the develop branch, thanks.

**Comment by TATUMTOT** [comment]
Yes i have winrar installed.

Get the samething in the DEV Branch. so i will have to get edit the config to re-enable unpack

AA TypeError: tuple indices must be integers, not NoneType
AA return ('not supported', 'supported')[check]
AA File "E:\SickRage\sickbeard\webserve.py", line 4438, in isRarSupported
AA if self.isRarSupported() != 'not supported':
AA File "E:\SickRage\sickbeard\webserve.py", line 4274, in savePostProcessing
AA result = function(**kwargs)
AA File "E:\SickRage\sickbeard\webserve.py", line 273, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "E:\SickRage\lib\concurrent\futures\thread.py", line 61, in run
AA exec('raise exc_type, exc_value, traceback', {}, locals_)
AA File "E:\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise
AA reraise(self._exception, self._traceback)
AA File "E:\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result
AA return self.__get_result()
AA File "E:\SickRage\lib\concurrent\futures\_base.py", line 400, in result
AA value = future.result()
AA File "E:\SickRage\lib\tornado\gen.py", line 1015, in run
AA results = yield self.async_call(method)
AA File "E:\SickRage\sickbeard\webserve.py", line 257, in get
AA yielded = self.gen.throw(*exc_info)
AA File "E:\SickRage\lib\tornado\gen.py", line 1021, in run
AA raise_exc_info(self._exc_info)
AA File "E:\SickRage\lib\tornado\concurrent.py", line 237, in result
AA value = future.result()
AA File "E:\SickRage\lib\tornado\gen.py", line 1015, in run
AA result = yield result
AA File "E:\SickRage\lib\tornado\web.py", line 1469, in _execute
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='https', host='

**Comment by TATUMTOT** [comment]
everything is working like it should now as the system is functioning but you just cant make that modification through the GUI
