### ISSUE TITLE
Unrar Executable not found when unpack option is selected

### ISSUE THREAD

**Issue by mudsloth** [SickRage/SickRage#2992]
Branch/Commit: Master
OS: Windows 10
What you did: Clicked the "Unpack" option in the Post-processing options
What happened: Error pops up saying "Unrar Executable not found"
What you expected: The option should remain checked and rars should unpack when downloaded.
Logs:
```
2017-01-26 07:14:25 Thread-26 :: [25cdaec] Failed doing webui callback: Traceback (most recent call last):
File "C:\Program Files\SickRage\sickbeard\webserve.py", line 271, in async_call
result = function(**kwargs)
File "C:\Program Files\SickRage\sickbeard\webserve.py", line 4272, in savePostProcessing
if self.isRarSupported() != 'not supported':
File "C:\Program Files\SickRage\sickbeard\webserve.py", line 4419, in isRarSupported
check = rarfile._check_unrar_tool()
File "C:\Program Files\SickRage\lib\rarfile\__init__.py", line 2931, in _check_unrar_tool
custom_check([ORIG_UNRAR_TOOL], True)
File "C:\Program Files\SickRage\lib\rarfile\__init__.py", line 2823, in custom_check
p = custom_popen(cmd)
File "C:\Program Files\SickRage\lib\rarfile\__init__.py", line 2813, in custom_popen
creationflags=creationflags)
File "C:\Python27\lib\subprocess.py", line 710, in __init__
errread, errwrite)
File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
startupinfo)
WindowsError: [Error 87] The parameter is incorrect
```

My understanding is that on a Windows install I shouldn't need anything custom setup. There is an unrar64.dll file under \SickRage\lib\unrar2\UnRARDLL\x64\ folder. I've heard that a few users have suddenly encountered this same error in the last day.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by oopled** [comment]
Branch/Commit: Master
OS: Windows 10
What you did: Postprocessing error log 
AA RarCannotExec: Unrar not installed? (rarfile.UNRAR_TOOL='unrar')
AA raise RarCannotExec("Unrar not installed? (rarfile.UNRAR_TOOL=%r)" % UNRAR_TOOL)
AA File "C:\SickRage\SickRage\lib\rarfile\__init__.py", line 2816, in custom_popen
AA p = custom_popen(cmd)
AA File "C:\SickRage\SickRage\lib\rarfile\__init__.py", line 885, in _extract
AA self._extract(fnlist, path, pwd)
AA File "C:\SickRage\SickRage\lib\rarfile\__init__.py", line 820, in extractall
AA rar_handle.extractall(path=path)
AA File "C:\SickRage\SickRage\sickbeard\processTV.py", line 361, in unrar
AA Traceback (most recent call last):
2017-01-26 17:46:01 ERROR POSTPROCESSOR-AUTO :: [25cdaec] Failed to extract the archive test.rar: Invalid Rar Archive Usage

**Comment by mudsloth** [comment]
A very slight update. Now I'm not getting this error when I select the unpack checkbox. But, it doesn't save the setting of leaving that checked, and I'm still receiving the same error in the logs.

**Comment by miigotu** [comment]
Add `c:\Program Files\WinRar` to the system path and reboot.

**Comment by mudsloth** [comment]
I don't have WinRar installed. Since it's a Windows installation, I thought installing a separate program was not required, based in this FAQ: https://github.com/SickRage/SickRage/wiki/FAQ%27s-and-Fixes#error-rar-not-supported-no-suitable-rar-unpacker-installed

I do have 7-zip installed, which is in the system path. I tried adding that as an alternate unrar solution but the error remained.

**Comment by miigotu** [comment]
The rarfile library used in SickRage was changed, because the old library has not been maintained for over 2 years, and did not accept important patches in that time.  The old lib had a memory-hole/cpu-lockup problem and also did not support RAR5 rars.  So yes, for now winrar is required on windows until I can smooth out the transition some more by maybe adding the unrar binaries in SR directly.  The new rarfile implementation is the community standard to use in python now, and heavily maintained, but it has the side effect of not supporting the unrar dll.

**Comment by mudsloth** [comment]
Ah, thanks for the explanation. Just tried installing WinRAR, made sure the folder was in the system path, rebooted, and successfully tested "unrar" in a command line. But, unfortunately, SR is still failing to unpack and is giving me the same error:

> 2017-01-26 11:38:19 Thread-23 :: [2ac702b] Failed doing webui callback: Traceback (most recent call last):
File "C:\Program Files\SickRage\sickbeard\webserve.py", line 271, in async_call
result = function(**kwargs)
File "C:\Program Files\SickRage\sickbeard\webserve.py", line 4272, in savePostProcessing
if self.isRarSupported() != 'not supported':
File "C:\Program Files\SickRage\sickbeard\webserve.py", line 4419, in isRarSupported
check = rarfile._check_unrar_tool()
File "C:\Program Files\SickRage\lib\rarfile\__init__.py", line 2931, in _check_unrar_tool
custom_check([ORIG_UNRAR_TOOL], True)
File "C:\Program Files\SickRage\lib\rarfile\__init__.py", line 2823, in custom_check
p = custom_popen(cmd)
File "C:\Program Files\SickRage\lib\rarfile\__init__.py", line 2813, in custom_popen
creationflags=creationflags)
File "C:\Python27\lib\subprocess.py", line 710, in __init__
errread, errwrite)
File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
startupinfo)
WindowsError: [Error 87] The parameter is incorrect

**Comment by miigotu** [comment]
You have to reboot or SR doesnt have the new environment PATH

**Comment by mudsloth** [comment]
I did a full reboot of my computer before testing SR.

**Comment by oopled** [comment]
besides, it was working fine up to the last update

**Comment by oopled** [comment]
I had winrar installed already, but it was not in the path. I manually added it to the env variables, tested in a new cmd window then restarted the sickrage service. That worked, didnt need to reboot

**Comment by mudsloth** [comment]
Working for me now!

I didn't really do anything different other than restart SR a few times, but it successfully processed the file I had.

**Comment by broyuken** [comment]
I have the same issue, and I installed winrar, but now I am getting an access error. What permissions do I need to set to get this to work? The user that I am logged in as, as well as the system user have full control over unrar.exe.

2017-01-26 17:14:33 ERROR POSTPROCESSOR-AUTO :: [2ac702b] Failed to extract the archive  filename.rar: error 5 : Access is denied
AA WindowsError: [Error 5] Access is denied

**Comment by miigotu** [comment]
open an administrator command prompt:
```
net stop sickrage
net start sickrage
```
See if it works then....

Also, can you guys check the develop branch out and see if my last commit helps?

**Comment by broyuken** [comment]
Hi,

I just did the net stop/start sickrage in an admin cmd prompt using the develop branch and I'm still getting access denied.

`Unpacking archive: gays.anatomy.1310.720p-dimension.rar
Failed to extract the archive gays.anatomy.1310.720p-dimension.rar: error 5 : Access is denied`

**Comment by broyuken** [comment]
I think I fixed it, I had to set the path to the unrar from C:\Program Files\WinRAR\ to C:\Program Files\WinRAR\UnRAR.exe including the .exe

**Comment by Vastlee** [comment]
Any chance in the near future that we could get this switched over to use 7zip instead of winrar?

**Comment by peteraclausen** [comment]
Getting the same error:

`2017-02-10 07:31:35 INFO POSTPROCESSOR-MANUAL :: Manual post processing task for X:\Transmission\TV\test completed
2017-02-10 07:31:35 INFO POSTPROCESSOR-MANUAL :: test.rar : Unpacking failed: Unpacking Failed with Invalid Rar Archive Usage. Is unrar installed and on the system PATH?
2017-02-10 07:31:35 INFO POSTPROCESSOR-MANUAL :: Some items were not processed.
2017-02-10 07:31:35 INFO POSTPROCESSOR-MANUAL :: Successfully processed
AA RarCannotExec: Unrar not installed? (rarfile.UNRAR_TOOL='unrar')
AA raise RarCannotExec("Unrar not installed? (rarfile.UNRAR_TOOL=%r)" % UNRAR_TOOL)
AA File "C:\SickRage\lib\rarfile\__init__.py", line 2816, in custom_popen
AA p = custom_popen(cmd)
AA File "C:\SickRage\lib\rarfile\__init__.py", line 885, in _extract
AA self._extract(fnlist, path, pwd)
AA File "C:\SickRage\lib\rarfile\__init__.py", line 820, in extractall
AA rar_handle.extractall(path=rar_extract_path)
AA File "C:\SickRage\sickbeard\processTV.py", line 371, in unrar
AA Traceback (most recent call last):
2017-02-10 07:31:35 ERROR POSTPROCESSOR-MANUAL :: [7e6e057] Failed to extract the archive test.rar: Invalid Rar Archive Usage
2017-02-10 07:31:35 INFO POSTPROCESSOR-MANUAL :: Beginning manual post processing task: X:\Transmission\TV\test`

Winrar is in my path.  and I have rebooted several times and also done the net stop sickrage / net start sickrage.  I can type "unrar" from anywhere and it works and I get:

UNRAR 5.40 x54 freeware Copyright (c) 1993-2016 Alexander Roshal

Branch: master
Commit: 7e6e0575542c3f3e5476663532b1357f3ae1e902
Version: v2017.02.2-1
Database Version: 44.0

Any ideas?

**Comment by peteraclausen** [comment]
Adding this in the web GUI in the "Unrar Location" box under "Post Processing" resolved it for me:

C:\Program Files\WinRAR\UnRAR.exe

**Comment by alexgrist** [comment]
You can also just download the UnRAR.exe on it's own at http://www.rarlab.com/rar/unrarw32.exe and just extract it to a directory in SickRage for use as long as you set the directory you extracted it to.

**Comment by miigotu** [comment]
Could someone try with 7z ? =P

**Comment by alexgrist** [comment]
It won't work. You don't need to install WinRaR, you only need to have the executable and set the path in SickRage to it.
