### ISSUE TITLE
ERROR TORNADO :: [25cdaec] API :: 'NoneType' object has no attribute 'request'

### ISSUE THREAD

**Issue by zerosquared** [SickRage/SickRage#2993]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Win 10
What you did: SR updated on its own yesterday
What happened: started seeing the following error spam itself every 15-20 seconds
What you expected: normal update
Logs: error below
```
PASTE LOGS HERE

AA AttributeError: 'NoneType' object has no attribute 'request'
AA for cur_notification in ui.notifications.get_notifications(self.rh.request.remote_ip):
AA File "C:\Users\xxxx\Documents\GitHub\SickRage\sickbeard\webapi.py", line 1535, in run
AA cur_out_dict = func(cur_args, cur_kwargs).run() # call function and get response
AA File "C:\Users\xxxx\Documents\GitHub\SickRage\sickbeard\webapi.py", line 193, in call_dispatcher
AA out_dict = _call_dispatcher(args, kwargs)
AA File "C:\Users\xxxx\Documents\GitHub\SickRage\sickbeard\webapi.py", line 122, in get
AA Traceback (most recent call last):
2017-01-26 12:30:28 ERROR TORNADO :: [25cdaec] API :: 'NoneType' object has no attribute 'request'

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Did you try turning it off, and then back on again?

**Comment by zerosquared** [comment]
Several times, yes.
