### ISSUE TITLE
[APP SUBMITTED]: getFileList() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by bckwltn** [SickRage/SickRage#3000]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:05:22) [GCC 4.6.4 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@e216414dc835ef5c995154d25a4b3f4b2851f0e9
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [e216414] Failed doing webui callback: Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 621, in index
    return json.dumps(foldersAtPath(path, True, bool(int(includeFiles)), bool(int(imagesOnly))))
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/browser.py", line 119, in foldersAtPath
    file_list = getFileList(parent_path, includeFiles)
TypeError: getFileList() takes exactly 3 arguments (2 given)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by aerandir83** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@e216414dc835ef5c995154d25a4b3f4b2851f0e9
No Log available with ERRORS:
### ERROR
```
Thread-19 :: [e216414] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 621, in index
    return json.dumps(foldersAtPath(path, True, bool(int(includeFiles)), bool(int(imagesOnly))))
  File "C:\SickRage\SickRage\sickbeard\browser.py", line 119, in foldersAtPath
    file_list = getFileList(parent_path, includeFiles)
TypeError: getFileList() takes exactly 3 arguments (2 given)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by aerandir83** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@e216414dc835ef5c995154d25a4b3f4b2851f0e9
No Log available with ERRORS:
### ERROR
```
Thread-22 :: [e216414] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 621, in index
    return json.dumps(foldersAtPath(path, True, bool(int(includeFiles)), bool(int(imagesOnly))))
  File "C:\SickRage\SickRage\sickbeard\browser.py", line 119, in foldersAtPath
    file_list = getFileList(parent_path, includeFiles)
TypeError: getFileList() takes exactly 3 arguments (2 given)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
