### ISSUE TITLE
[APP SUBMITTED]: [Errno 13] Permission denied: u'/opt/sickrage/cache/mako/errorlogs.mako.py'

### ISSUE THREAD

**Issue by patrickstaarink** [SickRage/SickRage#3002]
### INFO
Python Version: **2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-59-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@e216414dc835ef5c995154d25a4b3f4b2851f0e9
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [e216414] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 5286, in index
    t = PageTemplate(rh=self, filename="errorlogs.mako")
  File "/opt/sickrage/sickbeard/webserve.py", line 115, in __init__
    self.template = lookup.get_template(filename)
  File "/opt/sickrage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/opt/sickrage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/opt/sickrage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/opt/sickrage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/opt/sickrage/lib/mako/compat.py", line 87, in load_module
    fp = open(path, 'rb')
IOError: [Errno 13] Permission denied: u'/opt/sickrage/cache/mako/errorlogs.mako.py'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Dont delete the cache with SR running, thanks.
