### ISSUE TITLE
No such file or directory: u'/opt/sickrage/cache/mako/layouts/main.mako.py

### ISSUE THREAD

**Issue by julienferla** [SickRage/SickRage#3003]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

> can't access the web UI since the last update

Branch/Commit:
OS: pi - OSMC
What you did: 
update

What happened: 
restart and then can't access the web ui

SSH
**python /opt/sickrage/SickBeard.py**
>>

`[Errno 2] No such file or directory: u'/opt/sickrage/cache/mako/layouts/main.mako.py'
`
**restart the server**
>>
```
09:32:36 INFO::MAIN :: Starting SickRage [master] using '/opt/sickrage/config.ini'
09:32:36 INFO::TORNADO :: Starting SickRage on http://0.0.0.0:8081/
09:32:36 INFO::TORNADO :: Could not start webserver on port 8081, already in use!
```

What you expected:

What can I do ?

Logs:
```
PASTE LOGS HERE

`Error

[Errno 2] No such file or directory: u'/opt/sickrage/cache/mako/layouts/main.mako.py'

Traceback

Traceback (most recent call last): 
File "/opt/sickrage/lib/tornado/web.py", line 1469, in _execute result = yield result 
File "/opt/sickrage/lib/tornado/gen.py", line 1015, in run value = future.result() 
File "/opt/sickrage/lib/tornado/concurrent.py", line 237, in result raise_exc_info(self._exc_info) 
File "/opt/sickrage/lib/tornado/gen.py", line 1021, in run yielded = self.gen.throw(*exc_info) 
File "/opt/sickrage/sickbeard/webserve.py", line 253, in get results = yield self.async_call(method) 
File "/opt/sickrage/lib/tornado/gen.py", line 1015, in run value = future.result() 
File "/opt/sickrage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/opt/sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/opt/sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/opt/sickrage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/opt/sickrage/sickbeard/webserve.py", line 269, in async_call result = function(**kwargs) 
File "/opt/sickrage/sickbeard/webserve.py", line 5272, in index logLevel=level, controller="errorlogs", action="index") 
File "/opt/sickrage/sickbeard/webserve.py", line 159, in render kwargs['backtrace'] = RichTraceback() 
File "/opt/sickrage/lib/mako/exceptions.py", line 93, in __init__ self.records = self._init(traceback) 
File "/opt/sickrage/lib/mako/exceptions.py", line 165, in _init module_source = info.code 
File "/opt/sickrage/lib/mako/template.py", line 632, in code return util.read_python_file(self.module_filename) 
File "/opt/sickrage/lib/mako/util.py", line 374, in read_python_file fp = open(path, "rb") 
IOError: [Errno 2] No such file or directory: u'/opt/sickrage/cache/mako/layouts/main.mako.py' 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /errorlogs/
query_arguments: {}
_start_time: 1485592393.43
headers: Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4,de;q=0.2,it;q=0.2 Accept-Encoding: gzip, deflate, sdch Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8 User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36 Host: 192.168.1.104:8081 Referer: http://192.168.1.104:8081/errorlogs/ Cookie: compact_display_state=false; user="2|1:0|10:1483350211|4:user|44:YzFiYTc5MjFlYWQ2NDQyZTgyZjNkMGRmMWViZDlhZWQ=|3524fd512fb1bbcd579ad33cbf767bdd3da6c36174f902b3093e83306abbc822"; advanced_toggle_checked=1; manage_view=thumb; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; wanted_view=thumb Upgrade-Insecure-Requests: 1 
host: 192.168.1.104:8081
version: HTTP/1.1
arguments: {}
_finish_time: None
query: 
path: /errorlogs/
method: GET
remote_ip: 192.168.1.102

View Log(Errors)


`

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by julienferla** [comment]
Right now I don't know how I can you give more information...

**Comment by miigotu** [comment]
Restart the pi

**Comment by julienferla** [comment]
Hum...  Thanks for your answer.
But I already restart the pi.

But you have maybe a special command I don't know to restart...

**Comment by miigotu** [comment]
I dont know how you installed SR on osmc, but you need to stop the sickrage service and THEN `rm -r /opt/sickrage/cache` and the start the service again.

**Comment by julienferla** [comment]
I Stop sickrage

`sudo service sickrage stop
`
Then
`rm -r /opt/sickrage/cache
`
reboot the pi
`sudo reboot
`
visit 
`http://192.168.1.104:8081/home/
`
and still can't access

when I do on my terminal (ssh)
`python /opt/sickrage/SickBeard.py`

I got the webpage with the error
`[Errno 2] No such file or directory: u'/opt/sickrage/cache/mako/layouts/main.mako.py'
`

and on my terminal I got this message:
```
INFO::MAIN :: Starting SickRage [master] using '/opt/sickrage/config.ini'
INFO::TORNADO :: Starting SickRage on http://0.0.0.0:8081/
INFO::TORNADO :: Could not start webserver on port 8081, already in use!
```

I instal sickrage following this doc:
[Install SickRage Raspberry Pi for Usenet Torrent TV](http://www.htpcguides.com/install-sickrage-raspberry-pi-usenet-torrent-tv/
)
everything was fine since the last month and after the last update I got that

but now :'(

**Comment by miigotu** [comment]
You cant start SR from the command line when the service is running.
```
sudo service sickrage stop
rm -r /opt/sickrage/cache
python /opt/sickrage/SickBeard.py
```


I would chown /opt/sickrage again to the user that SR runs as
```bash
service sickrage stop
rm -r /opt/sickrage/cache
SR_USER = $(grep -oP '(?<=SR_USER=).*$' lala?) chown -R $SR_USER:$SR_USER /opt/sickrage
service sickrage start
```

**Comment by julienferla** [comment]
ok we got some progress...
after doing this command:

`osmc@osmc:~$ sudo SR_USER=$(grep -oP '(?<=SR_USER=).*$' /etc/default/sickrage) && chown -R $osmc:$osmc /opt/sickrage
`
_Did I correctly write it ?_

O the terminal I got:
`osmc@osmc:~$ sudo SR_USER=$(grep -oP '(?<=SR_USER=).*$' /etc/default/sickrage) && chown -R $osmc:$osmc /opt/sickrage
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-u user]
            [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-u user] file ...`

How I use it ?

**Comment by miigotu** [comment]
if you know the user is osmc you just chown it without the magic...
```
chown -R osmc:osmc /opt/sickrage
```

**Comment by julienferla** [comment]
I think I will give up... 
:-(
Thank you for your help but I don't know what can I do next

I try everything, even this...

```
osmc@osmc:~$ sudo service sickrage stop
osmc@osmc:~$ sudo rm -r /opt/sickrage/cache
osmc@osmc:~$ sudo chown -R osmc:osmc /opt/sickrage
osmc@osmc:~$ sudo service sickrage start

```

and still can't load the web ui
and still have the error page after
> `osmc@osmc:~$ python /opt/sickrage/SickBeard.py
`

there is no way to restore from the backup (don't know where is located but.. ) with command line ?

**Comment by miigotu** [comment]
The backup has nothing to do with it, the cache isnt part of the repo.

**Comment by julienferla** [comment]
I'm visibly stuck...

what can I do ?
reinstall ?
When I try t said the folder is already used...

too bad the update crash the system

**Comment by miigotu** [comment]
sudo mv /opt/sickrage /opt/sickrage2
reinstall
copy the config.ini and database from /opt/sickrage2

I can write the software but I cannot administrate your system also.

**Comment by julienferla** [comment]
I save the backup I made before

reinstal and restore it
and eerything work again


Want do you recomand me about the update ?
made everytime the update is there a way to update eery commit ?

What the best practice to avoid an other crash ?

**Comment by miigotu** [comment]
If you want to update manually you do exactly this:
Note: __NO sudo with git__

```bash
sudo service sickrage stop
cd /opt/sickrage
git pull
sudo service sickrage start
```
