### ISSUE TITLE
Sickrage wont launch anymore

### ISSUE THREAD

**Issue by sossienl** [SickRage/SickRage#3035]
Overnight Sickrage is not starting anymore (Windows service is failing).
when running it manually via "python SickBeard.py" it throws this error:

Traceback (most recent call last):
  File "SickBeard.py", line 65, in <module>
    import sickbeard
  File "C:\Downloaden\SickRage\SickRage\sickbeard\__init__.py", line 40, in <module>
    from sickbeard.databases import mainDB, cache_db, failed_db
  File "C:\Downloaden\SickRage\SickRage\sickbeard\databases\mainDB.py", line 30, in <module>
    from sickbeard.name_parser.parser import NameParser, InvalidNameException, InvalidShowException
ImportError: cannot import name NameParser

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sossienl** [comment]
Tried to use GIT to solve the issue, however when running several GIT commands I end up with this issue:

****SickRage>git fetch --all
Fetching origin
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
error: inflate: data stream error (unknown compression method)
fatal: failed to read object 3ace99cd9d9f43263a189a152f41aafb33e0cc53: Invalid argument
error: https://github.com/SickRage/SickRage.git did not send all necessary objects

**Comment by miigotu** [comment]
Your local clone of SR has become corrupted. There are usually only 2 causes of this problem, a git pull was interrupted by an unexpected reboot (power outage, not a normal restart/shutdown), or a failing disk.  I hope for your sake it isn't a disk failing :-1: 

You can try to fix it with this command first:
`git fsck --full`
If that doesnt work copy the c:\SickRage\Data folder somewhere, uninstall and reinstall, then shut the service down and copy the folder back to c:\SickRage\Data and overwrite files (thats basically a manual backup)
