### ISSUE TITLE
UnRAR not found (Windows platform)

### ISSUE THREAD

**Issue by Sjolus** [SickRage/SickRage#3043]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Windows Server 2008 R2 Datacenter
What you did: Tried to let the automatic unpacking do its thing
What happened: Sickrage cannot seem to find the unrar DLL's included with Sickrage
What you expected: Unpacked shows
Logs:
```
2017-01-30 07:53:47 DEBUG    POSTPROCESSOR-AUTO :: Processing folder O:\Shares\Unsorted\sickrage\the.lovely.show.about.nerds.PROPER.S10E13.720p.HDTV.x264-FLEET
2017-01-30 07:53:47 DEBUG    POSTPROCESSOR-AUTO :: O:\Shares\Unsorted\sickrage\the.lovely.show.about.nerds.PROPER.S10E13.720p.HDTV.x264-FLEET : No processable items found in folder
2017-01-30 07:53:47 DEBUG    POSTPROCESSOR-AUTO :: Processing folder O:\Shares\Unsorted\sickrage\the.lovely.show.about.nerds.S10E13.720p.HDTV.X264-DIMENSION
2017-01-30 07:53:47 DEBUG    POSTPROCESSOR-AUTO :: Parsed the.lovely.show.about.nerds.S10E13.720p.HDTV.X264-DIMENSION into The Lovely Show About Nerds - S10E13 [GROUP: DIMENSION] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2017-01-30 07:53:47 DEBUG    POSTPROCESSOR-AUTO :: Packed Releases detected: [u'the.lovely.show.about.nerds.1013.720p-dimension.rar']
2017-01-30 07:53:47 DEBUG    POSTPROCESSOR-AUTO :: Parsed O:\Shares\Unsorted\sickrage\the.lovely.show.about.nerds.S10E13.720p.HDTV.X264-DIMENSION into The Lovely Show About Nerds - S10E13 [GROUP: DIMENSION] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2017-01-30 07:53:47 DEBUG    POSTPROCESSOR-AUTO :: Checking if archive is valid and contains a video: O:\Shares\Unsorted\sickrage\the.lovely.show.about.nerds.S10E13.720p.HDTV.X264-DIMENSION\the.lovely.show.about.nerds.1013.720p-dimension.rar
2017-01-30 07:53:47 DEBUG    POSTPROCESSOR-AUTO :: Parsed O:\Shares\Unsorted\sickrage\the.lovely.show.about.nerds.S10E13.720p.HDTV.X264-DIMENSION\the.lovely.show.about.nerds.1013.720p-dimension into The Lovely Show About Nerds - S10E13 [GROUP: DIMENSION] [ABD: False] [ANIME: False] [whichReg: ['bare', 'standard']]
2017-01-30 07:53:47 DEBUG    POSTPROCESSOR-AUTO :: Unpacking archive: the.lovely.show.about.nerds.1013.720p-dimension.rar
2017-01-30 07:53:47 ERROR    POSTPROCESSOR-AUTO :: [43e8701] Failed to extract the archive the.lovely.show.about.nerds.1013.720p-dimension.rar: Invalid Rar Archive Usage
Traceback (most recent call last):
  File "C:\SickRage\sickbeard\processTV.py", line 371, in unrar
    rar_handle.extractall(path=rar_extract_path)
  File "C:\SickRage\lib\rarfile\__init__.py", line 820, in extractall
    self._extract(fnlist, path, pwd)
  File "C:\SickRage\lib\rarfile\__init__.py", line 885, in _extract
    p = custom_popen(cmd)
  File "C:\SickRage\lib\rarfile\__init__.py", line 2816, in custom_popen
    raise RarCannotExec("Unrar not installed? (rarfile.UNRAR_TOOL=%r)" % UNRAR_TOOL)
RarCannotExec: Unrar not installed? (rarfile.UNRAR_TOOL='unrar')
```

If I understand correctly, the unrar DLL's should be included with sickrage, and I can also find them in the installation directory in a few places.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Sjolus** [comment]
My suspicion is that it is related to this commit/merge, which seems to match with the time I started seeing the issues (The logs have however rotated since I use debug logs continously so I can't confirm the exact time)

https://github.com/SickRage/SickRage/commit/1eca23b956970d2001b236a1489f89cdb1896c12

**Comment by miigotu** [comment]
Read the news in SR.

**Comment by Sjolus** [comment]
I started digging into this and yeah it wouldn't be easy switching to a better software, and I get that, I just want to voice my hatred against needing winrar/rarlabs software on my machine. It's trialware, it's scary, they've fucked up pretty badly before and yeah...

I respect all of your work as developers, and I truly appreciate how easy my life has become since I first found sickrage but I truly am a bit saddened by this change.

All the best, y'all <3

**Comment by miigotu** [comment]
The unrar.dll that was used before was winrar anyways. Every linux system also uses winrars unrar.

**Comment by miigotu** [comment]
Im fairly sure that if you make sure 7z.exe is in path and you change unrar path to 7z it works anyways.  Either way, you are always welcome to make a PR.

**Comment by jrochet** [comment]
Ahh, thanks for the tip.  I'll give that a go.

**Comment by OneGuy83** [comment]
I've been getting "Invalid Rar Archive Usage" from sickrage and when i manually unpack the files with WinRAR i have no issues...

i have reinstalled winRAR and rebooted several times and this issue remains.
