### ISSUE TITLE
[APP SUBMITTED]: [Errno 28] No space left on device: '/var/db/sickrage/cache/mako/tmpfka8kG'

### ISSUE THREAD

**Issue by EliteNevil** [SickRage/SickRage#3066]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@43e87014bcd7515e3cb2e50a185361861aed6800
No Log available with ERRORS:
### ERROR
```
Thread-275 :: [43e8701] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2333, in index
    t = PageTemplate(rh=self, filename="home_postprocess.mako")
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 115, in __init__
    self.template = lookup.get_template(filename)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/mako/template.py", line 703, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "/usr/pbi/sickrage-amd64/lib/python2.7/tempfile.py", line 308, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 28] No space left on device: '/var/db/sickrage/cache/mako/tmpfka8kG'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
