### ISSUE TITLE
Torrent providers search problem 

### ISSUE THREAD

**Issue by jaumard** [SickRage/SickRage#3084]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/7e6e0575542c3f3e5476663532b1357f3ae1e902
OS: raspian / osmc
What you did: Enable TorrentProject, LimeTorrents, ThePirateBay, TokyoToshokan providers
What happened: some errors in logs and nothing is found
What you expected: no errors at least
Logs:
```
AA 
AA AttributeError: 'NoneType' object has no attribute 'group'
AA raise requests_exception
AA File "/home/osmc/sickrage/sickbeard/helpers.py", line 1433, in handle_requests_exception
AA AttributeError: 'NoneType' object has no attribute 'group'
AA raise requests_exception
AA File "/home/osmc/sickrage/sickbeard/helpers.py", line 1433, in handle_requests_exception
AA Traceback (most recent call last):
2017-02-05 11:30:08 ERROR SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [7e6e057] Request failed: 'NoneType' object has no attribute 'group'
2017-02-05 11:29:51 INFO SEARCHQUEUE-DAILY-SEARCH :: [TokyoToshokan] :: Request failed: HTTPConnectionPool(host='tokyotosho.info', port=80): Read timed out. (read timeout=30)
2017-02-05 11:29:49 INFO Thread-19 :: Sending backlog for Supergirl season 2 because some eps were set to wanted
2017-02-05 11:28:58 INFO SEARCHQUEUE-DAILY-SEARCH :: [LimeTorrents] :: Request failed: HTTPSConnectionPool(host='www.limetorrents.cc', port=443): Max retries exceeded with url: /rss/20/ (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused',))
2017-02-05 11:28:42 INFO SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.se', port=443): Max retries exceeded with url: /browse/205/0/4 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused',))
2017-02-05 11:28:42 INFO SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.se', port=443): Max retries exceeded with url: /browse/208/0/4 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused',))
2017-02-
```

I wasn't able to submit issue from sick rage because I use two factor auth and it look like not supported.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Looks like your isp is blocking the sites or your pi has no internet.  None of this is an error on SR part, the attribute error is in python requests
