### ISSUE TITLE
[APP SUBMITTED]: no such column: rls_ignore_words

### ISSUE THREAD

**Issue by ldhookj** [SickRage/SickRage#3094]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [7e6e057] DB error: no such column: rls_ignore_words
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [7e6e057] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1642, in editShow
    show_obj.saveToDB()
  File "/opt/sickrage/sickbeard/tv.py", line 1162, in saveToDB
    main_db_con.upsert("tv_shows", newValueDict, controlValueDict)
  File "/opt/sickrage/sickbeard/db.py", line 326, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/opt/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: no such column: rls_ignore_words

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [7e6e057] DB error: no such column: rls_ignore_words
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [7e6e057] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 3514, in massEditSubmit
    directCall=True)
  File "/opt/sickrage/sickbeard/webserve.py", line 1642, in editShow
    show_obj.saveToDB()
  File "/opt/sickrage/sickbeard/tv.py", line 1162, in saveToDB
    main_db_con.upsert("tv_shows", newValueDict, controlValueDict)
  File "/opt/sickrage/sickbeard/db.py", line 326, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/opt/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: no such column: rls_ignore_words

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-19 :: [7e6e057] DB error: no such column: rls_ignore_words
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-19 :: [7e6e057] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 3514, in massEditSubmit
    directCall=True)
  File "/opt/sickrage/sickbeard/webserve.py", line 1642, in editShow
    show_obj.saveToDB()
  File "/opt/sickrage/sickbeard/tv.py", line 1162, in saveToDB
    main_db_con.upsert("tv_shows", newValueDict, controlValueDict)
  File "/opt/sickrage/sickbeard/db.py", line 326, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/opt/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: no such column: rls_ignore_words

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-18 :: [7e6e057] DB error: no such column: rls_ignore_words
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-18 :: [7e6e057] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 3514, in massEditSubmit
    directCall=True)
  File "/opt/sickrage/sickbeard/webserve.py", line 1642, in editShow
    show_obj.saveToDB()
  File "/opt/sickrage/sickbeard/tv.py", line 1162, in saveToDB
    main_db_con.upsert("tv_shows", newValueDict, controlValueDict)
  File "/opt/sickrage/sickbeard/db.py", line 326, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/opt/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: no such column: rls_ignore_words

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [7e6e057] DB error: no such column: rls_ignore_words
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [7e6e057] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 3514, in massEditSubmit
    directCall=True)
  File "/opt/sickrage/sickbeard/webserve.py", line 1642, in editShow
    show_obj.saveToDB()
  File "/opt/sickrage/sickbeard/tv.py", line 1162, in saveToDB
    main_db_con.upsert("tv_shows", newValueDict, controlValueDict)
  File "/opt/sickrage/sickbeard/db.py", line 326, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/opt/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: no such column: rls_ignore_words

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-20 :: [7e6e057] DB error: no such column: rls_ignore_words
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-20 :: [7e6e057] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1642, in editShow
    show_obj.saveToDB()
  File "/opt/sickrage/sickbeard/tv.py", line 1162, in saveToDB
    main_db_con.upsert("tv_shows", newValueDict, controlValueDict)
  File "/opt/sickrage/sickbeard/db.py", line 326, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/opt/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: no such column: rls_ignore_words

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-17 :: [7e6e057] DB error: no such column: rls_ignore_words
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-17 :: [7e6e057] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1642, in editShow
    show_obj.saveToDB()
  File "/opt/sickrage/sickbeard/tv.py", line 1162, in saveToDB
    main_db_con.upsert("tv_shows", newValueDict, controlValueDict)
  File "/opt/sickrage/sickbeard/db.py", line 326, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/opt/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: no such column: rls_ignore_words

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [7e6e057] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1642, in editShow
    show_obj.saveToDB()
  File "/opt/sickrage/sickbeard/tv.py", line 1162, in saveToDB
    main_db_con.upsert("tv_shows", newValueDict, controlValueDict)
  File "/opt/sickrage/sickbeard/db.py", line 326, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/opt/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: no such column: rls_ignore_words

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [7e6e057] DB error: no such column: rls_ignore_words
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [7e6e057] Error saving show info to the database: no such column: rls_ignore_words
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
