### ISSUE TITLE
[APP SUBMITTED]: no such column: s.indexer_id

### ISSUE THREAD

**Issue by ldhookj** [SickRage/SickRage#3096]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [7e6e057] DB error: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [7e6e057] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 3744, in index
    data = self.history.get(limit)
  File "/opt/sickrage/sickrage/show/History.py", line 69, in get
    results = self.db.select(common_sql + order_sql + 'LIMIT ?', [limit])
  File "/opt/sickrage/sickbeard/db.py", line 287, in select
    sql_results = self.action(query, args, fetchall=True)
  File "/opt/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: no such column: s.indexer_id

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-17 :: [7e6e057] DB error: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ldhookj** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-42-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-17 :: [7e6e057] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 3744, in index
    data = self.history.get(limit)
  File "/opt/sickrage/sickrage/show/History.py", line 69, in get
    results = self.db.select(common_sql + order_sql + 'LIMIT ?', [limit])
  File "/opt/sickrage/sickbeard/db.py", line 287, in select
    sql_results = self.action(query, args, fetchall=True)
  File "/opt/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: no such column: s.indexer_id

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [Rarbg] :: [2d4e83a] DB error: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [Rarbg] :: [2d4e83a] Exception while searching propers in Rarbg, skipping: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [eztv] :: [2d4e83a] DB error: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [eztv] :: [2d4e83a] Exception while searching propers in eztv, skipping: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [LimeTorrents] :: [2d4e83a] DB error: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [LimeTorrents] :: [2d4e83a] Exception while searching propers in LimeTorrents, skipping: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [Torrentz] :: [2d4e83a] DB error: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [Torrentz] :: [2d4e83a] Exception while searching propers in Torrentz, skipping: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [ThePirateBay] :: [2d4e83a] DB error: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [ThePirateBay] :: [2d4e83a] Exception while searching propers in ThePirateBay, skipping: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [Torrent9] :: [2d4e83a] DB error: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [Torrent9] :: [2d4e83a] Exception while searching propers in Torrent9, skipping: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [HorribleSubs] :: [2d4e83a] DB error: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [SkyTorrents] :: [2d4e83a] DB error: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [SkyTorrents] :: [2d4e83a] Exception while searching propers in SkyTorrents, skipping: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [ilCorsaroNero] :: [2d4e83a] DB error: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [ilCorsaroNero] :: [2d4e83a] Exception while searching propers in ilCorsaroNero, skipping: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [Nyaa] :: [2d4e83a] DB error: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [Nyaa] :: [2d4e83a] Exception while searching propers in Nyaa, skipping: no such column: s.indexer_id
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
you cannot use a DB from the "other" sickrage.
