### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by sponnapalli** [SickRage/SickRage#3105]
### INFO
Python Version: **2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-62-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-21 :: [7e6e057] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/opt/SickRage/sickbeard/webserve.py", line 2365, in processEpisode
    process_path = ss(kwargs.get('dir', proc_dir))
  File "/opt/SickRage/sickrage/helper/encoding.py", line 70, in ss
    var = var.encode('utf-8', 'ignore')
AttributeError: 'NoneType' object has no attribute 'encode'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by fontes31** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@7e6e0575542c3f3e5476663532b1357f3ae1e902
No Log available with ERRORS:
### ERROR
```
Thread-64 :: [7e6e057] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2365, in processEpisode
    process_path = ss(kwargs.get('dir', proc_dir))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickrage/helper/encoding.py", line 70, in ss
    var = var.encode('utf-8', 'ignore')
AttributeError: 'NoneType' object has no attribute 'encode'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by csmarshall** [comment]
Looks like it *may* be due to something around this commit:

https://github.com/SickRage/SickRage/commit/7f84c57b91f9a86e252a710e06fb78ffa2c479f2#diff-245c1186ac2a7f4851ef96382afe7b40

@miigotu ?

**Comment by froggay** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@9783c5f4de5d600d249705ce230cca53a9169f65
Link to Log: https://gist.github.com/17e09b2c81ce0d1fa7a2f647e586cc3f
### ERROR
```
SEARCHQUEUE-BACKLOG-266609 :: [TorrentLeech] :: [9783c5f] Exception while searching TorrentLeech. Error: AttributeError("'NoneType' object has no attribute 'encode'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by froggay** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@9783c5f4de5d600d249705ce230cca53a9169f65
Link to Log: https://gist.github.com/1fac82aa556eaaccdad96a0bfaf860f2
### ERROR
```
SEARCHQUEUE-BACKLOG-305288 :: [TorrentLeech] :: [9783c5f] Exception while searching TorrentLeech. Error: AttributeError("'NoneType' object has no attribute 'encode'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by froggay** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@9783c5f4de5d600d249705ce230cca53a9169f65
Link to Log: https://gist.github.com/24ef91c1144f917fd2fd328b421de7c3
### ERROR
```
SEARCHQUEUE-BACKLOG-296956 :: [TorrentLeech] :: [9783c5f] Exception while searching TorrentLeech. Error: AttributeError("'NoneType' object has no attribute 'encode'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by froggay** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@9783c5f4de5d600d249705ce230cca53a9169f65
Link to Log: https://gist.github.com/f16b4794839bb3215f732701547f9f3d
### ERROR
```
SEARCHQUEUE-BACKLOG-311714 :: [TorrentLeech] :: [9783c5f] Exception while searching TorrentLeech. Error: AttributeError("'NoneType' object has no attribute 'encode'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by froggay** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@9783c5f4de5d600d249705ce230cca53a9169f65
Link to Log: https://gist.github.com/f681b6cb36d9d4297e581bafd500aaac
### ERROR
```
SEARCHQUEUE-BACKLOG-76885 :: [TorrentLeech] :: [9783c5f] Exception while searching TorrentLeech. Error: AttributeError("'NoneType' object has no attribute 'encode'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by froggay** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@9783c5f4de5d600d249705ce230cca53a9169f65
Link to Log: https://gist.github.com/155753a93ad4beb16bd34a76f53df585
### ERROR
```
SEARCHQUEUE-BACKLOG-247897 :: [TorrentLeech] :: [9783c5f] Exception while searching TorrentLeech. Error: AttributeError("'NoneType' object has no attribute 'encode'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by froggay** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@9783c5f4de5d600d249705ce230cca53a9169f65
Link to Log: https://gist.github.com/c622fdd72a1cc629ada96260003ab1cc
### ERROR
```
SEARCHQUEUE-BACKLOG-280847 :: [TorrentLeech] :: [9783c5f] Exception while searching TorrentLeech. Error: AttributeError("'NoneType' object has no attribute 'encode'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by froggay** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@9783c5f4de5d600d249705ce230cca53a9169f65
Link to Log: https://gist.github.com/6afd4562ef1c3110f9ec6a03ede3bd9c
### ERROR
```
SEARCHQUEUE-BACKLOG-282401 :: [TorrentLeech] :: [9783c5f] Exception while searching TorrentLeech. Error: AttributeError("'NoneType' object has no attribute 'encode'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by froggay** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@9783c5f4de5d600d249705ce230cca53a9169f65
Link to Log: https://gist.github.com/3d41f011650a282a4da42020d0fce8d1
### ERROR
```
SEARCHQUEUE-BACKLOG-153021 :: [TorrentLeech] :: [9783c5f] Exception while searching TorrentLeech. Error: AttributeError("'NoneType' object has no attribute 'encode'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HitmanThe47** [comment]
### INFO
Python Version: **2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]**
Operating System: **Linux-4.4.121-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@51328d1fb61ebc9704934e3cf14425453196790d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_10 :: [51328d1] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 402, in showPoster
    self.set_header(b'Content-Type', media.get_media_type())
  File "/opt/sickrage/sickrage/media/GenericMedia.py", line 89, in get_media_type
    static_media_path = self.get_static_media_path()
  File "/opt/sickrage/sickrage/media/GenericMedia.py", line 112, in get_static_media_path
    media_path = self.get_media_path()
  File "/opt/sickrage/sickrage/media/ShowNetworkLogo.py", line 40, in get_media_path
    return ek(join, self.get_media_root(), 'images', 'network', show.network_logo_name + '.png')
  File "/opt/sickrage/sickbeard/tv.py", line 156, in network_logo_name
    return unidecode(self.network).lower()
  File "/opt/sickrage/lib/unidecode/__init__.py", line 48, in unidecode_expect_ascii
    bytestring = string.encode('ASCII')
AttributeError: 'NoneType' object has no attribute 'encode'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
