### ISSUE TITLE
[TorrentProject] :: [7e6e057] Request failed: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by fabzeh** [SickRage/SickRage#3108]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Linux-3.2.40-i686-with-glibc2.0
What you did: Nothing, i checked SR and found 10 Errors.
What happened: 2017-02-08 20:25:11 SEARCHQUEUE-BACKLOG-303236 :: [TorrentProject] :: [7e6e057] Request failed: 'NoneType' object has no attribute 'group'
What you expected: No errors at all..

Logs:
```
2017-02-09 16:06:59 MANUAL :: [7e6e057] Traceback (most recent call last):
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 372, in submit_errors
for report in reports:
File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/PaginatedList.py", line 48, in __iter__
newElements = self._grow()
File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/PaginatedList.py", line 60, in _grow
newElements = self._fetchNextPage()
File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/PaginatedList.py", line 161, in _fetchNextPage
headers=self.__headers
File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 171, in requestJsonAndCheck
return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
File "/usr/local/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 179, in __check
raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://developer.github.com/v3/#rate-limiting', u'message': u"API rate limit exceeded for 212.238.174.237. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"}

2017-02-08 20:25:11 SEARCHQUEUE-BACKLOG-303236 :: [TorrentProject] :: [7e6e057] Request failed: 'NoneType' object has no attribute 'group'
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
