### ISSUE TITLE
Error when running develop branch

### ISSUE THREAD

**Issue by h3llrais3r** [SickRage/SickRage#3146]
Error when starting up in develop branch (clean install)

Branch: develop
Commit: d0fa71619f501e233deee536f38100df8325ee41
Version: v2017.02.12-2
Database Version: 44.0

Logs:
```
2017-02-14 19:33:16 Thread-30 :: [d0fa716] Failed doing webui callback: Traceback (most recent call last):
File "C:/Tools/GitHub/SickRage\sickbeard\webserve.py", line 273, in async_call
result = function(**kwargs)
File "C:/Tools/GitHub/SickRage\sickbeard\webserve.py", line 609, in set_site_message
if sickbeard.BRANCH and sickbeard.BRANCH != 'master' and not sickbeard.DEVELOPER and self.rh.get_current_user():
AttributeError: 'UI' object has no attribute 'rh'
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
