### ISSUE TITLE
Manual Episode Search Does Not Find Episode on First Try When Show is Scene Numbered

### ISSUE THREAD

**Issue by aeozyalcin** [SickRage/SickRage#3152]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
Branch: master 
Commit: 5ba0a5263267c8f7fc568325de523ef869dccf7f 
Version: v2017.02.12-2 
Database Version: 44.0 

OS: Linux-4.4.27-7-osmc-armv7l-with-debian-8.7 
What you did: Manual search for an episode of a show with Scene Numbering
What happened: First time manual search was executed, Sickrage was unable to find and download the correct torrent file for the episode of a Scene Numbered show. Second time I hit the manual search button, it finds the episode almost instantly because it seems to search through cached search results from Torrent providers, rather than fetching a new set of results from the providers. 
What you expected: Episode should have been located & downloaded on first try.
Logs:
```
PASTE LOGS HERE
2017-02-14 19:25:25 DEBUG SEARCHQUEUE-MANUAL-259393 :: Transaction with 1 queries executed
2017-02-14 19:25:25 DEBUG SEARCHQUEUE-MANUAL-259393 :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> Fast N' Loud - 10x05 - Buggin' Out - 720p HDTV
2017-02-14 19:25:25 DEBUG SEARCHQUEUE-MANUAL-259393 :: Checking if we should stop searching for a better quality for for episode Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv]
2017-02-14 19:25:24 DEBUG SEARCHQUEUE-MANUAL-259393 :: Calling DelugeD Client
2017-02-14 19:25:24 INFO SEARCHQUEUE-MANUAL-259393 :: Downloading Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv] from ExtraTorrent
2017-02-14 19:25:24 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Checking if we should keep searching after we've found Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv]
2017-02-14 19:25:24 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Picked Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv] as the best
2017-02-14 19:25:24 INFO SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Quality of Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv] is 720p HDTV
2017-02-14 19:25:24 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Picking the best result out of [u'Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv]']
2017-02-14 19:25:24 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: The highest quality of any match is 720p HDTV
2017-02-14 19:25:24 INFO SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Found result Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv] at magnet:?xt=urn:btih:25204fbb40170f5c6fab9c5856f6aafc0a1a48bf&dn=Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv]&tr=udp://open.demonii.com:1337&tr=udp://9.rarbg.me:2710/announce&tr=udp://9.rarbg.to:2710/announce&tr=udp://coppersurfer.tk:6969/announce&tr=udp://exodus.desync.com:6969&tr=udp://tracker.openbittorrent.com:80/announce&tr=udp://glotorrents.pw:6969/announce
2017-02-14 19:25:24 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Existing episode status is 'Wanted', getting found result for Fast N' Loud S10E05 with quality 720p HDTV
2017-02-14 19:25:24 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Any,Best = [ SDTV, SD DVD, 720p HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL ] [ SDTV, SD DVD ] Found = [ 720p HDTV ]
2017-02-14 19:25:24 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Using cached parse result for: Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv]
2017-02-14 19:25:24 INFO SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Performing episode search for Fast N' Loud
2017-02-14 19:25:24 DEBUG SEARCHQUEUE-MANUAL-259393 :: [LimeTorrents] :: Last update was too soon, using old cache: 2017-02-14 19:19:33. Updated less then 10 minutes ago
2017-02-14 19:25:24 DEBUG SEARCHQUEUE-MANUAL-259393 :: [TorrentProject] :: Last update was too soon, using old cache: 2017-02-14 19:19:31. Updated less then 10 minutes ago
2017-02-14 19:25:24 DEBUG SEARCHQUEUE-MANUAL-259393 :: [Torrentz] :: Last update was too soon, using old cache: 2017-02-14 19:19:25. Updated less then 15 minutes ago
2017-02-14 19:25:24 DEBUG SEARCHQUEUE-MANUAL-259393 :: [Rarbg] :: Last update was too soon, using old cache: 2017-02-14 19:18:48. Updated less then 10 minutes ago
2017-02-14 19:25:24 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ThePirateBay] :: Last update was too soon, using old cache: 2017-02-14 19:18:39. Updated less then 30 minutes ago
2017-02-14 19:25:24 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Last update was too soon, using old cache: 2017-02-14 19:03:37. Updated less then 30 minutes ago
2017-02-14 19:25:24 INFO SEARCHQUEUE-MANUAL-259393 :: Beginning manual search for: [Fast N' Loud - S10E05 - Buggin' Out]
2017-02-14 19:25:24 DEBUG SEARCHQUEUE-MANUAL-259393 :: formatting pattern: %SN - S%0SE%0E - %EN -> Fast N' Loud - S10E05 - Buggin' Out
2017-02-14 19:25:08 INFO SEARCHQUEUE-MANUAL-259393 :: Unable to find a download for: [Fast N' Loud - S10E05 - Buggin' Out]
2017-02-14 19:25:08 DEBUG SEARCHQUEUE-MANUAL-259393 :: formatting pattern: %SN - S%0SE%0E - %EN -> Fast N' Loud - S10E05 - Buggin' Out
2017-02-14 19:25:08 DEBUG SEARCHQUEUE-MANUAL-259393 :: formatting pattern: %SN - S%0SE%0E - %EN -> Fast N' Loud - S10E05 - Buggin' Out
2017-02-14 19:25:08 DEBUG SEARCHQUEUE-MANUAL-259393 :: [LimeTorrents] :: No data returned from provider
2017-02-14 19:25:08 DEBUG SEARCHQUEUE-MANUAL-259393 :: [LimeTorrents] :: GET URL: https://www.limetorrents.cc/searchrss/20/Fast%20N'%20Loud%20S07E12/ [Status: 200]
2017-02-14 19:25:07 DEBUG SEARCHQUEUE-MANUAL-259393 :: [LimeTorrents] :: GET URL: http://www.limetorrents.cc/searchrss/20/Fast%20N'%20Loud%20S07E12/ [Status: 301]
2017-02-14 19:25:07 DEBUG SEARCHQUEUE-MANUAL-259393 :: [LimeTorrents] :: GET URL: https://www.limetorrents.cc/searchrss/20/Fast%20N'%20Loud%20S07E12 [Status: 301]
2017-02-14 19:25:06 DEBUG SEARCHQUEUE-MANUAL-259393 :: [LimeTorrents] :: Search string: Fast N' Loud S07E12
2017-02-14 19:25:06 DEBUG SEARCHQUEUE-MANUAL-259393 :: [LimeTorrents] :: Search Mode: Episode
2017-02-14 19:25:06 INFO SEARCHQUEUE-MANUAL-259393 :: [LimeTorrents] :: Performing episode search for Fast N' Loud
2017-02-14 19:25:06 DEBUG SEARCHQUEUE-MANUAL-259393 :: [TorrentProject] :: Data returned from provider does not contain any torrents
AA 
AA AttributeError: 'NoneType' object has no attribute 'group'
AA raise requests_exception
AA File "/opt/sickrage/sickbeard/helpers.py", line 1433, in handle_requests_exception
2017-02-14 19:25:06 DEBUG SEARCHQUEUE-MANUAL-259393 :: [TorrentProject] :: Traceback (most recent call last):
AA AttributeError: 'NoneType' object has no attribute 'group'
AA raise requests_exception
AA File "/opt/sickrage/sickbeard/helpers.py", line 1433, in handle_requests_exception
AA Traceback (most recent call last):
2017-02-14 19:25:06 ERROR SEARCHQUEUE-MANUAL-259393 :: [TorrentProject] :: [5ba0a52] Request failed: 'NoneType' object has no attribute 'group'
2017-02-14 19:25:00 DEBUG SEARCHQUEUE-MANUAL-259393 :: [TorrentProject] :: Search string: Fast N' Loud S07E12
2017-02-14 19:25:00 DEBUG SEARCHQUEUE-MANUAL-259393 :: [TorrentProject] :: Search Mode: Episode
2017-02-14 19:25:00 INFO SEARCHQUEUE-MANUAL-259393 :: [TorrentProject] :: Performing episode search for Fast N' Loud
2017-02-14 19:25:00 DEBUG SEARCHQUEUE-MANUAL-259393 :: [Torrentz] :: Transaction with 1 queries executed
2017-02-14 19:25:00 DEBUG SEARCHQUEUE-MANUAL-259393 :: [Torrentz] :: Unable to match www.Torrenting.com.-.Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HEVC.x265-MeGusta to a show in your database. Parser result: www Torrenting com - Fast N Loud - S07E12 [GROUP: MeGusta] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2017-02-14 19:25:00 DEBUG SEARCHQUEUE-MANUAL-259393 :: [Torrentz] :: Added RSS item: [Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv]] to cache: [torrentz]
2017-02-14 19:25:00 DEBUG SEARCHQUEUE-MANUAL-259393 :: [Torrentz] :: Adding item from search to cache: Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv]
2017-02-14 19:25:00 DEBUG SEARCHQUEUE-MANUAL-259393 :: [Torrentz] :: The result Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv] doesn't seem to match an episode that we are currently trying to snatch, skipping it
2017-02-14 19:25:00 DEBUG SEARCHQUEUE-MANUAL-259393 :: [Torrentz] :: Using cached parse result for: Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv]
2017-02-14 19:25:00 DEBUG SEARCHQUEUE-MANUAL-259393 :: [Torrentz] :: GET URL: https://torrentz2.eu/feed?f=Fast+N%27+Loud+S07E12 [Status: 200]
2017-02-14 19:24:59 DEBUG SEARCHQUEUE-MANUAL-259393 :: [Torrentz] :: Search string: Fast N' Loud S07E12
2017-02-14 19:24:59 DEBUG SEARCHQUEUE-MANUAL-259393 :: [Torrentz] :: Search Mode: Episode
2017-02-14 19:24:59 INFO SEARCHQUEUE-MANUAL-259393 :: [Torrentz] :: Performing episode search for Fast N' Loud
2017-02-14 19:24:59 INFO SEARCHQUEUE-MANUAL-259393 :: [Rarbg] :: Cant find search_tvdb in database. Are you sure it exists?
2017-02-14 19:24:59 DEBUG SEARCHQUEUE-MANUAL-259393 :: [Rarbg] :: GET URL: http://torrentapi.org/pubapi_v2.php?sort=seeders&min_leechers=0&min_seeders=1&search_tvdb=259393&app_id=sickrage2&search_string=Fast+N%27+Loud+S07E12&ranked=1&category=tv&format=json_extended&token=2dqwae431l&limit=100&mode=search [Status: 200]
2017-02-14 19:24:57 DEBUG SEARCHQUEUE-MANUAL-259393 :: [Rarbg] :: Search string: Fast N' Loud S07E12
2017-02-14 19:24:57 DEBUG SEARCHQUEUE-MANUAL-259393 :: [Rarbg] :: Search Mode: Episode
2017-02-14 19:24:56 INFO SEARCHQUEUE-MANUAL-259393 :: [Rarbg] :: Performing episode search for Fast N' Loud
2017-02-14 19:24:56 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ThePirateBay] :: Data returned from provider does not contain any torrents
2017-02-14 19:24:56 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ThePirateBay] :: GET URL: https://thepiratebay.org/search/Fast%20N'%20Loud%20S07E12/0/7/200/ [Status: 200]
2017-02-14 19:24:55 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ThePirateBay] :: GET URL: https://thepiratebay.se/search/Fast%20N'%20Loud%20S07E12/0/7/200/ [Status: 301]
2017-02-14 19:24:55 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ThePirateBay] :: Search string: Fast N' Loud S07E12
2017-02-14 19:24:55 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ThePirateBay] :: Search Mode: Episode
2017-02-14 19:24:55 INFO SEARCHQUEUE-MANUAL-259393 :: [ThePirateBay] :: Performing episode search for Fast N' Loud
2017-02-14 19:24:55 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Transaction with 1 queries executed
2017-02-14 19:24:55 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Added RSS item: [Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv]] to cache: [extratorrent]
2017-02-14 19:24:55 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Adding item from search to cache: Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv]
2017-02-14 19:24:55 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: The result Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv] doesn't seem to match an episode that we are currently trying to snatch, skipping it
2017-02-14 19:24:55 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Parsed Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv] into Fast N Loud - S10E05 [GROUP: DHD[ettv]] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2017-02-14 19:24:55 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Converted parsed result Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv] into Fast N Loud - S10E05 [GROUP: DHD[ettv]] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2017-02-14 19:24:55 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Found result: Fast.N.Loud.S07E12.Buggin.Out.iNTERNAL.720p.HDTV.x264-DHD[ettv] with 5984 seeders and 1917 leechers
2017-02-14 19:24:55 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: GET URL: http://extratorrent.cc/rss.xml?search=Fast+N%27+Loud+S07E12&type=search&cid=8 [Status: 200]
2017-02-14 19:24:54 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Search string: Fast N' Loud S07E12
2017-02-14 19:24:54 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Search Mode: Episode
2017-02-14 19:24:54 INFO SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Performing episode search for Fast N' Loud
2017-02-14 19:24:54 DEBUG SEARCHQUEUE-MANUAL-259393 :: [LimeTorrents] :: Last update was too soon, using old cache: 2017-02-14 19:19:33. Updated less then 10 minutes ago
2017-02-14 19:24:54 DEBUG SEARCHQUEUE-MANUAL-259393 :: [TorrentProject] :: Last update was too soon, using old cache: 2017-02-14 19:19:31. Updated less then 10 minutes ago
2017-02-14 19:24:54 DEBUG SEARCHQUEUE-MANUAL-259393 :: [Torrentz] :: Last update was too soon, using old cache: 2017-02-14 19:19:25. Updated less then 15 minutes ago
2017-02-14 19:24:54 DEBUG SEARCHQUEUE-MANUAL-259393 :: [Rarbg] :: Last update was too soon, using old cache: 2017-02-14 19:18:48. Updated less then 10 minutes ago
2017-02-14 19:24:54 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ThePirateBay] :: Last update was too soon, using old cache: 2017-02-14 19:18:39. Updated less then 30 minutes ago
2017-02-14 19:24:54 DEBUG SEARCHQUEUE-MANUAL-259393 :: [ExtraTorrent] :: Last update was too soon, using old cache: 2017-02-14 19:03:37. Updated less then 30 minutes ago
2017-02-14 19:24:54 INFO SEARCHQUEUE-MANUAL-259393 :: Beginning manual search for: [Fast N' Loud - S10E05 - Buggin' Out]
2017-02-14 19:24:54 DEBUG SEARCHQUEUE-MANUAL-259393 :: formatting pattern: %SN - S%0SE%0E - %EN -> Fast N' Loud - S10E05 - Buggin' Out

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
