### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/config/cache/mako/tmpli02QU'

### ISSUE THREAD

**Issue by fatgeek** [SickRage/SickRage#3160]
### INFO
Python Version: **2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]**
Operating System: **Linux-4.9.8-unRAID-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@d95ec824201c32be3e22dd3e64c8c3a7e3fe2c63
No Log available with ERRORS:
### ERROR
```
Thread-33 :: [d95ec82] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 4951, in index
    t = PageTemplate(rh=self, filename="config_notifications.mako")
  File "/app/sickrage/sickbeard/webserve.py", line 116, in __init__
    self.template = lookup.get_template(filename)
  File "/app/sickrage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/app/sickrage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/app/sickrage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/app/sickrage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/app/sickrage/lib/mako/template.py", line 703, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "/usr/lib/python2.7/tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/config/cache/mako/tmpli02QU'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

--EDIT--

This happens when I click Settings > Notifications:

Error

[Errno 2] No such file or directory: '/config/cache/mako/tmpbOvbzy'

Traceback

Traceback (most recent call last): 
File "/app/sickrage/lib/tornado/web.py", line 1469, in _execute result = yield result 
File "/app/sickrage/lib/tornado/gen.py", line 1015, in run value = future.result() 
File "/app/sickrage/lib/tornado/concurrent.py", line 237, in result raise_exc_info(self._exc_info) 
File "/app/sickrage/lib/tornado/gen.py", line 1021, in run yielded = self.gen.throw(*exc_info) 
File "/app/sickrage/sickbeard/webserve.py", line 257, in get results = yield self.async_call(method) 
File "/app/sickrage/lib/tornado/gen.py", line 1015, in run value = future.result() 
File "/app/sickrage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/app/sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/app/sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/app/sickrage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/app/sickrage/sickbeard/webserve.py", line 273, in async_call result = function(**kwargs) 
File "/app/sickrage/sickbeard/webserve.py", line 4951, in index t = PageTemplate(rh=self, filename="config_notifications.mako") 
File "/app/sickrage/sickbeard/webserve.py", line 116, in __init__ self.template = lookup.get_template(filename) 
File "/app/sickrage/lib/mako/lookup.py", line 256, in get_template return self._load(srcfile, uri) 
File "/app/sickrage/lib/mako/lookup.py", line 321, in _load **self.template_args) 
File "/app/sickrage/lib/mako/template.py", line 322, in __init__ module = self._compile_from_file(path, filename) 
File "/app/sickrage/lib/mako/template.py", line 378, in _compile_from_file self.module_writer) 
File "/app/sickrage/lib/mako/template.py", line 703, in _compile_module_file (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath)) 
File "/usr/lib/python2.7/tempfile.py", line 314, in mkstemp return _mkstemp_inner(dir, prefix, suffix, flags) 
File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner fd = _os.open(file, flags, 0600) 
OSError: [Errno 2] No such file or directory: '/config/cache/mako/tmpbOvbzy' 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /config/notifications/
query_arguments: {}
_start_time: 1487272902.88
headers: Accept-Language: en-US,en;q=0.8 Accept-Encoding: gzip, deflate, sdch Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 Host: tower:8081 Referer: http://tower:8081/errorlogs/ Cookie: snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_box_office_view=thumb; imdb_top_250_movies_view=thumb; login_cookie=223865be114884d2b38d488bc1d43c5284d40927; login_salt=181 Upgrade-Insecure-Requests: 1 
host: tower:8081
version: HTTP/1.1
arguments: {}
_finish_time: None
query: 
path: /config/notifications/
method: GET
remote_ip: 10.10.20.104

View Log(Errors)

Sickrage is running on unRAID via the linuxserver.io docker image. Browser is Chrome 56.0.2924.87 (64-bit)

--EDIT2--

Seems to have resolved after restarting Sickrage.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
