### ISSUE TITLE
unrar to temporary folder

### ISSUE THREAD

**Issue by bleedinge** [SickRage/SickRage#3195]
Branch/Commit: master
OS: Ubuntu

My post processing dir (where my download client puts the downloads) is read-only, so only the Copy action makes sense. Some folders hold rar files, and since the rar files are expanded in their original location, unrar will fail as shown in the log:

```
AA No such file or directory
AA Cannot create /mnt/remoto/mirror/tv/Man.with.a.Plan.S01E14.720p.HDTV.X264-DIMENSION/man.with.a.plan.114.720p-dimension/Man.with.a.Plan.S01E14.720p.HDTV.X264-DIMENSION.mkv
AA RarNoFilesError: No files that match pattern were found [10]: 
AA raise exc(msg)
AA File "/home/sickrage/SickRage/lib/rarfile/__init__.py", line 2868, in check_returncode
AA check_returncode(p, output)
AA File "/home/sickrage/SickRage/lib/rarfile/__init__.py", line 887, in _extract
AA self._extract(fnlist, path, pwd)
AA File "/home/sickrage/SickRage/lib/rarfile/__init__.py", line 820, in extractall
AA rar_handle.extractall(path=rar_extract_path)
AA File "/home/sickrage/SickRage/sickbeard/processTV.py", line 371, in unrar
AA Traceback (most recent call last):
2017-02-22 02:02:52 ERROR POSTPROCESSOR-AUTO :: [59ce825] Failed to extract the archive man.with.a.plan.114.720p-dimension.rar: Invalid Rar Archive Usage
```

Would it be possible to have a setting to define a temporary R/W folder where unrar should take place?

Thanks for such an awesome tool!

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by snigel** [comment]
I created a feature request for this a while ago:
http://feathub.com/SickRage/SickRage/+546

Having a different location would also improve performance for network mounts, since it will be one network transfer instead of three. Read rar, write content, copy content.

**Comment by miigotu** [comment]
@sharkykh has added this to develop branch, it should be merged into master this weekend if all goes well.
