### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/294196/en.xml

### ISSUE THREAD

**Issue by consenti** [SickRage/SickRage#3196]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@59ce8253f9f43c2297ea4e558373d46c6e2b185b
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [59ce825] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2830, in addShowByID
    show_name = get_showname_from_indexer(1, indexer_id)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1730, in get_showname_from_indexer
    s = t[int(indexer_id)]
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 946, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 841, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 629, in _getetsrc
    raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/294196/en.xml

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment]
TheTVDB.com is down for maintenance and will be back soon.
See http://thetvdb.com
