### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/media/USB/downloads/series/Stan.Lees.Lucky.Man.S02E01.HDTV.x264-MTB[rarbg]/stan.lees.lucky.man.s02e01.hdtv.x264-mtb.nfo'

### ISSUE THREAD

**Issue by devenashani** [SickRage/SickRage#3216]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.9.11-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@945a6a19e810f8b91b8c4a54a6cfa7acb20af97f
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [945a6a1] Unable to move file /media/USB/downloads/series/Stan.Lees.Lucky.Man.S02E01.HDTV.x264-MTB[rarbg]/stan.lees.lucky.man.s02e01.hdtv.x264-mtb.nfo to /media/MEDIASERVER/Videos/TV Shows/Stan Lee's Lucky Man/Season 02/Stan Lee's Lucky Man - S02E01 - Episode 1.nfo-orig: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by DrDrewZA** [comment]
Yeah - second for this issue - I am experiencing it as well.  Started in the last 24 hours or so - perhaps from an update.

Symptoms are that post processor fails after claiming that there is no such file or directory to move.  However, the file HAS ALREADY been moved and is in the right place.  All I have had to do is do a rescan in Plex and the file is imported and ready for viewing.

**Comment by sharkykh** [comment]
Some fixes were implemented into develop branchm. You can attempt to switch to it or wait for it to be merged today or tomorrow.

**Comment by sharkykh** [comment]
@devenashani @DrDrewZA 
Are you still having the issue on the latest version?
NFO files get moved with no issues?

**Comment by DrDrewZA** [comment]
I noticed my previous post was throwing the error on a .txt file - it is also still doing it with .nfo files as well, as you can see from this log excerpt:

2017-02-26 22:00:22 INFO POSTPROCESSOR-AUTO :: Auto post processing task for C:\Downloads\Sickrage completed 
2017-02-26 22:00:22 INFO POSTPROCESSOR-AUTO :: C:\Downloads\Sickrage\Jimmy.Fallon.2017.02.23.Susan.Sarandon.HDTV.x264-SORNY.mkv : Processing failed: Unable to move the files to their new home 
2017-02-26 22:00:22 INFO POSTPROCESSOR-AUTO :: Some items were not processed. 
2017-02-26 22:00:22 WARNING POSTPROCESSOR-AUTO :: Processing Failed 
2017-02-26 22:00:22 WARNING POSTPROCESSOR-AUTO :: Processing failed for C:\Downloads\Sickrage\Jimmy.Fallon.2017.02.23.Susan.Sarandon.HDTV.x264-SORNY.mkv: Unable to move the files to their new home 
AA IOError: [Errno 2] No such file or directory: u'C:\\Downloads\\Sickrage\\jimmy.fallon.2017.02.23.susan.sarandon.hdtv.x264-sorny.nfo' 
AA with open(src, 'rb') as fsrc: 
AA File "C:\SickRage\Python\lib\shutil.py", line 82, in copyfile 
AA copyfile(src, dst) 
AA File "C:\SickRage\Python\lib\shutil.py", line 130, in copy2 
AA copy2(src, real_dst) 
AA File "C:\SickRage\Python\lib\shutil.py", line 302, in move 
AA result = function(*args, **kwargs) 
AA File "C:\SickRage\SickRage\sickrage\helper\encoding.py", line 38, in ek 
AA ek(shutil.move, srcFile, destFile) 
AA File "C:\SickRage\SickRage\sickbeard\helpers.py", line 374, in moveFile 
AA helpers.moveFile(cur_file_path, new_file_path) 
AA File "C:\SickRage\SickRage\sickbeard\postProcessor.py", line 370, in _int_move 
AA Traceback (most recent call last): 
2017-02-26 22:00:22 ERROR POSTPROCESSOR-AUTO :: [8965a31] Unable to move file C:\Downloads\Sickrage\jimmy.fallon.2017.02.23.susan.sarandon.hdtv.x264-sorny.nfo to F:\Media Library\Series\The Tonight Show Starring Jimmy Fallon\Season 04\The.Tonight.Show.Starring.Jimmy.Fallon.S04E32.SDTV-SORNY.nfo-orig: error 2 : No such file or directory 
2017-02-26 22:00:13 INFO POSTPROCESSOR-AUTO :: Release name (jimmy.fallon.2017.02.23.susan.sarandon.hdtv.x264-sorny) found from file (jimmy.fallon.2017.02.23.susan.sarandon.hdtv.x264-sorny.nfo) 
2017-02-26 22:00:13 INFO POSTPROCESSOR-AUTO :: Process method is 'move' and src and destination are on the same device, skipping free space check 
2017-02-26 22:00:13 INFO POSTPROCESSOR-AUTO :: This download is marked a priority download so I'm going to replace an existing file if I find one 
2017-02-26 22:00:13 INFO POSTPROCESSOR-AUTO :: Processing C:\Downloads\Sickrage\Jimmy.Fallon.2017.02.23.Susan.Sarandon.HDTV.x264-SORNY.mkv (None) 
2017-02-26 22:00:12 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: C:\Downloads\Sickrage 
2017-02-26 22:00:12 INFO POSTPROCESSOR :: Auto post processing task for C:\Downloads\Sickrage was added to the queue

**Comment by sharkykh** [comment]
When https://github.com/SickRage/SickRage/issues/3233 will be merged to develop branch,
switch to it and see if it fixes the issue.
And please, before you start testing - enable debug in SickRage config, because I can't do much without it.

**Comment by miigotu** [comment]
Test the develop branch please!

**Comment by miigotu** [comment]
Fixed in develop
