### ISSUE TITLE
Database error after adding shows

### ISSUE THREAD

**Issue by dpedu** [SickRage/SickRage#3217]
Branch/Commit: master, 945a6a19e810f8b91b8c4a54a6cfa7acb20af97f
OS: Using docker image https://github.com/linuxserver/docker-sickrage on ubuntu trusty
What you did: Added all my shows through the ui
What happened: As the shows are scanned database errors are logged and the show isn't added. The below log starts when I pressed "Add show" in the ui, and ends when activity seemed to have stopped.
What you expected: The show successfully added.
Logs:
```
20:23:36 DEBUG::Thread-14 :: Failed to set permission for /tv/Robot Wars to 2755, parent directory has 2755
20:23:36 DEBUG::Thread-14 :: Searching for Show with searchterm(s): ['Cops'] on Indexer: theTVDB
20:23:37 INFO::SHOWQUEUE-ADD :: Starting to add show by ShowDir: /tv/Robot Wars
20:23:37 INFO::SHOWQUEUE-ADD :: theTVDB: {'useZip': True, 'apikey': 'F9C450E78D99172E', 'cache': u'/config/cache/indexers/theTVDB', 'language': 'en'}
20:23:37 INFO::SHOWQUEUE-ADD :: 71146: Unable to find the show in the database
20:23:37 DEBUG::SHOWQUEUE-ADD :: 71146: Loading show info from theTVDB
20:23:37 DEBUG::SHOWQUEUE-ADD :: Setter sets location to /tv/Robot Wars
20:23:37 INFO::SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
20:23:37 DEBUG::SHOWQUEUE-ADD :: Retrieving show info from IMDb
20:23:37 DEBUG::SHOWQUEUE-ADD :: 71146: Loading show info from IMDb
20:23:39 DEBUG::SHOWQUEUE-ADD :: 71146: Obtained info from IMDb ->{u'rating': 7.4, u'votes': 672, u'countries': u'UK', u'title': u'Robot Wars', u'genres': u'Action|Game-Show', u'imdb_id': u'tt0163488', u'country_codes': u'gb', u'year': 1998, u'certificates': u'', u'runtimes': u'45', u'akas': u'', u'last_update': 736384}
20:23:39 DEBUG::SHOWQUEUE-ADD :: 71146: Saving to database: Robot Wars
20:23:39 ERROR::SHOWQUEUE-ADD :: [945a6a1] DB error: attempt to write a readonly database
Traceback (most recent call last):
  File "/app/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/app/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: attempt to write a readonly database
20:23:39 ERROR::SHOWQUEUE-ADD :: [945a6a1] Error saving the show to the database: attempt to write a readonly database
Traceback (most recent call last):
  File "/app/sickrage/sickbeard/show_queue.py", line 459, in run
    self.show.saveToDB()
  File "/app/sickrage/sickbeard/tv.py", line 1165, in saveToDB
    main_db_con.upsert("tv_shows", newValueDict, controlValueDict)
  File "/app/sickrage/sickbeard/db.py", line 331, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/app/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/app/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: attempt to write a readonly database
20:23:39 DEBUG::SHOWQUEUE-ADD :: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/show_queue.py", line 459, in run
    self.show.saveToDB()
  File "/app/sickrage/sickbeard/tv.py", line 1165, in saveToDB
    main_db_con.upsert("tv_shows", newValueDict, controlValueDict)
  File "/app/sickrage/sickbeard/db.py", line 331, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/app/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/app/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: attempt to write a readonly database

Exception in thread SHOWQUEUE-ADD:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/app/sickrage/sickbeard/show_queue.py", line 459, in run
    self.show.saveToDB()
  File "/app/sickrage/sickbeard/tv.py", line 1165, in saveToDB
    main_db_con.upsert("tv_shows", newValueDict, controlValueDict)
  File "/app/sickrage/sickbeard/db.py", line 331, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/app/sickrage/sickbeard/db.py", line 257, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/app/sickrage/sickbeard/db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: attempt to write a readonly database

20:23:42 INFO::SHOWQUEUE-REMOVE-SHOW :: Removing Robot Wars
20:23:42 DEBUG::SHOWQUEUE-REMOVE-SHOW :: Transaction with 5 queries executed
20:23:42 INFO::SHOWQUEUE-REMOVE-SHOW :: Attempt to delete cache file /config/cache/images/71146.fanart.jpg
20:23:42 INFO::SHOWQUEUE-REMOVE-SHOW :: Attempt to delete cache file /config/cache/images/71146.poster.jpg
20:23:42 INFO::SHOWQUEUE-REMOVE-SHOW :: Attempt to delete cache file /config/cache/images/71146.banner.jpg
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment]
Seems like the issue is permissions - SickRage is saying it has readonly access.

Check that SickRage is running on a user that has write access to the required folders (SickRage data folder)

**Comment by miigotu** [comment]
Yep, SR can do a lot of things, but writing to or setting permissions on stuff it doesnt have permissions to change is not one of them.

**Comment by dpedu** [comment]
Permissions are OK - sickrage initialized the database to begin with, and was able to add some shows to it. Here's a listing:

```
root@6e64dfb5dc86:/$ ps 
PID   USER     TIME   COMMAND
    1 root       0:00 s6-svscan -t0 /var/run/s6/services
   29 root       0:00 s6-supervise s6-fdholderd
  199 root       0:00 s6-supervise sickrage
  202 abc        1:16 python /app/sickrage/SickBeard.py --datadir /config
  602 root       0:00 bash
  633 root       0:00 ps
root@6e64dfb5dc86:/$ ls -lad /config
drwxr-xr-x 4 abc users 4096 Feb 25 11:25 /config
root@6e64dfb5dc86:/$ ls -la /config
total 4652
drwxr-xr-x  4 abc  users    4096 Feb 25 11:25 .
drwxr-xr-x 24 root root     4096 Feb 24 20:22 ..
-rw-r--r--  1 root root        0 Feb 21 21:23 .datadb.lock
drwxr-xr-x  2 abc  users    4096 Feb 21 21:24 Logs
drwxr-xr-x  4 abc  users    4096 Feb 21 21:27 cache
-rw-r--r--  1 abc  users  266240 Feb 21 21:34 cache.db
-rw-r--r--  1 abc  users   24301 Feb 21 21:24 config.ini
-rw-r--r--  1 abc  users   16384 Feb 21 21:24 failed.db
-rw-r--r--  1 abc  users 4358144 Feb 21 21:41 sickbeard.db
-rw-r--r--  1 abc  users   81920 Feb 21 21:24 sickbeard.db.v43
```
