### ISSUE TITLE
SR won't start after the latest update

### ISSUE THREAD

**Issue by usegev** [SickRage/SickRage#3229]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Raspberry Pi
What you did: Updated to the latest version
What happened: After update, the service won't start
What you expected:
Logs:
```
PASTE LOGS HERE
```
When I try to start it from the command line I get the following:
>>python SickBeard.py -q --daemon --nolaunch --pidfile=/home/pi/.sickrage.pid --datadir=/opt/sickrage
Traceback (most recent call last):
  File "SickBeard.py", line 65, in <module>
    import sickbeard
  File "/opt/sickrage/sickbeard/__init__.py", line 41, in <module>
    from sickbeard.databases import mainDB, cache_db, failed_db
  File "/opt/sickrage/sickbeard/databases/mainDB.py", line 34, in <module>
    from sickbeard import subtitles
  File "/opt/sickrage/sickbeard/subtitles.py", line 29, in <module>
    import subliminal
  File "/opt/sickrage/lib/subliminal/__init__.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/opt/sickrage/lib/subliminal/core.py", line 13, in <module>
    from guessit import guessit
  File "/opt/sickrage/lib/guessit/__init__.py", line 6, in <module>
    from .api import guessit, GuessItApi
MemoryError

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by usegev** [comment]
Issue resolved after reinstalling the environment.
