### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/volume5/Downloads/103 NZB/Complete/101 Episodes/Primeval S05E02 WS PDTV XviD-BiA/Primeval.S05E02.WS.PDTV.XviD-BiA.nzb'

### ISSUE THREAD

**Issue by HPMSGEN8** [SickRage/SickRage#3230]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8965a3145b69c292e7c139ae065d5f8fa7c57dda
No Log available with ERRORS:
### ERROR
```
MANUAL :: [8965a31] Unable to move file /volume5/Downloads/103 NZB/Complete/101 Episodes/Primeval S05E02 WS PDTV XviD-BiA/Primeval.S05E02.WS.PDTV.XviD-BiA.nzb to /volume3/Episodes 3/Primeval/Season 05/Primeval S05E02 Episode 2.nzb: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment]
Hey @HPMSGEN8, please test develop branch.
We need your feedback, thanks!

**Comment by stef64** [comment]
Ho....funny !
Just happened to me, I have that behaviour sometimes but it does save it properly.
The problem in my case is my drive is in standby and need few second to spin-up.
So it does finally copy it at the next sequence (10 minutes after, my setup spin-down my disk after 30 min.)
*But you know all this already*
2017-02-27 10:06:09 INFO     POSTPROCESSOR-AUTO :: Release name (vice.s05e01.hdtv.x264-batv) found from file (vice.s05e01.hdtv.x264-batv.nfo)
2017-02-27 10:06:13 ERROR    POSTPROCESSOR-AUTO :: [8965a31] Unable to move file /home/sickrage/downloads/qbtdone/VICE.S05E01.HDTV.x264-BATV[rarbg]/vice.s05e01.hdtv.x264-batv.nfo to /media/4T/_TVShows4T/VICE/Season 05/VICE - S05E01 - Assad's Syria & Cost of Climate Change.nfo: error 2 : No such file or directory
Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/postProcessor.py", line 370, in _int_move
    helpers.moveFile(cur_file_path, new_file_path)
  File "/opt/sickrage/sickbeard/helpers.py", line 374, in moveFile
    ek(shutil.move, srcFile, destFile)
  File "/opt/sickrage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/sickrage/downloads/qbtdone/VICE.S05E01.HDTV.x264-BATV[rarbg]/vice.s05e01.hdtv.x264-batv.nfo'
2017-02-27 10:06:13 WARNING  POSTPROCESSOR-AUTO :: Processing failed for /home/sickrage/downloads/qbtdone/VICE.S05E01.HDTV.x264-BATV[rarbg]/VICE.S05E01.HDTV.x264-BATV.mkv: Unable to move the files to their new home
2017-02-27 10:06:13 WARNING  POSTPROCESSOR-AUTO :: Processing Failed
2017-02-27 10:06:13 INFO     POSTPROCESSOR-AUTO :: Some items were not processed.
2017-02-27 10:06:13 INFO     POSTPROCESSOR-AUTO :: /home/sickrage/downloads/qbtdone/VICE.S05E01.HDTV.x264-BATV[rarbg]/VICE.S05E01.HDTV.x264-BATV.mkv : Processing failed: Unable to move the files to their new home
2017-02-27 10:06:13 INFO     POSTPROCESSOR-AUTO :: Auto post processing task for /home/sickrage/downloads/qbtdone completed
2017-02-27 10:16:02 INFO     POSTPROCESSOR :: Auto post processing task for /home/sickrage/downloads/qbtdone was added to the queue
2017-02-27 10:16:07 INFO     POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/sickrage/downloads/qbtdone
2017-02-27 10:16:07 INFO     POSTPROCESSOR-AUTO :: Successfully processed

**Comment by sharkykh** [comment]
@stef64 Please switch to `develop` branch and try again, we pushed a fix to the issue. We hope it'll fix it, but we need feedback from users like you! Test on develop branch and report back, please. Thank you!

**Comment by stef64** [comment]
I would like to but, in my pull-down menu I have only master.
I found /opt/sickrage/config.ini and changed branch = develop
after I relaunched SR it came back to master...

**Comment by sharkykh** [comment]
Set your Github credentials (username and password) in SickRage General Config under Advanced Settings, save, then refresh.

You should be able to switch between master and develop, in the same config section.
Select develop and click on Checkout Branch.

### [As you can see here.](https://cloud.githubusercontent.com/assets/10238474/23356949/6d90c5a4-fce4-11e6-9470-9a48edfe8a22.jpg)

**Comment by stef64** [comment]
Yyyyyyyyyaaaaaaaaaaa.
Just for the next 10 minutes, for the test. Clear text password I don't like !
Because the product is great and I want to assist you.   :)
(there is no other way to access the develop without login?)

**Comment by miigotu** [comment]
Clear text password?  Its sent over https in a post to github, we don't see that.

**Comment by sharkykh** [comment]
@stef64 
You can do that with git, I just gave you the simplest way to switch... Easier to explain.

**Comment by stef64** [comment]
test in progresss
sudo hdparm -C /dev/sda

/dev/sda:
 drive state is : standby

I did it twice making sure hdparm doesnt wake it

clear text in config.ini I mean.

**Comment by stef64** [comment]
file downloaded, waiting for postprocessing... minus 2:20

still standby

**Comment by stef64** [comment]
@sharkykh how can I do it with git ?

**Comment by miigotu** [comment]
```bash
cd sickrage_dir
git checkout develop
git pull
```

**Comment by stef64** [comment]
drive switched to active/idle

hooo really....
didn't know that : git ...    
(just a user that to put my nose everywhere and learn)

***No error message / file as been moved properly ***
Job well done !

**Comment by stef64** [comment]
moving back to master and changing my password ;-)
1 - tough task to implement an encryption for password ? ( can also be used for my kodi password that reside in that same file)

Any more immediate test to do before I go ?

**Comment by sharkykh** [comment]
Um... there is an option for encryption... One sec

**Comment by miigotu** [comment]
Encryption in config.ini is already possible, you just have to enable it.
![image](https://cloud.githubusercontent.com/assets/390379/23369244/8a8d19ce-fcc5-11e6-8682-1577c97c57f6.png)

**Comment by miigotu** [comment]
It will be a day or 2 before the fix goes to master, GL

**Comment by HPMSGEN8** [comment]
@sharkykh sorry for the delay things been hetic. Right so there are no more errors in the logs BUT the files still sit around after it processes.

**Comment by sharkykh** [comment]
What files remain?

**Comment by HPMSGEN8** [comment]
.nfo & .srr

**Comment by sharkykh** [comment]
Then tweak your settings: move associated files or delete non associated files

**Comment by HPMSGEN8** [comment]
Move is selected with NFO and SRR and i have Delete Selected.

**Comment by sharkykh** [comment]
Can you please post any debug logs you have for that specific post-process?

**Comment by HPMSGEN8** [comment]
Sure i will find something and give it an try. It might only be this weekend or next week.

**Comment by HPMSGEN8** [comment]
Here you go.

The files where left again. 

`2017-03-04 05:54:43 DEBUG MANUAL :: Metadata provider KODI 12+ creating episode metadata for The Voice - S12E01 - Blind Auditions Premiere, Night 1
2017-03-04 05:54:43 DEBUG MANUAL :: formatting pattern: %SN - S%0SE%0E - %EN -> The Voice - S12E01 - Blind Auditions Premiere, Night 1
2017-03-04 05:54:43 DEBUG MANUAL :: Found codec for 'The Voice: Blind Auditions Premiere, Night 1'.
2017-03-04 05:54:43 DEBUG MANUAL :: Using cached parse result for: The.Voice.S12E01.HDTV.x264-2HD
2017-03-04 05:54:43 DEBUG MANUAL :: Parsed /volume1/Episodes 1/The Voice/Season 12/The Voice S12E01 Blind Auditions Premiere, Night 1 into The Voice - S12E01 [ABD: False] [ANIME: False] [whichReg: [u'standard', u'season_only']]
2017-03-04 05:54:43 DEBUG MANUAL :: Checking if /volume1/Episodes 1/The Voice/Season 12/The Voice S12E01 Blind Auditions Premiere, Night 1.nfo exists: False
2017-03-04 05:54:43 DEBUG MANUAL :: Transaction with 2 queries executed
2017-03-04 05:54:42 DEBUG MANUAL :: Setter sets location to /volume1/Episodes 1/The Voice/Season 12/The Voice S12E01 Blind Auditions Premiere, Night 1.mkv
2017-03-04 05:54:33 DEBUG MANUAL :: Moving file from /volume5/Downloads/103 NZB/Complete/101 Episodes/The Voice S12E01 HDTV x264-2HD/The.Voice.S12E01.HDTV.x264-2HD.mkv to /volume1/Episodes 1/The Voice/Season 12/The Voice S12E01 Blind Auditions Premiere, Night 1.mkv
2017-03-04 05:54:33 DEBUG MANUAL :: No associated files for /volume5/Downloads/103 NZB/Complete/101 Episodes/The Voice S12E01 HDTV x264-2HD/The.Voice.S12E01.HDTV.x264-2HD.mkv were found during this pass
2017-03-04 05:54:32 DEBUG MANUAL :: Checking if the path /volume1/Episodes 1/The Voice/Season 12 already exists
2017-03-04 05:54:32 DEBUG MANUAL :: Destination folder for this episode: /volume1/Episodes 1/The Voice/Season 12
2017-03-04 05:54:32 DEBUG MANUAL :: formatting pattern: Season %0S -> Season 12
2017-03-04 05:54:32 DEBUG MANUAL :: Found codec for 'The Voice: Blind Auditions Premiere, Night 1'.
2017-03-04 05:54:32 DEBUG MANUAL :: Using cached parse result for: The.Voice.S12E01.HDTV.x264-2HD
2017-03-04 05:54:32 DEBUG MANUAL :: Parsed /volume1/Episodes 1/The Voice/Season 12/The Voice S12E01 Blind Auditions Premiere, Night 1 into The Voice - S12E01 [ABD: False] [ANIME: False] [whichReg: [u'standard', u'season_only']]
2017-03-04 05:54:32 DEBUG MANUAL :: formatting pattern: %SN S%0SE%0E %EN -> The Voice S12E01 Blind Auditions Premiere, Night 1
2017-03-04 05:54:32 DEBUG MANUAL :: Found codec for 'The Voice: Blind Auditions Premiere, Night 1'.
2017-03-04 05:54:32 DEBUG MANUAL :: Using cached parse result for: The.Voice.S12E01.HDTV.x264-2HD
2017-03-04 05:54:32 DEBUG MANUAL :: Parsed /volume1/Episodes 1/The Voice/Season 12/The Voice S12E01 Blind Auditions Premiere, Night 1 into The Voice - S12E01 [ABD: False] [ANIME: False] [whichReg: [u'standard', u'season_only']]
2017-03-04 05:54:31 INFO MANUAL :: Using nzb_name for release name.
2017-03-04 05:54:31 DEBUG MANUAL :: Found release name The.Voice.S12E01.HDTV.x264-2HD
2017-03-04 05:54:31 INFO MANUAL :: Trying to clean any empty folders under /volume1/Episodes 1/The Voice/Season 12
2017-03-04 05:54:31 DEBUG MANUAL :: Deleting file /volume1/Episodes 1/The Voice/Season 12/The Voice S12E01 Blind Auditions Premiere, Night 1.nfo
2017-03-04 05:54:31 DEBUG MANUAL :: Deleting file /volume1/Episodes 1/The Voice/Season 12/The Voice S12E01 Blind Auditions Premiere, Night 1.mkv
2017-03-04 05:54:31 DEBUG MANUAL :: Deleting file /volume1/Episodes 1/The Voice/Season 12/The Voice S12E01 Blind Auditions Premiere, Night 1.nfo-orig
2017-03-04 05:54:31 DEBUG MANUAL :: Associated files to delete for /volume1/Episodes 1/The Voice/Season 12/The Voice S12E01 Blind Auditions Premiere, Night 1.mkv: [u'/volume1/Episodes 1/The Voice/Season 12/The Voice S12E01 Blind Auditions Premiere, Night 1.nfo-orig']
2017-03-04 05:54:31 DEBUG MANUAL :: Associated files to allow for /volume1/Episodes 1/The Voice/Season 12/The Voice S12E01 Blind Auditions Premiere, Night 1.mkv: [u'/volume1/Episodes 1/The Voice/Season 12/The Voice S12E01 Blind Auditions Premiere, Night 1.nfo']
2017-03-04 05:54:31 DEBUG MANUAL :: Found the following associated files for /volume1/Episodes 1/The Voice/Season 12/The Voice S12E01 Blind Auditions Premiere, Night 1.mkv: [u'/volume1/Episodes 1/The Voice/Season 12/The Voice S12E01 Blind Auditions Premiere, Night 1.nfo', u'/volume1/Episodes 1/The Voice/Season 12/The Voice S12E01 Blind Auditions Premiere, Night 1.nfo-orig']
2017-03-04 05:54:31 DEBUG MANUAL :: Trying to determine free space on destination drive
2017-03-04 05:54:31 DEBUG MANUAL :: File /volume1/Episodes 1/The Voice/Season 12/The Voice S12E01 Blind Auditions Premiere, Night 1.mkv is larger than /volume5/Downloads/103 NZB/Complete/101 Episodes/The Voice S12E01 HDTV x264-2HD/The.Voice.S12E01.HDTV.x264-2HD.mkv
2017-03-04 05:54:31 DEBUG MANUAL :: Is ep a priority download: False
2017-03-04 05:54:31 DEBUG MANUAL :: Quality of the episode we're processing: SDTV
2017-03-04 05:54:31 DEBUG MANUAL :: Snatch history had a quality in it, using that: SDTV
2017-03-04 05:54:31 DEBUG MANUAL :: Retrieving episode object for 12x1
2017-03-04 05:54:31 DEBUG MANUAL :: Parsed The.Voice.S12E01.HDTV.x264-2HD into The Voice - S12E01 [GROUP: 2HD] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2017-03-04 05:54:31 DEBUG MANUAL :: Analyzing name The.Voice.S12E01.HDTV.x264-2HD.nzb
2017-03-04 05:54:31 INFO MANUAL :: Processing /volume5/Downloads/103 NZB/Complete/101 Episodes/The Voice S12E01 HDTV x264-2HD/The.Voice.S12E01.HDTV.x264-2HD.mkv (The.Voice.S12E01.HDTV.x264-2HD.nzb)
2017-03-04 05:54:30 DEBUG MANUAL :: Parsed /volume5/Downloads/103 NZB/Complete/101 Episodes/The Voice S12E01 HDTV x264-2HD into The Voice - S12E01 [GROUP: 2HD] [ABD: False] [ANIME: False] [whichReg: [u'standard', u'no_season']]
2017-03-04 05:54:30 DEBUG MANUAL :: Parsed The.Voice.S12E01.HDTV.x264-2HD.mkv into The Voice - S12E01 [GROUP: 2HD] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2017-03-04 05:54:29 DEBUG MANUAL :: Processing folder /volume5/Downloads/103 NZB/Complete/101 Episodes/The Voice S12E01 HDTV x264-2HD
2017-03-04 05:54:29 INFO MANUAL :: Processing /volume5/Downloads/103 NZB/Complete/101 Episodes/The Voice S12E01 HDTV x264-2HD
2017-03-04 05:54:29 DEBUG MANUAL :: Processing in folder /volume5/Downloads/103 NZB/Complete/101 Episodes/The Voice S12E01 HDTV x264-2HD
2017-03-04 05:54:29 INFO MANUAL :: Beginning manual post processing task: /volume5/Downloads/103 NZB/Complete/101 Episodes/The Voice S12E01 HDTV x264-2HD`

**Comment by HPMSGEN8** [comment]
This is only with Auto Processing. Manual Processing is 100%

**Comment by sharkykh** [comment]
Are you sure? The log you posted is of Manual Post-Processing.

**Comment by HPMSGEN8** [comment]
This is the log from the Auto Processing that happen from sab to sickrage. i use NZBtoMedia we well. 

I will test this all tomorrow and get back to you.

**Comment by sharkykh** [comment]
NZBtoMedia doesn't use SickRages Auto Post Processing.
It invokes a the Manual Post-Processing on each downloaded episode, if I'm not mistaken.
So check NZBtoMedia's settings too.

**Comment by HPMSGEN8** [comment]
Same issues nothing changed. Am i the only one having this issue still ?

**Comment by sharkykh** [comment]
We are currently working on modifying Post-Processor (again) in #3358
Perhaps it will fix itself as we are making many changes to the code.

I would very much appreciate if you could send me a list of the files that you have in the folder before post processing starts, and after it finishes so I can test it on the #3358 branch.

**Comment by HPMSGEN8** [comment]
Sure as soon as the next one is done will send u the info.

**Comment by HPMSGEN8** [comment]
So for this one - Criminal.Minds.Beyond.Borders.S02E01.720p.HDTV.x264-AVS there was only an .mkv file and this worked 100% processed and folder deleted

**Comment by HPMSGEN8** [comment]
@sharkykh here is an better one:

**These are the files in the Folder Before Processing:**

survivor.s34e01.hdtv.x264-2hd.sfv
survivor.s34e01.hdtv.x264-2hd.srr
survivor.s34e01.hdtv.x264-2hd.mkv
survivor.s34e01.hdtv.x264-2hd.nfo
survivor.s34e01.hdtv.x264-2hd.par2

sample-survivor.s34e01.hdtv.x264-2hd.mkv
sample-survivor.s34e01.hdtv.x264-2hd.par2

**These are the files that moved as Part Of Processing:**

survivor.s34e01.hdtv.x264-2hd.mkv

**These are the files that Deleted as Part Of Processing:**

sample-survivor.s34e01.hdtv.x264-2hd.mkv
sample-survivor.s34e01.hdtv.x264-2hd.par2

survivor.s34e01.hdtv.x264-2hd.sfv
survivor.s34e01.hdtv.x264-2hd.par2

**These are the files that Left Over as Part Of Processing:**

survivor.s34e01.hdtv.x264-2hd.srr
survivor.s34e01.hdtv.x264-2hd.nfo

Hope this helps.

Thanks
