### ISSUE TITLE
File not Post Processed to many Characters?

### ISSUE THREAD

**Issue by technazz** [SickRage/SickRage#3235]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:8965a3145b69c292e7c139ae065d5f8fa7c57dda
OS:Windows-7-6.1.7601-SP1
What you did:show Snatched download. processed and then NOT updated
What happened:Show not Post processed
What you expected:Show to process
Logs:
```
2017-02-27 08:41:22 INFO POSTPROCESSOR-AUTO :: Auto post processing task for H:\Torrents\TV completed
2017-02-27 08:41:22 INFO POSTPROCESSOR-AUTO :: Successfully processed
2017-02-27 08:41:22 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: H:\Torrents\TV
2017-02-27 08:41:17 INFO POSTPROCESSOR :: Auto post processing task for H:\Torrents\TV was added to the queue
2017-02-27 08:32:15 INFO POSTPROCESSOR-AUTO :: Auto post processing task for H:\Torrents\TV completed
2017-02-27 08:32:15 INFO POSTPROCESSOR-AUTO :: H:\Torrents\TV\The.Walking.Dead.S07E11.Hostiles.And.Calamities.1080p.WEBRip.x264-HEAT\the.walking.dead.s07e11.hostiles.and.calamities.1080p.webrip.x264-heat.mkv : Processing failed: Unable to move the files to their new home
2017-02-27 08:32:15 INFO POSTPROCESSOR-AUTO :: Some items were not processed.
2017-02-27 08:32:15 WARNING POSTPROCESSOR-AUTO :: Processing Failed
2017-02-27 08:32:15 WARNING POSTPROCESSOR-AUTO :: Processing failed for H:\Torrents\TV\The.Walking.Dead.S07E11.Hostiles.And.Calamities.1080p.WEBRip.x264-HEAT\the.walking.dead.s07e11.hostiles.and.calamities.1080p.webrip.x264-heat.mkv: Unable to move the files to their new home
AA IOError: [Errno 2] No such file or directory: u'H:\\Torrents\\TV\\The.Walking.Dead.S07E11.Hostiles.And.Calamities.1080p.WEBRip.x264-HEAT\\the.walking.dead.s07e11.hostiles.and.calamities.1080p.webrip.x264-heat.nfo'
AA with open(src, 'rb') as fsrc:
AA File "C:\Python27\lib\shutil.py", line 82, in copyfile
AA copyfile(src, dst)
AA File "C:\Python27\lib\shutil.py", line 130, in copy2
AA copy2(src, real_dst)
AA File "C:\Python27\lib\shutil.py", line 302, in move
AA result = function(*args, **kwargs)
AA File "C:\SickRage\SickRage\sickrage\helper\encoding.py", line 38, in ek
AA ek(shutil.move, srcFile, destFile)
AA File "C:\SickRage\SickRage\sickbeard\helpers.py", line 374, in moveFile
AA helpers.moveFile(cur_file_path, new_file_path)
AA File "C:\SickRage\SickRage\sickbeard\postProcessor.py", line 370, in _int_move
AA Traceback (most recent call last):
2017-02-27 08:32:15 ERROR POSTPROCESSOR-AUTO :: [8965a31] Unable to move file H:\Torrents\TV\The.Walking.Dead.S07E11.Hostiles.And.Calamities.1080p.WEBRip.x264-HEAT\the.walking.dead.s07e11.hostiles.and.calamities.1080p.webrip.x264-heat.nfo to F:\Videos\Dload TV\The Walking Dead\Season 07\The.Walking.Dead.S07E11 Hostiles.and.Calamities.1080p WEB-DL.nfo-orig: error 2 : No such file or directory
2017-02-27 08:31:35 INFO POSTPROCESSOR-AUTO :: Release name (the.walking.dead.s07e11.hostiles.and.calamities.1080p.webrip.x264-heat) found from file (the.walking.dead.s07e11.hostiles.and.calamities.1080p.webrip.x264-heat.nfo)
2017-02-27 08:31:35 INFO POSTPROCESSOR-AUTO :: Process method is 'move' and src and destination are on the same device, skipping free space check
2017-02-27 08:31:35 INFO POSTPROCESSOR-AUTO :: This download is marked a priority download so I'm going to replace an existing file if I find one
2017-02-27 08:31:35 INFO POSTPROCESSOR-AUTO :: Processing H:\Torrents\TV\The.Walking.Dead.S07E11.Hostiles.And.Calamities.1080p.WEBRip.x264-HEAT\the.walking.dead.s07e11.hostiles.and.calamities.1080p.webrip.x264-heat.mkv (None)
2017-02-27 08:31:35 INFO POSTPROCESSOR-AUTO :: Deleting folder (if it's empty): H:\Torrents\TV\Last.Week.Tonight.with.John.Oliver.S04E03.720p.WEBRip.AAC2.0.H264-doosh[rarbg]
2017-02-27 08:31:35 INFO POSTPROCESSOR-AUTO :: Processing succeeded for H:\Torrents\TV\Last.Week.Tonight.with.John.Oliver.S04E03.720p.WEBRip.AAC2.0.H264-doosh[rarbg]\Last.Week.Tonight.with.John.Oliver.S04E03.720p.WEBRip.AAC2.0.H.264-doosh.mkv
AA 
AA Removing GlobalCommand@command=UpdateMediaLibrary.
AA 
AA 2017-02-27 08:31:35 (107 MB/s) - `GlobalCommand@command=UpdateMediaLibrary' saved [1811/1811]
AA 
AA 0K . 100% 107M=0s
AA 
AA Saving to: `GlobalCommand@command=UpdateMediaLibrary'
AA Length: 1811 (1.8K) [text/html]
AA HTTP request sent, awaiting response... 200 OK
AA Reusing existing connection to localhost:8080.
AA HTTP request sent, awaiting response... 401 Unauthorized
AA Connecting to localhost|127.0.0.1|:8080... connected.
AA Resolving localhost... 127.0.0.1, ::1
AA --2017-02-27 08:31:35-- http://tzz:*password*@localhost:8080/sage/GlobalCommand?command=UpdateMediaLibrary
AA syswgetrc = c:/progra~1/wget/etc/wgetrc
AA SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
AA C:\SickRage\SickRage>wget.exe --delete-after --tries=1 "http://tzz:tzz@localhost:8080/sage/GlobalCommand?command=UpdateMediaLibrary" 
2017-02-27 08:31:34 INFO POSTPROCESSOR-AUTO :: Executing command: [u'c:\\python27\\updatesage.bat', 'F:\\Videos\\Dload TV\\Last Week Tonight with John Oliver\\Season 04\\Last.Week.Tonight.with.John.Oliver.S04E03 Episode.92.720p WEB-DL.mkv', 'H:\\Torrents\\TV\\Last.Week.Tonight.with.John.Oliver.S04E03.720p.WEBRip.AAC2.0.H264-doosh[rarbg]\\Last.Week.Tonight.with.John.Oliver.S04E03.720p.WEBRip.AAC2.0.H.264-doosh.mkv', '278518', '4', '3', '2017-02-26']
2017-02-27 08:31:34 INFO POSTPROCESSOR-AUTO :: NMA: Notification sent to NotifyMyAndroid
2017-02-27 08:31:22 INFO POSTPROCESSOR-AUTO :: Process method is 'move' and src and destination are on the same device, skipping free space check
2017-02-27 08:31:22 INFO POSTPROCESSOR-AUTO :: This download is marked a priority download so I'm going to replace an existing file if I find one
2017-02-27 08:31:22 INFO POSTPROCESSOR-AUTO :: Processing H:\Torrents\TV\Last.Week.Tonight.with.John.Oliver.S04E03.720p.WEBRip.AAC2.0.H264-doosh[rarbg]\Last.Week.Tonight.with.John.Oliver.S04E03.720p.WEBRip.AAC2.0.H.264-doosh.mkv (None)
2017-02-27 08:31:22 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: H:\Torrents\TV
2017-02-27 08:31:17 INFO POSTPROCESSOR :: Auto post processing task for H:\Torrents\TV was added to the queue
2017-02-27 08:21:17 INFO POSTPROCESSOR-AUTO :: Auto post processing task for H:\Torrents\TV completed
2017-02-27 08:21:17 INFO POSTPROCESSOR-AUTO :: Successfully processed
2017-02-27 08:21:17 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: H:\Torrents\TV
2017-02-27 08:21:17 INFO POSTPROCESSOR :: Auto post processing task for H:\Torrents\TV was added to the queue
2017-02-27 08:16:51 INFO SEARCHQUEUE-DAILY-SEARCH :: NMA: Notification sent to NotifyMyAndroid
2017-02-27 08:16:51 INFO SEARCHQUEUE-DAILY-SEARCH :: Downloading Last.Week.Tonight.with.John.Oliver.S04E03.720p.WEBRip.AAC2.0.H264-doosh[rartv] from Rarbg
2017-02-27 08:16:49 INFO SEARCHQUEUE-DAILY-SEARCH :: NMA: Notification sent to NotifyMyAndroid
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: Downloading The.Walking.Dead.S07E11.Hostiles.And.Calamities.1080p.WEBRip.x264-HEAT from TorrentDay
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Quality of Last.Week.Tonight.with.John.Oliver.S04E03.720p.WEBRip.AAC2.0.H264-doosh[rartv] is 720p WEB-DL
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Quality of Last.Week.Tonight.with.John.Oliver.S04E03.720p.HDTV.x264-BFF[rartv] is 720p HDTV
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Quality of The.Walking.Dead.S07E11.Hostiles.and.Calamities.1080p.AMZN.WEBRip.DD5.1.x264-CasStudio[rartv] is 1080p WEB-DL
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Quality of The.Walking.Dead.S07E11.Hostiles.And.Calamities.1080p.WEBRip.x264-HEAT[rartv] is 1080p WEB-DL
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Quality of The.Walking.Dead.S07E11.720p.WEB-DL.DD5.1.H264-RARBG is 720p WEB-DL
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Quality of The.Walking.Dead.S07E11.1080p.WEB-DL.DD5.1.H264-RARBG is 1080p WEB-DL
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Quality of The.Walking.Dead.S07E11.720p.HDTV.x264-FLEET[rartv] is 720p HDTV
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Quality of The.Walking.Dead.S07E11.720p.HDTV.x264-AVS[rartv] is 720p HDTV
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Found result Last.Week.Tonight.with.John.Oliver.S04E03.720p.WEBRip.AAC2.0.H264-doosh[rartv] at magnet:?xt=urn:btih:a7090757a27d5a533813eecad972e119e1f78d1f&dn=Last.Week.Tonight.with.John.Oliver.S04E03.720p.WEBRip.AAC2.0.H264-doosh%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Found result Last.Week.Tonight.with.John.Oliver.S04E03.720p.HDTV.x264-BFF[rartv] at magnet:?xt=urn:btih:ec5f775970ad4d67cebd132ad3195964ea77a8fa&dn=Last.Week.Tonight.with.John.Oliver.S04E03.720p.HDTV.x264-BFF%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Found result The.Walking.Dead.S07E11.Hostiles.and.Calamities.1080p.AMZN.WEBRip.DD5.1.x264-CasStudio[rartv] at magnet:?xt=urn:btih:2585eb62d099798e1ad7e24d01a3dc982a4b110d&dn=The.Walking.Dead.S07E11.Hostiles.and.Calamities.1080p.AMZN.WEBRip.DD5.1.x264-CasStudio%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Found result The.Walking.Dead.S07E11.Hostiles.And.Calamities.1080p.WEBRip.x264-HEAT[rartv] at magnet:?xt=urn:btih:35e7215aa804fab6c88ad93cf2d6e774332716af&dn=The.Walking.Dead.S07E11.Hostiles.And.Calamities.1080p.WEBRip.x264-HEAT%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Found result The.Walking.Dead.S07E11.720p.WEB-DL.DD5.1.H264-RARBG at magnet:?xt=urn:btih:d2c4de4d97d1d3013da1cce96eb731f60bde1304&dn=The.Walking.Dead.S07E11.720p.WEB-DL.DD5.1.H264-RARBG&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Found result The.Walking.Dead.S07E11.1080p.WEB-DL.DD5.1.H264-RARBG at magnet:?xt=urn:btih:1673b41afe3327a60f9914cffa9222e121384c6e&dn=The.Walking.Dead.S07E11.1080p.WEB-DL.DD5.1.H264-RARBG&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Found result The.Walking.Dead.S07E11.720p.HDTV.x264-FLEET[rartv] at magnet:?xt=urn:btih:93b33b41d11ab707d6aa918d392bf29ea33190a2&dn=The.Walking.Dead.S07E11.720p.HDTV.x264-FLEET%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Found result The.Walking.Dead.S07E11.720p.HDTV.x264-AVS[rartv] at magnet:?xt=urn:btih:8eac9f9f5dceaf6f7bcad4947e67d962fcea585f&dn=The.Walking.Dead.S07E11.720p.HDTV.x264-AVS%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: [TorrentBytes] :: Quality of The.Walking.Dead.S07E11.Hostiles.And.Calamities.1080p.WEBRip.x264-HEAT is 1080p WEB-DL
2017-02-27 08:16:47 INFO SEARCHQUEUE-DAILY-SEARCH :: [TorrentBytes] :: Found result The.Walking.Dead.S07E11.Hostiles.And.Calamities.1080p.WEBRip.x264-HEAT at https://www.torrentbytes.net/download.php?id=1423475&SSL=1
2017-02-27 08:16:46 INFO SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: Quality of Last.Week.Tonight.with.John.Oliver.S04E03.WEBRip.x264-FUM is SDTV
2017-02-27 08:16:46 INFO SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: Quality of The.Walking.Dead.S07E11.Hostiles.And.Calamities.1080p.WEBRip.x264-HEAT is 1080p WEB-DL
2017-02-27 08:16:46 INFO SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: Quality of The.Walking.Dead.S07E11.720p.WEB-DL.H264-FUM is 720p WEB-DL
2017-02-27 08:16:46 INFO SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: Found result Last.Week.Tonight.with.John.Oliver.S04E03.WEBRip.x264-FUM at https://classic.torrentday.com/download.php/2251593/Last.Week.Tonight.with.John.Oliver.S04E03.WEBRip.x264-FUM.torrent
2017-02-27 08:16:46 INFO SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: Found result The.Walking.Dead.S07E11.Hostiles.And.Calamities.1080p.WEBRip.x264-HEAT at https://classic.torrentday.com/download.php/2251756/The.Walking.Dead.S07E11.Hostiles.And.Calamities.1080p.WEBRip.x264-HEAT.torrent
2017-02-27 08:16:46 INFO SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: Found result The.Walking.Dead.S07E11.720p.WEB-DL.H264-FUM at https://classic.torrentday.com/download.php/2251580/The.Walking.Dead.S07E11.720p.WEB-DL.H264-FUM.torrent
2017-02-27 08:16:22 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2017-02-27 08:16:17 INFO DAILYSEARCHER :: No new released episodes found ...
2017-02-27 08:16:17 INFO DAILYSEARCHER :: Searching for new released episodes ...
2017-02-27 08:11:17 INFO POSTPROCESSOR-AUTO :: Auto post processing task for H:\Torrents\TV completed
2017-02-27 08:11:17 INFO POSTPROCESSOR-AUTO :: Successfully processed
2017-02-27 08:11:17 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: H:\Torrents\TV
2017-02-27 08:11:17 INFO POSTPROCESSOR :: Auto post processing task for H:\Torrents\TV was added to the queue
2017-02-27 08:06:17 INFO CHECKVERSION :: Checking for updates using GIT
2017-02-27 08:06:17 INFO TORNADO :: Starting SickRage on http://0.0.0.0:8083/
2017-02-27 08:06:16 INFO MAIN :: Starting SickRage [master] using 'C:\SickRage\SickRage\config.ini'PASTE LOGS HERE
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment]
@technazz This is a known issue, please check before submitting as there are 5 similar issues already open, and a fix in progress. (#3233)

**Comment by miigotu** [comment]
Should be fixed in develop, please test. (ill close this issue but you can still comment here and we will see it)
