### ISSUE TITLE
[APP SUBMITTED]: no such column: e.season

### ISSUE THREAD

**Issue by Ombouwleusden** [SickRage/SickRage#3252]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ad926e47cafd7bb9b919acc0e038f56cc7aa9aa5
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [ad926e4] DB error: no such column: e.season
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Ombouwleusden** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ad926e47cafd7bb9b919acc0e038f56cc7aa9aa5
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [ad926e4] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 279, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 3246, in downloadSubtitleMissed
    [cur_indexer_id])
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 292, in select
    sql_results = self.action(query, args, fetchall=True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 262, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 113, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: no such column: e.season

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
