### ISSUE TITLE
[APP SUBMITTED]: can't compare datetime.datetime to int

### ISSUE THREAD

**Issue by CheeseySandal** [SickRage/SickRage#3254]
### INFO
Python Version: **2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-64-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ad926e47cafd7bb9b919acc0e038f56cc7aa9aa5
No Log available with ERRORS:
### ERROR
```
TORNADO :: [ad926e4] API :: can't compare datetime.datetime to int
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by CheeseySandal** [comment]
Trying to view Upcoming and Missed using NZB360 Android app. 

More from log

AA TypeError: can't compare datetime.datetime to int
AA if result[b'localtime'] < today:
AA File "/home/.sickrage/sickrage/show/ComingEpisodes.py", line 113, in get_coming_episodes
AA grouped_coming_episodes = ComingEpisodes.get_coming_episodes(self.type, self.sort, True, self.paused)
AA File "/home/.sickrage/sickbeard/webapi.py", line 705, in run
AA cur_out_dict = to_call.run() # call function and get response
AA File "/home/.sickrage/sickbeard/webapi.py", line 201, in call_dispatcher
AA out_dict = _call_dispatcher(args, kwargs)
AA File "/home/.sickrage/sickbeard/webapi.py", line 129, in get
AA Traceback (most recent call last)

**Comment by br8e** [comment]
I was just about to post this as well

Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
OS: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.7**
Locale: **en_US.UTF-8**
Branch: **master**
Commit: **ad926e47cafd7bb9b919acc0e038f56cc7aa9aa5**

2017-02-28 22:23:56 TORNADO :: [ad926e4] API :: can't compare datetime.datetime to int
Happens after latest update.

**Comment by CheeseySandal** [comment]
I'm no longer getting the error so thanks for fixing. 

However, accessing via API shows episodes airing as on the 1st of January and any missed episodes as aired 0 mins ago (even though they're days old.
