### ISSUE TITLE
Failed Processing not working

### ISSUE THREAD

**Issue by ncfitzge** [SickRage/SickRage#3257]
Error started with latest update.

Branch/Commit: Master
OS: QNAP
What you did: Failed Processing
What happened: Marked as failed but does not research
What you expected: Find a new episode
Logs:
```
2017-02-28 19:37:52 INFO     Thread-17 :: Beginning manual post processing task: 
2017-02-28 19:37:52 DEBUG    Thread-17 :: Processing folder 
2017-02-28 19:37:52 DEBUG    Thread-17 :: Processing folder 
2017-02-28 19:37:52 INFO     Thread-17 :: Failed download detected: 
2017-02-28 19:37:52 INFO     Thread-17 :: Using nzb_name for release name.
2017-02-28 19:37:52 DEBUG    Thread-17 :: Using cached parse result for: 
2017-02-28 19:37:52 DEBUG    Thread-17 :: name_parser info: 
2017-02-28 19:37:52 INFO     Thread-17 :: Deleting folder: 
2017-02-28 19:37:52 DEBUG    Thread-17 :: Deleted folder: 
2017-02-28 19:37:52 INFO     Thread-17 :: Failed Download Processing succeeded: 
2017-02-28 19:37:52 INFO     Thread-17 :: Successfully processed
2017-02-28 19:37:52 INFO     Thread-17 :: Some items were not processed.
2017-02-28 19:37:52 INFO     Thread-17 :: : Failed download
2017-02-28 19:37:52 INFO     Thread-17 :: Manual post processing task for * completed
2017-02-28 19:37:55 DEBUG    SEARCHQUEUE-RETRY-269578 :: formatting pattern: %SN - S%0SE%0E - %EN -> 
2017-02-28 19:37:55 INFO     SEARCHQUEUE-RETRY-269578 :: Marking episode as bad: 
2017-02-28 19:37:55 DEBUG    SEARCHQUEUE-RETRY-269578 :: Traceback (most recent call last):
  File "/SickBeard-TVRage/SickBeard-TVRage/sickbeard/search_queue.py", line 261, in run
    (release, provider) = failed_history.findRelease(epObj)
  File "/SickBeard-TVRage/SickBeard-TVRage/sickbeard/failed_history.py", line 239, in findRelease
    release = str(result["release"])
IndexError: Index must be int or string
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
