### ISSUE TITLE
Latest patch (1/3/2017) - issue with Schedule menu.

### ISSUE THREAD

**Issue by cp2222** [SickRage/SickRage#3263]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: FreeNAS 9.3
What you did: After installing patches from the list - a single solitary patch appears - I performed an additional update.
What happened: I found that the "Schedule" now returned an error.
What you expected: I expected the "Schedule" to give me the show schedule.
Logs:
```
Error

'NoneType' object is not iterable

Traceback

Traceback (most recent call last): 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tornado/web.py", line 1469, in _execute result = yield result 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tornado/gen.py", line 1015, in run value = future.result() 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tornado/concurrent.py", line 237, in result raise_exc_info(self._exc_info) 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tornado/gen.py", line 1021, in run yielded = self.gen.throw(*exc_info) 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 265, in get results = yield self.async_call(method) 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tornado/gen.py", line 1015, in run value = future.result() 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/concurrent/futures/_base.py", line 422, in result return self.__get_result() 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/concurrent/futures/thread.py", line 62, in run result = self.fn(*self.args, **self.kwargs) 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 281, in async_call result = function(**kwargs) 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 483, in schedule results = ComingEpisodes.get_coming_episodes(ComingEpisodes.categories, sickbeard.COMING_EPS_SORT, False) 
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickrage/show/ComingEpisodes.py", line 95, in get_coming_episodes for index, item in enumerate(results): 
TypeError: 'NoneType' object is not iterable 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /schedule/
query_arguments: {}
_start_time: 1488352253.44
headers: Accept-Language: en-US,en;q=0.8 Accept-Encoding: gzip, deflate, sdch Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8 User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 Dnt: 1 Host: 192.168.0.112:8081 Referer: http://192.168.0.112:8081/home/ Upgrade-Insecure-Requests: 1 
host: 192.168.0.112:8081
version: HTTP/1.1
arguments: {}
_finish_time: None
query: 
path: /schedule/
method: GET
remote_ip: 192.168.0.12
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
