### ISSUE TITLE
New Error log after 3/1 update

### ISSUE THREAD

**Issue by vslice24** [SickRage/SickRage#3288]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Freenas
What you did: updated to latest release
What happened: error keeps popping up in log. not sure what they mean
What you expected: no error logs
Logs:
```
2017-03-01 19:45:09 Thread-18 :: [de056c2] Failed doing webui callback: Traceback (most recent call last):
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 282, in async_call
result = function(**kwargs)
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2145, in getManualSearchStatus
episodes += getEpisodes(searchThread, searchstatus)
File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2110, in getEpisodes
'size': pretty_file_size(searchThread.segment.file_size) if searchThread.segment.file_size else ''
AttributeError: 'list' object has no attribute 'file_size'

```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
