### ISSUE TITLE
[APP SUBMITTED]: Index must be int or string

### ISSUE THREAD

**Issue by fexofenadine** [SickRage/SickRage#3293]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.102-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@26da4a8fcb8a783b5747a16e8736ba0224a5fc7e
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [NZBGeek] :: [26da4a8] Exception while searching propers in NZBGeek, skipping: Index must be int or string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DrakeJones** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@26da4a8fcb8a783b5747a16e8736ba0224a5fc7e
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [drake local] :: [26da4a8] Exception while searching propers in drake local, skipping: Index must be int or string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DrakeJones** [comment]
2017-03-02 15:32:23 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2017-03-02 15:32:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2017-03-02 15:32:18 INFO     DAILYSEARCHER :: No new released episodes found ...
2017-03-02 15:32:18 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2017-03-02 15:22:35 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2017-03-02 15:22:34 INFO     SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.org', port=443): Max retries exceeded with url: /browse/205/0/4 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))
2017-03-02 15:22:33 INFO     SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.org', port=443): Max retries exceeded with url: /browse/208/0/4 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))
2017-03-02 15:22:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2017-03-02 15:22:18 INFO     DAILYSEARCHER :: No new released episodes found ...
2017-03-02 15:22:18 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2017-03-02 15:17:22 INFO     POSTPROCESSOR-AUTO :: Auto post processing task for D:\Newsbin Staging completed
2017-03-02 15:17:22 INFO     POSTPROCESSOR-AUTO :: Successfully processed
2017-03-02 15:17:22 INFO     POSTPROCESSOR-AUTO :: Processing D:\Newsbin Staging
2017-03-02 15:17:22 INFO     POSTPROCESSOR-AUTO :: Beginning auto post processing task: D:\Newsbin Staging
2017-03-02 15:17:17 INFO     POSTPROCESSOR :: Auto post processing task for D:\Newsbin Staging was added to the queue
2017-03-02 15:12:54 INFO     FINDPROPERS :: Completed the search for new propers, next check in approx. 44m, 24s
2017-03-02 15:12:54 INFO     FINDPROPERS :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.org', port=443): Max retries exceeded with url: /search/Schitt's%20Creek%20S03E08%20PROPER%7CREPACK%7CREAL/0/7/200/ (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))
2017-03-02 15:12:53 INFO     FINDPROPERS :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.org', port=443): Max retries exceeded with url: /s/?q=24+Hours+In+A%26E+2017+02+28+PROPER%7CREPACK%7CREAL (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))
2017-03-02 15:12:52 INFO     FINDPROPERS :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.org', port=443): Max retries exceeded with url: /s/?q=24.Hours.In.A.And.E.+2017+02+28+PROPER%7CREPACK%7CREAL (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))
2017-03-02 15:12:51 INFO     FINDPROPERS :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.org', port=443): Max retries exceeded with url: /s/?q=24.hours.in.a.and.e.+2017+02+28+PROPER%7CREPACK%7CREAL (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))
2017-03-02 15:12:50 INFO     FINDPROPERS :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.org', port=443): Max retries exceeded with url: /s/?q=24+Hours+in+A%26E+2017+02+28+PROPER%7CREPACK%7CREAL (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))
2017-03-02 15:12:49 INFO     FINDPROPERS :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.org', port=443): Max retries exceeded with url: /search/24%20Hours%20In%20A%20And%20E%202017%2002%2028%20PROPER%7CREPACK%7CREAL/0/7/200/ (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))
2017-03-02 15:12:48 INFO     FINDPROPERS :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.org', port=443): Max retries exceeded with url: /search/Criminal%20Minds%20S12E15%20PROPER%7CREPACK%7CREAL/0/7/200/ (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))
2017-03-02 15:12:47 INFO     FINDPROPERS :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.org', port=443): Max retries exceeded with url: /search/Face%20Off%20S11E06%20PROPER%7CREPACK%7CREAL/0/7/200/ (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))
2017-03-02 15:12:45 INFO     FINDPROPERS :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.org', port=443): Max retries exceeded with url: /search/The%20100%20S04E05%20PROPER%7CREPACK%7CREAL/0/7/200/ (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))
2017-03-02 15:12:44 INFO     FINDPROPERS :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.org', port=443): Max retries exceeded with url: /search/The%20Detour%20S02E03%20PROPER%7CREPACK%7CREAL/0/7/200/ (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))
2017-03-02 15:12:43 INFO     FINDPROPERS :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.org', port=443): Max retries exceeded with url: /search/Suits%20S06E16%20PROPER%7CREPACK%7CREAL/0/7/200/ (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))
2017-03-02 15:12:42 INFO     FINDPROPERS :: [ThePirateBay] :: Searching for any new PROPER releases from ThePirateBay
2017-03-02 15:12:23 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2017-03-02 15:12:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2017-03-02 15:12:18 INFO     FINDPROPERS :: [Rarbg] :: Searching for any new PROPER releases from Rarbg
AA IndexError: Index must be int or string
AA return [Proper(x['name'], x['url'], datetime.fromtimestamp(x['time']), self.show) for x in results]
AA File "C:\SickRage\SickRage\sickrage\providers\GenericProvider.py", line 121, in find_propers
AA curPropers = curProvider.find_propers(search_date)
AA File "C:\SickRage\SickRage\sickbeard\properFinder.py", line 89, in _getProperList
AA IndexError: Index must be int or string
AA return [Proper(x['name'], x['url'], datetime.fromtimestamp(x['time']), self.show) for x in results]
AA File "C:\SickRage\SickRage\sickrage\providers\GenericProvider.py", line 121, in find_propers
AA curPropers = curProvider.find_propers(search_date)
AA File "C:\SickRage\SickRage\sickbeard\properFinder.py", line 89, in _getProperList
AA Traceback (most recent call last):
2017-03-02 15:12:18 ERROR    FINDPROPERS :: [drake local] :: [26da4a8] Exception while searching propers in drake local, skipping: Index must be int or string
2017-03-02 15:12:18 INFO     FINDPROPERS :: [drake local] :: Searching for any new PROPER releases from drake local
