### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/usr/local/sickbeard-custom/var/Logs/sickrage.log'

### ISSUE THREAD

**Issue by HPMSGEN8** [SickRage/SickRage#3303]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66babc76d28646807c1040a3e225072b410489ad
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [66babc7] Failed doing webui callback: Traceback (most recent call last):
  File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 281, in async_call
    result = function(**kwargs)
  File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 5334, in viewlog
    data = sickbeard.logger.log_data(min_level, log_filter, log_search, max_lines)
  File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 512, in log_data
    with io.open(_log_file, 'r', encoding='utf-8') as f:
IOError: [Errno 2] No such file or directory: '/usr/local/sickbeard-custom/var/Logs/sickrage.log'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment]
Try restarting SR

**Comment by HPMSGEN8** [comment]
### INFO
Python Version: **2.7.14 (default, Jan 15 2018, 19:15:25) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.102-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
No Log available with ERRORS:
### ERROR
```
MANUAL :: [5bc5c3a] Failed doing webui callback: Traceback (most recent call last):
  File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 280, in async_call
    result = function(**kwargs)
  File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 5398, in viewlog
    data = sickbeard.logger.log_data(min_level, log_filter, log_search, max_lines)
  File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 519, in log_data
    with io.open(_log_file, 'r', encoding='utf-8') as f:
IOError: [Errno 2] No such file or directory: '/usr/local/sickbeard-custom/var/Logs/sickrage.log'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
