### ISSUE TITLE
blackandwhitelist issue

### ISSUE THREAD

**Issue by miigotu** [SickRage/SickRage#3317]
```
17:11:35 DEBUG::SHOWQUEUE-ADD :: Building black and white list for 317953
17:11:35 ERROR::SHOWQUEUE-ADD :: [76f9874] Error trying to add show: 'int' object is not iterable
Traceback (most recent call last):
  File "/home/dusted/Projects/SickRage/sickbeard/show_queue.py", line 419, in run
    self.show.release_groups.set_white_keywords(self.whitelist)
  File "/home/dusted/Projects/SickRage/sickbeard/blackandwhitelist.py", line 76, in set_white_keywords
    self._add_keywords(b'whitelist', values)
  File "/home/dusted/Projects/SickRage/sickbeard/blackandwhitelist.py", line 55, in _add_keywords
    for value in values:
TypeError: 'int' object is not iterable
17:11:35 DEBUG::SHOWQUEUE-ADD :: Traceback (most recent call last):
  File "/home/dusted/Projects/SickRage/sickbeard/show_queue.py", line 419, in run
    self.show.release_groups.set_white_keywords(self.whitelist)
  File "/home/dusted/Projects/SickRage/sickbeard/blackandwhitelist.py", line 76, in set_white_keywords
    self._add_keywords(b'whitelist', values)
  File "/home/dusted/Projects/SickRage/sickbeard/blackandwhitelist.py", line 55, in _add_keywords
    for value in values:
TypeError: 'int' object is not iterable

Exception in thread SHOWQUEUE-ADD:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/dusted/Projects/SickRage/sickbeard/show_queue.py", line 419, in run
    self.show.release_groups.set_white_keywords(self.whitelist)
  File "/home/dusted/Projects/SickRage/sickbeard/blackandwhitelist.py", line 76, in set_white_keywords
    self._add_keywords(b'whitelist', values)
  File "/home/dusted/Projects/SickRage/sickbeard/blackandwhitelist.py", line 55, in _add_keywords
    for value in values:
TypeError: 'int' object is not iterable

17:11:40 INFO::SHOWQUEUE-REMOVE-SHOW :: Removing Marvel's Iron Fist
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
@sharkykh or @h3llrais3r didn't one of you change b/w list recently?  Can you fix it, I have no clue when it comes to this anime junk.

**Comment by sharkykh** [comment]
> I have no clue when it comes to this anime junk.
Same here lol

**Comment by sharkykh** [comment]
@miigotu How did you get this error?
I tried adding it as an anime, everything was fine...

**Comment by miigotu** [comment]
Use the `Add From Trakt List` option

**Comment by sharkykh** [comment]
Unfortunately it doesn't suggest that show to me. :angry:

**Comment by miigotu** [comment]
Seems to do it with any show from there.
```
Exception in thread SHOWQUEUE-ADD:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/dusted/Projects/SickRage/sickbeard/show_queue.py", line 417, in run
    self.show.release_groups.set_white_keywords(self.whitelist)
  File "/home/dusted/Projects/SickRage/sickbeard/blackandwhitelist.py", line 76, in set_white_keywords
    self._add_keywords(b'whitelist', values)
  File "/home/dusted/Projects/SickRage/sickbeard/blackandwhitelist.py", line 55, in _add_keywords
    for value in values:
TypeError: 'int' object is not iterable

17:28:17 INFO::SHOWQUEUE-REMOVE-SHOW :: Removing Breaking Bad
```

**Comment by sharkykh** [comment]
I'm trying with Marvel's The Inhumans and it's not going into that method because show.anime = 0
That's weird.

**Comment by sharkykh** [comment]
Found the issue,
It happens when your default show settings have anime = True
But trending shows page doesn't even have an option to change it before adding...

**Comment by miigotu** [comment]
Webserve.py L2832 Missing param subtitles_sr_metadata, so the order is wrong
All the calls to addShow should probably specify the paremeter names in the method call

**Comment by sharkykh** [comment]
On it

**Comment by h3llrais3r** [comment]
Sorry for late answer, but I didn't change anything to the black and white listing.
I see it's already fixed, but this isn't an anime series... and anime isn't junk :rofl:
