### ISSUE TITLE
[APP SUBMITTED]: 'sqlite3.Row' object does not support item assignment

### ISSUE THREAD

**Issue by Mickroz** [SickRage/SickRage#3322]
### INFO
Python Version: **2.7.13 (default, Dec 18 2016, 22:44:40) [GCC 4.9.3 20150311 (prerelease)]**
Operating System: **Linux-3.10.102-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@12e8e54a4a8d15d3f6739f9afede01129d1e7449
No Log available with ERRORS:
### ERROR
```
TORNADO :: [12e8e54] API :: 'sqlite3.Row' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Mickroz** [comment]
Branch: master
Commit: 12e8e54a4a8d15d3f6739f9afede01129d1e7449
Version: v2017.03.04-1
Database Version: 44.0
OS: Linux-3.10.102-armv7l-with-glibc2.4

Seems to be something regarding episode call, apibuilder isn't working correct either.

**Comment by miigotu** [comment]
need the exception from your log file.

**Comment by derkens** [comment]
Hi, I have the same issue, here's the exception

`2017-03-05 09:18:47 DEBUG TRAKTCHECKER :: Starting new thread: TRAKTCHECKER
AA TypeError: 'sqlite3.Row' object does not support item assignment
AA network_timezones.parse_date_time(int(episode[b'airdate']), show_obj.airs, show_obj.network)), d_preset=dateFormat)
AA File "/opt/sickrage/sickbeard/webapi.py", line 787, in run
AA cur_out_dict = to_call.run() # call function and get response
AA File "/opt/sickrage/sickbeard/webapi.py", line 201, in call_dispatcher
AA out_dict = _call_dispatcher(args, kwargs)
AA File "/opt/sickrage/sickbeard/webapi.py", line 129, in get
AA Traceback (most recent call last):
2017-03-05 09:17:43 ERROR TORNADO :: [12e8e54] API :: 'sqlite3.Row' object does not support item assignment
2017-03-05 09:17:43 DEBUG TORNADO :: API :: episode: cur_kwargs {'season': '3', 'indexerid': '75710', 'episode': '4', 'full_path': '1'}
2017-03-05 09:17:43 DEBUG TORNADO :: API :: all kwargs: '{'indexerid': '75710', 'season': '3', 'cmd': 'episode', 'episode': '4', 'full_path': '1'}'
2017-03-05 09:17:43 DEBUG TORNADO :: API :: all args: '()'
2017-03-05 09:17:43 DEBUG TORNADO :: API :: 172.19.3.10 - gave correct API KEY. ACCESS GRANTED`

**Comment by miigotu** [comment]
Working on it.

**Comment by Mickroz** [comment]
```
AA TypeError: 'sqlite3.Row' object does not support item assignment
AA network_timezones.parse_date_time(int(episode[b'airdate']), show_obj.airs, show_obj.network)), d_preset=dateFormat)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webapi.py", line 787, in run
AA cur_out_dict = to_call.run() # call function and get response
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webapi.py", line 201, in call_dispatcher
AA out_dict = _call_dispatcher(args, kwargs)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webapi.py", line 129, in get
AA Traceback (most recent call last):
2017-03-05 09:05:10 ERROR TORNADO :: [12e8e54] API :: 'sqlite3.Row' object does not support item assignment
```

**Comment by Mickroz** [comment]
Yes, works again, thank you.👍
