### ISSUE TITLE
SickRage Service fails RARCheck after AutoUpdate and wont start: FreeNAS

### ISSUE THREAD

**Issue by shitrus** [SickRage/SickRage#3350]
Branch/Commit: Master/12e8e54
OS: FreeNAS-9.10.2-U2 (e1497f2)
What you did: AutoUpdate ran at 3am, and installed new version of SickRage
What happened: The service was unable to start
What you expected: The service to start
Logs:

sickrage.log: http://pastebin.com/2EajX624

manual start from shell:
```
root@sickrage_1:/ # service sickrage start                                                                                          
Starting sickrage.                                                                                                                  
Traceback (most recent call last):                                                                                                  
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/SickBeard.py", line 492, in <module>                                        
    SickRage().start()                                                                                                              
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/SickBeard.py", line 240, in start                                          
    sickbeard.initialize(consoleLogging=self.console_logging)                                                                      
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/__init__.py", line 1028, in initialize                            
    check_setting_str(CFG, 'General', 'alt_unrar_tool', rarfile.ALT_TOOL)                                                          
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/config.py", line 140, in change_unrar_tool                        
    rarfile.custom_check(alt_unrar_tool)                                                                                            
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/rarfile/__init__.py", line 2826, in custom_check                        
    raise RarExecError("Check-run failed")                                                                                          
rarfile.RarExecError: Check-run failed                                                                                              
/usr/local/etc/rc.d/sickrage: WARNING: failed to start sickrage                                                                    
root@sickrage_1:/ #
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment]
There was an error in the commit you updated to. Please do a `git pull` in the SickRage directory then try starting it again

**Comment by shitrus** [comment]
`root@sickrage_1:/usr/pbi/sickrage-amd64/share/sickrage/SickRage # git pull                                                          
fatal: Not a git repository (or any of the parent directories): .git`

This is what happens when I try to git pull.

**Comment by sharkykh** [comment]
Ok, then I suggest you download that latest SickRage https://github.com/SickRage/SickRage/archive/master.zip
Extract the contents of SickRage-master folder (inside the zip) to `/usr/pbi/sickrage-amd64/share/sickrage/SickRage` - overwrite all files

**Comment by shitrus** [comment]
Awesome. Thanks!
