### ISSUE TITLE
Request failed: data must be a byte string, upgrade python 2.7.9 --> .13

### ISSUE THREAD

**Issue by Fitouf** [SickRage/SickRage#3372]
Hi, 
first, sorry for my bad english.
I have lot of problems since few days.

Branch/Commit: master
OS: debian
What you did: Since few days, i have "Request failed: data must be a byte string" error each times SR search news episodes. After lot of research, i decided to upgrade my python version 2.7.9 --> 2.7.13 and change the path of python in /etc/init.d/sickrage /usr/bin/python2.7 to /usr/local/bin/python2.7
What happened: after this change, when i restart the service, SR service won't start. I check my version of python and i have that : 
 - /usr/bin/python2.7 -V --> python 2.7.9
- /usr/local/bin/python2.7 -V --> python 2.7.13

Logs:
```
AA TypeError: data must be a byte string
AA raise requests_exception
AA File "/opt/sickrage/sickbeard/helpers.py", line 1479, in handle_requests_exception
AA TypeError: data must be a byte string
AA raise requests_exception
AA File "/opt/sickrage/sickbeard/helpers.py", line 1479, in handle_requests_exception
AA Traceback (most recent call last):
2017-03-10 02:14:09 ERROR SEARCHQUEUE-MANUAL-311787 :: [T411] :: [edc61ac] Request failed: data must be a byte string
AA TypeError: data must be a byte string
AA raise requests_exception
AA File "/opt/sickrage/sickbeard/helpers.py", line 1479, in handle_requests_exception
AA TypeError: data must be a byte string
AA raise requests_exception
AA File "/opt/sickrage/sickbeard/helpers.py", line 1479, in handle_requests_exception
AA Traceback (most recent call last):
2017-03-10 02:14:09 ERROR SEARCHQUEUE-MANUAL-311787 :: [T411] :: [edc61ac] Request failed: data must be a byte string
AA TypeError: data must be a byte string
AA raise requests_exception
AA File "/opt/sickrage/sickbeard/helpers.py", line 1479, in handle_requests_exception
AA TypeError: data must be a byte string
AA raise requests_exception
AA File "/opt/sickrage/sickbeard/helpers.py", line 1479, in handle_requests_exception
AA Traceback (most recent call last):
2017-03-10 02:14:09 ERROR SEARCHQUEUE-MANUAL-311787 :: [T411] :: [edc61ac] Request failed: data must be a byte string
AA TypeError: data must be a byte string
AA raise requests_exception
AA File "/opt/sickrage/sickbeard/helpers.py", line 1479, in handle_requests_exception
AA TypeError: data must be a byte string
AA raise requests_exception
AA File "/opt/sickrage/sickbeard/helpers.py", line 1479, in handle_requests_exception
AA Traceback (most recent call last):
2017-03-10 02:14:09 ERROR SEARCHQUEUE-MANUAL-311787 :: [T411] :: [edc61ac] Request failed: data must be a byte string
2017-03-10 02:14:08 INFO SEARCHQUEUE-MANUAL-311787 :: [T411] :: Performing episode search for 24: Legacy
2017-03-10 02:14:08 INFO SEARCHQUEUE-MANUAL-311787 :: Beginning manual search for: [24 Legacy - S01E06 - 500 P.M. - 600 P.M]

```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [ ] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Fitouf** [comment]
I solved my issue :)

Sorry for the distrub
