### ISSUE TITLE
[APP SUBMITTED]: character mapping must return integer, None or unicode

### ISSUE THREAD

**Issue by RobLaw0304** [SickRage/SickRage#3373]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **develop**
Commit: SickRage/SickRage@19ada9d00e82ace606eb3deabdf4ff91a5c8ea40
No Log available with ERRORS:
### ERROR
```
Thread-25 :: [19ada9d] Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\Rob\AppData\Local\SickRage\sickbeard\webserve.py", line 284, in async_call
    result = function(**kwargs)
  File "C:\Users\Rob\AppData\Local\SickRage\sickbeard\webserve.py", line 908, in twitterStep1
    return notifiers.twitter_notifier._get_authorization()  # pylint: disable=protected-access
  File "C:\Users\Rob\AppData\Local\SickRage\sickbeard\notifiers\tweet.py", line 81, in _get_authorization
    resp, content = oauth_client.request(self.REQUEST_TOKEN_URL, 'GET')
  File "C:\Users\Rob\AppData\Local\SickRage\lib\oauth2\__init__.py", line 597, in request
    req.sign_request(self.method, self.consumer, self.token)
  File "C:\Users\Rob\AppData\Local\SickRage\lib\oauth2\__init__.py", line 351, in sign_request
    self['oauth_signature'] = signature_method.sign(self, consumer, token)
  File "C:\Users\Rob\AppData\Local\SickRage\lib\oauth2\__init__.py", line 681, in sign
    hashed = hmac.new(key, raw, hashlib.sha1)
  File "C:\Python27\lib\hmac.py", line 136, in new
    return HMAC(key, msg, digestmod)
  File "C:\Python27\lib\hmac.py", line 75, in __init__
    self.outer.update(key.translate(trans_5C))
TypeError: character mapping must return integer, None or unicode

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
