### ISSUE TITLE
Exception when adding shows from trending lists

### ISSUE THREAD

**Issue by sharkykh** [SickRage/SickRage#3379]
When adding a show from trending(=Trakt) shows (popular=IMDB uses the same method),
and the show was deleted from TVDB, or the indexer ID is invalid, an exception is thrown.

Branch: trakt-images (**Shouldn't matter**)
Commit: 1697245f7a0438f4a81632f22cb0cc29aaa05d5c

Traceback
-------
```
2017-03-10 23:47:15 Thread-26 :: [1697245] Failed doing webui callback: Traceback (most recent call last):
File "C:\Github\SickRage-Dev\SickRage\sickbeard\webserve.py", line 282, in async_call
result = function(**kwargs)
File "C:\Github\SickRage-Dev\SickRage\sickbeard\webserve.py", line 2798, in addShowByID
show_name = get_showname_from_indexer(1, indexer_id)
File "C:\Github\SickRage-Dev\SickRage\sickbeard\helpers.py", line 1775, in get_showname_from_indexer
s = t[int(indexer_id)]
File "C:\Github\SickRage-Dev\SickRage\lib\tvdb_api\tvdb_api.py", line 946, in __getitem__
self._getShowData(key, self.config['language'], True)
File "C:\Github\SickRage-Dev\SickRage\lib\tvdb_api\tvdb_api.py", line 841, in _getShowData
self.config['url_seriesInfo'] % (sid, getShowInLanguage)
File "C:\Github\SickRage-Dev\SickRage\lib\tvdb_api\tvdb_api.py", line 629, in _getetsrc
raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318852/en.xml
```

AJAX Response Preview (what the call to addShowByID returns)
-----
```
Error

HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318852/en.xml

Traceback

Traceback (most recent call last): 
File "C:\Github\SickRage-Dev\SickRage\lib\tornado\web.py", line 1469, in _execute result = yield result 
File "C:\Github\SickRage-Dev\SickRage\lib\tornado\gen.py", line 1015, in run value = future.result() 
File "C:\Github\SickRage-Dev\SickRage\lib\tornado\concurrent.py", line 237, in result raise_exc_info(self._exc_info) 
File "C:\Github\SickRage-Dev\SickRage\lib\tornado\gen.py", line 1021, in run yielded = self.gen.throw(*exc_info) 
File "C:\Github\SickRage-Dev\SickRage\sickbeard\webserve.py", line 266, in get results = yield self.async_call(method) 
File "C:\Github\SickRage-Dev\SickRage\lib\tornado\gen.py", line 1015, in run value = future.result() 
File "C:\Github\SickRage-Dev\SickRage\lib\concurrent\futures\_base.py", line 422, in result return self.__get_result() 
File "C:\Github\SickRage-Dev\SickRage\lib\concurrent\futures\thread.py", line 62, in run result = self.fn(*self.args, **self.kwargs) 
File "C:\Github\SickRage-Dev\SickRage\sickbeard\webserve.py", line 282, in async_call result = function(**kwargs) 
File "C:\Github\SickRage-Dev\SickRage\sickbeard\webserve.py", line 2798, in addShowByID show_name = get_showname_from_indexer(1, indexer_id) 
File "C:\Github\SickRage-Dev\SickRage\sickbeard\helpers.py", line 1775, in get_showname_from_indexer s = t[int(indexer_id)] 
File "C:\Github\SickRage-Dev\SickRage\lib\tvdb_api\tvdb_api.py", line 946, in __getitem__ self._getShowData(key, self.config['language'], True) 
File "C:\Github\SickRage-Dev\SickRage\lib\tvdb_api\tvdb_api.py", line 841, in _getShowData self.config['url_seriesInfo'] % (sid, getShowInLanguage) 
File "C:\Github\SickRage-Dev\SickRage\lib\tvdb_api\tvdb_api.py", line 629, in _getetsrc raise tvdb_error(e) 
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318852/en.xml 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /addShows/addShowByID?indexer_id=318852&show_name=Marvel%27s+The+Punisher
query_arguments: {'indexer_id': ['318852'], 'show_name': ["Marvel's The Punisher"]}
_start_time: 1489182413.79
headers: Accept-Language: en-US,en;q=0.8,he;q=0.6 Accept-Encoding: gzip, deflate, sdch, br Connection: keep-alive Accept: */* User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 Host: localhost:8082 Referer: http://localhost:8082/addShows/trendingShows/?traktList=anticipated Cookie: Pycharm-cffa0bd7=82f462c3-4027-45fc-9b07-be53799de242 X-Requested-With: XMLHttpRequest 
host: localhost:8082
version: HTTP/1.1
arguments: {'indexer_id': '318852', 'show_name': "Marvel's The Punisher"}
_finish_time: None
query: indexer_id=318852&show_name=Marvel%27s+The+Punisher
path: /addShows/addShowByID
method: GET
remote_ip: 127.0.0.1
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
