### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/324852/en.xml

### ISSUE THREAD

**Issue by shadow11001** [SickRage/SickRage#3385]
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.7**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@edc61acc6934ac3e15568ed07c37b06233ec19a9
No Log available with ERRORS:
### ERROR
```
Thread-238 :: [edc61ac] Failed doing webui callback: Traceback (most recent call last):
  File "/media/d99e/shadow11001/.sickrage/sickbeard/webserve.py", line 281, in async_call
    result = function(**kwargs)
  File "/media/d99e/shadow11001/.sickrage/sickbeard/webserve.py", line 2828, in addShowByID
    show_name = get_showname_from_indexer(1, indexer_id)
  File "/media/d99e/shadow11001/.sickrage/sickbeard/helpers.py", line 1775, in get_showname_from_indexer
    s = t[int(indexer_id)]
  File "/media/d99e/shadow11001/.sickrage/lib/tvdb_api/tvdb_api.py", line 946, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/media/d99e/shadow11001/.sickrage/lib/tvdb_api/tvdb_api.py", line 841, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "/media/d99e/shadow11001/.sickrage/lib/tvdb_api/tvdb_api.py", line 629, in _getetsrc
    raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/324852/en.xml

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by shadow11001** [comment]
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.7**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@edc61acc6934ac3e15568ed07c37b06233ec19a9
No Log available with ERRORS:
### ERROR
```
Thread-227 :: [edc61ac] Failed doing webui callback: Traceback (most recent call last):
  File "/media/d99e/shadow11001/.sickrage/sickbeard/webserve.py", line 281, in async_call
    result = function(**kwargs)
  File "/media/d99e/shadow11001/.sickrage/sickbeard/webserve.py", line 2828, in addShowByID
    show_name = get_showname_from_indexer(1, indexer_id)
  File "/media/d99e/shadow11001/.sickrage/sickbeard/helpers.py", line 1775, in get_showname_from_indexer
    s = t[int(indexer_id)]
  File "/media/d99e/shadow11001/.sickrage/lib/tvdb_api/tvdb_api.py", line 946, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/media/d99e/shadow11001/.sickrage/lib/tvdb_api/tvdb_api.py", line 841, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "/media/d99e/shadow11001/.sickrage/lib/tvdb_api/tvdb_api.py", line 629, in _getetsrc
    raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/324852/en.xml

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sharkykh** [comment]
Same cause as #3379
