### ISSUE TITLE
A bit noobish, but suddenly this error:  ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by NorCalJason** [SickRage/SickRage#3391]
Didn't change a thing.  Then suddenly, new shows stopped downloading.  Can't get sickrage to launch.  Instead I get "ERR_CONNECTION_REFUSED"

Where do I go from here?  

Running windows 10...
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment]
Please attempt this fix: https://github.com/SickRage/SickRage/issues/3331#issuecomment-284269334
`unrar.exe` might not be in Data folder. Run a search in the SickRage installation for `unrar.exe` file and delete it.
(If it's not in your Data directory, please also say where you did find it so we can fix it for other users).

**Comment by NorCalJason** [comment]
Thank you for the response!

Unrar.exe was already in my Data folder.

Followed the instructions provided

Stop the SickRage service
Delete unrar.exe in the Data folder
Start the service

Still ERR_CONNECTION_REFUSED

Been running stable for at least a year...

**Comment by sharkykh** [comment]
Did you also do `git pull`? This is crucial.

There was a specific version of SickRage that caused this issue, yet we fixed it in a later update.

**Comment by sharkykh** [comment]
And also I would need to know the commit or version you're and, and the logs after SickRage fails to start.

**Comment by NorCalJason** [comment]
Trying to run the Git pull...  

E:\TV\Sickrage\Git\bin\git pull

Fatal:  Not a git repository (or any of the parent directories): .git

**Comment by NorCalJason** [comment]
Where would I find my version?

**Comment by sharkykh** [comment]
config.ini, find the line that starts with `cur_commit_hash`

**Comment by sharkykh** [comment]
`config.ini` file in the Data folder, find the line that starts with `cur_commit_hash`.
Logs are also in Data folder, inside the folder `Logs` -> file named `sickrage.log`. You can post it to [pastebin](http://pastebin.com)

**Comment by NorCalJason** [comment]
cur_commit_hash = 16f9f6b000528a1a2386107d26820c6841e87425

**Comment by sharkykh** [comment]
I was right, you were affected by that issue I was talking about.
Okay, to fix this do the following:

1. Make sure SickRage is not running, backup your Data folder.
2. Download [SickRage-master.zip](https://github.com/SickRage/SickRage/archive/master.zip).
3. Extract the ZIP file and move everything from the folder named `SickRage-master` (that was inside the ZIP) to your SickRage Installation (**E:\TV\Sickrage\SickRage**) and **overwrite all the files and folders.**
4. Run SickRage.

**Comment by NorCalJason** [comment]
Here's the log..  lots of processing errors before this; http://pastebin.com/WPXyjfT2

**Comment by sharkykh** [comment]
@NorCalJason Please see my latest comment.

**Comment by NorCalJason** [comment]
Still no luck.  Here's the latest log:

CHECKVERSION :: New update found for SickRage, starting auto-updater ...
2017-03-05 11:49:47 INFO     CHECKVERSION :: Config backup in progress...
2017-03-05 11:49:54 INFO     CHECKVERSION :: Config backup successful, updating...
2017-03-05 11:49:58 INFO     CHECKVERSION :: Update was successful!
2017-03-05 11:49:58 INFO     EVENT-QUEUE :: Aborting all threads
2017-03-05 11:49:58 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2017-03-05 11:49:58 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2017-03-05 11:49:58 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2017-03-05 11:49:58 INFO     EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2017-03-05 11:49:59 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE-REFRESH thread to exit
2017-03-05 11:49:59 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE-DAILY-SEARCH thread to exit
2017-03-05 11:49:59 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2017-03-05 11:49:59 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR-AUTO thread to exit
2017-03-05 11:49:59 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2017-03-05 11:49:59 INFO     EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2017-03-05 11:49:59 INFO     EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2017-03-05 11:49:59 INFO     EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2017-03-05 11:49:59 INFO     EVENT-QUEUE :: Saving all shows to the database
2017-03-05 11:50:02 INFO     EVENT-QUEUE :: Saving config file to disk
2017-03-05 11:50:02 INFO     EVENT-QUEUE :: Shutting down Tornado
2017-03-05 11:50:02 INFO     EVENT-QUEUE :: Restarting SickRage with ['E:\\TV\\SickRage\\Python\\python.exe', u'E:\\TV\\SickRage\\SickRage\\SickBeard.py', '--nolaunch', '--port=8081', '--datadir=E:\\TV\\SickRage\\Data']
2017-03-05 11:50:28 INFO     MAIN :: Unrar not found at the path specified. Trying to download unrar and set the path
2017-03-13 21:33:07 INFO     MAIN :: Unrar not found at the path specified. Trying to download unrar and set the path
2017-03-13 22:04:54 INFO     MAIN :: Unrar not found at the path specified. Trying to download unrar and set the path

**Comment by NorCalJason** [comment]
But I do see the Unrar in Data Folder...

**Comment by sharkykh** [comment]
Then I don't think that you the files correctly.
Try removing `E:\TV\SickRage\SickRage` folder
then unpack the `SickRage-master.zip` to `E:\TV\SickRage\` (should create `E:\TV\SickRage\SickRage-master`) and rename the new folder to SickRage.

Also try running from command line:
(instead of running the service. after the issue is fixed you can run it as service again)
```
E:\TV\SickRage\Python\python.exe E:\TV\SickRage\SickRage\SickBeard.py --port=8081 --datadir=E:\TV\SickRage\Data
```

**Comment by NorCalJason** [comment]
Deleted Sickrage folder

Extracted Sickrage-master to directory E:\TV\Sickrage folder.  

Renamed Sickrage-master to Sickrage

Restarted service, says "paused"

**Comment by sharkykh** [comment]
As I said, try running from command line please.
Running as service won't help you solve the issue.

Also. What is the contents of E:\TV\Sickrage\SickRage now?

**Comment by NorCalJason** [comment]
Ran the command line.  Here's what I got:

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>E:\TV\SickRage\Python\python.exe E:\TV\SickRage\SickRage\SickBeard.py --port=8081 --datadir=E:\TV\SickRage\Data
Traceback (most recent call last):
  File "E:\TV\SickRage\SickRage\SickBeard.py", line 492, in <module>
    SickRage().start()
  File "E:\TV\SickRage\SickRage\SickBeard.py", line 240, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "E:\TV\SickRage\SickRage\sickbeard\__init__.py", line 1030, in initialize
    check_setting_str(CFG, 'General', 'alt_unrar_tool', rarfile.ALT_TOOL)
  File "E:\TV\SickRage\SickRage\sickbeard\config.py", line 114, in change_unrar_tool
    os.remove(bad_unrar)
WindowsError: [Error 5] Access is denied: u'E:\\TV\\SickRage\\Data\\unrar.exe'

C:\WINDOWS\system32>

**Comment by NorCalJason** [comment]
Contents of E:\TV\Sickrage\Sickrage

.github folder
.contrib folder
gui folder
lib folder
locale folder
patches folder

etc

**Comment by NorCalJason** [comment]
Would it be easier to backup the settings, uninstall, reinstall, restore?

**Comment by sharkykh** [comment]
Ok,
that's better.

>Would it be easier to backup the settings, uninstall, reinstall, restore?

You could, but I already know what the issue is, so there's no need for that.

For some reason there is no permissions to delete the unrar.
Try deleting `E:\TV\SickRage\Data\unrar.exe` yourself (again)
And run using command line again.

**Comment by NorCalJason** [comment]
That seemed to do it.  Thanks!  

Should I update to latest version?

**Comment by sharkykh** [comment]
By downloading and extracting the zip I gave you,
you're supposed to be on the latest version right now.
You can verify that by clicking Check for Updates in SickRage.


You can now shutdown SickRage, then run it as a service again as usual.

**Comment by NorCalJason** [comment]
Yep!  thank you!
