### ISSUE TITLE
[APP SUBMITTED]: showPoster() got an unexpected keyword argument ' Mr Norrell'

### ISSUE THREAD

**Issue by miiichael** [SickRage/SickRage#3394]
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-4.1.0-1-amd64-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@826b084110bdef33f9a519686286a5d6f02e1bcc
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [826b084] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 284, in async_call
    result = function(**kwargs)
TypeError: showPoster() got an unexpected keyword argument ' Mr Norrell'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miiichael** [comment]
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-4.1.0-1-amd64-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@826b084110bdef33f9a519686286a5d6f02e1bcc
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [826b084] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 284, in async_call
    result = function(**kwargs)
TypeError: showPoster() got an unexpected keyword argument ' Mr Norrell'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miiichael** [comment]
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-4.1.0-1-amd64-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@826b084110bdef33f9a519686286a5d6f02e1bcc
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [826b084] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 284, in async_call
    result = function(**kwargs)
TypeError: showPoster() got an unexpected keyword argument ' Mr Norrell'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miiichael** [comment]
This appears to only happen for TV shows with ampersands in the title, and before Sickrage has had a chance to fetch metadata for that show (eg. due to adding a bunch of shows at once).

The (slightly sanitised) requested URL: http://hostname:8081/showPoster/?show=/path/to/Jonathan%20Strange%20&%20Mr%20Norrell&which=banner

Traceback (most recent call last): 
File "/opt/sickrage/lib/tornado/web.py", line 1469, in _execute result = yield result 
File "/opt/sickrage/lib/tornado/gen.py", line 1015, in run value = future.result() 
File "/opt/sickrage/lib/tornado/concurrent.py", line 237, in result raise_exc_info(self._exc_info) 
File "/opt/sickrage/lib/tornado/gen.py", line 1021, in run yielded = self.gen.throw(*exc_info) 
File "/opt/sickrage/sickbeard/webserve.py", line 268, in get results = yield self.async_call(method) 
File "/opt/sickrage/lib/tornado/gen.py", line 1015, in run value = future.result() 
File "/opt/sickrage/lib/concurrent/futures/_base.py", line 422, in result return self.__get_result() 
File "/opt/sickrage/lib/concurrent/futures/thread.py", line 62, in run result = self.fn(*self.args, **self.kwargs) 
File "/opt/sickrage/sickbeard/webserve.py", line 284, in async_call result = function(**kwargs) 
TypeError: showPoster() got an unexpected keyword argument ' Mr Norrell'

**Comment by NickMolloy** [comment]
You are right, it is due to shows with ampersands in their names.
When a show is still being loaded, it's id in the showlist page is [set to it's title](https://github.com/SickRage/SickRage/blob/ecfef2cf75c7903782c0f5a0b53073d809fb8565/gui/slick/views/inc_home_showList.mako#L37). The ampersand in the title is therefore interpreted as a query string seperator, leading to an extra unexpected argument to `showPoster()`.
