### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/media/d99e/shadow11001/.sickrage/Logs/sickrage.log'

### ISSUE THREAD

**Issue by shadow11001** [SickRage/SickRage#3403]
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.7**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@826b084110bdef33f9a519686286a5d6f02e1bcc
No Log available with ERRORS:
### ERROR
```
Thread-35 :: [826b084] Failed doing webui callback: Traceback (most recent call last):
  File "/media/d99e/shadow11001/.sickrage/sickbeard/webserve.py", line 284, in async_call
    result = function(**kwargs)
  File "/media/d99e/shadow11001/.sickrage/sickbeard/webserve.py", line 5333, in viewlog
    data = sickbeard.logger.log_data(min_level, log_filter, log_search, max_lines)
  File "/media/d99e/shadow11001/.sickrage/sickbeard/logger.py", line 512, in log_data
    with io.open(_log_file, 'r', encoding='utf-8') as f:
IOError: [Errno 2] No such file or directory: '/media/d99e/shadow11001/.sickrage/Logs/sickrage.log'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
