### ISSUE TITLE
[APP SUBMITTED]: showPoster() got an unexpected keyword argument ' Funny Caught on Camera'

### ISSUE THREAD

**Issue by shadow11001** [SickRage/SickRage#3411]
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.7**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c1d4fd232f9e052063e08630b36c9cdd351e0e5a
No Log available with ERRORS:
### ERROR
```
Thread-25 :: [c1d4fd2] Failed doing webui callback: Traceback (most recent call last):
  File "/media/d99e/shadow11001/.sickrage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
TypeError: showPoster() got an unexpected keyword argument ' Funny Caught on Camera'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by shadow11001** [comment]
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.7**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c1d4fd232f9e052063e08630b36c9cdd351e0e5a
No Log available with ERRORS:
### ERROR
```
Thread-48 :: [c1d4fd2] Failed doing webui callback: Traceback (most recent call last):
  File "/media/d99e/shadow11001/.sickrage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
TypeError: showPoster() got an unexpected keyword argument ' Funny Caught on Camera'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by NickMolloy** [comment]
Seems to be the same as #3394.
