### ISSUE TITLE
[APP SUBMITTED]: unsupported type for timedelta days component: tuple

### ISSUE THREAD

**Issue by DDA78** [SickRage/SickRage#3432]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.9.14-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@78143873f776c0506c340c0eb6bab2f166952968
No Log available with ERRORS:
### ERROR
```
TORNADO :: [7814387] API :: unsupported type for timedelta days component: tuple
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment]
I can confirm, happens when loading schedule (for me it's in list layout in case that matters)
```
Error

unsupported type for timedelta days component: tuple

Traceback

Traceback (most recent call last): 
File "C:\SickRage\SickRage\lib\tornado\web.py", line 1469, in _execute result = yield result 
File "C:\SickRage\SickRage\lib\tornado\gen.py", line 1015, in run value = future.result() 
File "C:\SickRage\SickRage\lib\tornado\concurrent.py", line 237, in result raise_exc_info(self._exc_info) 
File "C:\SickRage\SickRage\lib\tornado\gen.py", line 1021, in run yielded = self.gen.throw(*exc_info) 
File "C:\SickRage\SickRage\sickbeard\webserve.py", line 269, in get results = yield self.async_call(method) 
File "C:\SickRage\SickRage\lib\tornado\gen.py", line 1015, in run value = future.result() 
File "C:\SickRage\SickRage\lib\concurrent\futures\_base.py", line 422, in result return self.__get_result() 
File "C:\SickRage\SickRage\lib\concurrent\futures\thread.py", line 62, in run result = self.fn(*self.args, **self.kwargs) 
File "C:\SickRage\SickRage\sickbeard\webserve.py", line 285, in async_call result = function(**kwargs) 
File "C:\SickRage\SickRage\sickbeard\webserve.py", line 497, in schedule results = ComingEpisodes.get_coming_episodes(ComingEpisodes.categories, sickbeard.COMING_EPS_SORT, False) 
File "C:\SickRage\SickRage\sickrage\show\ComingEpisodes.py", line 63, in get_coming_episodes recently = (date.today() - timedelta(days=sickbeard.COMING_EPS_MISSED_RANGE)).toordinal() 
TypeError: unsupported type for timedelta days component: tuple 
```

**Comment by aerandir83** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 20 2016, 16:33:50) [GCC 6.2.1 20160822]**
Operating System: **Linux-3.19.8-x86_64-with**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@78143873f776c0506c340c0eb6bab2f166952968
No Log available with ERRORS:
### ERROR
```
Thread-17 :: [7814387] Failed doing webui callback: Traceback (most recent call last):
  File "/sickrage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/sickrage/sickbeard/webserve.py", line 497, in schedule
    results = ComingEpisodes.get_coming_episodes(ComingEpisodes.categories, sickbeard.COMING_EPS_SORT, False)
  File "/sickrage/sickrage/show/ComingEpisodes.py", line 63, in get_coming_episodes
    recently = (date.today() - timedelta(days=sickbeard.COMING_EPS_MISSED_RANGE)).toordinal()
TypeError: unsupported type for timedelta days component: tuple

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by aerandir83** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 20 2016, 16:33:50) [GCC 6.2.1 20160822]**
Operating System: **Linux-3.19.8-x86_64-with**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@78143873f776c0506c340c0eb6bab2f166952968
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [7814387] Failed doing webui callback: Traceback (most recent call last):
  File "/sickrage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/sickrage/sickbeard/webserve.py", line 497, in schedule
    results = ComingEpisodes.get_coming_episodes(ComingEpisodes.categories, sickbeard.COMING_EPS_SORT, False)
  File "/sickrage/sickrage/show/ComingEpisodes.py", line 63, in get_coming_episodes
    recently = (date.today() - timedelta(days=sickbeard.COMING_EPS_MISSED_RANGE)).toordinal()
TypeError: unsupported type for timedelta days component: tuple

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sharkykh** [comment]
@aerandir83 Update SickRage.
This was fixed 3 hours ago.
