### ISSUE TITLE
Web display for logs displays error when viewing backlog filter

### ISSUE THREAD

**Issue by TheFiZi** [SickRage/SickRage#3434]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/v2017.03.19-1
OS: CentOS 6.8 64-bit
What you did: Went to the logging interface and selected 'Backlog' from the filter list
What happened: Python error was displayed
What you expected: Backlog log output
Logs: 
```
AA AttributeError: 'module' object has no attribute 'ANIME_SPLIT_HOME_IN_TABS'
AA __M_writer(unicode(sickbeard.ANIME_SPLIT_HOME_IN_TABS))
AA File "/data/apps/sa_******/sickrage/cache/mako/layouts/main.mako.py", line 93, in render_body
AA callable_(context, *args, **kwargs)
AA File "/data/apps/sa_******/sickrage/lib/mako/runtime.py", line 890, in _exec_template
AA _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
AA File "/data/apps/sa_******/sickrage/lib/mako/runtime.py", line 864, in _render_context
AA **_kwargs_for_callable(callable_, data))
AA File "/data/apps/sa_******/sickrage/lib/mako/runtime.py", line 829, in _render
AA as_unicode=True)
AA File "/data/apps/sa_******/sickrage/lib/mako/template.py", line 454, in render_unicode
AA File "/data/apps/sa_******/sickrage/sickbeard/webserve.py", line 164, in render
AA # handle 404 http errors
AA File "/data/apps/sa_******/sickrage/sickbeard/webserve.py", line 187, in write_error
AA self.write_error(status_code, **kwargs)
AA File "/data/apps/sa_******/sickrage/lib/tornado/web.py", line 994, in send_error
AA Traceback (most recent call last):
AA 2017-03-05 13:26:25 ERROR Uncaught exception in write_error
AA AttributeError: 'module' object has no attribute 'ANIME_SPLIT_HOME_IN_TABS'
AA __M_writer(unicode(sickbeard.ANIME_SPLIT_HOME_IN_TABS))
AA File "/data/apps/sa_******/sickrage/cache/mako/layouts/main.mako.py", line 93, in render_body
AA callable_(context, *args, **kwargs)
AA File "/data/apps/sa_******/sickrage/lib/mako/runtime.py", line 890, in _exec_template
AA _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
AA File "/data/apps/sa_******/sickrage/lib/mako/runtime.py", line 864, in _render_context
AA **_kwargs_for_callable(callable_, data))
AA File "/data/apps/sa_******/sickrage/lib/mako/runtime.py", line 829, in _render
AA as_unicode=True)
AA File "/data/apps/sa_******/sickrage/lib/mako/template.py", line 454, in render_unicode
AA File "/data/apps/sa_******/sickrage/sickbeard/webserve.py", line 164, in render
AA t = PageTemplate(rh=self, filename="restart.mako")
AA File "/data/apps/sa_******/sickrage/sickbeard/webserve.py", line 1260, in update
AA @run_on_executor
AA File "/data/apps/sa_******/sickrage/sickbeard/webserve.py", line 273, in async_call
AA Traceback (most recent call last):
AA AttributeError: 'module' object has no attribute 'ANIME_SPLIT_HOME_IN_TABS'
AA __M_writer(unicode(sickbeard.ANIME_SPLIT_HOME_IN_TABS))
AA File "/data/apps/sa_******/sickrage/cache/mako/layouts/main.mako.py", line 93, in render_body
AA callable_(context, *args, **kwargs)
AA File "/data/apps/sa_******/sickrage/lib/mako/runtime.py", line 890, in _exec_template
AA _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
AA File "/data/apps/sa_******/sickrage/lib/mako/runtime.py", line 864, in _render_context
AA **_kwargs_for_callable(callable_, data))
AA File "/data/apps/sa_******/sickrage/lib/mako/runtime.py", line 829, in _render
AA as_unicode=True)
AA File "/data/apps/sa_******/sickrage/lib/mako/template.py", line 454, in render_unicode
AA File "/data/apps/sa_******/sickrage/sickbeard/webserve.py", line 164, in render
AA t = PageTemplate(rh=self, filename="restart.mako")
AA File "/data/apps/sa_******/sickrage/sickbeard/webserve.py", line 1260, in update
AA @run_on_executor
AA File "/data/apps/sa_******/sickrage/sickbeard/webserve.py", line 273, in async_call
AA fatal: HTTP request failed
AA AttributeError: 'module' object has no attribute 'SICKRAGE_BACKGROUND'
AA __M_writer(unicode(sickbeard.SICKRAGE_BACKGROUND))
AA File "/data/apps/sa_******/sickrage/cache/mako/layouts/main.mako.py", line 117, in render_body
AA callable_(context, *args, **kwargs)
AA File "/data/apps/sa_******/sickrage/lib/mako/runtime.py", line 890, in _exec_template
AA _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
AA File "/data/apps/sa_******/sickrage/lib/mako/runtime.py", line 864, in _render_context
AA **_kwargs_for_callable(callable_, data))
AA File "/data/apps/sa_******/sickrage/lib/mako/runtime.py", line 829, in _render
AA as_unicode=True)
AA File "/data/apps/sa_******/sickrage/lib/mako/template.py", line 454, in render_unicode
AA except Exception:
AA File "/data/apps/sa_******/sickrage/sickbeard/webserve.py", line 160, in render
AA url = url[len(sickbeard.WEB_ROOT) + 1:]
AA File "/data/apps/sa_******/sickrage/sickbeard/webserve.py", line 183, in write_error
AA self.write_error(status_code, **kwargs)
AA File "/data/apps/sa_******/sickrage/lib/tornado/web.py", line 994, in send_error
AA Traceback (most recent call last):
AA 2017-01-26 21:12:30 ERROR Uncaught exception in write_error
AA AttributeError: 'module' object has no attribute 'SICKRAGE_BACKGROUND'
AA __M_writer(unicode(sickbeard.SICKRAGE_BACKGROUND))
AA File "/data/apps/sa_******/sickrage/cache/mako/layouts/main.mako.py", line 117, in render_body
AA callable_(context, *args, **kwargs)
AA File "/data/apps/sa_******/sickrage/lib/mako/runtime.py", line 890, in _exec_template
AA _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
AA File "/data/apps/sa_******/sickrage/lib/mako/runtime.py", line 864, in _render_context
AA **_kwargs_for_callable(callable_, data))
AA File "/data/apps/sa_******/sickrage/lib/mako/runtime.py", line 829, in _render
AA as_unicode=True)
AA File "/data/apps/sa_******/sickrage/lib/mako/template.py", line 454, in render_unicode
AA except Exception:
AA File "/data/apps/sa_******/sickrage/sickbeard/webserve.py", line 160, in render
AA backup = checkversion.updater and checkversion._runbackup() # pylint: disable=protected-access
AA File "/data/apps/sa_******/sickrage/sickbeard/webserve.py", line 1216, in update
AA for arg, value in kwargs.iteritems():
AA File "/data/apps/sa_******/sickrage/sickbeard/webserve.py", line 269, in async_call
AA Traceback (most recent call last):
AA AttributeError: 'module' object has no attribute 'SICKRAGE_BACKGROUND'
AA __M_writer(unicode(sickbeard.SICKRAGE_BACKGROUND))
AA File "/data/apps/sa_******/sickrage/cache/mako/layouts/main.mako.py", line 117, in render_body
AA callable_(context, *args, **kwargs)
AA File "/data/apps/sa_******/sickrage/lib/mako/runtime.py", line 890, in _exec_template
AA _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
AA File "/data/apps/sa_******/sickrage/lib/mako/runtime.py", line 864, in _render_context
AA **_kwargs_for_callable(callable_, data))
AA File "/data/apps/sa_******/sickrage/lib/mako/runtime.py", line 829, in _render
AA as_unicode=True)
AA File "/data/apps/sa_******/sickrage/lib/mako/template.py", line 454, in render_unicode
AA except Exception:
AA File "/data/apps/sa_******/sickrage/sickbeard/webserve.py", line 160, in render
AA backup = checkversion.updater and checkversion._runbackup() # pylint: disable=protected-access
AA File "/data/apps/sa_******/sickrage/sickbeard/webserve.py", line 1216, in update
AA for arg, value in kwargs.iteritems():
AA File "/data/apps/sa_******/sickrage/sickbeard/webserve.py", line 269, in async_call
```

![untitled](https://cloud.githubusercontent.com/assets/1762426/24084672/ae10bbf8-0cab-11e7-8583-b31d14074073.png)

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by NickMolloy** [comment]
Have you recently upgraded SickRage? [A similar issue](https://github.com/SickRage/SickRage/issues/2977#issuecomment-275324419) appeared after an upgrade.

Try restarting SickRage and see if this happens again.

**Comment by TheFiZi** [comment]
I had just updated.

Just updated again and restarted Sickrage twice. Still get that error when using the backlog filter.

**Comment by miigotu** [comment]
This info is in your log file itself, from when it WAS erroring during the update.
