### ISSUE TITLE
[APP SUBMITTED]: 403 {u'documentation_url': u'https://developer.github.com/v3/#rate-limiting', u'message': u'API rate limit exceeded for johann1007.'}

### ISSUE THREAD

**Issue by johann1007** [SickRage/SickRage#3438]
### INFO
Python Version: **2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]**
Operating System: **Linux-3.10.102-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@ba5331731f7d3a04eef8e396c6563fef5b83b749
No Log available with ERRORS:
### ERROR
```
Thread-25 :: [ba53317] Traceback (most recent call last):
  File "/app/sickrage/sickbeard/logger.py", line 385, in submit_errors
    for report in reports:
  File "/app/sickrage/lib/github/PaginatedList.py", line 48, in __iter__
    newElements = self._grow()
  File "/app/sickrage/lib/github/PaginatedList.py", line 60, in _grow
    newElements = self._fetchNextPage()
  File "/app/sickrage/lib/github/PaginatedList.py", line 161, in _fetchNextPage
    headers=self.__headers
  File "/app/sickrage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/app/sickrage/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://developer.github.com/v3/#rate-limiting', u'message': u'API rate limit exceeded for johann1007.'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
