### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: u'/config/cache/mako/layouts/main.mako.py'

### ISSUE THREAD

**Issue by johann1007** [SickRage/SickRage#3441]
### INFO
Python Version: **2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]**
Operating System: **Linux-3.10.102-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@ba5331731f7d3a04eef8e396c6563fef5b83b749
No Log available with ERRORS:
### ERROR
```
Thread-25 :: [ba53317] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 748, in index
    0], max_download_count=stats[1], controller="home", action="index", selected_root=selected_root or '-1')
  File "/app/sickrage/sickbeard/webserve.py", line 171, in render
    kwargs['backtrace'] = RichTraceback()
  File "/app/sickrage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/app/sickrage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/app/sickrage/lib/mako/template.py", line 632, in code
    return util.read_python_file(self.module_filename)
  File "/app/sickrage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/config/cache/mako/layouts/main.mako.py'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [5bc5c3a] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 280, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 766, in index
    0], max_download_count=stats[1], controller="home", action="index", selected_root=selected_root or '-1')
  File "/app/sickrage/sickbeard/webserve.py", line 162, in render
    kwargs['backtrace'] = RichTraceback()
  File "/app/sickrage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/app/sickrage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/app/sickrage/lib/mako/template.py", line 660, in code
    return util.read_python_file(self.module_filename)
  File "/app/sickrage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/config/cache/mako/layouts/main.mako.py'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [a760263] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 758, in index
    0], max_download_count=stats[1], controller="home", action="index", selected_root=selected_root or '-1')
  File "/app/sickrage/sickbeard/webserve.py", line 164, in render
    kwargs['backtrace'] = RichTraceback()
  File "/app/sickrage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/app/sickrage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/app/sickrage/lib/mako/template.py", line 660, in code
    return util.read_python_file(self.module_filename)
  File "/app/sickrage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/config/cache/mako/layouts/main.mako.py'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mannibis** [comment]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]**
Operating System: **Linux-3.12.6-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@34fdd20ee3f8ec8799b7577cfdbdc9cf7bb5f73c
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [34fdd20] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 761, in index
    0], max_download_count=stats[1], controller="home", action="index", selected_root=selected_root or '-1')
  File "/app/sickrage/sickbeard/webserve.py", line 164, in render
    kwargs['backtrace'] = RichTraceback()
  File "/app/sickrage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/app/sickrage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/app/sickrage/lib/mako/template.py", line 660, in code
    return util.read_python_file(self.module_filename)
  File "/app/sickrage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/config/cache/mako/layouts/main.mako.py'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.59+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [1ed3156] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickchill/views/index.py", line 180, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickchill/views/home.py", line 138, in index
    0], max_download_count=stats[1], controller="home", action="index", selected_root=selected_root or '-1')
  File "/app/sickrage/sickchill/views/common.py", line 115, in render
    kwargs['backtrace'] = RichTraceback()
  File "/app/sickrage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/app/sickrage/lib/mako/exceptions.py", line 166, in _init
    module_source = info.code
  File "/app/sickrage/lib/mako/template.py", line 679, in code
    return util.read_python_file(self.module_filename)
  File "/app/sickrage/lib/mako/util.py", line 391, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/config/cache/mako/layouts/main.mako.py'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by danmcg13** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-4.19.0-0.bpo.6-amd64-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@2404f197697602a2bbfa8e6b39207229a94d37bb
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [2404f19] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickchill/sickchill/views/index.py", line 180, in async_call
    result = function(**kwargs)
  File "/app/sickchill/sickchill/views/home.py", line 138, in index
    0], max_download_count=stats[1], controller="home", action="index", selected_root=selected_root or '-1')
  File "/app/sickchill/sickchill/views/common.py", line 115, in render
    kwargs['backtrace'] = RichTraceback()
  File "/app/sickchill/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/app/sickchill/lib/mako/exceptions.py", line 166, in _init
    module_source = info.code
  File "/app/sickchill/lib/mako/template.py", line 679, in code
    return util.read_python_file(self.module_filename)
  File "/app/sickchill/lib/mako/util.py", line 391, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/config/cache/mako/layouts/main.mako.py'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
