### ISSUE TITLE
[APP SUBMITTED]: [Errno 1] Operation not permitted: u'/apps/sickrage/gui/slick/views/displayShow.mako'

### ISSUE THREAD

**Issue by chimchild** [SickRage/SickRage#3449]
### INFO
Python Version: **2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]**
Operating System: **Linux-3.10.0-514.6.1.el7.x86_64-x86_64-with-centos-7.3.1611-Core**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@f2e84c185a15c6b42839dda48cf34c5e7b40048c
No Log available with ERRORS:
### ERROR
```
Thread-17 :: [f2e84c1] Failed doing webui callback: Traceback (most recent call last):
  File "/apps/sickrage/sickbeard/webserve.py", line 285, in async_call
  File "/apps/sickrage/sickbeard/webserve.py", line 1354, in displayShow
  File "/apps/sickrage/sickbeard/webserve.py", line 124, in __init__
  File "/apps/sickrage/lib/mako/lookup.py", line 256, in get_template
  File "/apps/sickrage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/apps/sickrage/lib/mako/template.py", line 322, in __init__
  File "/apps/sickrage/lib/mako/template.py", line 372, in _compile_from_file
  File "/apps/sickrage/lib/mako/util.py", line 365, in read_file
IOError: [Errno 1] Operation not permitted: u'/apps/sickrage/gui/slick/views/displayShow.mako'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Update your python to 2.7.10 - 2.17.13

And to fix your problem, make sure the user running SickRage owns the whole source of SickRage. It has to write files in there...

**Comment by thisdjiknow** [comment]
### INFO
Python Version: **3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]**
Operating System: **Linux-5.8.0-38-generic-x86_64-with-glibc2.32**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@07b71fe7076bf50be4c06f6d852a25b356ddaf5b
Link to Log: https://gist.github.com/14228192d0eaa7b07d64c6c28d8b5fe9
### ERROR
```
Unable to move file /home/********/Downloads/complete/The.Expanse.S05E08.Hard.Vacuum.720p.AMZN.WEB-DL.DDP5.1.H.264-NTG/The.Expanse.S05E08.Hard.Vacuum.mkv to /media/TV/The Expanse/The.Expanse.S05E08.Hard.Vacuum.mkv: [Errno 1] Operation not permitted
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by thisdjiknow** [comment]
### INFO
Python Version: **3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]**
Operating System: **Linux-5.8.0-38-generic-x86_64-with-glibc2.32**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@07b71fe7076bf50be4c06f6d852a25b356ddaf5b
Link to Log: https://gist.github.com/170eb3598804c38fdbbecf4660105f51
### ERROR
```
Unable to move file /home/********/Downloads/complete/Endeavour.S06E03.720p.HEVC.x265-MeGusta/1ee57db0dde447c2b853449d607019de.mkv to /media/Sci-Fi/TV/Endeavour/Endeavour.S06E03.Confection.mkv: [Errno 1] Operation not permitted
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by thisdjiknow** [comment]
### INFO
Python Version: **3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]**
Operating System: **Linux-5.8.0-38-generic-x86_64-with-glibc2.32**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@07b71fe7076bf50be4c06f6d852a25b356ddaf5b
Link to Log: https://gist.github.com/87d5bc87f638a5b389b75c552ba31031
### ERROR
```
Unable to move file /home/********/Downloads/complete/The.Expanse.S05E08.Hard.Vacuum.720p.AMZN.WEB-DL.DDP5.1.H.264-NTG/The.Expanse.S05E08.Hard.Vacuum.mkv to /media/TV/The Expanse/The.Expanse.S05E08.Hard.Vacuum.mkv: [Errno 1] Operation not permitted
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by thisdjiknow** [comment]
### INFO
Python Version: **3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]**
Operating System: **Linux-5.8.0-38-generic-x86_64-with-glibc2.32**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@07b71fe7076bf50be4c06f6d852a25b356ddaf5b
Link to Log: https://gist.github.com/e457b7596057afd03c3219e013b04e4f
### ERROR
```
Unable to move file /home/********/Downloads/complete/Endeavour.S06E04.720p.HEVC.x265-MeGusta/4cd714a4ca024416b92a3d29d28acb58.mkv to /media/Sci-Fi/TV/Endeavour/Endeavour.S06E04.Degüello.mkv: [Errno 1] Operation not permitted
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by thisdjiknow** [comment]
### INFO
Python Version: **3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]**
Operating System: **Linux-5.8.0-38-generic-x86_64-with-glibc2.32**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@07b71fe7076bf50be4c06f6d852a25b356ddaf5b
Link to Log: https://gist.github.com/86dec139a750120c8eb716c53405dfda
### ERROR
```
Unable to move file /home/********/Downloads/complete/Endeavour.S01.720p.WEB-DL.x265-HETeam/Ende@vour.S01E01.720p.WEB-DL.x265-HETeam.mkv to /media/Sci-Fi/TV/Endeavour/Endeavour.S01E01.Girl.mkv: [Errno 1] Operation not permitted
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by thisdjiknow** [comment]
### INFO
Python Version: **3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]**
Operating System: **Linux-5.8.0-38-generic-x86_64-with-glibc2.32**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@07b71fe7076bf50be4c06f6d852a25b356ddaf5b
Link to Log: https://gist.github.com/bb0eb7e620cfddb385588a95ea0e1818
### ERROR
```
Unable to move file /home/********/Downloads/complete/Endeavour.S01.720p.WEB-DL.x265-HETeam/Ende@vour.S01E04.720p.WEB-DL.x265-HETeam.mkv to /media/Sci-Fi/TV/Endeavour/Endeavour.S01E04.Home.mkv: [Errno 1] Operation not permitted
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by thisdjiknow** [comment]
### INFO
Python Version: **3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]**
Operating System: **Linux-5.8.0-38-generic-x86_64-with-glibc2.32**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@07b71fe7076bf50be4c06f6d852a25b356ddaf5b
Link to Log: https://gist.github.com/e7854f438ae7c270511d7566231f54ff
### ERROR
```
Unable to move file /home/********/Downloads/complete/Endeavour.S01.720p.WEB-DL.x265-HETeam/Ende@vour.S01E03.720p.WEB-DL.x265-HETeam.mkv to /media/Sci-Fi/TV/Endeavour/Endeavour.S01E03.Rocket.mkv: [Errno 1] Operation not permitted
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by thisdjiknow** [comment]
### INFO
Python Version: **3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]**
Operating System: **Linux-5.8.0-38-generic-x86_64-with-glibc2.32**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@07b71fe7076bf50be4c06f6d852a25b356ddaf5b
Link to Log: https://gist.github.com/3d01a68ce7e2e2b30f3c3a651eaec424
### ERROR
```
Unable to move file /home/********/Downloads/complete/Endeavour.S01.720p.WEB-DL.x265-HETeam/Ende@vour.S01E02.720p.WEB-DL.x265-HETeam.mkv to /media/Sci-Fi/TV/Endeavour/Endeavour.S01E02.Fugue.mkv: [Errno 1] Operation not permitted
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by thisdjiknow** [comment]
### INFO
Python Version: **3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]**
Operating System: **Linux-5.8.0-40-generic-x86_64-with-glibc2.32**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@c6ee7aa889661dde40ea2240ecb5d88da776e039
Link to Log: https://gist.github.com/4de789dbf22a0770644e9919753ba35d
### ERROR
```
Unable to move file /home/********/Downloads/complete/American.Gods.S03E03.720p.WEB.H264-GGEZ/1bcc3398b7b145b0880028594b4ba36b.mkv to /media/TV2/TV Overflow/American Gods/American.Gods.S03E03.Ashes.and.Demons.mkv: [Errno 1] Operation not permitted
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by thisdjiknow** [comment]
### INFO
Python Version: **3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]**
Operating System: **Linux-5.8.0-40-generic-x86_64-with-glibc2.32**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@c6ee7aa889661dde40ea2240ecb5d88da776e039
Link to Log: https://gist.github.com/4793a264c98c4c51e32b8fee30d6b20d
### ERROR
```
Unable to move file /home/********/Downloads/complete/American.Gods.S03E03.720p.WEB.H264-GGEZ/1bcc3398b7b145b0880028594b4ba36b.mkv to /media/TV2/TV Overflow/American Gods/American.Gods.S03E03.Ashes.and.Demons.mkv: [Errno 1] Operation not permitted
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
