### ISSUE TITLE
After updating I got this log error

### ISSUE THREAD

**Issue by NinoFloris** [SickRage/SickRage#3484]
Sickrage won't startup for me after commit c32c66b

```
2017-03-24 14:28:04 ERROR    Thread-30 :: [12f5423] Failed doing webui callback: Traceback (most recent call last):
  File "D:\Applications\Downloaders\SickRage\*********\webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "D:\Applications\Downloaders\SickRage\*********\webserve.py", line 1284, in update
  File "D:\Applications\Downloaders\SickRage\*********\webserve.py", line 172, in render
    return get_lookup().get_template('500.mako').render_unicode(*args, **kwargs)
  File "D:\Applications\Downloaders\SickRage\lib\mako\template.py", line 454, in render_unicode
    as_unicode=True)
  File "D:\Applications\Downloaders\SickRage\lib\mako\runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "D:\Applications\Downloaders\SickRage\lib\mako\runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "D:\Applications\Downloaders\SickRage\lib\mako\runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "D:\Applications\Downloaders\SickRage\cache\mako\layouts\main.mako.py", line 208, in render_body
    if *********.CUSTOM_CSS:
AttributeError: 'module' object has no attribute 'CUSTOM_CSS'
Traceback (most recent call last):
  File "D:\Applications\Downloaders\SickRage\*********\webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "D:\Applications\Downloaders\SickRage\*********\webserve.py", line 1284, in update
    
  File "D:\Applications\Downloaders\SickRage\*********\webserve.py", line 172, in render
    return get_lookup().get_template('500.mako').render_unicode(*args, **kwargs)
  File "D:\Applications\Downloaders\SickRage\lib\mako\template.py", line 454, in render_unicode
    as_unicode=True)
  File "D:\Applications\Downloaders\SickRage\lib\mako\runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "D:\Applications\Downloaders\SickRage\lib\mako\runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "D:\Applications\Downloaders\SickRage\lib\mako\runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "D:\Applications\Downloaders\SickRage\cache\mako\layouts\main.mako.py", line 208, in render_body
    if *********.CUSTOM_CSS:
AttributeError: 'module' object has no attribute 'CUSTOM_CSS'
2017-03-24 14:28:04 INFO     EVENT-QUEUE :: Shutting down Tornado
2017-03-24 14:28:04 ERROR    Future exception was never retrieved: Traceback (most recent call last):
  File "D:\Applications\Downloaders\SickRage\lib\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "D:\Applications\Downloaders\SickRage\*********\webserve.py", line 275, in get
    raise HTTPError(404)
HTTPError: HTTP 404: Not Found
```
Branch/Commit: latest develop
OS: Windows 10

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment]
have you tried manually restarting sickrage?

**Comment by NinoFloris** [comment]
Yes this is the log entry, I run sickrage as a windows service and tried to restart a few times

**Comment by sharkykh** [comment]
I just updated myself and got the error only when SickRage was shutting down in order to load the new version. After a refresh SickRage is working on the latest version.

Maybe try to remove the folder `D:\Applications\Downloaders\SickRage\cache\mako`

**Comment by NinoFloris** [comment]
Ok yeah after trying to go to the latest version again it seems to happen on shutdown. sickrage won't startup again, and if that log entry is on shutdown there is no startup log entry. let me run it from the shell. I'll post what I'll find

**Comment by NinoFloris** [comment]
Ok it took a while before something happened on the shell, but it started successfully. Then I tried to run it via the windows service which after that also works again.

Either it was a fluke or something prevented it from doing an upgrade process while running as a service. I don't know but it's fixed, thanks for the quick replies!
