### ISSUE TITLE
[APP SUBMITTED]: u'result'

### ISSUE THREAD

**Issue by STLawson** [SickRage/SickRage#3510]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7ba52ea56efd8ceb72e2fc23ba344c8599e75b0d
No Log available with ERRORS:
### ERROR
```
Thread-234 :: [7ba52ea] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 285, in async_call
  File "C:\SickRage\sickbeard\webserve.py", line 1292, in update
    # do a hard restart
  File "C:\SickRage\sickbeard\versionChecker.py", line 627, in update
    notifiers.notify_git_update(sickbeard.CUR_COMMIT_HASH or "")
  File "C:\SickRage\sickbeard\notifiers\__init__.py", line 107, in notify_git_update
    n.notify_git_update(new_version)
  File "C:\SickRage\sickbeard\notifiers\kodi.py", line 536, in notify_git_update
    self._notify_kodi(update_text + new_version, title)
  File "C:\SickRage\sickbeard\notifiers\kodi.py", line 134, in _notify_kodi
    kodiapi = self._get_kodi_version(curHost, username, password, dest_app)
  File "C:\SickRage\sickbeard\notifiers\kodi.py", line 87, in _get_kodi_version
    return result["result"]["version"]
KeyError: u'result'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by STLawson** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7ba52ea56efd8ceb72e2fc23ba344c8599e75b0d
No Log available with ERRORS:
### ERROR
```
CHECKVERSION :: [e2a51e2] Exception generated in thread CHECKVERSION: result
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by STLawson** [comment]
Just a quick comment on this issue. It happens essentially daily. I log in, shut down SR, and run the instructions given on the FAQ's and Fixes page under "[problems updating...](https://github.com/SickRage/SickRage/wiki/FAQ%27s-and-Fixes#i-have-problems-updating-or-my-installation-got-corrupt-what-now)". When I start SR back up, it doesn't seem to have any problem, but usually within a day or two, it says there's an update needed and gives me the above errors when I try the automatic update process.

**Comment by sharkykh** [comment]
Try shutting down your Kodi before updating.

What is your Kodi version?
Perhaps Kodi changed something in v17 (and later)

**Comment by STLawson** [comment]
Ok, I'll give that I a shot. I also disabled my kodi notifications from SR, so it's not really even trying to connect to it during the process. Not the "ideal" solution, but hopefully it'll make things run more smoothly for now.
I'm using Kodi 17.1-RC1

Thanks.

**Comment by sharkykh** [comment]
I see no issue, but I'm using Kodi 17.1, not the RCx versions.
[I suggest you update](https://kodi.tv/download/).

Maybe RC1 had issues with the remote control...

**Comment by sharkykh** [comment]
@STLawson Any updates on the matter?

**Comment by STLawson** [comment]
It does appear that disabling the Kodi notifications has fixed the issue. SR appears to be updating correctly and automatically now (at least, it has for the last couple of days. 

I don't really have the ability to update Kodi yet though, because I recently switched over to the Windows Store version of it (thinking that it'd be able to handle automatic updates to Kodi) although there is currently an issue with Kodi updating through the Windows Store...so it's stuck at 17.1 RC1 for now.

Since everything else is working fine currently, I think I'll just leave it as-is (since it's kinda a pain to switch back to the "standard" installation of Kodi). My plan is to wait until Windows and Kodi figure out their update issue (they are aware and working on it) and once I get updated to the regular 17.1, I'll re-enable the notifications and stuff. Since it appears that the issue is on Kodi's end, this issue can probably be closed.

Thanks for your help.
