### ISSUE TITLE
Maxing Out API Hits

### ISSUE THREAD

**Issue by HPMSGEN8** [SickRage/SickRage#3525]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master / 121a0fd93fd4cfe77b58d6cf762975883153cd63
OS: Synologu DSM 6
What you did: Nothing
What happened: API Hits To NZB.SU & NZB.Org Maxed Out
What you expected: Not Max Out In 1 Day
Logs:
```
AA AttributeError: 'UI' object has no attribute 'locale_json'
AA _route = _route.strip('/').replace('.', '_').replace('-', '_') or 'index'
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 267, in get
AA downCurQuality=download_current_quality)2017-03-30 19:57:02 INFO SEARCHQUEUE-BACKLOG-79824 :: Beginning backlog search for: [Naruto Shippuden]
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickrage/providers/GenericProvider.py", line 134, in find_search_results
AA searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 481, in searchProviders
AA Traceback (most recent call last):

Then I get tons of these:

2017-03-30 19:57:06 INFO SEARCHQUEUE-BACKLOG-79824 :: [NZB.su] :: Request failed: 429 Client Error: Too Many Requests for url: https://api.nzb.su/api?apikey=***************
```
This is all Auto nothing was done Manually. I have hit 5000 on the 1 and 3500 on the other this is very odd and i do not know why this is happening.

Thanks

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment]
The debug logs are messed up a bit... There's not connection between:
```
AA AttributeError: 'UI' object has no attribute 'locale_json'
AA _route = _route.strip('/').replace('.', '_').replace('-', '_') or 'index'
AA File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 267, in get
```
(Which shouldn't even happen, what the hell)

To the nzb provider stuff

**Comment by HPMSGEN8** [comment]
I have just it this again. Please can this get fixed

**Comment by HPMSGEN8** [comment]
Is there no way to split the Shows up into Batches to do updates to the NZB Providers as it happened again. (Just thinking can be 100 wrong here)

I really do not know what is going on.  as every day now it is maxing out over 5000 API Hits

Thanks

**Comment by sharkykh** [comment]
Could you maybe post an updated debug log?
The first one is very confusing.

**Comment by HPMSGEN8** [comment]
Here you go. This is an example of what I am getting all the time. I know some of this is meant to search but if the show is Downloads as what you want it should not try an look for info again should it ? 

`2017-04-02 20:56:26 DEBUG SEARCHQUEUE-BACKLOG-121361 :: [NZBs.org] :: Search string: Game of Thrones S02E01
2017-04-02 20:56:26 DEBUG SEARCHQUEUE-BACKLOG-121361 :: [NZBs.org] :: Search Mode: Episode
2017-04-02 20:56:26 INFO SEARCHQUEUE-BACKLOG-121361 :: [NZBs.org] :: Performing episode search for Game of Thrones
2017-04-02 20:56:26 INFO SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Request failed: HTTPSConnectionPool(host='api.nzb.su', port=443): Max retries exceeded with url: /api?apikey=**********&season=2&maxage=3000&cat=5000%2C5070%2C5040%2C5030%2C5060&q=Game+of+Thrones+S02E10&limit=100&t=tvsearch&offset=0&ep=10 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2017-04-02 20:56:24 DEBUG SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Search string: Game of Thrones S02E10
2017-04-02 20:56:24 DEBUG SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Search Mode: Episode
2017-04-02 20:56:24 INFO SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Request failed: HTTPSConnectionPool(host='api.nzb.su', port=443): Max retries exceeded with url: /api?apikey=**********&season=2&maxage=3000&cat=5000%2C5070%2C5040%2C5030%2C5060&q=Game+of+Thrones+S02E09&limit=100&t=tvsearch&offset=0&ep=9 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2017-04-02 20:56:22 DEBUG SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Search string: Game of Thrones S02E09
2017-04-02 20:56:22 DEBUG SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Search Mode: Episode
2017-04-02 20:56:22 INFO SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Request failed: HTTPSConnectionPool(host='api.nzb.su', port=443): Max retries exceeded with url: /api?apikey=**********&season=2&maxage=3000&cat=5000%2C5070%2C5040%2C5030%2C5060&q=Game+of+Thrones+S02E08&limit=100&t=tvsearch&offset=0&ep=8 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2017-04-02 20:56:20 DEBUG SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Search string: Game of Thrones S02E08
2017-04-02 20:56:20 DEBUG SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Search Mode: Episode
2017-04-02 20:56:20 INFO SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Request failed: HTTPSConnectionPool(host='api.nzb.su', port=443): Max retries exceeded with url: /api?apikey=**********&season=2&maxage=3000&cat=5000%2C5070%2C5040%2C5030%2C5060&q=Game+of+Thrones+S02E07&limit=100&t=tvsearch&offset=0&ep=7 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2017-04-02 20:56:18 DEBUG SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Search string: Game of Thrones S02E07
2017-04-02 20:56:18 DEBUG SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Search Mode: Episode
2017-04-02 20:56:18 INFO SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Request failed: HTTPSConnectionPool(host='api.nzb.su', port=443): Max retries exceeded with url: /api?apikey=**********&season=2&maxage=3000&cat=5000%2C5070%2C5040%2C5030%2C5060&q=Game+of+Thrones+S02E06&limit=100&t=tvsearch&offset=0&ep=6 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2017-04-02 20:56:16 DEBUG SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Search string: Game of Thrones S02E06
2017-04-02 20:56:16 DEBUG SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Search Mode: Episode
2017-04-02 20:56:16 INFO SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Request failed: HTTPSConnectionPool(host='api.nzb.su', port=443): Max retries exceeded with url: /api?apikey=**********&season=2&maxage=3000&cat=5000%2C5070%2C5040%2C5030%2C5060&q=Game+of+Thrones+S02E05&limit=100&t=tvsearch&offset=0&ep=5 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2017-04-02 20:56:14 DEBUG SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Search string: Game of Thrones S02E05
2017-04-02 20:56:14 DEBUG SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Search Mode: Episode
2017-04-02 20:56:14 INFO SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Request failed: HTTPSConnectionPool(host='api.nzb.su', port=443): Max retries exceeded with url: /api?apikey=**********&season=2&maxage=3000&cat=5000%2C5070%2C5040%2C5030%2C5060&q=Game+of+Thrones+S02E04&limit=100&t=tvsearch&offset=0&ep=4 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2017-04-02 20:56:12 DEBUG SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Search string: Game of Thrones S02E04
2017-04-02 20:56:12 DEBUG SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Search Mode: Episode
2017-04-02 20:56:12 INFO SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Request failed: HTTPSConnectionPool(host='api.nzb.su', port=443): Max retries exceeded with url: /api?apikey=**********&season=2&maxage=3000&cat=5000%2C5070%2C5040%2C5030%2C5060&q=Game+of+Thrones+S02E03&limit=100&t=tvsearch&offset=0&ep=3 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2017-04-02 20:56:10 DEBUG SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Search string: Game of Thrones S02E03
2017-04-02 20:56:10 DEBUG SEARCHQUEUE-BACKLOG-121361 :: [NZB.su] :: Search Mode: Episode`

**Comment by sharkykh** [comment]
How many items do you have backlogged?
How frequently do your run the backlog search?

**Comment by sharkykh** [comment]
Also, in this log the connection isn't even made.
Not because of maxed out API calls,
[looks like a DNS issue: `Temporary failure in name resolution`](https://github.com/kennethreitz/requests/issues/3677)

Try calling `https://api.nzb.su` outside SickRage (on the same system).
And check your DNS settings, I believe the issue is your DNS.

**Comment by HPMSGEN8** [comment]
Backlog Wanted = 111 / Backlog search frequency = 720 Minutes / DNS Issue yes i saw that but that is all fine. There is tons of logs like this one below. 

I wonder if the DNS Issue could be related to the API hits as well. as when it does get there then there is no response so it sends an hit again until it get ones or times out. 

`2017-03-30 19:57:06 INFO SEARCHQUEUE-BACKLOG-79824 :: [NZB.su] :: Request failed: 429 Client Error: Too Many Requests for url: https://api.nzb.su/api?apikey=***************`

Let me watch this for the next few days and see what happens.

**Comment by HPMSGEN8** [comment]
Right it just happened again and it is not an DNS issue this time. 

`2017-04-04 19:25:37 INFO SEARCHQUEUE-BACKLOG-75692 :: [NZB.su] :: Request failed: 429 Client Error: Too Many Requests for url: https://api.nzb.su/api?apikey=**********&season=18&maxage=3000&cat=5000%2C5070%2C5040%2C5030%2C5060&q=Law+%26+Order%3A+Special+Victims+Unit+S18E11&limit=100&t=tvsearch&offset=0&ep=11`

**Comment by sharkykh** [comment]
Sorry, I'm not sure what's causing it...

**Comment by sharkykh** [comment]
>My NOTES: I see what this is doing,. It is looking at all the Allowed vs Downloaded. So if i have it as SD and Allowed = 720p then it is trying to find SD.

This doesn't make sense. If the episode is SD and allowed is 720p it should perform a backlog search for **720p**.

>So is there an way i can stop this from happening. but i only want SD to get Downloaded but 720p is what i got Manually.

You got me confused now.
What is the final quality that you want? SD or HD720p?

**Comment by HPMSGEN8** [comment]
This can now get closed seems it is all fixed. Will keep an eye out on this. Thanks again.
