### ISSUE TITLE
After latest update, SickRage won't start

### ISSUE THREAD

**Issue by bartolomesoriano** [SickRage/SickRage#3558]
I just updated SickRage, and now it will not start.  I am getting this:

![2017-03-31](https://cloud.githubusercontent.com/assets/7786357/24554916/4253f5d2-15fd-11e7-80f2-ee10fea35d94.png)

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sjantzi** [comment]
Help same issue it will not start up after updating

**Comment by Mordak603** [comment]
Hi,
Same problem here. Sickrage is not restarting after last update.

**Comment by Rotox** [comment]
Thought it was just me but I'm getting the exact same error stream since the recent update and it won't start.

**Comment by seqiro** [comment]
Same here on MacOS Sierra.

**Comment by sjantzi** [comment]
I rolled back 3 files and it starts up :
sickbeard/__init__.py
sickbeard/helpers.py
sickbeard/webserve.py

**Comment by jangrewe** [comment]
Run this in your SickRage directory:
```
git checkout c05176c3f0d7af113f6cc77855ee989e1f065b28
```
and then start SR again, and disable automatic updates until it's fixed.

**Comment by damianharouff** [comment]
This doesn't seem to have fixed it. I checked out 3dc24c9 and I can see the return in sickrage/sickbeard/helpers.py, but it still doesn't start.

sickrage/sickbeard/helpers.py: 
  1872
  1873  def manage_torrents_url(reset=False):
  1874      if not reset:
  1875          return sickbeard.CLIENT_WEB_URLS.get('torrent', '')
  1876
  1877      if not sickbeard.USE_TORRENTS or sickbeard.TORRENT_METHOD == 'blackhole' or \
  1878              sickbeard.ENABLE_HTTPS and not sickbeard.TORRENT_HOST.lower().startswith('https'):
  1879          sickbeard.CLIENT_WEB_URLS['torrent'] = ''
  1880          return sickbeard.CLIENT_WEB_URLS.get('torrent')
  1881
  1882      torrent_ui_url = re.sub('localhost|127.0.0.1', sickbeard.LOCALHOST_IP or get_lan_ip(), sickbeard.TORRENT_HOST or '', re.I)
  1883

Mar 31 09:28:15 combine-plex systemd[1]: Starting SickRage Daemon...
Mar 31 09:28:17 combine-plex python2.7[32576]: Traceback (most recent call last):
Mar 31 09:28:17 combine-plex python2.7[32576]:   File "/opt/sickrage/SickBeard.py", line 494, in <module>
Mar 31 09:28:17 combine-plex python2.7[32576]:     SickRage().start()
Mar 31 09:28:17 combine-plex python2.7[32576]:   File "/opt/sickrage/SickBeard.py", line 242, in start
Mar 31 09:28:17 combine-plex python2.7[32576]:     sickbeard.initialize(consoleLogging=self.console_logging)
Mar 31 09:28:17 combine-plex python2.7[32576]:   File "/opt/sickrage/sickbeard/__init__.py", line 1100, in initialize
Mar 31 09:28:17 combine-plex python2.7[32576]:     helpers.manage_torrents_url(reset=True)
Mar 31 09:28:17 combine-plex python2.7[32576]:   File "/opt/sickrage/sickbeard/helpers.py", line 1897, in manage_torrents_url
Mar 31 09:28:17 combine-plex python2.7[32576]:     sickbeard.CLIENT_WEB_URLS['torrent'] = ('', torrent_ui_url)[test_exists(torrent_ui_url)]
Mar 31 09:28:17 combine-plex python2.7[32576]:   File "/opt/sickrage/sickbeard/helpers.py", line 1886, in test_exists
Mar 31 09:28:17 combine-plex python2.7[32576]:     h = requests.head(url)
Mar 31 09:28:17 combine-plex python2.7[32576]:   File "/opt/sickrage/lib/requests/api.py", line 93, in head
Mar 31 09:28:17 combine-plex python2.7[32576]:     return request('head', url, **kwargs)
Mar 31 09:28:17 combine-plex python2.7[32576]:   File "/opt/sickrage/lib/requests/api.py", line 53, in request
Mar 31 09:28:17 combine-plex python2.7[32576]:     return session.request(method=method, url=url, **kwargs)
Mar 31 09:28:17 combine-plex python2.7[32576]:   File "/opt/sickrage/lib/requests/sessions.py", line 468, in request
Mar 31 09:28:17 combine-plex python2.7[32576]:     resp = self.send(prep, **send_kwargs)
Mar 31 09:28:17 combine-plex python2.7[32576]:   File "/opt/sickrage/lib/requests/sessions.py", line 572, in send
Mar 31 09:28:17 combine-plex python2.7[32576]:     adapter = self.get_adapter(url=request.url)
Mar 31 09:28:17 combine-plex python2.7[32576]:   File "/opt/sickrage/lib/requests/sessions.py", line 646, in get_adapter
Mar 31 09:28:17 combine-plex python2.7[32576]:     raise InvalidSchema("No connection adapters were found for '%s'" % url)
Mar 31 09:28:17 combine-plex python2.7[32576]: requests.exceptions.InvalidSchema: No connection adapters were found for 'scgi://172.16.128.117:58846/'
Mar 31 09:28:17 combine-plex systemd[1]: sickrage.service: Control process exited, code=exited status=1
Mar 31 09:28:17 combine-plex systemd[1]: Failed to start SickRage Daemon.
Mar 31 09:28:17 combine-plex systemd[1]: sickrage.service: Unit entered failed state.
Mar 31 09:28:17 combine-plex systemd[1]: sickrage.service: Failed with result 'exit-code'.

**Comment by bartolomesoriano** [comment]
I downloaded the zip for the master branch from GitHub and extracted over my existing SickRage folder and the issue is fixed for me.

**Comment by jangrewe** [comment]
If you checked out the master branch and then (re)started, it would have been still the broken version. Either a `git pull` or a forced update check would have fixed it, as long as you don't try to start the unfixed commit in master again.

**Comment by damianharouff** [comment]
a1f5e67 got me fixed up. Thank you!

**Comment by VarunChugh** [comment]
Hi, sorry a newbie here. I am having the same issue, I have sickrage installed as a docker on my freenas. How do I correct this on Freenas? I re-installed the docker but it still wont start. Thanks
