### ISSUE TITLE
SickRage won't launch after lastest auto-update

### ISSUE THREAD

**Issue by cbinder4** [SickRage/SickRage#3561]
I'm unable to enable Debug logging because I can not get SickRage to launch.  When I run the service commands from a cmd prompt, I get the Traceback shown below.  It seems to be hung up maybe trying to process a show listed as Show.Name.S02E03.HDTV.XviD-RLSGROUP which I can't find anywhere.

OS: Windows 10
What you did: Ran SickRage Auto-Update
What happened: SickRage won't launch
Logs:
```
15:17:13 DEBUG::MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
15:17:13 DEBUG::MAIN :: Found codec for 'Show Name: Ep Name'.
15:17:13 DEBUG::MAIN :: Episode has no release group, replacing it with 'RLSGROUP'
15:17:13 DEBUG::MAIN :: formatting pattern: %S.N.S%0SE%0E.%Q.N-%RG -> Show.Name.S02E03.720p.HDTV-RLSGROUP
15:17:13 DEBUG::MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
15:17:13 DEBUG::MAIN :: Found codec for 'Show Name: Ep Name'.
15:17:13 DEBUG::MAIN :: formatting pattern: Season %0S -> Season 02
15:17:13 DEBUG::MAIN :: Trying to parse Show.Name.S02E03.720p.HDTV-RLSGROUP.ext
15:17:13 DEBUG::MAIN :: Parsed Show.Name.S02E03.720p.HDTV-RLSGROUP.ext into Show Name - S02E03 [GROUP: RLSGROUP.ext] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
15:17:13 DEBUG::MAIN :: The name Show.Name.S02E03.720p.HDTV-RLSGROUP.ext parsed into Show Name - S02E03 [GROUP: RLSGROUP.ext] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
Traceback (most recent call last):
  File "C:\SickRage\SickRage\SickBeard.py", line 494, in <module>
    SickRage().start()
  File "C:\SickRage\SickRage\SickBeard.py", line 242, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "C:\SickRage\SickRage\sickbeard\__init__.py", line 1100, in initialize
    helpers.manage_torrents_url(reset=True)
  File "C:\SickRage\SickRage\sickbeard\helpers.py", line 1897, in manage_torrents_url
    sickbeard.CLIENT_WEB_URLS['torrent'] = ('', torrent_ui_url)[test_exists(torrent_ui_url)]
  File "C:\SickRage\SickRage\sickbeard\helpers.py", line 1886, in test_exists
    h = requests.head(url)
  File "C:\SickRage\SickRage\lib\requests\api.py", line 93, in head
    return request('head', url, **kwargs)
  File "C:\SickRage\SickRage\lib\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\SickRage\SickRage\lib\requests\sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "C:\SickRage\SickRage\lib\requests\sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\SickRage\SickRage\lib\requests\models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "C:\SickRage\SickRage\lib\requests\models.py", line 353, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?




Also, the log file seems to just show this over and over.

2017-03-31 15:13:15 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2017-03-31 15:13:15 DEBUG    MAIN :: Found codec for 'Show Name: Ep Name'.
2017-03-31 15:13:15 DEBUG    MAIN :: Episode has no release group, replacing it with 'RLSGROUP'
2017-03-31 15:13:15 DEBUG    MAIN :: formatting pattern: %S.N.S%0SE%0E.%Q.N-%RG -> Show.Name.S02E03.720p.HDTV-RLSGROUP
2017-03-31 15:13:15 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2017-03-31 15:13:15 DEBUG    MAIN :: Found codec for 'Show Name: Ep Name'.
2017-03-31 15:13:15 DEBUG    MAIN :: formatting pattern: Season %0S -> Season 02
2017-03-31 15:13:15 DEBUG    MAIN :: Trying to parse Show.Name.S02E03.720p.HDTV-RLSGROUP.ext
2017-03-31 15:13:15 DEBUG    MAIN :: Parsed Show.Name.S02E03.720p.HDTV-RLSGROUP.ext into Show Name - S02E03 [GROUP: RLSGROUP.ext] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2017-03-31 15:13:15 DEBUG    MAIN :: The name Show.Name.S02E03.720p.HDTV-RLSGROUP.ext parsed into Show Name - S02E03 [GROUP: RLSGROUP.ext] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2017-03-31 15:17:13 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2017-03-31 15:17:13 DEBUG    MAIN :: Found codec for 'Show Name: Ep Name'.
2017-03-31 15:17:13 DEBUG    MAIN :: Episode has no release group, replacing it with 'RLSGROUP'
2017-03-31 15:17:13 DEBUG    MAIN :: formatting pattern: %S.N.S%0SE%0E.%Q.N-%RG -> Show.Name.S02E03.720p.HDTV-RLSGROUP
2017-03-31 15:17:13 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2017-03-31 15:17:13 DEBUG    MAIN :: Found codec for 'Show Name: Ep Name'.
2017-03-31 15:17:13 DEBUG    MAIN :: formatting pattern: Season %0S -> Season 02
2017-03-31 15:17:13 DEBUG    MAIN :: Trying to parse Show.Name.S02E03.720p.HDTV-RLSGROUP.ext
2017-03-31 15:17:13 DEBUG    MAIN :: Parsed Show.Name.S02E03.720p.HDTV-RLSGROUP.ext into Show Name - S02E03 [GROUP: RLSGROUP.ext] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2017-03-31 15:17:13 DEBUG    MAIN :: The name Show.Name.S02E03.720p.HDTV-RLSGROUP.ext parsed into Show Name - S02E03 [GROUP: RLSGROUP.ext] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
```

Not sure what happened, but sure would be happy if someone could help me get it going again.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment]
Try https://github.com/SickRage/sickrage.github.io#before-you-open-an-issue

**Comment by cbinder4** [comment]
Yes, I've just followed #3558 to correct my issue.  Sorry... don't know how I did not see that before I posted.
