### ISSUE TITLE
Sickbeard crashes on startup since last update

### ISSUE THREAD

**Issue by marka65** [SickRage/SickRage#3563]
Branch/Commit: **master / a1f5e6750493b00b032536c9a4274da57b5b9531**
OS: **QNAP (Linux-4.2.8-x86_64-with-glibc2.2.5)**
What you did: **Nothing - woke up this morning to Sickbeard not working**
What happened: **Not running**
What you expected: **Running**

Everything was running fine and this last update somehow broke Sickbeard from starting up

Logs: **Bash shell script output**

> [/share/QPKG/QSickRage] # ./QSickRage.sh start
file exists
Traceback (most recent call last):
  File "SickBeard.py", line 494, in <module>
    SickRage().start()
  File "SickBeard.py", line 242, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage-master/sickbeard/__init__.py", line 1100, in initialize
    helpers.manage_torrents_url(reset=True)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage-master/sickbeard/helpers.py", line 1897, in manage_torrents_url
    sickbeard.CLIENT_WEB_URLS['torrent'] = ('', torrent_ui_url)[test_exists(torrent_ui_url)]
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage-master/sickbeard/helpers.py", line 1886, in test_exists
    h = requests.head(url)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage-master/lib/requests/api.py", line 93, in head
    return request('head', url, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage-master/lib/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage-master/lib/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage-master/lib/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage-master/lib/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage-master/lib/requests/models.py", line 353, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
[/share/QPKG/QSickRage] #

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment]
Fixed in the latest update

See https://github.com/SickRage/SickRage/issues/3558
or https://github.com/SickRage/sickrage.github.io#before-you-open-an-issue

**Comment by marka65** [comment]
Sorry did a scan and missed them....

**Comment by sharkykh** [comment]
No prob 😄
