### ISSUE TITLE
One show won't postprocess

### ISSUE THREAD

**Issue by Yellow1144** [SickRage/SickRage#3565]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master/a1f5e6750493b00b032536c9a4274da57b5b9531
OS:Win7 Pro/64bit

I'll try again...

What you did: Manually downloaded a show then later added it in SR. Show folder was successfully created in the proper folder on the proper drive and folder was populated with art and show metadata.

What happened: Upon  completion, moved complete downloads into the right folder for post processing. Post processing failed with the following error. At the same time other shows were in the same folder and were being successfully post processed to their destination on the same drive. This started yesterday and it is the only show that is having this problem.

What you expected:
Logs:
```
2017-03-31 23:07:13 DEBUG    Thread-20 :: Analyzing name Con Man S01E01 Stalled.mp4
2017-03-31 23:07:13 DEBUG    Thread-20 :: Parsed Con Man S01E01 Stalled into Con Man - S01E01 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2017-03-31 23:07:13 DEBUG    Thread-20 :: Parse result not sufficient (all following have to be set). will not save release name
2017-03-31 23:07:13 DEBUG    Thread-20 :: Parse result(series_name): Con Man
2017-03-31 23:07:13 DEBUG    Thread-20 :: Parse result(season_number): 1
2017-03-31 23:07:13 DEBUG    Thread-20 :: Parse result(episode_numbers): [1]
2017-03-31 23:07:13 DEBUG    Thread-20 ::  or Parse result(air_date): None
2017-03-31 23:07:13 DEBUG    Thread-20 :: Parse result(release_group): None
2017-03-31 23:07:13 DEBUG    Thread-20 :: Retrieving episode object for 1x1
2017-03-31 23:07:13 DEBUG    Thread-20 :: Looking up quality for name Complete TV, got Unknown
2017-03-31 23:07:13 DEBUG    Thread-20 :: Looking up quality for name Con Man S01E01 Stalled.mp4, got Unknown
2017-03-31 23:07:13 DEBUG    Thread-20 :: Guessing quality for name Con Man S01E01 Stalled.mp4, got Unknown
2017-03-31 23:07:13 DEBUG    Thread-20 :: Quality of the episode we're processing: Unknown
2017-03-31 23:07:13 DEBUG    Thread-20 :: Is ep a priority download: True
2017-03-31 23:07:13 DEBUG    Thread-20 :: There is no existing file so there's no worries about replacing it
2017-03-31 23:07:13 INFO     Thread-20 :: This download is marked a priority download so I'm going to replace an existing file if I find one
2017-03-31 23:07:13 DEBUG    Thread-20 :: Trying to determine free space on destination drive
2017-03-31 23:07:13 INFO     Thread-20 :: Process method is 'move' and src and destination are on the same device, skipping free space check
2017-03-31 23:07:13 DEBUG    Thread-20 :: Using original release name Con Man S01E01 Stalled.mp4
2017-03-31 23:07:13 DEBUG    Thread-20 :: Folder name (Complete TV) appears to be a valid release name. Using it.
2017-03-31 23:07:13 DEBUG    Thread-20 :: Using cached parse result for: Con Man S01E01 Stalled
2017-03-31 23:07:13 DEBUG    Thread-20 :: formatting pattern: %S.N.S%0SE%0E.%E.N -> Con.Man.S01E01.Stalled
2017-03-31 23:07:13 DEBUG    Thread-20 :: Destination folder for this episode: Q:\Series 2\Con Man
2017-03-31 23:07:13 DEBUG    Thread-20 :: Checking if the path Q:\Series 2\Con Man already exists
2017-03-31 23:07:14 DEBUG    Thread-20 :: Moving file from E:\Torrents\Complete Downloads\Complete TV\Con Man S01E01 Stalled.mp4 to Q:\Series 2\Con Man\Con.Man.S01E01.Stalled.mp4
2017-03-31 23:07:14 ERROR    Thread-20 :: [a1f5e67] Unable to move file E:\Torrents\Complete Downloads\Complete TV\Con Man S01E01 Stalled.mp4 to Q:\Series 2\Con Man\Con.Man.S01E01.Stalled.mp4: error 2 : No such file or directory
Traceback (most recent call last):
  File "C:\Users\user\SickRage\SickRage\sickbeard\postProcessor.py", line 369, in _int_move
    helpers.moveFile(cur_file_path, new_file_path)
  File "C:\Users\user\SickRage\SickRage\sickbeard\helpers.py", line 388, in moveFile
    ek(shutil.move, srcFile, destFile)
  File "C:\Users\user\SickRage\SickRage\sickrage\helper\encoding.py", line 41, in ek
    result = function(*args, **kwargs)
  File "C:\Users\user\SickRage\Python\lib\shutil.py", line 302, in move
    copy2(src, real_dst)
  File "C:\Users\user\SickRage\Python\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Users\user\SickRage\Python\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: u'Q:\\Series 2\\Con Man\\Con.Man.S01E01.Stalled.mp4'
2017-03-31 23:07:14 WARNING  Thread-20 :: Processing failed for E:\Torrents\Complete Downloads\Complete TV\Con Man S01E01 Stalled.mp4: Unable to move the files to their new home
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment]
- Check if the `Q:\Series 2\Con Man` directory exists.
- Enable `Create missing show directories` in Post-Processing configuration.
Then try again.

**Comment by Yellow1144** [comment]
Yeah, as I mentioned above that directory was created fine and was populated with metadata and art.
Enabling Create Missing Show directories has no effect.

**Comment by Yellow1144** [comment]
I figured it out. It is a strange situation where when SR attempts to rename the file with a period after Con, windows complains because Con is a reserved word in the OS and won't allow the operation. It's just that the windows error is not reflected in the error that is registered in SR. Damn windows.. Moving to Linux soon.. 
Nothing to see here.. Carry on...
