### ISSUE TITLE
Invalid URL '': No schema supplied. Perhaps you meant http://?

### ISSUE THREAD

**Issue by McKay1717** [SickRage/SickRage#3571]
Branch/Commit: master/c53b55fbd000d73bdcd84900bae2afc3bfff15a3
OS: Ubuntu 16.04 server
What you did: service sickrage start
What happened:
Sickrage crash and abort boot
What you expected:
Sickrage boot and run normaly
Logs:
```
Traceback (most recent call last):
  File "SickBeard.py", line 494, in <module>
    SickRage().start()
  File "SickBeard.py", line 242, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/opt/sickrage/sickbeard/__init__.py", line 1100, in initialize
    helpers.manage_torrents_url(reset=True)
  File "/opt/sickrage/sickbeard/helpers.py", line 1897, in manage_torrents_url
    sickbeard.CLIENT_WEB_URLS['torrent'] = ('', torrent_ui_url)[test_exists(torrent_ui_url)]
  File "/opt/sickrage/sickbeard/helpers.py", line 1886, in test_exists
    h = requests.head(url)
  File "/opt/sickrage/lib/requests/api.py", line 93, in head
    return request('head', url, **kwargs)
  File "/opt/sickrage/lib/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/sickrage/lib/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/opt/sickrage/lib/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/opt/sickrage/lib/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/opt/sickrage/lib/requests/models.py", line 353, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment]
Fixed in the latest update

See https://github.com/SickRage/SickRage/issues/3558
or https://github.com/SickRage/sickrage.github.io#before-you-open-an-issue
