### ISSUE TITLE
Sickrage will not load 

### ISSUE THREAD

**Issue by vbigchris** [SickRage/SickRage#3572]
-- Unit acpid.service has finished starting up.
--
-- The start-up result is done.
Apr 01 21:49:52 nzbsvrv3 polkitd(authority=local)[996]: Unregistered Authentication Agent for unix-process:14906:799403 (system bus name :1.28, object path /org/freedes
Apr 01 21:49:57 nzbsvrv3 sudo[14928]:  nzbuser : TTY=pts/0 ; PWD=/home/nzbuser ; USER=root ; COMMAND=/usr/sbin/service sickrage start
Apr 01 21:49:57 nzbsvrv3 sudo[14928]: pam_unix(sudo:session): session opened for user root by nzbuser(uid=0)
Apr 01 21:50:12 nzbsvrv3 python[14898]: Traceback (most recent call last):
Apr 01 21:50:12 nzbsvrv3 python[14898]:   File "/opt/sickrage/SickBeard.py", line 494, in <module>
Apr 01 21:50:12 nzbsvrv3 python[14898]:     SickRage().start()
Apr 01 21:50:12 nzbsvrv3 python[14898]:   File "/opt/sickrage/SickBeard.py", line 242, in start
Apr 01 21:50:12 nzbsvrv3 python[14898]:     sickbeard.initialize(consoleLogging=self.console_logging)
Apr 01 21:50:12 nzbsvrv3 python[14898]:   File "/opt/sickrage/sickbeard/__init__.py", line 1100, in initialize
Apr 01 21:50:12 nzbsvrv3 python[14898]:     helpers.manage_torrents_url(reset=True)
Apr 01 21:50:12 nzbsvrv3 python[14898]:   File "/opt/sickrage/sickbeard/helpers.py", line 1897, in manage_torrents_url
Apr 01 21:50:12 nzbsvrv3 python[14898]:     sickbeard.CLIENT_WEB_URLS['torrent'] = ('', torrent_ui_url)[test_exists(torrent_ui_url)]
Apr 01 21:50:12 nzbsvrv3 python[14898]:   File "/opt/sickrage/sickbeard/helpers.py", line 1886, in test_exists
Apr 01 21:50:12 nzbsvrv3 python[14898]:     h = requests.head(url)
Apr 01 21:50:12 nzbsvrv3 python[14898]:   File "/opt/sickrage/lib/requests/api.py", line 93, in head
Apr 01 21:50:12 nzbsvrv3 python[14898]:     return request('head', url, **kwargs)
Apr 01 21:50:12 nzbsvrv3 python[14898]:   File "/opt/sickrage/lib/requests/api.py", line 53, in request
Apr 01 21:50:12 nzbsvrv3 python[14898]:     return session.request(method=method, url=url, **kwargs)
Apr 01 21:50:12 nzbsvrv3 python[14898]:   File "/opt/sickrage/lib/requests/sessions.py", line 454, in request
Apr 01 21:50:12 nzbsvrv3 python[14898]:     prep = self.prepare_request(req)
Apr 01 21:50:12 nzbsvrv3 python[14898]:   File "/opt/sickrage/lib/requests/sessions.py", line 388, in prepare_request
Apr 01 21:50:12 nzbsvrv3 python[14898]:     hooks=merge_hooks(request.hooks, self.hooks),
Apr 01 21:50:12 nzbsvrv3 python[14898]:   File "/opt/sickrage/lib/requests/models.py", line 293, in prepare
Apr 01 21:50:12 nzbsvrv3 python[14898]:     self.prepare_url(url, params)
Apr 01 21:50:12 nzbsvrv3 python[14898]:   File "/opt/sickrage/lib/requests/models.py", line 353, in prepare_url
Apr 01 21:50:12 nzbsvrv3 python[14898]:     raise MissingSchema(error)
Apr 01 21:50:12 nzbsvrv3 python[14898]: requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
Apr 01 21:50:13 nzbsvrv3 systemd[1]: sickrage.service: Control process exited, code=exited status=1
Apr 01 21:50:13 nzbsvrv3 systemd[1]: Failed to start SickRage Daemon.
-- Subject: Unit sickrage.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit sickrage.service has failed.
--
-- The result is failed.
Apr 01 21:50:13 nzbsvrv3 sudo[14928]: pam_unix(sudo:session): session closed for user root
Apr 01 21:50:13 nzbsvrv3 systemd[1]: sickrage.service: Unit entered failed state.
Apr 01 21:50:13 nzbsvrv3 systemd[1]: sickrage.service: Failed with result 'exit-code'.

running Ubuntu 16

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment]
Fixed in the latest update

See https://github.com/SickRage/SickRage/issues/3558
or https://github.com/SickRage/sickrage.github.io#before-you-open-an-issue
