### ISSUE TITLE
still  not fixed 

### ISSUE THREAD

**Issue by vbigchris** [SickRage/SickRage#3573]
```
-- Unit acpid.service has finished starting up.

-- The start-up result is done.
 Apr 01 21:49:52 nzbsvrv3 polkitd(authority=local)[996]: Unregistered Authentication Agent for unix-process:14906:799403 (system bus name :1.28, object path /org/freedes
 Apr 01 21:49:57 nzbsvrv3 sudo[14928]: nzbuser : TTY=pts/0 ; PWD=/home/nzbuser ; USER=root ; COMMAND=/usr/sbin/service sickrage start
 Apr 01 21:49:57 nzbsvrv3 sudo[14928]: pam_unix(sudo:session): session opened for user root by nzbuser(uid=0)
 Apr 01 21:50:12 nzbsvrv3 python[14898]: Traceback (most recent call last):
 Apr 01 21:50:12 nzbsvrv3 python[14898]: File "/opt/sickrage/SickBeard.py", line 494, in 
 Apr 01 21:50:12 nzbsvrv3 python[14898]: SickRage().start()
 Apr 01 21:50:12 nzbsvrv3 python[14898]: File "/opt/sickrage/SickBeard.py", line 242, in start
 Apr 01 21:50:12 nzbsvrv3 python[14898]: sickbeard.initialize(consoleLogging=self.console_logging)
 Apr 01 21:50:12 nzbsvrv3 python[14898]: File "/opt/sickrage/sickbeard/init.py", line 1100, in initialize
 Apr 01 21:50:12 nzbsvrv3 python[14898]: helpers.manage_torrents_url(reset=True)
 Apr 01 21:50:12 nzbsvrv3 python[14898]: File "/opt/sickrage/sickbeard/helpers.py", line 1897, in manage_torrents_url
 Apr 01 21:50:12 nzbsvrv3 python[14898]: sickbeard.CLIENT_WEB_URLS['torrent'] = ('', torrent_ui_url)[test_exists(torrent_ui_url)]
 Apr 01 21:50:12 nzbsvrv3 python[14898]: File "/opt/sickrage/sickbeard/helpers.py", line 1886, in test_exists
 Apr 01 21:50:12 nzbsvrv3 python[14898]: h = requests.head(url)
 Apr 01 21:50:12 nzbsvrv3 python[14898]: File "/opt/sickrage/lib/requests/api.py", line 93, in head
 Apr 01 21:50:12 nzbsvrv3 python[14898]: return request('head', url, **kwargs)
 Apr 01 21:50:12 nzbsvrv3 python[14898]: File "/opt/sickrage/lib/requests/api.py", line 53, in request
 Apr 01 21:50:12 nzbsvrv3 python[14898]: return session.request(method=method, url=url, **kwargs)
 Apr 01 21:50:12 nzbsvrv3 python[14898]: File "/opt/sickrage/lib/requests/sessions.py", line 454, in request
 Apr 01 21:50:12 nzbsvrv3 python[14898]: prep = self.prepare_request(req)
 Apr 01 21:50:12 nzbsvrv3 python[14898]: File "/opt/sickrage/lib/requests/sessions.py", line 388, in prepare_request
 Apr 01 21:50:12 nzbsvrv3 python[14898]: hooks=merge_hooks(request.hooks, self.hooks),
 Apr 01 21:50:12 nzbsvrv3 python[14898]: File "/opt/sickrage/lib/requests/models.py", line 293, in prepare
 Apr 01 21:50:12 nzbsvrv3 python[14898]: self.prepare_url(url, params)
 Apr 01 21:50:12 nzbsvrv3 python[14898]: File "/opt/sickrage/lib/requests/models.py", line 353, in prepare_url
 Apr 01 21:50:12 nzbsvrv3 python[14898]: raise MissingSchema(error)
 Apr 01 21:50:12 nzbsvrv3 python[14898]: requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
 Apr 01 21:50:13 nzbsvrv3 systemd[1]: sickrage.service: Control process exited, code=exited status=1
 Apr 01 21:50:13 nzbsvrv3 systemd[1]: Failed to start SickRage Daemon.
 -- Subject: Unit sickrage.service has failed
 -- Defined-By: systemd
 -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- Unit sickrage.service has failed.

-- The result is failed.
 Apr 01 21:50:13 nzbsvrv3 sudo[14928]: pam_unix(sudo:session): session closed for user root
 Apr 01 21:50:13 nzbsvrv3 systemd[1]: sickrage.service: Unit entered failed state.
 Apr 01 21:50:13 nzbsvrv3 systemd[1]: sickrage.service: Failed with result 'exit-code'.

running Ubuntu 16

nzbuser@nzbsvrv3:/opt/sickrage$ sudo service sickrage start
Job for sickrage.service failed because the control process exited with error code. See "systemctl status sickrage.service" and "journalctl -xe" for details.
nzbuser@nzbsvrv3:/opt/sickrage$ git checkout a1f5e6750493b00b032536c9a4274da57b5b9531
Note: checking out 'a1f5e6750493b00b032536c9a4274da57b5b9531'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at a1f5e67... #3558 - Make sure to check that host starts with http for manage_torrents_url
nzbuser@nzbsvrv3:/opt/sickrage$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
nzbuser@nzbsvrv3:/opt/sickrage$ sudo git pull
Already up-to-date.
nzbuser@nzbsvrv3:/opt/sickrage$ sudo service sickrage start
Job for sickrage.service failed because the control process exited with error code. See "systemctl status sickrage.service" and "journalctl -xe" for details.
nzbuser@nzbsvrv3:/opt/sickrage$
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by vbigchris** [comment]
-- The result is failed.
Apr 01 22:09:59 nzbsvrv3 systemd[1]: sickrage.service: Unit entered failed state.
Apr 01 22:09:59 nzbsvrv3 systemd[1]: sickrage.service: Failed with result 'exit-code'.
Apr 01 22:09:59 nzbsvrv3 sudo[1788]: pam_unix(sudo:session): session closed for user root
Apr 01 22:17:01 nzbsvrv3 CRON[1859]: pam_unix(cron:session): session opened for user root by (uid=0)
Apr 01 22:17:01 nzbsvrv3 CRON[1860]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Apr 01 22:17:01 nzbsvrv3 CRON[1859]: pam_unix(cron:session): session closed for user root
Apr 01 22:19:47 nzbsvrv3 sudo[1885]:  nzbuser : TTY=pts/0 ; PWD=/opt/sickrage ; USER=root ; COMMAND=/usr/sbin/service sickrage start
Apr 01 22:19:47 nzbsvrv3 sudo[1885]: pam_unix(sudo:session): session opened for user root by nzbuser(uid=0)
Apr 01 22:19:47 nzbsvrv3 systemd[1916]: sickrage.service: Failed at step USER spawning /usr/bin/python2.7: No such process
-- Subject: Process /usr/bin/python2.7 could not be executed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- The process /usr/bin/python2.7 could not be executed and failed.
--
-- The error number returned by this process is 3.
Apr 01 22:19:47 nzbsvrv3 systemd[1]: Starting SickRage Daemon...
-- Subject: Unit sickrage.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit sickrage.service has begun starting up.
Apr 01 22:19:47 nzbsvrv3 systemd[1]: sickrage.service: Control process exited, code=exited status=217
Apr 01 22:19:47 nzbsvrv3 systemd[1]: Failed to start SickRage Daemon.
-- Subject: Unit sickrage.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit sickrage.service has failed.
--
-- The result is failed.
Apr 01 22:19:47 nzbsvrv3 systemd[1]: sickrage.service: Unit entered failed state.
Apr 01 22:19:47 nzbsvrv3 systemd[1]: sickrage.service: Failed with result 'exit-code'.
Apr 01 22:19:47 nzbsvrv3 sudo[1885]: pam_unix(sudo:session): session closed for user root

**Comment by sharkykh** [comment]
Why did you open another issue? You could have just commented there if you had any problem...
Never mind that now.

Try:
```
git fetch
git reset --hard origin/master
git rev-parse --verify HEAD
```

**Comment by vbigchris** [comment]
it would not allow me to add to the other one 

nzbuser@nzbsvrv3:/opt/sickrage$ git fetch
nzbuser@nzbsvrv3:/opt/sickrage$ git reset --hard origin/master
HEAD is now at a1f5e67 #3558 - Make sure to check that host starts with http for manage_torrents_url
nzbuser@nzbsvrv3:/opt/sickrage$ git rev-parse --verify HEAD
a1f5e6750493b00b032536c9a4274da57b5b9531
nzbuser@nzbsvrv3:/opt/sickrage$ sudo service sickrage start
Job for sickrage.service failed because the control process exited with error code. See "systemctl status sickrage.service" and "journalctl -xe" for details.
nzbuser@nzbsvrv3:/opt/sickrage$ systemctl status sickrage.service
● sickrage.service - SickRage Daemon
   Loaded: loaded (/etc/systemd/system/sickrage.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2017-04-01 22:34:08 BST; 16s ago
  Process: 2216 ExecStart=/usr/bin/python2.7 /opt/sickrage/SickBeard.py -q --daemon --nolaunch --datadir=/opt/sickrage (code=exited, status=217/USER)

Apr 01 22:34:08 nzbsvrv3 systemd[1]: Starting SickRage Daemon...
Apr 01 22:34:08 nzbsvrv3 systemd[1]: sickrage.service: Control process exited, code=exited status=217
Apr 01 22:34:08 nzbsvrv3 systemd[1]: Failed to start SickRage Daemon.
Apr 01 22:34:08 nzbsvrv3 systemd[1]: sickrage.service: Unit entered failed state.
Apr 01 22:34:08 nzbsvrv3 systemd[1]: sickrage.service: Failed with result 'exit-code'.
nzbuser@nzbsvrv3:/opt/sickrage$ journalctl -xe
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit sickrage.service has failed.
--
-- The result is failed.
Apr 01 22:31:44 nzbsvrv3 systemd[1]: sickrage.service: Unit entered failed state.
Apr 01 22:31:44 nzbsvrv3 systemd[1]: sickrage.service: Failed with result 'exit-code'.
Apr 01 22:31:44 nzbsvrv3 sudo[2128]: pam_unix(sudo:session): session closed for user root
Apr 01 22:32:05 nzbsvrv3 sudo[2161]:  nzbuser : TTY=pts/0 ; PWD=/opt/sickrage ; USER=root ; COMMAND=/bin/chown root:root /etc/init/sickrage.conf
Apr 01 22:32:05 nzbsvrv3 sudo[2161]: pam_unix(sudo:session): session opened for user root by nzbuser(uid=0)
Apr 01 22:32:05 nzbsvrv3 sudo[2161]: pam_unix(sudo:session): session closed for user root
Apr 01 22:33:25 nzbsvrv3 sudo[2170]:  nzbuser : TTY=pts/0 ; PWD=/opt/sickrage ; USER=root ; COMMAND=/bin/chmod 644 /etc/init/sickrage.conf
Apr 01 22:33:25 nzbsvrv3 sudo[2170]: pam_unix(sudo:session): session opened for user root by nzbuser(uid=0)
Apr 01 22:33:25 nzbsvrv3 sudo[2170]: pam_unix(sudo:session): session closed for user root
Apr 01 22:34:08 nzbsvrv3 sudo[2185]:  nzbuser : TTY=pts/0 ; PWD=/opt/sickrage ; USER=root ; COMMAND=/usr/sbin/service sickrage start
Apr 01 22:34:08 nzbsvrv3 sudo[2185]: pam_unix(sudo:session): session opened for user root by nzbuser(uid=0)
Apr 01 22:34:08 nzbsvrv3 systemd[2216]: sickrage.service: Failed at step USER spawning /usr/bin/python2.7: No such process
-- Subject: Process /usr/bin/python2.7 could not be executed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- The process /usr/bin/python2.7 could not be executed and failed.
--
-- The error number returned by this process is 3.
Apr 01 22:34:08 nzbsvrv3 systemd[1]: Starting SickRage Daemon...
-- Subject: Unit sickrage.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit sickrage.service has begun starting up.
Apr 01 22:34:08 nzbsvrv3 systemd[1]: sickrage.service: Control process exited, code=exited status=217
Apr 01 22:34:08 nzbsvrv3 systemd[1]: Failed to start SickRage Daemon.
-- Subject: Unit sickrage.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit sickrage.service has failed.
--
-- The result is failed.
Apr 01 22:34:08 nzbsvrv3 systemd[1]: sickrage.service: Unit entered failed state.
Apr 01 22:34:08 nzbsvrv3 systemd[1]: sickrage.service: Failed with result 'exit-code'.
Apr 01 22:34:08 nzbsvrv3 sudo[2185]: pam_unix(sudo:session): session closed for user root
lines 2226-2268/2268 (END)

**Comment by sharkykh** [comment]
Looks like you're trying to run SickRage as root.
This is not recommended..

Also, just so I could see what's the problem,
run SickRage normally, without the service:
```
/usr/bin/python2.7 /opt/sickrage/SickBeard.py --nolaunch --datadir=/opt/sickrage
```

**Comment by vbigchris** [comment]
it should have been running as a user nzbuser 

here is the output from the last command


nzbuser@nzbsvrv3:/opt/sickrage$
nzbuser@nzbsvrv3:/opt/sickrage$ /usr/bin/python2.7 /opt/sickrage/SickBeard.py --nolaunch --datadir=/opt/sickrage
22:47:01 DEBUG::MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
22:47:01 DEBUG::MAIN :: Found codec for 'Show Name: Ep Name'.
22:47:01 DEBUG::MAIN :: Episode has no release group, replacing it with 'RLSGROUP'
22:47:01 DEBUG::MAIN :: formatting pattern: %SN %Sx%0E -> Show Name 2x03
22:47:01 DEBUG::MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
22:47:01 DEBUG::MAIN :: Found codec for 'Show Name: Ep Name'.
22:47:01 DEBUG::MAIN :: formatting pattern: Season %S -> Season 2
22:47:01 DEBUG::MAIN :: Trying to parse Show Name 2x03.ext
22:47:01 DEBUG::MAIN :: Parsed Show Name 2x03.ext into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'fov']]
22:47:01 DEBUG::MAIN :: The name Show Name 2x03.ext parsed into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'fov']]
22:47:02 DEBUG::MAIN :: Checking database structure...sickbeard.db
22:47:02 DEBUG::MAIN :: Database upgrade required: Reset Version
22:47:02 DEBUG::MAIN :: ResetDBVersion upgrade completed
22:47:02 DEBUG::MAIN :: Checking database structure...cache.db
22:47:02 DEBUG::MAIN :: Checking database structure...failed.db
22:47:04 DEBUG::MAIN :: Checking for shows with tvrage id's, since tvrage is gone
22:47:04 DEBUG::MAIN :: Checking for archived episodes not qualified
22:47:04 DEBUG::MAIN :: Checking if we can use git commands: git version
22:47:04 DEBUG::MAIN :: Executing git version with your shell in /opt/sickrage
22:47:04 DEBUG::MAIN :: git version : returned successful
22:47:04 DEBUG::MAIN :: Using: git
22:47:04 DEBUG::MAIN :: Executing git symbolic-ref -q HEAD with your shell in /opt/sickrage
22:47:04 ERROR::MAIN :: [c53b55f] git symbolic-ref -q HEAD returned :
None
22:47:04 DEBUG::MAIN :: Retrieving the last check time from the DB
22:47:04 DEBUG::MAIN :: Loading initial show list
22:47:04 INFO::MAIN :: 77859: Unable to find IMDb show info in the database
22:47:04 INFO::MAIN :: 167211: Unable to find IMDb show info in the database
22:47:04 INFO::MAIN :: Starting SickRage [] using '/opt/sickrage/config.ini'
22:47:04 INFO::TORNADO :: Starting SickRage on https://0.0.0.0:8081/
22:47:04 DEBUG::CHECKVERSION :: Starting new thread: CHECKVERSION
22:47:04 DEBUG::CHECKVERSION :: Executing git symbolic-ref -q HEAD with your shell in /opt/sickrage
22:47:05 INFO::MAIN :: Checking for scene exception updates from http://sickrage.github.io/scene_exceptions/scene_exceptions.json
22:47:05 ERROR::CHECKVERSION :: [c53b55f] git symbolic-ref -q HEAD returned :
None
22:47:05 DEBUG::CHECKVERSION :: Executing git rev-parse HEAD with your shell in /opt/sickrage
22:47:05 DEBUG::CHECKVERSION :: git rev-parse HEAD : returned successful
22:47:05 DEBUG::CHECKVERSION :: Executing git config remote.origin.url https://github.com/SickRage/SickRage.git with your shell in /opt/sickrage
22:47:05 DEBUG::CHECKVERSION :: git config remote.origin.url https://github.com/SickRage/SickRage.git : returned successful
22:47:05 DEBUG::CHECKVERSION :: Executing git fetch origin with your shell in /opt/sickrage
22:47:05 INFO::MAIN :: Checking for XEM scene exception updates for theTVDB
22:47:07 DEBUG::CHECKVERSION :: git fetch origin : returned successful
22:47:07 DEBUG::CHECKVERSION :: Executing git branch --set-upstream-to origin/ with your shell in /opt/sickrage
22:47:07 WARNING::CHECKVERSION :: git branch --set-upstream-to origin/ returned : fatal: could not set upstream of HEAD to origin/ when it does not point to any branch.
22:47:07 DEBUG::CHECKVERSION :: Executing git branch -u origin/ with your shell in /opt/sickrage
22:47:07 WARNING::CHECKVERSION :: git branch -u origin/ returned : fatal: could not set upstream of HEAD to origin/ when it does not point to any branch.
22:47:07 DEBUG::CHECKVERSION :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /opt/sickrage
22:47:07 WARNING::CHECKVERSION :: git rev-parse --verify --quiet "@{upstream}" returned : fatal: HEAD does not point to a branch
22:47:07 DEBUG::CHECKVERSION :: git didn't return newest commit hash
22:47:07 DEBUG::CHECKVERSION :: check_for_new_news: Checking GitHub for latest news.
22:47:11 INFO::MAIN :: Checking for scene exception updates for AniDB
22:47:12 DEBUG::MAIN :: Transaction with 1 queries executed
22:47:12 DEBUG::MAIN :: Updated scene exceptions
22:47:44 INFO::TORNADO :: User logged into the SickRage web interface

**Comment by sharkykh** [comment]
That worked for you. SickRage is running.
I don't use linux so I don't know how to fix the issue with the service, sorry.

In any case, one more set of commands so SickRage can auto-update again:
```
git checkout master
git branch -u origin/master
git reset --hard origin/master
git pull
```

**Comment by vbigchris** [comment]
nzbuser@nzbsvrv3:/opt/sickrage$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
nzbuser@nzbsvrv3:/opt/sickrage$ git branch -u origin/master
Branch master set up to track remote branch master from origin.
nzbuser@nzbsvrv3:/opt/sickrage$ git reset --hard origin/master
HEAD is now at a1f5e67 #3558 - Make sure to check that host starts with http for manage_torrents_url
nzbuser@nzbsvrv3:/opt/sickrage$ git pull
Already up-to-date.
nzbuser@nzbsvrv3:/opt/sickrage$

May thanks

**Comment by sharkykh** [comment]
@vbigchris
If you're still having the issue with the service, please check the user settings like I suggested another user [here](https://github.com/SickRage/SickRage/issues/3593#issuecomment-294247240).
