### ISSUE TITLE
sickbeard-custom: error after automatic update

### ISSUE THREAD

**Issue by mickae1** [SickRage/SickRage#3582]
2017-03-31 17:07:23 INFO     POSTPROCESSOR :: Auto post processing task for /volume1/Download was added to the queue
2017-03-31 17:07:26 INFO     POSTPROCESSOR-AUTO :: Beginning auto post processing task: /volume1/Download
2017-03-31 17:07:26 INFO     POSTPROCESSOR-AUTO :: Processing /volume1/Download
2017-03-31 17:07:29 INFO     POSTPROCESSOR-AUTO :: Successfully processed
2017-03-31 17:07:29 INFO     POSTPROCESSOR-AUTO :: Some items were not processed.
2017-03-31 17:07:29 INFO     POSTPROCESSOR-AUTO :: /volume1/Download/torrents/@eaDir : Hidden folder
2017-03-31 17:07:29 INFO     POSTPROCESSOR-AUTO :: /volume1/Download/@eaDir : Hidden folder
2017-03-31 17:07:29 INFO     POSTPROCESSOR-AUTO :: Auto post processing task for /volume1/Download completed
2017-03-31 17:11:55 INFO     CHECKVERSION :: New update found for SickRage, starting auto-updater ...
2017-03-31 17:11:58 INFO     CHECKVERSION :: Config backup in progress...
2017-03-31 17:12:16 INFO     CHECKVERSION :: Config backup successful, updating...
2017-03-31 17:12:21 INFO     CHECKVERSION :: Update was successful!
2017-03-31 17:12:21 INFO     EVENT-QUEUE :: Aborting all threads
2017-03-31 17:12:21 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2017-03-31 17:12:22 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2017-03-31 17:12:22 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2017-03-31 17:12:22 INFO     EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2017-03-31 17:12:23 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE thread to exit
2017-03-31 17:12:23 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE-DAILY-SEARCH thread to exit
2017-03-31 17:12:23 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2017-03-31 17:12:23 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR-AUTO thread to exit
2017-03-31 17:12:23 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2017-03-31 17:12:23 INFO     EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2017-03-31 17:12:23 INFO     EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2017-03-31 17:12:23 INFO     EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2017-03-31 17:12:23 INFO     EVENT-QUEUE :: Saving all shows to the database
2017-03-31 17:12:23 INFO     EVENT-QUEUE :: Saving config file to disk
2017-03-31 17:12:24 INFO     EVENT-QUEUE :: Shutting down Tornado
2017-03-31 17:12:24 INFO     EVENT-QUEUE :: Restarting SickRage with ['/usr/local/sickbeard-custom/env/bin/python', u'/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py', '--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/', '--nolaunch']

and after nothing .... when I start manually the process I got : 

/usr/local/sickbeard-custom/env/bin/python /usr/local/sickbeard-custom/var/SickBeard/SickBeard.py --config /usr/local/sickbeard-custom/var/config.ini --datadir /usr/local/sickbeard-custom/var/
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py", line 494, in <module>
    SickRage().start()
  File "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py", line 242, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 1100, in initialize
    helpers.manage_torrents_url(reset=True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1897, in manage_torrents_url
    sickbeard.CLIENT_WEB_URLS['torrent'] = ('', torrent_ui_url)[test_exists(torrent_ui_url)]
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1886, in test_exists
    h = requests.head(url)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/api.py", line 93, in head
    return request('head', url, **kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/models.py", line 353, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [ ] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by mickae1** [comment]
I fixed the problem with a new install and a restore of the last backup ....
