### ISSUE TITLE
[APP SUBMITTED]: type object 'GithubException' has no attribute 'RateLimitExceededException'

### ISSUE THREAD

**Issue by BlackOnix80** [SickRage/SickRage#3585]
### INFO
Python Version: **2.7.13 (default, Mar 13 2017, 18:01:51) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-9.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@a1f5e6750493b00b032536c9a4274da57b5b9531
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [a1f5e67] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 286, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 5367, in submit_errors
    submitter_result, issue_id = logger.submit_errors()
  File "/opt/sickrage/sickbeard/logger.py", line 469, in submit_errors
    return Wrapper.instance.submit_errors(*args, **kwargs)
  File "/opt/sickrage/sickbeard/logger.py", line 414, in submit_errors
    except GhEx.RateLimitExceededException as ex:
AttributeError: type object 'GithubException' has no attribute 'RateLimitExceededException'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by BlackOnix80** [comment]
Error you can close it.
