### ISSUE TITLE
Starting up fails with requests.exceptions.InvalidURL

### ISSUE THREAD

**Issue by Keou0007** [SickRage/SickRage#3589]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/origin a1f5e67
OS: Ubuntu 14.04 LTS
What you did: "service sickrage start"
What happened: python exception, start fails. Traceback below
What you expected: sickrage to start. 

used "git checkout v2017.03.24-4"
and starts normally.

Logs:
```
~/.sickrage$ service sickrage start
Starting SickRage
Traceback (most recent call last):
  File "SickBeard.py", line 494, in <module>
    SickRage().start()
  File "SickBeard.py", line 242, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/home/shannon/.sickrage/sickbeard/__init__.py", line 1100, in initialize
    helpers.manage_torrents_url(reset=True)
  File "/home/shannon/.sickrage/sickbeard/helpers.py", line 1897, in manage_torrents_url
    sickbeard.CLIENT_WEB_URLS['torrent'] = ('', torrent_ui_url)[test_exists(torrent_ui_url)]
  File "/home/shannon/.sickrage/sickbeard/helpers.py", line 1886, in test_exists
    h = requests.head(url)
  File "/home/shannon/.sickrage/lib/requests/api.py", line 93, in head
    return request('head', url, **kwargs)
  File "/home/shannon/.sickrage/lib/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/shannon/.sickrage/lib/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/home/shannon/.sickrage/lib/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/shannon/.sickrage/lib/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/home/shannon/.sickrage/lib/requests/models.py", line 356, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL u'http:///': No host supplied

```

**Comment by FlyingPersian** [comment]
Same here. It updates itself and this problem started after an update probably, as nothing else has been changed:

Traceback (most recent call last):
  File "/media/SickRage/SickBeard.py", line 494, in <module>
    SickRage().start()
  File "/media/SickRage/SickBeard.py", line 242, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/media/SickRage/sickbeard/__init__.py", line 1100, in initialize
    helpers.manage_torrents_url(reset=True)
  File "/media/SickRage/sickbeard/helpers.py", line 1897, in manage_torrents_url
    sickbeard.CLIENT_WEB_URLS['torrent'] = ('', torrent_ui_url)[test_exists(torrent_ui_url)]
  File "/media/SickRage/sickbeard/helpers.py", line 1886, in test_exists
    h = requests.head(url)
  File "/media/SickRage/lib/requests/api.py", line 93, in head
    return request('head', url, **kwargs)
  File "/media/SickRage/lib/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/media/SickRage/lib/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/media/SickRage/lib/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/media/SickRage/lib/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/media/SickRage/lib/requests/models.py", line 353, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
/usr/local/etc/rc.d/sickrage: WARNING: failed to start sickrage

**Comment by sharkykh** [comment]
Fixed in the latest update

You need to update manually, https://github.com/SickRage/sickrage.github.io#before-you-open-an-issue

**Comment by sharkykh** [comment]
@Keou0007 Were you able to fix it too?

**Comment by Keou0007** [comment]
I changed back to origin/master and pulled, but no changes came down. So no fix.

**Comment by sharkykh** [comment]
What torrent/nzb client were you using?

**Comment by Keou0007** [comment]
sabnzbdplus 2.0.0RC2 from the ubuntu repo

**Comment by sharkykh** [comment]
Open your config.ini, and look for: `torrent_host`, what's the value?

**Comment by Keou0007** [comment]
http:///

I changed it to http:// but still got the same error

**Comment by sharkykh** [comment]
That's what's causing the problem.
To fix it, shut down SR and change the value to "" (two quotes).
Then try running SR again (on latest commit of course)

**Comment by Keou0007** [comment]
yup that's fixed it
