### ISSUE TITLE
SR interface not loading

### ISSUE THREAD

**Issue by STLawson** [SickRage/SickRage#3605]
When I try to log into SickRage, the login page looks fine, but as soon as I hit the login button, I get an error that says the following (username, password, ip address change for privacy/security):

`Error

u'result'

Traceback

Traceback (most recent call last): 
File "C:\SickRage\lib\tornado\web.py", line 1467, in _execute result = method(*self.path_args, **self.path_kwargs) 
File "C:\SickRage\sickbeard\webserve.py", line 315, in post notifiers.notify_login(self.request.remote_ip) 
File "C:\SickRage\sickbeard\notifiers\__init__.py", line 116, in notify_login n.notify_login(ipaddress) 
File "C:\SickRage\sickbeard\notifiers\kodi.py", line 542, in notify_login self._notify_kodi(update_text.format(ipaddress), title) 
File "C:\SickRage\sickbeard\notifiers\kodi.py", line 134, in _notify_kodi kodiapi = self._get_kodi_version(curHost, username, password, dest_app) 
File "C:\SickRage\sickbeard\notifiers\kodi.py", line 87, in _get_kodi_version return result["result"]["version"] 
KeyError: u'result' 

Request Info

body: username=********&password=********&remember_me=1&submit=Login
files: {}
protocol: http
connection: 
body_arguments: {'username': ['********'], 'remember_me': ['1'], 'password': ['********'], 'submit': ['Login']}
uri: /login/?next=%2Ferrorlogs%2F
query_arguments: {'next': ['/errorlogs/']}
_start_time: 1491523766.68
headers: Origin: http://myaddress:8081 Content-Length: 63 Accept-Language: en-US,en;q=0.8 Accept-Encoding: gzip, deflate Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8 Upgrade-Insecure-Requests: 1 Host: myaddress:8081 Referer: http://myaddress:8081/login/?next=%2Ferrorlogs%2F Cache-Control: max-age=0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36 Content-Type: application/x-www-form-urlencoded 
host: myaddress:8081
version: HTTP/1.1
arguments: {'username': ['********'], 'remember_me': ['1'], 'password': ['********'], 'submit': ['Login'], 'next': ['/errorlogs/']}
_finish_time: None
query: next=%2Ferrorlogs%2F
path: /login/
method: POST
remote_ip: myipaddress

View Log(Errors)`

Any thoughts, recommendations? Is my installation borked and needs to be wiped and reinstalled? Thanks in advance for any help.

**Comment by STLawson** [comment]
Well, apparently the problem fixed itself. I didn't do anything with it, it just works now.
