### ISSUE TITLE
Can't start sickrage process - OverflowError

### ISSUE THREAD

**Issue by jfnz** [SickRage/SickRage#3608]
Branch/Commit: Unknown (lastest probably?)
OS: Ubuntu 16.10
What you did: Nothing
What happened: Sickrage just stopped working, had been working fine for months
What you expected: N/A
Logs:
```
root@ubuntu:~# systemctl status sickrage.service
● sickrage.service - LSB: starts instance of SickRage
   Loaded: loaded (/etc/init.d/sickrage; generated; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2017-04-07 20:03:25 PDT; 18s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 5120 ExecStart=/etc/init.d/sickrage start (code=exited, status=1/FAILURE)

root@ubuntu:~# journalctl -xe
Apr 07 20:06:00 ubuntu kernel: raid6: using avx2x2 recovery algorithm
Apr 07 20:06:00 ubuntu kernel: xor: automatically using best checksumming function: avx
Apr 07 20:06:00 ubuntu kernel: Btrfs loaded, crc32c=crc32c-intel
Apr 07 20:06:00 ubuntu os-prober[13390]: debug: /dev/sda2: DOS extended partition; skipping
Apr 07 20:06:00 ubuntu os-prober[13398]: debug: /dev/sda5: is active swap
Apr 07 20:06:11 ubuntu os-prober[20026]: debug: /dev/sda2: DOS extended partition; skipping
Apr 07 20:06:11 ubuntu os-prober[20034]: debug: /dev/sda5: is active swap
Apr 07 20:06:13 ubuntu os-prober[21020]: debug: /dev/sda2: DOS extended partition; skipping
Apr 07 20:06:13 ubuntu os-prober[21028]: debug: /dev/sda5: is active swap
Apr 07 20:06:31 ubuntu systemd[1]: Starting LSB: starts instance of SickRage...
-- Subject: Unit sickrage.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit sickrage.service has begun starting up.
Apr 07 20:06:31 ubuntu sickrage[21075]: Starting SickRage
Apr 07 20:06:33 ubuntu sickrage[21075]: Traceback (most recent call last):
Apr 07 20:06:33 ubuntu sickrage[21075]:   File "SickBeard.py", line 494, in <module>
Apr 07 20:06:33 ubuntu sickrage[21075]:     SickRage().start()
Apr 07 20:06:33 ubuntu sickrage[21075]:   File "SickBeard.py", line 242, in start
Apr 07 20:06:33 ubuntu sickrage[21075]:     sickbeard.initialize(consoleLogging=self.console_logging)
Apr 07 20:06:33 ubuntu sickrage[21075]:   File "/home/media/.sickrage/sickbeard/__init__.py", line 1581, in initialize
Apr 07 20:06:33 ubuntu sickrage[21075]:     update_interval = datetime.timedelta(minutes=BACKLOG_FREQUENCY)
Apr 07 20:06:33 ubuntu sickrage[21075]: OverflowError: normalized days too large to fit in a C int
Apr 07 20:06:33 ubuntu systemd[1]: sickrage.service: Control process exited, code=exited status=1
Apr 07 20:06:33 ubuntu systemd[1]: Failed to start LSB: starts instance of SickRage.
-- Subject: Unit sickrage.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit sickrage.service has failed.
--
-- The result is failed.
Apr 07 20:06:33 ubuntu systemd[1]: sickrage.service: Unit entered failed state.
Apr 07 20:06:33 ubuntu systemd[1]: sickrage.service: Failed with result 'exit-code'.

Last items in sickrage log file:

2017-04-05 22:34:26 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2017-04-05 22:34:35 INFO     MAIN :: Signal 15 caught, saving and exiting...
2017-04-05 22:34:35 INFO     EVENT-QUEUE :: Aborting all threads
2017-04-05 22:34:35 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2017-04-05 22:34:36 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2017-04-05 22:34:36 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2017-04-05 22:34:36 INFO     EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2017-04-05 22:34:36 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE-REFRESH thread to exit
2017-04-05 22:34:36 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE-DAILY-SEARCH thread to exit
2017-04-05 22:34:36 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2017-04-05 22:34:36 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR-AUTO thread to exit
2017-04-05 22:34:36 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2017-04-05 22:34:36 INFO     EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2017-04-05 22:34:36 INFO     EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2017-04-05 22:34:36 INFO     EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2017-04-05 22:34:36 INFO     EVENT-QUEUE :: Saving all shows to the database
2017-04-05 22:34:36 INFO     EVENT-QUEUE :: Saving config file to disk
2017-04-05 22:34:36 INFO     EVENT-QUEUE :: Shutting down Tornado


```

**Comment by jfnz** [comment]
Nevermind, solved it. Found I had set backlog search to 99999999999 days to stop it going through and trying to get everything I'm missing. Fixed by dropping this down to less nines :)
