### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'find_parent'

### ISSUE THREAD

**Issue by cooleo007** [SickRage/SickRage#3613]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.3-rosa**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b3dad8eec3e238b1cadc809acf8e0e26deb9eb3
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-72108 :: [ilCorsaroNero] :: [4b3dad8] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/home/leo/.sickrage/sickbeard/providers/ilcorsaronero.py", line 249, in search
    torrent_table = html.find('tr', class_='bordo').find_parent("table")
AttributeError: 'NoneType' object has no attribute 'find_parent'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by cooleo007** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.3-rosa**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b3dad8eec3e238b1cadc809acf8e0e26deb9eb3
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-281053 :: [ilCorsaroNero] :: [4b3dad8] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/home/leo/.sickrage/sickbeard/providers/ilcorsaronero.py", line 249, in search
    torrent_table = html.find('tr', class_='bordo').find_parent("table")
AttributeError: 'NoneType' object has no attribute 'find_parent'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by cooleo007** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.3-rosa**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b3dad8eec3e238b1cadc809acf8e0e26deb9eb3
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-279121 :: [ilCorsaroNero] :: [4b3dad8] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/home/leo/.sickrage/sickbeard/providers/ilcorsaronero.py", line 249, in search
    torrent_table = html.find('tr', class_='bordo').find_parent("table")
AttributeError: 'NoneType' object has no attribute 'find_parent'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by cooleo007** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.3-rosa**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b3dad8eec3e238b1cadc809acf8e0e26deb9eb3
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-78804 :: [ilCorsaroNero] :: [4b3dad8] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/home/leo/.sickrage/sickbeard/providers/ilcorsaronero.py", line 249, in search
    torrent_table = html.find('tr', class_='bordo').find_parent("table")
AttributeError: 'NoneType' object has no attribute 'find_parent'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by cooleo007** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.3-rosa**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b3dad8eec3e238b1cadc809acf8e0e26deb9eb3
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-264108 :: [ilCorsaroNero] :: [4b3dad8] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/home/leo/.sickrage/sickbeard/providers/ilcorsaronero.py", line 249, in search
    torrent_table = html.find('tr', class_='bordo').find_parent("table")
AttributeError: 'NoneType' object has no attribute 'find_parent'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by cooleo007** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.3-rosa**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b3dad8eec3e238b1cadc809acf8e0e26deb9eb3
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-80379 :: [ilCorsaroNero] :: [4b3dad8] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/home/leo/.sickrage/sickbeard/providers/ilcorsaronero.py", line 249, in search
    torrent_table = html.find('tr', class_='bordo').find_parent("table")
AttributeError: 'NoneType' object has no attribute 'find_parent'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
