### ISSUE TITLE
Sickrage doesn't restart (working fine for a while since this morning)

### ISSUE THREAD

**Issue by kgaut** [SickRage/SickRage#3644]
# Branch/Commit: 
Master / HEAD

# OS
Raspbian on RPi3

# What you did: 
After rebooting sickrage from UI, I wasn't able to access to webui. I ssh'd to the RPi 3 and tried to manually restart the service with : 
```
sudo service sickrage restart
```
Here's the output : 
```
Job for sickrage.service failed. See 'systemctl status sickrage.service' and 'journalctl -xn' for details.
```

`systemctl status sickrage.service` give me : 
```
● sickrage.service - LSB: starts instance of SickRage
   Loaded: loaded (/etc/init.d/sickrage)
   Active: failed (Result: exit-code) since jeu. 2017-04-20 12:12:59 CEST; 20s ago
  Process: 1245 ExecStart=/etc/init.d/sickrage start (code=exited, status=1/FAILURE)
```
I tried to manually update my git local copy, replace the init.ubuntu in case it was updated.

I also tried to manually start sickrage with : `python /opt/sickrage/SickBeard.py` : 
```
Traceback (most recent call last):
  File "/opt/sickrage/SickBeard.py", line 66, in <module>
    import sickbeard
  File "/opt/sickrage/sickbeard/__init__.py", line 43, in <module>
    from sickbeard.indexers import indexer_api
  File "/opt/sickrage/sickbeard/indexers/__init__.py", line 21, in <module>
    from . import indexer_api
  File "/opt/sickrage/sickbeard/indexers/indexer_api.py", line 26, in <module>
    from indexer_config import initConfig
  File "/opt/sickrage/sickbeard/indexers/indexer_config.py", line 3, in <module>
    from tvdb_api.tvdb_api import Tvdb
  File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 24, in <module>
    import requests
  File "/opt/sickrage/lib/requests/__init__.py", line 63, in <module>
    from . import utils
  File "/opt/sickrage/lib/requests/utils.py", line 24, in <module>
    from ._internal_utils import to_native_string
  File "/opt/sickrage/lib/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/opt/sickrage/lib/requests/compat.py", line 46, in <module>
    from .packages.urllib3.packages.ordered_dict import OrderedDict
ValueError: bad marshal data (string ref out of range)
```

**Comment by sharkykh** [comment]
This seems to be an issue with a corrupt compiled python module/`.pyc` file.
Try removing all of the compiled files in the SickRage directory:
`find . -name "*.pyc" -type f -delete` ([source](https://askubuntu.com/a/377442))

**Comment by kgaut** [comment]
That totally did the trick ! 

Thank you very much !
