### ISSUE TITLE
[Error] UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' [...] ordinal not in range(128)

### ISSUE THREAD

**Issue by Rokys** [SickRage/SickRage#3675]
Branch: master
Commit: 558cd35a9c7dee197cced35a0db9361de1c41ca3
Version: v2017.04.26-1
Database Version: 44.0
Versão do Python: 2.7.13 (default, Feb 11 2017, 10:44:41) [GCC 6.3.0]
Versão SSL: OpenSSL 1.0.2k 26 Jan 2017
SO: Linux-3.2.40-armv7l-with-debian-7.11

What you did: Only noticed the pattern today, but after moving my (previously sickbeard managed) files to a Lenovo ix4-300d, and mass-adding the tv shows, a couple of them lacked posters on Sickrage WebUI.

Today I noticed that only the tv shows with non-standard ASCII characters in path have issues.

I tried changing the directory name to use only standard ascii characters, deleting all nfo and similar files, deleting the show from database (tested with "Homeland - Segurança Nacional"), and re-adding it. Ended with proper metada files being generated (nfo's, thumb, posters, xml, etc) as expected, but still no Poster image in SickRage.

Logs:

2017-04-26 22:59:21 INFO Thread-14 :: Checking for updates using GIT
AA UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 42: ordinal not in range(128)
AA nfo_file = io.open(nfo_file_path, 'wb')
AA File "/mnt/pools/A/A0/.Apps/SickRage/sickbeard/metadata/generic.py", line 463, in write_ep_file
AA return self.write_ep_file(ep_obj)
AA File "/mnt/pools/A/A0/.Apps/SickRage/sickbeard/metadata/generic.py", line 265, in create_episode_metadata
AA result = cur_provider.create_episode_metadata(self) or result
AA File "/mnt/pools/A/A0/.Apps/SickRage/sickbeard/tv.py", line 1845, in createNFO
AA self.createNFO()
AA File "/mnt/pools/A/A0/.Apps/SickRage/sickbeard/tv.py", line 1834, in createMetaFiles
AA rootEp.createMetaFiles()
AA File "/mnt/pools/A/A0/.Apps/SickRage/sickbeard/tv.py", line 754, in makeEpFromFile
AA curEpisode = self.makeEpFromFile(media_file)
AA File "/mnt/pools/A/A0/.Apps/SickRage/sickbeard/tv.py", line 422, in loadEpisodesFromDir
AA self.show.loadEpisodesFromDir()
AA File "/mnt/pools/A/A0/.Apps/SickRage/sickbeard/show_queue.py", line 495, in run
AA UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 42: ordinal not in range(128)
AA nfo_file = io.open(nfo_file_path, 'wb')
AA File "/mnt/pools/A/A0/.Apps/SickRage/sickbeard/metadata/generic.py", line 463, in write_ep_file
AA return self.write_ep_file(ep_obj)
AA File "/mnt/pools/A/A0/.Apps/SickRage/sickbeard/metadata/generic.py", line 265, in create_episode_metadata
AA result = cur_provider.create_episode_metadata(self) or result
AA File "/mnt/pools/A/A0/.Apps/SickRage/sickbeard/tv.py", line 1845, in createNFO
AA self.createNFO()
AA File "/mnt/pools/A/A0/.Apps/SickRage/sickbeard/tv.py", line 1834, in createMetaFiles
AA rootEp.createMetaFiles()
AA File "/mnt/pools/A/A0/.Apps/SickRage/sickbeard/tv.py", line 754, in makeEpFromFile
AA curEpisode = self.makeEpFromFile(media_file)
AA File "/mnt/pools/A/A0/.Apps/SickRage/sickbeard/tv.py", line 422, in loadEpisodesFromDir
AA self.show.loadEpisodesFromDir()
AA File "/mnt/pools/A/A0/.Apps/SickRage/sickbeard/show_queue.py", line 495, in run
AA Traceback (most recent call last):
2017-04-26 22:58:30 ERROR SHOWQUEUE-ADD :: [558cd35] Error searching dir for episodes: 'ascii' codec can't encode character u'\xe7' in position 42: ordinal not in range(128)
2017-04-26 22:57:03 INFO SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
2017-04-26 22:57:01 INFO SHOWQUEUE-ADD :: 247897: Unable to find the show in the database
2017-04-26 22:56:59 INFO SHOWQUEUE-ADD :: theTVDB: {'useZip': True, 'apikey': 'F9C450E78D99172E', 'cache': u'/mnt/pools/A/A0/.Apps/SickRage/cache/indexers/theTVDB', 'language': 'pt'}
2017-04-26 22:56:59 INFO SHOWQUEUE-ADD :: Starting to add show by ShowDir: /mnt/pools/A/A0/HomeMedia/tvseries/Segurança Nacional
2017-04-26 22:56:40 WARNING Thread-15 :: There was an error parsing your existing metadata file: '/mnt/pools/A/A0/HomeMedia/documentarios/Teste o Seu Cérebro/tvshow.nfo' error: ascii : /mnt/pools/A/A0/HomeMedia/documentarios/Teste o Seu Cérebro/tvshow.nfo : error 53 : error 54 : ordinal not in range(128)
2017-04-26 22:56:40 WARNING Thread-15 :: There was an error parsing your existing metadata file: '/mnt/pools/A/A0/HomeMedia/documentarios/Teste o Seu Cérebro/tvshow.nfo' error: ascii : /mnt/pools/A/A0/HomeMedia/documentarios/Teste o Seu Cérebro/tvshow.nfo : error 53 : error 54 : ordinal not in range(128)
2017-04-26 22:56:40 INFO Thread-15 :: Invalid info in tvshow.nfo (missing name or id): Naruto None None
2017-04-26 22:56:40 INFO Thread-15 :: Invalid info in tvshow.nfo (missing name or id): Naruto None None
2017-04-26 22:56:40 WARNING Thread-15 :: There was an error parsing your existing metadata file: '/mnt/pools/A/A0/HomeMedia/tvseries/Caçadores de Dragões/tvshow.nfo' error: ascii : /mnt/pools/A/A0/HomeMedia/tvseries/Caçadores de Dragões/tvshow.nfo : error 37 : error 38 : ordinal not in range(128)
2017-04-26 22:56:40 WARNING Thread-15 :: There was an error parsing your existing metadata file: '/mnt/pools/A/A0/HomeMedia/tvseries/Caçadores de Dragões/tvshow.nfo' error: ascii : /mnt/pools/A/A0/HomeMedia/tvseries/Caçadores de Dragões/tvshow.nfo : error 37 : error 38 : ordinal not in range(128)
2017-04-26 22:56:40 WARNING Thread-15 :: There was an error parsing your existing metadata file: '/mnt/pools/A/A0/HomeMedia/tvseries/Martim Manhã/tvshow.nfo' error: ascii : /mnt/pools/A/A0/HomeMedia/tvseries/Martim Manhã/tvshow.nfo : error 46 : error 47 : ordinal not in range(128)
2017-04-26 22:56:40 WARNING Thread-15 :: There was an error parsing your existing metadata file: '/mnt/pools/A/A0/HomeMedia/tvseries/Martim Manhã/tvshow.nfo' error: ascii : /mnt/pools/A/A0/HomeMedia/tvseries/Martim Manhã/tvshow.nfo : error 46 : error 47 : ordinal not in range(128)
2017-04-26 22:56:40 WARNING Thread-15 :: There was an error parsing your existing metadata file: '/mnt/pools/A/A0/HomeMedia/tvseries/Segurança Nacional/tvshow.nfo' error: ascii : /mnt/pools/A/A0/HomeMedia/tvseries/Segurança Nacional/tvshow.nfo : error 42 : error 43 : ordinal not in range(128)
2017-04-26 22:56:40 WARNING Thread-15 :: There was an error parsing your existing metadata file: '/mnt/pools/A/A0/HomeMedia/tvseries/Segurança Nacional/tvshow.nfo' error: ascii : /mnt/pools/A/A0/HomeMedia/tvseries/Segurança Nacional/tvshow.nfo : error 42 : error 43 : ordinal not in range(128)
2017-04-26 22:56:34 INFO SHOWQUEUE-REMOVE-SHOW :: Removing Homeland - Segurança Nacional
```

**Comment by sharkykh** [comment]
@Rokys 
What is your locale? (you can check it under http://localhost8081/config/)

**Comment by Rokys** [comment]
@sharkykh 
My googling skills might just have failed me on this occasion. The info I pasted was all the info provided by that specific page. The locale indication was not present.

After some digging, and variable exporting, it now shows pt_BR.UTF-8 as language. In my case it should be pt_PT, but Lenovo's firmware only has a couple of locales built/configure, and I don't want to mess with it too much, so I switched to pt_BR which should close enough.

But after once again deleting the show, the nfo's and re-adding the show, I still get the no poster in GUI issue. 

Since running Sickrage on Lenovo's ix4-300d requires some custom scripting, on the Lenovo's linux-based OS firmware, could this be some python/UTF encoding related dependency missing?

To be honest, the issue is (I believe) purely cosmetic, as it gets the episodes anyway, the nfos are (apparentely) generated and usable. So... l'd consider this a low priority issue...

**Comment by sharkykh** [comment]
@Rokys 
Probably not a dependency issue, since most of the dependencies we use are in SickRage (/libs folder).
Do you still get an error in your logs after fixing the locale issue or not?
Please enable debug logs in **General Configuration > Advanced Settings > Enable debug logs**, then force a full update of the show.
Then go to http://localhost:8081/errorlogs/viewlog/?min_level=10 and search for the shows name, see if there is something about the posters of the show.
You should also post the logs of it here.

Ping @miigotu: I don't really know much about this. Maybe you could shed some light on the issue?

**Comment by miigotu** [comment]
You should set your locale to *.utf-8

**Comment by sharkykh** [comment]
@miigotu 
> After some digging, and variable exporting, it now shows pt_BR.UTF-8 as language.

**Comment by miigotu** [comment]
After setting the locale correctly, stop sickrage, delete the cache folder and any images in the show folder, restart the machine, and force a full update on the show

**Comment by Rokys** [comment]
my apologies for leaving this "hanging". I believe I did just that, and still didn't work, but then work caught up with  me and I was unable to post a proper "feedback". I'll try to do it properly once again this next couple of days, and report back.
