### ISSUE TITLE
Unicode equal comparison failed to convert both arguments to Unicode

### ISSUE THREAD

**Issue by googley** [SickRage/SickRage#3698]
Branch/Commit: master/558cd35a9c7dee197cced35a0db9361de1c41ca3
OS: Ubuntu 16.04
What you did: start the server
What happened: Error in logging
What you expected: No error in logging
Logs:
```shell
$ /var/lib/sickrage/src/SickBeard.py  --config /var/lib/sickrage/.sickrage/config.ini -p 8081
/usr/lib/python2.7/urllib.py:1299: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/var/lib/sickrage/src/sickbeard/logger.py", line 93, in format
    censored = censored | {quote(item) for item in censored}
  File "/var/lib/sickrage/src/sickbeard/logger.py", line 93, in <setcomp>
    censored = censored | {quote(item) for item in censored}
  File "/usr/lib/python2.7/urllib.py", line 1299, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe9'
Logged from file logger.py, line 252
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/var/lib/sickrage/src/sickbeard/logger.py", line 93, in format
    censored = censored | {quote(item) for item in censored}
  File "/var/lib/sickrage/src/sickbeard/logger.py", line 93, in <setcomp>
    censored = censored | {quote(item) for item in censored}
  File "/usr/lib/python2.7/urllib.py", line 1299, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe9'
```

**Comment by sharkykh** [comment]
@googley What is your locale? (you can check it under http://localhost8081/config/)

**Comment by googley** [comment]
The problem was fixed mysteriously 👍
