### ISSUE TITLE
Any torrent fails with bdecode error

### ISSUE THREAD

**Issue by claunia** [SickRage/SickRage#3703]
Hi,

Any torrent fails to download with bdecode error. Failure is the same with Transmission or QBitTorrent. Bot are checked to work.

Branch/Commit: 9.0.17 master
OS: Arch Linux
What you did: Add a show
What happened: Episodes snatched, not added to torrent app
What you expected: Episodes snatched and added to torrent app
Logs:
```
2017-05-03 17:04:20 ERROR::SEARCHQUEUE-BACKLOG-312505::qbittorrent: Failed Sending Torrent
Traceback (most recent call last):
  File "/opt/sickrage/sickrage/clients/__init__.py", line 310, in sendTORRENT
    result = self._get_torrent_hash(result)
  File "/opt/sickrage/sickrage/clients/__init__.py", line 280, in _get_torrent_hash
    torrent_bdecode = bdecode(result.content)
  File "/usr/lib/python2.7/site-packages/bencode/__init__.py", line 68, in bdecode
    raise BTFailure("not a valid bencoded string")
BTFailure: not a valid bencoded string
```

**Comment by sharkykh** [comment]
@claunia You're using another fork of SickRage that's not ours and we don't support it.

**Comment by claunia** [comment]
@sharkykh I have been lied then, sorry for the inconveniences. Ofc problem solved moving to this project.

**Comment by HLFH** [comment]
Same issue with this official SickRage.
