### ISSUE TITLE
[APP SUBMITTED]: Invalid line at line "1169".

### ISSUE THREAD

**Issue by friderichsen** [SickRage/SickRage#3801]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.102-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
Thread-17 :: [10a0c30] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 4891, in saveProviders
    sickbeard.save_config()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 1761, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8')
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/configobj.py", line 1302, in _load
    raise error
ParseError: Invalid line at line "1169".

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
stop sickrage and open your config.ini, you have bad data at line 1169. fix the data and start SR again.
