### ISSUE TITLE
qnap rtorrent - Error: Unable to connect to rTorrent

### ISSUE THREAD

**Issue by oodonnell** [SickRage/SickRage#3838]
Branch/Commit: Master
OS: Qnap QTS 4.3.3
What you did: changed torrent client to rtorrent 
What happened: I have put in all my details and have been searching google for answers, trawling through forums and I even asked in rtorrent community forum but they didn't know as the client is working perfect except connecting to sickrage.

I have tried using multiple suggestions such as https://localhost/rutorrent/plugins/httprpc/action.php I've went through sftp and found the action php, and to be fair it doesnt give the error right away but inevitably comes back as - "Error: Unable to connect to rTorrent", tried SSL enabled/disabled, basic/digest and none. tried restarting everything 
What you expected: to be able to use my torrent client

I pasted a log below but i dont even know if i have the setup correct.. ive searched so much I am tired of searching how to fix this

![1](https://cloud.githubusercontent.com/assets/10993752/26803911/f126bac6-4a3d-11e7-8805-578e8378ed8b.PNG)
![2](https://cloud.githubusercontent.com/assets/10993752/26803956/2757f380-4a3e-11e7-96f8-fd96bc3e912d.PNG)

Logs:
```
DEBUG    SEARCHQUEUE-MANUAL-273181 :: Calling rTorrent Client
2017-06-05 22:20:28 DEBUG    SEARCHQUEUE-MANUAL-273181 :: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/search_queue.py", line 182, in run
    self.success = search.snatchEpisode(searchResult[0])
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/search.py", line 136, in snatchEpisode
    dlResult = client.sendTORRENT(result)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/clients/generic.py", line 248, in sendTORRENT
    if not (self.auth or self._get_auth()):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/clients/rtorrent_client.py", line 58, in _get_auth
    self.auth = RTorrent(self.host, None, None, True)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/__init__.py", line 84, in __init__
    self._verify_conn()
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/__init__.py", line 123, in _verify_conn
    assert "system.client_version" in self._get_rpc_methods(
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/__init__.py", line 162, in _get_rpc_methods
    return(self._rpc_methods or self._update_rpc_methods())
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/__init__.py", line 151, in _update_rpc_methods
    self._rpc_methods = self._get_conn().system.listMethods()
  File "/opt/lib/python2.7/xmlrpclib.py", line 1243, in __call__
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 188, in __request
    verbose=self.__verbose
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 98, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/rtorrent/lib/xmlrpc/scgi.py", line 121, in single_request
    sock.connect(addrinfo[0][4])
  File "/opt/lib/python2.7/socket.py", line 228, in meth
error: [Errno 111] Connection refused
```

**Comment by oodonnell** [comment]
192.168.0.4:6009/ui/rtorrent/plugins/httprpc/action.php


This is what you use for QNAP - 4.3.3 QTS updated.

please close and resolve this thread, sorry for wasting time, 25 hours i had this issue, and the minute i post about it i resolve it.. but incase it helps others it may be useful to leave it here for the Qnap users ?

**Comment by miigotu** [comment]
RTorrent settings a not right, you have to get the rpc working first before setting it up inside SR.

Possibly Helpful Reference: http://elektito.com/2016/02/10/rtorrent-xmlrpc/

Google is your friend.

**Comment by oodonnell** [comment]
I did google it lots in my defence, I would never just post stuff without researching it first. The RPC is working as otherwise the web UI wouldnt be functioning was my understanding after reading a good few help forums.

I use a qnap so don't have a rtorrent.rc file, I done a search using filezilla sftp for it in depth and came up with nothing, I think the config file is rtorrent.sh but there is a SCGI line in this.  

I would love to get this working I just can't figure it out, for now I have switched back to blackhole and it puts it into rtorrent watch folder, which in essence is okay but since I also use couchpotato and these use seperate folders ideally I would like to be able to use the torrent client and not blackhole

**Comment by sharkykh** [comment]
I don't have QNAP or use rTorrent.
Some people suggest trying `http://localhost:6009`. See if that works?

**Comment by oodonnell** [comment]
fantastic

Yes I am using the qpkg from qnap.net.pl as that works on the new QTS firmware build for the Qnap NAS I have, and had also asked on their forums in regards to that and another thing, I trawled through config files (I will admit im not a coder, nor have i a great deal of experience) but after using 

scgi://localhost:19000/

it is now 

" Success: Connected and Authenticated "

Thank you for the help, had spent hours trying to fix that
