### ISSUE TITLE
Doesn't start after updating to current master

### ISSUE THREAD

**Issue by mdmbc** [SickRage/SickRage#3842]
Updated last night.. Won't start now. I was quite a few commits behind, so not too sure which one caused it. 

Traceback (most recent call last):
  File "SickBeard.py", line 545, in <module>
    SickRage().start()
  File "SickBeard.py", line 247, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/media/ext/SickRage/sickbeard/__init__.py", line 1551, in initialize
    versionChecker.CheckVersion(),
  File "/media/ext/SickRage/sickbeard/versionChecker.py", line 53, in __init__
    self.updater = GitUpdateManager()
  File "/media/ext/SickRage/sickbeard/versionChecker.py", line 347, in __init__
    self._git_path = self._find_working_git()
  File "/media/ext/SickRage/sickbeard/versionChecker.py", line 383, in _find_working_git
    stdout_, stderr_, exit_status = self._run_git(main_git, test_cmd)
  File "/media/ext/SickRage/sickbeard/versionChecker.py", line 453, in _run_git
    if 'stash' in output:
TypeError: argument of type 'NoneType' is not iterable

**Comment by sharkykh** [comment]
@mdmbc Can you try:
```
python SickBeard.py --force-update
```

**Comment by mdmbc** [comment]
That did it. It looks like I had a sickrage instance that wouldn't close when killed. Sorry for the non-issue, and thanks for the quick help!
