### ISSUE TITLE
TORNADO :: [96b53de] API :: error 6

### ISSUE THREAD

**Issue by sethrd** [SickRage/SickRage#3892]
Branch: master
Commit: 96b53dee713dc35ebf295d0f37a67b2a36fb4ea3
Version: v2017.06.05-1
Database Version: 44.0
OS: CentOS 7 x64_86
What you did: Every hour, this shows in logs
What happened: See logs
What you expected: Nothing
Logs:

```
2017-06-28 13:00:00 DEBUG    TORNADO :: API :: 172.18.0.3 - gave correct API KEY. ACCESS GRANTED
2017-06-28 13:00:00 DEBUG    TORNADO :: API :: all args: '()'
2017-06-28 13:00:00 DEBUG    TORNADO :: API :: all kwargs: '{'cmd': 'show.stats', 'tvdbid': '275274'}'
2017-06-28 13:00:00 DEBUG    TORNADO :: API :: show.stats: cur_kwargs {'tvdbid': '275274'}
2017-06-28 13:00:00 DEBUG    TORNADO :: API :: 172.18.0.3 - gave correct API KEY. ACCESS GRANTED
2017-06-28 13:00:00 DEBUG    TORNADO :: API :: all args: '()'
2017-06-28 13:00:00 DEBUG    TORNADO :: API :: all kwargs: '{'cmd': 'show.stats', 'tvdbid': '121361'}'
2017-06-28 13:00:00 DEBUG    TORNADO :: API :: show.stats: cur_kwargs {'tvdbid': '121361'}
2017-06-28 13:00:00 ERROR    TORNADO :: [96b53de] API :: error 6
Traceback (most recent call last):
  File "/apps/sickrage/sickbeard/webapi.py", line 129, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/apps/sickrage/sickbeard/webapi.py", line 201, in call_dispatcher
    cur_out_dict = to_call.run()  # call function and get response
  File "/apps/sickrage/sickbeard/webapi.py", line 2641, in run
    episode_qualities_counts_download[int(row[b"status"])] += 1
KeyError: 6
```

I believe this request is coming from PlexRequest, as that matches the docker IP,  the tvdbid matches shows I have requests through PlexRequest, but the shows have already been added to SickRage and are at 100%. However, every hour, on the hour, the logs are populated with these errors. PlexRequests and Sickrage work well together, other than this.

**Comment by sharkykh** [comment]
That's a bug in the API from the looks of it. I think I traced it [to here](https://github.com/SickRage/SickRage/blob/master/sickbeard/webapi.py#L2638-L2647).
Does that show matching tvdbid 121361 have archived episodes with no quality?

I'll look on it some more later.

**Comment by sethrd** [comment]
Yes, the show with tvdbid 121361 does have 2 episodes that are downloaded, but show as archived and won't change to downloaded, even though the files exist. They do show green though, because files for those episodes do exist.

**Comment by sharkykh** [comment]
1. Episodes marked as archived are basically untracked. You should be able to manually change their status - select them and then choose the new status in the dropdown under the show info box. Then click the button next to it.
2. Green background = Prefered quality, orange background = Allowed quality (changes according to the show's quality settings), this has no connection to whether there's a file or not.

**Comment by sethrd** [comment]
Man, I could have sworn that I tried changing the status on those episodes from archived to the actual quality of the existing files, but that it stayed as archived. Just tried again, and it updated fine. Given that the error happens at the top of the hour, I'll let you know if it pops back up again in ~50 minutes.

**Comment by sethrd** [comment]
Passed the hour, no error was presented. Thanks for the assist! Marking as closed.
