### ISSUE TITLE
Fedora 26 : sickrage won't start (ERROR:Exception in callback)

### ISSUE THREAD

**Issue by didli** [SickRage/SickRage#3981]
Branch/Commit: Master
OS: Fedora 26 x64
Since my upgrade from Fedora 25 to Fedora 26, Sickrage won't start. Systemd service starts just fine, but I can't access sickrage on port 8081 (web page is loading endlessly).
At first, I could see a message in the log stating that the database could not be writable (which I corrected right away) and now I've got this exception and I'm not sure what to do :
A little help please ? Thank you !
Logs:
```
2017-08-11 11:43:56 ERROR    Exception in callback (<socket._socketobject object at 0x7fe348c78210>, <function null_wrapper at 0x7fe34779e2a8>)
Traceback (most recent call last):
  File "/media/Databank/Apps/webserver/sickrage/lib/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/media/Databank/Apps/webserver/sickrage/lib/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/media/Databank/Apps/webserver/sickrage/lib/tornado/netutil.py", line 276, in accept_handler
    callback(connection, address)
  File "/media/Databank/Apps/webserver/sickrage/lib/tornado/tcpserver.py", line 264, in _handle_connection
    do_handshake_on_connect=False)
  File "/media/Databank/Apps/webserver/sickrage/lib/tornado/netutil.py", line 517, in ssl_wrap_socket
    context = ssl_options_to_context(ssl_options)
  File "/media/Databank/Apps/webserver/sickrage/lib/tornado/netutil.py", line 494, in ssl_options_to_context
    context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
SSLError: [SSL: CA_MD_TOO_WEAK] ca md too weak (_ssl.c:2699)
```

**Comment by didli** [comment]
Weird. Since I could also see an SSL error, I've tried to update (again, tried it twice already) my configuration without SSL support, and reverted back to an earlier sickrage version, and this time, it worked. I'm closing this issue since I could get Sickrage to work nonetheless ^^.
