### ISSUE TITLE
Error sending Torrent to Deluge & Submitting error

### ISSUE THREAD

**Issue by bicodegas** [SickRage/SickRage#4020]
Every time I do a manual search and most of the times Sickrage does the automatic search I get this error:

> 2017-09-01 20:29:12 SEARCHQUEUE-MANUAL-71256 :: [d8c2613] Unable to bdecode torrent
> 2017-09-01 20:29:12 SEARCHQUEUE-MANUAL-71256 :: [d8c2613] DelugeD: Failed Sending Torrent

I tried this knowing that the torrent I'm searching is available in several sites.

And when I tried to submit the error above I get another error:

> 2017-09-01 20:31:09 Thread-94 :: [d8c2613] Traceback (most recent call last): 
> File "/home/asensio/.sickrage/sickbeard/logger.py", line 325, in submit_errors
> regex = r'^({0})\s+([A-Z]+)\s+[A-Za-z0-9\-\[\] :]+::\s(?:\[[\w]{7}\]).*$'.format(re.escape(cur_error.time))
> IndexError: tuple index out of range

**Here's my Info:** 
Branch: master
Commit: d8c2613583ce8b321a5adc9ff70c52e830f224a8
Version: v2017.06.05-1
Database Version: 44.0
Python: 2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]
SO: Linux-4.4.0-93-generic-x86_64-with-Ubuntu-14.04-trusty
Torrent Client: Deluge 1.3.15

What you did: Manual Search (but also happens on the automatic search) & Submitting the Error
What happened: from manual search got the error: Unable to bdecode torrent; submitting error/warning: Thread-94 :: Exception generated in issue submitter, please check the log 

**And here are the Logs**:
```
2017-09-01 20:51:10 WARNING  Thread-94 :: Exception generated in issue submitter, please check the log
AA IndexError: tuple index out of range
AA regex = r'^({0})\s+([A-Z]+)\s+[A-Za-z0-9\-\[\] :]+::\s(?:\[[\w]{7}\]).*$'.format(re.escape(cur_error.time))
AA File "/home/*******/.sickrage/sickbeard/logger.py", line 325, in submit_errors
AA Traceback (most recent call last):
AA IndexError: tuple index out of range
AA regex = r'^({0})\s+([A-Z]+)\s+[A-Za-z0-9\-\[\] :]+::\s(?:\[[\w]{7}\]).*$'.format(re.escape(cur_error.time))
AA File "/home/*******/.sickrage/sickbeard/logger.py", line 325, in submit_errors
2017-09-01 20:51:10 ERROR    Thread-94 :: [d8c2613] Traceback (most recent call last):
2017-09-01 20:51:10 DEBUG    Thread-94 :: cur_commit = d8c2613583ce8b321a5adc9ff70c52e830f224a8, newest_commit = d8c2613583ce8b321a5adc9ff70c52e830f224a8, num_commits_behind = 0, num_commits_ahead = 0
2017-09-01 20:51:10 DEBUG    Thread-94 :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2017-09-01 20:51:10 DEBUG    Thread-94 :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /home/*******/.sickrage
2017-09-01 20:51:10 DEBUG    Thread-94 :: git rev-parse --verify --quiet "@{upstream}" : returned successful
2017-09-01 20:51:09 DEBUG    Thread-94 :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /home/*******/.sickrage
2017-09-01 20:51:09 DEBUG    Thread-94 :: git branch --set-upstream-to origin/master : returned successful
2017-09-01 20:51:09 DEBUG    Thread-94 :: Executing git branch --set-upstream-to origin/master with your shell in /home/*******/.sickrage
2017-09-01 20:51:09 DEBUG    Thread-94 :: git fetch origin : returned successful
2017-09-01 20:51:06 DEBUG    Thread-94 :: Executing git fetch origin with your shell in /home/*******/.sickrage
2017-09-01 20:51:06 DEBUG    Thread-94 :: git config remote.origin.url https://github.com/SickRage/SickRage.git : returned successful
2017-09-01 20:51:06 DEBUG    Thread-94 :: Executing git config remote.origin.url https://github.com/SickRage/SickRage.git with your shell in /home/*******/.sickrage
2017-09-01 20:51:06 DEBUG    Thread-94 :: git rev-parse HEAD : returned successful
2017-09-01 20:51:06 DEBUG    Thread-94 :: Executing git rev-parse HEAD with your shell in /home/*******/.sickrage
2017-09-01 20:51:06 DEBUG    Thread-94 :: git symbolic-ref -q HEAD : returned successful
2017-09-01 20:51:05 DEBUG    Thread-94 :: Executing git symbolic-ref -q HEAD with your shell in /home/*******/.sickrage
2017-09-01 20:51:05 DEBUG    Thread-94 :: git symbolic-ref -q HEAD : returned successful
2017-09-01 20:51:05 DEBUG    Thread-94 :: Executing git symbolic-ref -q HEAD with your shell in /home/*******/.sickrage
2017-09-01 20:51:05 DEBUG    Thread-94 :: Using: git
2017-09-01 20:51:05 DEBUG    Thread-94 :: git version : returned successful
2017-09-01 20:51:05 DEBUG    Thread-94 :: Executing git version with your shell in /home/*******/.sickrage
2017-09-01 20:51:05 DEBUG    Thread-94 :: Checking if we can use git commands: git version
AA . Error not a valid bencoded string
AA Release Group: CROOKS
AA Size: -1
AA Name: The.Daily.Show.2017.08.31.Reid.Hoffman.720p.HDTV.x264-CROOKS
AA Quality: 720p HDTV
AA status: 3
AA hastbn: False
AA hasnfo: False
AA airdate: 736572 (datetime.date(2017, 8, 31))
AA subtitles_lastsearch: '0001-01-01 00:00:00'
AA subtitles_searchcount: 0
AA subtitles: u''
AA description: u'Reid Hoffman, entrepreneur & investor.'
AA location: u''
AA u'The Daily Show' - S22E148 - u'Reid Hoffman'
AA Episodes:
AA Extra Info:
2017-09-01 20:47:54 DEBUG    SEARCHQUEUE-MANUAL-71256 :: DelugeD: Exception raised when sending torrent: Speedcd @ https://speed.cd/download.php?torrent=1136672
AA BTFailure: not a valid bencoded string
AA raise BTFailure("not a valid bencoded string")
AA File "/home/*******/.sickrage/lib/bencode/__init__.py", line 68, in bdecode
AA torrent_bdecode = bencode.bdecode(result.content)
AA File "/home/*******/.sickrage/sickbeard/clients/generic.py", line 215, in _get_torrent_hash
AA result = self._get_torrent_hash(result)
AA File "/home/*******/.sickrage/sickbeard/clients/generic.py", line 257, in sendTORRENT
AA Traceback (most recent call last):
2017-09-01 20:47:54 ERROR    SEARCHQUEUE-MANUAL-71256 :: [d8c2613] DelugeD: Failed Sending Torrent
2017-09-01 20:47:54 DEBUG    SEARCHQUEUE-MANUAL-71256 :: Error is: not a valid bencoded string
AA BTFailure: not a valid bencoded string
AA raise BTFailure("not a valid bencoded string")
AA File "/home/*******/.sickrage/lib/bencode/__init__.py", line 68, in bdecode
AA torrent_bdecode = bencode.bdecode(result.content)
AA File "/home/*******/.sickrage/sickbeard/clients/generic.py", line 215, in _get_torrent_hash
AA Traceback (most recent call last):
2017-09-01 20:47:54 ERROR    SEARCHQUEUE-MANUAL-71256 :: [d8c2613] Unable to bdecode torrent
2017-09-01 20:47:54 DEBUG    SEARCHQUEUE-MANUAL-71256 :: Calling DelugeD Client
2017-09-01 20:47:54 DEBUG    SEARCHQUEUE-MANUAL-71256 :: GET URL: https://speed.cd/download.php?torrent=1136672 [Status: 200]
2017-09-01 20:47:54 INFO     SEARCHQUEUE-MANUAL-71256 :: Downloading The.Daily.Show.2017.08.31.Reid.Hoffman.720p.HDTV.x264-CROOKS from Speedcd
2017-09-01 20:47:54 DEBUG    SEARCHQUEUE-MANUAL-71256 :: [Speedcd] :: Checking if we should keep searching after we've found The.Daily.Show.2017.08.31.Reid.Hoffman.720p.HDTV.x264-CROOKS
2017-09-01 20:47:54 DEBUG    SEARCHQUEUE-MANUAL-71256 :: [Speedcd] :: Picked The.Daily.Show.2017.08.31.Reid.Hoffman.720p.HDTV.x264-CROOKS as the best
2017-09-01 20:47:54 INFO     SEARCHQUEUE-MANUAL-71256 :: [Speedcd] :: Quality of The.Daily.Show.2017.08.31.Reid.Hoffman.720p.HDTV.x264-CROOKS is 720p HDTV
2017-09-01 20:47:54 DEBUG    SEARCHQUEUE-MANUAL-71256 :: [Speedcd] :: Picking the best result out of [u'The.Daily.Show.2017.08.31.Reid.Hoffman.720p.HDTV.x264-CROOKS']
2017-09-01 20:47:54 DEBUG    SEARCHQUEUE-MANUAL-71256 :: [Speedcd] :: The highest quality of any match is 720p HDTV
2017-09-01 20:47:54 INFO     SEARCHQUEUE-MANUAL-71256 :: [Speedcd] :: Found result The.Daily.Show.2017.08.31.Reid.Hoffman.720p.HDTV.x264-CROOKS at https://speed.cd/download.php?torrent=1136672
2017-09-01 20:47:54 DEBUG    SEARCHQUEUE-MANUAL-71256 :: [Speedcd] :: Existing episode status is 'Wanted', getting found result for The Daily Show S22E148 with quality 720p HDTV
2017-09-01 20:47:54 DEBUG    SEARCHQUEUE-MANUAL-71256 :: [Speedcd] :: Any,Best = [ SDTV, SD DVD, 720p HDTV, 720p WEB-DL ] [ SDTV, SD DVD ] Found = [ 720p HDTV ]
2017-09-01 20:47:54 DEBUG    SEARCHQUEUE-MANUAL-71256 :: [Speedcd] :: Using cached parse result for: The.Daily.Show.2017.08.31.Reid.Hoffman.720p.HDTV.x264-CROOKS
2017-09-01 20:47:54 INFO     SEARCHQUEUE-MANUAL-71256 :: [Speedcd] :: Performing episode search for The Daily Show
```
Thanks.

**Comment by bicodegas** [comment]
I don't know if the log above shows any errors, but everything seems to be working fine now. 

I'll close this issue (if it ever was one...)
