### ISSUE TITLE
Issue with subtitles downloads

### ISSUE THREAD

**Issue by NunoHiggs** [SickRage/SickRage#4153]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Origin
OS: Linux
What you did: Tried to do a download subtitles
What happened: Error
What you expected: The subtitles downloads
Logs:
```
2017-11-24 16:54:09 FINDSUBTITLES :: [d8c2613] Traceback (most recent call last):
File "/opt/sickrage/sickbeard/subtitles.py", line 257, in download_subtitles
(subtitle.provider_name, subtitle.id, score, user_score), logger.DEBUG)
File "/opt/sickrage/lib/subliminal/providers/legendastv.py", line 113, in id
return '%s-%s' % (self.archive.id, self.name.lower())
File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x82 in position 2: invalid start byte
```

**Comment by nmbchaves** [comment]
Happened to me something similar:

2017-12-07 12:30:48 FINDSUBTITLES :: [d8c2613] Traceback (most recent call last):
File "/opt/sickrage/sickbeard/subtitles.py", line 255, in download_subtitles
hearing_impaired=sickbeard.SUBTITLES_HEARING_IMPAIRED)
File "/opt/sickrage/lib/subliminal/score.py", line 106, in compute_score
matches = subtitle.get_matches(video)
File "/opt/sickrage/lib/subliminal/providers/legendastv.py", line 125, in get_matches
if video.original_series and self.year is None or video.year and video.year == self.year - self.season + 1:
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
