### ISSUE TITLE
After adding Torrent search provider sickrage won't start anymore

### ISSUE THREAD

**Issue by rickbakker** [SickRage/SickRage#4311]
Hi guys,

Tried to fix this myself but i couldnt get it to work anymore. When i want to start sickrage, it just exists with a error. This happend after i added a torrent searchprovider. So the first thing i tried was so backup my config file, delete that and see if sickrage would start again. It did. So something is wrong with my config, but it's hard for me to pin point what that would be. I know that i added a new torrent searchprovider before this all happend. This is the error i get when i want to start the sickrage service:

-- Unit sickrage.service has begun starting up.
Feb 12 22:44:25 Akira sickrage[26499]: Starting SickRage
Feb 12 22:44:27 Akira sickrage[26499]: Traceback (most recent call last):
Feb 12 22:44:27 Akira sickrage[26499]:   File "SickBeard.py", line 548, in <module>
Feb 12 22:44:27 Akira sickrage[26499]:     SickRage().start()
Feb 12 22:44:27 Akira sickrage[26499]:   File "SickBeard.py", line 247, in start
Feb 12 22:44:27 Akira sickrage[26499]:     sickbeard.CFG = ConfigObj(sickbeard.CONFIG_FILE, encoding='UTF-8')
Feb 12 22:44:27 Akira sickrage[26499]:   File "/mnt/storage/autodown/.sickrage/lib/configobj.py", line 1219, in __init__
Feb 12 22:44:27 Akira sickrage[26499]:     self._load(infile, configspec)
Feb 12 22:44:27 Akira sickrage[26499]:   File "/mnt/storage/autodown/.sickrage/lib/configobj.py", line 1302, in _load
Feb 12 22:44:27 Akira sickrage[26499]:     raise error
Feb 12 22:44:27 Akira sickrage[26499]: configobj.ConfigObjError: Parsing failed with several errors.
Feb 12 22:44:27 Akira sickrage[26499]: First error at line 1092.
Feb 12 22:44:27 Akira systemd[1]: sickrage.service: Control process exited, code=exited status=1
Feb 12 22:44:27 Akira systemd[1]: Failed to start LSB: starts instance of SickRage.
-- Subject: Unit sickrage.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit sickrage.service has failed.
--
-- The result is failed.

I also cleared my logfiles to see if something is being logged but unfortunately this does not happen. Any ideas what i could do next?

**Comment by rickbakker** [comment]
Nobody with a solution to this issue? Been scanning the config file but can't seem to find the problem. I'm a programmer my self, but it's kinda difficult if you don't know what to look for.

**Comment by rickbakker** [comment]
Finally fixed this. For some reason, when you activate torrents with Sickrage, it puts some settings at the bottom of the config file. When you restart sickrage after that, those settings give an error. When i investigated this, it seems like it creates duplicate sections in the config file. Something like [SKYTORRENTS] was already in the config file and it added that again at the bottom. I guess that that caused the error.
