### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by fontes31** [SickRage/SickRage#4342]
Branch/Commit: Loading...
Os: Freenas 9
What you did:
What happened:
What you expected:
Logs:
```
2018-02-28 13:49:34 Thread-17 :: [5066fab] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 280, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 1322, in fetchRemoteBranches
    gh_branches = sickbeard.versionCheckScheduler.action.list_remote_branches()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/versionChecker.py", line 332, in list_remote_branches
    return self.updater.list_remote_branches()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/versionChecker.py", line 863, in list_remote_branches
    repo = sickbeard.gh.get_organization(sickbeard.GIT_ORG).get_repo(sickbeard.GIT_REPO)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/MainClass.py", line 197, in get_organization
    "/orgs/" + login
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 213, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 252, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 277, in __requestRaw
    requestHeaders
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 1204, in connect
    HTTPConnection.connect(self)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/helpers.py", line 86, in getaddrinfo_wrapper
    return orig_getaddrinfo(host, port, family, socktype, proto, flags)
gaierror: [Errno 8] hostname nor servname provided, or not known

**Comment by mtclemente** [comment]
I am getting similar errors to the above after the most recent update...cannot view any of my shows and unable to snatch new torrent files.  Hopefully a fix is coming soon?

Branch/Commit: Most recent
Os: FreeNas 11.1 Jail/Plugin
What you did:   Updated within app
What happened: Unable to view any shows or snatch new torrents
What you expected:  Be able to view shows and snatch new torrents
Logs:

```
AA DatabaseError: database disk image is malformed
AA sql_results = self.connection.cursor().execute(query, args)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/db.py", line 112, in _execute
AA sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/db.py", line 261, in action
AA Traceback (most recent call last):
2018-03-01 22:38:50 ERROR    SEARCHQUEUE-BACKLOG-75160 :: [6e3a1dc] Fatal error executing query: database disk image is malformed
2018-03-01 22:38:50 INFO     SEARCHQUEUE-BACKLOG-75160 :: Beginning backlog search for: [Highlander]
AA DatabaseError: database disk image is malformed
AA sql_results = self.connection.cursor().execute(query, args)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/db.py", line 112, in _execute
AA sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/db.py", line 261, in action
AA Traceback (most recent call last):
2018-03-01 22:38:45 ERROR    SEARCHQUEUE-BACKLOG-75160 :: [6e3a1dc] Fatal error executing query: database disk image is malformed
2018-03-01 22:38:45 INFO     SEARCHQUEUE-BACKLOG-75160 :: Beginning backlog search for: [Highlander]
AA DatabaseError: database disk image is malformed
AA sql_results = self.connection.cursor().execute(query, args)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/db.py", line 112, in _execute
AA sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/db.py", line 261, in action
AA Traceback (most recent call last):
2018-03-01 22:38:44 ERROR    POSTPROCESSOR-AUTO :: [6e3a1dc] Fatal error executing query: database disk image is malformed
AA DatabaseError: database disk image is malformed
AA sql_results = self.connection.cursor().execute(query, args)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/db.py", line 112, in _execute
AA sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/db.py", line 261, in action
``
```

**Comment by miigotu** [comment]
2 totally different problems there. @fontes31 your machine cannot reach github. @mtclemente your database is corrupted.

**Comment by mtclemente** [comment]
Yes, I know it's corrupt.  But it was corrupted by the latest update.

**Comment by mtclemente** [comment]
The update may not intend to corrupt the database but the only time I restarted SR was after the update was applied.  I run it in a FreeNAS jail and my NAS hasn't been restarted in months.  And the jails only get restarted after an update is applied.

I haven't even been able to do a fresh install of the Plugin/Jail in my FreeNAS and then restore from backups. It becomes completely corrupted the moment I restore my backups.  And these backups are from months ago before any corruption would have taken place.  so how does that happen?  I try to use the 'update' command inside SR and it fails.  Old config files don't work and any database I try to restore prevents the jail from even starting.

So something is not right here and apparently I'm not going to get any support from this forum. Appreciate the help.

**Comment by fontes31** [comment]
With the new update all is fine. Working at 100%
Thanks

**Comment by mtclemente** [comment]
So that's all I get?  All those error logs I posted above and everything is fine?  Great community here. Thanks for the support.
