### ISSUE TITLE
RecordNotFound: Not found, Can't start anymore.

### ISSUE THREAD

**Issue by CptanPanic** [SickRage/SickRage#4346]
I am not sure what happened, but Sickrage no longer starts up for me.  And I get the following error, logs are empty.

```
python SiCKRAGE.py 
Traceback (most recent call last):
  File "/home/brian/sickrage/sickrage/__init__.py", line 310, in main
    app.start()
  File "/home/brian/sickrage/sickrage/core/__init__.py", line 251, in start
    db.cleanup()
  File "/home/brian/sickrage/sickrage/core/databases/main/__init__.py", line 73, in cleanup
    self.fix_orphaned_episodes()
  File "/home/brian/sickrage/sickrage/core/databases/main/__init__.py", line 145, in fix_orphaned_episodes
    if not self.get('tv_shows', ep['showid']):
  File "/home/brian/sickrage/sickrage/core/databases/__init__.py", line 306, in get
    data = self.db.get(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/CodernityDB/database_super_thread_safe.py", line 43, in _inner
    res = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/CodernityDB/database.py", line 944, in get
    raise RecordNotFound("Not found")
RecordNotFound: Not found
```

Branch/Commit: 
commit 986e796a7e9fcdf9d45b5a6c6fc469165ba47f90
Merge: cda782d aa7292f
Author: echel0n <echel0n@sickrage.ca>
Date:   Thu Feb 8 18:32:24 2018 -0500

    Merge branch 'release/9.2.101'
OS: Ubuntu 16.04

**Comment by miigotu** [comment]
You arent using the SickRage from this repo, you are using echelons
