### ISSUE TITLE
Unable to Add New Shows

### ISSUE THREAD

**Issue by tconkle** [SickRage/SickRage#4365]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:Master
OS:Ubuntu 16.04
What you did:Added new show
What happened:Failed to add show and Errored
What you expected: To add the show
Logs:
```
AA TypeError: Expected bytes, unicode, or None; got 
AA "Expected bytes, unicode, or None; got %r" % type(value)
AA File "/opt/sickrage/lib/tornado/escape.py", line 248, in to_basestring
AA to_basestring(value))
AA File "/opt/sickrage/lib/tornado/escape.py", line 63, in xhtml_escape
AA kwargs[arg] = xhtml_escape(value)
AA File "/opt/sickrage/sickbeard/webserve.py", line 281, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "/opt/sickrage/lib/concurrent/futures/thread.py", line 62, in run
AA return self.__get_result()
AA File "/opt/sickrage/lib/concurrent/futures/_base.py", line 422, in result
AA value = future.result()
AA File "/opt/sickrage/lib/tornado/gen.py", line 1055, in run
AA results = yield self.async_call(method)
AA File "/opt/sickrage/sickbeard/webserve.py", line 265, in get
AA yielded = self.gen.throw(*exc_info)
AA File "/opt/sickrage/lib/tornado/gen.py", line 1063, in run
AA raise_exc_info(self._exc_info)
AA File "/opt/sickrage/lib/tornado/concurrent.py", line 238, in result
AA value = future.result()
AA File "/opt/sickrage/lib/tornado/gen.py", line 1055, in run
AA result = yield result
AA File "/opt/sickrage/lib/tornado/web.py", line 1511, in _execute
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol=u'http', host='192.168.1.8:8081', method='POST', uri='/addShows/addNewShow', version='HTTP/1.1', remote_ip='192.168.1.10', headers={'Origin': 'http://192.168.1.8:8081', 'Content-Length': '346', 'Accept-Language': 'en-US,en;q=0.9,es;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.1.8:8081', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Connection': 'keep-alive', 'Referer': 'http://192.168.1.8:8081/addShows/newShow/', 'Cache-Control': 'max-age=0', 'Cookie': '_ga=GA1.1.1119859656.1484315285; wanted_view=thumb; advanced_toggle_checked=0; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; imdb_top_250_movies_view=thumb; filter=all; file-manager-response=; file-manager-response_count=; ys-torrentGrid=o%3Acolumns%3Da%253Ao%25253Aid%25253Ds%2525253Aqueue%25255Ewidth%25253Dn%2525253A30%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Ds%2525253Aname%25255Ewidth%25253Dn%2525253A1000%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A2%25255Ewidth%25253Dn%2525253A75%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A3%25255Ewidth%25253Dn%2525253A150%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A4%25255Ewidth%25253Dn%2525253A80%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A5%25255Ewidth%25253Dn%2525253A80%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A6%25255Ewidth%25253Dn%2525253A60%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A7%25255Ewidth%25253Dn%2525253A60%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A8%25255Ewidth%25253Dn%2525253A60%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A9%25255Ewidth%25253Dn%2525253A60%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A10%25255Ewidth%25253Dn%2525253A60%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A11%25255Ewidth%25253Dn%2525253A80%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A12%25255Ewidth%25253Dn%2525253A120%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A13%25255Ewidth%25253Dn%2525253A120%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A14%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A15%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A16%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A17%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A18%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%5Esort%3Do%253Afield%253Ds%25253Aname%255Edirection%253Ds%25253AASC', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded'})
AA 2018-03-10 06:31:08 ERROR Uncaught exception POST /addShows/addNewShow (192.168.1.10)
AA TypeError: Expected bytes, unicode, or None; got 
AA "Expected bytes, unicode, or None; got %r" % type(value)
AA File "/opt/sickrage/lib/tornado/escape.py", line 248, in to_basestring
AA to_basestring(value))
AA File "/opt/sickrage/lib/tornado/escape.py", line 63, in xhtml_escape
AA kwargs[arg] = xhtml_escape(value)
AA File "/opt/sickrage/sickbeard/webserve.py", line 281, in async_call
AA Traceback (most recent call last):
AA TypeError: Expected bytes, unicode, or None; got 
AA "Expected bytes, unicode, or None; got %r" % type(value)
AA File "/opt/sickrage/lib/tornado/escape.py", line 248, in to_basestring
AA to_basestring(value))
AA File "/opt/sickrage/lib/tornado/escape.py", line 63, in xhtml_escape
AA kwargs[arg] = xhtml_escape(value)
AA File "/opt/sickrage/sickbeard/webserve.py", line 281, in async_call
2018-03-10 06:31:08 ERROR Thread-18 :: [2bdb321] Failed doing webui callback: Traceback (most recent call last):
```

**Comment by svencoeck** [comment]
I can confirm this issue. I get the same error when adding a new show.

**Comment by svencoeck** [comment]
Dupllicate of #4364

**Comment by Kratos42** [comment]
Hello
igot the same issue too
I just reinstalled sickrage I can't add show or existing show
