### ISSUE TITLE
Request failed: '_io.BytesIO'

### ISSUE THREAD

**Issue by Jamyz** [SickRage/SickRage#4378]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:master/7a26059801aed3e1aa4994663b0c68ee13fb3d56
OS:Linux-3.10.102-x86_64-with-glibc2.2.5
What you did: SEARCHQUEUE-DAILY-SEARCH or SEARCHQUEUE-BACKLOG
What happened: [7a26059] Request failed: '_io.BytesIO' object has no attribute 'fp'
What you expected: No Errors
Logs:
```
2018-03-12 07:33:44 SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: [7a26059] Request failed: '_io.BytesIO' object has no attribute 'fp'
2018-03-12 07:22:57 SEARCHQUEUE-BACKLOG-77398 :: [Torrent9] :: [7a26059] Request failed: '_io.BytesIO' object has no attribute 'fp'
2018-03-12 07:11:58 SEARCHQUEUE-BACKLOG-289108 :: [Torrent9] :: [7a26059] Request failed: '_io.BytesIO' object has no attribute 'fp'



2018-03-12 07:33:45 DEBUG SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: Transaction with 2423 queries executed
AA AttributeError: '_io.BytesIO' object has no attribute 'fp'
AA raise requests_exception
AA File "/volume1/@appstore/sickrage/var/sickbeard/helpers.py", line 1525, in handle_requests_exception
2018-03-12 07:33:44 DEBUG SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: Traceback (most recent call last):
AA AttributeError: '_io.BytesIO' object has no attribute 'fp'
AA raise requests_exception
AA File "/volume1/@appstore/sickrage/var/sickbeard/helpers.py", line 1525, in handle_requests_exception
AA Traceback (most recent call last):
2018-03-12 07:33:44 ERROR SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: [7a26059] Request failed: '_io.BytesIO' object has no attribute 'fp'
2018-03-12 07:33:44 DEBUG SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: GET URL: http://www.torrent9.bz/torrents_series.html [Status: 301]
2018-03-12 07:33:44 DEBUG SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: Search Mode: RSS


2018-03-12 07:22:57 INFO SEARCHQUEUE-BACKLOG-77398 :: [Torrent9] :: Performing episode search for X-Files : Aux frontières du réel
AA AttributeError: '_io.BytesIO' object has no attribute 'fp'
AA raise requests_exception
AA File "/volume1/@appstore/sickrage/var/sickbeard/helpers.py", line 1525, in handle_requests_exception
2018-03-12 07:22:57 DEBUG SEARCHQUEUE-BACKLOG-77398 :: [Torrent9] :: Traceback (most recent call last):
AA AttributeError: '_io.BytesIO' object has no attribute 'fp'
AA raise requests_exception
AA File "/volume1/@appstore/sickrage/var/sickbeard/helpers.py", line 1525, in handle_requests_exception
AA Traceback (most recent call last):
2018-03-12 07:22:57 ERROR SEARCHQUEUE-BACKLOG-77398 :: [Torrent9] :: [7a26059] Request failed: '_io.BytesIO' object has no attribute 'fp'
2018-03-12 07:22:57 DEBUG SEARCHQUEUE-BACKLOG-77398 :: [Torrent9] :: GET URL: http://www.torrent9.bz/torrents_series.html [Status: 301]
2018-03-12 07:22:57 DEBUG SEARCHQUEUE-BACKLOG-77398 :: [Torrent9] :: Search Mode: RSS
2018-03-12 07:22:57 INFO SEARCHQUEUE-BACKLOG-77398 :: Beginning backlog search for: [X-Files : Aux frontières du réel]
2018-03-12 07:22:55 INFO Thread-17 :: Sending backlog for X-Files : Aux frontières du réel season 11 because some eps were set to wanted
2018-03-12 07:22:54 DEBUG Thread-17 :: Transaction with 1 queries executed
2018-03-12 07:22:54 DEBUG Thread-17 :: Attempting to set status on episode 11x8 to 3
```
Maybe is special characters fail ???

**Comment by miigotu** [comment]
Try changing the torrent9 url to `http://www.torrent9.red`

**Comment by Jamyz** [comment]
I change torrent9.py with torrent9.red, now i wait 48hours if error come back

**Comment by Jamyz** [comment]
I have the same error,
Log:
`2018-03-18 08:30:35 SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: [1981e70] Request failed: '_io.BytesIO' object has no attribute 'fp'`

Debug:
`2018-03-18 08:30:36 DEBUG SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: Transaction with 2302 queries executed
AA AttributeError: '_io.BytesIO' object has no attribute 'fp'
AA raise requests_exception
AA File "/volume1/@appstore/sickrage/var/sickbeard/helpers.py", line 1525, in handle_requests_exception
2018-03-18 08:30:35 DEBUG SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: Traceback (most recent call last):
AA AttributeError: '_io.BytesIO' object has no attribute 'fp'
AA raise requests_exception
AA File "/volume1/@appstore/sickrage/var/sickbeard/helpers.py", line 1525, in handle_requests_exception
AA Traceback (most recent call last):
2018-03-18 08:30:35 ERROR SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: [1981e70] Request failed: '_io.BytesIO' object has no attribute 'fp'
2018-03-18 08:30:35 DEBUG SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: GET URL: http://www.torrent9.bz/torrents_series.html [Status: 301]
2018-03-18 08:30:34 DEBUG SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: Search Mode: RSS`
