### ISSUE TITLE
Sickrage's Git Functions Are Broken (Python < 2.7.9)

### ISSUE THREAD

**Issue by LeeThompson** [SickRage/SickRage#4387]
The functions in Sickrage that access Git need updated.

Branch/Commit: origin
OS: Windows 7
```
2018-03-13 13:13:58 Thread-20 :: [5066fab] Failed doing webui callback: Traceback (most recent call last):
File "C:\Services\Sickrage\current\sickbeard\webserve.py", line 280, in async_call
result = function(**kwargs)
File "C:\Services\Sickrage\current\sickbeard\webserve.py", line 1322, in fetchRemoteBranches
gh_branches = sickbeard.versionCheckScheduler.action.list_remote_branches()
File "C:\Services\Sickrage\current\sickbeard\versionChecker.py", line 332, in list_remote_branches
return self.updater.list_remote_branches()
File "C:\Services\Sickrage\current\sickbeard\versionChecker.py", line 863, in list_remote_branches
repo = sickbeard.gh.get_organization(sickbeard.GIT_ORG).get_repo(sickbeard.GIT_REPO)
File "C:\Services\Sickrage\current\lib\github\MainClass.py", line 197, in get_organization
"/orgs/" + login
File "C:\Services\Sickrage\current\lib\github\Requester.py", line 172, in requestJsonAndCheck
return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
File "C:\Services\Sickrage\current\lib\github\Requester.py", line 213, in requestJson
return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
File "C:\Services\Sickrage\current\lib\github\Requester.py", line 252, in __requestEncode
status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
File "C:\Services\Sickrage\current\lib\github\Requester.py", line 277, in __requestRaw
requestHeaders
File "C:\python\lib\httplib.py", line 973, in request
self._send_request(method, url, body, headers)
File "C:\python\lib\httplib.py", line 1007, in _send_request
self.endheaders(body)
File "C:\python\lib\httplib.py", line 969, in endheaders
self._send_output(message_body)
File "C:\python\lib\httplib.py", line 829, in _send_output
self.send(msg)
File "C:\python\lib\httplib.py", line 791, in send
self.connect()
File "C:\python\lib\httplib.py", line 1176, in connect
self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
File "C:\python\lib\ssl.py", line 387, in wrap_socket
ciphers=ciphers)
File "C:\python\lib\ssl.py", line 143, in __init__
self.do_handshake()
File "C:\python\lib\ssl.py", line 305, in do_handshake
self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```
The functions in Sickrage that access Git need updated.

**Comment by LeeThompson** [comment]
I'm ... 80% sure the issue is in pygithub (lib/github).  Github seems to be requiring a TLS handshake (rejecting SSL) and lib/httplib2 specifically defaults to SSL23

**Comment by LeeThompson** [comment]
Switched to Python 2.7.9 which defaults to TLS and now it's working.    Might want to add code if < 2.7.9 is still going to be supported.

**Comment by miigotu** [comment]
< 2.7.9 is not supported.
