### ISSUE TITLE
[APP SUBMITTED]: 502 {u'message': u'Server Error'}

### ISSUE THREAD

**Issue by freeextreme** [SickRage/SickRage#4424]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.15+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@2d4e83adcf80d9e50125beaf8b64b6439f158916
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [2d4e83a] Traceback (most recent call last):
  File "/app/sickrage/sickbeard/logger.py", line 385, in submit_errors
    for report in reports:
  File "/app/sickrage/lib/github/PaginatedList.py", line 49, in __iter__
    newElements = self._grow()
  File "/app/sickrage/lib/github/PaginatedList.py", line 61, in _grow
    newElements = self._fetchNextPage()
  File "/app/sickrage/lib/github/PaginatedList.py", line 163, in _fetchNextPage
    headers=self.__headers
  File "/app/sickrage/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/app/sickrage/lib/github/Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 502 {u'message': u'Server Error'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by janusn** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [f7a113a] Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 385, in submit_errors
    for report in reports:
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/github/PaginatedList.py", line 49, in __iter__
    newElements = self._grow()
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/github/PaginatedList.py", line 61, in _grow
    newElements = self._fetchNextPage()
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/github/PaginatedList.py", line 163, in _fetchNextPage
    headers=self.__headers
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 502 {u'message': u'Server Error'}

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by janusn** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@86207e9e728f4685e5b92a14674d2ae4e6e1279b
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [86207e9] Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 385, in submit_errors
    for report in reports:
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/github/PaginatedList.py", line 49, in __iter__
    newElements = self._grow()
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/github/PaginatedList.py", line 61, in _grow
    newElements = self._fetchNextPage()
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/github/PaginatedList.py", line 163, in _fetchNextPage
    headers=self.__headers
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 502 {u'message': u'Server Error'}

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
