### ISSUE TITLE
[APP SUBMITTED]: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

### ISSUE THREAD

**Issue by ilovesickrage** [SickRage/SickRage#4572]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
Link to Log: https://gist.github.com/9667a9811ba68cac4f87f551623ba190
### ERROR
```
SEARCHQUEUE-MANUAL-194031 :: [ThePirateBay] :: [a760263] Exception while searching ThePirateBay. Error: FeatureNotFound(u"Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ilovesickrage** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
Link to Log: https://gist.github.com/281be182823d29c3406e3c99d5a554bd
### ERROR
```
SEARCHQUEUE-MANUAL-153021 :: [ThePirateBay] :: [a760263] Exception while searching ThePirateBay. Error: FeatureNotFound(u"Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ilovesickrage** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
Link to Log: https://gist.github.com/36a714349c70509b3ca11ff080feb893
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [LimeTorrents] :: [a760263] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "C:\\SickRageNew\\sickbeard\\providers\\limetorrents.py", line 79, in search\n    data = BeautifulSoup(data, \'html5lib\')\n  File "C:\\SickRageNew\\lib\\bs4\\__init__.py", line 165, in __init__\n    % ",".join(features))\nFeatureNotFound: Couldn\'t find a tree builder with the features you requested: html5lib. Do you need to install a parser library?\n'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ilovesickrage** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
Link to Log: https://gist.github.com/2b807abb9ea0889b9749faf79e3d1938
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Torrentz] :: [a760263] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "C:\\SickRageNew\\sickbeard\\providers\\torrentz.py", line 92, in search\n    with BS4Parser(data, \'html5lib\') as parser:\n  File "C:\\SickRageNew\\sickbeard\\bs4_parser.py", line 28, in __init__\n    self.soup = BeautifulSoup(*args, **kwargs)\n  File "C:\\SickRageNew\\lib\\bs4\\__init__.py", line 165, in __init__\n    % ",".join(features))\nFeatureNotFound: Couldn\'t find a tree builder with the features you requested: html5lib. Do you need to install a parser library?\n'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ilovesickrage** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
Link to Log: https://gist.github.com/90e22261134f4c9f581ee46a81c6fa00
### ERROR
```
SEARCHQUEUE-MANUAL-277165 :: [ThePirateBay] :: [a760263] Exception while searching ThePirateBay. Error: FeatureNotFound(u"Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ilovesickrage** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
Link to Log: https://gist.github.com/20fe2f632a00115fa13aee46bbedc4ff
### ERROR
```
SEARCHQUEUE-MANUAL-277165 :: [LimeTorrents] :: [a760263] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "C:\\SickRageNew\\sickbeard\\providers\\limetorrents.py", line 79, in search\n    data = BeautifulSoup(data, \'html5lib\')\n  File "C:\\SickRageNew\\lib\\bs4\\__init__.py", line 165, in __init__\n    % ",".join(features))\nFeatureNotFound: Couldn\'t find a tree builder with the features you requested: html5lib. Do you need to install a parser library?\n'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ilovesickrage** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
Link to Log: https://gist.github.com/50e0949909831f7fb6e27141b73ccb5e
### ERROR
```
SEARCHQUEUE-MANUAL-277165 :: [Torrentz] :: [a760263] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "C:\\SickRageNew\\sickbeard\\providers\\torrentz.py", line 92, in search\n    with BS4Parser(data, \'html5lib\') as parser:\n  File "C:\\SickRageNew\\sickbeard\\bs4_parser.py", line 28, in __init__\n    self.soup = BeautifulSoup(*args, **kwargs)\n  File "C:\\SickRageNew\\lib\\bs4\\__init__.py", line 165, in __init__\n    % ",".join(features))\nFeatureNotFound: Couldn\'t find a tree builder with the features you requested: html5lib. Do you need to install a parser library?\n'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ilovesickrage** [comment]
Somehow I got some missing files in my checkout... nevermind this issue
