### ISSUE TITLE
PostProcessing Isn't Copying over the entire file

### ISSUE THREAD

**Issue by missinnale** [SickRage/SickRage#4589]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Windows 10
Browser: Edge
What you did: Auto Post Processor (figured out the issue by manual post processing)
What happened: Files were correctly copied to correct location, but not the entire file, it only seems to copy a fraction of the file.
What you expected: The entire file to be copied over since I chose the copy option of post processing since I'm using Torrents.
Logs:
```
2018-04-10 11:52:52 INFO     ThreadPoolExecutor-0_2 :: Manual post processing task for C:\Users\elanm\Downloads\Completed Torrents\rage\Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2[rarbg] completed
2018-04-10 11:52:52 INFO     ThreadPoolExecutor-0_2 :: Successfully processed
2018-04-10 11:52:52 INFO     ThreadPoolExecutor-0_2 :: Processing succeeded for C:\Users\elanm\Downloads\Completed Torrents\rage\Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2[rarbg]\Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2.mkv
2018-04-10 11:52:52 DEBUG    ThreadPoolExecutor-0_2 :: Notification for NMJ scan update not enabled, skipping this notification
2018-04-10 11:52:52 DEBUG    ThreadPoolExecutor-0_2 :: formatting pattern: %SN - %Sx%0E - %EN - %QN -&gt; Taboo (2017) - 1x01 - Episode 1 - 1080p WEB-DL
2018-04-10 11:52:52 DEBUG    ThreadPoolExecutor-0_2 :: Found codec for 'Taboo (2017): Episode 1'.
2018-04-10 11:52:52 DEBUG    ThreadPoolExecutor-0_2 :: Using cached parse result for: Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2
2018-04-10 11:52:51 DEBUG    ThreadPoolExecutor-0_2 :: Parsed \\SHIELD\External\NVIDIA_SHIELD\TV Shows\Taboo (2017)\Season 01\Taboo (2017) - S01E01 - Episode 1 into Taboo (2017) - S01E01 [ABD: False] [ANIME: False] [whichReg: [u'standard', u'season_only']]
2018-04-10 11:52:51 DEBUG    ThreadPoolExecutor-0_2 :: Transaction with 2 queries executed
2018-04-10 11:52:50 DEBUG    ThreadPoolExecutor-0_2 :: Setter sets location to \\SHIELD\External\NVIDIA_SHIELD\TV Shows\Taboo (2017)\Season 01\Taboo (2017) - S01E01 - Episode 1.mkv
AA IOError: [Errno 22] Invalid argument
AA fdst.write(buf)
AA File "C:\SickRage\Python\lib\shutil.py", line 52, in copyfileobj
AA return copyfileobj_orig(fsrc, fdst, length)
AA File "C:\SickRage\SickRage\sickbeard\helpers.py", line 98, in _copyfileobj
AA copyfileobj(fsrc, fdst)
AA File "C:\SickRage\Python\lib\shutil.py", line 84, in copyfile
AA result = function(*args, **kwargs)
AA File "C:\SickRage\SickRage\sickrage\helper\encoding.py", line 42, in ek
AA ek(shutil.copyfile, srcFile, destFile)
AA File "C:\SickRage\SickRage\sickbeard\helpers.py", line 386, in copyFile
AA Traceback (most recent call last):
2018-04-10 11:52:50 ERROR    ThreadPoolExecutor-0_2 :: [1d34bcb] [Errno 22] Invalid argument
2018-04-10 11:52:34 DEBUG    ThreadPoolExecutor-0_2 :: Copying file from C:\Users\elanm\Downloads\Completed Torrents\rage\Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2[rarbg]\Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2.mkv to \\SHIELD\External\NVIDIA_SHIELD\TV Shows\Taboo (2017)\Season 01\Taboo (2017) - S01E01 - Episode 1.mkv
2018-04-10 11:52:34 DEBUG    ThreadPoolExecutor-0_2 :: Checking if the path \\SHIELD\External\NVIDIA_SHIELD\TV Shows\Taboo (2017)\Season 01 already exists
2018-04-10 11:52:34 DEBUG    ThreadPoolExecutor-0_2 :: Destination folder for this episode: \\SHIELD\External\NVIDIA_SHIELD\TV Shows\Taboo (2017)\Season 01
2018-04-10 11:52:33 DEBUG    ThreadPoolExecutor-0_2 :: formatting pattern: Season %0S -&gt; Season 01
2018-04-10 11:52:33 DEBUG    ThreadPoolExecutor-0_2 :: Found codec for 'Taboo (2017): Episode 1'.
2018-04-10 11:52:33 DEBUG    ThreadPoolExecutor-0_2 :: Using cached parse result for: Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2
2018-04-10 11:52:33 DEBUG    ThreadPoolExecutor-0_2 :: Parsed \\SHIELD\External\NVIDIA_SHIELD\TV Shows\Taboo (2017)\Season 01\Taboo (2017) - S01E01 - Episode 1 into Taboo (2017) - S01E01 [ABD: False] [ANIME: False] [whichReg: [u'standard', u'season_only']]
2018-04-10 11:52:33 DEBUG    ThreadPoolExecutor-0_2 :: formatting pattern: %SN - S%0SE%0E - %EN -&gt; Taboo (2017) - S01E01 - Episode 1
2018-04-10 11:52:33 DEBUG    ThreadPoolExecutor-0_2 :: Found codec for 'Taboo (2017): Episode 1'.
2018-04-10 11:52:33 DEBUG    ThreadPoolExecutor-0_2 :: Using cached parse result for: Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2
2018-04-10 11:52:33 DEBUG    ThreadPoolExecutor-0_2 :: Parsed \\SHIELD\External\NVIDIA_SHIELD\TV Shows\Taboo (2017)\Season 01\Taboo (2017) - S01E01 - Episode 1 into Taboo (2017) - S01E01 [ABD: False] [ANIME: False] [whichReg: [u'standard', u'season_only']]
2018-04-10 11:52:33 DEBUG    ThreadPoolExecutor-0_2 :: Folder name (Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2[rarbg]) appears to be a valid release name. Using it.
2018-04-10 11:52:33 DEBUG    ThreadPoolExecutor-0_2 :: Using cached parse result for: Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2[rarbg]
2018-04-10 11:52:33 DEBUG    ThreadPoolExecutor-0_2 :: Found release name Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2
2018-04-10 11:52:32 INFO     ThreadPoolExecutor-0_2 :: Trying to clean any empty folders under \\SHIELD\External\NVIDIA_SHIELD\TV Shows\Taboo (2017)\Season 01
2018-04-10 11:52:31 DEBUG    ThreadPoolExecutor-0_2 :: Deleting file \\SHIELD\External\NVIDIA_SHIELD\TV Shows\Taboo (2017)\Season 01\Taboo (2017) - S01E01 - Episode 1.mkv
2018-04-10 11:52:31 DEBUG    ThreadPoolExecutor-0_2 :: No associated files for \\SHIELD\External\NVIDIA_SHIELD\TV Shows\Taboo (2017)\Season 01\Taboo (2017) - S01E01 - Episode 1.mkv were found during this pass
2018-04-10 11:52:29 DEBUG    ThreadPoolExecutor-0_2 :: Trying to determine free space on destination drive
2018-04-10 11:52:29 INFO     ThreadPoolExecutor-0_2 :: This download is marked a priority download so I'm going to replace an existing file if I find one
2018-04-10 11:52:29 DEBUG    ThreadPoolExecutor-0_2 :: File \\SHIELD\External\NVIDIA_SHIELD\TV Shows\Taboo (2017)\Season 01\Taboo (2017) - S01E01 - Episode 1.mkv is smaller than C:\Users\elanm\Downloads\Completed Torrents\rage\Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2[rarbg]\Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2.mkv
2018-04-10 11:52:27 DEBUG    ThreadPoolExecutor-0_2 :: Is ep a priority download: True
2018-04-10 11:52:27 DEBUG    ThreadPoolExecutor-0_2 :: Quality of the episode we're processing: 1080p WEB-DL
2018-04-10 11:52:27 DEBUG    ThreadPoolExecutor-0_2 :: Snatch history had a quality in it, using that: 1080p WEB-DL
2018-04-10 11:52:27 DEBUG    ThreadPoolExecutor-0_2 :: Retrieving episode object for 1x1
2018-04-10 11:52:27 DEBUG    ThreadPoolExecutor-0_2 :: Using cached parse result for: Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2
2018-04-10 11:52:27 DEBUG    ThreadPoolExecutor-0_2 :: Analyzing name Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2.mkv
2018-04-10 11:52:27 INFO     ThreadPoolExecutor-0_2 :: Processing C:\Users\elanm\Downloads\Completed Torrents\rage\Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2[rarbg]\Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2.mkv (None)
2018-04-10 11:52:27 DEBUG    ThreadPoolExecutor-0_2 :: Parsed Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2.mkv into Taboo 2017 - S01E01 [GROUP: R2D2] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2018-04-10 11:52:27 DEBUG    ThreadPoolExecutor-0_2 :: Processing folder C:\Users\elanm\Downloads\Completed Torrents\rage\Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2[rarbg]
2018-04-10 11:52:27 INFO     ThreadPoolExecutor-0_2 :: Processing C:\Users\elanm\Downloads\Completed Torrents\rage\Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2[rarbg]
2018-04-10 11:52:27 DEBUG    ThreadPoolExecutor-0_2 :: Processing in folder C:\Users\elanm\Downloads\Completed Torrents\rage\Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2[rarbg]
2018-04-10 11:52:27 INFO     ThreadPoolExecutor-0_2 :: Beginning manual post processing task: C:\Users\elanm\Downloads\Completed Torrents\rage\Taboo.2017.S01E01.1080p.WEB-DL.DD5.1.H264-R2D2[rarbg]
```
Can include screenshots of what I just did as well if needed.

**Comment by llonca13** [comment]
Happens to me aproximately every 10th download using both Transmission and Deluge for the last year and a half..always followed by Warning Postprocessor error in log that reports that it couldnt delete tv show folder (from the download location, its set to copy to another folder when finished) because the folder is not empty...btw both deluge and transmission were configured with Incomplete folder before moving to sickrage folder(finished downloads ready for postprocessing) so I guess Its not error in torrent clients but in Sickrage itself (because it never happened to me when downloading torrents directly, only through sickrage)

**Comment by crowaust** [comment]
Just an idea, is it mistakenly post processing the Sample as the actual or something similar rather than a truncated file? Or maybe truncated because it is only processing the first compressed file? I have seen both of these happen previously but not in some time.
