### ISSUE TITLE
issue with YGG

### ISSUE THREAD

**Issue by Crush33** [SickRage/SickRage#4618]
Branch/Commit: master (a7602639bd525f27475f1eeb2fc504111a14b51c)
OS: debian 9
Browser: chrome
What you did: search manually / auto for torrent on yggtorrent.is
What happened: torrent is found but error occurs when pushing it to transmission for download
What you expected: successuful push from sickrage to transmission

Logs: (read from bottom to the top)
```
2018-04-19 21:15:53 INFO DAILYSEARCHER :: No new released episodes found ...
2018-04-19 21:15:53 INFO DAILYSEARCHER :: Searching for new released episodes ...
AA BTFailure: not a valid bencoded string
AA raise bencode.BTL.BTFailure("not a valid bencoded string")
AA File "/srv/sickrage/sickbeard/helpers.py", line 1935, in bdecode
AA torrent_bdecode = helpers.bdecode(result.content, True)
AA File "/srv/sickrage/sickbeard/clients/generic.py", line 216, in _get_torrent_hash
AA result = self._get_torrent_hash(result)
AA File "/srv/sickrage/sickbeard/clients/generic.py", line 259, in sendTORRENT
AA Traceback (most recent call last):
2018-04-19 21:14:35 ERROR SEARCHQUEUE-MANUAL-153021 :: [a760263] Transmission: Failed Sending Torrent
AA BTFailure: not a valid bencoded string
AA raise bencode.BTL.BTFailure("not a valid bencoded string")
AA File "/srv/sickrage/sickbeard/helpers.py", line 1935, in bdecode
AA torrent_bdecode = helpers.bdecode(result.content, True)
AA File "/srv/sickrage/sickbeard/clients/generic.py", line 216, in _get_torrent_hash
AA Traceback (most recent call last):
2018-04-19 21:14:35 ERROR SEARCHQUEUE-MANUAL-153021 :: [a760263] Unable to bdecode torrent
2018-04-19 21:14:34 INFO SEARCHQUEUE-MANUAL-153021 :: Downloading The.Walking.Dead.S08E01.VOSTFR.1080p.WEB-DL.DD5.1.H264-ARK01 from YggTorrent
2018-04-19 21:14:34 INFO SEARCHQUEUE-MANUAL-153021 :: [YggTorrent] :: Quality of The.Walking.Dead.S08E01.Mercy.VOSTFR.1080p.AMZN.WEB-DL.H.264-NLX5.mkv is 1080p WEB-DL
2018-04-19 21:14:34 INFO SEARCHQUEUE-MANUAL-153021 :: [YggTorrent] :: Quality of The.Walking.Dead.S08E01.VOSTFR.1080p.WEB-DL.DD5.1.H264-ARK01 is 1080p WEB-DL
2018-04-19 21:14:33 INFO SEARCHQUEUE-MANUAL-153021 :: [YggTorrent] :: Performing episode search for The Walking Dead
2018-04-19 21:14:17 INFO SEARCHQUEUE-MANUAL-153021 :: Beginning manual search for: [The Walking Dead - S08E01 - Mercy]
```
thx for any help...

**Comment by skillfr** [comment]
reboot sickrage

**Comment by Crush33** [comment]
fixed ! thx a lot !!!
