### ISSUE TITLE
Cannot start version with updated Subliminal - "cannot import name NameRegistry"

### ISSUE THREAD

**Issue by woopla** [SickRage/SickRage#4629]
Hello,
I updated yesterday to the latest version of SickRage (using the Archlinux AUR package `sickrage2-git`), and now SickRage won't start. It complains about a module called during the init of Subliminal. Here's the output:
```python
Traceback (most recent call last):
  File "/opt/sickrage/app/SickBeard.py", line 69, in <module>
    import sickbeard
  File "/opt/sickrage/app-git/sickbeard/__init__.py", line 46, in <module>
    from sickbeard import (auto_postprocessor, dailysearcher, db, helpers, logger, metadata, naming, post_processing_queue, properFinder, providers, scheduler,
  File "/opt/sickrage/app-git/sickbeard/naming.py", line 27, in <module>
    from sickbeard import common, logger, tv
  File "/opt/sickrage/app-git/sickbeard/tv.py", line 36, in <module>
    from sickbeard import db, helpers, image_cache, logger, network_timezones, notifiers, postProcessor, subtitles
  File "/opt/sickrage/app-git/sickbeard/subtitles.py", line 32, in <module>
    import subliminal
  File "/opt/sickrage/app/lib/subliminal/__init__.py", line 13, in <module>
    from .cache import region
  File "/opt/sickrage/app/lib/subliminal/cache.py", line 4, in <module>
    from dogpile.cache import make_region
  File "/opt/sickrage/app/lib/dogpile/cache/__init__.py", line 1, in <module>
    from .region import CacheRegion, register_backend, make_region  # noqa
  File "/opt/sickrage/app/lib/dogpile/cache/region.py", line 3, in <module>
    from ..util import NameRegistry
ImportError: cannot import name NameRegistry
```

SickRage is started through Systemd with the following command line:
```shell
/usr/bin/env python2 /opt/sickrage/app/SickBeard.py --nolaunch --datadir /opt/sickrage/data
```

If I go in the `/opt/sickrage/app/lib/dogpile` dir and run a python2 shell in there, typing `from util import NameRegistry` works fine. Looks like Python is getting lost in the relative import path resolution.

Thanks,

Clément

**Comment by miigotu** [comment]
`python2 --version`

**Comment by woopla** [comment]
Version is 2.7.14

Thanks,

Clément

**Comment by miigotu** [comment]
You could try the develop branch, lmk if that helps

**Comment by woopla** [comment]
So I switched to a container-based build and it works now, I'll just close the issue.

**Comment by luisfcorreia** [comment]
FYI this error is still a thing now

I've just changed to this code and got this issue, Fedora Linux, Python 2.7.15

and yes, it's a python path related thing
