### ISSUE TITLE
[APP SUBMITTED]: 403 {u'documentation_url': u'https://developer.github.com/v3/issues/comments/#create-a-comment', u'message': u'Must have admin rights to Repository.'}

### ISSUE THREAD

**Issue by scarygary** [SickRage/SickRage#4634]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [a760263] Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/logger.py", line 392, in submit_errors
    if report.create_comment(message):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Issue.py", line 276, in create_comment
    input=post_parameters
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://developer.github.com/v3/issues/comments/#create-a-comment', u'message': u'Must have admin rights to Repository.'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by hippie131** [comment]
### INFO
Python Version: **2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]**
Operating System: **Linux-4.4.0-127-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@93923792e8908427344d6e01de968656cf096626
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [9392379] Traceback (most recent call last):
  File "/home/jesse/.sickrage/sickbeard/logger.py", line 392, in submit_errors
    if report.create_comment(message):
  File "/home/jesse/.sickrage/lib/github/Issue.py", line 276, in create_comment
    input=post_parameters
  File "/home/jesse/.sickrage/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/home/jesse/.sickrage/lib/github/Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://developer.github.com/v3/issues/comments/#create-a-comment', u'message': u'Must have admin rights to Repository.'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by skjnldsv** [comment]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]**
Operating System: **Linux-4.17.0-0.bpo.3-amd64-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@30efa255db37af28f62f6c21a86a92e755ea1ff9
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [30efa25] Traceback (most recent call last):
  File "/app/sickrage/sickbeard/logger.py", line 392, in submit_errors
    if report.create_comment(message):
  File "/app/sickrage/lib/github/Issue.py", line 276, in create_comment
    input=post_parameters
  File "/app/sickrage/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/app/sickrage/lib/github/Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://developer.github.com/v3/issues/comments/#create-a-comment', u'message': u'Must have admin rights to Repository.'}

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ryanjnacht** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@b3da866cadff70973fabdbb3ffbe8ad0dd208c49
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [b3da866] Traceback (most recent call last):
  File "C:\SickRage\sickbeard\logger.py", line 392, in submit_errors
    if report.create_comment(message):
  File "C:\SickRage\lib\github\Issue.py", line 276, in create_comment
    input=post_parameters
  File "C:\SickRage\lib\github\Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\lib\github\Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://developer.github.com/v3/issues/comments/#create-a-comment', u'message': u'Must have admin rights to Repository.'}

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by skjnldsv** [comment]
@scarygary please reopen!
