### ISSUE TITLE
Tornado API Error 6

### ISSUE THREAD

**Issue by ImDevinC** [SickRage/SickRage#4641]
Branch/Commit: master/a760263
OS: Arch Linux 4.15
Browser: Chrome
What you did: Nothing
What happened: I keep seeing errors similar to the below section in my log.  
`2018-04-29 19:00:00 ERROR TORNADO :: [a760263] API :: error 6` and the errors that show up just after it.
What you expected: Not to see the error
Logs:
```
2018-04-29 19:00:01 DEBUG TORNADO :: API :: show.stats: cur_kwargs {'tvdbid': '313435'}
2018-04-29 19:00:01 DEBUG TORNADO :: API :: all kwargs: '{'cmd': 'show.stats', 'tvdbid': '313435'}'
2018-04-29 19:00:01 DEBUG TORNADO :: API :: all args: '()'
2018-04-29 19:00:01 DEBUG TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2018-04-29 19:00:01 DEBUG TORNADO :: API :: show.stats: cur_kwargs {'tvdbid': '305719'}
2018-04-29 19:00:01 DEBUG TORNADO :: API :: all kwargs: '{'cmd': 'show.stats', 'tvdbid': '305719'}'
2018-04-29 19:00:01 DEBUG TORNADO :: API :: all args: '()'
2018-04-29 19:00:01 DEBUG TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2018-04-29 19:00:00 DEBUG TORNADO :: API :: show.stats: cur_kwargs {'tvdbid': '79275'}
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all kwargs: '{'cmd': 'show.stats', 'tvdbid': '79275'}'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all args: '()'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2018-04-29 19:00:00 DEBUG TORNADO :: API :: show.stats: cur_kwargs {'tvdbid': '76666'}
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all kwargs: '{'cmd': 'show.stats', 'tvdbid': '76666'}'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all args: '()'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2018-04-29 19:00:00 DEBUG TORNADO :: API :: show.stats: cur_kwargs {'tvdbid': '269653'}
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all kwargs: '{'cmd': 'show.stats', 'tvdbid': '269653'}'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all args: '()'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2018-04-29 19:00:00 DEBUG TORNADO :: API :: show.stats: cur_kwargs {'tvdbid': '332027'}
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all kwargs: '{'cmd': 'show.stats', 'tvdbid': '332027'}'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all args: '()'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2018-04-29 19:00:00 DEBUG TORNADO :: API :: show.stats: cur_kwargs {'tvdbid': '271910'}
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all kwargs: '{'cmd': 'show.stats', 'tvdbid': '271910'}'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all args: '()'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2018-04-29 19:00:00 DEBUG TORNADO :: API :: show.stats: cur_kwargs {'tvdbid': '272849'}
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all kwargs: '{'cmd': 'show.stats', 'tvdbid': '272849'}'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all args: '()'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2018-04-29 19:00:00 DEBUG TORNADO :: API :: show.stats: cur_kwargs {'tvdbid': '80096'}
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all kwargs: '{'cmd': 'show.stats', 'tvdbid': '80096'}'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all args: '()'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
AA KeyError: 6
AA episode_qualities_counts_download[int(row[b"status"])] += 1
AA File "/opt/sickrage/sickbeard/webapi.py", line 2724, in run
AA cur_out_dict = to_call.run() # call function and get response
AA File "/opt/sickrage/sickbeard/webapi.py", line 202, in call_dispatcher
AA out_dict = _call_dispatcher(args, kwargs)
AA File "/opt/sickrage/sickbeard/webapi.py", line 130, in get
AA Traceback (most recent call last):
2018-04-29 19:00:00 ERROR TORNADO :: [a760263] API :: error 6
2018-04-29 19:00:00 DEBUG TORNADO :: API :: show.stats: cur_kwargs {'tvdbid': '328724'}
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all kwargs: '{'cmd': 'show.stats', 'tvdbid': '328724'}'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all args: '()'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2018-04-29 19:00:00 DEBUG TORNADO :: API :: show.stats: cur_kwargs {'tvdbid': '330415'}
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all kwargs: '{'cmd': 'show.stats', 'tvdbid': '330415'}'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all args: '()'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2018-04-29 19:00:00 DEBUG TORNADO :: API :: show.stats: cur_kwargs {'tvdbid': '72306'}
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all kwargs: '{'cmd': 'show.stats', 'tvdbid': '72306'}'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all args: '()'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2018-04-29 19:00:00 DEBUG TORNADO :: API :: show.stats: cur_kwargs {'tvdbid': '322399'}
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all kwargs: '{'cmd': 'show.stats', 'tvdbid': '322399'}'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all args: '()'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2018-04-29 19:00:00 DEBUG TORNADO :: API :: show.stats: cur_kwargs {'tvdbid': '77119'}
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all kwargs: '{'cmd': 'show.stats', 'tvdbid': '77119'}'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all args: '()'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2018-04-29 19:00:00 DEBUG TORNADO :: API :: show.stats: cur_kwargs {'tvdbid': '75164'}
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all kwargs: '{'cmd': 'show.stats', 'tvdbid': '75164'}'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all args: '()'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2018-04-29 19:00:00 DEBUG TORNADO :: API :: show.stats: cur_kwargs {'tvdbid': '289882'}
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all kwargs: '{'cmd': 'show.stats', 'tvdbid': '289882'}'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: all args: '()'
2018-04-29 19:00:00 DEBUG TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
```

**Comment by ImDevinC** [comment]
This message looks to have resolved itself, closing this
