### ISSUE TITLE
Torrentleech provider broken since April 30th.

### ISSUE THREAD

**Issue by carbonneaud** [SickRage/SickRage#4649]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Ubuntu
Browser: Chrome
What you did: Try to download a torrent
What happened: Nothing.  Torrent goes to backlog
What you expected: A torrent to download.

Logs:
2018-05-03 14:16:18 INFO SEARCHQUEUE-BACKLOG-80379 :: No needed episodes found during backlog search for: [The Big Bang Theory]
2018-05-03 14:16:18 INFO SEARCHQUEUE-BACKLOG-80379 :: [TorrentLeech] :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.
AA OperationalError: no such column: indexerid
AA sql_results = self.connection.cursor().execute(query, args)
AA File "/transmission/Sickrage/sickbeard/db.py", line 112, in _execute
AA sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
AA File "/transmission/Sickrage/sickbeard/db.py", line 261, in action
AA sql_results = self.action(query, args, fetchall=True)
AA File "/transmission/Sickrage/sickbeard/db.py", line 291, in select
AA [episode.show.indexerid, episode.season, "%|" + str(episode.episode) + "|%"])
AA File "/transmission/Sickrage/sickbeard/tvcache.py", line 314, in find_needed_episodes
AA needed_eps = self.find_needed_episodes(episode, manual_search, down_cur_quality)
AA File "/transmission/Sickrage/sickbeard/tvcache.py", line 291, in search_cache
AA down_cur_quality=download_current_quality)
AA File "/transmission/Sickrage/sickrage/providers/GenericProvider.py", line 134, in find_search_results
AA searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
AA File "/transmission/Sickrage/sickbeard/search.py", line 475, in searchProviders
AA Traceback (most recent call last):
2018-05-03 14:16:18 ERROR SEARCHQUEUE-BACKLOG-80379 :: [TorrentLeech] :: [a760263] Exception while searching TorrentLeech. Error: OperationalError('no such column: indexerid',)
AA OperationalError: no such column: indexerid
AA sql_results = self.connection.cursor().execute(query, args)
AA File "/transmission/Sickrage/sickbeard/db.py", line 112, in _execute
AA sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
AA File "/transmission/Sickrage/sickbeard/db.py", line 261, in action
AA Traceback (most recent call last):
2018-05-03 14:16:18 ERROR SEARCHQUEUE-BACKLOG-80379 :: [TorrentLeech] :: [a760263] DB error: no such column: indexerid
2018-05-03 14:16:18 INFO SEARCHQUEUE-BACKLOG-80379 :: [TorrentLeech] :: Performing episode search for The Big Bang Theory
2018-05-03 14:15:39 INFO SEARCHQUEUE-BACKLOG-80379 :: Beginning backlog search for: [The Big Bang Theory]

**Comment by carbonneaud** [comment]
Deleting the cache.db fixed the issue.
