### ISSUE TITLE
[APP SUBMITTED]: 401 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Requires authentication'}

### ISSUE THREAD

**Issue by antipiot** [SickRage/SickRage#4710]
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-4.9.0-0.bpo.6-amd64-x86_64-with-debian-8.10**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_7 :: [5a9a634] Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/logger.py", line 335, in submit_errors
    gist = sickbeard.gh.get_user().create_gist(False, {'sickrage.log': InputFileContent(paste_data)})
  File "/opt/sickbeard/lib/github/AuthenticatedUser.py", line 479, in create_gist
    input=post_parameters
  File "/opt/sickbeard/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/opt/sickbeard/lib/github/Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 401 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Requires authentication'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by antipiot** [comment]
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-4.9.0-0.bpo.6-amd64-x86_64-with-debian-8.10**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [5a9a634] Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/logger.py", line 335, in submit_errors
    gist = sickbeard.gh.get_user().create_gist(False, {'sickrage.log': InputFileContent(paste_data)})
  File "/opt/sickbeard/lib/github/AuthenticatedUser.py", line 479, in create_gist
    input=post_parameters
  File "/opt/sickbeard/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/opt/sickbeard/lib/github/Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 401 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Requires authentication'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by skjnldsv** [comment]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]**
Operating System: **Linux-4.17.0-0.bpo.3-amd64-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@30efa255db37af28f62f6c21a86a92e755ea1ff9
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [30efa25] Traceback (most recent call last):
  File "/app/sickrage/sickbeard/logger.py", line 335, in submit_errors
    gist = sickbeard.gh.get_user().create_gist(False, {'sickchill.log': InputFileContent(paste_data)})
  File "/app/sickrage/lib/github/AuthenticatedUser.py", line 479, in create_gist
    input=post_parameters
  File "/app/sickrage/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/app/sickrage/lib/github/Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 401 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Requires authentication'}

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by muscledsnow3475** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_6 :: [e094759] Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\logger.py", line 335, in submit_errors
    gist = sickbeard.gh.get_user().create_gist(False, {'sickchill.log': InputFileContent(paste_data)})
  File "C:\SickChill\SickChill\lib\github\AuthenticatedUser.py", line 479, in create_gist
    input=post_parameters
  File "C:\SickChill\SickChill\lib\github\Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickChill\SickChill\lib\github\Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 401 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Requires authentication'}

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
