### ISSUE TITLE
Unable to Connect to TheTVDB API

### ISSUE THREAD

**Issue by meyersbs** [SickRage/SickRage#4795]
Branch/Commit:  master/807c5ae37ecd5af7483f06459c94788ee9db483d
OS: Ubuntu 17.10
Browser: Chrome

I tried to manually add an existing show using the web GUI, but it failed to search for the show using TheTVDB (or any other indexer). There were no warnings/errors thrown. I created an NFO file to attempt to circumvent the issue. That resulted in the logs below. I followed the instructions in the error message (delete the NFO and try manually) with the same results as before.
Logs:
```
2018-06-19 10:26:19 SHOWQUEUE-ADD :: [807c5ae] Unable to look up the show in /path/to/show/Transformers: Prime Wars on theTVDB using ID 314265, not using the NFO. Delete .nfo and try adding manually again.: Connection error HTTPConnectionPool(host=u'10', port=80): Max retries exceeded with url: http://thetvdb.com/api/F9C450E78D99172E/series/314265/en.xml (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError(': Failed to establish a new connection: [Errno 22] Invalid argument',))) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/314265/en.xml

Traceback (most recent call last):                                                       
  File "/home/user/Code/SickRage/sickbeard/show_queue.py", line 324, in run          
    s = t[self.indexer_id]                                                               
  File "/home/user/Code/SickRage/lib/tvdb_api/tvdb_api.py", line 946, in __getitem__ 
    self._getShowData(key, self.config['language'], True)                                
  File "/home/user/Code/SickRage/lib/tvdb_api/tvdb_api.py", line 841, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)                             
  File "/home/user/Code/SickRage/lib/tvdb_api/tvdb_api.py", line 629, in _getetsrc   
```
I have been using SickRage for a few months and never saw this issue until this morning.

**Comment by meyersbs** [comment]
It appears that my database got corrupted. I nuked it and started over and I have no problem talking to TheTVDB now.
