### ISSUE TITLE
[APP SUBMITTED]: No module named utorrent_client

### ISSUE THREAD

**Issue by divx-guy** [SickRage/SickRage#4815]
### INFO
Python Version: **2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17692**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_8 :: [807c5ae] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 867, in testTorrent
    client = clients.getClientInstance(torrent_method)
  File "C:\SickRage\sickbeard\clients\__init__.py", line 56, in getClientInstance
    module = getClientModule(name)
  File "C:\SickRage\sickbeard\clients\__init__.py", line 52, in getClientModule
    (prefix=prefix, name=name), fromlist=_clients)
ImportError: No module named utorrent_client

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17692**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [807c5ae] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 867, in testTorrent
    client = clients.getClientInstance(torrent_method)
  File "C:\SickRage\sickbeard\clients\__init__.py", line 56, in getClientInstance
    module = getClientModule(name)
  File "C:\SickRage\sickbeard\clients\__init__.py", line 52, in getClientModule
    (prefix=prefix, name=name), fromlist=_clients)
ImportError: No module named utorrent_client

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17692**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_7 :: [807c5ae] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 867, in testTorrent
    client = clients.getClientInstance(torrent_method)
  File "C:\SickRage\sickbeard\clients\__init__.py", line 56, in getClientInstance
    module = getClientModule(name)
  File "C:\SickRage\sickbeard\clients\__init__.py", line 52, in getClientModule
    (prefix=prefix, name=name), fromlist=_clients)
ImportError: No module named utorrent_client

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17692**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [807c5ae] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 867, in testTorrent
    client = clients.getClientInstance(torrent_method)
  File "C:\SickRage\sickbeard\clients\__init__.py", line 56, in getClientInstance
    module = getClientModule(name)
  File "C:\SickRage\sickbeard\clients\__init__.py", line 52, in getClientModule
    (prefix=prefix, name=name), fromlist=_clients)
ImportError: No module named utorrent_client

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17692**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_4 :: [807c5ae] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 867, in testTorrent
    client = clients.getClientInstance(torrent_method)
  File "C:\SickRage\sickbeard\clients\__init__.py", line 56, in getClientInstance
    module = getClientModule(name)
  File "C:\SickRage\sickbeard\clients\__init__.py", line 52, in getClientModule
    (prefix=prefix, name=name), fromlist=_clients)
ImportError: No module named utorrent_client

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17692**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [807c5ae] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 867, in testTorrent
    client = clients.getClientInstance(torrent_method)
  File "C:\SickRage\sickbeard\clients\__init__.py", line 56, in getClientInstance
    module = getClientModule(name)
  File "C:\SickRage\sickbeard\clients\__init__.py", line 52, in getClientModule
    (prefix=prefix, name=name), fromlist=_clients)
ImportError: No module named utorrent_client

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
