### ISSUE TITLE
New install shows error: Error Unicode decode operation of encoding 'ascii' failed in file '/opt/sickrage/gui/slick/views/errorlogs.mako' at line: 0 char: 0

### ISSUE THREAD

**Issue by Amar444** [SickRage/SickRage#4913]
**Branch/Commit:** Master
**OS:** Raspbian GNU/Linux v9
**Browser**: Chrome
**What you did:** Clean Raspbian install and followed the tutorial : https://www.htpcguides.com/install-sickrage-raspberry-pi-usenet-torrent-tv/ to install Sickrage after the clean install
**What happened:** After installing everything, when I try to start up Sickrage and open it in the browser, the following shows up: 

**Logs:**
```
Error
Unicode decode operation of encoding 'ascii' failed in file '/opt/sickrage/gui/slick/views/errorlogs.mako' at line: 0 char: 0

Traceback
Traceback (most recent call last): 
File "/opt/sickrage/lib/tornado/web.py", line 1511, in _execute result = yield result 
File "/opt/sickrage/lib/tornado/gen.py", line 1055, in run value = future.result() 
File "/opt/sickrage/lib/tornado/concurrent.py", line 238, in result raise_exc_info(self._exc_info) 
File "/opt/sickrage/lib/tornado/gen.py", line 1063, in run yielded = self.gen.throw(*exc_info) 
File "/opt/sickrage/sickbeard/webserve.py", line 266, in get results = yield self.async_call(method) 
File "/opt/sickrage/lib/tornado/gen.py", line 1055, in run value = future.result() 
File "/opt/sickrage/lib/concurrent/futures/_base.py", line 455, in result return self.__get_result() 
File "/opt/sickrage/lib/concurrent/futures/thread.py", line 63, in run result = self.fn(*self.args, **self.kwargs) 
File "/opt/sickrage/sickbeard/webserve.py", line 288, in async_call result = function(**kwargs) 
File "/opt/sickrage/lib/tornado/web.py", line 1767, in wrapper return method(self, *args, **kwargs) 
File "/opt/sickrage/sickbeard/webserve.py", line 5259, in index t = PageTemplate(rh=self, filename="errorlogs.mako") 
File "/opt/sickrage/sickbeard/webserve.py", line 115, in __init__ self.template = lookup.get_template(filename) 
File "/opt/sickrage/lib/mako/lookup.py", line 258, in get_template return self._load(srcfile, uri) 
File "/opt/sickrage/lib/mako/lookup.py", line 323, in _load **self.template_args) 
File "/opt/sickrage/lib/mako/template.py", line 338, in __init__ module = self._compile_from_file(path, filename) 
File "/opt/sickrage/lib/mako/template.py", line 395, in _compile_from_file self.module_writer) 
File "/opt/sickrage/lib/mako/template.py", line 720, in _compile_module_file generate_magic_comment=True) 
File "/opt/sickrage/lib/mako/template.py", line 685, in _compile node = lexer.parse() 
File "/opt/sickrage/lib/mako/lexer.py", line 224, in parse self.filename) 
File "/opt/sickrage/lib/mako/lexer.py", line 215, in decode_raw_stream 0, 0, filename) 
CompileException: Unicode decode operation of encoding 'ascii' failed in file '/opt/sickrage/gui/slick/views/errorlogs.mako' at line: 0 char: 0 

Request Info
body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /errorlogs/
query_arguments: {}
_start_time: 1534407489.1
headers: Sec-Metadata: cause=user-activated, destination=document, target=top-level, site=same-origin Accept-Language: en,nl-NL;q=0.9,nl;q=0.8,en-US;q=0.7 Accept-Encoding: gzip, deflate Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8 User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36 Dnt: 1 Host: 192.168.2.16:8081 Referer: http://192.168.2.16:8081/errorlogs/ Cookie: sickrage_user="2|1:0|10:1534361342|13:sickrage_user|44:NjRiOTRlN2E5ZWQyMjE3YTk5NzY5MzkxZjEzNmJmZjk=|9e94d16b7c0d20f38b92e48570d1fa7a6f43e14bc3e446c892437ebc4d021da7" Upgrade-Insecure-Requests: 1 
host: 192.168.2.16:8081
version: HTTP/1.1
server_connection: 
host_name: 192.168.2.16
_finish_time: None
query: 
arguments: {}
path: /errorlogs/
method: GET
remote_ip: 192.168.2.13
```

What can I do to solve this?

**Comment by Amar444** [comment]
I just did the exact same instructions again, and now it works..
