### ISSUE TITLE
Update failure

### ISSUE THREAD

**Issue by janusn** [SickRage/SickRage#4956]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

SickRage Info:

- Branch: master
- Commit: ```05aea9527abd815c71993ca2b335338d6ed7e4f6```
- Database Version: 44.0
- Build: [BenjV's .SPK Sickrage package](https://github.com/BenjV/SYNO-packages/raw/master/SickRage%20DSM%206%20noarch%20V1.0.spk)

Python Version: 2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]
SSL Version: OpenSSL 1.0.2n 7 Dec 2017
OS: Linux-4.4.59+-x86_64-with-glibc2.2.5
Locale: None.None
Browser: Google Chrome Version 69.0.3497.92 (Official Build) (64-bit)

What you did: update found and sickrage do an automatic update
What happened: Update failed
What you expected: Update and restart completed successfully

Logs:
```
AA OperationalError: near "WHERE": syntax error
AA sql_results = self.connection.cursor().execute(query, args)
AA File "/volume1/@appstore/sickrage/var/sickbeard/db.py", line 141, in _execute
AA sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
AA File "/volume1/@appstore/sickrage/var/sickbeard/db.py", line 283, in action
AA self.action(query, value_dict.values() + key_dict.values())
AA File "/volume1/@appstore/sickrage/var/sickbeard/db.py", line 362, in upsert
AA main_db_con.upsert("imdb_info", self.imdb_info, controlValueDict)
AA File "/volume1/@appstore/sickrage/var/sickbeard/tv.py", line 1178, in saveToDB
AA show.saveToDB()
AA File "/volume1/@appstore/sickrage/var/sickbeard/__init__.py", line 1713, in saveAll
AA sickbeard.saveAll() # save all shows to DB
AA File "/var/packages/sickrage/target/var/SickBeard.py", line 457, in shutdown
AA self.callback(type)
AA File "/volume1/@appstore/sickrage/var/sickbeard/event_queue.py", line 46, in run
AA Traceback (most recent call last):
2018-09-14 17:21:38 ERROR EVENT-QUEUE :: [05aea95] Exception generated in thread EVENT-QUEUE: near "WHERE": syntax error
2018-09-14 17:21:38 INFO EVENT-QUEUE :: Here is the arguments that were passed to this function (This is what the developers need to know): {'fetchall': False, 'attempt': 0, 'severity': 40, 'self': , 'args': [339637], 'sql_results': [], 'query': u'UPDATE [imdb_info] SET WHERE indexer_id = ?', 'e': OperationalError('near "WHERE": syntax error',), 'fetchone': False}
2018-09-14 17:21:38 INFO EVENT-QUEUE :: If this happened in cache.db, you can safely stop SickRage, and delete the cache.db file without losing any data
AA OperationalError: near "WHERE": syntax error
AA sql_results = self.connection.cursor().execute(query, args)
AA File "/volume1/@appstore/sickrage/var/sickbeard/db.py", line 141, in _execute
AA sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
AA File "/volume1/@appstore/sickrage/var/sickbeard/db.py", line 283, in action
AA Traceback (most recent call last):
2018-09-14 17:21:38 ERROR EVENT-QUEUE :: [05aea95] Fatal error executing query with db.action in database /var/packages/sickrage/target/var/sickbeard.db: near "WHERE": syntax error
2018-09-14 17:21:35 INFO EVENT-QUEUE :: Saving all shows to the database
2018-09-14 17:21:35 INFO EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2018-09-14 17:21:35 INFO EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2018-09-14 17:21:35 INFO EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2018-09-14 17:21:35 INFO EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2018-09-14 17:21:35 INFO EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2018-09-14 17:21:35 INFO EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2018-09-14 17:21:35 INFO EVENT-QUEUE :: Waiting for the SEARCHQUEUE thread to exit
2018-09-14 17:21:35 INFO EVENT-QUEUE :: Waiting for the SHOWQUEUE thread to exit
2018-09-14 17:21:34 INFO EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2018-09-14 17:21:34 INFO EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2018-09-14 17:21:34 INFO EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2018-09-14 17:21:34 INFO EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2018-09-14 17:21:34 INFO EVENT-QUEUE :: Aborting all threads
2018-09-14 17:21:34 INFO CHECKVERSION :: Update was successful!
2018-09-14 17:21:23 INFO CHECKVERSION :: Moving files from /var/packages/sickrage/target/var/sr-update/SickRage-SickRage-05aea95 to /var/packages/sickrage/target/var
2018-09-14 17:21:23 INFO CHECKVERSION :: Deleting file /var/packages/sickrage/target/var/sr-update/sr-update.tar
2018-09-14 17:21:14 INFO CHECKVERSION :: Extracting file /var/packages/sickrage/target/var/sr-update/sr-update.tar
2018-09-14 17:20:58 INFO CHECKVERSION :: Downloading update from http://github.com/SickRage/SickRage/tarball/master
2018-09-14 17:20:58 INFO CHECKVERSION :: Creating update folder /var/packages/sickrage/target/var/sr-update before extracting
2018-09-14 17:20:54 INFO CHECKVERSION :: Config backup successful, updating...
2018-09-14 17:19:41 INFO CHECKVERSION :: Config backup in progress...
2018-09-14 17:19:18 INFO CHECKVERSION :: New update found for SickRage, starting auto-updater ...
```

**Comment by miigotu** [comment]
Should be fixed now, you will have to manually start it

**Comment by janusn** [comment]
Thanks. However, I have backed up and reinstalled as [Switching your Synology's Sickrage to the new repository](https://github.com/SickRage/SickRage/wiki/Switching-your-Synology's-Sickrage-to-the-new-repository#install-sickrage) guide now.
I can't test it this time.

**Comment by miigotu** [comment]
Thats fine, honestly it would have just started back up if you started the service again I think =P
Hoever, I did fix the exact issue it had when it tried to save the database before restarting. What had happened was imdb was either down or the information for one of the shows was not loaded yet, and then some crafty sql tried to save null information to the database, which resulted in bad SQL. So either way, I'm glad you reported this!
